### ISSUE TITLE
Network error (TransientException), entering retry loop. 

### ISSUE THREAD

**Issue by qixiong-wang** [wandb/client#1001]
* Weights and Biases version:wandb-0.8.33  
* Python version:python -3.6.5
* Operating System:Ubuntu 18

### Description
I was using wandb with Jupyter notebook, and it successfully connected to my account. But it failed to upload file.

wandb: Network error (TransientException), entering retry loop. See /home/wangqx/qixiong's/EO/wandb/debug.log for full traceback.
wandb: ERROR Error uploading "requirements.txt": CommError, None
wandb: ERROR Error uploading "config.yaml": CommError, None
wandb: ERROR Error uploading "___batch_archive_1.tgz": CommError, None

And the debug.log is empty.
![issue](https://user-images.githubusercontent.com/42293370/80325965-daadfa80-8869-11ea-90a7-813f2987f27e.png)

**Comment by cvphelps** [comment]
Hi there, is it possible this was happening on flaky internet?

**Comment by ariG23498** [comment]
Hey @qixiong-wang 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
