### ISSUE TITLE
ERROR Error while calling W&B API: permission denied (<Response [403]>)

### ISSUE THREAD

**Issue by Billy1900** [wandb/client#1003]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb-0.8.33-py2.py3-none-any.whl
* Python version: 3.7
* Operating System: Windows

### Description

When I run the tutorial.py, the error occurred, 
<pre>
wandb: ERROR Install the win32api library with `pip install pypiwin32`
wandb: Tracking run with wandb version 0.8.33
wandb: Run data is saved locally in wandb\run-20200428_013505-3df0bae9
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
wandb: ERROR Launch exception: Permission denied to access wandb/set-run-name-to-id/3df0bae9
wandb: ERROR To disable wandb syncing set WANDB_MODE=dryrun
wandb: ERROR W&B process (PID 10976) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
Traceback (most recent call last):
  File "tutorial.py", line 33, in <module>
    wandb.init(config=hyperparameter_defaults)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\wandb\__init__.py", line 1090, in init
    _init_headless(run)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\wandb\__init__.py", line 306, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log
</pre>

### What I Did

I thought there was some permission about the account, so I log in my own account, but the problem was still there.

**Comment by vanpelt** [comment]
There's likely a settings file in your directory pointing to the "wandb" project.  You can update the script to post to your own username with `wandb.init(entity="YOUR_USERNAME", project="tutorial:")`.  Where did you find `tutorial.py`?  We will update it.

**Comment by Billy1900** [comment]
ok, I have already made it.

**Comment by xmBryant24** [comment]
How did you solve this problem？
