### ISSUE TITLE
Failed to connect to W&B servers after 10 seconds "SIGWINCH handler was not None" error 

### ISSUE THREAD

**Issue by hadyelsahar** [wandb/client#1005]
```
wandb, version 0.8.33
Python 3.7.4
Linux
```

### Description
While using jupyer notebooks  I always get this message while the cell execution halts.
 
![image](https://user-images.githubusercontent.com/1453243/80497276-82aaed00-896a-11ea-9327-d8fd906a394c.png)

### What I Did

This seems not to be an connection problem since the run entry gets created in the wandb web interface.  
![image](https://user-images.githubusercontent.com/1453243/80497533-e3d2c080-896a-11ea-9757-d457d5619bcd.png)

Also when I run the same command from ipython terminal I get the following error
```
In [1]: import wandb                                                                                                                                     

In [2]: config = { 
   ...:     "steps": 25600, 
   ...:     "batch_size": 128}                                                                                                                           

In [3]: wandb.init(name='run-42', project='dpg-control', config=config)                                                                                  
<IPython.core.display.HTML object>
SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
Failed to connect to W&B servers after 10 seconds.                    Letting user process proceed while attempting to reconnect.
Out[3]: W&B Run: https://app.wandb.ai/hadyelsahar/dpg-control/runs/21vzikrq
```

**Comment by cvphelps** [comment]
Hi Hady, I was having some trouble reproducing this issue— do you have any other tips for how I can recreate this behavior?

**Comment by ariG23498** [comment]
Hey @hadyelsahar 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
