### ISSUE TITLE
Offline no chart

### ISSUE THREAD

**Issue by WHCer** [wandb/client#1007]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.34
* Python version: 3.7
* Operating System: win10 & ubuntu

### Description
run PyTorch mnist demo with the offline guild. Uploaded project contains no chart

### What I Did
```
os.environ["WANDB_MODE"] = "dryrun"  # wandb offline
wandb init
wandb sync .
```

```
No chart is shown 
```

**Comment by cvphelps** [comment]
Hi there, did the local wandb folder show up with data?

**Comment by WHCer** [comment]
Yes, It contains all files the same as the online version.
The public project running offline: https://app.wandb.ai/whcer/uncategorized/runs/28xkypdv/overview?workspace=user-whcer

The public project running online:
https://app.wandb.ai/whcer/uncategorized/runs/373u5l0c/overview?workspace=user-whcer

**Comment by RyleeThompson** [comment]
Same issue here.

**Comment by ariG23498** [comment]
Hey folks
Could you check if this issue still persists with the current version of wandb?
