### ISSUE TITLE
wandb sync --id myRun syncs other runs as well

### ISSUE THREAD

**Issue by rubenhorn** [wandb/client#1010]
* Weights and Biases version: 0.8.33
* Python version: 3.7.0
* Operating System: Windows 10 Home 64bit

When I run `wand sync --id myRun -e myUser -p myProject` I just want to upload the latest dryrun.
But it crashes with HTTP 400, because some runs have been deleted.
Why does it try to sync all runs?

**Comment by vanpelt** [comment]
`wandb sync` will sync all runs in the current directory.  If you want to sync a specific run you can run `wandb sync path_to_run_directory`

**Comment by zbpjlc** [comment]
wandb: Syncing wandb/run-20200510_013904-sicd31eq to:
wandb: floral-dawn-104 https://app.wandb.ai/zbpjlc/temporal-shift-module/runs/2a0aiv6z
is therer any bug?
