### ISSUE TITLE
Run.history(keys=list) doesn't behave as expected

### ISSUE THREAD

**Issue by kcajf** [wandb/client#1012]
`wandb --version && python --version && uname`

wandb, version 0.8.35
Python 3.7.6
Linux

### Description
I'm querying a `Run` object's history, using `run.history()`. 
With the `keys` argument set to `None`, it returns a dataframe with all the metrics as columns. When I set the `keys` argument to a list of strings, all of which are valid metric names, it returns a pandas Series of dictionaries instead. It feels like this should instead return a dataframe, just with a subset of columns. Is there a reason for the discrepancy?

**Comment by cvphelps** [comment]
Hi, thanks for flagging this. My colleague @raubitsj is working on a CLI rewrite which should clean up issues like this

**Comment by raubitsj** [comment]
This is the public api so it is independent of the CLI rewrite.

**Comment by ariG23498** [comment]
Hey @kcajf 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
