### ISSUE TITLE
Feature Request: Automatic updates

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#1014]
wandb, version 0.8.35
Python 3.8.2
Linux

### Description

wandb already informs about a new library version, you update wandb very often (that's great, thank you for that!), how about you add the possibility that on new version detected you just update?
Of course add an option to turn it off, or only for minor version, so that nothing breaks. Thank you!

**Comment by vanpelt** [comment]
This is a little tricky as certain environments will need sudo access to install the library.  I've never seen any other libraries do this, do you have any examples in mind?  For the `gcloud` CLI for instance they provide a command `gcloud components update` command.  What's the specific issue you're trying to address with auto-upgrades?

**Comment by dreamflasher** [comment]
The specific issue is the one I describe above: At least once a week you recommend upgrade the software, so I figured it would be nice if it could do that itself. Might be difficult with python packages, but there's a lot of software out there with auto-updaters.

**Comment by ariG23498** [comment]
Hey @dreamflasher 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
