### ISSUE TITLE
[Feedback/Error] JSON serialisation issue when trying to log a metric of variable type set

### ISSUE THREAD

**Issue by neomatrix369** [wandb/client#1015]
* Weights and Biases version: 0.8.32
* Python version: 3.7.2
* Operating System: Linux/MacOS

### Description

I was logging a variable/value that is of type `set` this caused JSON serialisation issues, similar to the error reported here https://stackoverflow.com/questions/8230315/how-to-json-serialize-sets (JSON serialisation failing when handling data with set data types).

Although the way `python` reported the error (low-level call stack information), it wasn't clear if it was caused by `wandb` coming from my code. I looked to look at it closer, googled and then looked at my last commit change lead me to the solution.

### What I Did

```
a = {'a', 'b', 'c'}
wandb.log({'metric': a})
```
Removing the line of code that logged the metric, resolved the issue. I then converted variable to a `list` and that worked fine.

I would suggest if we try to log an unsupported data-type, that warnings be reported during logging not when synchronising with remote. Also maybe some sort of error handling be introduced around conversions, so if they fail the user gets a call stack.

**Comment by cvphelps** [comment]
Hi, thanks for reporting this issue, @raubitsj is working on a good CLI rewrite that should improve error messages like this one

**Comment by neomatrix369** [comment]
> Hi, thanks for reporting this issue, @raubitsj is working on a good CLI rewrite that should improve error messages like this one

Thanks for the response, and great to hear about the re-write, looking forward to it. A re-write is always good, I like Fred George's practise about re-writing it multiple times.

**Comment by neomatrix369** [comment]
@cvphelps can this issue be marked as a bug pls thnx

**Comment by raubitsj** [comment]
As of cling 0.0.22, an exception is thrown that sets are not handled:
```
"/Users/jeff/.pyenv/versions/3.6.10/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
```

**Comment by neomatrix369** [comment]
One small feedback on this one functionality, when running in non-verbose mode it's best to only show a small section of the stack trace and hide the rest with the message "See full trace in wandb's debug.logs. While in verbose mode it's okay to show the whole stack trace and log it.

**Comment by neomatrix369** [comment]
Can we close this issue now, since it's ready for the next release when the CLI tool will be released?

**Comment by neomatrix369** [comment]
@raubitsj I found another one to do with passing a lambda function as key:value pair i.e. `{'value': lambda: some_function()}`. Would it also report the error in the same fashion as above?

What would also help, if it mentioned the name of the key(s) where there are conversion issues.

**Comment by ariG23498** [comment]
Hey @neomatrix369 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by neomatrix369** [comment]
> Hey @neomatrix369
> In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

Thanks for letting me know, I trust the raised issue is fixed in the newer version, I haven't played with it yet look forward to it.
