### ISSUE TITLE
Manual wandb sync opens manifest.json and does not sync

### ISSUE THREAD

**Issue by bknyaz** [wandb/client#1025]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.35
* Python version: 3.6.8 :: Anaconda, Inc.
* Operating System: Linux

### Description

I'm trying to manually sync the project, because for some reasons it does not sync it automatically.
I run `wandb sync path_to_the_project`, then in my terminal I see this window (attached), which I can't exit or do anything with it.
I've done it before using older versions and it worked fine.

![image](https://user-images.githubusercontent.com/3225366/81436780-09fd1b00-9138-11ea-811b-3cf874d14cdf.png)

### What I Did

```
wandb sync wandb/run-some-project
```

**Comment by vanpelt** [comment]
Your machine likely isn't logged in to wandb so it's taking you through the auth flow and your terminal is configured to use the lynx browser.  Goto your settings page at https://app.wandb.ai/settings and copy an api key.  Then run `wandb login YOUR_API_KEY`.  After this wandb sync should work properly.

**Comment by bknyaz** [comment]
Thanks, I already tried that, but it didn't help. Then I removed .netrc and logged in again and it helped. Perhaps, somehow my .netrc got corrupted.
