### ISSUE TITLE
Silent mode not working!

### ISSUE THREAD

**Issue by cduguet** [wandb/client#1026]
* Weights and Biases version: 0.8.35
* Python version: Python 3.6.10 :: Anaconda, Inc.
* Operating System: Linux

### Description
Doing the despite enabling silent mode I'm still getting log messages in jupyter lab. 

### What I Did

![image](https://user-images.githubusercontent.com/1536515/81481947-e1f2e200-9233-11ea-93ff-6c261f91ffe5.png)

**Comment by vanpelt** [comment]
Hey @cduguet we're working on an overhaul of the library that will fix these output issues once and for all.  Until then, the following should turn them off in jupyter:

```python
import logging
logger = logging.getLogger("wandb")
logger.setLevel(logging.WARNING)
```

**Comment by cduguet** [comment]
thank you!!

**Comment by andyljones** [comment]
@vanpelt 's advice silences the log messages, but not the 'Logging results to' lines. For that you have to install PR #1495, a la

```
pip install git+https://github.com/wandb/client.git@bugfix/CLI622-jupyter_obey_wandb_silent --upgrade
```

Hopefully it'll make its way into the release soon! Anyway, with this codebase,  

```python
%env WANDB_SILENT=true
```
```python
import wandb
wandb.init(name='first', project='wandb-test');
```

is mercifully, finally silent.
