### ISSUE TITLE
Compatibility issue with python 3.7 on ubuntu

### ISSUE THREAD

**Issue by w2sv** [wandb/client#1027]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.35
* Python version: 3.7.6
* Operating System: Ubuntu 18.04

### Description

After mounting wandb into my conda environment by means of a pip install the package seems to be improperly installed, leading to neither the login, nor a package import to work due to an alleged missing of gql, although it was confirmedly installed alongside with wandb.
I noticed that everything works fine if I either switch to python 3.6 on the exact same Ubuntu machine or to one running on Windows, then again installed for python 3.7, suggesting that the problem is in fact caused by this particular combination of python version and OS. 

### What I Did

`(base) janek@w2sv:~$ pip install wandb

Collecting wandb
  Using cached wandb-0.8.35-py2.py3-none-any.whl (1.4 MB)
Requirement already satisfied: PyYAML>=3.10 in ./.local/lib/python3.7/site-packages (from wandb) (5.3)
Collecting GitPython>=1.0.0
  Using cached GitPython-3.1.2-py3-none-any.whl (451 kB)
Processing ./.cache/pip/wheels/bc/ed/6c/028dea90d31b359cd2a7c8b0da4db80e41d24a59614154072e/watchdog-0.10.2-cp37-none-any.whl
Collecting configparser>=3.8.1
  Using cached configparser-5.0.0-py3-none-any.whl (22 kB)
Requirement already satisfied: requests>=2.0.0 in ./miniconda3/lib/python3.7/site-packages (from wandb) (2.23.0)
Collecting docker-pycreds>=0.4.0
  Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Requirement already satisfied: six>=1.10.0 in ./miniconda3/lib/python3.7/site-packages (from wandb) (1.14.0)
Requirement already satisfied: psutil>=5.0.0 in ./miniconda3/lib/python3.7/site-packages (from wandb) (5.7.0)
Processing ./.cache/pip/wheels/e4/1d/06/640c93f5270d67d0247f30be91f232700d19023f9e66d735c7/nvidia_ml_py3-7.352.0-cp37-none-any.whl
Processing ./.cache/pip/wheels/ce/0e/7b/58a8a5268655b3ad74feef5aa97946f0addafb3cbb6bd2da23/gql-0.2.0-cp37-none-any.whl
Collecting shortuuid>=0.5.0
  Using cached shortuuid-1.0.1-py3-none-any.whl (7.5 kB)
Requirement already satisfied: python-dateutil>=2.6.1 in ./miniconda3/lib/python3.7/site-packages (from wandb) (2.8.1)
Collecting sentry-sdk>=0.4.0
  Using cached sentry_sdk-0.14.3-py2.py3-none-any.whl (103 kB)
Processing ./.cache/pip/wheels/68/39/1a/5e402bdfdf004af1786c8b853fd92f8c4a04f22aad179654d1/subprocess32-3.5.4-cp37-none-any.whl
Collecting Click>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.5-py3-none-any.whl (63 kB)
Processing ./.cache/pip/wheels/0b/04/79/c3b0c3a0266a3cb4376da31e5bfe8bba0c489246968a68e843/pathtools-0.1.2-cp37-none-any.whl
Requirement already satisfied: chardet<4,>=3.0.2 in ./miniconda3/lib/python3.7/site-packages (from requests>=2.0.0->wandb) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/lib/python3.7/site-packages (from requests>=2.0.0->wandb) (2020.4.5.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./miniconda3/lib/python3.7/site-packages (from requests>=2.0.0->wandb) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in ./miniconda3/lib/python3.7/site-packages (from requests>=2.0.0->wandb) (2.9)
Processing ./.cache/pip/wheels/19/49/34/c3c1e78bcb954c49e5ec0d31784fe63d14d427f316b12fbde9/promise-2.3-cp37-none-any.whl
Processing ./.cache/pip/wheels/45/99/d7/c424029bb0fe910c63b68dbf2aa20d3283d023042521bcd7d5/graphql_core-1.1-cp37-none-any.whl
Collecting smmap<4,>=3.0.1
  Using cached smmap-3.0.4-py2.py3-none-any.whl (25 kB)
Installing collected packages: smmap, gitdb, GitPython, pathtools, watchdog, configparser, docker-pycreds, nvidia-ml-py3, promise, graphql-core, gql, shortuuid, sentry-sdk, subprocess32, Click, wandb
Successfully installed Click-7.1.2 GitPython-3.1.2 configparser-5.0.0 docker-pycreds-0.4.0 gitdb-4.0.5 gql-0.2.0 graphql-core-1.1 nvidia-ml-py3-7.352.0 pathtools-0.1.2 promise-2.3 sentry-sdk-0.14.3 shortuuid-1.0.1 smmap-3.0.4 subprocess32-3.5.4 wandb-0.8.35 watchdog-0.10.2

(base) janek@w2sv:~$ wandb login

Traceback (most recent call last):
  File "/home/janek/miniconda3/bin/wandb", line 5, in <module>
    from wandb.cli import cli
  File "/home/janek/miniconda3/lib/python3.7/site-packages/wandb/__init__.py", line 45, in <module>
    from wandb.apis import InternalApi, PublicApi, CommError
  File "/home/janek/miniconda3/lib/python3.7/site-packages/wandb/apis/__init__.py", line 7, in <module>
    from gql.client import RetryError
ModuleNotFoundError: No module named 'gql'`

**Comment by vanpelt** [comment]
This looks like an issue with your virtual environment.  Some packages are in `./.local/lib/python3.7/site-packages` while others are in `/home/janek/miniconda3/lib/python3.7/site-packages/`.  How are you activating the miniconda environment?  I would try blowing away the `./local/lib/python3.7` directory and re-installing.  I've verified the install works on a fresh ubuntu 18.4 install with:

`docker run -e LANG=C.UTF-8 -it ubuntu:18.04 bash -c "apt update; apt install -y python3-pip; pip3 install wandb; wandb login"`

The other thing to try would be `pip install gql==0.2.0`.  You can see where a package resides from a python REPL with:

```
import wandb
print(wandb.__path__)
```

That same site-packages directory should contain the dependency libs.

**Comment by w2sv** [comment]
Removing both the cached pip wheels located under `~/janek/.cache/pip/wheels`
and the  `~/.local/lib/python3.7/site-packages` dir into a re-installation did the job for me, thank you for your help.
