### ISSUE TITLE
Multiple runs in notebook cells are not properly synced (wrong "state" for all but last)

### ISSUE THREAD

**Issue by chrka** [wandb/client#1033]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: Python 3.6.9 :: Anaconda, Inc.
* Operating System: Linux (Ubuntu 18.04) and macOS (10.15.4)

### Description

I'm trying to execute several runs from a single cell in a Jupyter Notebook (for example, doing cross-validation with each split as a separate run.)

All runs execute and their results are logged, however, only the last run shows up as being `finished` — all earlier runs still show as `running` (until they are registered as `crashed` some time later).

I would expect all successfully completed runs to have state `finished`.

(When running from a script, everything works fine.)

### What I Did

A small example to illustrate the problem:

```
import wandb
import time

for i in range(10):
    with wandb.init(project="sandbox", name=f"wandb-test-{i + 1}", reinit=True) as run:
        run.summary['accuracy'] = (i + 1) / 10
        time.sleep(5)
```

Running this in a notebook cell results in the last run ("wandb-test-10") having state `finished`, but runs "wandb-test-1" through "wandb-test-9" still show up as `running`.

If instead the same code is run outside of a notebook in a separate script, all runs are correctly registered as being `finished`.

**Comment by tyomhak** [comment]
Hi. Thank you for the feedback, we will make sure to take a look at the issue.

**Comment by SamPruden** [comment]
I'm seeing something similar, but I'm just trying wandb for the first time and may be doing something wrong.

I'm running multiple runs in a loop, something like:
```Python3
for _ in range(10):
    run = wandb.init(reinit = True, project = "Meta-Q", name = setup.get_name())
    # Loop through epochs, calling wandb.log() in each
    wandb.join()
```

Only the last run gets marked as finished. I've tried replacing the init with `with wandb.init(reinit = True, project = "Meta-Q", name = setup.get_name()) as run:` but the behaviour seems identical. From my experimentation, `wand.join()` doesn't seem to change the behaviour at all.

These are very short lasting runs with durations of around 10 seconds each. Here's a screenshot of my training dashboard from playing around with this. Note how those runs got launched in quick succession and only the last run in each group is marked as finished and the others have long runtimes.

![image](https://user-images.githubusercontent.com/19550501/82668535-c921fd80-9c31-11ea-876e-55e460fd5182.png)


I can't find clear documentation on how a run's lifetime is managed. My code is compliant with the instructions here. https://docs.wandb.com/library/init#how-do-i-launch-multiple-runs-from-one-script

```
wandb, version 0.8.36
Python 3.6.9
Linux
```

My environment is Google Colab.

**Comment by lcannell** [comment]
I have the same identical issue as SamPruden...any update on this?

**Comment by tyomhak** [comment]
This is a bug, that we're working on. Running the same code in a script through a cmd should work just fine, but there seems to be an issue with running experiments in a loop in a notebook. Sorry for the inconvenience.

Also, I would suggest upgrading your wandb. The latest version is 0.9.3

**Comment by ariG23498** [comment]
Hey folks in the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing some stale issues. Please comment to reopen.
