### ISSUE TITLE
Interdependent hyperparameters in sweeps

### ISSUE THREAD

**Issue by mojesty** [wandb/client#1034]
`wandb --version && python --version && uname`

wandb, version 0.8.35
Python 3.7.6
Linux

### Description
I have an experiment where some config parameters control presense / absense of other hyperparameters. The simplest case is when we have "flag" parameter that controls what kind of layer we use, and hyperparameter set for each layer is different, e. g. num_channels and num_filters for CNN, input_size and hidden_size for RNN, etc.

So I have config variations like
```
"model.encoder.type": "cnn",
"model.encoder.input_channels": 32,
"model.encoder.stride": 2,
"model.encoder.hidden_size": 32
```
and

```
"model.encoder.type": "rnn",
"model.encoder.input_dim": 32,
"model.encoder.num_layers": 2,
"model.encoder.hidden_dim": 32
```

so depending on "type" parameter, different sets of hyperparameters are required. 
I want to use sweeps to search over such hyperparameters space, and I would like to understand 
what hyperparameter search strategy should I use to take these dependencies into account?

**Comment by tyomhak** [comment]
Hello! thanks for the question!
@raubitsj could you please take a look?

**Comment by cvphelps** [comment]
Thanks, this is definitely a good feature request that we're tracking as part of sweeps.

**Comment by ariG23498** [comment]
Hey @mojesty 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
