### ISSUE TITLE
Segmentation Mask Tracker

### ISSUE THREAD

**Issue by bluesky314** [wandb/client#1035]
* Weights and Biases version: 0.8.36
* Python version: 3.6
* Operating System: Linux

### Description

Am having a really hard time getting segmentation view to work like in the image. I want to track a paticular image as my network trains and see its changing mask. It is shown in https://t.co/1VzIVSA4yf?amp=1. See image:
![Screen Shot 2020-05-14 at 4 48 17 PM](https://user-images.githubusercontent.com/35393972/81934128-0e2fa980-960c-11ea-9cf6-f74060304194.png)

### What I Did

'a' is a binary mask and 'img' rgb image
```
class_labels = {0: "Background",1: "Human"}
wandb.log({'TTTESSTT ': wandb.Image( img,  masks={ "prediction" : {"mask_data" : a, "class_labels" : class_labels}, "ground truth" : {"mask_data" : a, "class_labels" : class_labels }}) })

```
I get:
<img width="1426" alt="Screen Shot 2020-05-14 at 5 57 04 PM" src="https://user-images.githubusercontent.com/35393972/81934317-68306f00-960c-11ea-8d05-0fc1738dee35.png">

The rgb image shows but mask and ground truth is blank. There is no step counter like in the original image as well. How can I get what I wanted?

**Comment by nbardy** [comment]
Hey @bluesky314 

Could you provide a link to the run you are having issues with?

You can click the gear in the top right to access the image slider.

**Comment by ariG23498** [comment]
Hey @bluesky314 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
