### ISSUE TITLE
wandb-cli pull command crashes if entity is not specified with wrong error message

### ISSUE THREAD

**Issue by umgupta** [wandb/client#1039]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: 3.6.9
* Operating System: Linux

### Description

Trying to download run files using `wandb pull` command

### What I Did

`
wandb pull <run_id> -p <project-name> 
`

GIves error `Error: 'NoneType' object is not subscriptable`

Note that I did not specify the entity option. The error message does not say that.

**Comment by cvphelps** [comment]
Hi there Umang, if you run `wandb init` in the directory you won't need to specify your entity.

**Comment by umgupta** [comment]
Yes, but it would be nice to print the right error message. 

I also have a small request to make this command more flexible. I keep pulling into a directory and then have to move to another directory for proper organization. It would be nice to let user specify a folder and pull into that folder?

**Comment by ariG23498** [comment]
Hey @umgupta 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
