### ISSUE TITLE
Better visualization of histograms

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#1045]
Not wandb client related, but the website itself (is there an issue tracker for that?)

### Description

I'd like to visualize histograms. In your UI it's not possible to see much. The color idea across epochs is nice, but I'd appreciate to see more variants to pick the one that works best for the particular case. 
Tensorboard does that very nicely: https://jhui.github.io/2017/03/12/TensorBoard-visualize-your-learning/
An alternative could be to have a slider across epochs, like tensorboard does for images:
https://stackoverflow.com/questions/51163871/tensorboard-image-summaries

**Comment by tyomhak** [comment]
Thank you for the feedback! We will add these as feature requests and take an in depth look at them!

**Comment by cvphelps** [comment]
Hi there, could you tell me a little more about why you like the tensorboard style? If you hover over our histograms it will show the underlying distribution cross section in a tooltip.

**Comment by dreamflasher** [comment]
I find the tensorboard style easier to understand/interpret. With the blue color scheme it's unclear what the maximum is. Maybe a Black → White grading would be easier to read. The hover histograms are too small to see anything, if they would replace/overlay the whole image and have axis titles I think that would work nicely! Then one can move the mouse pointer from left to right and see a development over time with the mouse pointer. Also currently the histogram hovers land on random places for me (overlaying other graphs, Firefox latest version)

**Comment by ariG23498** [comment]
Hey @dreamflasher 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
