### ISSUE TITLE
Should I commit wandb files?

### ISSUE THREAD

**Issue by free-soellingeraj** [wandb/client#1046]
`wandb --version && python --version && uname`

wandb, version 0.8.36
Python 3.6.9 :: Anaconda, Inc.
Linux

### Description

This is a documentation request.  Or maybe just point me to docs.

Is it best practices to commit the wandb files?  What are the options for these files? 

<img width="486" alt="Screen Shot 2020-05-19 at 10 40 05 AM" src="https://user-images.githubusercontent.com/44525375/82305643-32013f80-99be-11ea-81b5-5c9a2045e808.png">

**Comment by vanpelt** [comment]
Hey @free-soellingeraj you should not be committing them.  You can commit a settings file.  If you call `wandb init` in your nbs/dll directory we'll add a ".gitignore" for you.  If you want to write one yourself you can add the following to `nbs/dll/wandb/.gitignore`:

```
*
!settings
```

**Comment by cpoptic** [comment]
I just added `wandb/` to my `.gitignore` file and that worked fine.   The wandb run folders can get numerous and large, so I'd think best practice is to not include them in your commits.
