### ISSUE TITLE
Add option for blocking wandb.save() call to immediately save

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#1047]
wandb, version 0.8.36
Python 3.8.2
Linux

### Description

I am trying to save a file with `wandb.save(filename)`. I am deleting the file after calling `wandb.save()`. Unfortunately, this leads to wandb not saving the file, because it does lazy saving/uploading. I need to delete the file, so it's not an option to keep the file around. 

Thus it would be great if you add an option to call save that makes sure after returning the file is uploaded, or expose a `wandb.sync()` function that triggers a sync (push metrics to wandb, upload files, etc.) and returns when the sync is finished.

**Comment by dreamflasher** [comment]
Workaround I found:

```
wandb.init(id=wandb_id, reinit=True, resume="allow")
wandb.save(filename)
wandb.join()
wandb.init(id=wandb_id, reinit=True, resume="allow")
```

**Comment by raubitsj** [comment]
That is a creative workaround,  I would like the blocking behavior to be the default,  I think it is already working this way in the experimental library.  We will verify this and close this when the experimental library is released as the standard library.

**Comment by ariG23498** [comment]
Hey @dreamflasher 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
