### ISSUE TITLE
wandb: Network Error when running and the charts page remains empty

### ISSUE THREAD

**Issue by ky66111** [wandb/client#1048]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: 3.6.9
* Operating System: Linux

### Description
I have encountered several problems at the same time:
1. During running my python script, wandb keeps drop out error
`wandb: Network error resolved after 0:00:15.405201, resuming normal operation.`
And the script still continues running.

2. The charts page remains empty although I log the result with 
`wandb.log({'train_loss':xxx, 'test_loss':xxx, 'epoch':xxx})`

3. I guess the reason may be that my server is behind the proxy.
So I have set env variables:
```
HTTPS_PROXY=proxy_url
HTTP_PROXY=proxy_url
```
but it doesn't work for this case.

Could anyone help me? Thanks so much

**Comment by tyomhak** [comment]
Hi, we're looking into this. Sorry for the delay.

**Comment by ky66111** [comment]
Hi, I found the run somehow works and normally prints charts. Maybe the internet connection issue. Thanks a lot!
