### ISSUE TITLE
File download should not auto-open as text file

### ISSUE THREAD

**Issue by rmrao** [wandb/client#1050]
Right now, the file download API automatically opens the downloaded file in read-only mode (see [here](https://github.com/wandb/client/blob/eb8dd5c56d88454d443102d871d81cc6b5992f52/wandb/apis/public.py#L1202)). It would be better to return the filename (instead of opening a potentially unnecessary file descriptor) or to at least allow the user to specify the open mode (e.g. if I have saved a model file, I should be able to open it in read-binary mode).

**Comment by cvphelps** [comment]
Thanks for the feedback. We're going to be releasing Artifacts soon which will be the new preferred way to handle files and will not return open files. If you call .name on the file object we return, you can open it in any mode you want.

**Comment by ariG23498** [comment]
Hey @rmrao 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
