### ISSUE TITLE
request for alternative argparse format in sweep

### ISSUE THREAD

**Issue by kengz** [wandb/client#1052]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb, version 0.8.36
* Python version: Python 3.8.2
* Operating System: Darwin

### Description

Sweep config file will format the hyperparams into the form of `--foo=bar` [doc here](https://docs.wandb.com/sweeps/configuration) and [code responsible](https://github.com/wandb/client/blob/6a0b23dc3f07f61267757c3cc5d5d2100b14d3f5/wandb/wandb_agent.py#L306).

When using with Facebook's config library Hydra, this becomes an issue as no argparse is allowed, i.e. no `--foo=bar` ([see here](https://hydra.cc/docs/tutorial/simple_cli)). For instance, when wandb agent runs a command: `python train.py --lr=0.02` this breaks the code that uses it; instead it needs the command to be `python train.py lr=0.02`, then Hydra will pick it up.

Is it possible to allow for usage without the prefix `--`? This would enable very nice pairing with Hydra to manage complex configurations while still allowing sweep to work. Plus, Hydra is getting quite popular and is used with Ax and PyTorch Lightning.

Thanks.

**Comment by vanpelt** [comment]
Hey @kengz you can [customize](https://docs.wandb.com/sweeps/configuration#command) how your program is called and optionally omitting arguments.  In this examples args is still prepended with "--", we should expose the ability to change the prefix in this config so I'll keep this ticket open.  In the meantime you can have the sweep execute a wrapper script that modifies the parameters before calling your script:

```python
import sys
import os

args = sys.argv[1:]
bare = [a.replace("--", "") for a in args]
os.system(f"python train.py {' '.join(bare)}")
```

**Comment by kengz** [comment]
This works in the meantime, thanks! Will keep an eye out for the support.

**Comment by varun19299** [comment]
@vanpelt Hydra also supports hyper-param sweeps through AxSweeper and Nevergrad. 

Would it be possible to extend W&B to support usage of external sweep tools in the panel?

**Comment by raubitsj** [comment]
We have added alternative command line parsing and documented it here:
```

**Comment by raubitsj** [comment]
@varun19299 , I am closing this issue, we do have some plans to integrate with other sweep tools in the future.   If you want to make a new feature request we can track your request.
