### ISSUE TITLE
Load config.json before syncing the run

### ISSUE THREAD

**Issue by umgupta** [wandb/client#1057]
https://github.com/wandb/client/blob/eb8dd5c56d88454d443102d871d81cc6b5992f52/wandb/wandb_run.py#L354

Currently syncing a run that has `config.json` gives the following error. The issue is due to the `user_config` variable being a file name instead of JSON dict in the referenced code. It needs to be loaded before calling `.items`
```
  File "/root/.local/lib/python3.6/site-packages/wandb/cli.py", line 447, in sync
    path, run_id=id, project=project, entity=entity, ignore_globs=globs)
  File "/root/.local/lib/python3.6/site-packages/wandb/wandb_run.py", line 355, in from_directory
    for k, v in six.iteritems(user_config)}
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 587, in iteritems
    return iter(d.items(**kw))
AttributeError: 'str' object has no attribute 'items'
```

**Comment by cvphelps** [comment]
Thanks for this bug report, we'll work on a fix for the next release

**Comment by ariG23498** [comment]
Hey @umgupta 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
