### ISSUE TITLE
early stopping envelope seem to have no effect

### ISSUE THREAD

**Issue by evfro** [wandb/client#1058]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: 3.8.2
* Operating System: Ubuntu 18.04.3 LTS

### Description
We have configured wandb to perform early stoppin. However, even after 80 runs nothing was early-stopped.

### What I Did
Our config file `config.yml` contains the following lines:
```yaml
early_terminate:
  type: envelope
method: bayes
```
It seem to have no effect on runs. Is it supported? If yes, how can we check/ensure early-stopping works properly?

Thanks!

**Comment by cvphelps** [comment]
For early stopping, you need to specify a metric that you're logging to wandb.
https://docs.wandb.com/sweeps/configuration#stopping-criteria

**Comment by evfro** [comment]
We do have metric specified in the configuration.

Unfortunately, the links you provided describe only Hyperband early-stopping algorithm. I can't find any text on how it is connected to the Envelope early-stopping. Could you please elaborate more on it? 

Also there's no information on which parameters does envelope algorithm take as input, could you also provide it with examples how to set them?

**Comment by ariG23498** [comment]
Hey @evfro 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
