### ISSUE TITLE
wandb on/off does not seem to change WANDB_MODE

### ISSUE THREAD

**Issue by samarth4149** [wandb/client#1060]
`wandb --version && python --version && uname`

* Weights and Biases version : 0.8.36
* Python version : 3.7.4
* Operating System : Ubuntu 16.04

### Description

wandb on/off not working.

### What I Did
I noticed wandb on/off was not working so I tried setting the environment variable 'WANDB_MODE' manually and found that it worked as expected. Then I tried using 'wandb on/off' and found that it had no effect on the environment variable (See output below). 
Installations were made inside a conda environment, if that matters.

```
$ wandb off
W&B disabled, running your script from this directory will only write metadata locally.
$ echo $WANDB_MODE
run
$ wandb on
W&B enabled, running your script from this directory will now sync to the cloud.
$ echo $WANDB_MODE
run
$ wandb off
W&B disabled, running your script from this directory will only write metadata locally.
$ echo $WANDB_MODE

```

**Comment by vanpelt** [comment]
Hey @samarth4149 `wandb off` updates the file `wandb/settings` relative to where it's run.  The library automatically reads this file.  You can always set the WANDB_MODE environment variable manually to set the run mode.
