### ISSUE TITLE
When stopping or restarting a run with PyCharm, shell refuses to close

### ISSUE THREAD

**Issue by ShaneSmiskol** [wandb/client#1062]
* Weights and Biases version: 0.8.36
* Python version: Python 3.7.5
* Operating System: CYGWIN_NT-10.0

### Description

There's no real error, but it's an annoying issue I run into when I use wandb with PyCharm all the time. When I'm done with a run that I don't care about, or don't need the run synced (or I forget I'm using wandb with this issue and just restart anyway), if I click the restart or stop button for the Python shell in PyCharm I get this error:

`ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`
(full exception: https://pastebin.com/0weX5Lh7)

It wouldn't be a huge issue except when this occurs I cannot stop or restart the Python shell within PyCharm, it remains open in PyCharm, stuck like that. So when I want to start training, there's a Python process that's taking up system and GPU RAM because it refuses to shut down from PyCharm. I end up having to use Task Manager to shut down all the Python processes because 3 or 4 accumulate after a while, but PyCharm restarts Python processes stopped by Task Manager, so they all restart at once.

### What I Did

Use the stop or restart buttons in PyCharm to restart the current run without issuing a Keyboard Interrupt and waiting for it to sync.
![Screenshot_614](https://user-images.githubusercontent.com/25857203/82745781-d7fdd280-9d4d-11ea-8106-3267fadb2284.png)

### Ideal Behavior

What would be great is for wandb to ignore any errors about not syncing a run if the user shuts down the Python shell manually and to let the shell stop fully.

**Comment by cvphelps** [comment]
ccing @raubitsj — we're working on a new beta of the Weights & Biases client that improves support for environments like Windows. Would you be interested in giving it a try? 

1. [Join the Slack forum](http://bit.ly/wandb-forum) and go to the wandb-cling channel.
2. [Install CLI-NG](https://github.com/wandb/client-ng) following directions from the GitHub repo.
3. Try tracking a model with the new client, no code changes necessary.

Message us in the wandb-cling channel— we’d love to hear any questions or feedback.

**Comment by ShaneSmiskol** [comment]
Excellent! `wandb-ng` works as expected within PyCharm compared to the normal build. It takes a few seconds to restart or stop once I press either button, but I'm guessing it's syncing the run in the background and waiting for it to complete. Much nicer response than not allowing me to close the shell at all and throwing an error. Thanks!

**Comment by ariG23498** [comment]
Hey @ShaneSmiskol 
We are closing this issue due to the inactivity of the thread. Please feel free to open it if the issue persists :smile:
