### ISSUE TITLE
Is it possible to have two runs concurrently in one script?

### ISSUE THREAD

**Issue by seungjaeryanlee** [wandb/client#1063]
### Description

I want to have two runs from two projects in one script. Is this supported, or do you have any viable alternatives for this?

This is different from [this commonly asked question](https://docs.wandb.com/library/init#how-do-i-launch-multiple-runs-from-one-script) in that I also want another run outside the loop.

### What I Did

```python
meta_run = wandb.init(project="meta")

for ... # Meta loop
    individual_run= wandb.init(project="individual")
    for ... # Training loop
        individual_run.log(...)
    individual_run.join()
    meta_run.log()
```

**Comment by vanpelt** [comment]
It's not currently possible.  Only one run can be tracked concurrently in a single process.  Is it possible to run the meta loop in a separate process?  Can you provide more details around your specific usecase?

**Comment by seungjaeryanlee** [comment]
I am trying to reproduce [double descent](https://arxiv.org/abs/1812.11118). For example, In Figure 9, they plot the test loss (y-axis) with the number of hidden units (x-axis). This corresponds to the meta loop. I also want to plot the test loss with the epoch for each number of hidden units, which is the training loop.

I am not too familiar with subprocesses, so I don't know how I could run it on a separate process.

**Comment by cvphelps** [comment]
In this case you should be able to log all metrics in the same run.  If you add your hidden units to your calls to wandb.log you'll be able to choose that as an x-axis in the UI and plot your test loss against it.

**Comment by seungjaeryanlee** [comment]
@cvphelps, like this?
```python3
import random
import wandb

wandb.init(project="delete-this")

for n_units in [1, 2, 3]:
    for epoch_i in [1, 2, 3, 4, 5]:
        wandb.log({"train/loss": epoch_i * 100 - random.randint(-10, 10)})
        wandb.log({"valid/loss": epoch_i * 100 - random.randint(-20, 20)})
    
    wandb.log({
        "n_units": n_units,
        "test/loss": n_units * 10 - random.randint(-5, 5),
    })
```

This solution does not work for me since I can't plot the individual runs separately. These are the plots I get:

![image](https://user-images.githubusercontent.com/6107926/83098037-80ac8900-a0e4-11ea-84ec-068d424700d7.png)

Is there a way to plot each individual run separately? 

By the way, thank you for your swift responses! You are awesome 😄

**Comment by vanpelt** [comment]
@seungjaeryanlee if your n_units actually correspond to different models you can start 3 different runs:

```python
import random
import wandb

for n_units in [1, 2, 3]:
    wandb.init(project="delete-this", config={"n_units": n_units}, reinit=True)
    for epoch_i in [1, 2, 3, 4, 5]:
        wandb.log({"train/loss": epoch_i * 100 - random.randint(-10, 10)}, step=epoch_i)
        wandb.log({"valid/loss": epoch_i * 100 - random.randint(-20, 20)}, step=epoch_i)
    wandb.log({
        "test/loss": n_units * 10 - random.randint(-5, 5),
    })
```

**Comment by neomatrix369** [comment]
@seungjaeryanlee thanks for asking this question.

@vanpelt I have question around the same realm as the above,  I was wondering how would we do multiple models in one run? I'll can make sure the metric names are unique and model-specific (model name in their prefix). 

Would something like work?

```python
wandb.init(project="xxxx", ...rest of param...)
iterate {
    build models
    wandb.log({'<model_name>.<params>': <value> })
    wandb.log({'<model_name>.<metric_name>': <value>})
}
wandb.sync()
```

**Comment by vanpelt** [comment]
@neomatrix369 that would work, you would likely want to align the metrics on steps by passing the `step` keyword to your log calls.  You can also log nested dictionaries:

`wandb.log({'model_1": {"loss": 1, "acc": 1}, "model_2": {"loss": 2, "acc": 2}}, step=epoch)`

There's no `sync` method.  If you call `wandb.init` multiple times in the same process you may want to call `wandb.join` but we automatically call it when you specify `reinit=True` in your calls to `wandb.init`.

**Comment by neomatrix369** [comment]
> @neomatrix369 that would work, you would likely want to align the metrics on steps by passing the `step` keyword to your log calls. You can also log nested dictionaries:
> 
> `wandb.log({'model_1": {"loss": 1, "acc": 1}, "model_2": {"loss": 2, "acc": 2}}, step=epoch)`
> 
> There's no `sync` method. If you call `wandb.init` multiple times in the same process you may want to call `wandb.join` but we automatically call it when you specify `reinit=True` in your calls to `wandb.init`.

Thanks that helps a lot.

PS: I meant `wandb.join` thnx for confirming

**Comment by seungjaeryanlee** [comment]
> @seungjaeryanlee if your n_units actually correspond to different models you can start 3 different runs:
> 
> ```python
> import random
> import wandb
> 
> for n_units in [1, 2, 3]:
>     wandb.init(project="delete-this", config={"n_units": n_units}, reinit=True)
>     for epoch_i in [1, 2, 3, 4, 5]:
>         wandb.log({"train/loss": epoch_i * 100 - random.randint(-10, 10)}, step=epoch_i)
>         wandb.log({"valid/loss": epoch_i * 100 - random.randint(-20, 20)}, step=epoch_i)
>     wandb.log({
>         "test/loss": n_units * 10 - random.randint(-5, 5),
>     })
> ```

Is it possible to plot a line plot (test loss vs N) in this case?

**Comment by vanpelt** [comment]
You can use a bar plot to compare the different runs, or use the the line label template syntax to plot multiple runs against eachother and include n_units in the legend.  Does that make sense?

**Comment by seungjaeryanlee** [comment]
@vanpelt I understood the bar plot. Could you point me to a documentation or an example of the line label template syntax? I wasn't able to figure it out.

**Comment by vanpelt** [comment]
When editing a chart you can edit the legend section:

![image](https://user-images.githubusercontent.com/17/83411833-d8d9d880-a3cd-11ea-9eba-3d5b93a1401c.png)

The expressions section has some more examples of variables.
