### ISSUE TITLE
Git diff & code saving not working for Ray Tune

### ISSUE THREAD

**Issue by concretevitamin** [wandb/client#1064]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: 3.7.7
* Operating System: Ubuntu

### Description

My app uses Ray Tune's `tune.run_experiments()` and `tune.Trainable` to launch everything.  In particular `wandb.init()` is called inside `Trainable._setup()`.  

Expected behavior: I'd expect Git SHA, code diff saved with respect to my app (`~/app/run.py`, where `~/app` is a Git directory).

Current behavior: No Git SHA; code saved to W&B is `/home/ubuntu/anaconda3/envs/exp/lib/python3.7/site-packages/ray/workers/default_worker.py`.  This is the main program that launches a Ray worker that holds a `Trainable` object.

**Comment by vanpelt** [comment]
Currently when `wandb.init` is called we use `os.getcwd` to determine where to look for the git repo.  Because ray is running from the workers directory we're not finding the repo.  We should add a new environment variable that allows you to override for this case.

**Comment by concretevitamin** [comment]
Thanks @vanpelt; yep, I believe that'd resolve this.

**Comment by concretevitamin** [comment]
@lavanyashukla @vanpelt do you mind re-opening this to track?  This issue isn't resolved.

**Comment by vanpelt** [comment]
@concretevitamin sorry about that, just reopened.

**Comment by ariG23498** [comment]
Hey @concretevitamin 
Could you check if the issue still persists?
We would like to close state threads as we move along :smile:
