### ISSUE TITLE
Python version issue

### ISSUE THREAD

**Issue by pochtar** [wandb/client#1070]
`wandb --version && python --version && uname`

wandb, version 0.8.36
Python 2.7.16
Darwin (MacOS 10.15.5)

### Description

When I run `wandb agent my-sweep-id`, it fails.
The problem seems to be that it tries to use `python` (which is 2.7), and I want to use `python3`:
```
$ python3 --version
Python 3.7.6
```

How can I specify the correct python version so that it uses python3 instead of python?

**Comment by cvphelps** [comment]
Hi there, please specify python3 in your sweep YAML file:
https://docs.wandb.com/sweeps/faq#sweep-with-custom-commands
