### ISSUE TITLE
Local wandb not letting me add back user I have deleted

### ISSUE THREAD

**Issue by ameliatqy** [wandb/client#1071]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: 3.6.9
* Operating System: Linux (Ubuntu 18.04)

### Description

I have some trouble adding users in the local version of wandb (i.e. wandb local). It seems that it is not letting me re-add a user that I have deleted from the system. It tells me that their email address still exists in the system, even after I have deleted them.

### What I Did
1. I tried adding a user via email address at http://localhost:8080/admin/users. 
2. That particular user didn't get an email, so I thought of deleting the user and adding him back. So I deleted the user  at http://localhost:8080/admin/users. 
3. When I tried adding the user again (like in step 1), I saw the error "Email is already in use."

<img width="1205" alt="Screen Shot 2020-05-29 at 1 40 19 AM" src="https://user-images.githubusercontent.com/33330101/83239891-72df1e00-a14d-11ea-8de9-9c2132d4f269.png">

Thank you for your help in advance!

**Comment by davidwallacejackson** [comment]
Hi! Re-adding deleted users is a case we haven't addressed -- sorry about that. In the meantime, this should do for a workaround:

```
docker exec -it wandb-local bash
sudo mysql
use wandb_local
UPDATE users SET deleted_at = NULL WHERE email = 'email@company.com';
```

Invite emails aren't currently sent automatically when users are added -- you can send an invite email or copy a new invite link from a user's actions menu in `/admin/users`:

![image](https://user-images.githubusercontent.com/1735971/83288367-1523f380-a198-11ea-878b-c2d8cd44daf6.png)

Thank you for your patience with this, and thank you for using the product!

**Comment by ameliatqy** [comment]
Thank you for your help! The workaround you suggested worked for me. Just to let you know, when I click "Send Invite Email", it works as expected. However, when I click "Copy invite link", I get the error "Error retrieving invite link." Not a big issue as I can the link via "Send Invite Email", just to let you know that this issue exists.
