### ISSUE TITLE
Unable to use TensorBoard

### ISSUE THREAD

**Issue by jarednielsen** [wandb/client#1072]
* Weights and Biases version: 0.8.36
* Python version: 3.7
* Operating System: Ubuntu 18.04
* TensorFlow: 2.1.1
* TensorBoard: 2.1.1

### Description

```python
import tensorflow as tf
import wandb
wandb.init(sync_tensorboard=True)
writer = tf.summary.create_file_writer('logdir')
```

results in 

```python
wandb: ERROR Couldn't import tensorboard, not streaming events. Run `pip install tensorboard`
```

**Comment by cvphelps** [comment]
Hey there, could you please install tensorboard on your machine?

```
pip install tensorboard
```

**Comment by jarednielsen** [comment]
Yep, I've done that. I have tensorboard==2.1.1.

**Comment by ariG23498** [comment]
Hey @jarednielsen 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen. :smile:
