### ISSUE TITLE
Broken link on website dashboard

### ISSUE THREAD

**Issue by jarednielsen** [wandb/client#1073]
When I click on a specific run on the web dashboard, it links me to a page with `undefined` in the URL, which doesn't exist. Here's an annotated image of how to replicate.

<img width="579" alt="Screen Shot 2020-05-29 at 4 35 10 PM" src="https://user-images.githubusercontent.com/4564897/83313411-ed9a4e80-a1ca-11ea-9cc8-2aee9f97ac1f.png">

**Comment by tyomhak** [comment]
Thank you for reporting! We'll investigate, and get back to you once we have something!

**Comment by tyomhak** [comment]
This seems like a bug, I'm filing a ticket.

**Comment by jarednielsen** [comment]
Fixed, thank you!
