### ISSUE TITLE
Unable to log grad & params with pt-lightning

### ISSUE THREAD

**Issue by tshrjn** [wandb/client#1074]
### Description

When using `WandbLogger` with `pytorch-lightning`, the gradients and parameters are not being logged.

### Code Demo
Please refer the simple demo code file [here](https://app.wandb.ai/tshrjn/demo/runs/3riz322l/files/code/demo_wandb_log.py) and the logs [here](https://app.wandb.ai/tshrjn/demo)

Also, there's more information in the run info in the above demo logging. Please help resolve this issue as gradient & parameter logging are super important for NN debugging.

### Version info

```bash
* CUDA:
        - GPU:
                - GeForce RTX 2080 Ti
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.18.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.5.0
        - pytorch-lightning: 0.7.5
        - tensorboard:       2.2.0
        - tqdm:              4.45.0
        - wandb:            0.8.35
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.6.10
        - version:           #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019
```

**Comment by tyomhak** [comment]
Thank you very much for reporting!

**Comment by borisdayma** [comment]
I see weights and gradients in your run. Click on the tabs at the bottom.
![run_grad_param](https://user-images.githubusercontent.com/715491/83554033-c0eb7d00-a4d1-11ea-91bd-159ec8ce3ba6.png)

**Comment by tshrjn** [comment]
Oh, right I only see them inside each run but not if I'm the workspace. Is this the expected behavior?

<img width="1680" alt="Screen Shot 2020-06-02 at 2 41 58 PM" src="https://user-images.githubusercontent.com/8372098/83557197-3a3d9c80-a4df-11ea-9c57-b0ec02d2472a.png">

**Comment by borisdayma** [comment]
I never try to use it in the workspace as I feel it would be difficult to represent for several runs.

You can add custom graphs by selecting the "+" on the top right where you can select manually some parameters/gradients.

@cvphelps do you have anything to add?

**Comment by ariG23498** [comment]
Hey @tshrjn 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen. :smile:
