### ISSUE TITLE
Improving sections export to reports

### ISSUE THREAD

**Issue by tshrjn** [wandb/client#1075]
### Description

I enjoy using W&B as it makes experiment tracking is so much better. 
A feature I really really want to use a lot is **Reports**. However, I have faced way too much friction, stated below, to properly use it. Assuming others have also faced similar issues, resolving them would greatly be beneficial to the community.

<img width="1361" alt="Screen Shot 2020-05-31 at 6 09 28 PM" src="https://user-images.githubusercontent.com/8372098/83363785-1dcc2380-a36a-11ea-8a07-dce25582704a.png">

#### Good to Have Features (or Currently too much effort/friction):
1. Currently exporting a section from the UI Workspace creates a new report. This has led to me creating tens of report instead of 1. Having everything in 1 report helps build a story & progression of experiments. Also, there seems to be no way to copy sections from one report to another.

2. Similar to the above issue when exporting sections, there seems no way to simply check the runs you want to export instead of exporting all runs & then filtering & selecting the runs in the report.

These issues make using reports too much of a time sink. I believe reports have the potential to be awesome & act as blogs or experiments/analysis/results sections of WIP paper/projects.

@lavanyashukla & @sayakpaul have created quite a few awesome blog-ish reports. Perhaps they might have also faced similar issues and/or found workarounds.
If there are any quick & easy workarounds these issues, I'd be glad to discover them.

**Comment by sayakpaul** [comment]
I can share my workflow.

- After I am done with running all the experiments, I start with a blank report. 
- I then fill it with the section placeholders to give it a skeleton. 
- I then add plots, summary statistics, basically all the good stuff specific to a section. 
- If any filtering is required in the Run Set, I do that as well. If a run set has way too many runs (which is likely the case almost all the times) I first toggle the **Visualize None** option, and then I select the runs I am interested in. 

@lavanyashukla can perhaps share more.

**Comment by tshrjn** [comment]
Hi, @sayakpaul thanks for sharing your workflow.
I still feel there's a need for better operability between reports & UI workspace. 

For example, I've project ongoing for which the number of experiments in the hundreds, therefore, a better reporting mechanism where a smaller set of experiments can be easily logged & analysed would still be useful. Currently, I'm using screenshots to avoid the whole process of exporting & filtering runs😅.

**Comment by sayakpaul** [comment]
There's a capability that allows you to group runs in a better way and which is something you might be looking for. @cvphelps can comment more on this.

**Comment by tshrjn** [comment]
Yes, but grouping doesn't work with `pytorch-lightning` as far as I know.

**Comment by cvphelps** [comment]
Hi there @tshrjn thanks for your suggestions
1. **Export to existing report**: Great idea, we should add this asap.
2. **Select run set to export**: On the project page, this currently pulls from the set of visible runs, and those are the runs that are set to visible in the run set for your report. Are you not seeing this behavior? If you're exporting from the run page instead of the project page, it might automatically select all runs— if so, this is a bug we should fix.

**Comment by vanpelt** [comment]
@tshrjn The pytorch lightening logger has a "group" keyword argument for grouping.  You can also set the "WANDB_JOB_TYPE" environment variable to assign sub groups.

**Comment by tshrjn** [comment]
@vanpelt Thanks. Yes, indeed now there's a group arg & I didn't know about `WANDB_JOB_TYPE`. 

Apparently it isn't listed in the [env variables docs](https://docs.wandb.com/library/advanced/environment-variables).  Also, similarly, the `WANDB_RUN_GROUP` is only listed in the [grouping doc](https://docs.wandb.com/library/advanced/grouping) but not in the [env var doc](https://docs.wandb.com/library/advanced/environment-variables).

Is this on purpose?

**Comment by ariG23498** [comment]
Hey @tshrjn 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen. :smile:

**Comment by coloss** [comment]
It appears to me that the feature of adding to existing report does not work. When I want add stuff to an existing report, the drop down menu does not list any of my reports but only offers the option to create a new report.

**Comment by ariG23498** [comment]
Hey @coloss 
We have recently updated the editor for our reports. Could you check if you could go into an existing report of yours and then manually add a panel to that report? This would help you add a section to an existing report!
Let us know if this helped. Thanks! 😄

**Comment by coloss** [comment]
@ariG23498 , it seems to work now. :-) Thanks a lot.
