### ISSUE TITLE
[CLI] wandb sync --id=3ry7a3m2 syncs all experiments instead of the provided one

### ISSUE THREAD

**Issue by sebastian-sosa** [wandb/client#1078]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: 3.7.6
* Operating System: Debian 9.0

### Description

I modified `wandb-summary.json` locally and want to upload my changes. I'm probably missing something from the CLI docs, but no matter what command combination I try, I keep uploading all the runs instead of just the provided one. 

Docs from CLI:
```
wandb sync --help

Usage: wandb sync [OPTIONS] [PATH]...

  Upload an offline training directory to W&B

Options:
  --id TEXT           The run you want to upload to.
  -p, --project TEXT  The project you want to upload to.
  -e, --entity TEXT   The entity to scope to.
  --ignore TEXT       A comma seperated list of globs to ignore syncing with
                      wandb.

  --help              Show this message and exit.
```

### What I Did

I tried with all the following commands, and the result was always the same: wandb would upload all the runs on my local directory. There is a folder `wandb`  and a run inside it under the folder `run-20200602_150630-3ry7a3m2` from where the command was invoked.

Commands I tried:
```
wandb sync --id=3ry7a3m2
wandb sync --id=3ry7a3m2 wandb/
wandb sync --id 3ry7a3m2 wandb/
wandb sync --id=3ry7a3m2 wandb/
wandb sync --id "3ry7a3m2"
wandb sync --id '3ry7a3m2'
wandb sync --id '3ry7a3m2' wandb/
wandb sync --id='3ry7a3m2' wandb/
wandb sync --id="3ry7a3m2" wandb/

```

Am I missing anything?

Thanks,
Sebastian

**Comment by vanpelt** [comment]
We iterate over all directories by default.  You can pass the individual directory to sync only that one.  i.e. `wandb sync wandb/run-XXXXX-3ry7a3m2`

**Comment by ariG23498** [comment]
Hey @sebastian-sosa 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen. :smile:

**Comment by zycalice** [comment]
> We iterate over all directories by default. You can pass the individual directory to sync only that one. i.e. `wandb sync wandb/run-XXXXX-3ry7a3m2`

to clarify, if pathA has a nested structure and has structure pathA/h/*tfevents, and pathA/g/*tfevents, and if i do `wandb sync --sync-tensorboard pathA`, does it also iterate over all directories? I somehow got a warning saying `wandb: WARNING Found {} directories containing tfevent files. If these represent multiple experiments, sync them individually or pass a list of paths.`; wanted to confirm the warning might not be needed and the sync is correct
