### ISSUE TITLE
Feature request: aggregating metrics inside epochs

### ISSUE THREAD

**Issue by MartSlaaf** [wandb/client#1080]
* Weights and Biases version: 0.8.36
* Python version: 3.7.3
* Operating System: Linux

### Description
Situation:
I want to see the train and test metric on the same plot because it's good for model understanding. Although, two choices I see: (i) aggregate metric by epochs instead of steps, (ii) see on plots by steps, having them disjoint (for each step I can have either train or test metric point).

Problem:
If I going the first way and aggregating by epoch, the plot is looking quite misleading. The lines along the x-axis don't represent the trend, cause they match not the means or medians, but they match last and first data points inside epoch. If I go the second way, at some number of points it becomes quite hard to distinguish train from test, because them getting too tight, also matching lines do not help in this process, covering part of the data.

Possible solutions:
For the aggregation, I would highly appreciate the same plot you have aggregating the different runs (mean/median/etc with deviation shown), but with statistics per point caused by different points with the same epoch number. Or, as an option -- just show how it is, but with gap-lines linking means and not last points (additional improvement is to add error bars).
For step-plotting I would suggest removing gap-lines at all.

Of course, I can pre-calculate means by myself, and log only one value per epoch, but it will make me loose information about in-epoch metric variation.

Any other options or recommendations on how to plot train and test metrics on one plot and do not result in a mess would be much appreciated.

**Comment by cvphelps** [comment]
Hi! Great news, we're starting to work on a new feature that will make custom plots like what you describe possible. Thanks for this good feature requst

**Comment by ariG23498** [comment]
Hey @MartSlaaf 
We have come up with [Custom Charts](https://docs.wandb.ai/app/features/custom-charts) that can help you with your feature request. Would you like to dive into them and share your feedback on this? 😄
