### ISSUE TITLE
wandb.log() should fail silently if not logged in

### ISSUE THREAD

**Issue by jarednielsen** [wandb/client#1086]
The code should still function if not logged in (no `WANDB_API_KEY` or `wandb login`) is set. Currently it throws an error if you attempt to log.

Related to https://github.com/wandb/client/issues/764; I would like to distribute my code to users who do not have wandb enabled.

**Comment by vanpelt** [comment]
@jarednielsen you can specify `anonymous="allow"` in your call to wandb.init() to not enforce login and instead create an anonymous account that only the user running the code can access.  Otherwise you'll need to put wandb logging behind a feature flag that users can turn on or off.

**Comment by ariG23498** [comment]
Hey @jarednielsen 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing stale issues. Please comment to reopen. :smile:
