### ISSUE TITLE
Permission denied on wandb.init()

### ISSUE THREAD

**Issue by jwallat** [wandb/client#1095]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.1
* Python version: 3.7.3
* Operating System: Linux

### Description

I am trying to use wandb on a computing cluster. 

### What I Did

I use this small script to see if I can login and log some arbitrary values. 
Since I am unable to do wandb login, I am setting the api key.
```
os.environ["WANDB_API_KEY"] = '<my_key>'
os.environ['WANDB_MODE'] = 'dryrun'
os.environ['WANDB_ENTITY'] = '<my_wandb_name>'
os.environ['WANDB_PROJECT'] = 'cluster_test'
os.environ['WANDB_CONFIG_DIR'] = '/home/wallat/.config/wandb/'

wandb.init(dir='/home/wallat/wandb_mnist_test/')
wandb.log({'epoch': 2, 'loss': 0.5})
```

This is the output: 
```
Traceback (most recent call last):
  File "/home/wallat/wandb_mnist_test/test_wandb.py", line 23, in <module>
    main()
  File "/home/wallat/wandb_mnist_test/test_wandb.py", line 16, in main
    wandb.init(dir='/home/wallat/wandb_mnist_test/')
  File "/home/wallat/.local/lib/python3.7/site-packages/wandb/__init__.py", line 1125, in init
    _init_headless(run)
  File "/home/wallat/.local/lib/python3.7/site-packages/wandb/__init__.py", line 286, in _init_headless
    headless_args)], env=environ, **popen_kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
```

Can anyone tell me what might cause this problem? The error message is not quite enough to guess :) 

Thanks

**Comment by vanpelt** [comment]
This looks like a file system permission error.  Are you sure `/home/wallat/wandb_mnist_test/` exists and is writeble by the user you're running the script as?

**Comment by vanpelt** [comment]
There are likely more details in `wandb/debug.log`

**Comment by jwallat** [comment]
Yes, it should not be an permission problem. Every run creates a new run-folder in `/home/wallat/wandb_mnist_test/wandb/`. The debug.log is empty though...
My guess was that the cluster's job manager is not letting me spawn more subprocesses, since it is crashing on that line. But I tried and spawning subprocesses seems not the be the problem either.

**Comment by vanpelt** [comment]
This is really strange.  If debug.log is empty that indicates we weren't able to write to that file.  What are the permissions on it?  `ls -al wandb`

**Comment by jwallat** [comment]
I managed to figure out what was causing the problem. The job-manager of my cluster was starting the script from a private dir. This caused the `os.getcwd()` and `sys.executable` to direct to some dir like `/var/lib/condor/execute/dir_25945` (the cluster is using ht condor). 
When `wandb.init()` tried to open the subprocess like this: 
```
subprocess.Popen([sys.executable, internal_cli_path, json.dumps(
        headless_args)], env=environ, **popen_kwargs)
```
it had no permission to access the executable in that folder. 
A workaround was manually setting `sys.executable = '/usr/bin/python3'`. After doing so, it worked like a charm. Not sure if that might cause problems with my cluster configuration later on, though. 

But the problem was entirely on my side, so I am closing this issue. Thanks for the help.

**Comment by vanpelt** [comment]
Good to know, we can provide a better error message in this case.
