### ISSUE TITLE
Frontend: View exact date in Created At column

### ISSUE THREAD

**Issue by sebastian-sosa** [wandb/client#1103]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.36
* Python version: 3.7.6
* Operating System: Linux

### Description

On the web UI, when visualizing all the runs under a project there's a column called Created, which says when the run was made. It shows the relative time from the present (ie `7h ago` or `1d ago`), and if you hover the mouse on top of the label, it shows the exact time (ie `2020-06-05 20:31`).

Personally, I often find myself searching for the experiment I run yesterday after lunch at 13:30, or the one I ran today at 9:00. It would be nice to have the ability to toggle the default format to the exact time, as I usually end up doing more mental math than needed to visually search for the experiment I'm looking for.

By the way, I love the product! Thanks for the great work.

**Comment by vanpelt** [comment]
Thanks for the feature request, we're tracking this internally.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. You should now be able to view the exact date in the created at column.

**Comment by nc1m** [comment]
@sydholl I just have a "Created" column and it still shows the relative time from the present.
