### ISSUE TITLE
confusing confusion matrix plot

### ISSUE THREAD

**Issue by noklam** [wandb/client#1104]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.1
* Python version: 3.6.4
* Operating System: Window 10

### Description
* The x/y axis is unconventional and confusing, x-axis should be predicted value, and y-axis should be actual

# Code Snippets
![image](https://user-images.githubusercontent.com/18221871/84879308-a0b8e200-b0bd-11ea-9398-0516d8d90a19.png)

## Expected
x: Predict
y: Actual
The common confusion  matrix should be:

|   |   |
|---|---|
| TN | FP |
| FN | TP |

The UI is showing this instead:

|   |   |
|---|---|
| TN | **FN** |
| **FP** | TP |

# Gist Example
https://gist.github.com/45c6a6cf3f50ace5b5f94d027e619237

cc @hinofafa

**Comment by tyomhak** [comment]
Thank you very much for pointing it out. We filed a ticket for it.

**Comment by cvphelps** [comment]
Hey there, thanks for your message. I don't think we'll be able to switch this for a little while but we're building a better solution for custom graphs which will allow you to customize this behavior.
