### ISSUE TITLE
Running W&B Locally on an EC2 Instance (trying to bind to a different address)

### ISSUE THREAD

**Issue by dr-aheydari** [wandb/client#1105]
Hello,
### Description
I would like to run `wandb local` on an EC2 instance, but I would like to have access to the reports from different machines, i.e. viewing the app not through `localhost`.

Is it possible to bind the `wandb` app to a different address (e.g. http://0.0.0.0) so that the page could be viewed form different machines ?

* Operating System: Linux-Ubuntu (on an EC2 instance) 

Thank you for your help.

**Comment by vanpelt** [comment]
The wandb local command simply runs the following docker command under the hood:

```
$ docker run --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```

This binds to 0.0.0.0:8080 by default.  You'll need to open up whatever port you on the EC2 instance to make it available.  More info [here](https://docs.wandb.com/self-hosted/setup#ec2).

**Comment by dr-aheydari** [comment]
Thank you for your response, I assumed since it said `localhost` it would always bind to `127.0.0.1`. This answered my question!
