### ISSUE TITLE
"null" not working when filtering the runs

### ISSUE THREAD

**Issue by umgupta** [wandb/client#1107]
This issue is related to W&B UI.

When some config option is logged as null (or none in python), the table filtering does not work with it properly. For example, no matter what filter you set on that property, you won't be able to see the runs with "null" value of that config option.

**Comment by vanpelt** [comment]
Hey @umgupta this should be supported.  Can you link us to a project where you're unable to do this currently?  Are the values actual null values or the string "null"?

**Comment by ariG23498** [comment]
Hey @umgupta 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing stale issues. Please comment to reopen. :smile:

**Comment by Linusnie** [comment]
I'm having the same issue. I have 40 runs with null in the dataset.n_points parameter, but they don't show up in the panels
![Screenshot from 2023-09-30 12-24-15](https://github.com/wandb/wandb/assets/12471058/1a3c678c-b3f3-4e45-92cb-c7fabcac9013)

**Comment by nblauch** [comment]
This issue appears to have popped up anew, since this worked not too long ago, but now does not (in both reports and workspaces)

**Comment by Pastells** [comment]
I'm having the same issue

**Comment by siantonelli** [comment]
I have the same issue and cannot filter these runs using the API either. I've tried also with different values `"null"`, `"None"`, and `"none"`, but all of these return 0 runs.

```python
entity = cfg.wandb.entity
project = cfg.wandb.project

api = wandb.Api()
runs = api.runs(
    path=f"{entity}/{project}",
    filters={
        "$and": [
            {"config.data.dataset.name": cfg.data.dataset.name},
            {"config.train.model._target_": cfg.train.model._target_},
            {"config.train.alpha": None},
        ]
    },
)

print(len(runs))
```

**Comment by zimmer-m** [comment]
Why is this still closed? This issue persists and apparently there is no solution. I am having the exact same problem.

**Comment by charliemarx** [comment]
I am having the same issue. Can this be reopened?

**Comment by eMarco** [comment]
I have the same issue. I cannot find a way to filter out non-null values without getting a 400 error
