### ISSUE TITLE
Log content is erased in silent mode

### ISSUE THREAD

**Issue by kaglowka** [wandb/client#1110]
* Weights and Biases version: 0.9.1
* Python version: 3.8.2
* Operating System: Ubuntu 20.04

### Description

I ran `wandb` in my simulations and wanted to be in control of wandb output, so it wouldn't mix with the output I printed myself.

### What I Did

I set silent mode (as below), and set up `watchdog` handler to listen to changes appearing in `debug.log`, so I could print them at the right moment.
```python
os.environ['WANDB_SILENT'] = 'true'
wandb.init(
            dir=config.WANDB_DIR,
            project=config.WANDB_PROJECT,
            config=config.WANDB_CONFIG,
            group=config.WANDB_GROUP_NAME,
            name="{0}-{1}".format(config.WANDB_GROUP_NAME, config.SIMULATION_ID),
            notes=config.WANDB_NOTES,
        )
```

It was only a test wandb initialisation that lasted about a second, but it is enough to see what happens in the log:

`debug.log`:
```
wandb: Synced testRuns-2: https://app.wandb.ai/hill_uw/cangelosi-2001/runs/qu1tjdsb
2020-06-20 21:43:58,877 INFO    MainThread:1963908 [run_manager.py:_sync_etc():1466] syncing complete: https://app.wandb.ai/hill_uw/cangelosi-2001/runs/qu1tjdsb
2020-06-20 21:43:58,877 INFO    MainThread:1963908 [qu1tjdsb:run_manager.py:_sync_etc():1466] syncing complete: https://app.wandb.ai/hill_uw/cangelosi-2001/runs/qu1tjdsb
```

I see the following issues here:
1. Output that was previously (in non-silent mode) output in the console (starting with "wandb:", now is output in the log, but it also overwrites all other content.  Above you can see, that the first line of the log is also the line that is normally displayed last in the console (as far as I'm aware).
2. There is a long line filled with some bad values, e.g. Geany editor couldn't open the file.

### Very likely solution to 1)
I took a quick look and it seems that it's just the `w` file opening mode that erases previous log's content.: 
```python
with open(util.get_log_file_path(), 'w') as log:
```
https://github.com/wandb/client/blob/68b4fbc96a9e30f9808a991cf7c63baffd818c61/wandb/core.py#L96

**Comment by vanpelt** [comment]
Thanks for filing we'll work on a fix for the next release.

**Comment by ariG23498** [comment]
Hey @kaglowka 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing stale issues. Please comment to reopen. :smile:
