### ISSUE TITLE
Simultaneously started runs are too similarly coloured

### ISSUE THREAD

**Issue by Nintorac** [wandb/client#1112]
wandb, version 0.9.1
Python 3.6.10 :: Anaconda, Inc.
Linux

### Description

Starting multiple runs simultaneously results in very similar colours in the web front end

![Screenshot_2020-06-22 Weights Biases](https://user-images.githubusercontent.com/24326299/85290412-4d3efd80-b4dc-11ea-9266-f3f8d79b1638.png)

The bottom 4 runs in the screen capture were started simultaneously

### What I Did
Using `ray.tune` to launch a grid search

**Comment by vanpelt** [comment]
Hey @Nintorac this is currently by design.  You can change the colors in the UI by clicking on the circles.  We'll sync internally about the best thing to do in this case.

**Comment by Nintorac** [comment]
Just a bit of a pain to manually change multiples of runs but must be done otherwise the runs cannot be visually distinguished. Might make more sense to try and base colours on hyper params but might be tricky to implement.
