### ISSUE TITLE
System metrics: customize logging frequency

### ISSUE THREAD

**Issue by coolalexzb** [wandb/client#1133]
`wandb --version && python --version && uname`

* Weights and Biases version: version 0.9.1
* Python version: Python 3.7.4
* Operating System: MAC OS

### Description

Hi there! From the documentation, I find that default metrics will be averaged every 30 seconds. I want to ask if we have any approach to change the time interval. I hope that users can have the option to choose by themselves. For example, if I have a program that runs for about 3 minutes, we might want to record system metrics every 5 or 10 seconds. If not, is there any way to add some code to make a control outside of `wandb` package. Thank you!

**Comment by vanpelt** [comment]
Hey @coolalexzb we're currently not exposing these dynamic settings in the UI.  The relevant code is here: https://github.com/wandb/client/blob/master/wandb/stats.py#L81  As a quick workaround you could override this method.  In the next release of our python library we plan to expose this in the UI, this release is planned for late July.

**Comment by coolalexzb** [comment]
@vanpelt That sounds great. I will try to override the method you mentioned. I decide to add `set_sample_rate_seconds` and `set_samples_to_average` functions to help users to set these two values. Can you show me where users might call these two functions to set time intervals after I add these functions?

**Comment by vanpelt** [comment]
We don't want to add these methods to the library itself.  We'll eventually expose this setting in our UI hence the current logic to look at "dynamic_settings".

**Comment by ariG23498** [comment]
Hey folks
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing stale issues. Please comment to reopen. :smile:

**Comment by salmanmashayekh** [comment]
Hey! How can we customize the logging frequency in the new CLI/UI?

**Comment by loodvn** [comment]
Hi there, I think this option would be really useful! 
For debugging GPU memory issues, the 2s (averaged over 30s) logging frequency is insufficient, I find. 
Would be great if we could change the option somewhere in the ui / config!

**Comment by aidanjdonohue** [comment]
@loodvn if you're using PyTorch, using the profiler is probably your best bet for debugging GPU memory issues but I can file a ticket for adding some of these more basic tools to the UI

**Comment by dingyiyi0226** [comment]
Is there any update on this issue? [The previous workaround](https://github.com/wandb/wandb/issues/1133#issuecomment-653113342) doesn't seem to be working.

**Comment by daphnecor** [comment]
Hello! I would also love to see this feature, have there been any updates?
