### ISSUE TITLE
`wandb.init` does not play well under `bazel test`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [wandb/client#1137]
* Weights and Biases version: `wandb, version 0.9.1`
* Python version: Python 3.6.9
* Operating System: Linux

### Description

Just trying to put our usages of `wandb.init` under `bazel test`.

However, when we do that, we get the following:

```
Traceback (most recent call last):
  File "{runfiles}/wandb_examples/
test/wandb_stub_test.py", line 48, in test_wandb
    wandb.init(project="test_project", sync_tensorboard=True)
  File "{execroot}/wandb_examples/venv/lib/python3.6/site-packages/wandb/__init__.py", line 1129, in init
    _init_headless(run, False)
  File "{execroot}/wandb_examples/venv/lib/python3.6/site-packages/wandb/__init__.py", line 259, in _init_headless
    stdout_master_fd, stdout_slave_fd = io_wrap.wandb_pty(resize=False)
  File "{execroot}/wandb_examples/venv/lib/python3.6/site-packages/wandb/io_wrap.py", line 157, in wandb_pty
    master_fd, slave_fd = pty.openpty()
  File "/usr/lib/python3.6/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.6/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
```

### What I Did

See this `repro/.../README` section:
https://github.com/EricCousineau-TRI/repro/tree/3cc6aa5ba70e306b3b1a1660f3f59c07b1eca12d/python/wandb_examples#wandb-and-bazel-test

**Comment by vanpelt** [comment]
@EricCousineau-TRI it looks like the bazel build is calling `wandb.init` many times, so many times that it's consuming all pty devices.  Do you know how many calls to `wandb.init` end up happening when you run bazel build?

**Comment by EricCousineau-TRI** [comment]
Ah, sorry - this code is only meant to test one call to `wandb.init`; the `if SHOW_ERROR` statement is to show the case where it fails (no mocking of `_init_headless`), but should only be called once per process:
https://github.com/EricCousineau-TRI/repro/blob/3cc6aa5ba70e306b3b1a1660f3f59c07b1eca12d/python/wandb_examples/test/wandb_stub_test.py#L56-L57

If I the section here, `wandb.init` should only be called once per `bazel test ` invocation:
https://github.com/EricCousineau-TRI/repro/tree/3cc6aa5ba70e306b3b1a1660f3f59c07b1eca12d/python/wandb_examples#wandb-and-bazel-test
```sh
# Show it working
bazel test --config=show_test :wandb_stub_test

# Show it failing
bazel test --config=show_test --test_arg="--show_error" :wandb_stub_test
```

Does that clarify? I can rewrite it to be simpler if you'd like!

**Comment by EricCousineau-TRI** [comment]
I've added this commit which concretely shows that `wandb.init` is only called once per run of `bazel test`:
https://github.com/EricCousineau-TRI/repro/commit/de29bf3845c6372fcb374ef0e1023f8b7e96d14f

Each time, it prints out `Num calls: 1`.
I think the issue has to do deal with how `bazel test` redirects I/O (for logging), and `wandb`s expectations of having a pty?

**Comment by yoks** [comment]
To fix pty issue under bazel, you can use `--spawn_strategy=processwrapper-sandbox` flag

**Comment by vanpelt** [comment]
@yoks thanks for the trick!  @EricCousineau-TRI does this work for you?

**Comment by EricCousineau-TRI** [comment]
Thanks!
However, I'm not sure how I feel about this as a workaround that I want to either infect other tests with, or add specific filtering logic for.
When I search for `processwrapper-sandbox`, I don't really get any public documentation about it, so I don't know how this stacks against the default spawn strategy of `sandboxed`:
https://docs.bazel.build/versions/master/user-manual.html#strategy-options
https://bazel.build/search.html?q=processwrapper-sandbox
https://bazel.build/search.html?q=processwrapper

Ideally, `wandb` has a way to not require `pty`s for a dryrun mode? Or if it's for a feature, disable that feature, but still allow us to test codepaths for `wandb`?

**Comment by vanpelt** [comment]
We're targeting a big release of our library for next week.  It will include a "noop" mode which will do exactly what you want here.

**Comment by EricCousineau-TRI** [comment]
Sweet, thank you!

**Comment by EricCousineau-TRI** [comment]
Confirmed that it works!
https://github.com/EricCousineau-TRI/repro/commit/583acd21
