### ISSUE TITLE
Issue using step argument in wandb.log()

### ISSUE THREAD

**Issue by numpee** [wandb/client#1142]
* Weights and Biases version: 0.9.2
* Python version: 3.5.2
* Operating System: Linux

### Description

Metric logging is always delayed by 1 step when using the `step=` argument in `wandb.log()`. 
I realize this was an issue in Jupyter notebooks, but it still an issue in ordinary Python scripts. 
I guess the current workaround is to not set the `step` at all, and log a custom step value, but I still feel like this `step` issue should be fixed in the near future. 
Please refer to the below code to reproduce this issue.

### What I Did

```
import wandb
import time

def main():
    wandb.init(name='test', project="arbitrary_project", entity="numpee")
    for i in range(10):
        val = {'val': i}
        wandb.log(val, step=i)
        print("logged")
        time.sleep(60)

if __name__=="__main__":
    main()
```

**Comment by vanpelt** [comment]
Hey @numpee, step is used to determine when to "commit" a step.  We should be commiting the final step when the process exits, it looks like that may be a bug.  If you want the step to "commit" you can pass `commit=True` to your call to wandb.log.  You should only do this if you don't intend to add another metrics to the current step, which in your example looks to be the case.

**Comment by numpee** [comment]
@vanpelt Great! 
I didn't know there was a `commit=True` argument.
What I can do now is call all the `wandb.log()` for the current step, then pass an empty dictionary and commit the results. This seems to work now :)

For reference, the changed code would be:

```
import wandb
import time

def main():
    wandb.init(name='test', project="universal-segmentation", entity="numpee")
    for i in range(10):
        val = {'val': i}
        wandb.log(val, step=i)
        print("logged")
        # More wandb.log() calls here if needed
        wandb.log({}, step=i, commit=True)
        time.sleep(60)

if __name__=="__main__":
    main()
```
