### ISSUE TITLE
CLI `login` command incorrectly triggers interactive prompt

### ISSUE THREAD

**Issue by brentschroeter** [wandb/client#1156]
* Weights and Biases version: 0.9.3
* Python version: 3.6.9, 3.7.8
* Operating System: Ubuntu 18.04, macOS 10.15.3

### Description

From a fresh install, attempting to log in via the command line using `wandb login <valid API key>` should succeed without requiring interactive input. Instead, it prompts for an API key interactively (see below).

The cause can be traced back to the addition of `public_api = PublicApi()` on line 210 of wandb/cli.py. To my understanding, this causes the `__init__()` method of the `PublicApi` class (which triggers the interactive prompt if API key is unknown) to be called prior to the execution of _any_ WandB CLI command. This behavior is undesirable, particularly because it renders `wandb login <key>` useless except when a user is already logged in.

### What I Did

```
$ wandb login <my-api-key-here>
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:
```

For now, working around this by downgrading to version 0.9.2.

**Comment by tyomhak** [comment]
Thank you very much for reporting! We have filed a ticket for this.
Sorry for the inconvenience.

**Comment by ariG23498** [comment]
Hey @brentschroeter 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing inactivate threads for the time being. Please comment to reopen. :smile:

**Comment by KhushalB** [comment]
@ariG23498 this issue is still there. Experienced it while trying to init as anonymous on a kaggle kernel

**Comment by ecthompson99** [comment]
@KhushalB did you figure out a workaround on the kaggle kernel? Running into this problem now.

**Comment by KhushalB** [comment]
@ecthompson99 setting anonymous='must' worked for me. Was not able to claim the runs from my wandb account after though.

**Comment by nateraw** [comment]
Same experience as @KhushalB - I can create anonymous runs but I can't claim them. Is claiming still supported somehow?
