### ISSUE TITLE
UI makes it impossible to edit 1-line markdown cells without resizing

### ISSUE THREAD

**Issue by Michael-Tanzer** [wandb/client#1157]
Problem related to the *reports'* UI.

### Description

How to reproduce:
 - Create a report
 - Add a markdown cell
 - Resize it to be 1 line tall
 - Try to edit the text

Expected behaviour: clicking the cell should open the editor and allow the user to type on the cell

Observed behaviour: when hovering on the cell the clickable text appears ("_Add images by dragging & dropping or pasting, use $math$ for TeX_") making it impossible to click on the cell and edit the content.
![image](https://user-images.githubusercontent.com/23483071/87426704-e777fa00-c5df-11ea-8847-c599b08af6f2.png)
![image](https://user-images.githubusercontent.com/23483071/87426724-ef379e80-c5df-11ea-9c74-65150710a106.png)

**Comment by tyomhak** [comment]
Hi Michael, thank you very much for reporting. We have filed an internal ticket for this issue.

**Comment by tyomhak** [comment]
Hey @Michael-Tanzer , this should be fixed now. Please let us know if it reoccurs for you.
