### ISSUE TITLE
wandb status in an unconfigured directory should tell me that it's in an uninitialized directory

### ISSUE THREAD

**Issue by lukas** [wandb/client#116]
* Weights and Biases version: 0.4.47
* Python version: 3.6.3
* Operating System: mac

### Description

When I run `wandb status` in an unconfigured directory the output should be something like

"Wandb is not initialized - use wandb init to initialize the directory"

**Comment by altay** [comment]
fixed in https://github.com/wandb/client/commit/7034b06491d6fdd7606c7a31be6bf65adff4e5c4
