### ISSUE TITLE
Jupyter Notebook— use wandb.login() instead of !wandb login

### ISSUE THREAD

**Issue by abdulsam** [wandb/client#1162]
I'm using google colab.
![wandb](https://user-images.githubusercontent.com/11463868/87881944-64f59d00-ca1a-11ea-81b4-96e3e2528aab.JPG)

Why is it asking API key for 2 times even after pasting the same key?

**Comment by vanpelt** [comment]
Hey @abdulsam what version of the wandb library are you using?  `wandb --version`

**Comment by abdulsam** [comment]
version 0.9.3
Which version should I use?

**Comment by vanpelt** [comment]
That’s the latest version.  We’ll reproduce and get a fix in.

**Comment by vanpelt** [comment]
In colab, you should be running `wandb.login()` from python instead of starting a shell with `!`.  I just verified that works correctly.  We'll look into the command line case as well.
