### ISSUE TITLE
wandb.watch(model): unwatch and rewatch models with new parameters, using Hugging Face

### ISSUE THREAD

**Issue by pedrocolon93** [wandb/client#1164]
`wandb --version && python --version && uname`

wandb, version 0.9.3
Python 3.6.8 :: Anaconda, Inc.
Darwin

### Description

I was trying to unwatch models and rewatch them with new parameters.  I am using the huggingface library which uses wandb.  

### What I Did
 ```
wandb.unwatch()
self._setup_wandb()
 ```

self._setup_wandb() is defined basically as:
 ```

wandb.watch(
                    self.model, log=os.getenv("WANDB_WATCH", "gradients"), log_freq=max(100, self.args.logging_steps)
                )
 ```

Now, looking into unwatch/unhook in the wandb code:
 ```
  def unhook_all(self):
        for handle in self._hook_handles.values():
            handle.remove()
        self._hook_handles = []


    def unhook(self, name):
        handle = self._hook_handles.pop(name)
        handle.remove()

```
This is wrong, it seems that at some point self._hook_handles was changed to a dictionary, so unhook/unhook all should be something like:

 ```
  def unhook_all(self):
        for handle in self._hook_handles.values():
            handle.remove()
        self._hook_handles = {}


    def unhook(self, name):
        handle = self._hook_handles[name]
        handle.remove()

```

I havent tried this yet but I'll get back to it if I do.

**Comment by cvphelps** [comment]
Hi Pedro, thanks for diving in to the `wandb.watch()` code, @borisdayma could you take a look?

As for un-watching and re-watching a model, it sounds like you're editing the model during training, is that right? I'd recommend calling wandb.init() to start a new run each time you want to watch a model with new parameters

**Comment by borisdayma** [comment]
I can confirm issues with `wandb.unwatch` method. Maybe we should wait for the new CLI?

**Comment by pedrocolon93** [comment]
Hi there, the fixed code I think solved the problem (no longer a missing get), but as you said, there needs to be another `init` or else an exception is thrown that the watcher should be reinitialized with a copy.  Is there any reason that you couldn't just add a watch to the new parameters? I am sure there are some internal logistics with references etc.  What I am doing is just changing the `requires_grad` of a few existing parameters at a certain iteration.

**Comment by ariG23498** [comment]
Hey @pedrocolon93 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing inactivate threads for the time being. Please comment to reopen. :smile:
