### ISSUE TITLE
Log markdown for a run to Notes field or similar?

### ISSUE THREAD

**Issue by sullivancolin** [wandb/client#1175]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.2
* Python version: 3.7.7
* Operating System: Darwin

#### Feature Request

I'd like the ability to programmatically log some markdown for a run.  Preferably, I'd like a way to log markdown information with the run as a whole, instead of associated with a step or other x-axis unit.   Notes are only available via the UI that I can tell, but I'd like to be able to generate some notes programmatically as markdown during the run and have them saved and displayed in the info pane of the run.

### What I Did
I attempted to manually render some markdown containing the JSON definition of of my model and log it.

```python
model_markdown = f"```json\n{model.json()}\n```"
wandb.log(
{"Model Definition": wandb.Html(markdown.markdown(model_markdown))}, step=0
)
```
The HTML entry is created, but not displayed very well.   All new lines and indents from the code block are removed.

<img width="1218" alt="Screen Shot 2020-07-25 at 9 57 57 PM" src="https://user-images.githubusercontent.com/10760217/88469651-e8ebd100-cec1-11ea-92f7-e6aa2d855b9a.png">

I would rather standard code block rendering like so:
```json
{
    "MLP": {
        "output_dim": 2,
        "layers": [
            {
                "Linear": {
                    "w": "shape=(10, 2)",
                    "b": "shape=(10,)",
                    "activation": "tanh"
                }
            },
            {
                "Linear": {
                    "w": "shape=(10, 10)",
                    "b": "shape=(10,)",
                    "activation": "tanh"
                }
            },
            {
                "Linear": {
                    "w": "shape=(10, 10)",
                    "b": "shape=(10,)",
                    "activation": "tanh"
                }
            },
            {
                "Linear": {
                    "w": "shape=(2, 10)",
                    "b": "shape=(2,)",
                    "activation": "identity"
                }
            }
        ],
        "input_dim": 2
    }
}
```

**Comment by vanpelt** [comment]
@sullivancolin the notes field accepts valid markdown.  You can pass it to `wandb.init` with the `notes` attribute.  Or you can run this after calling `wandb.init`:

```
wandb.run.notes = "# My Markdown"
wandb.run.save()
```

**Comment by sullivancolin** [comment]
I've tried this work around, but keep running into 
```bash
wandb: ERROR Error while calling W&B API: permission denied (<Response [401]>)
wandb: ERROR Invalid or missing api_key.  Run wandb login
```
 when I get access the run object

```python
run.notes = content
run.save()
```

**Comment by vanpelt** [comment]
Have you run `wandb login` from the command line?

**Comment by vanpelt** [comment]
We fixed the double login command for `wandb login` in version 0.9.4, you should be able to get it by upgrading.  Calling login should write a file to your home directory `~/.netrc` with your credentials which wandb will then read.  If you're able to provide a simple example script that reproduces this issue that would help on our end.  This is really odd, if you're able to log metrics to the cloud you're definitely logged in so I'm not sure why saving is triggering an authentication issue.

**Comment by sullivancolin** [comment]
I found the reason for the error accessing the run object.  It is a collision between the variable name `run` and the `run` command when using Pdb or iPdb debugger.  Changing the variable name of the run object, prevents that spurious error.

Upgrading to 0.9.4 solved the repeated login issue, thanks very much.

However `run.save()` throws an error
```
except handle
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    run.save()
TypeError: save() missing 1 required positional argument: 'path'
```
I've can't find any documentation on that function.
I tried using the current run path which successfully ends, but I don't see the Notes displayed anywhere in the UI

Here is a complete script

```python
import wandb

my_config = {
    "batch_size": 8,
    "learning_rate": 0.01,
}

run_obj = wandb.init(config=my_config, project="test_project")

run_obj.notes = "# My Markdown Header\n##Subheader"

#replace with hard-coded entity_name
path = f"<entity_name>/{run_obj.project_name()}/{run_obj.id}"

run_obj.save(path)

```
Also `run.entity` and `run._entity` both return `None`  but if I print out `run.__dict__` I can see that the correct entity name is displayed.  It would be nice to be able access the entity property so I can re-use code elsewhere.

**Comment by vanpelt** [comment]
That error is really strange.  The save method for the run object is [here](https://github.com/wandb/client/blob/master/wandb/wandb_run.py#L411).  There is no `path` argument to the `save` method.  I think you're using one of the release candidate builds for the new client library.  Try running `pip install wandb-ng`, then `pip install wandb==0.9.4`.

**Comment by niloch** [comment]
Wow that was it! Both these errors, were my fault!  So my setup.py had `wandb>=0.9.4` and my Pipfile had `allow_prereleases = true` to install black and it installed a release candidate 0.10.0rc1.   

Everything works now!  Thanks for the help!

**Comment by sullivancolin** [comment]
Wow that did it!  Both errors were my fault.  I had setup.py with `wandb>=0.9.4` and my Pipfile with `allow_prereleases = true` which installed the release candidate.

Everything works great now.  Thank you for all the help.
