### ISSUE TITLE
Wandb 0.9.x OSError: [Errno 95] Operation not supported

### ISSUE THREAD

**Issue by ZeroCool940711** [wandb/client#1176]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0rc1
* Wandb-ng version: 0.0.33, 0.0.36
* Python version: 3.6.9, 3.8.2, 3.8.3
* Operating System: Linux (Ubuntu 18.04, Ubuntu 20.04)

### Description
When trying to run a script that is on a network mounted folder like a Windows share or also from a symbolic link all Wandb versions that are higher than `0.8.36` will throw the following error `OSError: [Errno 95] Operation not supported: 'runs/run-xxxxxxxx_xxxxxx-xxxxxxxx' -> 'latest.12473'` where `xxxxxxxx_xxxxxx-xxxxxxxx` is the date, time and run unique id (I think).

It seems like Wandb is trying to create the folder where it will store the information for the current/latest run but it fails, as I said it only happens on version higher than `0.8.36` so I guess something was changed on `_WandbInit._safe_symlink()` which is on the `wandb/sdk/wandb_init.py` file after that version and that broke wandb so it doesnt work correctly now on symbolic links.

### What I Did
I tried using multiple Python versions and multiple Operating Systems as I wasn't sure what was the problem or were it was coming from at first because previously wandb was working, I upgraded to Ubuntu 20.04 so that was the first thing I thought was causing the problem as many things can break after an upgrade, then tried different Python versions just in case it was something caused by a broken Python installation, then I started testing the different Wandb versions from the newest and going back one version at the time until I found one that worked.

----------------------------------------------------------------------------------
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

This is the command I used to run my script, the script is not the problem and the python version on here shows Python 3.6 as that was the last version I tested.

```
python run_lm_finetuning.py --output_dir=models/at_the_earths_core__small --model_type=gpt2 --cache_model_name=gpt2 --model_name_or_path=gpt2 --do_train --train_data_file="input_data/train_at_the_earths_core.txt" --do_eval --eval_data_file="input_data/val_at_the_earths_core.txt" --overwrite_output_dir --per_gpu_train_batch_size=1 --per_gpu_eval_batch_size=1 --block_size=0 --save_steps 500 --evaluate_during_training --num_train_epochs=1000 --max_steps=0 --save_total_limit=2 --logging_steps=51 --warmup_steps=1

wandb: Currently logged in as: Xxxxxxx (use `wandb login --relogin` to force relogin)
[WARNING] currently unsupported wandb.init() arg: sync_tensorboard
Traceback (most recent call last):
  File "run_lm_finetuning.py", line 689, in <module>
    main()
  File "run_lm_finetuning.py", line 548, in main
    name=str(args.output_dir).split('/')[1] + '-' + str(args.cache_model_name) + '-1')
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 594, in init
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 569, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 212, in setup
    self._log_setup(settings)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 317, in _log_setup
    delete=True,
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 265, in _safe_symlink
    os.symlink(target, tmp_name)
OSError: [Errno 95] Operation not supported: 'runs/run-20200726_045312-3vgct9dg' -> 'latest.12473'
```

**Comment by raubitsj** [comment]
Thanks for the detailed report.  We have seen a similar issue when using symlinks on windows  so the newer versions (experimental 0.0.33, 0.0.36 and 0.10.0rc1) have a new setting to disable symlinks.

```
wandb.init(settings=wandb.Settings(symlink=False))
```

Please give this a try.  We will try to automatically handle this better in the future.

**Comment by ZeroCool940711** [comment]
@raubitsj thanks for the reply it works now after adding the `settings=wandb.Settings(symlink=False)` to `wandb.init()` , really appreciate the help, :)

I will close this issue as the problem has been solved.

**Comment by frederico-klein** [comment]
I've encountered this problem when trying to save runs to a samba mount. 

In my case I should have turned symlinks for users when mounting the share (with the `mfsymlinks` option. [See this question](https://superuser.com/questions/1337257/clients-cant-create-symlinks-on-samba-share) ). 

Just leaving this here in case someone else runs into this issue.
