### ISSUE TITLE
Display Launch Command in The Dashboard

### ISSUE THREAD

**Issue by vwxyzjn** [wandb/client#1177]
### Description

Currently the launch command is private even though the project is public, as shown below.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5555347/88679925-f53c7d80-d0bd-11ea-9a1e-63d00db608b9.png">

But sometimes showing the launch command is actually crucial to help others reproduce the results. I was wondering if it is possible to have the options to show python or launch command details.

Thanks.

**Comment by cvphelps** [comment]
Hi there, this is a good suggestion thanks Costa. I'll see if we can fix this soon.

**Comment by ariG23498** [comment]
Hey @vwxyzjn 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing inactivate threads for the time being. Please comment to reopen. :smile:

**Comment by vwxyzjn** [comment]
Hi @ariG23498, thanks for letting me know. However, I still feel this feature is quite helpful for improving reproducibility. Any chance you could reopen the ticket? Thanks.

**Comment by ariG23498** [comment]
Hey @vwxyzjn 
Thanks for the reply
I will be reopening this ticket.

**Comment by vwxyzjn** [comment]
https://wandb.ai/cleanrl/cleanrl.benchmark/runs/3f7o9vtj/overview?workspace=user- Already displays the command. Thanks and closing the issue.
