### ISSUE TITLE
Segmentation mask logging issue in wandb.Image

### ISSUE THREAD

**Issue by numpee** [wandb/client#1178]
`wandb --version && python --version && uname`
Wandb version: 0.9.2
Python version: 3.5.2
OS: Linux

* Weights and Biases version: 0.9.2
* Python version: 3.5.2
* Operating System: Linux

### Description

There is a bug in the segmentation mask logging code. Specifically, [here](https://github.com/wandb/client/blob/master/wandb/data_types.py#L1264).
The code is supposed to validate whether mask is a numpy integer array, but it calls `issubclass(mask.dtype.type, np.integer)`, while `mask` is a dictionary. I believe it should be `mask['mask_data']`? 

### Edit
I've changed this line in my local wandb source code, and it seems to be working now. Hopefully you'll fix this bug in the next version 😄

**Comment by tyomhak** [comment]
Hey there! Thank you very much for reporting, and a special thanks for pointing out the problematic line!
