### ISSUE TITLE
AttributeError: partially initialized module 'wandb' has no attribute 'Api' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ydcjeff** [wandb/client#1186]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.4
* Python version: 3.8
* Operating System: Ubuntu

### Description

`wandb` has no attribute `Api` when trying to run on my laptop and github actions.

Error message on local (macOS 10.15.6): `AttributeError: module 'wandb' has no attribute 'Api'`

Error message on github actions: `AttributeError: partially initialized module 'wandb' has no attribute 'Api' (most likely due to a circular import)`

### What I Did

[Same code from the docs](https://docs.wandb.com/library/api/examples#export-metrics-from-all-runs-in-a-project-to-a-csv-file), modified to my needs

```py
import os
import datetime
import pandas
import wandb
import json

os.environ['WANDB_API_KEY'] = '*******************************'

api = wandb.Api()

projects = api.projects()
project_list = [p.name for p in projects]
entity = [p.entity for p in projects]

summary_list = []
config_list = []
name_list = []

for i, p in enumerate(project_list):
    for run in api.runs(f'{entity[i]}/{p}'):
        # run.summary are the output key/values like accuracy.
        # We call ._json_dict to omit large files
        summary_list.append(run.summary._json_dict)

        # run.config is the input metrics.
        # We remove special values that start with _.
        config = {k: v for k, v in run.config.items() if not k.startswith('_')}
        config_list.append(config)

        # run.name is the name of the run.
        name_list.append(run.name)

    summary_df = pd.DataFrame.from_records(summary_list)
    config_df = pd.DataFrame.from_records(config_list)
    name_df = pd.DataFrame({'name': name_list})
    df = pd.concat([name_df, config_df, summary_df], axis=1)
    d = dict(df.loc[df['epoch_train_loss'].idxmin()])

    with open(f'{p}.json', 'w') as f:
        json.dump(d, f)
```

Error trace from github actions ⬇️

![Screen Shot 2020-08-05 at 15 15 07](https://user-images.githubusercontent.com/32727188/89392129-1f7de300-d72f-11ea-8c9c-d18808ad406a.png)

**Comment by tyomhak** [comment]
Thank you for reporting! Looking into this.

**Comment by tyomhak** [comment]
hey @ydcjeff can you please rename the file from wandb.py to something else, and make sure there is no file named wandb.py in the directory, and try running the code again?

**Comment by ydcjeff** [comment]
@tyomhak It's working
Really sorry for the inconvenience 🙏

**Comment by dunnkers** [comment]
For anyone stumbling on this error, but does not have any conflicting filenames; I had the same type of error:

```shell
Traceback (most recent call last):
  File "/Users/dunnkers/Downloads/wandb_uploading_just_a_table.py", line 4, in <module>
    import wandb
  File "/Users/dunnkers/.pyenv/versions/py-3.9/lib/python3.9/site-packages/wandb/__init__.py", line 62, in <module>
    from wandb import plots  # deprecating this
  File "/Users/dunnkers/.pyenv/versions/py-3.9/lib/python3.9/site-packages/wandb/plots/__init__.py", line 1, in <module>
    from wandb.plots.roc import roc as ROC
  File "/Users/dunnkers/.pyenv/versions/py-3.9/lib/python3.9/site-packages/wandb/plots/roc.py", line 10, in <module>
    chart_limit = wandb.Table.MAX_ROWS
AttributeError: partially initialized module 'wandb' has no attribute 'Table' (most likely due to a circular import)
```

→ Which was somehow fixed by re-installing wandb:

```shell
pip uninstall wandb -y; pip install wandb
```
👍🏻
