### ISSUE TITLE
Error getting url of the run

### ISSUE THREAD

**Issue by karanpathak** [wandb/client#1188]
* Weights and Biases version: 0.9.4
* Python version: 3.8.3
* Operating System: Windows 10

### Description

I wanted to get the url of the current run

### What I Did

I called the `get_url` function of the current run.

### Traceback

File "D:\KP\anaconda3\envs\torchenv\lib\site-packages\wandb\wandb_run.py", line 670, in get_url
    self._load_entity(api, network)
  File "D:\KP\anaconda3\envs\torchenv\lib\site-packages\wandb\wandb_run.py", line 618, in _load_entity
    raise CommError("Can't connect to network to query entity from API key")
wandb.apis.CommError: Can't connect to network to query entity from API key

**Comment by cvphelps** [comment]
Hi @karanpathak thanks for reporting. @raubitsj could you take a look

**Comment by cvphelps** [comment]
Hi @karanpathak it sounds like this might be a Windows issue. Would you be up for trying our new RC for the updated version of our client library? You can try installing it with the command `pip install wandb --upgrade --pre`

**Comment by karanpathak** [comment]
Thanks @cvphelps . I will try it out and post the outcome.

**Comment by ariG23498** [comment]
Hey @karanpathak 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing inactivate threads for the time being. Please comment to reopen. :smile:
