### ISSUE TITLE
ModuleNotFoundError in wandb hyperparameter tuning using sweep

### ISSUE THREAD

**Issue by Kimonili** [wandb/client#1190]
* Weights and Biases version: 0.9.4
* Python version: 3.8.5
* Operating System: Windows

### Description

I am trying to do hyperparameter tuning for a reinforcement learning project. I use sweep for that, I created a yalm file as suggested in the website and everything seemed to work as expected. (an ID was created, I can see the dashboard of the hyperparams etc). 

Although it seems that there is ModuleNotFoundError for every package I use in the script that is not build in python. For example I get errors for both pytorch and gym packages, which when I run locally in a virtual environment are imported correctly.

Should I in some way install these packages to wandb in some way? 

Thank you in advance.

### What I Did

`wandb agent k_ili/multiagent-particle-envs/128f6fo8`

```
 File "agent.py", line 5, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by vanpelt** [comment]
Hey Kimonili, this is likely due to the agent using the wrong python on your system.  By default we call `/usr/bin/env python`  You can override the `command` section of your sweep config to use the appropriate python: https://docs.wandb.com/sweeps/configuration#command

**Comment by Kimonili** [comment]
I specified the appropriate python to use but I keep getting the same error. I think that there is something wrong with the environments. 

I have installed all the packages needed to a virtual environment exclusively and not "globally" in my machine. Might that be the case that I need to specify the virtual environment in which the libraries used in the script are installed? Although I run the command from the terminal of this virtual environment so it does not make sense.

Thank you for the fast response @vanpelt !

**Comment by vanpelt** [comment]
Sometimes the virtual env does weird things to the shell environment that might not get picked up by sub procs.  The sure fire way to get this working is to explicitly set the path to the virtual environments python.  There may be some other tricks we could use to better handle venvs so I'm going to keep this ticket open.  Let me know if you're still stuck.

**Comment by Kimonili** [comment]
> The sure fire way to get this working is to explicitly set the path to the virtual environments python. 

By that you mean I should set the path of my python interpreter in the pycharm project that I am working on? Something like this:

`command:`
  `- ${env}`
  `- C:\Users\PycharmProjects\myproject\venv\Scripts\python.exe`
  `- ${program}`
  `- ${args}`

I have already specified program and args in the yalm file. Should I set something to ` ${env}` as well?

**Comment by vanpelt** [comment]
Yep, that should work.  You don't need `env` in this case.
