### ISSUE TITLE
Artifact Issue

### ISSUE THREAD

**Issue by noklam** [wandb/client#1194]
wandb --version == 0.9.3

* Weights and Biases version:
* Python version:
* Operating System:

### Description
Artifact.add_file(path)

path does not support pathlib.Path() object, currently need to manually use str(path).
![image](https://user-images.githubusercontent.com/18221871/90107591-a0665b80-dd7b-11ea-99b3-0f54679f5619.png)

**Comment by tyomhak** [comment]
Hi, thanks for reporting! @annirudh  can you please take a look at this?

**Comment by tyomhak** [comment]
@shawnlewis do I file a request ticket for this or is this a bug?

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
