### ISSUE TITLE
Agent hang up on sweep

### ISSUE THREAD

**Issue by ajay340** [wandb/client#1197]
* Weights and Biases version: 0.9.4
* Python version: Python 3.7.7
* Operating System: Ubuntu 18.04.4 LTS

### Description

Sweeping parameters hangs up and does not throw any errors or traceback.

### What I Did
In my Jupyter notebook
```
def tune():
    wandb.init(project=project)

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
    model = Sequential()
    model.add(Dense(wandb.config.first_hidden_layer, 
                    kernel_initializer=wandb.config.kernels,
                    input_dim=wandb.config.first_hidden_layer, 
                    activation=wandb.config.activation1))
    ....
    opt = wandb.config.optimizer
    model.compile(loss=wandb.config.losses, optimizer=opt, metrics=['accuracy', 'categorical_accuracy', f1_m,precision_m, recall_m])
    model.fit(
            X_train,
            y_train,
            epochs=wandb.config.epochs,
            verbose=0,
            validation_data=(X_test, y_test),
            batch_size=wandb.config.batch_size,
            callbacks=[WandbCallback(labels=labels)]
    )
    y_probas = model.predict(X_test)
    wandb.log({'pr': wandb.plots.precision_recall(y_test, y_probas, labels=labels)})
```
```
sweep_config = {
    'method': 'random',
    'parameters': {
        'activation1': {"values": ["relu"]},
        'last_activation': { "values": ['sigmoid', 'softmax']},
        'batch_size': {"values" : random.sample(range(1, 64), 3) + [100]},
        'epochs': {"values" : [1000, 1200, 1300, 1500]},
        'optimizer': {"values" : ['Nadam','Adam', 'sgd']},   
        'losses': {"values" : ['categorical_crossentropy']},
        'kernels': {"values" : ['random_normal', 'random_uniform', "truncated_normal", "glorot_normal", "glorot_uniform"]},
    }
}
sweep_id = wandb.sweep(sweep_config, project=project)
wandb.agent(sweep_id, function=tune)
```
The sweep is then created the agent says it started running, however, it does not actually run and hangs up. No metrics are recorded on the web interface.

**Comment by ajay340** [comment]
I switched from my cpu architecture to using gpus and switch back but it still hasn't solved this issue.

If anyone else having this issue?

**Comment by ajay340** [comment]
Retried notebook without making difference and it seems to work. Perhaps the api endpoint was down?

**Comment by ajay340** [comment]
Reopening because the issue because it is still recurring. When I run my notebook sometimes wandb records the model's metrics and other times it hangs up.

**Comment by vanpelt** [comment]
Hey @ajay340 This is likely due to your notebook attaching to the gpu before you run the sweep.  PyTorch / Tensorflow don't play nice with GPU's and multiprocessing.  If you move all of your imports into your train function this will work.  See: https://docs.wandb.com/sweeps/python-api#wandb-agent

**Comment by scho97** [comment]
Hi. I am reopening this issue, because I have a similar problem in a non-Jupyter environment. When you said "move all of your imports into your train function", do you mean putting `import <LIBRARY>` within my train function?

**Comment by omgwenxx** [comment]
I am encountering the same problem but running it via cli command. My output looks like the following

```
wandb: Starting wandb agent 🕵️
2024-09-11 10:50:02,794 - wandb.wandb_agent - INFO - Running runs: []
```

then it gets stuck and doesn't continue.
