### ISSUE TITLE
Logging metrics at different rates drops metrics / has inconsistent results.

### ISSUE THREAD

**Issue by jramapuram** [wandb/client#1204]
wandb, version 0.9.4
Python 3.7.8
Linux

### Description

As far as I can tell it is not possible to log metrics at different rates. My use case is as follows (but I'm sure you can contrive of a simpler use case):

- Generate metrics at every epoch
- At every  `% K` epochs request an async calculation of a time consuming metric (eg: Frechet Inception Distance such as here: https://github.com/jramapuram/async_fid) 
- The async callback pushes metrics after current epoch has passed but the data is never pushed.

```bash
test-0[Epoch 41][1600 samples][4.59 sec]:  Loss: 63.7088 -ELBO: 63.7088 NLL: 67.5594 KLD: -3.8506
wandb: WARNING Adding to old History rows isn't currently supported.  Step 20 < 42; dropping {'train_precision': 0.2194}.
wandb: WARNING Adding to old History rows isn't currently supported.  Step 20 < 42; dropping {'train_recall': 0.0014906832}.
wandb: WARNING Adding to old History rows isn't currently supported.  Step 20 < 42; dropping {'train_density': 0.06182}.
wandb: WARNING Adding to old History rows isn't currently supported.  Step 20 < 42; dropping {'train_coverage': 0.028074535}.
wandb: WARNING Adding to old History rows isn't currently supported.  Step 20 < 42; dropping {'train_fid': 92.375404}.
train-0[Epoch 42][4864 samples][58.90 sec]:  Loss: 56.6939 -ELBO: 56.6939 NLL: 60.5773 KLD: -3.8834
test-0[Epoch 42][1600 samples][4.53 sec]:  Loss: 63.7523 -ELBO: 63.7523 NLL: 67.6258 KLD: -3.8735
```

Is there a workaround to this?

**Comment by vanpelt** [comment]
The argument you pass to `step` must always increase.  If you have other steps you want to use a x-axis to plot metrics against you can add them to the dictionary.  I.E. `wandb.log({"acc": 1, "batch": 120})`.  This will enable you to choose a custom x-axis in the ui and plot "acc" against "batch" as an x-axis instead of the default "step".

**Comment by jramapuram** [comment]
@vanpelt : thanks, seems like a reasonable workaround. Is it possible to join two plots with this though? ie:

- plot1: (x, y)
- plot2: (x2, y2)

Ideally you want to be able to join on x here (especially in most ML cases where the step is either batch or epoch). In the FID case above the x-axis on both plots is the same (epoch), but it is just not possible to post to the FID graph at a later time during training.

**Comment by lukas** [comment]
Yes - our system is designed to make this work

**Comment by jramapuram** [comment]
Ok then, closing this, thanks!

**Comment by jramapuram** [comment]
I tested this solution but it doesnt work as expected. My async callback is:

```python
def loss_lbda(metrics_map, epoch, prefix):
    """This function is called when the metrics are returned from a remote server"""
    print("received {} @ epoch {}".format(metrics_map, epoch))
    wandb.log({'train_fid': metrics_map['train_fid_mean', 'epoch': epoch}, commit=False)

# some other metrics registered with wandb.log for different steps (but all posted with 'epoch' key and value)
wandb.log({})
```

This results in:

```bash
train-0[Epoch 53][32 samples][3.48 sec]:         Loss: 212.0825 -ELBO: 212.0825 NLL: 211.0835   KLD: 0.9990
test-0[Epoch 53][32 samples][1.75 sec]:  Loss: 210.1963 -ELBO: 210.1963 NLL: 209.1403   KLD: 1.0560
received {'precision_mean': 0.0576, 'recall_mean': 0.1029, 'density_mean': 0.01206, 'coverage_mean': 0.0006, 'fid_mean': 208.79129} @
 epoch 20
train-0[Epoch 54][32 samples][3.58 sec]:         Loss: 211.5856 -ELBO: 211.5856 NLL: 210.5278   KLD: 1.0578
test-0[Epoch 54][32 samples][1.75 sec]:  Loss: 213.8170 -ELBO: 213.8170 NLL: 212.8823   KLD: 0.9347
```

However even with `epoch` set as the x-axis the plot generated later does not update to the correct epoch and instead reflects the step it was posted at (~step 54 above):
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/8204807/90452341-338df100-e0ee-11ea-8473-41363e898a93.png">

I refreshed the page to no avail.

**Comment by vanpelt** [comment]
Hey @jramapuram can you share a link to the run in question and the specific metric you're looking at?

**Comment by jramapuram** [comment]
http://neuralnetworkart.com:8080/jramapuram/kpp3d_devbox/runs/3v7ef099/overview?workspace=user-jramapuram

**Comment by vanpelt** [comment]
Hey @jramapuram I took a look at the raw data using the api with the following commands:

```
import wandb
api = wandb.Api()
run = api.run("jramapuram/kpp3d_devbox/3v7ef099")
df = run.history()
df[['epoch','train_fid']].dropna()   
```

This returns:

```
     epoch   train_fid
53      54  208.791290
86      87  190.593033
100    100  186.474792
```

It looks like your code isn't actually calling `wandb.log` with train_fid before epoch 54.

**Comment by jramapuram** [comment]
Hey @vanpelt ,

Thanks for looking into this; your time is appreciated! I added even more logging to check if it is on my side and I don't believe it is. Here is the dict recorded at each call:

```bash
logging {'epoch': 45, 'test_bits-per-dim-recon': 0.3932685852050781}
logging {'epoch': 45, 'test_bits-per-dim-elbo': 0.3973080515861511}
test-0[Epoch 45][32 samples][1.87 sec]:  Loss: 215.9081 -ELBO: 215.9081 NLL: 213.7129   KLD: 2.1952
logging {'epoch': 45, 'train_learning-rate': 0.000671010071662834}
saving existing model to /home/jramapuram/experiments/kpp3d/models/kpp3dv26_04_tbmnist_bs32_e100_el64_mip0.1_ws4_ms32_ftglow_mc1_mrs16_wltc_wlmsine_mcps1_ntB_rt
N_aped0.9_elttsm_r18_elmsine_eai_dltc_dlmsine_dai_ls512_ebc32_ecm2_dbc512_dcm0.5_kb1_wd0.001_l0.001_luscos_w10_oladam_nr1_os10.th
received {'precision_mean': 0.0031, 'recall_mean': 0.0009, 'density_mean': 0.00066, 'coverage_mean': 0.0005, 'fid_mean': 161.03168} @ epoch 20

# See below
logging {'epoch': 20, 'train_precision': 0.0031}
logging {'epoch': 20, 'train_recall': 0.0009}
logging {'epoch': 20, 'train_density': 0.00066}
logging {'epoch': 20, 'train_coverage': 0.0005}
logging {'epoch': 20, 'train_fid': 161.03168}

logging {'epoch': 46, 'train_loss': 217.0189971923828}
logging {'epoch': 46, 'train_elbo': 217.0189971923828}
logging {'epoch': 46, 'train_nll': 214.8604278564453}
logging {'epoch': 46, 'train_kld': 2.158548593521118}
logging {'epoch': 46, 'train_kl-beta': 0.015384615384615385}
logging {'epoch': 46, 'train_proxy': 0.0}
logging {'epoch': 46, 'train_mut-info': 0.0}
logging {'epoch': 46, 'train_memory-difference-norm': 0.028450028970837593}
logging {'epoch': 46, 'train_bits-per-dim-recon': 0.3953801691532135}
logging {'epoch': 46, 'train_bits-per-dim-elbo': 0.3993522822856903}
train-0[Epoch 46][32 samples][3.60 sec]:         Loss: 217.0190 -ELBO: 217.0190 NLL: 214.8604   KLD: 2.1585
```

The data written into the internal database seems incorrect, so querying it will produce the results you see.  But I guess this eliminates the issue being on the frontend.

Here is the run with more logs:
http://neuralnetworkart.com:8080/jramapuram/kpp3d_devbox/runs/2ge6v790/overview?workspace=user-jramapuram

**Comment by jramapuram** [comment]
Here is a simplified example example that seems to not work as expected:

```python
import os
import wandb
import time
import threading

# init wandb
os.environ['WANDB_BASE_URL'] = 'http://neuralnetworkart.com:8080'
wandb.init(
    name='test',
    resume=True,
    dir='/tmp/wandb'
)


def post_async():
    """Simple helper that sleeps and pushed new_metric every """
    for i in range(10):
        value, epoch = 5, i
        print("[async] posting with value {} @ epoch {}".format(value, epoch))
        wandb.log({'async_metric': value, 'epoch': i}, commit=False)
        time.sleep(1)


# Spinup parallel job
thd = threading.Thread(target=post_async)
thd.start()
time.sleep(1)  # a small wait to start posting normal_metrics

# Normal sync jobs
for i in range(20, 30):
    value, epoch = 8, i
    print("[sync] posting with value {} @ epoch {}".format(value, epoch))
    wandb.log({'normal_metric': value, 'epoch': epoch}, commit=True)

thd.join()
wandb.log({})  # Make sure we get a final commit
```

Here is the [result](http://neuralnetworkart.com:8080/jramapuram/async_tests/runs/ksd9xt59?workspace=user-jramapuram)

The `async_metric` should only exist between epoch 0 and 10, and the normal_metric between to 30, however async metric seems to extend all the way to 20:
![image](https://user-images.githubusercontent.com/8204807/90572305-f855f580-e1b3-11ea-8660-75ccef499e16.png)

```bash
[async] posting with value 5 @ epoch 0
[async] posting with value 5 @ epoch 1
[sync] posting with value 8 @ epoch 20
[sync] posting with value 8 @ epoch 21
[sync] posting with value 8 @ epoch 22
[sync] posting with value 8 @ epoch 23
[sync] posting with value 8 @ epoch 24
[sync] posting with value 8 @ epoch 25
[sync] posting with value 8 @ epoch 26
[sync] posting with value 8 @ epoch 27
[sync] posting with value 8 @ epoch 28
[sync] posting with value 8 @ epoch 29
[async] posting with value 5 @ epoch 2
[async] posting with value 5 @ epoch 3
[async] posting with value 5 @ epoch 4
[async] posting with value 5 @ epoch 5
[async] posting with value 5 @ epoch 6
[async] posting with value 5 @ epoch 7
[async] posting with value 5 @ epoch 8
[async] posting with value 5 @ epoch 9
```

**Comment by sydholl** [comment]
n the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
