### ISSUE TITLE
Logging Precision Recall Multiclass Labeling issue

### ISSUE THREAD

**Issue by ajay340** [wandb/client#1207]
* Weights and Biases version: 0.9.5
* Python version: 3.7.7
* Operating System: Ubuntu

### Description

My multiclass classification model produces a matrix with 3 columns to which it I put three items as its labels. However, when I try to log the model's precision and recall I receive an error saying the labels are mismatched.

### What I Did

```
y_probas = model.predict(X_test)
wandb.log({'pr': wandb.plots.precision_recall(y_test, y_probas, labels=["label1", "label2", "label3"])})
```

and I receive this traceback

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/wandb/wandb_agent.py", line 64, in _start
    function()
  File "<ipython-input-11-5e53f86ad550>", line 27, in tune
    wandb.log({'pr': wandb.plots.precision_recall(y_test, y_probas, labels=labels)})
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/wandb/plots/precision_recall.py", line 46, in precision_recall
    binarized_y_true = scikit.preprocessing.label_binarize(y_true, classes=classes)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/sklearn/preprocessing/_label.py", line 650, in label_binarize
    .format(classes, unique_labels(y)))
ValueError: classes [0. 1.] mismatch with the labels [0 1 2] found in the data
```

**Comment by vanpelt** [comment]
Hey @ajay340 you're specifying 3 labels but your y_probas only has two.  Changing it to `wandb.log({'pr': wandb.plots.precision_recall(y_test, y_probas, labels=["label1", "label2"])})` should work.

**Comment by ajay340** [comment]
> Hey @ajay340 you're specifying 3 labels but your y_probas only has two. Changing it to `wandb.log({'pr': wandb.plots.precision_recall(y_test, y_probas, labels=["label1", "label2"])})` should work.

Here is what my y_test looks like:
```
[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]]
```
and here is what my y_probas looks like:
```
[[3.42467862e-13 6.41496900e-09 1.00000000e+00]
 [9.71979320e-01 2.80205794e-02 9.68188303e-08]
 [9.82566357e-01 1.74336545e-02 1.17806103e-08]
 ...
 [3.37857387e-09 4.82112512e-07 9.99999523e-01]]
```
Both of them have 3 columns yet its saying there is a mismatch

**Comment by ajay340** [comment]
> Hey @ajay340 you're specifying 3 labels but your y_probas only has two. Changing it to `wandb.log({'pr': wandb.plots.precision_recall(y_test, y_probas, labels=["label1", "label2"])})` should work.

@vanpelt Also just tried switching to two labels and I am getting the same issue with the same traceback.

**Comment by ajay340** [comment]
@vanpelt Here is a full example of this error happening:

```
wandb.init(project=project)
y_test = [[0., 1., 0.],[1., 0., 0.],[1., 0., 0.]]
y_probas = [[3.42467862e-13, 6.41496900e-09, 1.00000000e+00], [9.71979320e-01, 2.80205794e-02, 9.68188303e-08]
,[9.82566357e-01, 1.74336545e-02, 1.17806103e-08]]
wandb.log({'pr': wandb.plots.precision_recall(y_test, y_probas, labels=["label1", "label2", "label3"])})
```

**Comment by lavanyashukla** [comment]
Hi Ajay,

PR curves are usually used to analyze results from binary classification problems.

In order to extend it to a multi-class problem, please binarize the output first. You can read more about how to do so in the [scikit docs](https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html).

Let me know if have more questions!

**Comment by ubiest** [comment]
I get the same issue doing a multi-label classification with fastai 
With y_probas, I get this message (I have 9 labels): 
`ValueError: classes [0 1] mismatch with the labels [0 1 2 3 4 5 6 7 8] found in the data`

Whether y_probas consists of the raw probability values or it is converted into class labels as 0s and 1s (ie, the output is binarized, as suggested by @lavanyashukla above), the result is the same. 

Afterwards, I also looked into changing from the binarized output to one that uses all 9 class labels. The error message that ensues is this one:
`ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.`

I'll make sure to post some further details later today.

**Comment by sydholl** [comment]
Hi @ubiest, we wanted to follow up on this issue. Were you able to gather any additional details?
