### ISSUE TITLE
"CommError, Whoa, you found a bug." when uploading files to misconfigured wandb local

### ISSUE THREAD

**Issue by dniku** [wandb/client#1208]
* Weights and Biases version: 0.9.5
* Python version: 3.7.8
* Operating System: Linux

### Description

I am trying to set up `wandb local`. I entered the machine's address on the admin page (in the format `http://<ip>:8080`), but now due to network topology I am trying to log to that instance using an `ssh` tunnel: the machine where I am running training code has its local port 8080 forwarded to the 8080 port of the machine where `wandb local` is running. When I tried to log something to wandb, I got errors like

```
wandb: ERROR Error uploading "wandb-events.jsonl": CommError, Whoa, you found a bug.
wandb: ERROR Error uploading "wandb-history.jsonl": CommError, Whoa, you found a bug.
wandb: ERROR Error uploading "output.log": CommError, Whoa, you found a bug.
...
```

I traced the error to [this line](https://github.com/wandb/client/blob/02bbade81a2cfa4961dc09e3449112d4582a2c1d/wandb/apis/__init__.py#L79). Adding a `print(err)` statement next to it, I got a more meaningful error message as follows:

```
403 Client Error: Forbidden for url: http://<ip>:8080/local-files/<team>/sample-project/2j7f41g6/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<random string>%3D%3D%2F20200819%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20200819T155213Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=<some long hash>
```

I see two unrelated problems here:

1. The true error message is suppressed. Instead, a useless `Whoa, you found a bug` is printed.
2. The wandb instance always expects that clients connect to it using the same hostname. This might not be the case due to weird network restrictions.

**Comment by vanpelt** [comment]
Thanks @dniku we're working on a new SDK release with better error messages.  Should be out in a couple weeks.  The local hostname issue is something we're tracking and hope to address soon as well.  I'll keep this ticket open and update once we've addressed both issues.

**Comment by jramapuram** [comment]
I also ran into this error, but for a different reason: the storage on the server had been exhausted.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
