### ISSUE TITLE
How to delete locally saved files

### ISSUE THREAD

**Issue by jh-yi** [wandb/client#1213]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.5
* Python version:3.7.6
* Operating System: Ubuntu 18.04

### Description

It seems that locally saved files and synchronized files in the cloud are separated, right? Deleting a run in W&B Dashboard will not automatically delete its corresponding local files and vice versa. And the command "$ wandb gc" only shows "no runs older than 24 hours found". 

Can anyone tell me how can delete runs both locally and remotely?

Besides, the locally saved directory has a name consist of "run-time-id". Can we simply define id as dir name?

**Comment by raubitsj** [comment]
@jh-yi we are working on tools to help you manage your local files.. We do have an option to specify how your directories are named.  I will update this bug when the feature is available in a release candidate.

**Comment by jh-yi** [comment]
Thanks a lot for your quick reply. 

Btw, I also wonder if we can move one run from A project to B project?

**Comment by cvphelps** [comment]
Sure, you can move them in the UI: https://docs.wandb.com/app/features/sidebar#move-runs-between-projects

**Comment by jh-yi** [comment]
> Sure, you can move them in the UI: https://docs.wandb.com/app/features/sidebar#move-runs-between-projects

Thanks!

**Comment by karthi0804** [comment]
Hi, 
I have a doubt. I am using Wandb local and I find that the local runs and the W&B dashboard are not synchronized. Then to which place in the local filesystem, the dashboard is pointing to? or that is uploaded to the cloud? Please help me @cvphelps

**Comment by vanpelt** [comment]
Hey @karthi0804 when you're using wandb/local you need to either set WANDB_BASE_URL to the address of your local installation or run `wandb login --host=http://YOUR_LOCAL_IP_ADDRESS:AND_PORT`

**Comment by karthi0804** [comment]
> Hey @karthi0804 when you're using wandb/local you need to either set WANDB_BASE_URL to the address of your local installation or run `wandb login --host=http://YOUR_LOCAL_IP_ADDRESS:AND_PORT`

Hi, i did that. I can see syncing works when a new run is created. But during deletion, i don't see the proper sync.

**Comment by vanpelt** [comment]
@alekhka you can run `wandb sync --clean`

**Comment by william-davies** [comment]
Hello!

I don't want to delete an entire run. But I want to delete some files associated with a run. I have deleted the files locally, but they are still present on the wandb.ai website. I tried using `wandb sync` to try to sync the online files with my local files, but I keep getting `wandb: No runs to be synced.`:

```
Wills-MacBook-Pro:files williamdavies$ wandb sync --id ytenhze8 --include-online --include-offline --include-synced
wandb: No runs to be synced.
```

I can't see a way to delete the online files via the GUI either. Sorry for the hassle, but I would be very grateful if someone could please let me know how to:
1. Ideally sync the online files with the offline files
2. If that's not possible, at least delete the online files

Thanks so much!

```
Wills-MacBook-Pro:files williamdavies$ wandb --version && python --version && uname
wandb, version 0.10.33
Python 3.7.10
Darwin
```

**Comment by vanpelt** [comment]
You can manage the files stored inside of wandb.ai via the storage explorer accessible from your "/settings" page.  The url of the storage explorer is: `https://wandb.ai/storage/YOUR_USERNAME`

**Comment by william-davies** [comment]
> You can manage the files stored inside of wandb.ai via the storage explorer accessible from your "/settings" page. The url of the storage explorer is: `https://wandb.ai/storage/YOUR_USERNAME`

Thank you so much, Chris! That worked perfectly :)
