### ISSUE TITLE
Web client artifact file view error: 'Cannot query field "defaultCloudRegion" on type "ServerInfo"'

### ISSUE THREAD

**Issue by alexmirrington** [wandb/client#1216]
* Weights and Biases version: 0.9.5
* Python version: 3.8.5
* Operating System: Arch Linux
* Kernel: 5.8.3-arch1-1

### Description

Artifact is accessible via `wandb.Artifact.download()` but trying to view files tab in the browser yields the following error:

> Cannot query field "defaultCloudRegion" on type "ServerInfo". Did you mean "availableCloudRegions"?

![20200828-144623](https://user-images.githubusercontent.com/34053287/91522447-975db880-e93d-11ea-8834-a0b596084dec.png)

### What I Did

A preprocessed dataset (size approximately 404MiB) was uploaded via `wandb.run.log_artifact()`. The preprocessing run finished without error, and the `wandb` reported syncing the dataset successfully:

```Text
wandb: Program ended successfully.
wandb: Syncing 5 W&B file(s), 0 media file(s), 6 artifact file(s) and 0 other file(s)
wandb: ✨ W&B sync reduced upload amount by 90.0%             
``` 

Opening the run in the web client (from both slack notification, CLI url and manually selecting the run), clicking on the related artifact and selecting the files tab yields the above error. Error persists after 10 minutes.

I have not changed my default cloud storage region since creating my account.

**Comment by cvphelps** [comment]
Hi, thanks for letting us know. @annirudh could you take a look

**Comment by annirudh** [comment]
Apologies for the inconvenience. This issue was caused by an out of order deploy. It should be resolved now.
