### ISSUE TITLE
Web-UI: List of run output artifacts cannot display >500 elements

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1223]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.5
* Python version: 3.6.10
* Operating System: Win10
* Browser: Google Chrome v.84.0.4147.135

### Description

I use artifacts to track the checkpoint files (the artifact version is updated on every epoch) and for some other run-related info. When the number of epochs goes above 500, I run into troubles: 

on the "Output artifacts" page of the run web-interface, only the first 500 recordings are displayed, and I could not find the way to get the links to what was recorded after. 
Has the page lost the paging navigation? 

Here is an example run 
https://app.wandb.ai/maria_korosteleva/Garments-Reconstruction/runs/fdn9uzmz/artifacts?workspace=user-maria_korosteleva

**Comment by cvphelps** [comment]
Hi Maria, thanks for your message. I've emailed you — let's get on a quick call to talk about how you're using artifacts

**Comment by cvphelps** [comment]
Hi Maria! @annirudh and @laxels helped fix this issue, and it should be resolved in production. Could you please take a look?

**Comment by maria-korosteleva** [comment]
It's working like a charm, I can see all of the outputs now =) 
Thank you all very much!
