### ISSUE TITLE
How to check my storage

### ISSUE THREAD

**Issue by jh-yi** [wandb/client#1226]
### Description

Hi, I know that for personal account there is a limitation of 200GB data storage. Then where can I check my used/available memory and memory of each run. Besides, is it possible to delete e.g. media/ or checkpoint under "Files" on dashboard? 

Thanks a lot in advance!

**Comment by vanpelt** [comment]
Hey @jh-yi we're actively working on this.  We'll update this ticket once it's been released.

**Comment by jh-yi** [comment]
Thanks for your quick reply. I also found it would be nice to delete some columns in "Table" instead of hiding them, as sometimes I stored all the args in the beginning but later on some of them turned out to be useless (especially when I log all the args from different implementations, and when I want to recover a column among too many hidden columns). Anyways thanks a lot for this powerful tool. It really helps a lot！

**Comment by jh-yi** [comment]
@vanpelt Thanks for your quick reply. I also found it would be nice to delete some columns in "Table" instead of hiding them, as sometimes I stored all the args in the beginning but later on some of them turned out to be useless (especially when I log all the args from different implementations, and when I want to recover a column among too many hidden columns). Anyways thanks a lot for this powerful tool. It really helps a lot！

**Comment by RishalAggarwal** [comment]
Hey, just wanted to check if there is a way now to check our storage

**Comment by jh-yi** [comment]
> Hey, just wanted to check if there is a way now to check our storage

HI, I think you can check it here: https://wandb.ai/subscriptions

**Comment by hyeseung-of-dable** [comment]
Hi. I want to delete some columns in Table, too. 

> I also found it would be nice to delete some columns in "Table" 
Could you share how to delete some columns?

**Comment by vanpelt** [comment]
Hey @hyeseung-of-dable you can't currently delete columns, but you can toggle their visiblity.  Click the 3 vertical dots and choose "Hide Column".
