### ISSUE TITLE
Artifacts: Run outputting many versions causes page to hang and then crash

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1228]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.5
* Python version: 3.6.10
* Operating System: Win10
* Browser: Google Chrome v.85.0.4183.83 

### Description

For some of my runs, the artifacts page refuses to load. It hangs and eventually crashes with memory error e.g. 
https://app.wandb.ai/maria_korosteleva/Garments-Reconstruction/runs/veeany7a/artifacts?workspace=user-maria_korosteleva

There is also some Error in browser Console
![image](https://user-images.githubusercontent.com/6837635/92206488-8de6ca00-eec2-11ea-861e-d60fcaff3d52.png)

There are runs, for which the page loads just fine: https://app.wandb.ai/maria_korosteleva/Garments-Reconstruction/runs/29iczuwn/artifacts?workspace=user-maria_korosteleva

### What I did

It started to happen with the runs when I started to upload an additional artifact with multiple versions. 
Previously, I had 3 artifacts created within a run, one of which added with many versions (checkpoints after every epoch), for the other two, only one new version is created per run => page loads fine
Now I have 4 artifacts, two of which are created with a number of versions => Page crashes

**Comment by cvphelps** [comment]
Hi Maria, thanks for filing this. @annirudh could you take a look

**Comment by cvphelps** [comment]
@maria-korosteleva thanks for sharing a link to a page that is working correctly. Could you please share a link to a page that crashes?

**Comment by maria-korosteleva** [comment]
@cvphelps, the very first link is the one with the problem. Does it open correctly for you?

**Comment by annirudh** [comment]
Hi @maria-korosteleva, thanks for the detailed bug report! I have a fix for the issue that we'll deploy ASAP. Once the fix is live, I'll circle back with you here.

**Comment by annirudh** [comment]
@maria-korosteleva The issue should be fixed now. Sorry for any inconvenience this caused!
