### ISSUE TITLE
Predicted bounding boxs overwritten by ground truth boxes when images passed as a list

### ISSUE THREAD

**Issue by davisj147** [wandb/client#1245]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.10.1
* Python version: 3.7.3
* Operating System: Linux

### Description

I am attempting to log a row (one batch) of images with corresponding ground truth and predicted bounding boxes.
However, when passing the images in as a list to wandb.log, the predicted bounding boxes are overwritten by the ground truth boxes, despite having unique keys in the dictionary as per the documentation. Thus, only one boxes meta-file with their coordinates is produced so predicted and ground truth boxes are shown on top of each other.

Minimal example below:

### What I Did

```
import wandb
import numpy as np
wandb.init()

image = np.zeros((500, 500, 3))
img = wandb.Image(image, boxes={
    "predictions": {
        "box_data": [{
            "position": {
                "minX": 0.1,
                "maxX": 0.2,
                "minY": 0.3,
                "maxY": 0.4,
            },
            "class_id" : 1,
            "box_caption": "pred",
        }
        ]
    },
    "ground_truth": {
        "box_data": [{
            "position": {
                "minX": 0.2,
                "maxX": 0.4,
                "minY": 0.7,
                "maxY": 0.8,
            },
            "class_id" : 1,
            "box_caption": "ground_truth",
        }]
    }
})

## Bug - Predicted bounding box is overwritten by ground truth box
wandb.log({"log_as_list": [img, img]})

## Works, but images are shown in different sections
[wandb.log({"seperate_logs"+str(i): x}) for i, x in enumerate([img, img])]
```

**Comment by tyomhak** [comment]
Hi @davisj147, thank you for reporting. We are currently looking into this.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
