### ISSUE TITLE
wandb.restore not respecting run_path

### ISSUE THREAD

**Issue by rahular** [wandb/client#1246]
* Weights and Biases version: 0.10.1
* Python version: 3.7.7
* Operating System: Linux-3.10.0

### Description

I am trying to restore a previously trained model from a different run by specifying the `run_path`. But it still seems to be ignoring it and searching in the current run's folder.

### What I Did

```
> load_path = wandb.restore("best_model.th", run_path="rahular/nlp/o9yf2jxr")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wjv316/anaconda3/envs/pos-bert/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 855, in restore
    raise ValueError("File {} not found.".format(path))
ValueError: File wandb/run-20200918_164521-1n2653n1/files/best_model.th not found.
```

**Comment by KyleGoyette** [comment]
Hi @rahular, it looks like the run in question used wandb version 0.10.1, so the file isn't saved to `rahular/nlp/o9yf2jxr`. It could be saved to your next run which seems to be have been run in parallel, but it will exist on your machine in the `wandb/run-*-o9yf2jxr/files` directory, under your project.

You did find an issue in our messaging for cases where restoring a file failed. Thank you for that, and good luck.
