### ISSUE TITLE
New version doesn't support save_code as a parameter in init function.

### ISSUE THREAD

**Issue by yooceii** [wandb/client#1248]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.10.0 and 0.10.1
* Python version: 3.6.10
* Operating System: Ubuntu 18.04.4 LTS

### Description

The save_code parameter is not in the init function anymore.

### What I Did

```
wandb.init(save_code=True)
init() got an unexpected keyword argument 'save_code'
```
I don't know if it is intended, but the doc still shows the "save_code" as one accepted parameter for the init function.

**Comment by raubitsj** [comment]
@yooceii , thanks for the report, this was an oversight and it will be fixed in the 0.10.2 release which we are working on now.

**Comment by eyaler** [comment]
still seeing this on 0.10.2

**Comment by vanpelt** [comment]
Unfortunately this didn't make the 0.10.2 release, it will definitely be in 0.10.3 which should be released in the next few days.  In the meantime you should be able to set `os.environ['WANDB_SAVE_CODE'] = "true"` to have the same behavior as setting this via wandb.init.

**Comment by louiskirsch** [comment]
By the way, are there any other breaking changes when upgrading from `0.9.7` to `0.10.x` ? Is there an api changelog somewhere?

**Comment by vanpelt** [comment]
Our changelog is available here: https://github.com/wandb/client/blob/master/CHANGELOG.md

**Comment by RamanHacks** [comment]
The issue still presists. Unable to save_code or log_model when using the latest wandb (version 0.10.12) in colab! Please help!

**Comment by vanpelt** [comment]
Hey @RamanHacks I've confirmed save_code works with wandb.init in 0.10.12.  I'm not familiar with a `log_model` option.  Can you share a colab or some code that you're trying to execute?

**Comment by RamanHacks** [comment]
> Hey @RamanHacks I've confirmed save_code works with wandb.init in 0.10.12.  I'm not familiar with a `log_model` option.  Can you share a colab or some code that you're trying to execute?

Okay! The issue is when I am using wand logger inside pytorch lightning! Only the logs get passed to wandb server not the code/model! But things work totally fine with ver:0.9.7!

**Comment by vanpelt** [comment]
That sounds like an issue with the Pytorch Lightning version, not the wandb version.  What version of PytorchLightning are you using?

**Comment by RamanHacks** [comment]
`wandb_logger = WandbLogger(name=config.WANDB_NAME,project='Named Entity Recognition', log_model=config.LOG_MODEL, save_code=True)`

** save_code=True** is the **kwarg that get passed to wandb initializer!

PL version is 1.1.3 which is the stable release as of now!

**Comment by vanpelt** [comment]
Pytorch Lightning calls model.save when it's finalized: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/wandb.py#L191

If you can create a colab or snippet that consistently reproduces your issue along with any errors you're seeing we can get to the bottom of what's up.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
