### ISSUE TITLE
Fail to load file-based configs

### ISSUE THREAD

**Issue by kaixin96** [wandb/client#1249]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.10.1
* Python version: 3.7.7
* Operating System: Ubuntu 16.04.5 LTS (Xenial Xerus)

### Description

Fail to load file-based configs (either with `config-defaults.yaml` or using command line argument `--configs special-configs.yaml`. Configurations within yaml file are not loaded into `wandb.config` nor logged to `run_folder/files/config.yaml`.

### What I Did

```bash
python test_yaml.py
```

```bash
python test_yaml.py --configs config-defaults.yaml
```

Within `test_yaml.py`:
```python
import wandb
wandb.init()
wandb.join()
```

**Comment by tyomhak** [comment]
Hi @kaixin96 , can you please update wandb, and see if the issue persists?

**Comment by kaixin96** [comment]
Hi @tyomhak , the issue persists under wandb 0.10.2. Though I found explicitly specifying `WANDB_CONFIG_PATHS` works. But one new issue is that wandb does not support yaml files containing complex python tags.

Initially I thought the user-specified yaml config file would be directly merged into `run_folder/files/config.yaml`. However, it seems wandb also use json to serialize config object, which precludes using complex python tags. I don't quite get why the config dict need to be json-serialized, given that the final output file is also in yaml.

Can you help look into it ? Thank you.

**Comment by tyomhak** [comment]
@raubitsj can you please help here?

**Comment by Dewald928** [comment]
Same here. Since version 10, my `config-defaults.yaml` isn't being read.

**Comment by kaixin96** [comment]
Is there any updates on this issue?

**Comment by vanpelt** [comment]
Hey @kaixin96 apologies for not updating this ticket.  This was fixed in version 0.10.6 on Oct. 15th: https://github.com/wandb/client/blob/master/CHANGELOG.md#0106-october-15-2020

**Comment by rvinas** [comment]
I'm having similar issues with version 0.10.14. The command:
`python test_yaml.py --configs CONFIG_FILE.yaml`
results in an empty `wandb.config` dict.

**Comment by Dewald928** [comment]
I haven't tested it again.

But first try putting the contents of that config file into ```config-defaults.yaml``` and rerun it without the --configs.
If that doesn't work, try version 0.10.6.

**Comment by rvinas** [comment]
The default config file `config-defaults.yaml` works with version 0.10.15. However, the --configs argument appears to be broken (e.g. I cannot load another config file). I ended up using `argparse` and `yaml` myself to read the parameters of another config file.
