### ISSUE TITLE
W&B data tranmission

### ISSUE THREAD

**Issue by sgummidipundi** [wandb/client#1254]
### Description

Not so much a problem, but more of a question. I get the following warning message:

wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.

I wanted to make sure that although I'm not logged or set any project, that no data is actually transmitted to W&B. If I did specify an API key, would the only thing that are sent is hyperparatemeters and weights?

**Comment by vanpelt** [comment]
You can set `WANDB_MODE=offline` to ensure data is only synced to your local filesystem.  You can also run a local server to ensure no data leaves your network:  https://docs.wandb.com/self-hosted/local

When you call `wandb.init` in your script we capture metadata about the system such as os version, python dependencies, the original command that was run, and git repo metadata.  We can also save the code that was run, but that's disabled by default.  You can set it at `https://wandb.ai/settings` if you're using our cloud server.  Depending on the integration use we can log examples from datasets or generated model weights.  Our default keras integration just saves hyperparameters and the best weights, you can disable weight saving by setting `save_model=False`.  More information about what data is saved is here: https://docs.wandb.com/company/data-and-privacy

**Comment by sgummidipundi** [comment]
Just to provide some context, I am using https://github.com/ThilinaRajapakse/simpletransformers, which popped up something on the integration.

So unless an API or project is specified using the wand.init(), no data could be transmitted?

**Comment by cvphelps** [comment]
@sgummidipundi yes that's right, no data will be sent to an account if you don't login or specify and API key
