### ISSUE TITLE
Silent Mode Not Working in Terminal

### ISSUE THREAD

**Issue by michaelmyc** [wandb/client#1268]
## Issue:
Silent mode doesn't seem to work in terminal. There are still lines with `wandb:` polluting terminal outputs. This is interfering with outputs of `tqdm` making my terminal logs unreadable. 

## Environment:
- python: 3.8.5
- wandb: 0.10.2
- tqdm: 4.48.2

## Reproduce:
```py
import os
import wandb

os.environ["WANDB_SILENT"] = "true"
wandb.init()
```

## Comments:
I noticed #457 mentioned that a fix was supposed to address this by August, did the fix not make it to production yet?

**Comment by tyomhak** [comment]
Hey @6etacat , thanks for flagging this. We're looking into it.

**Comment by ariG23498** [comment]
Hey @farizrahman4u would you like to look into this? I have noticed a recent PR of yours that was merged that dealt with the silent mode. An update here would be great. :smile:

**Comment by farizrahman4u** [comment]
@ariG23498 It has been fixed in master and will make it to the upcoming `0.10.3` release. Users can also pip install the current state of master with `python -m pip install git+https://www.github.com/wandb/client.git@master` if they wish to not wait for the release.

**Comment by ariG23498** [comment]
I am closing this issue as the solution is going to make an appearance in the next release 
We can reopen it if there is a further persisting issue.

**Comment by pkuderov** [comment]
Hello!
Have you fixed interfering with `tqdm` output? I have `0.10.22` version and it still affects the width of tqdm progress bar in both silent and non-silent mode!

First pic, **up** - non-silent mode, **down** - silent mode. Look at how short is tqdm progress bar. Second pic - I entirely commented out wandb usage (no init, etc.) and progress bar returned to normal width. It seems that you somehow edit the environment width, and I don't think it's a really good behavior.

![image](https://user-images.githubusercontent.com/699035/110800133-f311e280-828c-11eb-8db4-a5a999aae88f.png)
![image](https://user-images.githubusercontent.com/699035/110800785-9d8a0580-828d-11eb-9cbf-bc277bef652d.png)

**Comment by farizrahman4u** [comment]
@pkuderov This is fixed in the `fr_redir` branch and will be merged to master soon.
