### ISSUE TITLE
Group by run name doesn't handle run name updates

### ISSUE THREAD

**Issue by collinmccarthy** [wandb/client#1269]
Hi, 

Sorry I don't have an example for this but it should be easy to verify. This is what I did:
- Run some experiments, create a custom line plot (not sure if that matters) and group by run name
- Change some of the run names via the API
- Refresh the page to update the plot

After I change the run names I can't get the plot to group by the new names. It still has some of the old names being used instead. I waited overnight hoping it might just take some time, tried turning on and off the grouping, tried re-creating the plot from scratch (which would be a huge pain but was worth trying) but I can't get it to correctly display the new names.

Thanks in advance for your help on this!

**Comment by cvphelps** [comment]
Hi @collinmccarthy thanks for being so patient to wait overnight for this feature to work. We'll take a look.

**Comment by laxels** [comment]
Hey there @collinmccarthy. I just tried reproducing the issue but couldn't. [Here's](https://youtu.be/nXIkOWBtvks) a video of my attempt. Can you take a look to see if I misunderstood your issue?

If these exact steps don't work for you, the issue may only be present on an old version of the client. Which version of the client are you using?

**Comment by ariG23498** [comment]
Hey @laxels thanks for the video :smile: 
We are closing this issue as it has gone stale and the issue has been resolved with the version upgrades. @collinmccarthy please feel free to open this if the issue still persists in your system.
