### ISSUE TITLE
Sync tensorboard stops working in upgrade from 0.9.7 to 0.10.2

### ISSUE THREAD

**Issue by ecatkins** [wandb/client#1272]
I had been using [sync_tensorboard ](https://docs.wandb.com/library/integrations/tensorboard)with the [Tensorflow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) (`tensorflow==1.15.2`), but when upgrading to version `0.10.2` metrics are no longer logged to the wandb dashboard.

I have confirmed when downgrading to `0.9.7` the logging begins working again

**Comment by raubitsj** [comment]
@ecatkins , Thanks for reporting this issue.  Can you tell us what version of tensorboard you were using?

In the new version of the library we improved support for tensorflow 2.x and the latest pytorch but this might have inadvertently broken something with tensorflow 1.x support.

Are you manually loggging to a summarywriter or is this something that the tensorflow object detection api is doing?

**Comment by ecatkins** [comment]
`tensorboard==1.15.0`

And no, nothing manual. I was just using the events that the tensorflow object detection api logs OOTB

**Comment by koulanurag** [comment]
Facing same issue. Tensorboard events are no longer being logged in the wandb api.

**Comment by raubitsj** [comment]
@koulanurag, This is fixed now and will be in the next release: 0.10.3.  If you want to try it now use:
```
pip install --upgrade git+git://github.com/wandb/client.git
```

@ecatkins, we are still looking into your issue as I believe it is different but the fixes we did might address your problem if you were writing your tensorboard log to cloud storage (s3).

**Comment by moizsajid** [comment]
I was also facing this same problem even in version ```0.10.7.dev1```. Everything is working fine now after downgrading to version ```0.9.7``` as suggested by @ecatkins.

**Comment by vanpelt** [comment]
@moizsajid can you provide an example script and the versions of tensorflow / tensorboard you're using.  sync_tensorboard should be fixed for all version of tensorflow >= 1.15 in 0.10.3 so if you're still seeing it we need to address the bug.

**Comment by lminer** [comment]
I'm having this issue with tensorflow 2.3.1. Works fine if I save my tensorboard logs locally, but breaks when I log to s3.

**Comment by TusharNimbhorkar** [comment]
@vanpelt @ecatkins @raubitsj 
Facing the same issue. Is there any update on this?

**Comment by vanpelt** [comment]
Hey @TusharNimbhorkar what version of tensorboard are you using / how are you instantiating your SummaryWriter?

**Comment by TusharNimbhorkar** [comment]
@vanpelt 
Version:
`tensorboard==2.4.0`
`tensorboardX==2.1`

I am using tensorboardX's SummaryWriter. I have installed `tensorboard` because wandb gives me error without it. 

Command to instantiating SummaryWriter: 
`writer = SummaryWriter(output_folder)`

**Comment by vanpelt** [comment]
@TusharNimbhorkar we just made a branch that addresses support for tboardx, it will go out with in the next release.  You can use it now but installing wandb with:

```
pip install --upgrade git+git://github.com/wandb/client.git@task/tboardx#egg=wandb
```

**Comment by TusharNimbhorkar** [comment]
@vanpelt 
Thank you this fixed worked. Any idea when the next release is scheduled?

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
