### ISSUE TITLE
Finish porting parallel coordinates to react-vis

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#129]
The work was started here: https://github.com/wandb/client/tree/feature/parcoor

We need to hookup highlighting, CSS, and the custom d3.brushes on the columns as is implemented in https://github.com/wandb/client/blob/feature/parcoor/wandb/board/ui/src/components/PanelParallelCoord.js

The legacy component uses d3 version 3 and the brush API has changed: https://github.com/d3/d3/blob/master/CHANGES.md#brushes-d3-brush

**Comment by vanpelt** [comment]
@shawnlewis originally implemented this and mentioned that the react-vis implementation of parallel coordinates wasn't very performant.  It might be a better approach to port the existing component to d3 version 4, regardless the brush logic will need to be written in v4 so that's a good place to start.

**Comment by shawnlewis** [comment]
Yeah I think staying in d3 might be better but feel free to experiment.

Sorry the code is pretty terrible, it was the result of a hackathon and has
never been cleaned up.

**Comment by vanpelt** [comment]
@thekatic there's a pull request open with comments about what needs to be added.

**Comment by thekatic** [comment]
@vanpelt I've pushed new commit for this pull request.
