### ISSUE TITLE
what _step mean?

### ISSUE THREAD

**Issue by MrRace** [wandb/client#1291]
I set my save step and other parameter,therefore the global_step in the figure is meeting my expectation. However I am confused about the red arrow's `_step` 437.  I can not guess how it been calculated and its meaning？
![image](https://user-images.githubusercontent.com/10300313/94358751-acad3a80-00d5-11eb-80b7-0da912d4eebe.png)

Thanks a lot!

**Comment by tyomhak** [comment]
Hi @MrRace , let me check and get back to you on this.

**Comment by tyomhak** [comment]
It is our internal counter of the number of logged (and committed) items. If you have your own step you can ignore ours.   
We will remove that from the summary in the future.
