### ISSUE TITLE
Resolve Linter Warnings

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#130]
Let's get rid of the linter warnings before we open source the app.  You can see them all on the terminal by running yarn start in `board/ui`.

@thekatic to run a simple backend for the board/ui frontend you need to run `wandb board` in a directory where you previously ran some jobs.

**Comment by thekatic** [comment]
@vanpelt here is a new [pull request](https://github.com/wandb/client/pull/131) with all warnings sorted out, except ones related to altered module paths. 
Not sure how to tackle this. On of the solutions would be to update config-overrides and add Cloud alias, so there will be no need for try...catch.

Do you plan on open source entire frontend or just parts of it?

**Comment by vanpelt** [comment]
Everything in the "client" module will be open sourced.
