### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters when logging multiple runs

### ISSUE THREAD

**Issue by fteufel** [wandb/client#1302]
I am trying to log multiple runs from a single script, as described in the API docs using `wandb.init(reinit=True)` and `run.finish()`.
It gives a strange error that I do not understand, it seems to be output related, but it only appears at the 2nd iteration of the following loop. The first run is logged correctly to w&b and is also closed without an error.

```
for validation_partition in all_ids:
        run = wandb.init(reinit=True, name=f'Val{validation_partition}')
        logger.info('Initialized new w&b run.')
        #call main
        setattr(args, 'experiment_name', f'crossval_{test_partition}_{validation_partition}_{time.strftime("%Y-%m-%d-%H-%M",time.gmtime())}')
        best_mcc_det, best_mcc_cs = main_training_loop(args)
        result_list_det.append(best_mcc_det)
        result_list_cs.append(best_mcc_cs)
        logger.info(f'partition {validation_partition}: MCC Detection {best_mcc_det}, MCC CS {best_mcc_cs}')

        run.finish()
        logger.info(f'Finished partition {validation_partition}.')
```

```
wandb: Synced Test0_Val1: https://wandb.ai/fteufel/lm-sp-crossvalidation/runs/2i3alvte
20/09/30 00:14:47 - INFO - __main__ -   Finished partition 1.

wandb: wandb version 0.10.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.3
wandb: Syncing run Test0_Val2
Traceback (most recent call last):
  File "/zhome/1d/8/153438/experiments/py3-torch-env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 460, in init
    run = wi.init()
  File "/zhome/1d/8/153438/experiments/py3-torch-env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 398, in init
    run._on_start()
  File "/zhome/1d/8/153438/experiments/py3-torch-env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1220, in _on_start
    self._display_run()
  File "/zhome/1d/8/153438/experiments/py3-torch-env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1037, in _display_run
    click.style(project_url, underline=True, fg="blue"),
  File "/zhome/1d/8/153438/experiments/py3-torch-env/lib/python3.6/site-packages/wandb/errors/term.py", line 33, in termlog
    click.echo(line, file=sys.stderr, nl=newline)
  File "/zhome/1d/8/153438/experiments/py3-torch-env/lib/python3.6/site-packages/click/utils.py", line 272, in echo
    file.write(message)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 7-8: ordinal not in range(256)
wandb: ERROR Abnormal program exit
```

**Comment by tyomhak** [comment]
Hey @fteufel , can you please update wandb, and check if the error persists?

**Comment by fteufel** [comment]
Hi @tyomhak , yes, persists in 0.10.4

minimal example:
```
    for validation_partition in all_ids:
        run = wandb.init(reinit=True, name='test')
        logger.info('Initialized new w&b run.')

        best_mcc_det, best_mcc_cs =1, 1 #would call training loop here
        logger.info(f'partition {validation_partition}: MCC Detection {best_mcc_det}, MCC CS {best_mcc_cs}')

        run.finish()
```

**Comment by tyomhak** [comment]
Thanks, we're looking into this issue.

**Comment by xukai92** [comment]
I also meet the same issue.

**Comment by vanpelt** [comment]
This is an issue with your terminal not supporting UTF8 characters in our output.  We should detect this case, but in the meantime, setting the following in your terminal should fix this:

```
export LANG=C.UTF-8
```

You can add this to your `~/.profile` or `~/.bash_rc` if you're on linux or mac.  What OS are you guys using?

**Comment by fteufel** [comment]
hi @vanpelt ,
Thanks for figuring out the problem!
Had this error on Scientific Linux 7.7 (Nitrogen). Will give the workaround a try next time I need it.

**Comment by bjabot12** [comment]
I also have this problem, with version 0.10.12. First iteration of training works, but then second iteration fails and produces the mentioned error message for all runs after that. Tried with adding `export LANG=C.UTF-8` , but nothing changed.

**Comment by vanpelt** [comment]
Hey @bjabot12 can you try setting all of these environment variables:

```
LC_ALL=C.UTF-8
LANG=C.UTF-8
LANGUAGE=C.UTF-8
```

Additionally if you can provide the `debug.log` from the `wandb` directory relative your script that would be helpful.

**Comment by bjabot12** [comment]
This fixed it for me!

Thank you, @vanpelt!

**Comment by ariG23498** [comment]
Hey folks,
As the solution is found we are closing this issue. Feel free to reopen this ticket is the issue persists. :smile:

**Comment by fteufel** [comment]
Hi,
still doesn't do it for me.
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)
```
So ascii codec instead of latin-1 now. Problem seems to be hard to fix on Scientific Linux.

**Comment by Javier-Jimenez99** [comment]
I'm getting the same error once I reinit the train script.

**Comment by RGring** [comment]
+1. This doesn't allow me to run sweeps :(

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
