### ISSUE TITLE
Setting init directory still creates wandb folder on init

### ISSUE THREAD

**Issue by alexmirrington** [wandb/client#1354]
**System:**

- OS: `MacOS 10.15.5`
- Python: `3.8.5`
- wandb: `0.10.5`

**Steps to reproduce:**

1. Initialise a project from a python file with a changed root directory like so:

```Python
wandb.init(project="my-project", dir="results")
```

A `wandb` folder will still be created at the top level of the project despite the changed directory.

As a side note, a `wandb` folder is also created inside the `results` folder. It is likely this is intended, but it would be nice have an option to turn this off as I like to place my results in a hidden folder `.wandb`, since linting tools such as `isort` rely on top-level directories to determine which packages are part of a project and which are third-party packages. Using the default `wandb` directory causes these tools to recognise `wandb` as part of the project instead of a third party tool.

**Comment by tyomhak** [comment]
Hey @alexmirrington , thanks for flagging this. We're looking into it.
