### ISSUE TITLE
[Feature request] Plot each individual run as grouping options

### ISSUE THREAD

**Issue by 51616** [wandb/client#1355]
It would be nice if we can plot each individual run in, say, a transparent or dotted line and showing the mean of the group with a thick line (just like how grouping works now).

**Comment by lukas** [comment]
Hi @51616 - I implemented this for you, under grouping range pick "Samples"

![image](https://user-images.githubusercontent.com/29/96320561-9228fb80-0fc7-11eb-9a51-2377a75c084b.png)
