### ISSUE TITLE
How to specify project for "wandb sync"?

### ISSUE THREAD

**Issue by alsuhr-c** [wandb/client#1356]
I accidentally ran some experiments in dryrun mode, and would like to sync them online. I have a few projects (A, B, C) and ran my experiments in project B. However, when I run "wandb sync", they are sent to project A in the web interface. How can I specify that I want them to sync to project B instead?

Note: in the web interface I can move runs from one project to another, which solves this to some extent, but I just wanted to know if it's possible to do this in `wandb sync` in the first place.

**Comment by tyomhak** [comment]
Hey @alsuhr-c , the runs log to project A, even if you set the project=B in your init() function?

**Comment by tyomhak** [comment]
I see, can you check which wandb version you are using? also which OS is this happening on?
I'd like to try to reproduce this.

**Comment by vanpelt** [comment]
@alsuhr-c when you call `wandb sync` from the command line you can specify `-p` or `--project` to sync runs to that specific project.

**Comment by alsuhr-c** [comment]
Thanks!
