### ISSUE TITLE
wandb 10.x creates symlinks, which require administrator privileges on Windows

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1370]
wandb version: 10.7
Python version: 3.8.5
OS: Win 10

## Problem
Since the upgrade to wandb10.x it started to create symlinks. This is inconvenient for Windows users, as requires to run my IDE (VS Code) with administrator privileges -- few more clicks to do so.  

## Traceback
```
wandb: WARNING Symlinked 0 file into the W&B run directory, call wandb.save again to sync new files.
Traceback (most recent call last):
  File "c:/Users/Asus/Desktop/Garment-Pattern-Estimation/nn/train.py", line 129, in <module>
    trainer.fit(model)  # Magic happens here
  File "c:\Users\Asus\Desktop\Garment-Pattern-Estimation\nn\trainer.py", line 88, in fit
    start_epoch = self._start_experiment(model)
  File "c:\Users\Asus\Desktop\Garment-Pattern-Estimation\nn\trainer.py", line 154, in _start_experiment
    self.experiment.init_run(self.setup)
  File "c:\Users\Asus\Desktop\Garment-Pattern-Estimation\nn\experiment.py", line 48, in init_run
    wb.save(os.path.join(wb.run.dir, '*.json'))
  File "C:\Users\Asus\anaconda3\envs\Garments\lib\site-packages\wandb\sdk\wandb_run.py", line 919, in save
    os.symlink(abs_path, wandb_path)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\Asus\\Desktop\\Garment-Pattern-Estimation\\wandb\\run-20201016_172608-2v7x9f8u\\files\\wandb-metadata.json' -> 'wandb\\run-20201016_172608-2v7x9f8u\\files\\wandb\\run-20201016_172608-2v7x9f8u\\files\\wandb-metadata.json'
```

## Additional comment

I'm not entirely sure, but I have a suspicion that those symlinks are related to another issue -- there is a strange subdirectory in the run directory files with a path like this `MyProject/wandb/<rundirname>/files/wandb/<rundirname>/files` (duplicate path??). This is also visible in the traceback final paths.

**Comment by vanpelt** [comment]
A quick fix is to write the file a file directly into `wandb.run.dir` and then call save which will bypass the symlink.  In a future release we'll switch to copying instead of symlinking.

**Comment by mohamedr002** [comment]
I have a similar problem can you please clarify more about this fix of wandb.run.dir

**Comment by vanpelt** [comment]
Hey @mohamedr002 we'll be releasing a version of the library on Tuesday of next week that fixes this issue in windows.  Regarding wandb.run.dir:

```
import shutil
shutil.copy("C://path/to/file.h5", os.path.join(wandb.run.dir, "file.h5"))
```

Will copy a file to the wandb directory which is automatically synced and would bypass he symlink issue.

**Comment by hobogalaxy** [comment]
@vanpelt Hi, this still hasn't been patched yet or am I wrong? Because I still get  "OSError: symbolic link privilege not held" when calling wandb.save()

**Comment by vanpelt** [comment]
Hey @hobogalaxy we didn't push a symlinking fix to wandb.save in the last release.  For now I suggest either writing your files directly to `wandb.run.dir` and then calling wandb.save, or manually copying the files into `wandb.run.dir` before calling wandb.save.

**Comment by mohamedr002** [comment]
> A quick fix is to write the file a file directly into `wandb.run.dir` and then call save which will bypass the symlink. In a future release we'll switch to copying instead of symlinking.

Thanks for your response, but what can I do if I am syncing tensorboard, will I do this for each file I save from tensorboard?

**Comment by vanpelt** [comment]
If you just set the logdir for your tensorboard writers to wandb.run.dir it will not attempt to symlink anything.

**Comment by SamGalanakis** [comment]
`save_model_path = wandb.run.dir+wandb.run.name+".pt"`
    `torch.save(save_state_dict,save_model_path)`
    `wandb.save(save_model_path)`


`Exception has occurred: OSError
[WinError 1314] A required privilege is not held by the client: 'C:\\code\\flow_change\\wandb\\run-20201207_005152-rbk0gfx9\\filesfanciful-salad-27.pt' -> 'C:\\code\\flow_change\\wandb\\run-20201207_005152-rbk0gfx9\\files\\filesfanciful-salad-27.pt'
  File "C:\code\flow_change\train.py", line 214, in <module>
    wandb.save(save_model_path)`

Seem to be getting the error dispite using run.dir and then saving with that path

**Comment by shivamiitgoa** [comment]
Following code works fine for me on windows 10.

```
torch.onnx.export(net, inputs, config.onnx_model_path)
shutil.copy(
    config.onnx_model_path,
    os.path.join(wandb.run.dir, os.path.basename(config.onnx_model_path)),
)
wandb.save(config.onnx_model_path)
```

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by dc914337** [comment]
I stumbled upon this problem when calling "wandb.save".
Here is a solution for all symlink related problems: https://www.scivision.dev/windows-symbolic-link-permission-enable/
in short: add your user (or "Everyone") rights to create symlinks.
Python 3.8 (which is mentioned in the manual) is not required, python 3.7 worked for me

**Comment by maria-korosteleva** [comment]
I can confirm that I'm still experiencing an issue in wandb 0.16.5

```
wb.save(filepath, base_path=filepath.parent, policy='now')
  File "C:\Users\mariako\anaconda3\envs\train\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\mariako\anaconda3\envs\train\lib\site-packages\wandb\sdk\wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\mariako\anaconda3\envs\train\lib\site-packages\wandb\sdk\wandb_run.py", line 1936, in save
    return self._save(
  File "C:\Users\mariako\anaconda3\envs\train\lib\site-packages\wandb\sdk\wandb_run.py", line 2000, in _save
    target_path.symlink_to(source_path)
  File "C:\Users\mariako\anaconda3\envs\train\lib\pathlib.py", line 1403, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: '\\local\\path\\data_split.json' -> 'wandb\\wandb\\run-20240410_150558-23vhj6ln\\files\\data_split.json'
```

**Comment by kptkin** [comment]
> WinError 1314

@mjmikulski i'm a little surprised that you are hitting this error on windows 11, as it suppose to support symlinks without administrative privileges, based on the documentation.

**Comment by jhurliman** [comment]
Still hitting this on Win 11 in June 2025
