### ISSUE TITLE
Can't add evaluation logs to a finished run

### ISSUE THREAD

**Issue by MartinHahner** [wandb/client#1371]
It seems to be impossible to log to a run once it has been marked "_finished_".
Shouldn't it be possible to run further evaluations on a _finished_ training run?!

snipped from `eval.py`:
```python


        run = None

        if tb_log and arguments.platform == 'slurm':  # only do this once for a multi-GPU job

            api = wandb.Api()
            runs = api.runs('cvpr_2021/pcdet')

            # try to find training run on WAND (maybe does not exits)
            for r in runs:
                if r.name == arguments.folder.split('/')[-1]:
                    run = r
                    run.dir = output_dir
                    break

            if run: 

                 step = int(accumulated_iter)  # accumulated_iter sometimes is a String and WAND currently can't handle that

                 run.log({identifier: value}, step=step)
```

resulting error message:
```
    run.log({identifier: value}, step=step)
  File "/home/martin/anaconda3/envs/PCDet/lib/python3.6/site-packages/wandb/apis/public.py", line 530, in __getattr__
    "'{}' object has no attribute '{}'".format(repr(self), name)
AttributeError: '<Run cvpr_2021/pcdet/3g4f3tpq (finished)>' object has no attribute 'log'
```

Note:
I also encountered another issue:
                 `step = int(accumulated_iter)  # accumulated_iter sometimes is a String and WAND currently can't handle that`

**Comment by cvphelps** [comment]
Hi @MartinHahner, it's best practice to use [Artifacts](https://docs.wandb.com/artifacts) to link your evaluation run to your training run. Could you use this approach to link your evaluation metrics?

**Comment by MartinHahner** [comment]
> Hi @MartinHahner, it's best practice to use [Artifacts](https://docs.wandb.com/artifacts) to link your evaluation run to your training run. Could you use this approach to link your evaluation metrics?

Hi @cvphelps, is this still "best" practice?
I don't see why it's not allowed to add additional metrics later on. :thinking: 
As far as I understand, I can not show the content of artifacts in the table view of my runs, or can I?  
That would be what I want.

**Comment by MartinHahner** [comment]
This feature solved it for me:
https://docs.wandb.ai/library/resuming

**Comment by lucasdavid** [comment]
@cvphelps if I understood your ref. correctly, artifacts can be stored and retrieved by one or more runs.
How would one link two separate runs using them?

**Comment by ramit-wandb** [comment]
Hi @lucasdavid,

You are right, artifacts can be used to store and retrieve data by one or more runs. 2 runs can be "linked" by an artifact in the sense that you have a "Training Run" which logs an artifact (like a model) and an "Evaluation Run", which uses the same artifact for evaluation.

However, as @MartinHahner mentioned, you can also resume runs if you would like to evaluate after your training process has completed but still have all your metrics present in one run.

Thanks,
Ramit

**Comment by lucasdavid** [comment]
I see. I was imagining a different kind of "link", where two runs would be merged and showed as a single label in the charts.
Thank you very much for the clarification.
