### ISSUE TITLE
Missing GPU metrics after moving to another server

### ISSUE THREAD

**Issue by janvainer** [wandb/client#1373]
Hi, we have recently moved our entire filesystem to a new provider. When we try to log our experiments with wandb, everything gets displayed correctly except for the GPU stats. Only the GPU power usage gets displayed but the rest is empty. Our GPUs have changed from Nvidia V100s to Nvidia T4s. We use wandb 0.10.7, python 3.6.9. Could you give advice on how to make this feature work? We tried reinstalling wandb, but had no success.

**Comment by tyomhak** [comment]
Hey there @LordOfLuck , we're looking into this issue.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by krenerd** [comment]
Hi @sydholl, I think I'm having the same issue here. I'm using `(WandbLogger)[https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.loggers.WandbLogger.html]` to integrate wandb. The GPU is clearly detected, but I can't see GPU utilization in the dashboard.

link: https://wandb.ai/krenerd77/devchal_2022_final/runs/g1xa238g/logs?workspace=user-krenerd77

![image](https://user-images.githubusercontent.com/48239275/192088395-07d797ae-3272-4303-9557-53229e0ab61e.png)
![image](https://user-images.githubusercontent.com/48239275/192088414-0664e837-efb2-46d6-98b1-17834460560e.png)

**Comment by nagyrajmund** [comment]
I am experiencing the same issue as krenerd above. I am also using the `WandbLogger` in Lightning.

**Comment by karyam** [comment]
I am experiencing the same problem using the colab provided here: https://wandb.ai/authors/ayusht/reports/Using-GPUs-With-Keras-A-Tutorial-With-Code--VmlldzoxNjEyNjE. How to use wandb to display GPU system graphs? An answer would be extremely helpful!
