### ISSUE TITLE
add custom JSONEncoder 

### ISSUE THREAD

**Issue by Zhylkaaa** [wandb/client#1375]
Hi, 
is it possible to add argument to enable using custom encoder to enable logging non-serializable objects?

Currently I am using simpletransformers and I am getting error when I am trying to use custom dataset passed in model parameters.

**Comment by tyomhak** [comment]
Not sure if it's possible right now. Asking the engineers about this.

**Comment by vanpelt** [comment]
The next release will automatically convert any callable non-json serializable objects: https://github.com/wandb/client/pull/1384/files

**Comment by Zhylkaaa** [comment]
Looks nice 😁
Thanks, for your work ❤️
