### ISSUE TITLE
Add richer aggregation method for the table, parallel coordinates, etc.

### ISSUE THREAD

**Issue by GarrettLee** [wandb/client#1380]
Usually, I use the function `wandb.log` to log metrics for each step. At the end, I have a list of numbers corresponding to the metric at each step. For example:

| step | Test Accuray |
| :-----| ----: |
|0|0.1|
|1|0.3|
|2|0.4|
|3|0.45|
|4|0.43|
|5|0.4|

So, when I am trying to compare test accuracies of different runs using the various tools in wandb like table, parallel coordinates, I care most about their highest test accuracy, that is the 3rd step in the example above. But wandb defaultly shows the test accuracy of the last step, the 5th step. 

To meet my requirement, I have add a summary name `max_text_accuray` by add extra logging code. However, I found that this doubles the columns of the table. To manage the table neatly, I have to hide this redundant column manully. 

My question is that ,can wandb add a button on the webpage, so that we can decide in which way we want the metrics to be aggregated and shown on the page. The possible aggregation methods can be maximum, minimum and mean, etc.

**Comment by cvphelps** [comment]
Hi @GarrettLee, instead of creating a new summary `max_test_acc`, you can set the value of your existing summary key `test_acc`. This is by default the last value from history, but you can overwrite it to be the max value instead.

**Comment by ariG23498** [comment]
Hey @GarrettLee 
We are closing this ticket due to the inactivity.
Please feel free to reopen if your issue still persists. :smile:
