### ISSUE TITLE
Trainer terminated with OS disk quota error - wandb hangs forever

### ISSUE THREAD

**Issue by toshas** [wandb/client#1382]
In an environment with limited amount of files allowed in a partition, if the trainer process terminates with an OS disk quota error, then wandb process hangs forever waiting for the trainer process. It would be great to add a wait timeout so a GPU can be released as soon as the trainer terminates, for whatever reason. 
wandb client version 0.10.5 for Linux

**Comment by tyomhak** [comment]
Thanks for flagging this issue. We're looking into it. I would also suggest upgrading wandb to 0.10.7

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by Apprisco** [comment]
![image](https://user-images.githubusercontent.com/34324909/185654241-c6e85eba-a96e-48a5-8f4c-763bb580e0dd.png)

MAny compute clusters have a small /tmp allocation, and setting the wandb_dir doesn't change the fact that WandB will copy files to the /tmp directory. Please address this issue.

**Comment by mwritescode** [comment]
Hello, I'm still facing this issue when running wandb on a slurm cluster, as my disk quota is limited and setting WANDB_CACHE_DIR to another folder does not change anything. Is there a way to avoid this?

**Comment by holajoa** [comment]
> Hello, I'm still facing this issue when running wandb on a slurm cluster, as my disk quota is limited and setting WANDB_CACHE_DIR to another folder does not change anything. Is there a way to avoid this?

Hello, I'm not sure if you are still looking for a solution to this but just in case you do - I was having the same issue, and changing the env variable `WANDB_DATA_DIR` to a folder with more space in the sbatch script solves it for me.

**Comment by shehzi-khan** [comment]
> > Hello, I'm still facing this issue when running wandb on a slurm cluster, as my disk quota is limited and setting WANDB_CACHE_DIR to another folder does not change anything. Is there a way to avoid this?
> 
> Hello, I'm not sure if you are still looking for a solution to this but just in case you do - I was having the same issue, and changing the env variable `WANDB_DATA_DIR` to a folder with more space in the sbatch script solves it for me.

that's the thing if we dont have other locations with more space. i either wish to log all the data online only or minimize the memory footprints somehow.
