### ISSUE TITLE
wandb: ERROR Error while calling W&B API: conflict detected for file digest <random number here>, rebase required (<Response [409]>)

### ISSUE THREAD

**Issue by JacobARose** [wandb/client#1407]
Hi all,

I've been seeing this warning numerous times while running experiments, but haven't been able to find any documentation of it occurring elsewhere. It doesn't crash the run, but I am concerned about potentially missed silent errors. 

I feel like it could have something to do with conflicts from other runs, but as far as I can tell everything is fairly well separated by directory upon any new run. Any insight on this?

P.S. I'd give a minimal example to reproduce it, but at this point it's far too unclear to me what is actually causing it in order to be able to extract the key code.

Thanks in advance!

**Comment by cvphelps** [comment]
Hi there, I've never seen this error, could you share your debug.log and debug_internal.log from the wandb directory?

**Comment by cvphelps** [comment]
May I ask, what integrations from W&B are you using? Are you using a framework integration? Artifacts?

**Comment by annirudh** [comment]
This error occurs if the following sequence of steps occurs:

- Run 1 is committing to artifact `A` a file `file.txt` with digest `ABC`.
- Run 2 is committing to artifact `A` the same file `file.txt` with a different digest `DEF`.
- Run 1 commits
- Run 2 commits, but there's a conflict since it's trying to overwrite `file.txt` without being aware of Run 1's commit.

Our plan was to have the CLI automatically do a "rebase" in this case, we just haven't implemented that flow yet.

Does the above sequence of events sound plausible for your logging flow?

**Comment by ZaydH** [comment]
@annirudh I have encountered the same issue reported by @JacobARose above.  I believe it is due to the sequencing collision you describe.  Your comment is a little over a year old; I wanted to see if the fix `rebase` change you describe has been implemented.  I am using W&B 0.12.9.

**Comment by rilshok** [comment]
I have the same problem. I am using wandb 0.12.10

**Comment by mtkinit** [comment]
Hey. In my case the problem occured in this situation.

I ran runs in separate processes (I used standard multiprocessing processes). 
Then, in every process I tried to log source codes:
`run.log_code("..", include_fn=lambda path: (path.endswith(".py") or path.endswith(".sh")) and ('src' in path or 'scripts' in path))`

When I tried that, I got following errors:
`wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>)   
wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>)   
wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>)   
wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>)   
wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>)   
wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>)`

When I tried to run processes one at a time (still using multiprocessing), there was no problem.

**Comment by thinh-re** [comment]
Hi, I encounter the same problem.

I terminated the program (by pressing Ctrl+C)
![image](https://user-images.githubusercontent.com/104742129/183378263-3de40162-2ab0-4e17-929f-7d2f04f290fe.png)

And then I run wandb with the same ID (with resume='auto'), it resumes the last run and after `wandb.finish()`: 
![image](https://user-images.githubusercontent.com/104742129/183378523-cb2c2ec1-0efb-4db9-93d0-e9b6d7444853.png)

**Comment by mattdl-meta** [comment]
> Hey. In my case the problem occured in this situation.
> 
> I ran runs in separate processes (I used standard multiprocessing processes). Then, in every process I tried to log source codes: `run.log_code("..", include_fn=lambda path: (path.endswith(".py") or path.endswith(".sh")) and ('src' in path or 'scripts' in path))`
> 
> When I tried that, I got following errors: `wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>) wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>) wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>) wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>) wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>) wandb: ERROR Error while calling W&B API: conflict detected for file digest fKJoshQzzPQ2cUY83ynjTw==, rebase required (<Response [409]>)`
> 
> When I tried to run processes one at a time (still using multiprocessing), there was no problem.

I encountered to exact same problem, resulting in a deadlock waiting for my spawned processes to finish.
Version: 0.13.3

**Comment by kiddyboots216** [comment]
I am also encountering the same problem.

**Comment by thanos-wandb** [comment]
@here this thread has closed and new discussion moved [here](https://github.com/wandb/wandb/issues/4297).
