### ISSUE TITLE
(Web Interface) Aggregation of bar chart does not work 

### ISSUE THREAD

**Issue by berlino** [wandb/client#1410]
hi, there:

  I found that the aggregation option of bar chart seems not work for me. Below is a screenshot 
![image](https://user-images.githubusercontent.com/2403596/97018943-a2048a80-1547-11eb-972d-003d506036e3.png) 

Changing Agg to mean/min/max does not make any difference. I guess wandb is only loading the metric from the final step. But in some cases (my previous plots weeks ago), the option worked, i.e., doing aggregation across steps. 

I do have the metric from different runs, and the line plot is working properly, see below

![image](https://user-images.githubusercontent.com/2403596/97019183-eb54da00-1547-11eb-84b0-b470e1deab0b.png)

Thanks!

**Comment by cvphelps** [comment]
Hi there, it looks like grouping isn't on for these bar charts. The aggregation works across summary metrics, so summary values from multiple different runs. It doesn't work for aggregating values across a time series for a metric from a single run. Is that what you were expecting?

**Comment by berlino** [comment]
Hi, @cvphelps Thanks for the response!

**Comment by berlino** [comment]
I figured it out that I need to write the info using wandb.run.summary.
