### ISSUE TITLE
`wand on` and `wandb off` fail with TypeError

### ISSUE THREAD

**Issue by SinclairHudson** [wandb/client#1424]
I've set weights and biases off with `wandb off`, but coming back to it now I can't turn it back on. It seems I can't run any wandb commands from the CLI.
Setup:
Python 3.8.5
Ubuntu 20.04
wandb-0.10.7
In a conda environment with conda 4.9.0

![image](https://user-images.githubusercontent.com/30478652/97116259-69dd8300-16d2-11eb-979c-0b2ed66763e1.png)

**Comment by tyomhak** [comment]
Hey @SinclairHudson , thanks for reporting.

@raubitsj @vanpelt can you please take a look?

**Comment by cvphelps** [comment]
Hi Sinclair, could you share more about your environment setup? This is working properly for me, if you could share a backtrace then maybe we can figure this out

**Comment by SinclairHudson** [comment]
Ok. I did some more digging. If I run
```
conda create --name newEnv
conda activate newEnv
conda install wandb
wandb on
```
Then I get the error pictured above. However, if I instead install `wandb` with `pip`, `pip3 install wandb`, it works fine.
So the good news is that I'm unblocked, and I hope this can be a helpful clue. If you need any specific environment setup information, I'm still happy to provide it.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
