### ISSUE TITLE
Custom Charts: Dropdowns only contain fields from the first of multiple SummaryTables.

### ISSUE THREAD

**Issue by alexmirrington** [wandb/client#1426]
**Summary:**

When querying multiple SummaryTables in custom charts, only the keys for the first table in the query are displayed in the drop-down menu.

**Context:**

I am creating a graph of node and edge connections to visualize attention weights in my graph attention model. Given the graph has _n_ nodes, it is well known that it could have up to _O(n^2)_ edges. It is therefore very inefficient to log node-specific properties for every edge in the graph, leading me to log two tables for my visualization, one for nodes and one for edge connections. The tables contain the following fields:

Nodes:

| index | label | group |
| -------- | ------- | --------- |
| 0         | palm tree | object |
| 1         | leaves | object |
| ...        | ...         | ... |

Edges:

| source_index | target_index | value |
| ------------------- | ------------------ | -------- |
| 0         | 26 | 0.37581050395965576 |
| ...        | ...         | ... |

I then query both tables in the GraphQL query In the custom charts editor like so:

![20201026-170203](https://user-images.githubusercontent.com/34053287/97138774-112ee880-17ad-11eb-9405-c76156540cef.png)

Only the fields for the edge table are present in the dropdown for selecting the field to inject into the Vega spec (in addition to the run id and name):

![20201026-170317](https://user-images.githubusercontent.com/34053287/97138893-57844780-17ad-11eb-96ac-1b8bf43831f9.png)

I have been working around this by using `${string:data}` instead of `${field:data}` to specify the fields to draw from, however this requires knowing in advance what the headers of the table are.

My guess as to why this issue occurs is that the data for both tables is dumped into a single `wandb` array for use by Vega, and the dropdowns likely only look at the first element in the array to determine which fields are valid. Below is an example of the `wandb` vega data array where there are 331 edges and 140 nodes:

![20201026-170757](https://user-images.githubusercontent.com/34053287/97139156-fa3cc600-17ad-11eb-9d04-4f9d8e7b3f2b.png)

This introduces two problems:

1. Incorrect item listings in the field dropdowns as explained earlier
2. More complicated Vega specs where we have to apply filter transforms on the `wandb` data stream to check if fields exist or not.

Ideally, each table would be placed in a separate array under a top-level `wandb` object so we don't have to perform any additional filter transforms. Determining the values to populate the dropdown then just becomes a matter of iterating over keys in the `wandb` object and grabbing the fields from the first element of each of the arrays as I suspect is already being done.

**Comment by tyomhak** [comment]
Hey @alexmirrington, thanks for flagging this. We're looking into it.

cc @shawnlewis

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by gil2rok** [comment]
I'm having this same issue! Please fix or provide clarity in the docs on how to handle this.
