### ISSUE TITLE
Support Hydra in sweeps

### ISSUE THREAD

**Issue by tadej-redstone** [wandb/client#1427]
It would be great if applications configured to run with hydra could be used in sweeps. Right now the problems is that when expanding `args`, wandb prepends double dashes, as stated in documentation

> ${args}: Expanded arguments in the form --param1=value1 --param2=value2

Hydra would require the expansion to be

> param1=value1 param2=value2

I think this could be easily added as an option in sweep configuration.

**Comment by vanpelt** [comment]
Hey @tadej-redstone you can do this with the current release, you'll want to specify a custom `cmd` in your sweep yaml as described here: https://docs.wandb.com/sweeps/configuration#command.  You can replace `${args}` in the default command with `${args_no_hyphens}`.

**Comment by tadej-redstone** [comment]
Thanks! Don't know how I missed that 🙃

**Comment by captain-pool** [comment]
For posteriority, checkout: https://github.com/wandb/client/issues/1856#issuecomment-1041508724
