### ISSUE TITLE
Suppressing the run summary generated when a wandb process finishes?

### ISSUE THREAD

**Issue by alsuhr-c** [wandb/client#1431]
Hi, 

I have to write my code to handle both multiprocessing (ray) and without multiprocessing, and I believe the easiest way to use wandb for this is to wrap all calls that use wandb in a context manager, e.g.,

```
with wandb.init(project='project', reinit=True) as run:
    train(run)

with wandb.init(project='project', reinit=True) as run:
    evaluate(run)
```

However, every time the context ends, wandb prints the run summary, with a huge number of metrics printed to the console. Can I suppress this summary in some way?

**Comment by alsuhr-c** [comment]
Actually, even this doesn't work for what I am trying to do. It creates a new run in the wandb client for every call to wandb.init. Is there any way for me to log to a single run using this approach?

**Comment by vanpelt** [comment]
Hey @alsuhr-c yep, setting your own globally unique run id with `wandb.util.generate_id()` or just storing the result of your first wandb.init call will allow you to start the second run by setting `wandb.init(id=stored_id, resume="allow")`.  Assuming these scripts run serially and not in parallel.  To suppress output of summary information set the environment variable WANDB_SILENT=true 

https://docs.wandb.com/library/environment-variables#optional-environment-variables

**Comment by alsuhr-c** [comment]
Is `resume="allow"` necessary for this? It seems like I can get the same behavior without this flag -- just want to make sure it is necessary?

On the answer to my other question -- thanks!

**Comment by vanpelt** [comment]
Resume will ensure future calls to `wandb.log` have the appropriate "step" associated with it.  Without it, calls to `wandb.log` will begin at 0.

**Comment by alsuhr-c** [comment]
Ah I see, thanks. I am explicitly setting the step index whenever I log to wandb, so this is why it has worked.
