### ISSUE TITLE
feature request : debug mode

### ISSUE THREAD

**Issue by pclucas14** [wandb/client#1433]
Hi, 

I'm a big fan of your library! It would be even better if there was a way to completely bypass wandb when I'm debugging. More specifically, sometimes I'm trying stuff that **I know I will not want to upload later**. If there was a way to avoid the `wandb` overhead by essentially doing as if I had commented out all wandb lines, that would be great! Hope this makes sense. 

Thanks, 
Lucas

**Comment by lukas** [comment]
Thanks! Does the command wandb off or equivalently setting WANDB_MODE=dryrun not work for you?

**Comment by pclucas14** [comment]
so `wandb off` works well! The issue is if I say `ctrl-c` my current debugging session, instead of the program terminating directly, wandb takes some extra time to terminate (to save some results and gracefully exit I assume), which is annoying when you are repeatedly running and cancelling jobs.

This is a very "diva" request, as the added overhead is `~3 sec` . But it would be even better if there was no overhead at all

**Comment by vanpelt** [comment]
Hey @pclucas14 `wandb off` still syncs all metrics locally.  In the next release we're going to have `wandb disabled` which will completely disable wandb which sounds more like what you would want here.

**Comment by pclucas14** [comment]
Great! looking forward to it :)
