### ISSUE TITLE
[BUG] Data Loss in Visualization

### ISSUE THREAD

**Issue by 6etacat** [wandb/client#1453]
Data loss happens when graphs get updated. A hacky fix is to click the edit button and it may be refreshed. However, this fix does not work when the run is finished. This seems to be more likely when more data is logged. 

Example:
![image](https://user-images.githubusercontent.com/15188392/97942195-229a6680-1d52-11eb-9292-79377f6e417e.png)

**Comment by tyomhak** [comment]
Hey @6etacat , thanks for reporting. We're looking into this.

**Comment by vanpelt** [comment]
Hey @6etacat for performance reasons we randomly sample more than 5k data points to 5k data points in the UI.  The data is still stored and the full resolution data can be accessed via our api with the `scan_history` method: https://docs.wandb.com/library/api/examples#export-metrics-from-a-large-single-run-without-sampling

**Comment by 6etacat** [comment]
I'm wondering how I will be able to visualize things normally? This happens to data charts that have very few data points as well. I can't work with a graph like this, and I have no way to make it look normal again. Sure I can extract the data and visualize it with matplotlib or some other tool, but then what's the point of using wandb anymore? 

![image](https://user-images.githubusercontent.com/15188392/98151932-f50f0380-1e9e-11eb-86d4-425de55b6717.png)

**Comment by cvphelps** [comment]
Hi @6etacat could you please email vanpelt@wandb.com to set up a quick call so we can get this fixed for you

**Comment by MohamedOsman1998** [comment]
> Hi @6etacat could you please email [vanpelt@wandb.com](mailto:vanpelt@wandb.com) to set up a quick call so we can get this fixed for you


hey guys i still run into this to this day, seems likely with longer runs, I think it is the resampling that you guys are doing but it also happens with data-points that are fewer than 5k for sure, just as @6etacat reports. What kind of fix did you guys arrive at because this is definitely still an ongoing issue for me

**Comment by MohamedOsman1998** [comment]
For anyone googling this, I fixed this by editing the charts and reverting to the original step on the x axis instead of any other metric like wall time or a user defined step, which I had been using.
