### ISSUE TITLE
Wandb creates unwanted cell outputs in jupyterlab 

### ISSUE THREAD

**Issue by hal-314** [wandb/client#1458]
Hi

I notice that when I using wandb client in jupyter lab, I get cell outputs that I don't want, are quite big and I can't remove them. They make reading notebooks difficult. I get this behaviour with `wandb.init()` and `wandb.run.finish()` as you can see:

![Screenshot 2020-11-04 at 18 05 23](https://user-images.githubusercontent.com/22135069/98142893-b68e3e80-1ec8-11eb-90bb-e20dbd0f5c9c.png)

![Screenshot 2020-11-04 at 18 04 58](https://user-images.githubusercontent.com/22135069/98142914-bf7f1000-1ec8-11eb-8f43-199c865b5b4c.png)

![Screenshot 2020-11-04 at 18 04 37](https://user-images.githubusercontent.com/22135069/98142919-c148d380-1ec8-11eb-8535-edb4b442759a.png)

I tried to use `%%capture` ipython magic. It suppress any output with `wandb.init()`. However, it breaks `wandb.run.finish()`, either running in `wandb.init()` cell or in the same cell where `wandb.run.finish()` is. I also tried to silence W&B messages as said in [docs](https://docs.wandb.com/library/integrations/jupyter#silence-w-and-b-info-messages) without success :( 

So, I would like to request a way to suppress them.

I'm using wand 0.10.8 and jupyter lab 2.2.3. I think that this doesn't happen in colab.

**Comment by cvphelps** [comment]
Hi there @hal-314 thanks for reporting this! Great point, there should be a feature for silencing W&B output coming soon 👍

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
