### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [wandb/client#1466]
The README file in this repo has some bad links - [404:NotFound]

The markup version of the readme that is displayed for the main page in this repo contains the following links:
Status code [404:NotFound] - Link: https://docs.wandb.com/frameworks/keras
Status code [404:NotFound] - Link: https://docs.wandb.com/frameworks/pytorch
Status code [404:NotFound] - Link: https://docs.wandb.com/frameworks/tensorflow

Theses bad links were found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by tyomhak** [comment]
Hey @MrCull , thank you for reporting! Pretty awesome tool you got there! Definitely getting a star!

@cvphelps we need to fix some links in our Readme!
