### ISSUE TITLE
Weights are not logged when model is watched

### ISSUE THREAD

**Issue by stathius** [wandb/client#1471]
The gradients of the model are indeed logged but not the parameters. 

Using:
pytorch-lightning==1.0.4
torch==1.7.0
torchvision==0.8.1
wandb==0.10.9

mac os x 10.15.7

```
        logger = pl.loggers.WandbLogger(project=hparams.project_name, save_dir=save_dir)
        logger.log_hyperparams(vars(hparams))
        logger.watch(model, log='all', log_freq=1)
```

**Comment by tyomhak** [comment]
Hi @stathius , thanks for reporting this issue. We're looking into this.

**Comment by tyomhak** [comment]
I believe by default it is supposed to log only gradients, but you can change it by using argument log. 
Please see the documentation ([here](https://docs.wandb.com/library/integrations/pytorch#options)) for more details.

**Comment by stathius** [comment]
I am using the log='all' argument.

**Comment by lukas** [comment]
Hm, I tried to replicate this by setting log='all' in https://github.com/wandb/examples/blob/master/examples/pytorch/pytorch-cnn-mnist/main.py and it seemed to work as intended, logging both parameters and gradients - could you try that with your setup

**Comment by ariG23498** [comment]
Hey @stathius 
Did you happen to find the solution to the issue?
It would be great for us if we could close the stale threads if the solution has already been achieved. :smile:

**Comment by stathius** [comment]
Hi @ariG23498 not really but it's fine to close it.

**Comment by sbos** [comment]
I'm experiencing the same problem. Gradients are logged fine, but parameters don't show up in wandb panels. Is there any way to tell why this is silently failing?

**Comment by KarlXing** [comment]
I'm having the same issue.

wandb: 0.15.5
torch: 2.1.0.dev20230627+cu121

**Comment by tom-hehir** [comment]
Oops! For anyone stumbling on this (closed) issue, I found the solution here: https://github.com/wandb/wandb/issues/2342#issuecomment-874201310
