### ISSUE TITLE
Is it possible to force upload of a newly created artifact without finishing the run?

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1486]
wandb version: 10.0.9
Python: 3.6.12
OS: Win 10

The workflow of my work with artifacts looks like this: I'm uploading multiple versions of an artifact during DL training, and then at the end of the script, I want to get a version of this artifact with a certain label.

Like this: 
```
import torch
import wandb

wandb.init(project='Test')
run = wandb.run

artifact_name = 'Test-checkpoint'

# Do something 0...
# v0
artifact = wandb.Artifact(artifact_name, type='checkpoint')
artifact.add_file('./wandb/artifacts/42wsedgy/checkpoint_0.pth')
run.log_artifact(artifact)

# Do something 1...
# v1
artifact = wandb.Artifact(artifact_name, type='checkpoint')
artifact.add_file('./wandb/artifacts/42wsedgy/checkpoint_1.pth')
run.log_artifact(artifact)

# Do something 2...
# v2
artifact = wandb.Artifact(artifact_name, type='checkpoint')
artifact.add_file('./wandb/artifacts/42wsedgy/checkpoint_3.pth')
run.log_artifact(artifact)

# run.finish() #### QUESTION is about this line -- any other way to force artifacts upload? 

# Sometime later.. in another part of the system
# Now try to get the latest of that artifact
api = wandb.Api({'project': 'Test'})
artifact = api.artifact(name=artifact_name + ':latest', type='checkpoint')
# OR
# artifact = run.use_artifact(artifact_name + ':latest', type='checkpoint') 
# OR
# artifact = run.use_artifact(artifact)
filepath = artifact.download()
print(filepath)
```

When I use `run.finish()`, the artifact that gets downloaded is the one expected: `Test-checkpoint-v2`
If I don't want to finish the run and remove the line with `run.finish()`, I get different erroneous outcomes: 
* the error `ValueError: Project maria_korosteleva/Test does not contain artifact: "Test-checkpoint:latest"` (I guess when none of the versions got a chance to be uploaded)
* If use `run.use_artifact(artifact)` instead of `api.artifact()` to get artifact object, the error is `ValueError: Cannot call download on an artifact before it has been saved`
* Sometimes I just get the wrong version: e.g. `Test-checkpoint-v1` instead of `Test-checkpoint-v2`

So, is it possible to force upload artifacts versions so that I won't have to finish the run to get the correct files?

**Comment by vanpelt** [comment]
Hey @maria-korosteleva the artifact begins uploading the moment you call `log_artifact`.  When `run.finish` is called we block your process while all artifacts finish downloading.  We will eventually add a method for you to call in your process to wait for the upload to complete, but until then you can use a `try/catch` in a loop with a `time.sleep(5)` and attempt query the artifact with `api.artifact`.

```
api = wandb.Api({'project': 'Test')
max_attempts = 5
attempt = 1
while attempt <= max_attempts:
    try:
        time.sleep(5)
        artifact = api.artifact(artifact_name + ':latest', type='checkpoint')
        break
    except ValueError:
        attempt += 1
```

Unfortunately this approach won't always prevent the 3rd case you mentioned.  I'll sync with the team to see if there's a better way.

**Comment by maria-korosteleva** [comment]
@vanpelt thank you for your comment! Now I have a better idea of how it works. 
Unfortunately, the last case is the one I meet most often in practice, but I think I can reuse your suggested workaround by requesting a specific version to be uploaded instead of just the latest 🤔

**Comment by maria-korosteleva** [comment]
@vanpelt thank you for the tip!
I was able to use your suggestion to combat the last issue as well -- I just needed to request a specific version (I expect to be the last one) instead of the 'latest' tag. =)

**Comment by ariG23498** [comment]
Hey @maria-korosteleva 
Would you like to close the issue if the suggested solution helps you? :smile:

**Comment by maria-korosteleva** [comment]
@ariG23498 oh, right, the suggested solutions helps in most cases, thanks!
