### ISSUE TITLE
Error when Adding an artifact to a finished run 

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#1491]
wandb version: 10.0.9
Python version: 3.6.12
OS: Win10

I'm running some evaluation on the model after the run is finished and trying to upload the results as an artifact attached to this run.

I'm creating an artifact as described in the docs: 
```
run = wandb.Api().run('maria_koristeleva/Test/<run_id>')
artifact = wandb.Artifact(name, type=type)
artifact.add_dir(path)
run.log_artifact(artifact)
```

But I'm getting an error: 
```
wandb: Adding directory to artifact (D:\GK-Pattern-Data-Gen\nn_pred_data_1000_tee_200527-14-50-42_regen_200612-16-56-43201113-17-27-49)... Done. 2.1s
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\apis\public.py", line 1264, in log_artifact
    "Only existing artifacts are accepted by this api. "
ValueError: Only existing artifacts are accepted by this api. Manually create one with `wandb artifacts put`
```

Is this use-case supported?

**Comment by maria-korosteleva** [comment]
UPD: Looking at the discussion in issue #1371, I need to create a new run, upload an artifact, and then link the artifact to the old run.
But may I request a better error message for this case?? It confusing, and leads me to the un-existing function..

**Comment by vanpelt** [comment]
Yep, agreed this is confusing.  We want to do the work to make this case actually work.  In the mean time how does this sound?

> You can only link existing artifacts to historic runs.  Call `wandb.init(id="...", project="...", resume="allow")` then `wandb.run.log_artifact(...)` to save this artifact.

**Comment by maria-korosteleva** [comment]
@vanpelt I think it's just what's needed. Thank you!

**Comment by timothyjlaurent** [comment]
```bash
def get_historical_run(run_id: str):
    """Allows restoring an historical run to a writable state
    """
    return wandb.init(id=wandb.Api().run(run_id).id, resume='allow')
```

**Comment by timothyjlaurent** [comment]
After struggling with logging and using the artifact in the 'historical' run I couldn't see the artifact in the ui neither linked to the original run or in the artifact panel for the app. So I created a new run and logged and and used the model there, now I see 2 new model versions in the new run, but not in the artifact view.

Additionally the artifact got new versions so deduping failed

![image](https://user-images.githubusercontent.com/2000204/99158310-34e79f00-2686-11eb-98a6-424830f416e1.png)
![image](https://user-images.githubusercontent.com/2000204/99158320-46c94200-2686-11eb-913d-721956110ea5.png)

**Comment by timothyjlaurent** [comment]
So i can navigate to the link from the run artifact interface, but it doesn't show up in the side bar:
![image](https://user-images.githubusercontent.com/2000204/99158406-572dec80-2687-11eb-8ddb-f4430e8a89e5.png)

Also note there are now:
-  2 'latest' model
- v3, the real latest isn't one of them

**Comment by timothyjlaurent** [comment]
After clearing up the duplicate latests I can see them all:

![image](https://user-images.githubusercontent.com/2000204/99158439-a7a54a00-2687-11eb-8bbb-03a73cea45b4.png)

**Comment by timothyjlaurent** [comment]
Ha So with v2 the latest, if I try to delete v3 it says 
![image](https://user-images.githubusercontent.com/2000204/99158463-d15e7100-2687-11eb-97f2-1144f4681944.png)

**Comment by annirudh** [comment]
> Ha So with v2 the latest, if I try to delete v3 it says
> ![image](https://user-images.githubusercontent.com/2000204/99158463-d15e7100-2687-11eb-97f2-1144f4681944.png)

We'll be releasing a fix for this issue this week. I'll circle back on this thread when the fix is live.

Currently, there's a backend limitation where the most recent (but not necessarily the artifact marked `latest`) cannot be deleted for dedupe purposes. This limitation doesn't need to be in place, so we'll be getting rid of it this week.

**Comment by vanpelt** [comment]
> ```shell
> def get_historical_run(run_id: str):
>     """Allows restoring an historical run to a writable state
>     """
>     return wandb.init(id=wandb.Api().run(run_id).id, resume='allow')
> 
> run = get_historical_run('gfb-phi/invitae-bert/2jvvhbjy')
> print(run)
> MODEL_ARTIFACT_NAME = 'invitae-roberta-mlm'
> model_artifact = wandb.Artifact(MODEL_ARTIFACT_NAME, type='model')
> model_artifact.add_dir(get_latest_run_dir())
> run.log_artifact(model_artifact)
> ```
> 
> I see:
> 
> ```
> wandb: You can sync this run to the cloud by running:
> wandb: wandb sync /home/jovyan/share/users/tlaurent/invitae-bert/notebooks/wandb/offline-run-20201114_220039-2jvvhbjy
> ...Successfully finished last run (ID:2jvvhbjy). Initializing new run:
> 
> wandb: Offline run mode, not syncing to the cloud.  <-- this looks fishy
> wandb: W&B is disabled in this directory.  Run `wandb on` to enable cloud syncing.
> wandb: Adding directory to artifact (./results/balmy-pine-80)... 
> <wandb.sdk.wandb_run.Run object at 0x7fad10d25470>
> Done. 2.1s
> ```
> 
> So the artifact doesn't sync to the cloud
> 
> I tried running `wandb on` but it's still not working.

Can you check your environment and see of `WANDB_MODE` is set to "dryrun" or "offline"?  If you run `wandb on` you must run it in the same directory as your script.  We write a settings file to `./wandb/settings` that may be setting the mode to off.

**Comment by vanpelt** [comment]
> After struggling with logging and using the artifact in the 'historical' run I couldn't see the artifact in the ui neither linked to the original run or in the artifact panel for the app. So I created a new run and logged and and used the model there, now I see 2 new model versions in the new run, but not in the artifact view.
> 
> Additionally the artifact got new versions so deduping failed
> 
> ![image](https://user-images.githubusercontent.com/2000204/99158310-34e79f00-2686-11eb-98a6-424830f416e1.png)
> ![image](https://user-images.githubusercontent.com/2000204/99158320-46c94200-2686-11eb-913d-721956110ea5.png)

To understand what's happening here, can you share some code on exactly how you were calling **use** and **log** artifact?

**Comment by timothyjlaurent** [comment]
> Can you check your environment and see of WANDB_MODE is set to "dryrun" or "offline"?
Not set to either

> Also, in your get_historical_run: run_id == wandb.Api().run(run_id).id so there shouldn't be a need to wrap this in wandb.Api().run.

Ok -- 

> To understand what's happening here, can you share some code on exactly how you were calling use and log artifact?

```python
tokenizer_artifact = wandb.use_artifact(f"{TOKENIZER_NAME}:{TOKENIZER_VERSION}")
tokenizer_path = Path(tokenizer_artifact.download())
tokenizer = RobertaTokenizerFast.from_pretrained(str(tokenizer_path))
```

```python
    tokenizer.save(str(TOKENIZER_DIR / 'tokenizer.json'))

    tokenizer_artifact = wandb.Artifact(
        TOKENIZER_NAME,
        type='tokenizer',
        description="Roberta-based Byte-level BPE tokenizer",
    )
    tokenizer_artifact.add_dir(TOKENIZER_DIR)
    run.log_artifact(tokenizer_artifact)

```

**Comment by vanpelt** [comment]
Hey @timothyjlaurent for the suspicious offline run error, there's either a file at `./wandb/settings` relative to your script that has disabled = true in it (you can run `wandb on` from the same directory as your script to renable wandb).  Or the WANDB_MODE env variable is set.

Regarding the versions showing up in the run, but not in the artifact page.  We will likely need to hop on a quick screenshare to get to the bottom of this.  Can you email me at vanpelt@wandb.com with a couple times that would work for you?

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
