### ISSUE TITLE
Artifacts logged with the same name but of different type crash wandb server

### ISSUE THREAD

**Issue by timothyjlaurent** [wandb/client#1496]
This has bit me several times. I have some generic artifact name, `foo-bert`, I've logged a `foo-bert` of type `tokenizer`. If I log a type `model` `foo-bert` the wandb server dies and my jupyter notebook is irrecoverable and must be restarted.

**Comment by tyomhak** [comment]
Hey @timothyjlaurent , thanks for reporting.
@annirudh can you please take a look?

**Comment by annirudh** [comment]
I'm able to reproduce the issue. I can confirm that the notebook hangs once the mismatch error is thrown, and that the only way to proceed is to restart the kernel.

Given the severity of the bug, we're prioritizing a fix for this issue.

**Comment by sydholl** [comment]
This issue has been fixed as of Nov 2020
