### ISSUE TITLE
Hugging Face: Transformers isn't logging config

### ISSUE THREAD

**Issue by timothyjlaurent** [wandb/client#1499]
I'm working with 🤗  Transformers library.  I'm using the normal trainer - I can see gradient metrics being sent but I don't see any config parameters 

![image](https://user-images.githubusercontent.com/2000204/99158755-26e84d00-268b-11eb-9b37-3cd3ac97105a.png)

![image](https://user-images.githubusercontent.com/2000204/99158758-2cde2e00-268b-11eb-9e7d-674aee89e3c7.png)

Looking at the code it seems that this should be working.

**Comment by tyomhak** [comment]
Hi @timothyjlaurent , have you set the env variable WANDB_WATCH equal to 'all'?

**Comment by timothyjlaurent** [comment]
No, but I can.

That didn't help:

![image](https://user-images.githubusercontent.com/2000204/99564371-331c2500-297f-11eb-9b00-216560a18157.png)

**Comment by borisdayma** [comment]
You may not have enough steps. Try changing `logging_steps` (see [TrainingArguments](https://huggingface.co/transformers/main_classes/trainer.html#trainingarguments))

**Comment by timothyjlaurent** [comment]
So the config is supposed to log before any steps get taken, the _metrics_ were getting logged, though. Currently I'm manually logging the config so I don't lose it. 

I tried setting `WANDB_WATCH=all` but that stopped logging any _metrics_  --- and it ran for hours so there were plenty of steps.

So maybe the metrics aren't getting logged because the run is reiniting, I'm manually init a run to set up artifact dependencies prior to making the the trainer with `reinit=true`

**Comment by vanpelt** [comment]
Hey @timothyjlaurent, if you can get access to the `WandbCallback` instance, that's being passed to the `Trainer` you can set the `wandb_callback_instance._initialized = True` attribute so that the trainer doesn't create a new run after you manually called `wandb.init`.  We're looking into better ways to support this in a future release.

**Comment by borisdayma** [comment]
@timothyjlaurent can you clarify a few items:
* Are you using HuggingFace hyper-parameters search feature?
* Are you calling `wandb.init` prior to the `Trainer` or after?
* Are you explicitly setting `reinit` parameter? When setting to `True` it will close any existing run and start a new one.

You can see in your W&B interface if 2 runs have been created and what has been logged on each (config and metrics).

What I suspect:
* you are calling `wandb.init` before the `Trainer` does
* when the `Trainer` gets to `wandb.init`, `reinit` is set to `False`, which means this command is ignored by default (including config, project and run names).

Right now when calling `wandb.init` yourself, you should log your config parameters.
A possible alternative would be to call `wandb.config.update(new_config)` within HuggingFace integration which would add/overwrite new keys. Not sure if that should be the default.

**Comment by timothyjlaurent** [comment]
I'm calling `wandb.init(reinit=True)` before `Trainer`.

and I don't see any config. I believe that if I call it without `reinit=True` then the config will log properly from the `Trainer`, in both of these cases, the loss and gradients will log into wandb.

currently I'm updating the config myself with `wandb.config.update`

If I set `WANDB_WATCH=all` though, I don't get any metrics... This is with `reinit=True`

**Comment by borisdayma** [comment]
For info why do you use `reinit=True`?
Its purpose is mainly to close any previous open run (if available) and start a new one.

For allowing logging config automatically on a manually edited run, we will need to update HuggingFace integration though I think it's a reasonable modification.

As for the watch method, it needs to be further investigated.
I did an experiment on GLUE with a Bert model and it logged correctly parameters and gradients on my side: [W&B run](https://wandb.ai/borisd13/huggingface-demo/runs/2a3ob0wm?workspace=user-borisd13).
Maybe your model is extremely large?

**Comment by timothyjlaurent** [comment]
My understanding that `reinit=True` was used if there was something downstream (like the Traininer logic) where init will be run again. If I don't use it, then the run I start where I use artifacts, etc, gets closed and a new run starts when I initialize the trainer. 

My models have been BERT sized or smaller

**Comment by borisdayma** [comment]
Thanks a lot for those details.
In this case, you should not have to use `reinit=True` and it should not affect the rest of your program.

**Comment by borisdayma** [comment]
This issue should be fixed with https://github.com/huggingface/transformers/pull/10826
