### ISSUE TITLE
API: Get the group of a run from the api

### ISSUE THREAD

**Issue by berlino** [wandb/client#1500]
Hi, there:

   I use the Grouping feature a lot with the wandb web, because it helps me group separate train  and eval for the same experiment (very nice!). However, it seems that the group information (also job_type etc) of run can not be found/access from Api.run.  I'm wondering if it is possible to do so?

Thanks!

**Comment by tyomhak** [comment]
Hey! Thanks for using the feature! 
Not sure if API supports that. @vanpelt can you help here?

**Comment by patrickjohncyh** [comment]
Hi! I'm also wondering if this feature is supported!

**Comment by farizrahman4u** [comment]
`group` and `job_type` attributes are available for `Api.run`.

**Comment by meghbhalerao** [comment]
is there some way using the API to just get runs of a particular group? for example it would go something like - 
```
api = wand.Api()
run_group = api.Group(group_name=$name_of_group)
# now I can use this to access all the runs in that group by simple iteration
for run in run_group:
     # do some stuff
       pass
```
Is there something like this or is there some alternate way - the closest thing that I found similar to this was the `Runs` class in the API here - https://docs.wandb.ai/ref/python/public-api/runs 
thanks!
