### ISSUE TITLE
Adding artifacts to finished runs: graph view is not updated

### ISSUE THREAD

**Issue by EliaCereda** [wandb/client#1502]
I'm adding artifacts to a number of finished runs through the API: I have a second script, distinct from the training script that created the runs, to generate the artifacts and link them to the corresponding run.

For this purpose, the second script creates a new run, with job type `generate_artifacts`, generates the artifacts, logs them with `wandb.log_artifact(...)` and waits until they finish uploading, with the method you suggest in #1486. 

Then I fetch the artifacts using `artifact = wandb.Api().artifact(...)` and the original runs with `run = wandb.Api().run(...)` and use the API method `run.log_artifact(artifact)` to link them.

I'm using this method so that the artifacts are linked to both the training run they refer to and the run that actually created them. Furthermore I don't wand to potentially mess up the data of the original run.

For the most part this is working correctly: the artifacts are created and they show up as outputs of both runs (i.e. page `wandb.ai/_/_/runs/_/artifacts`). It appears the graph view of the artifact (i.e. page `wandb.ai/_/_/artifacts/_/_/_/graph`) is not updated though: the original runs do not show up here.

This issue doesn't occur if I resume the original runs and use `wandb.log_artifact(...)` to link the artifacts: in this case the graph view is correctly updated and shows both runs.

EDIT: although I've seen this working when I resumed the original runs, it seems that with the test case that I attached below, the graph view is not being updated in either case. It's broken in both.

## Environment
wandb 0.10.10
Python 3.8.6
macOS 10.15.7

## Reproducer
```python
import wandb

# Create the training run
train_run = wandb.init(job_type='train')
train_run.finish(0)

# Create the run that generates the artifacts
generate_run = wandb.init(job_type='generate_artifacts')

artifacts = []
for i in range(2):
    artifact = wandb.Artifact(f'test-artifact{i}', type='test')
    with artifact.new_file('test.txt', 'w') as f:
        f.write('Test case')
    generate_run.log_artifact(artifact, aliases='test')
    artifacts.append(artifact)

generate_run.finish(0)

# Link the artifact to the training run using the API
api = wandb.Api()
run = api.run(f'{train_run.project}/{train_run.id}')
artifact = api.artifact(f'{train_run.project}/test-artifact0:test', type='test')
run.log_artifact(artifact)
run.update()

# Resume the run and link the artifact using the traditional method
train_run2 = wandb.init(id=train_run.id, resume='must')
train_run2.log_artifact(artifacts[1])
train_run2.finish(0)
```

**Comment by annirudh** [comment]
The reason you're not seeing the training runs reflected in the graph is because when you call `log_artifact` from the `generate_run`, we log an output link from `generate_run` to that artifact. Later, when you call `run.log_artifact` from the training run it produces a second output link, but for the purposes of the graph only the very first output link is considered.

What would you like your graph structure to look like? I would recommend calling `use_artifact` instead of `log_artifact` to link your training run to the artifact produced by the `generate_run`.

**Comment by EliaCereda** [comment]
Thanks for the reply. My confusion came from the fact that I'd seen one method behave in one way and one in another, but it appears that I'm not able to replicate this anymore. 

What you describe makes sense. Although showing both output links would've been more intuitive to me, it's not a big deal. Fortunately, the part that really interests me is seeing the artifact in the list of logged artifacts of both runs and this works correctly.

**Comment by ariG23498** [comment]
Hey @EliaCereda 
Would it be okay to close this ticket as the issue has been addressed? :smile:

**Comment by EliaCereda** [comment]
Yes, thanks again for your support.
