### ISSUE TITLE
Host info through client API

### ISSUE THREAD

**Issue by carloalbertobarbano** [wandb/client#1523]
Is there a way to retrieve system details such as hostname and GPU type through the wandb.Api for a Run object? I couldn't find it on the docs.

**Comment by cvphelps** [comment]
Hi Carlo, thanks for asking about this. We have these metrics in the backend but they're not exposed via the API right now. This will be made available as part of our CLI roadmap, but will be a month or so out.

**Comment by artem-tkachuk** [comment]
Quick "fix" or workaround while the official feature is still not here yet: set `wandb.run.tags = ["<HOSTNAME_HERE>"]` in your script (in my case I used `os.environ["SLURM_JOB_NODELIST"]` for that placeholder) and then get it with `run.tags[0]` when getting runs data through wandb API :)

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
