### ISSUE TITLE
CLI: Offline sync of large files prints lots of terminal noise

### ISSUE THREAD

**Issue by nsidn98** [wandb/client#1531]
I am running my code on a remote cluster that does not have internet access while executing the code. Hence, I have to `scp` the files to my local system and then sync them. The issue with this is that whenever I try to sync large files(>400MB), a huge string of the metrics logged in at each time step gets printed out on the terminal. Would it be possible to suppress that?

My wandb version 0.10.11

**Comment by vanpelt** [comment]
Can you share a screen shot or terminal output of what you're seeing?  Is this happening when you run `wandb sync` or when you are `scp`'ing the data?

**Comment by nsidn98** [comment]
![Screenshot 2020-11-22 at 4 28 20 AM](https://user-images.githubusercontent.com/25846064/99889426-fac85f80-2c7a-11eb-93fd-069af1db25e6.png)
The above screenshot is just a small part of the whole thing which is printed. Actually, similar chunks are printed for other metrics as well(validation losses, etc.). This happens when I run `wandb sync`

**Comment by vanpelt** [comment]
Are there any other error messages surrounding these?

**Comment by nsidn98** [comment]
No, it just keeps on printing these lines for a long time.

**Comment by nsidn98** [comment]
Any updates on this?

**Comment by cvphelps** [comment]
Hi there, could you please share some code/files we could try to reproduce this issue? We'd like to get you a fix but I haven't been able to get this to happen on my own projects.

**Comment by nsidn98** [comment]
Can I email the log folder drive link to reproduce the error?

**Comment by vanpelt** [comment]
Sure, send them to `vanpelt@wandb.com`

**Comment by nsidn98** [comment]
@vanpelt I have sent a drive link to the log files to `vanpelt@wandb.com`

**Comment by vanpelt** [comment]
Thanks, I've received and the ticket will be prioritized in the backlog.

**Comment by nsidn98** [comment]
@vanpelt Are there any updates on this?

**Comment by vanpelt** [comment]
@nsidn98 we have a branch that should fix this.  You can install it locally by running the following:

`pip install --upgrade git+git://github.com/wandb/client.git@fr_sync_fix#egg=wandb`

This should go out in the next official release early next week, thanks for your patience on this one.

**Comment by nsidn98** [comment]
Thanks a lot for looking into this and fixing it!
