### ISSUE TITLE
Question: What happens when a sweep's run crushes?

### ISSUE THREAD

**Issue by Yannik1337** [wandb/client#1535]
I work with W&B with Keras/TF. When I run my models, I use a ModelCheckpoint() callback to ensure fault tolerance. When I now run a sweep, I create a directory on my disk, named after the current run, e.g. `dir_name = wand.run.name`.
Under this directory I periodically save the model weights.

What happens when a run crashes (due to whatever reasons), is it run again **with the same name** so I can check if my directory exists and load weights from there? Other wording: Is the same hyperparameter combination run again the next time after the crash?

**Comment by vanpelt** [comment]
Hey @Yannik1337 to resume crashed runs you'll need to configure your run with resuming using one of the methods as described here: https://docs.wandb.com/library/resuming
