### ISSUE TITLE
Update tracked parameters late in training

### ISSUE THREAD

**Issue by pedrocolon93** [wandb/client#1538]
Hi there! I was just wondering if there was any way to update a model whose parameters have been unfrozen after starting training (i.e. at iteration N, I set requires_grad = True and give it a .grad value). If I do this, the unlocked parameters are not displayed in the visualization.

Thanks!

**Comment by ariG23498** [comment]
Hey @pedrocolon93 could it be possible for us to look at the code and the dashboard screeenshots? It would be a whole lot easier for people to help you if they could see where the probelm was. Thanks!

**Comment by cvphelps** [comment]
Closing for now, we can reopen with further details
