### ISSUE TITLE
Integration: Project renaming breaks TensorBoard loading

### ISSUE THREAD

**Issue by Yannik1337** [wandb/client#1546]
**Describe the bug**
I am using TF 2.3.1 and wandb 0.10.10., and Safari.

I log the data via the TensorBoard callback for keras, and set sync_tensorboard to True. With this settings, everything worked fine the last days. I did not change anything.
As of today, I can not visualize the logged data in TB, this is also for some older logs I did (weeks ago). It says no data, but I can recall using this visualization on this exact run with success.

On my two runs I did yesterday and this morning, I also log data, but the TensorBoard screen stays empty.
I **can't** seem to reproduce this behavior, for the following toy example it works fine:

```
from tensorflow import keras
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import itertools, io, sklearn.metrics, os

!pip install wandb

import wandb
wandb.login()

def do_stuff():
  import tensorflow as tf
  from tensorflow.keras.layers import Input, Dense, Reshape
  from tensorflow.keras import Sequential

  model = Sequential([
    Input(shape=(128)), 
    Dense(20, name="test1"),           
    Dense(3)
  ])

  wandb.init(sync_tensorboard=True)
  wand_cb = wandb.keras.WandbCallback('val_sparse_categorical_crossentropy')

  inp = tf.random.uniform([128, 128], dtype=tf.float32)
  labels = tf.random.uniform([128], 0, 3, dtype=tf.int32)
  labels = np.random.randint(0, 3, size=(128))
  model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=["sparse_categorical_accuracy"])
  #model.summary()

  tb = tf.keras.callbacks.TensorBoard(log_dir="test")


  model.fit(inp, labels, epochs=10, callbacks=[tb, wand_cb])
  print(wandb.run.name)
  wandb.finish()
```

I noticed that I exceed the storage limit by 8 GBs, can this infer? (Also suggesting to send users a notification if quota is reached).

**Comment by ariG23498** [comment]
Thanks for the issue!
I am tagging @cvphelps here so that she can help you with the problem of exhausting the quota (if at all it is the issue here).

**Comment by cvphelps** [comment]
Hi Yannik, thanks. Right now the storage quota doesn't interfere with the app functioning, so this shouldn't be an issue for the TensorBoard instance spinning up. 

Are you saying that you looked at this exact run previously, and now you're not seeing tensorboard work for this very same run? Could you please share a link to the run so we can investigate further?

**Comment by Yannik1337** [comment]
I looked at this run [https://wandb.ai/p_j/b4w/runs/3hjyhqar](https://wandb.ai/p_j/b4w/runs/3hjyhqar) some 30 days ago, and remember seeing stuff visualized. Now it says I have no data logged.

A run from this morning did finish correctly, no errors reported [https://wandb.ai/p_j/b4w/runs/2t13v1dg](https://wandb.ai/p_j/b4w/runs/2t13v1dg). When spinning up TensorBoard, it can not find any data logged. I can however see stuff synced to the cloud, under the "Files" directory in the Dashboard.

I have set the runs/projects to private and would rather not share them publicly; if there is another way to access any necessary files just tell me.

**Comment by Yannik1337** [comment]
I have a guess: I log the same runs to a new project, and they can be visualized without problems.
**Now, I recall renaming the old project some time ago.**
Might this infer on your side with something? This could be a clue to the solution.

**Comment by Yannik1337** [comment]
Update: Have it confirmed, renaming breaks the TensorBoard.
Run below snippet in Colab once:

```
from tensorflow import keras
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import itertools, io, sklearn.metrics, os

!pip install wandb

import wandb
wandb.login()

def do_stuff():
  import tensorflow as tf
  from tensorflow.keras.layers import Input, Dense, Reshape
  from tensorflow.keras import Sequential

  model = Sequential([
    Input(shape=(128)), 
    Dense(20, name="test1"),           
    Dense(3)
  ])

  wandb.init(sync_tensorboard=True, project="test_a")
  wand_cb = wandb.keras.WandbCallback('val_sparse_categorical_crossentropy')

  inp = tf.random.uniform([128, 128], dtype=tf.float32)
  labels = tf.random.uniform([128], 0, 3, dtype=tf.int32)
  model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=["sparse_categorical_accuracy"])
  #model.summary()

  tb = tf.keras.callbacks.TensorBoard(log_dir="test")


  model.fit(inp, labels, epochs=10, callbacks=[tb, wand_cb])
  print(wandb.run.name)
  wandb.finish()

do_stuff()
```

Afterwards, **rename project "test_a" to e.g. "test_b" in the GUI**.
Now, check the TensorBoard feature for this run again in the GUI. It does not work anymore.

As a second step, re-run the code snippet again, changing the project in init to "test_b". This visualization will fail too, albeit it was logged to the already renamed project. This seems like an issue on the side of data handling, not on the client side.

**Comment by sydholl** [comment]
Hi @Yannik1337, this was fixed early this year. Please let us know if you're still experiencing similar issues.
