### ISSUE TITLE
CLI: wandb.login() with custom host prints wrong link to wandb.ai/authorize 

### ISSUE THREAD

**Issue by rjdp** [wandb/client#1551]
**Describe the bug**
On running following, it prompts to get token from wandb.ai/authorize instead of wand.mydomain.com/authorize
`
wandb.login(host="https://wandb.mydomain.com", relogin=False)
`
In colab notebook I had to run following, and this worked as expected 
`
 !wandb login --host=https://wandb.mydomain.com
`

Here is the screenshot

![Screenshot 2020-11-26 at 5 26 23 AM](https://user-images.githubusercontent.com/7734938/100292956-22376900-2fa8-11eb-8275-3869a664660e.png)

**Comment by tyomhak** [comment]
Hi, thanks for flagging this!

**Comment by raubitsj** [comment]
will go out in 0.10.13 release
