### ISSUE TITLE
CLI: Silent mode is not silent

### ISSUE THREAD

**Issue by koaning** [wandb/client#1556]
**Describe the bug**

I'm running `wandb` with `os.environ["WANDB_SILENT"] = "true"` but I'm still seeing this output; 

![image](https://user-images.githubusercontent.com/1019791/100547177-8f2b5700-3265-11eb-9310-477bcfac341c.png)

There's a lot less output with the environment variable set this way. But I wouldn't call it silent. Is it possible to turn this off too or is this a bug? 

This was run on python3.7 with wandb version '0.10.11'.

**Comment by vanpelt** [comment]
Thanks for the bug report, we'll fix this in a future release.

**Comment by tyomhak** [comment]
hey @koaning, I believe this has been fixed in later wandb releases. Can you check if the issue persists for you?
