### ISSUE TITLE
Custom Charts: Add grouping feature

### ISSUE THREAD

**Issue by zimmer-m** [wandb/client#1557]
Hey

**What I want to do**: After completely training a model (and logging all
kind of metrics to wandb) I want to do several computations and plot
custom line plots. I did so using wandb.log and wandb.plot.line
functions as illustrated in the Documentation. In the end, I want to
have various runs, each of which did plot this function, and I want to
compare these function.

**The problem**: When I select grouping within the Wandb webinterface,
metrics that were logged over epochs/steps are grouped as usual, but
custom plots are not. It would be highly valuable for me to compare
these custom functions I plotted, averaged by groups.

While this is not implemented, does someone know a workaround for this?
Thanks!

**Comment by cvphelps** [comment]
Hi Max, thanks for filing a ticket. I saw your email during the Thanksgiving holidays as well — we currently don't support grouping in custom charts but I've added this ticket to the top of our backlog for the project!

**Comment by cvphelps** [comment]
Hi there Max, for the moment here are some rough workarounds:
1. Vega: Specify the grouping inside the vega spec itself
2. Export API: Download logged data to your Python notebook and then log a new 'evaluation' run to W&B where you log the average for yourself

We'd also like to make this possible in the app itself!

**Comment by zimmer-m** [comment]
Hey Carey, thanks for the answers, but found a workaround myself. I just decided to log several metrics using wandb.log after training and then creating the plots I need "by hand" in the webinterface, takes me 2 minutes of extra work but grouping works just fine :+1:

**Comment by cvphelps** [comment]
Hi Max, good point, that's a very reasonable approach as well.

**Comment by frederik-cord** [comment]
In case anyone else needs something similar another day, I used the following vega-lite configuration to group runs in terms of `LineKey`:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A plot for an arbitrary number of lines",
  "data": {
    "name": "wandb"
  },
  "transform": [

    {"filter": {"field": "${field:lineVal}", "valid": true}},
    {"filter": {"field": "${field:step}", "valid": true}},
    {"aggregate": [
      {"op": "average", "field": "${field:lineVal}", "as": "mean_yval"},
      {"op": "ci0", "field": "${field:lineVal}", "as": "y_top"},
      {"op": "ci1", "field": "${field:lineVal}", "as": "y_bottom"}
    ], "groupby": ["lineKey", "step"]}
  ],
  
  "title": "${string:title}",
  "encoding": {
    "x": {          
          "field": "${field:step}",
          "type": "quantitative",
          "title": "${string:xname}"
        }
  },
  "layer": [
    {
      "selection": {
        "grid": {
            "type": "interval",
            "bind": "scales"
          }
      },
      "mark": "errorband",
      "encoding": {
        "y": {
          "field": "y_top",
          "type": "quantitative",
          "scale": {"zero": false}
        },
        "y2": {"field": "y_bottom"},
        "color": {
          "type": "nominal",
          "field": "${field:lineKey}"
        }
      }
    },
    {
      "selection": {
        "grid": {
            "type": "interval",
            "bind": "scales"
          }
      },
      "mark": {"type": "line", "interpolate": "linear"},
      "encoding": {
        "y": {
          "field": "mean_yval",
          "title": "y",
          "type": "quantitative"
        },
        "color": {
          "type": "nominal",
          "field": "${field:lineKey}"
        }
      }
    }
  ]
}
```
Where values are logged individually for each run with 
```python
wandb.plot.line_series(xs=xvalues,
        ys=[yval1, yval2, yval3],
        keys=['lineKey1', 'lineKey2', 'lineKey3',
        title="",
        xname="")
```
I takes the plot from left to right.
<img width="923" alt="Screenshot 2022-01-13 at 15 58 39" src="https://user-images.githubusercontent.com/93145535/149355519-5c8fddce-d625-421d-bedc-c5e60285005e.png">

**Comment by gil2rok** [comment]
Can someone please implement this feature? Would be immensely helpful in the web UI to group according to custom charts.

**Comment by alxndrTL** [comment]
I'm also interested in enabling grouping in custom charts.
I have tried to play around with the `filters` field to filter according to the Group field but this gives me "No data available", as seen in the figure attached. I guess we can't apply two filters based on the same field. Looking for a solution to group in custom charts (it seems that the workarounds found above are outdated now)

![Capture d’écran du 2024-08-17 10-30-25](https://github.com/user-attachments/assets/9ccbd74f-0094-4649-a6f4-05eea6946b8f)
