### ISSUE TITLE
AlreadyExistsError() when a Sweep run throws OOM error

### ISSUE THREAD

**Issue by Yannik1337** [wandb/client#1567]
I am using Kubernetes. In the container I call my python script. The following excerpts are the parts where the sweep starts:

```
def train():
 hyperparameter_defaults = {
     'num_conv1':24, #conv should be multiple of 8
     'num_conv2':32,
     'num_conv3':64,
     'num_conv4':128,
     'dropout1':0.1,
     'dropout2':0.1,
     'dropout3':0.1,
     'dropout4':0.1,
     'win_length': 512,
     'n_fft':2048,
     'n_mels':60,
     'frame_length':41,
     'hop_length':64,
     'dropout5':0.5,
     'num_dense':512, #dense should be multiple of 8
     'epochs':300
  }
  wandb.init(reinit=True, config=hyperparameter_defaults) #create some configs for the hyperparams
  config = wandb.config
...
```
and later in the script 

```
if __name__ == "__main__":
...
  sweep_config = get_sweep_config()
  sweep_id = wandb.sweep(sweep_config, project='test')
  wandb.agent(sweep_id, function=train, project='test')


```

When the first sweep run -- due to hyperparameter settings that exceed the boundaries -- throws an OOM error, the further ones are throwing these errors:

...
Run k7jsol3b errored: AlreadyExistsError()
wandb: ERROR Run k7jsol3b errored: AlreadyExistsError()
...
Run uu1xyrmp errored: AlreadyExistsError()
wandb: ERROR Run uu1xyrmp errored: AlreadyExistsError()
...
Run 574frvcl errored: AlreadyExistsError()
wandb: ERROR Run 574frvcl errored: AlreadyExistsError()
Detected 5 failed runs in a row at start, killing sweep.
wandb: ERROR Detected 5 failed runs in a row at start, killing sweep.
wandb: To change this value set WANDB_AGENT_MAX_INITIAL_FAILURES=val

Any suggestions to alleviate this errors?

**Comment by vanpelt** [comment]
Hey @Yannik1337, can you try removing the `reinit=True` argument?  You will also likely want to call `wandb.finish()` at the end of the `train()` function, although I think we'll automatically finish the run for you in this mode.

**Comment by farizrahman4u** [comment]
@Yannik1337 I was unable to reproduce the error. This is the code I used:

```python
import wandb


def get_sweep_config():
    return {
        'method': 'bayes',
        'metric':{
            'name': 'acc'
        },
        'parameters':{
            'a':{'min': 0, 'max': 10},
            'b':{'min': 0, 'max': 10},
            'c':{'min': 0, 'max': 10}
        }
    }

first = True
def train():
    hyperparameter_defaults = {
        'a': 1,
        'b': 2,
        'c': 3
    }
    wandb.init(reinit=True, config=hyperparameter_defaults) 
    config = wandb.config
    print(config)
    global first
    if first:
        first = False
        raise Exception("OOM")


if __name__ == "__main__":
    sweep_config = get_sweep_config()
    sweep_id = wandb.sweep(sweep_config, project='test')
    wandb.agent(sweep_id, function=train, project='test')
```

Are there any key differences between this and your setup?

**Comment by Yannik1337** [comment]
I think I traced back the problem to *sigh* TensorFlow. Clearing GPU memory is sadly a struggle with it so far.
Different to the above setup, I instantiate my TF/Keras model in the train() method and thus block VRAM. This means each time a new model is created - which is correct, since the model's architecture might drastically change (e.g. more convolutions, more dense layers,..).

One solution I thought of:
Since I use Kubernetes, I run my scripts from a .yaml file. Wandb is **not** installed on the Linux host, but within a Docker image. Is there any recommended procedure to run one yaml Docker file, that then calls my training script n times? This would remove the need for clearing VRAM since each script takes only one architecture search (and not k, which is the case now).

I suggest you stalling or halting this issue; I plan to do further research into this. I'll update with any further findings.

**Comment by vanpelt** [comment]
Hey @Yannik1337, one approach is to start the sweep agent on a machine that has access to `kubectl` and can talk to your kubernetes cluster.  Then the script that the agent executes could launch a pod into the cluster with the appropriate hyper-parameters in an environment variable or mounted into the container.

Another potentially simpler approach is to you run 2 process in your pod.  The main process starts the agent and then instead of running the code directly in a function it could spawn another process that actually does the training.

**Comment by Yannik1337** [comment]
Hey @vanpelt , thank you for your help. The sweep is now running- I have used your web GUI to create a sweep and then run an agent from my .yaml file.

As a sidenote, I log a metric with wandb.log({"A metric":123}). Note the spaces: They result in an GraphQL 500 error:

500 response executing GraphQL.
{"errors":[{"message":"anaconda 400 error: {\"code\":400,\"message\":\"ValueError: nan is not in list\"}\n","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"ValueError: nan is not in list"}
wandb: ERROR  (<Response [500]>)

When I then log the metric without spaces and update my sweep_config.yaml

metric:
  goal: minimize
  name: A_metric 

everything works. TL;DR: spaces in the metric the sweep depends on leads to breaking the sweep.
