### ISSUE TITLE
Getting url from run using python library.

### ISSUE THREAD

**Issue by miraodasilva** [wandb/client#1572]
**Problem or Use Case**
I would like to keep wandb silent, but print only the run/project URLs. I can get them for the log and print them but that doesnt seem like a very elegant solution.

**Suggested Solution**
 I would like to access these urls for my run using the python library. I took a look at the docs for environment variable and config and I could not find this. I'm pretty sure there is a way to do this but I can't find it. Thanks a lot in advance.

**Comment by vanpelt** [comment]
Hey @miraodasilva you can call `wandb.run.get_url()` after you've called wandb.init:

https://github.com/wandb/client/blob/master/wandb/sdk/wandb_run.py#L492

**Comment by miraodasilva** [comment]
Thanks! I could not find this in the docs (I guess it's probably there but I missed it).
