### ISSUE TITLE
Cannot access settings tab in web application

### ISSUE THREAD

**Issue by mswedrowski** [wandb/client#1575]
**Describe the bug**
I'm not sure whether it is the right place to report this bug, however, I cannot find any option to report a bug directly via the web page.Whenever I try to access settings tab ( https://wandb.ai/settings ) I receive an error "_Cannot query field "slackClientID" on type "ServerInfo"_ ". There is an option to refresh the page, but whenever I try to refresh prompt appears again.

**To Reproduce**
1. Open web application
2. Click on account avatar in top right corner
3. Select "Settings' tab

**Screenshots**
![image](https://user-images.githubusercontent.com/26623415/101138932-1cc5c880-3611-11eb-9e79-30e67defb3de.png)

**Operating System**
 - OS: Linux Ubuntu 20.4
 - Browser: Chrome Version 87.0.4280.66 (Official Build) (64-bit)

**Additional context**
wandb account: mswedrowski

**Comment by cvcore** [comment]
same problem here. Tried with 2 different accounts.

**Comment by vanpelt** [comment]
Sorry about this, we fixed the issue 2 hours ago it was a bad deploy.
