### ISSUE TITLE
Using W&B with PDB causes navigation and control keys to not work.

### ISSUE THREAD

**Issue by seanswyi** [wandb/client#1581]
**Describe the bug**
Using the Python Debugger along with W&B causes the interactive shell of the debugger to malfunction. It works, but you can no longer use keys like backspace, <kbd>CTRL</kbd> + <kbd>(something)</kbd>, etc.

**To Reproduce**
Reproduction is fairly simple. Just add a `import pdb; pdb.set_trace()` anywhere in your code, and when the script returns the  PDB interactive shell just press <kbd>backspace</kbd>.

**Expected behavior**
Backspace (or whatever key you pressed) will return `~[[A`, etc.

**Operating System**
 - OS: Ubuntu 16.04
 - Browser: No browser.
 - Version: 0.10.12

**Comment by ariG23498** [comment]
Hey @seanswyi 
I tried reproducing your issue in my system

**System Config**
- OS: Ubuntu 18.04
- Version: 0.10.12

**Code Used**
```python
import wandb
defaults = dict(seed=42, filter_size=3)
wandb.init(entity="xxx", project="pdb_issues",config=defaults)
log = 2*wandb.config["filter_size"] - 0.01*wandb.config["seed"]
import pdb
pdb.set_trace()
wandb.log({"output":log})
wandb.finish()
```
**Issues**
I did **not** find any probelm while using `backspace`. The only problem that I face is with the navigation keys. The `left`, `right`, `up` and `down` arrows seem to be outputting `^[[D`, `^[[C`, `^[[A` and `^[[B` respectively.

**Comment by seanswyi** [comment]
Hey @ariG23498 thanks for helping out. It's interesting how you're not getting the same error, as when I type backspace I get `^H`.

**Comment by farizrahman4u** [comment]
I'm working on this (will take some time). In the mean time you can set environment variable `WANDB_CONSOLE="off"` as a workaround.

**Comment by seanswyi** [comment]
@farizrahman4u Thanks for the tip! This will save my team and me some headache. :) Just one question though. Would you by any chance happen to know if setting this environment variable would potentially cause any unwanted behavior/problems? For example if it may affect other environment variables or system behavior, etc.

When I tested it there didn't seem to be any problems, but I'd just like to know the opinion of someone who's more knowledgeable than I am.

Thanks again!

**Comment by vanpelt** [comment]
Hey @seanswyi the only impact this will have on your environment is how we render output to the terminal.  By setting the console to wrap you may see messages starting with `wandb:` interspersed with the output that you're writing to the terminal.  Behind the scenes there's some rather complicated logic to enable our sub-process to synchronously write lines to your processes output.  That's what we believe is interacting poorly with pdb and the ultimate fix is a bit more involved...

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
