### ISSUE TITLE
`wandb sweep --update` does not behave as expected.

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/client#1584]
**Describe the bug**
`wandb sweep --update` throws a usage error when all arguments are provided. 

**To Reproduce**
```
❯ wandb sweep --update refactor.yaml
Usage: wandb sweep [OPTIONS] CONFIG_YAML
Try 'wandb sweep --help' for help.

Error: Missing argument 'CONFIG_YAML'.
```

**Expected behavior**
The documentation for `wandb sweep --update` is pretty sparse, so I'm not exactly sure... I was actually running this to see what it would do. But it looks like I am feeding it all the required arguments, so I would expect it to do something besides throwing a usage message.

**Operating System**
 - OS: ubuntu 18.04
 - Version 0.10.11

**Comment by ethanabrooks** [comment]
Ok. Adding some print statements to `cli.py`, it looks like the correct way to do this would be:
```
wandb sweep --project ppo --entity ethanabrooks --update fchbf5b5 refactor.yaml
```
where `ethanabrooks` is my username (wasn't clear on that), `fchbf5b5` is the sweep id, and `refactor.yaml` is the name of config file. Can I help add some documentation for these?

**Comment by ariG23498** [comment]
Hey @ethanabrooks 
We are sorry about the problems that you had to face.
You can pass the entity and the project name in the sweep yaml file itself. 
```yaml
project: ppo
entity: ethanabrooks
program: train.py
method: bayes
```
The sweep id is what you need to provide as an argument for the sweep to resume.
Actually in the [docs](https://docs.wandb.com/ref/cli#wandb-sweep) we have it mentioned that the `--update` will update a `pending sweep`. This means that it updates the sweep id that was pending.

CC: @cvphelps

**Comment by ethanabrooks** [comment]
I see. Thanks for the recommendation. Is there a place in the documentation where it explains what `entity` is?

**Comment by vanpelt** [comment]
`entity` is your username or a team name: https://docs.wandb.com/ref/init-1#wandb-sdk-wandb_init

**Comment by vanpelt** [comment]
Sorry about that, we're reworking our documentation and that link disappeared.  Entity is either your username or the name of a team that you are a member of.
