### ISSUE TITLE
How to copy a RUN from one project to another?

### ISSUE THREAD

**Issue by ShuteLee** [wandb/client#1587]
**Problem or Use Case**
How to copy a RUN from one project to another?

**Comment by cvphelps** [comment]
Hi @ShuteLee here's the details from our Documentation https://docs.wandb.com/app/features/sidebar#move-runs-between-projects

To move runs from one project to another:

1. Expand the table
2. Click the checkbox next to the runs  you want to move
3. Click move and select the destination project

![how to move runs in weights and biases ui](https://user-images.githubusercontent.com/6355078/101429771-929f8d80-38b8-11eb-9fae-ccf6f411eb9d.gif)

**Comment by ShuteLee** [comment]
It works, Thank you very much

**Comment by ehannigan** [comment]
Can this be done in python using the api?

**Comment by ash0ts** [comment]
@ehannigan, While there is no straightforward function to do so, you can utilize a combination of the public API's methods to achieve a similar effect. Is there a specific use case that you would find yourself using the API over the UI consistently?

**Comment by ash0ts** [comment]
Hey, @ehannigan were you able to figure out how to move runs with the [public API](https://docs.wandb.ai/ref/python)? If not I can make a minimal example to try to show something to that effect
