### ISSUE TITLE
Warn about large summary by mistake

### ISSUE THREAD

**Issue by elbaro** [wandb/client#1589]
**Problem or Use Case**
I had a bug in my script that `wandb.log` very large array. wandb hanged at `wandb: - 0.00MB of 0.09MB uploaded (0.00MB deduped)` and timed out. (The array was larger than 0.09MB) Also the web page for the run didn't load.

**Suggested Solution**
Please warn or crash if the metric is larger than w&b can handle. Crash is better because w&b will not work normally.

**Additional context**
@vanpelt helped find out the cause.
> the run you were trying to access has over 3MB of data in the summary field.  It looks like some very large arrays of numbers were stored in that summary.  We're going to clear the summary so that the page will load.

**Comment by ariG23498** [comment]
Thanks for the ticket @elbaro :smile:

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by icoderzqliu** [comment]
> 

I met the same question, how to solve it?

**Comment by icoderzqliu** [comment]
> **Problem or Use Case** I had a bug in my script that `wandb.log` very large array. wandb hanged at `wandb: - 0.00MB of 0.09MB uploaded (0.00MB deduped)` and timed out. (The array was larger than 0.09MB) Also the web page for the run didn't load.
> 
> **Suggested Solution** Please warn or crash if the metric is larger than w&b can handle. Crash is better because w&b will not work normally.
> 
> **Additional context** @vanpelt helped find out the cause.
> 
> > the run you were trying to access has over 3MB of data in the summary field.  It looks like some very large arrays of numbers were stored in that summary.  We're going to clear the summary so that the page will load.

I met the same question, how to slove it? BTW, how to clear the summary.

**Comment by zxy960307** [comment]
I also want to know how to solve

**Comment by ZiyeLuo** [comment]
I met the same question, how to slove it?

**Comment by ShuzhiLiu** [comment]
wandb: | 0.038 MB of 0.038 MB uploaded (0.000 MB deduped)

**Comment by woodenchild** [comment]
Same issues:
wandb: \ 0.028 MB of 0.028 MB uploaded (0.000 MB deduped)
Ctrl C does not work. I have stopped the task on the web and deleted it, while it can not stop.
It happens when I early stop the task by Ctrl C/Z. Please help me :)

**Comment by guzy0324** [comment]
same

**Comment by bestpredicts** [comment]
same error here

**Comment by joinvalgo** [comment]
If the log output is bothering you, press Ctrl+pq in order to stop that message. It will disconnect the terminal from the container output.

**Comment by pebonazzi** [comment]
Same here, it happens when I stop the task with Ctrl C. 
It makes the terminal unusable.

**Comment by sitzikbs** [comment]
Same issue here.

**Comment by BennoKrojer** [comment]
Same, the only solution is running "pkill wandb-service" from another terminal which unfortunately also stops all your other runs currently running...

**Comment by dongzhuoyao** [comment]
same.

**Comment by amritkumar9595** [comment]
same

**Comment by barathwaj07** [comment]
same

**Comment by sjtuytc** [comment]
same

**Comment by svetlov** [comment]
same

**Comment by tdye24** [comment]
This leads to the sweep can't start a new run (cry

**Comment by Alasdair-P** [comment]
same issue for me keep posting "wandb: - 0.059 MB of 0.059 MB uploaded (0.000 MB deduped)" or similar to the terminal after I kill a job

**Comment by Shinning-Zhou** [comment]
same

**Comment by CJStromberger** [comment]
I have the same issue. Also want to know if this will be reopened

**Comment by askerlee** [comment]
In my case the messages repeat on the ssh console, and my workaround is to disconnect ssh and then reconnect.
