### ISSUE TITLE
`wandb.watch(model)` is not logging gradients.

### ISSUE THREAD

**Issue by seanswyi** [wandb/client#1594]
**Describe the bug**
The title is pretty much the issue, but when I call `wandb.watch(model)` after instantiating my model the gradients are not showing up on my dashboard.

I've successfully used `wandb.watch` with other models, and its this particular case that seems to be the problem, so I'm pretty sure this isn't exactly a "bug," but I believe that I'm misunderstanding how watching models should behave and would appreciate it if anyone more knowledgeable than me could help.

**To Reproduce**
Line #147 of [this file](https://github.com/seanswyi/transformer-implementation/blob/main/src/main.py) is where I call `wandb.watch` after instantiating my model and putting it on the GPU device.

**Operating System**
 - OS: Ubuntu 16.04
 - Browser: Google Chrome
 - Version: 0.10.21

**Comment by seanswyi** [comment]
My apologies. For some reason the code I was actually running locally had this commented out. I'll close the Issue.

**Comment by cvphelps** [comment]
Haha thanks Sean :)
