### ISSUE TITLE
api_key not configured OSX Big Sur - PyCharm

### ISSUE THREAD

**Issue by emadboctorx** [wandb/client#1596]
**Describe the bug**

Unable to run `wandb.init()` from PyCharm - macOS Big Sur

**To Reproduce**
[in PyCharm**]

```
import wandb
wandb.init(name='name', project='project')
```

**OUT:**

```
Traceback (most recent call last):
  File "/Users/emadboctor/Desktop/DeepRL-TensorFlow2/DQN/DQN_Discrete.py", line 23, in <module>
    wandb.init(name='name', project='project')
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 572, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 138, in setup
    wandb_login._login(anonymous=anonymous, force=force, _disable_warning=True)
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 202, in _login
    wlogin.prompt_api_key()
  File "/usr/local/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 144, in prompt_api_key
    raise UsageError("api_key not configured (no-tty).  Run wandb login")
wandb.errors.error.UsageError: api_key not configured (no-tty).  Run wandb login
```
 
It runs fine from the terminal (same interpreter python 3.8.6)

```
>>> import wandb
>>> wandb.init(name='name, project='project')
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 
```

**Expected behavior**

Same behavior as the terminal.

**Screenshots**

**Operating System**
 - OS: macOS 11.0.1 (Big Sur)

**Additional context**
wandb v0.10.12

**Comment by ariG23498** [comment]
Hey @emadboctorx 
Thanks for the ticket.
We will get into this as soon as possible.
Until then, the workaround would be to run `wandb login` in your terminal and authorize yourself. This will add a `~/.netrc` file in your system that has your api-key. After this, `wandb.init()` would work as required.

Let us know if this solves the issue.
Your concern about the different behaviours in the script and terminal is taken under consideration.

CC: @cvphelps @vanpelt could you look into this?

**Comment by emadboctorx** [comment]
Yes, it solves the problem

**Comment by ariG23498** [comment]
Closing this issue. Please feel free to reopen it if need be.

**Comment by nialloh23** [comment]
Confirming that I'm still having this problem on OSX Big Sur - PyCharm

**Comment by ariG23498** [comment]
Hey @nialloh23 
Did the workaround provided above help?

**Comment by nialloh23** [comment]
@ariG23498 This workaround of manually logging in from the terminal worked for me.
This got a little frustrating after a while as you end up having to do it quite often.
I found a better fix which involved using the API to explicitly login at the start of my script.
Some context: this issue started affecting my runs around Dec and I just got it sorted with this solution today.
Not sure if it is linked to the Big Sur/Pycharm reason in this issue but this matches my OS and ENV directly .
Hope this helps.

**Comment by xbbkok** [comment]
> Hey @emadboctorx
> Thanks for the ticket.
> We will get into this as soon as possible.
> Until then, the workaround would be to run `wandb login` in your terminal and authorize yourself. This will add a `~/.netrc` file in your system that has your api-key. After this, `wandb.init()` would work as required.
> 
> Let us know if this solves the issue.
> Your concern about the different behaviours in the script and terminal is taken under consideration.
> 
> CC: @cvphelps @vanpelt could you look into this?

Thanks! Today I encountered the same problem,and this way solved it!!
