### ISSUE TITLE
Scatter plot does not correctly compute running average line

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/client#1603]
**Describe the bug**
The running average line appears to be off, based on visual inspection. It looks like points which correspond to the same x-value are being assigned to different x-values and therefore not being aggregated in the same mean.

**To Reproduce**
1. Open a sweep.
2. Click on the '+' in a panel to create a scatter plot. Plot a hyperparameter against some metric like reward or error.
3. Click the annotations tab and select the "Plot running average y values" checkbox.
4. Click ok.

**Expected behavior**
I expect the plotted average line to correspond to my visual intuition based on the placement of points on the graph. I also expect the line to not have discontinuities at each y-value where points are plotted.

**Screenshots**
![image](https://user-images.githubusercontent.com/10344742/101913469-0a0f3e80-3b91-11eb-8f71-8da39887d5e1.png)

**Operating System**
 - OS: macOS Big Ser
 - Browser Chrome
 - Version Version 87.0.4280.88

**Comment by cvphelps** [comment]
Hi Ethan, thanks for sharing this request. Could you please share a link to the page where you're seeing this?

**Comment by ethanabrooks** [comment]
Of course! 
This is a share of the graph: https://wandb.ai/ethanabrooks/ppo/reports/Shared-panel-20-12-12-09-12-86--VmlldzozNjMwNjg?highlightShare?accessToken=j1momsqhzjmg4v1fyagbkpg6sx73s4fx3niatuuu3tcp5yz51gf5zk67i71n6939
This is the sweep workspace: https://wandb.ai/ethanabrooks/ppo/sweeps/mq70zyt3?workspace=user-ethanabrooks

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
