### ISSUE TITLE
CLI: TensorBoard no longer working in 0.10.+

### ISSUE THREAD

**Issue by cvphelps** [wandb/client#1605]
[From Ben in the W&B Forum](https://wb-forum.slack.com/archives/CL4V2QE59/p1607509654442500):

I recently upgraded from a somewhat outdated 0.9.* wandb version and noticed that sync_tensorboard doesn't work for me anymore from version 0.10.0 on. I see that the release notes mention some Tensorboard-related fixes here and there, but the issue also exists in the newest 0.10.12 version, so those fixes were perhaps for different issues.
Both Tensorflow and Tensorboard are version 2.3.0 . Perhaps W&B misses the Summary events somehow? It used to work in 0.9.1 at least, even with TF 2. Perhaps I have to explicitly point it to the directory the tfevent file is written to now somehow (not sure if there's an option for that)? 

We use TF2, but still have some legacy Estimator models. These log via tensorflow.python.summary.writer.writer, the integration with which was apparently removed in W&B 0.10.0  (the module was called TENSORBOARD_LEGACY_MODULE there).
I can get some plots to show up by setting wandb.integration.tensorboard.monkeypatch.ENSORBOARD_WRITER_MODULE="tensorflow.python.summary.writer.writer"  and setting tensorflowX=True to avoid the TF2-codepath that patches create_summary_file_writer instead.
Unfortunately not all plots show up yet and they also end up in different sections in W&B, perhaps because pre-0.10.0 W&B patched EventFileWriter.add_event and now the EventFileWriter is instead subclassed as TBXEventFileWriter with some custom callbacks.

As a workaround, copying the old add_event related code from the 0.9.7 release that still included it seems to be a workaround. I'd use it to patch tensorflow.python.summary.writer.writer manually, since otherwise it doesn't seem supported anymore in 0.10.0 or greater.

**Comment by iantheconway** [comment]
I'm also missing some metrics in WANDB that I see in my tensorboard. These metrics used to show up in wandb with an earlier version, I believe.


wandb==0.10.12
tensorflow==2.3.1
tensorboard==2.4.0

**Comment by cvphelps** [comment]
Thanks @iantheconway, could you please share a repro script and a link to the page where you're seeing metrics missing? We'd like to track this one down and get in a fix.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
