### ISSUE TITLE
Image overlap when logging

### ISSUE THREAD

**Issue by juneskiafc** [wandb/client#1609]
**Describe the bug**
When I log multiple images with the same key, the images show up in the UI as overlapped.

**To Reproduce**
1. Log image with same key over multiple steps
2. See images from those steps shown in UI as one image, each image overlapped on top of each other. 

**Expected behavior**
Each step should have one image that I can see with the step slider.

**Screenshots**
![media_images_val_confusion matrix_18_648a50ee](https://user-images.githubusercontent.com/61970566/102043926-be80ae80-3da3-11eb-9f54-27fabeef6c92.png)

**Additional context**
Using:
pytorch_lightning==1.1.0
wandb==0.10.12
torch==1.3.1

**Comment by vanpelt** [comment]
Hey @juneskiafc can you share a snippet of code showing how you're logging the images?  Also a link to a run with this behavior would be helpful for debugging.

**Comment by juneskiafc** [comment]
heatmap = sns.heatmap(data=confmat_df, annot=True, fmt='.3f')
trainer.logger.experiment.log({f"confmat": wandb.Image(heatmap.get_figure())}, commit=False)

Unfortunately cannot share the run, unless there's a way to share one specific run without making the whole project public?

**Comment by vanpelt** [comment]
Hey @juneskiafc can you try logging the figure directly without wrapping it in a image?  Also, if you can provide a small snippet with dummy data populated in `confmat_df` we can likely reproduce.

**Comment by juneskiafc** [comment]
If I try to log the image without wrapping it with wandb.Image, I get some weird errors related to mpl_to_plotly being deprecated. I do get a plotly plot in the UI, though, but it's missing all the nice colors of the seaborn heatmap.

I'll get back to you with a minimal reproducible example.

**Comment by juneskiafc** [comment]
```
from pytorch_lightning.loggers.wandb import WandbLogger
import pytorch_lightning as pl
from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset
import torch
import torch.nn as nn

import pandas as pd
import seaborn as sns
import wandb

class WandbLogImage(pl.callbacks.Callback):
    def __init__(self):
        super().__init__()

    def on_train_epoch_end(self, trainer, pl_module, outputs):
        self.log_confusion_matrix(pl_module.confmat)
    
    def log_confusion_matrix(self, confmat):
        confmat = confmat.detach().cpu().numpy().reshape(4, 4)
        confmat_df = pd.DataFrame(confmat)
        confmat_heatmap_seaborn = self.get_confmat_heatmap_seaborn(confmat_df)

        trainer.logger.experiment.log({f"confmat": wandb.Image(confmat_heatmap_seaborn)}, commit=False)
    
    def get_confmat_df(self, confmat):
        return pd.DataFrame(confmat)
    
    def get_confmat_heatmap_seaborn(self, confmat_df):
        confmat_heatmap = sns.heatmap(data=confmat_df,
                                      cmap='RdYlGn',
                                      annot=True,
                                      fmt='.3f',
                                      cbar=False)

        confmat_heatmap.xaxis.set_label_position('top')
        confmat_heatmap.tick_params(axis='x', which='both', bottom=False)

        return confmat_heatmap.get_figure()

class MinimalPLModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.dummy_linear = nn.Linear(4, 1)
        self.dummy_loss = nn.L1Loss()

        self.confmat = None

    def forward(self, x):
        return self.dummy_linear(x)
    
    def training_step(self, batch, batch_idx):
        x, _ = batch
        self.confmat = x
        output = self(x)
        loss = self.dummy_loss(output, output)

        return loss
    
    def configure_optimizers(self):
        return Adam(self.parameters(), lr=1e-3)

class DummyDataset(Dataset):
    def __getitem__(self, index):
        return torch.rand(size=(4, 4)), torch.Tensor([1])
    
    def __len__(self):
        return 1

class DummyDataModule(pl.LightningDataModule):
    def __init__(self):
        super().__init__()
    
    def setup(self, stage=None):
        self.train_dataset = DummyDataset()

    def train_dataloader(self):
        return DataLoader(self.train_dataset, batch_size=1)
        
callbacks = [WandbLogImage()]
logger = WandbLogger('wandb_bug', project='hassanpour')

trainer = pl.Trainer(logger=logger,
                     callbacks=callbacks,
                     gpus=[3],
                     max_epochs=2,
                     num_sanity_val_steps=0,
                     deterministic=True,
                     fast_dev_run=False)

model = MinimalPLModel()
trainer.fit(model, datamodule=DummyDataModule())
```

**Comment by juneskiafc** [comment]
Never mind, I got it! I just have to clear the current active matplotlib figure with plt.clf() before creating the heatmap.

**Comment by vanpelt** [comment]
Awesome, glad to hear you figured it out!
