### ISSUE TITLE
Wrong Column/Key Names

### ISSUE THREAD

**Issue by ludwigwinkler** [wandb/client#1611]
**Describe the bug**
The names of the columns in the table view are wrongly displayed.
The charts are correctly named though.

Here are a couple of screenshots:
![Screenshot 2020-12-14 at 21 03 45](https://user-images.githubusercontent.com/29676773/102129752-28ef2880-3e50-11eb-81fc-cf7b01e4267a.png)
![Screenshot 2020-12-14 at 21 04 06](https://user-images.githubusercontent.com/29676773/102129765-2e4c7300-3e50-11eb-8c4e-d17dd6fe0202.png)
![Screenshot 2020-12-14 at 21 04 24](https://user-images.githubusercontent.com/29676773/102129771-33112700-3e50-11eb-8b64-bc8402cd2276.png)

You can see that the table view parses the column names wrongly by creating additional columns for "train/u_min" and "Min U"  instead of leaving it at "MinU" which is correctly shown in the chart view.

Additionally, "Train_Epoch/LL" should actually be "Train/EpochLL" so it's substituting characters for some reason.
It should be noted that the correct columns are shown.

**Comment by ariG23498** [comment]
Hey @ludwigwinkler 
Thanks for the ticket.
It would be great if you could share a basic implementation and a public project with us, so that our team could reproduce the issue themselves.

I am tagging @cvphelps on this ticket for more help. :smile:

**Comment by cvphelps** [comment]
HI Ludwig, could you please share some sample code so we can repro here
