### ISSUE TITLE
Weird behavior of typing after wandb.init()

### ISSUE THREAD

**Issue by cccntu** [wandb/client#1612]
**Describe the bug**
See this example:
```
>>> import typing
>>> x =typing.Optional[bool]
>>> x is typing.Optional[bool]
True
>>> import wandb
>>> x is typing.Optional[bool]
True
>>> wandb.init()
wandb: Offline run mode, not syncing to the cloud.
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` to enable cloud syncing.
<wandb.sdk.wandb_run.Run object at 0x7f3f75729ca0>>>>

>>> x is typing.Optional[bool]
False
>>> x =typing.Optional[bool]
>>> x is typing.Optional[bool]
True

```
**To Reproduce**
see above

`x is typing.Optional[bool]` should be true right after `wandb.init()`, which is true in python 3.7.9

**Operating System**
 - OS: ubuntu
 - Version 18
**Additional context**
I tired python 3.8.3 and 3.8.5, the result is the same.

**Comment by ariG23498** [comment]
Hey @cccntu 
I tried reproducing the above issue, but did not face the problem.
The only thing I did differently was to have an active internet connection while using the `wandb.init()` command.

**Comment by cccntu** [comment]
@ariG23498 Thanks. But I only used offline mode for a smaller output size. My result is the same with active internet connection. I will try to reproduce it and share more environment details.

**Comment by cccntu** [comment]
I cannot reproduce the bug with a new conda environment on the same machine. It's probably that the environment is broken somehow. Any idea on how to fix a broken environment?

**Comment by ariG23498** [comment]
Hey @cccntu 
What I can suggest you here is to have a fresh environment and then check if the issue persists. I am keeping this issue open till some time.
