### ISSUE TITLE
TypeError: 'bool' object is not callable when used with FastAI v1

### ISSUE THREAD

**Issue by bnapora** [wandb/client#1613]
Using wandb callback for fastai v1 get "TypeError: 'bool' object is not callable'" error.  When WandbCallback is removed then error disappears.  This error is appearing after recently upgrading wandb version (not sure which version but I believe it was when upgrading from 0.10.10 to 0.10.11...currently using 0.10.12) (Note: I downgraded wandb back to 0.10.9 but error still persists.)

**Wandb Setup is:**
    import wandb
    from functools import partialmethod
    from wandb.fastai import WandbCallback
    wandb.init(config=params, project=params['project'], name=params['wandb_run_name'], reinit=True)
    wandb.watch = False
    config = wandb.config

Wandb session is initiated successfully

   callbacks = [BBMetrics, ShowGraph, partial(WandbCallback, input_type='images')]
   learn = Learner(data, model, loss_func=crit, callback_fns=callbacks, metrics=[voc])

Error appears when either running:
learn.lr_find() or
learn.fit_one_cycle()

**Last 2 moduless of error trace are (can provide full trace if relevant):**

/opt/conda/envs/fastai1-wsi/lib/python3.7/site-packages/fastai/callback.py in _call_and_update(self, cb, cb_name, **kwargs)
    239     def _call_and_update(self, cb, cb_name, **kwargs)->None:
    240         "Call `cb_name` on `cb` and update the inner state."
--> 241         new = ifnone(getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs), dict())
    242         for k,v in new.items():
    243             if k not in self.state_dict:

/opt/conda/envs/fastai1-wsi/lib/python3.7/site-packages/wandb/integration/fastai/__init__.py in on_train_begin(self, **kwargs)
    120 
    121             # Logs model topology and optionally gradients and weights
--> 122             wandb.watch(self.learn.model, log=self.log)
    123 
    124     def on_epoch_end(self, epoch, smooth_loss, last_metrics, **kwargs):

TypeError: 'bool' object is not callable

**Environment:**
Jupyter Notebook running on Ubuntu 18.04

(If there is additional information I can provide, please let me know.)

**Comment by borisdayma** [comment]
Hi @bnapora,

You shouldn't use `wandb.watch = False`, you just need to use `partial(WandbCallback, input_type='images', log=None)`

See here for more details: 
https://docs.wandb.com/integrations/fastai/v1

**Comment by ariG23498** [comment]
Hey @bnapora 
It would be great if you could report back with your implementation :smile:.As @borisdayma has suggested a solution that should work in the case, we are closing this issue. Please feel free to comment to reopen this ticket if the issue persists.

**Comment by bnapora** [comment]
Sorry for tardy response.  I misunderstood solution in #961 which said to use WANDB_WATCH=False to solve issue, and instead used wandb.watch = False.  After adding WANDB_WATCH=False I'm able to make a successful run.  Thanks for the quick and timely response.
