### ISSUE TITLE
Create more frontend tests

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#162]
In general let's use the `yarn test --coverage` option to see where we're lacking on tests.  Ideally we would get the most files in the yellow. The following are places to focus

New pages: Signup, Team, Timeline, Dashboard (Skip AdminTimeline and Sweep for now)

Lets start with the following components, open to ideas on component testing frameworks / methodologies

components: Panel.js, PanelLinePlot.js, PanelRunsLinePlot.js, RunViewer.js

I know this is a big task, but as the codebase gets bigger, this is more and more important.

**Comment by vanpelt** [comment]
Also, @thekatic let's get your react-scripts plugin fix into master!

**Comment by thekatic** [comment]
@vanpelt here's a new [PR](https://github.com/wandb/client/pull/163) that will fix existing tests, and this is [the one](https://github.com/wandb/core/pull/237) that implements my update on the script.

**Comment by thekatic** [comment]
@vanpelt I've resolved that issue with PR on react-scripts.
