### ISSUE TITLE
Allow `wandb.init` to set `wandb.run.dir`.

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/client#1620]
**Problem or Use Case**
I am working with `wandb` and [`hydra`](https://hydra.cc/). Like `wandb`, `hydra` creates a new output directory unique to each run. I would like to unite my `wandb` output directory and `hydra` output directory -- for one, I would like to be able to save my `hydra` `config.yaml` to wandb.ai because it includes _all_ of the parameters (including defaults) and not just the ones that were set from the command line.

**Suggested Solution**
I think the best option would be to have separate `dir` and `base_dir` arguments for `wandb.init`.

**Comment by vanpelt** [comment]
Hey @ethanabrooks setting `dir` in wandb.init will control the `base_dir`.  You can call `wandb.save("config.yaml")` or simply write a file to `wandb.run.dir` after calling `wandb.init`.  Manually specifying the absolute directory would cause errors if init is called multiple times in the same directory.  There are low level ways to control the naming scheme of the sub directories we create, but do you think simply calling `wandb.save` or writing the file to `wandb.run.dir` will work for your usecase?

**Comment by ethanabrooks** [comment]
The `hydra` config doesn't get written to a directory of your choosing. It gets created automatically at, for example, `outputs/2020-12-16/15-50-04/.hydra/config.yaml`. This may inspire me to start an issue with `hydra` as well 😒

A program using `hydra` can programmatically access `outputs/2020-12-16/15-50-04/` as `os.getcwd()`. However, if I use `wandb.init(dir=os.getcwd())`, then `wandb.run.dir` will point to something like `outputs/2020-12-16/15-50-04/wandb/run-20201216_155005-382cmcvs/files`. 

No matter what argument I give to `wandb.save`, it will look inside `outputs/2020-12-16/17-40-20/wandb/run-20201216_174021-2e4m7het/files` because of [this line](https://github.com/wandb/client/blob/master/wandb/sdk/wandb_run.py#L870). 

A hacky solution would be to copy the config from `os.getcwd()` to `wandb.run.dir` and then call `wandb.save` but the having two separate programmatically created run-specific directories just doesn't seem like the right solution.

**Comment by vanpelt** [comment]
`wandb.save` will look in `os.getcwd()` for any files [by default](https://github.com/wandb/client/blob/master/wandb/sdk/wandb_run.py#L861).  I think you want to call `wandb.save("config.yaml", base_path=".hydra/config.yaml")` assuming `os.getcwd()` is the hydra directory in your script.

**Comment by ethanabrooks** [comment]
I wrote a minimal script that might help us discuss this:
```python
# main.py
import os

import hydra

import wandb


@hydra.main()
def app(cfg) -> None:
    wandb.init(dir=os.getcwd())
    print(wandb.save(os.path.join(os.getcwd(), "config.yaml"), base_path=".hydra/"))


if __name__ == "__main__":
    app()
```
When I run it:
```bash
❯ python main.py
wandb: Currently logged in as: ethanabrooks (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.10.12 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.11
wandb: Syncing run treasured-mountain-1
wandb: ⭐️ View project at https://wandb.ai/ethanabrooks/ppo-outputs_2020-12-16_19-58-07
wandb: 🚀 View run at https://wandb.ai/ethanabrooks/ppo-outputs_2020-12-16_19-58-07/runs/vz2c9b1h
wandb: Run data is saved locally in /Users/ethanbrooks/ppo/outputs/2020-12-16/19-58-07/wandb/run-20201216_195807-vz2c9b1h
wandb: Run `wandb offline` to turn off syncing.

Traceback (most recent call last):
  File "main.py", line 11, in app
    print(wandb.save(os.path.join(os.getcwd(), "config.yaml"), base_path=".hydra/"))
  File "/Users/ethanbrooks/miniconda3/envs/ppo/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 861, in save
    raise ValueError("globs can't walk above base_path")
ValueError: globs can't walk above base_path

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

wandb: Waiting for W&B process to finish, PID 36392
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb:
wandb: Find user logs for this run at: /Users/ethanbrooks/ppo/outputs/2020-12-16/19-58-07/wandb/run-20201216_195807-vz2c9b1h/logs/debug.log
wandb: Find internal logs for this run at: /Users/ethanbrooks/ppo/outputs/2020-12-16/19-58-07/wandb/run-20201216_195807-vz2c9b1h/logs/debug-internal.log
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb:
wandb: Synced treasured-mountain-1: https://wandb.ai/ethanabrooks/ppo-outputs_2020-12-16_19-58-07/runs/vz2c9b1h
```

**Comment by ethanabrooks** [comment]
To fix this, I had to specify the full path to the config file:
```python
import os

import hydra

import wandb


@hydra.main()
def app(cfg) -> None:
    wandb.init(dir=os.getcwd())
    print(
        wandb.save(
            os.path.join(os.getcwd(), ".hydra", "config.yaml"),
            base_path=os.path.join(os.getcwd(), ".hydra/"),
        )
    )


if __name__ == "__main__":
    app()
```
This avoids the error, but still selects the wrong files:
```bash
❯ python main.py
wandb: Currently logged in as: ethanabrooks (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.10.12 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.11
wandb: Syncing run valiant-snow-1
wandb: ⭐️ View project at https://wandb.ai/ethanabrooks/ppo-outputs_2020-12-16_20-02-56
wandb: 🚀 View run at https://wandb.ai/ethanabrooks/ppo-outputs_2020-12-16_20-02-56/runs/1wcx0h4o
wandb: Run data is saved locally in /Users/ethanbrooks/ppo/outputs/2020-12-16/20-02-56/wandb/run-20201216_200257-1wcx0h4o
wandb: Run `wandb offline` to turn off syncing.

['/Users/ethanbrooks/ppo/outputs/2020-12-16/20-02-56/wandb/run-20201216_200257-1wcx0h4o/files/config.yaml', '/Users/ethanbrooks/ppo/outputs/2020-12-16/20-02-56/wandb/run-20201216_200257-1wcx0h4o/files/config.yaml']

wandb: Waiting for W&B process to finish, PID 36699
wandb: Program ended successfully.
wandb:
wandb: Find user logs for this run at: /Users/ethanbrooks/ppo/outputs/2020-12-16/20-02-56/wandb/run-20201216_200257-1wcx0h4o/logs/debug.log
wandb: Find internal logs for this run at: /Users/ethanbrooks/ppo/outputs/2020-12-16/20-02-56/wandb/run-20201216_200257-1wcx0h4o/logs/debug-internal.log
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb:
wandb: Synced valiant-snow-1: https://wandb.ai/ethanabrooks/ppo-outputs_2020-12-16_20-02-56/runs/1wcx0h4o
```

**Comment by ariG23498** [comment]
Hey @ethanabrooks 
Do you think it would be okay to close the issue if the solution is obtained?

**Comment by ethanabrooks** [comment]
@ariG23498 the solution is not obtained. Neither of those scripts produce the desired result. The first script throws an error. The second script identifies the wrong files:
```
['/Users/ethanbrooks/ppo/outputs/2020-12-16/20-11-04/wandb/run-20201216_201104-3obr16xd/files/config.yaml', '/Users/ethanbrooks/ppo/outputs/2020-12-16/20-11-04/wandb/run-20201216_201104-3obr16xd/files/config.yaml']
```
instead of `/Users/ethanbrooks/ppo/outputs/2020-12-16/20-11-04/.hydra/config.yaml`.

**Comment by vanpelt** [comment]
Hey @ethanabrooks calling `wandb.save` on a file outside of the runs directory symlinks it into the run directory.  Those paths are the sym-linked paths.  If you look at the contents of `config.yaml` it should be hydra config.  

I'm thinking there may be another problem however.  We keep our own config.yaml file that may confuse our logic if its format changes.  The most full proof way to save the config is simply to symlink or copy the file into the run directory as a different name.

```
os.symlink(os.path.abspath(".hydra/config.yaml"), os.path.join(wandb.run.dir, "hydra-config.yaml"))
wandb.save("hydra-config.yaml")
```

**Comment by vanpelt** [comment]
If you don't call `wandb.save` we will sync the file when the run finishes.  Calling `wandb.save` tells us to upload the file immediately but it's not required.  All files in the `wandb.run.dir` are automatically synced.

**Comment by ethanabrooks** [comment]
I see. The symlink solution should work. Thank you.
