### ISSUE TITLE
Resume training and plot 

### ISSUE THREAD

**Issue by kargarisaac** [wandb/client#1622]
Hello,

I have a run that is terminated in the middle of Training and now I want to resume the training. I didn't set `resume=True` in `wandb.init()` but saved the model separately using PyTorch. IS it possible to load and resume the previous plot?

Thank you

**Comment by ariG23498** [comment]
Hey @kargarisaac 
The resuming that we offer as of now is documented here: https://docs.wandb.com/library/resuming

CC: @cvphelps for any further help on the sdk.

**Comment by vanpelt** [comment]
@kargarisaac the .wandb file is a protobuffer file that we write to from this library.  If you are feeling ambitious you could check the source code in this repo and reverse engineer it, but I don't suggest going down that path.  Using the official resuming api to add data to a run is the way to go.

**Comment by kargarisaac** [comment]
@ariG23498 @vanpelt Thank you for your answer. I think for resume, I need to set it to true. I cannot use it for my current available runs without `resume=True`, right? I used api and read data using history() for the moment to plot it using python and seaborn for example. My current run terminated after 40 hrs and I don't want to run from scratch. On the other hand I have my other runs in wandb and don't want to move everything out.

**Comment by vanpelt** [comment]
@kargarisaac to manually resume an existing run you should run `wandb.init(id="YOUR_RUN_ID", project="YOUR_PROJECT", resume="must")` then you can make calls to wandb.log that will append metrics to that run as documented here: https://docs.wandb.com/library/resuming

**Comment by kargarisaac** [comment]
@vanpelt great. Thank you for your help.

**Comment by nbortych** [comment]
But how does one get the id of the run if one hasn't set the id in the init the first time when the run was starting? Is there a way to find the id in the interface somehow?

**Comment by vanpelt** [comment]
@nbortych the run_id is available in the url of the run itself, or from the overview page.  I.E. https://wandb.ai/vanpelt/reproducibility/runs/3f87uku2/overview

You can find the run id in the last part of the "Run Path" attribute or from the url, `3f87uku2` in this case.

You can also access the id of the run programaticall in your script `wandb.run.id`

**Comment by nbortych** [comment]
Thank you for the help!
