### ISSUE TITLE
WandbCallback import error with older versions of TensorFlow and Keras

### ISSUE THREAD

**Issue by vasudev-sharma** [wandb/client#1634]
**Describe the bug**
Whenever I try to import `WandbCallback` via this line `from wandb.keras import WandbCallback`, I run into a bug; `module tensorflow has no attribute 'function'`. I'm pretty sure this bug has to do with the **tensorflow** and **keras** version as when I upgraded my tensorflow and keras to latest build, the error log given below no longer appears. Unfortunately, I can't upgrade my **Keras** and **TensorFlow** version to the latest as it breaks my project's dependencies, so I need to work with the current version of **TensorFlow** and **Keras**.

**TensorFlow version:** tensorflow==1.13.1
**Keras Version:** Keras==2.2.4
**Note:** I'm using tensorflow as backend to run my ML models

Here is the error log of it. 

```
Traceback (most recent call last):

  File "train_network.py", line 6, in <module>
    from wandb.keras import WandbCallback
  File "/home/GRAMES.POLYMTL.CA/p112473/miniconda/envs/ads_env/lib/python3.7/site-packages/wandb/keras/__init__.py", line 8, in <module>
    from wandb.integration.keras import WandbCallback  # type: ignore
  File "/home/GRAMES.POLYMTL.CA/p112473/miniconda/envs/ads_env/lib/python3.7/site-packages/wandb/integration/keras/__init__.py", line 5, in <module>
    from .keras import WandbCallback
  File "/home/GRAMES.POLYMTL.CA/p112473/miniconda/envs/ads_env/lib/python3.7/site-packages/wandb/integration/keras/keras.py", line 174, in <module>
    class _CustomOptimizer(tf.keras.optimizers.Optimizer):
  File "/home/GRAMES.POLYMTL.CA/p112473/miniconda/envs/ads_env/lib/python3.7/site-packages/wandb/integration/keras/keras.py", line 178, in _CustomOptimizer
    @tf.function
AttributeError: module 'tensorflow' has no attribute 'function'
```

**Operating System**
 - OS: macOS Mojave

**Comment by vanpelt** [comment]
@vs74 we'll fix this in a future release.  The bug was introduced in 0.10.12, so for now if you run `pip install wandb==0.10.11` it should work.  You may also be able to upgrade your tensorflow to 1.15 which will work with the latest version of our library but not require you to upgrade to tensorflow 2.0.

**Comment by vs74** [comment]
Thank you @vanpelt  for the quick turnaround. Unfortunately, I can upgrade to tensorFlow to 1.15, but will definetly try out your suggestion `(pip install wandb==0.10.11`) and will let you know if it doesn't work out.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by danzz006** [comment]
still facing the issue with wandb==0.15.2 and keras==2.10.0

**Comment by laerciop** [comment]
Hello! Also facing the same issue (wandb==0.15.5 and keras==2.13.1)
