### ISSUE TITLE
Conda-installed CLI 0.10.12 throwing TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by kengz** [wandb/client#1645]
**Describe the bug**
wandb cli is throwing `TypeError: 'module' object is not callable` when running `wandb login` and `wandb sweep sweepfile.yaml`

**To Reproduce**
1. Setup Conda environment with python 3.9.1, on Ubuntu 18.04. Install wandb 0.10.12 via conda
2. Run `wandb login` from within the conda environment

**Expected behavior**
CLI wandb should be callable.

**Screenshots**
I got the error below:
```
➜ wanbd login   
Traceback (most recent call last):
  File "/home/XX/miniconda3/envs/XXX/bin/wanbd", line 10, in <module>
    sys.exit(cli())
TypeError: 'module' object is not callable
```

**Operating System**
 - OS: Ubuntu 18.04
 - Version 0.10.12

Info on the conda release:
```
➜ conda list wan
# packages in environment at /home/XX/miniconda3/envs/XXX:
#
# Name                    Version                   Build  Channel
wandb                     0.10.12            pyhd3deb0d_0    conda-forge
```

**Additional info**:
This seems to occur only with the Conda build, which is from here https://anaconda.org/conda-forge/wandb
The pip version works as expected.

**Comment by ariG23498** [comment]
Hey @kengz 
I don't think we support package installation via conda.
I suppose after building your conda environment, you could install the `wandb` package using `pip` inside your conda env.
```
$ conda create -n env python=3.9.1
$ conda activate env
$ pip install --upgrade wandb
```

After following these steps, I think it would be possible for you to do the CLI specific tasks. :smile: 
Let me know if there is a persisting issue.

**Comment by kaiwenw** [comment]
@ariG23498 thanks, conda uninstalling and pip installing worked. 
perhaps you guys should take down https://anaconda.org/conda-forge/wandb to prevent any future accidents?
