### ISSUE TITLE
wandb sync did not successfully run 

### ISSUE THREAD

**Issue by MohammedAljahdali** [wandb/client#1647]
**Describe the bug**
I had period of bad internet connection and all of my runs would crash in wandb after few 5 - 60 min, while the run is still executing on my machine. Then I started doing my runs offline, but currently I have been trying for while to sync my offline and no run have been successfully synced. 

Last sync I got this error message:
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "c:\users\mohammed\.conda\envs\dl_env\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\mohammed\.conda\envs\dl_env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\mohammed\.conda\envs\dl_env\lib\site-packages\wandb\sdk\internal\file_stream.py", line 227, in _thread_body
    self._send(ready_chunks)
  File "c:\users\mohammed\.conda\envs\dl_env\lib\site-packages\wandb\sdk\internal\file_stream.py", line 270, in _send
    self._handle_response(
  File "c:\users\mohammed\.conda\envs\dl_env\lib\site-packages\wandb\sdk\internal\file_stream.py", line 249, in _handle_response
    raise response
  File "c:\users\mohammed\.conda\envs\dl_env\lib\site-packages\wandb\util.py", line 676, in request_with_retry
    response.raise_for_status()
  File "c:\users\mohammed\.conda\envs\dl_env\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/mohammed-aljahdali/Word%20Recognition/sgd_cnn_rnn_best_bcd_2/file_stream
done.
```
This is the message in the link:
{"error":"file sgd_cnn_rnn_best_bcd_2/file_stream not found while downloading file"}

All I need from my runs is the scalers graphs, is there a way to only upload those without the other logged information such as images?

 - Version 0.10.12

Update:
I noticed that all the tables and images got synced successfully, but the scaler values (losses, accuracy, and gradients) did not, and it get printed on the command line consistently.
Example of some of the printed values:
`92428589, 0.058621495962142944, 0.078125, 0.09762850403785706, 0.11713200807571411, 0.13663551211357117, 0.15613901615142822, 0.17564252018928528, 0.19514602422714233, 0.2146495282649994, 0.23415303230285645, 0.2536565363407135, 0.27316004037857056, 0.2926635444164276, 0.31216704845428467, 0.3316705524921417, 0.3511740565299988, 0.37067756056785583, 0.3901810646057129, 0.40968456864356995, 0.429188072681427, 0.44869157671928406, 0.4681950807571411, 0.48769858479499817, 0.5072020888328552]}, "parameters/bi_lstm.linear.weight": {"_type": "histogram", "values": [3.0, 0.0, 1.0, 1.0, 0.0, 0.0, 4.0, 4.0, 3.0, 6.0, 4.0, 12.0, 14.0, 29.0, 50.0, 72.0, 106.0, 151.0, 251.0, 374.0, 540.0, 821.0, 1122.0, 1805.0, 2917.0, 4670.0, 4908.0, 3447.0, 1929.0, 1250.0, 886.0, 604.0, 384.0, 276.0, 154.0, 131.0, 59.0, 60.0, 28.0, 19.0, 13.0, 8.0, 9.0, 4.0, 0.0, 1.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0], "bins": [-1.516934871673584, -1.4588371515274048, -1.400739312171936, -1.3426415920257568, -1.284543752670288, -1.2264460325241089, -1.1683483123779297, -1.110250473022461, -1.0521527528762817, -0.9940549731254578, -0.9359571933746338, -0.8778594732284546, -0.8197616934776306, -0.7616639137268066, -0.7035661339759827, -0.6454683542251587, -0.5873705744743347, -0.5292727947235107, -0.47117504477500916, -0.4130772650241852, -0.3549795150756836, -0.2968817353248596, -0.23878395557403564, -0.18068620562553406, -0.1225883960723877, -0.06449063122272491, -0.006392858922481537, 0.05170491337776184, 0.10980267822742462, 0.1679004430770874, 0.22599822282791138, 0.28409597277641296, 0.34219372272491455, 0.4002915024757385, 0.4583892524242401, 0.5164870023727417, 0.5745847821235657, 0.6326825618743896, 0.6907803416252136, 0.7488781213760376, 0.8069758415222168, 0.8650736212730408, 0.9231714010238647, 0.981269121170044, 1.0393669605255127, 1.097464680671692, 1.155562400817871, 1.2136602401733398, 1.2717580795288086, 1.3298557996749878, 1.3879536390304565, 1.4460513591766357, 1.5041491985321045, 1.5622469186782837, 1.620344638824463, 1.6784424781799316, 1.7365401983261108, 1.79463791847229, 1.8527357578277588, 1.910833477973938, 1.9689313173294067, 2.027029037475586, 2.0851268768310547, 2.1432244777679443, 2.201322317123413]}, "parameters/bi_lstm.linear.bias": {"_type": "histogram", "values": [3.0, 5.0, 4.0, 3.0, 5.0, 1.0, 5.0, 1.0, 0.0, 3.0, 0.0, 1.0, 2.0, 4.0, 1.0, 3.0, 2.0, 0.0, 2.0, 0.0, 0.0, 4.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], "bins": [-0.5642222166061401, -0.5119646787643433, -0.459707111120224, -0.40744954347610474, -0.35519200563430786, -0.302934467792511, -0.2506769001483917, -0.19841933250427246, -0.14616179466247559, -0.09390424191951752, -0.04164668917655945, 0.01061086356639862, 0.06286841630935669, 0.11512595415115356, 0.16738352179527283, 0.2196410894393921, 0.27189862728118896, 0.32415616512298584, 0.3764137327671051, 0.42867130041122437, 0.48092883825302124, 0.5331863760948181, 0.5854439735412598, 0.6377015113830566, 0.6899590492248535, 0.7422165870666504, 0.7944741249084473, 0.8467317223548889, 0.8989892601966858, 0.9512467980384827, 1.0035043954849243, 1.0557619333267212, 1.1080195903778076, 1.1602771282196045, 1.2125346660614014, 1.2647922039031982, 1.3170497417449951, 1.369307279586792, 1.4215649366378784, 1.4738224744796753, 1.5260800123214722, 1.578337550163269, 1.630595088005066, 1.6828526258468628, 1.7351102828979492, 1.787367820739746, 1.839625358581543, 1.8918828964233398, 1.9441404342651367, 1.9963979721069336, 2.0486555099487305, 2.1009130477905273, 2.153170585632324, 2.205428123474121, 2.257685661315918, 2.309943199157715, 2.3622007369995117, 2.4144582748413086, 2.4667158126831055, 2.5189733505249023, 2.571230888366699, 2.623488426208496, 2.675745964050293, 2.72800350189209, 2.780261278152466]}, "_step": 44199, "_runtime": 17995, "_timestamp": 1608179598}']}}}}`

**Comment by ariG23498** [comment]
Hey @MohammedAljahdali 
Could you enlist the steps that you have taken to reproduce this behaviour?
Thanks! :smile:

**Comment by MohammedAljahdali** [comment]
Do either an offline run, or interrupt the internet connection of an online run, until it becomes "crashed" on the website, then after the run ends on the machine (mostly ended manually), then try to sync the run data by using wandb sync <run dir>.

**Comment by ariG23498** [comment]
Hey @MohammedAljahdali 
I tried reproducing the issue.
Here is the code snippet and the steps that I have followed :point_down: 

## Steps
- Create a project manually in my wandb profile. This project presently should have no runs what so ever.
- Use the following code snippet to run an offline run
```python
import wandb
import os

os.environ["WANDB_BASE_URL"]="http://api.wandb.ai"

with wandb.init(entity="repro", project="offline_check", mode="offline") as run:
    for i in range(5):
        run.log({"metric":i})
```
- Upon running the above code snippet, the offline run executes. In the terminal itself, the command for online sync is presented.
```bash
wandb sync ./wandb/offline-run-20210113_103710-epvgmaj7
```
- This **successfully** updates the scalars that is provided namely `metric`

Let me know if I have missed anything while replicating the ticket. :smile:

**Comment by MohammedAljahdali** [comment]
I think another cause is that my logs are large, becuase I am also logging the gradients and the parameters. This is my wandb code
```
    wandb = WandbLogger(project='p_name', name=hparams.name, version=hparams.name, notes=hparams.notes)
    wandb.config = hparams
    wandb.log_hyperparams(hparams)
    wandb.watch(model.model, log='all')
```
Also, the size of the .wandb file in the run folder is almost 2 gb, I noticed something else that the images sync first and successfully.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
