### ISSUE TITLE
Flag WANDB_DISABLE_CODE doesn't work properly.

### ISSUE THREAD

**Issue by viyx** [wandb/client#1648]
**Describe the bug**

From [docs](https://docs.wandb.ai/library/environment-variables) we can see:

> WANDB_DISABLE_CODE
> Set this to true to prevent wandb from storing a reference to your source code

I add the flag and commitid disappear from run overview. But I still can see commit information on actions button.

**To Reproduce**

1. Go to 'run overview'
2. Click on button in upper-right corner
3. Select 'View code'
4. Select 'You can find your commit here on GitHub.'

**Expected behavior**
Send no information about source code to wandb cloud after the flag is setting.

**Operating System**
 - Linux
 - Firefox

**Additional context**
wandb, version 0.10.12

**Comment by cvphelps** [comment]
Thanks for reporting this. @ariG23498 could you please help reproduce this.

**Comment by ariG23498** [comment]
Hey @viyx could you share the repository that you were working on while you faced this issue? That would really help me trace the problem quickly :smile:

**Comment by viyx** [comment]
Hey @ariG23498, my repo is 
https://github.com/viyx/arc-nn.git -b hydra

**Comment by ariG23498** [comment]
Hey @viyx 
I tried reproducing this issue and here is what I did :point_down: 
## Steps
- Created a repository from scratch and made an initial commit with the `readme` and `.gitignore` file. [Initial commit](https://github.com/ariG23498/wandb_bug/tree/94b85dff116da5bf8282cbab8b4a5683dd82af49) 
- With this repository in hand, I created a basic `train.py` file with code to log some data in a new run.
```python
import os
import math
import random
import wandb

os.environ['WANDB_BASE_URL']='http://api.wandb.ai'
os.environ['WANDB_ENTITY']='repro'
os.environ['WANDB_PROJECT']='code-disable'
os.environ['WANDB_USERNAME']='ariG23498'
os.environ['WANDB_DISABLE_CODE']='True'

with wandb.init() as run:
    for step in range(5):
        run.log({
            "acc": math.log(.1 + random.random() + step * 0.01),
            "val_acc": math.log(.1 + random.random() + step *0.01),
            "loss": 4 - math.log(.1 + random.random() + step * 0.01),
            "val_loss": 4 - math.log(.1 + random.random() + step * 0.01),
        })
```
- Executed the `train.py` from my system. [The dashboard in wandb](https://wandb.ai/repro/code-disable)
- Went to the overview page of the run and saw that the initial commit reference was logged.
- Commited my present code in the github repository. [2nd commit with train.py](https://github.com/ariG23498/wandb_bug/tree/c4fdf1b25ec0a5f907411bfe67b738ec5767903a)
- Executed another run from system.
- Went to the overview and found that wandb was indeed referencing to the 2nd commit (which it should not).


Do you want me to add anything to this workflow? If there is something in specific that I have missed out in reproducing this bug, please let me know.

**Comment by viyx** [comment]
Hey @ariG23498, thanks for the quick response and throughout repro.

I expect from the flag that no information about the code would be sent to the server at all, since I can use a private(commercial) repo.
I believe this logic is in priority.

> Do you want me to add anything to this workflow? If there is something in specific that I have missed out in reproducing this bug, please let me know.

I think no information after the first commit and execution should be sent to the servers as well as after the second one.

**Comment by cvphelps** [comment]
Hi @viyx thanks for the clarification on expected behavior. It sounds like you want a flag that also prevents the library from capturing links to your git commit, not just a flag that prevents any code uploading to wandb servers.

**Comment by viyx** [comment]
Hi @cvphelps, I expect non capturing links to source code(no commit id, no link to repo, no any info from git).
I don't know anything about source code uploading to wandb servers(I guess this is not happen because it would be strange).

**Comment by vanpelt** [comment]
This was fixed 30 days ago, I've verified the following code indeed disables commit checks.

```
import os
import math
import random
import wandb

os.environ['WANDB_DISABLE_CODE']='true'

with wandb.init() as run:
    for step in range(5):
        run.log({
            "acc": math.log(.1 + random.random() + step * 0.01)})
```
