### ISSUE TITLE
Secondary Sorting

### ISSUE THREAD

**Issue by yanaiela** [wandb/client#1650]
**Problem or Use Case**
The sorting mechanism allow for multiple sorting fields, but I couldn't figure out the sorting logic behind it. It seems like it just picks one of the fields to sort by.

I would expect that it would function as a secondary, third, etc. sorting.
E.g. first sorting by the first field, and then within the equal values of the first field, it would sort by the second field, etc.

Was it supposed to work this way? if not, can this feature be added? It would be super useful.

**Comment by vanpelt** [comment]
Hey @yanaiela the logic should be as you described.  We sort in the order you specify, so for example:

![image](https://user-images.githubusercontent.com/17/103368020-5dcbc400-4a7b-11eb-817d-047e8cfc6d0d.png)

In the case above we first sort everything by "Created At" in descending order, then for any rows that have the same "Created At" value we sort by "decay" in descending order.

If you can share a specific case where this isn't happening for you, let me know and we can look into it.

**Comment by yanaiela** [comment]
It doesn't work in my use case.
The view I'm using have groups, so I'm looking at runs aggregates, the first column I'm sorting by is hidden from the columns, and the secondary is not. The result is that the ordering is only based on the secondary column.

**Comment by cvphelps** [comment]
Hi there, are you saying that you don't have a visible column that is one of the sorting columns? You might try making that column visible in the meantime, does that make the sorting work correctly for you?

**Comment by yanaiela** [comment]
I tried. Also when both columns are visible, it sorts by the secondary item.

**Comment by sydholl** [comment]
Hi @yanaiela, this was implemented in May 2021. Please let us know if you're still experiencing issues.
