### ISSUE TITLE
Show error for crashed runs in UI

### ISSUE THREAD

**Issue by kaiwenw** [wandb/client#1654]
**Problem or Use Case**
Often times, I'm running a dozen processes on my AWS EC2 server, and since wandb auto-restarts after failure, it's hard to locate the backtrace of the error. While there are disk logs of wandb, I'd have to match the failed run to it, which is tedious work.

**Suggested Solution**
Upload the logs, or at least the last 500 lines of it to the wandb UI.

**Comment by cvphelps** [comment]
Hi Kaiwen, thanks for the suggestion. We should have everything up until it crashes, but it depends on the type of crash honestly. If wandb doesn't have a chance to run our exit hooks, we might not be able to save the logs. The internal process is a child of the user process, so try to shut down gracefully. Could you tell me more about the nature of how your process is terminating?

**Comment by kaiwenw** [comment]
@cvphelps I'm just using a single-node GPU for training, and crashes might be due to bugs in the code (assert failures, or just RuntimeError). Which type of errors can your exit hooks handle? 

Also, is everything up until it crashes available in the UI?

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
