### ISSUE TITLE
Add button for expanding all charts in panel

### ISSUE THREAD

**Issue by hobogalaxy** [wandb/client#1659]
**Problem or Use Case**
So sometimes I have like 10 pages of charts in a panel and I would like to expand all of those pages. 
![image](https://user-images.githubusercontent.com/43458894/103484573-1d0fda00-4df0-11eb-9890-e62588b7914b.png)
However, dragging the handle in bottom right corner to expand all of them is a little inconvenient.

**Suggested Solution**
Add somewhere a small button which would expand all those pages.

**Comment by cvphelps** [comment]
Hi, it sounds like what you mean is that the section containing the individual panels is paginated, only showing 3 panels right now. Is it difficult to drag down the corner of the section to see more charts?
