### ISSUE TITLE
filter not working in sweep

### ISSUE THREAD

**Issue by kaiwenw** [wandb/client#1667]
**Describe the bug**
In this sweep: https://wandb.ai/kaiwenw/CartPole-v0/sweeps/1wkxr4hg?workspace=user-kaiwenw
I'm trying to filter by `w_net_config...explicitly_normalize_to_one` to be false or true. 
But the UI only shows "null" and when I type false or true, it does not apply the filter.

However, if you look at individual runs, the params are clearly false or true.

**Comment by tyomhak** [comment]
Hey @kaiwenw , thanks for reporting. I'm taking a look.

**Comment by tyomhak** [comment]
yep, that seems to be a bug. I'm filing an internal ticket to fix this.

**Comment by kaiwenw** [comment]
@tyomhak  cool thanks! in the meantime is there a workaround?

**Comment by tyomhak** [comment]
Hey @kaiwenw , sorry for the late response. Not that I'm aware of. btw right now it seems like there are runs that are successfully getting filtered — did you change the way you log this parameter?

**Comment by kaiwenw** [comment]
I did not change anything I think; but glad the UI is working now!
