### ISSUE TITLE
The Wandb CLI does not let you override its default location for storing credentials and other configuration details

### ISSUE THREAD

**Issue by amorehead** [wandb/client#1669]
**Problem or Use Case**
The Wandb CLI does not let you use its API to override its default location for storing credentials and other configuration details (i.e. ~/.config/wandb).

**Suggested Solution**
Add a new parameter to the Wandb CLI API's login() function (or possibly init() function) that lets users of the API dictate where they would like Wandb to store their credentials and other login info (i.e. in which directory to store the 'wandb' config directory).

**Additional context**
The reason I am making this feature request is that I have not been able to use Wandb on a high-performance computing (HPC) cluster because the default directory Wandb stores its credential files (i.e. ~/.config/wandb) is mandatorily read-only, that is, ~/ is read-only, and the Wandb CLI performs a call to the os.make_dir() function which is, of course, not permitted by the underlying filesystem.

Thank you in advance for your time!

**Comment by vanpelt** [comment]
@amorehead I haven't tried this but I believe you can do this by setting the `WANDB_CONFIG_DIR` environment variable.

**Comment by amorehead** [comment]
@vanpelt,

Thank you for the helpful redirection! After looking through Wandb's documentation for a while, I haven't been able to find an example of how I might declare my api_key and config_dir in a settings/config file so I do not have to execute the commands "export WANDB_API_KEY=..." and "export WANDB_CONFIG_DIR=..." in every environment I am running my script in.

**Comment by vanpelt** [comment]
Ahh, currently that's not supported.  We only support reading your api key from a `.netrc` file in the home directory of the current user.   The simplest solution for you would be to add the following to your code, but you should never checkin api keys to source control as a matter of general best practice.

```
import os

with open("wandb.env") as f:
   for line in f:
        key, val = line.strip().split("=", 1)
        os.environ[key] = val
```

And then create a file that looks like:

```
WANDB_CONFIG_DIR=.
WANDB_API_KEY=...
```

The other alternative is to add "export WANDB_API_KEY=..." to your `~/.bash_rc` or relavant init script.  Also, if you're running in docker you can use `wandb docker-run mycontainer:latest` and it will pass the API key on the host machine (set by calling `wandb login`) automatically into the container for you.

**Comment by amorehead** [comment]
Thank you for the great suggestions. I'll look into both of them and go from there!

**Comment by amorehead** [comment]
@vanpelt,

Do you have any ideas as to why the WANDB_CONFIG_DIR=. command is not overriding the default config dir (i.e. ~/.wandb)?

**Comment by vanpelt** [comment]
Ahh, @amorehead the error you're seeing is for the wandb artifact cache directory.  You can set that path with `export WANDB_CACHE_DIR=/...`.  We clearly need to consolidate these environment variables and make it easier to handle these cases.  Also, we should just fall back to the system temp directory in this case.
