### ISSUE TITLE
Run comparer: Can't scroll down on Firefox

### ISSUE THREAD

**Issue by zimmer-m** [wandb/client#1673]
On Ubuntu 20.04 and Firefox 84.0.1. I experience that I cannot scroll-down in the Run-Comparer, as the following GIF shows. 

![scroll](https://user-images.githubusercontent.com/66726489/103892672-3e244380-50ec-11eb-9fce-6fa68efada4e.gif)

The thing is, it works great on Google Chrome. I know that this Bug report should be rather directed at Firefox then, but I figured it would still be good to ask whether this has anything to do with the Wandb website or whether there are users experiencing similar behaviour (which might have solutions to it).

Thanks!

**Comment by cvphelps** [comment]
hi @zimmer-m thanks for reporting this! What a bummer, I'm sorry to hear it's not working in Firefow.

**Comment by ariG23498** [comment]
Hey @zimmer-m 
Could you check with the problem? I think this might have been mitigated by now!

**Comment by zimmer-m** [comment]
> Hey @zimmer-m
> Could you check with the problem? I think this might have been mitigated by now!

Hey @ariG23498, seems to be fixed, thanks!
