### ISSUE TITLE
logger noise that should be debug, and not being able to turn wandb logging off

### ISSUE THREAD

**Issue by stas00** [wandb/client#1676]
Just rebased transformers, needed to update `wandb` and started getting this when running hf trainer:
```
2021-01-07 18:46:19 | INFO | wandb.sdk.internal.internal | Internal process exited
2021-01-07 18:46:19 | INFO | wandb.sdk.internal.internal | Internal process exited
```
1. why is this info and not debug? I can't see what useful information this adds to the user of the hosting application. Turning this to DEBUG would be awesome. thanks.

2. `export WANDB_CONSOLE=off` didn't shut it off the docs suggest https://docs.wandb.ai/library/environment-variables

3. Would it be possible to add:

`WANDB=DISABLED` env var or something like that similar to how `COMET_MODE=DISABLED` does it? which would mean don't load the module at all even if it's available and API KEY is configured.

When I work on something it makes things difficult when modules that don't participate in the development process start logging their stuff. I don't use wandb most of the time, but the fact that I have it installed keeps on running it.

Thank you very much.

For now going to uninstall wandb

**Comment by stas00** [comment]
I also found a related https://github.com/wandb/client/issues/764 tried `export WANDB_MODE=off` - no difference - still getting the above log. (and those new additions aren't documented at https://docs.wandb.ai/library/environment-variables the entry is there but it doesn't say how to turn it off.

**Comment by vanpelt** [comment]
Hey @stas00 you can set `WANDB_MODE=disabled` see, https://github.com/huggingface/transformers/blob/master/src/transformers/integrations.py#L54

Those log statements should be getting written to a separate log file in `wandb/debug-internal.log`.  Do you have a custom logging setup?  Can you share a simple code snippet that reproduces this?

**Comment by stas00** [comment]
It's not working :( still gets logged.

This is just using a staple `examples/seq2seq/finetune_trainer.py`, nothing custom. 

```
cd examples/seq2seq
export BS=20; rm -r output_dir; CUDA_VISIBLE_DEVICES=0,1 PYTHONPATH=../../src USE_TF=0   ./finetune_trainer.py --model_name_or_path t5-small --output_dir output_dir --adam_eps 1e-06 --data_dir wmt_en_ro --do_eval --do_predict --do_train --evaluation_strategy=steps --freeze_embeds --label_smoothing 0.1 --learning_rate 3e-5 --logging_first_step --logging_steps 1000 --max_source_length 128 --max_target_length 128 --num_train_epochs 1 --overwrite_output_dir --per_device_eval_batch_size $BS --per_device_train_batch_size $BS --predict_with_generate --eval_steps 25000  --sortish_sampler --task translation_en_to_ro --test_max_target_length 128 --val_max_target_length 128 --warmup_steps 5 --n_train 100 --n_val 100 --n_test 100  --fp16 --save_steps 1
```
end of stderr:
```
2021-01-07 19:29:38 | INFO | __main__ | ***** test metrics *****
2021-01-07 19:29:38 | INFO | __main__ |   test_bleu = 27.7112
2021-01-07 19:29:38 | INFO | __main__ |   test_gen_len = 41.4
2021-01-07 19:29:38 | INFO | __main__ |   test_loss = inf
2021-01-07 19:29:38 | INFO | __main__ |   test_n_objs = 100
2021-01-07 19:29:38 | INFO | __main__ |   test_runtime = 4.5391
2021-01-07 19:29:38 | INFO | __main__ |   test_samples_per_second = 22.031
2021-01-07 19:29:38 | INFO | wandb.sdk.internal.internal | Internal process exited
```

**Comment by vanpelt** [comment]
Sorry, I misspoke.  It's `WANDB_DISABLED=true`, I should have read the code that I linked to 🙃

**Comment by vanpelt** [comment]
The docs are here: https://docs.wandb.ai/integrations/huggingface#examples

I'm still really curious how this is getting mixed in with your logs.  Can you share a repository with me so I can try to reproduce?

**Comment by stas00** [comment]
oh, I was looking in the normal wandb docs, the HF-specific workaround worked - thank you!

It's happening on `transformers` master which you can reproduce with:

```
git clone https://github.com/huggingface/transformers/
cd transformers/
cd examples/seq2seq
wget https://cdn-datasets.huggingface.co/translation/wmt_en_ro.tar.gz
tar -xzvf wmt_en_ro.tar.gz
export BS=20; rm -r output_dir; CUDA_VISIBLE_DEVICES=0,1 PYTHONPATH=../../src USE_TF=0   ./finetune_trainer.py --model_name_or_path t5-small --output_dir output_dir --adam_eps 1e-06 --data_dir wmt_en_ro --do_eval --do_predict --do_train --evaluation_strategy=steps --freeze_embeds --label_smoothing 0.1 --learning_rate 3e-5 --logging_first_step --logging_steps 1000 --max_source_length 128 --max_target_length 128 --num_train_epochs 1 --overwrite_output_dir --per_device_eval_batch_size $BS --per_device_train_batch_size $BS --predict_with_generate --eval_steps 25000  --sortish_sampler --task translation_en_to_ro --test_max_target_length 128 --val_max_target_length 128 --warmup_steps 5 --n_train 1 --n_val 1 --n_test 1  --fp16 --save_steps 1
```

**Comment by tssweeney** [comment]
Hey folks - just following up here to ensure we are not leaking logs and cannot seem to get a repro. Tried all 6 permutations which might be applicable:
```
export WANDB_MODE="disabled"; export WANDB_DISABLED=true; export BS=20; rm -r output_dir; USE_TF=0   ./finetune_trainer.py ...
export WANDB_MODE="dryrun"; export WANDB_DISABLED=true; export BS=20; rm -r output_dir; USE_TF=0   ./finetune_trainer.py ...
export WANDB_MODE="online"; export WANDB_DISABLED=true; export BS=20; rm -r output_dir; USE_TF=0   ./finetune_trainer.py ...
export WANDB_MODE="disabled"; unset WANDB_DISABLED; export BS=20; rm -r output_dir; USE_TF=0   ./finetune_trainer.py ...
export WANDB_MODE="dryrun"; unset WANDB_DISABLED; export BS=20; rm -r output_dir; USE_TF=0   ./finetune_trainer.py ...
export WANDB_MODE="online"; unset WANDB_DISABLED; export BS=20; rm -r output_dir; USE_TF=0   ./finetune_trainer.py ...
```

And none of these produce the leaked log. If this shows up again, I'll be happy to jump on it!

**Comment by stas00** [comment]
It was probably fixed by:
https://github.com/huggingface/transformers/commit/1c19b423bf274a465f95725a79819bf82f71329e
With the current master this one odd log line doesn't appear anymore. Instead I get a huge dump of wandb information.

**Comment by tssweeney** [comment]
Awesome - thank you for that tip. I can confirm that before the change, the `internal process exited` log would be emitted. After the change, wand's normal output can be observed.
