### ISSUE TITLE
Standard testing methodology

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#168]
Saw this was trending recently:

https://github.com/kentcdodds/react-testing-library

@thekatic Can you take a look and see if this is something that would make our testing better?  I'll leave it up to you.

**Comment by thekatic** [comment]
It's as they stated lightweight alternative to enzyme. More like all-in-one simple tool as an alternative to our enzyme-chai-sinon stack. But I don't see significant value in switching to this library.

I'm stumbling upon a lot of examples using our stack, as a good methodology for testing React project.
Also jest over mocha, based on a performance.

But I will definitely watch on this tool.

**Comment by thekatic** [comment]
@shawnlewis, I saw you got rid of chai for unit tests.
I can agree it's unnecessary to use one more package just for readability, as my initial intention.

Did you saw it as a potential performance decrease, as we add more and more tests, or you want to keep number of packages as low as possible?

**Comment by shawnlewis** [comment]
Hey Vlad, sorry I meant to email you about that. It's just a personal
preference... I really don't like the 'to.be.a(whatever)' notation. The
dots are meaningless and in my opinion an abuse of the language.

In general, please feel free to use packages that are helpful!
