### ISSUE TITLE
Not logging the None values in the wandb

### ISSUE THREAD

**Issue by pandorica-opens** [wandb/client#1683]
`None` values in 
```python 
wandb.config
``` 
are not showing in the comparison table.

To reproduce, simply set any parameter (i.e. max_iter) 
```python
wandb.config.max_iter = None
``` 
and try to find the column max_iter in the comparison table at:

`wandb.ai/username/projectname/table?workspace=user-username`,

where *username* is the login name and *projectname* is the name of the project that you're currently in.

I would expect the `None` values still to get logged, i.e. to know the expected behavior of the estimator in *sklearn* as some of the parameters during training are `None`.

**Comment by ariG23498** [comment]
Hey @pandorica-opens 
I tried reproducing the ticket, these are the steps that I have taken :point_down: 

## Steps
- Executing the code to log some metrics
```python
import wandb
import math
import random

config={
  "learning_rate": 0.01 + 0.1 * random.random(),
  "batch_size": 8 * 10 * random.random(),
  "momentum": 0.1 + random.random(),
  "layer_1_size": 0.02 * random.random(),
  "layer_2_size": 0.03 * random.random(),
  "max_iter":None,
}

with wandb.init(project="config_none",entity="repro",config=config) as run:
  config = run.config

  for step in range(5):
    run.log({
        "acc": math.log(.1 + random.random() + step * 0.01 + config.learning_rate + config.layer_1_size) + config.momentum * 0.1,
        "val_acc": math.log(.1 + random.random() + step *0.01 + config.learning_rate + config.layer_1_size)+ config.batch_size * 0.001,
        "loss": 4 - math.log(.1 + random.random() + step * 0.01 + config.learning_rate + config.layer_2_size) + config.momentum * 0.1,
        "val_loss": 4 - math.log(.1 + random.random() + step * 0.01 + config.learning_rate + config.layer_2_size) - config.momentum * 0.1,
    })
```
> Note: The `config` is the cofiguration for the particular run.
- Go to the overview page of wandb
![image](https://user-images.githubusercontent.com/36856589/104145311-78435d00-53ec-11eb-8fef-4f62bfff3ced.png)

The `max_iter` key that had `None`did get logged in the overview of the dashboard.

Let me know if I have missed out on something while reproducing the issue.

**Comment by pandorica-opens** [comment]
Hey @ariG23498 I have taken the same steps and it indeed works, so max_iter is shown at the overview of the run as (-) at i.e. `https://wandb.ai/s6hakond/config_none/runs/14poojtn/overview` - I made this project public so you can use the link as it is. However, max_iter is still absent from the table with all runs (i.e. at https://wandb.ai/s6hakond/config_none/table?workspace=user-s6hakond) max_iter parameter is not present.

**Comment by vanpelt** [comment]
@pandorica-opens this is operating as intended.  It should become visible once any of your runs actually have a value in `max_iter`.

**Comment by pandorica-opens** [comment]
it was a bit confusing for me, but thanks for helping :)
