### ISSUE TITLE
Problem with model logging to artifacts

### ISSUE THREAD

**Issue by freefeynman123** [wandb/client#1695]
**Describe the bug**
When logging model artifact saved in .pth ot .h5 format, I encountered the following issue:

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpao5hgvia'
Exception ignored in: <finalize object at 0x7f21769a2bf0; dead>
Traceback (most recent call last):
Exception ignored in: <finalize object at 0x7f21769a2bf0; dead>
Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
Exception ignored in: <finalize object at 0x7f21769a2bf0; dead>
Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.6/tempfile.py", line 938, in _cleanup
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.6/tempfile.py", line 938, in _cleanup
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    _rmtree(name)
  File "/usr/lib/python3.6/shutil.py", line 477, in rmtree
    _rmtree(name)
  File "/usr/lib/python3.6/shutil.py", line 477, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 475, in rmtree
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.6/tempfile.py", line 938, in _cleanup
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 475, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpao5hgvia'
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpao5hgvia'
    _rmtree(name)
  File "/usr/lib/python3.6/shutil.py", line 477, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 475, in rmtree
Exception ignored in: <finalize object at 0x7f21769a2bf0; dead>
Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpao5hgvia'
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.6/tempfile.py", line 938, in _cleanup
    _rmtree(name)
  File "/usr/lib/python3.6/shutil.py", line 477, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 475, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpao5hgvia'
```

After all the model is saved in artifacts and seems to work fine, however it may be corrupted in some way and the log looks just terrible.

**To Reproduce**
```
id = wandb.util.generate_id()        
run_train = wandb.init(project=args.project_name, id=id, resume="allow", job_type='train')
torch.save(dict(params=model.state_dict()), os.path.join(args.save_path, name + '.h5'))
artifact = wandb.Artifact(type='model', name=args.model_type)
artifact.add_file(os.path.join(args.save_path, name + '.h5'))
run_train.log_artifact(artifact)
```

**Expected behavior**
No error in log

**Operating System**
 - OS: Ubuntu (running on k8s cluster with nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04 base image)
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

Edit: After downgrading to version 0.9.5 of wandb everything seems to work fine.

**Comment by tssweeney** [comment]
Hello - thanks for the report and repro steps. On my machine I am not getting the same error. A few questions: 
1. where are you seeing the error logs - in stdout or in one of the debug logs?
2. Can you share the script that produces the model leading up?
3. Which line is causing the error? is it in fact `run_train.log_artifact(artifact)`?

**Comment by freefeynman123** [comment]
You can check the code from here https://github.com/freefeynman123/ifsl/blob/develop/MTL/models/mtl.py, especially for `MtlLearner`, is seems like the `run_train.log_artifact(artifact)` is causing the problem.

**Comment by cvphelps** [comment]
Thanks, it appears this might be an issue with the particular setup you have. @ariG23498 could you please try to repro this one when you get a chance

**Comment by freefeynman123** [comment]
I was working with Docker image based on nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04 which comes with Python 3.6.9, after installing Python 3.8.7 and launching training with it the error disappared, so I changed my base image to  nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04 and the error is gone. Thank you for your time, it was my setup after all.

**Comment by AdvCh** [comment]
Hi, I met the same problem when I used wandb in pytroch-lightning, so it because of the version of python or cuda? I don't use docker but just a conda environment.
