### ISSUE TITLE
Problem with wandb run sync

### ISSUE THREAD

**Issue by TusharNimbhorkar** [wandb/client#1696]
**Describe the bug**
The wandb run folder is not syncing. And seems to have gotten stuck(Waiting for some process to finish). 
Other problem also includes the tensorboardX run is not syncing at the end of each epoch(run). So basically there is nothing on wandb.ai

**Screenshots**
![image](https://user-images.githubusercontent.com/6749360/104389542-78417b00-551a-11eb-8b65-43abfd42b0f1.png)

**Operating System**
 - OS: Ubuntu 16.04
 
**version**
wandb==0.10.13
tensorboard==2.4.0
tensorboardX==2.1
**Additional context**

If I downgrade wandb to 0.9.5 everything works. 

**logs**

[debug.log](https://github.com/wandb/client/files/5805581/debug.log)
[debug-internal.log](https://github.com/wandb/client/files/5805583/debug-internal.log)

**Comment by ariG23498** [comment]
Hey @TusharNimbhorkar 
I am sorry for the delay. Could you also share some code snippet that could help me reproduce the issue with the latest version of wandb?
Thanks :smile:

**Comment by ariG23498** [comment]
Hey @TusharNimbhorkar 
I am closing this issue as the TB syncing is working and the issue #1782 has also been closed. Let me know if the issue persists.
