### ISSUE TITLE
wandb error when no .wandb should exit

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#17]
Log:
```bash
shawn@wbeast:~/code/gaze$ CUDA_VISIBLE_DEVICES=0 python train.py --env=wandb --max_epochs=2 ~/data/gaze/prep-ds-office-shawn-2-0.h5 ~/data/gaze/prep-ds-office-shawn-1-0.h5
Using TensorFlow backend.
WARNING:root:Unable to persist config, no .wandb directory exists.  Run `wandb config init` in this directory.
!!! Fatal W&B Error: '_model'
ERROR:wandb.sync:Traceback (most recent call last):

  File "/home/shawn/.local/lib/python2.7/site-packages/wandb/sync.py", line 87, in watch
    config=self.config.__dict__, description=self._description)

  File "/home/shawn/.local/lib/python2.7/site-packages/wandb/api.py", line 64, in wrapper
    raise Error(message)

Error: '_model'

('face_train shape: ', (2835, 260, 260, 3))
('masks_train shape:', (2835, 36, 64))
('y_train shape: ', (2835, 2))
('face_val shape: ', (119, 260, 260, 3))
('mask_val shape:', (119, 36, 64))
('y_val shape: ', (119, 2))
('model output_shape: ', (None, 2))
Train on 2835 samples, validate on 119 samples
Epoch 1/2
2017-09-06 09:36:49.221831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:06:00.0
Total memory: 10.91GiB
Free memory: 10.76GiB
2017-09-06 09:36:49.221857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2017-09-06 09:36:49.221863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2017-09-06 09:36:49.221873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0)
```

**Comment by vanpelt** [comment]
I'm thinking if no `.wandb` directory exists we create a temporary staging directory in `/tmp` to stage our files for the run.  The directory will likely be a hash of the current working directory so it can be re-used on future runs.  I'll make the script blowup if there is no API key or project configured in the environment.  Does this make sense @shawnlewis?

**Comment by shawnlewis** [comment]
This happened because I scp'd my code to a new machine and forgot to run wandb init. So blowing up because you don't detect API-key/project makes sense.

What's the case where there is no .wandb directory, but there is an API-key / project configured? Depending on the answer, it might be better to just blow up all the time if there's no .wandb dir.

I think we need to support two modes:
1) interactive: where the user has a terminal, can see the output etc
2) automated: user is scripting wandb runs on other machines / containers. Is the right thing in this case to have the .wandb directory checked in, and then "git pull"? Their script would still need to copy the API-key.

I'll play with some remote scripting stuff within the next few days to get an idea of how it would work.

**Comment by vanpelt** [comment]
I'm thinking in case number 2 it just uses a temp directory to stage files, or maybe the home directory?  We would likely want to support multiple instances running on the same machine so would need a namespace.  Maybe we just always stage files in ~/.config/wandb and manage the cleanup of old runs...

**Comment by shawnlewis** [comment]
I don't think they should be in .config, they're not config files so that's confusing. The three options that make sense to me are ~/.wandb/<run-root-hash>/run-<id>-tmp or <run-root>/.wandb/run-<id>-tmp. Or finally, if they're truly temporary files, they should probably go in /tmp

Relatedly, I think we should stop using ~/.netrc and start using ~/.wandb/api-key or something like that. What does .netrc get us?

**Comment by vanpelt** [comment]
It's just a standard.  Heroku uses it.  Google cloud uses `~/.config/gcloud`, yarn uses `~/.config/yarn` etc.  If you don't like ~/.netrc I say we use `~/.config/wandb/credentials`

**Comment by shawnlewis** [comment]
How about leave it since it's the only thing we stick in ~ right now, but if we end up creating a or ~/.config/wandb ~/.wandb directory we put it in there (I prefer ~/.wandb since it's easier to type and find, but that's just personal)

**Comment by vanpelt** [comment]
I'm now more inclined to just create a `wandb` directory in the working directory if it's not there as long as we have an API key, entity, and project in the environment.  If we can't create the directory we blowup.  The wandb dir would likely look like:

- wandb
   - .gitignore (likely only track config, maybe default-config.yaml)
   - config (optional configuration for the cli / api, tracked by git)
   - default-config.yaml (or default-params.yaml?  This is where the wandb config set stuff goes, likely tracked by git could be stored in wandb)
   - restored-config.yaml (this is where we restore previous runs parameters to, not tracked by git)
   - runs (not tracked by git)
      - runs.sqlite (a database tracking run states and age etc, could just be json in each dir...).
      - abc123
          - debug.log (debug logs from the module)
          - run.log (the stdout from the run)
          - diff.patch (the diff if any uncommited changes)
          - description.md (optional description)
          - config.yaml (the configuration parameters used in the run)
          - files (made easy to write to with helpers, all files tracked and synced with the cloud)
              - ** files from the run

**Comment by shawnlewis** [comment]
Looks pretty good! A few notes:

- I like json in each dir more than runs.sqlite (it's nice if everything here is user inspectable, non-binary)
- The user has to go pretty deep to get to their run files. If that's an issue we could have a wandb/last-run symlink, or a wandb-last-run-files symlink or something.
- OR abc123 IS the run files directory, but certain files are special and generated by us. All are synced to the server. I like this approach because it's highly inspectable on the server/browser side as well. The user needs to not re-use any of those file names, but I don't think that's a very big ask.
- run.log should be called stdout.log, I'm going to create a stderr.log as well that we can merge when rendering (they'll each be microsecond timestamped by the client)

**Comment by vanpelt** [comment]
Nice, I'm with you on the `json` and stdout/err.log.  What if we throw all of the wandb specific shit into it's own sub dir, something like `.meta` or `.var`.  I'm also liking the auto incrementing int, so it could look like:

- wandb/run-123/.meta/run.json
- wandb/run-123/weights.h5

**Comment by shawnlewis** [comment]
We've implemented a lot of the stuff discussed in this issue. And things work better when there is no .wandb or wandb dir now. #43 may still be an issue but we'll track it there.
