### ISSUE TITLE
Artifacts: Easy feature to capture all the code and certain extra files every time the model trains

### ISSUE THREAD

**Issue by suarezjessie** [wandb/client#1714]
This isn't really a bug I think but is there a way to save other files being called by `train.py` file? For example, I'd also like to track `model.py` or `dataset.py` whenever I run an experiment.

**Comment by ariG23498** [comment]
Hey @suarezjessie 
Going by the [documentation](https://docs.wandb.ai/ref/init#init), `save_code` will only save the entrypoint which is the `train.py`. To save the other files as well, I would suggest you to look into `Artifacts` that we provide as a tool. With astifacts you can not only save code but also save entire models and much more and version them according to your own experiments. :smile: 

Link for artifacts: https://wandb.ai/site/artifacts
