### ISSUE TITLE
Cannot download large artifact completely

### ISSUE THREAD

**Issue by sobir-git** [wandb/client#1716]
I am logging a large pickle file (572 mb) as an artifact. It shows well on the dashboard.. However when I try to use it in another script with `artifact.download()`, it downloads but I am not able to unpickle it. Raises the following exception: 
```
UnpicklingError: pickle data was truncated
```
And then I check the downloaded artifact file size in the `artifacts` local folder, it is smaller than the original (294 mb). I tried to download it manually from the web interface, still it has smaller size (353mb) and same error when unpickling.

**Comment by blizda** [comment]
Same isssu reprodusing by me. I log large artifact(1,2GB) pytorch file, but wen i trying download it - artifact don't loading complitly. This issue reprodusing with all wandb versions sinse 0.10.3 to 0.10.14

example code for reprodusing
```
import wandb

def get_model_from_w_b_without_run(artifact_name='T5_model_tasks:latest'):
    api = wandb.Api()
    artifact = api.artifact('blizd/mt-t5-ria-news/'+artifact_name, type='model')
    return artifact.download()

path = get_model_from_w_b_without_run()
```

**Comment by annirudh** [comment]
Thanks for the steps to reproduce the issue. I do see that for large files, the download drops before the full file is finished downloading. The files are fully intact on our side, but our server is failing to fully transmit them. We'll push a fix.

**Comment by annirudh** [comment]
Hi @sobir-git and @blizda, just wanted to let you know that we just deployed a fix for this issue. Larger files should properly download from both the web UI and the client.

Apologies for the trouble this issue caused! Please follow up on this thread if you are still encountering download issues.
