### ISSUE TITLE
detectron2 and wandb

### ISSUE THREAD

**Issue by rleonard1224** [wandb/client#1720]
**Describe the bug**
I'm having trouble getting weights and biases to write out the results of a detectron2 training session run from a google colab notebook.

**To Reproduce**
The block of code I was using to have detectron2 write out to weights and biases is: 

##################################################################################################
%pip install wandb
wandb.login()
wandb.init(project=project-name, sync_tensorboard=True)

cfg = get_cfg()
cfg.merge_from_file(
    model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
)
cfg.DATASETS.TRAIN = ("train",)
cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = (
    300
)  # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (
    128
)  # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 5  # 5 classes (tank, support_vehicle, trailer, other_afv, non_afv)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
##################################################################################################

and the error message I'm getting is:

##################################################################################################
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.6/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/dataset_mapper.py", line 186, in __call__
    dataset_dict["instances"] = utils.filter_empty_instances(instances)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/detection_utils.py", line 481, in filter_empty_instances
    return instances[m]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/instances.py", line 139, in __getitem__
    ret.set(k, v[item])
  File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/masks.py", line 345, in __getitem__
    item = item.nonzero().squeeze(1).cpu().numpy().tolist()
  File "/usr/lib/python3.6/warnings.py", line 101, in _showwarnmsg
    _showwarnmsg_impl(msg)
  File "/usr/lib/python3.6/warnings.py", line 30, in _showwarnmsg_impl
    file.write(text)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 92, in new_write
    cb(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 664, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 151, in publish_output
    self._publish_output(o)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 156, in _publish_output
    self._publish(rec)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 454, in _publish
    if self._process and not self._process.is_alive():
  File "/usr/lib/python3.6/multiprocessing/process.py", line 134, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
##################################################################################################

**Expected behavior**
I was expecting the tensorboard metrics from the detectron2 training session to be written out to weights and biases.

**Desktop:**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: Google Chrome

**Comment by ariG23498** [comment]
Hey @rleonard1224 could you link us to your `colab` notebook? This way we would be able to repo the ticket ASAP. It would be even better if you could add the wandb dashboard along with the colab notebook. :smile:

**Comment by rleonard1224** [comment]
Hi.  Thanks for your message.  For my wandb dashboard, when I click on a run and look in the charts tab I get the message 'No metrics logged yet.'  A version of my notebook is posted below:

###########################################################################################
Install Python Packages
# install dependencies: 
!pip install pyyaml==5.1
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())
!gcc --version
# opencv is pre-installed on colab
# install detectron2: (Colab has CUDA 10.1 + torch 1.7)
# See https://detectron2.readthedocs.io/tutorials/install.html for instructions
import torch
assert torch.__version__.startswith("1.7")
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html
# exit(0)  # After installation, you need to "restart runtime" in Colab. This line can also restart runtime
Import Python Packages
import detectron2
from detectron2.utils.logger import setup_logger
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.data.datasets import register_coco_instances
from detectron2.utils.visualizer import Visualizer
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2.utils.visualizer import ColorMode
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
from google.colab.patches import cv2_imshow
import random, cv2, os
Define Data Directories
# Download data from google drive
# Data Directories
traindir = 'path-to-training-set'
testdir = 'path-to-testing-set'
Register Datasets
# Register train and test datasets
register_coco_instances("train", {}, traindir + 'coco.json', traindir + 'images/')
register_coco_instances("test", {}, testdir + 'coco.json', testdir + 'images/')
​
# Generate metadata
train_metadata = MetadataCatalog.get("train")
test_metadata = MetadataCatalog.get("test")
print(train_metadata)
print(test_metadata)
​
​
# Get train and test dataset catalogs
train_dicts = DatasetCatalog.get("train")
test_dicts = DatasetCatalog.get("test")
Display Training Annotations
# Display a random training image with annotations
d = random.sample(train_dicts, 1)
d = d[0]
img = cv2.imread(d["file_name"])
visualizer = Visualizer(img[:, :, ::-1], metadata=train_metadata, scale=1.0)
vis = visualizer.draw_dataset_dict(d)
print("filename = " + d['file_name'])
cv2_imshow(vis.get_image()[:, :, ::-1])
Setup wandb
%pip install wandb
import wandb
wandb.login()
wandb.init(project='project-name', sync_tensorboard=True)
Train
# Train the network
cfg = get_cfg()
cfg.merge_from_file(
    model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
)
cfg.DATASETS.TRAIN = ("train",)
cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = (
    300
)  # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (
    128
)  # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 5  # 5 classes (tank, support_vehicle, trailer, other_afv, non_afv)
​
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
###########################################################################################

**Comment by rleonard1224** [comment]
Hi.  Thanks for your message.  This [link](https://dadoes-my.sharepoint.com/:f:/g/personal/rick_rendered_ai/EtuBuWyynVVAkAo0L1qS5boBx9bsk-XWms0fUQx9xtMWYQ?e=UKiTp1) contains a version of the colab notebook that is generating the error message I posted above.  This link also contains the dataset that can be used to run the colab notebook.

**Comment by rleonard1224** [comment]
Hi @jsbroks.  Thanks for your message.  So far I haven't been able to find a fix, but the link I posted in my last message contains a sample notebook and dataset which reproduces the error I'm getting.

**Comment by jsbroks** [comment]
@rleonard1224 Thanks for the response. I am getting the same error :(. I'll look into it and see what I can find.

**Comment by rleonard1224** [comment]
Thanks so much @jsbroks.

**Comment by jsbroks** [comment]
If you pass `settings=wandb.Settings(start_method="thread")` into the `init` it now shows `Exception: The wandb backend process has shutdown`.

**Comment by vanpelt** [comment]
Hey guys, I'm looking into this now with the code and data from @rleonard1224.  I'll report back on what I find.

**Comment by vanpelt** [comment]
Unfortunately I wasn't able to reproduce.  Colab upgraded their CUDA to 11 and torch to 1.8, detectron only supports torch 1.7 on CUDA 11 🙃 

If either of you can provide me with an updated colab that would be really helpful.  In the meantime @jsbroks it looks like the error you're seeing is from streaming content.  Can you try adding the following to your `wandb.init` call?

```
settings=wandb.Settings(start_method="thread", console="off")
```

**Comment by jsbroks** [comment]
I was able to get it working by installing 1.7 directly:

```py
# install dependencies
!pip install pyyaml==5.1
!pip install torch==1.7
!pip install torchvision==0.8.1 
 
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())

assert torch.__version__.startswith("1.7")
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html
# After installation, you need to "restart runtime" in Colab
```

But... thanks to @vanpelt suggestion I was able to get it working as follows:

```py
wandb.init(sync_tensorboard=True,
           settings=wandb.Settings(start_method="thread", console="off"))
```
@rleonard1224 check to see if this will fix it for you

**Comment by rleonard1224** [comment]
Hi @jsbroks, @vanpelt .  I'll give this a try and report back.  Thanks so much for your help.  I really appreciate it.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by XBeg9** [comment]
I still can't get metrics for detectron2, using 
```python
wandb.init(sync_tensorboard=True,
           settings=wandb.Settings(start_method="thread", console="off"))
```

Is someone can share the actual colab that does work? Thanks

**Comment by aidanjdonohue** [comment]
Hi @XBeg9 did you do all the steps that @jsbroks outlined in his last post?
