### ISSUE TITLE
[Feature] How to delete an user?

### ISSUE THREAD

**Issue by HaoLiuHust** [wandb/client#1733]
Is there a way to delete an user?

**Comment by cvphelps** [comment]
Hi there, are you trying to delete a user from a team? You can remove them from the team settings page. If you go to your team page and look in the left sidebar, you'll see a small gear icon with a "Team settings" link.

**Comment by khalilRhouma** [comment]
Hi @cvphelps
Is there any way to delete my account on Wandb site, it is very strange that I didn't find any way to delete my account

**Comment by armanhar** [comment]
@Syzygianinfern0 You'll need to contact support. If you tell me your username i can delete the account for you.

**Comment by Syzygianinfern0** [comment]
Thanks! This is my username: `syzygianinfern0`.

**Comment by armanhar** [comment]
The account has been deleted.

**Comment by Syzygianinfern0** [comment]
@armanhar wait, now I cannot create an account with the same Mail ID once more? I just wanted to start over. 

![](https://i.imgur.com/MzYENtO.png)

**Comment by sydholl** [comment]
@Syzygianinfern0 apologies for the delay, you should now be able to sign up again using the same email.

**Comment by asifpatankar** [comment]
Hi @armanhar ! Can I still ask a favor from you for deletion of my account?

**Comment by ParasKoundal** [comment]
Hi @sydholl , any plans on implementing it online (so that user can do it themselves). Anyway can you delete my user account parask

**Comment by GuYoonJeong** [comment]
I made a mistake in the username, so I'd like to withdraw and rejoin. my username is brqiue. (so url is  ' https://wandb.ai/brqiuekoo ')
please delete my account.
