### ISSUE TITLE
[CLI] 

### ISSUE THREAD

**Issue by AndrewPelton** [wandb/client#1738]
**Description**
artifact.download() crashed the script in pytorch lightning ddp mode with more than one GPU

"None type has no attribute download"

**Comment by vanpelt** [comment]
Hey @AndrewPelton can you share the code you used to set the `artifact` variable?

**Comment by AndrewPelton** [comment]
Sure it's something like this:

from pytorch_lightning.loggers import WandbLogger
wandb_logger = WandbLogger(project=args.project, name=args.run_id, id=args.run_id)
artifact = wandb_logger.experiment.use_artifact(args.artifact, type='model')
artifact_dir = artifact.download()

**Comment by vanpelt** [comment]
Hey @AndrewPelton, that means that `args.artifact` is specifying an artifact that does not exist.  Can you share the `args.artifact` string so we can verify it actually exists?

**Comment by AndrewPelton** [comment]
I'm sure the file exists - the code works fine with a single GPU. It only crashes with multiple GPUs.

**Comment by vanpelt** [comment]
It's not a file, it's an artifact path like: "username/project/artifact_name:v21".  Can you share what the value of args.artifact is?

**Comment by vanpelt** [comment]
What could be happening is you're not including the username or project.  In mutli GPU mode `wandb.init` will only be called in the master process which sets the username and project.  The sub process wouldn't know which W&B username or project unless you specify the full path.

**Comment by AndrewPelton** [comment]
Sorry I meant artifact. I'm unable to share the specific string but it is the full artifact path in the correct format you mentioned:(username/project/artifact_name:latest)

**Comment by vanpelt** [comment]
If you can't share the specific string, we'll need a code snippet to reproduce this issue.  Can you make a small script that we could use to reproduce what you're seeing?

Looking at [the code](https://github.com/wandb/client/blob/master/wandb/sdk/wandb_run.py#L1794) I can't see how `use_artifact` would ever return `None`.

**Comment by jacobdanovitch** [comment]
Getting a similar error on the `use_artifact` call itself. 

```python
artifact = wandb.Artifact('model', type='model')
artifact.add_dir(model_path)
logger.experiment.use_artifact(artifact)

>>> File ".../python3.8/site-packages/wandb/sdk/wandb_run.py", line 1681, in use_artifact
>>>    api = internal.Api(default_settings={"entity": r.entity, "project": r.project})
>>> AttributeError: 'NoneType' object has no attribute 'entity'
```

This doesn't work even when only using one GPU.

**Comment by jacobdanovitch** [comment]
Ah okay, got it. I was running an offline run with `WANDB_MODE=dryrun`. In that scenario, it looks like `run._run_obj == None`. I guess line 1680 of `wandb_run.py` should either be changed to:

```python
# r = self._run_obj <<< old
r = self._run_obj or self._run_obj_offline # <<< new
```

Or it should just throw an error saying that we shouldn't be using artifacts with offline runs (not sure if this is intended to be supported).

**Comment by kfkelvinng** [comment]
It is instead a Pytorch-lightning problem https://github.com/PyTorchLightning/pytorch-lightning/issues/981
