### ISSUE TITLE
artifact.download() crashed the script with more than one GPU, "None type has no attribute download"

### ISSUE THREAD

**Issue by AndrewPelton** [wandb/client#1739]
**Description**
artifact.download() crashed the script in pytorch lightning ddp mode with more than one GPU

"None type has no attribute download"

Works fine with 1 GPU

**Comment by tyomhak** [comment]
Hey @AndrewPelton , thanks for reporting. Do you think you could share a minimal reproducing script for this?

**Comment by cigrainger** [comment]
I've got the same issue. Pretty tough to minimally reproduce without a WandB account. It appears the `self.logger.experiment` object is None when DDP forks.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
