### ISSUE TITLE
UI not showing last data point on history charts

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#174]
http://app.test/shawnlewis/exp6/runs/9kvl8as6

There should be 33 points on the chart, but the final step shown is 31.

The summary shows the values from step 32 correctly.

**Comment by lukas** [comment]
Shawn - is it possible that's only saved locally for you?  I get a not found when I follow that link.  I checked a couple of my charts and they seem to display the points, although the tooltip doesn't pop up on the point furthest to the left.
