### ISSUE TITLE
`scan_history` fails to return all data

### ISSUE THREAD

**Issue by cswinter** [wandb/client#1742]
```
>>> run = api.run('cswinter/deep-codecraft-vs/i17gv7pw')
>>> fullhistory = run.scan_history(keys=['_step']+[key for key in run.summary.keys() if key.startswith('frac')], page_size=1000000)
>>> lfh = list(fullhistory)
>>> lfh[0]
{'_step': 557056, 'frac_1s1c': 0.03699900767818093, 'frac_2m1e1p': 0.011693050186448124, 'frac_2s1c1e': 5.5531092243215074e-05, 'frac_1m': 0.598750226269633, 'frac_1s': 0.27077593410453016, 'frac_2s2c': 5.769247851088523e-05, 'frac_3m1p': 0.004155086135766922, 'frac_2s1m1c': 0.005418786752288872, 'frac_1m1p': 0.03414841798541147, 'frac_2m2p': 0.009646313251061127, 'frac_2m': 0.028299954065925073}
>>> min([x['_step'] for x in lfh])
557056
>>> len(lfh)
7597
```

I expect this to return the full set of data points, of which there should be around 7630 (I could be off by one).
Instead, `scan_history` seems to drop dozens of data points at the beginning of the run.
The first `_step_` should be 16384, as can be confirmed by visiting the run page.
I'm using `wandb==0.10.12`.

**Comment by cswinter** [comment]
(not sure why it labeled it `cli`, but should probably be `bug`?)

**Comment by vanpelt** [comment]
Hey @cswinter when you specify `keys` to scan history we only returns rows that have those keys.  You should be able to run `scan_history` without the `keys` attribute to get every row in your history.

**Comment by cswinter** [comment]
I see, so _every_ metric specified in `keys` has to be present, that makes sense actually. Not sure if getting a full history of every metric is feasible, but if that doesn't work I could also just request each metric I want individually.
