### ISSUE TITLE
View .sh files in the web app [Feature] 

### ISSUE THREAD

**Issue by greeneggsandyaml** [wandb/client#1744]
**Is your feature request related to a problem? Please describe.**
I love wandb. I use save_code to save my code and often view it in the online web app. However, when I save a .sh file, the web app gives "File type unknown". I obviously can download the file and view it locally -- this is what I currently do. It's not a big problem by any means, but it would be really nice to be able to view scripts in the web app. 

**Describe the solution you'd like**
Display `.sh` scripts like `.txt` files or `.py` files in the web app files tab.

**Comment by tyomhak** [comment]
Hey @greeneggsandyaml , thank you for the kind words! 
I'm filing an internal ticket to support viewing .sh files in the app. Thank you for the request!

**Comment by greeneggsandyaml** [comment]
Brilliant, thank you!

**Comment by ariG23498** [comment]
Hey @greeneggsandyaml 
I tried reproducing this behaviour.
I am using `wandb.save("run.sh")` to log the `.sh` file. In the web app the shell script renders properly.
Dashboard: https://wandb.ai/repro/sh-files/runs/2vfq42fd/files/run.sh

I am closing this issue for now. Please comment to reopen 😄
