### ISSUE TITLE
[Feature] Is there a way to delete a run from api or command line?

### ISSUE THREAD

**Issue by HaoLiuHust** [wandb/client#1745]
I am writing a script to use wandb, I wonder is there a way to delete a run from api or command line?

**Comment by tyomhak** [comment]
Hey @HaoLiuHust , I'm afraid currently we do not support deleting runs from the API. I believe it's possible to delete runs only from your workspace at the moment. 

Could you describe your use case for deleting a run from the API/command line?

**Comment by bensums** [comment]
Same request here. Would have thought this would be a very basic feature of any API. In my case, I have a huge number of runs (with associated data that's taking up a lot of space) and only want to keep a few of them (which I can identify programmatically).

**Comment by raubitsj** [comment]
@bensums @HaoLiuHust 
We added support for deleting runs in the API in version 0.10.18

simply use the delete() on the run object returned by the export api:
```
import wandb
api = wandb.Api()
run = api.run("<entity>/<project>/<run_id>")
run.delete()
```

**Comment by brando90** [comment]
> @bensums @HaoLiuHust We added support for deleting runs in the API in version 0.10.18
> 
> simply use the delete() method on the run object returned by the export api:
> 
> ```
> import wandb
> api = wandb.Api()
> run = api.run("<entity>/<project>/<run_id>")
> run.delete()
> ```

what about from the web interface? a distributed made me have 31 runs. I want to delete them all.

**Comment by brando90** [comment]
> 

what about an entire group?

**Comment by brando90** [comment]
hu, weird, runs do exist...all same name
```
wandb.errors.CommError: Could not find run <Run brando/.../run_name (not found)>
```
error

**Comment by brando90** [comment]
solution in the api: https://github.com/wandb/wandb/issues/3804 summary use the table view. puts little boxes then delete

**Comment by latorrefabian** [comment]
can this be achieved with a terminal command? for example `wandb delete <entity>/<project>/<run_id>`
