### ISSUE TITLE
[CLI] Metrics of sweep runs are not shown with id in wandb.init

### ISSUE THREAD

**Issue by freefeynman123** [wandb/client#1747]
**Description**
The metrics used for hyperparameter optimisation with sweeps are not logged when id is passed to `wandb.init` method. Individual runs do not show their metrics either.

**How to reproduce**
Example of a run with such bug: https://wandb.ai/freefeynman123/ifsl-MTL_sweeps/sweeps/q9fxzeuo?workspace=user-freefeynman123

The code for this project can be viewed in: https://github.com/freefeynman123/ifsl/tree/develop

You can view `MTL/trainer/meta.py` for details of given code.

After changing the line 
`self.run_train = wandb.init(project=self.args.project_name, id=id, resume="allow", job_type='train', entity=USER_NAME)` 
to 
`self.run_train = wandb.init(project=self.args.project_name, resume="allow", job_type='train', entity=USER_NAME)`
(essentially deleting id from `wandb.init`)

the metrics are shown, however tracking individual runs is lost and one cannot retrieve artifacts for given run.

**Environment**
- Docker base image: nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
- Environment: Kubernetes pod with RTX2080 GPU
- Python Version: 3.8.5

**Comment by tyomhak** [comment]
Hi @freefeynman123 , thanks for reporting this. We're looking into it.

**Comment by cvphelps** [comment]
Thanks, we should print a warning. ID can't be changed for sweeps. The sweep has already created the ID, so you can't change it. May I ask why you are setting the ID in this scenario?

**Comment by freefeynman123** [comment]
I thought about recovering artifact from particular run within the sweep. As I can see currently I only have access to artifacts with my entity name, without particular sweep or run name.

**Comment by cvphelps** [comment]
To get the best model file, saved as an artifact, from a sweep:
1. Run a sweep. Don't set run IDs.
2. Open the sweep page in the UI. Sort by the columns you care about to find the best run for a given metric.
3. Click on the best run, and then click on the artifact tab. Download the artifact. 

@annirudh could you describe how to do this from python

**Comment by annirudh** [comment]
From the API, you could do something like this:

```
import wandb
api = wandb.Api()
sweep = api.sweep("<entity>/<project>/<sweep_id>")
runs = sorted(sweep.runs, key=lambda run: run.summary.get("val_acc", 0), reverse=True)
best_run = runs[0]
for artifact in best_run.logged_artifacts:
  # can download the artifact files here
  ...
```
