### ISSUE TITLE
Less intrusive application errors

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#175]
Instead of displaying the Application Error page, let's change `displayError` to use the flash logic to display a message in the upper right hand corner saying either "Network Error" when we can't connect to the server.  You can simulate this by turning off wifi.  And "Application Error" for the other error cases.  Line 124 of apollo.js is an example of calling setFlash instead of displayError.  It's important to note that just checking for networkError this doesn't means it's a network error.  You'll have to reproduce by turning of wifi to ensure we catch that case.  All calls to displayError should be replaced with this approach for now.

**Comment by thekatic** [comment]
@vanpelt in case we want to get rid of this intrusive Application Error page, we will have two sets of flush error messages, one caught by Apollo's error handler `errorLink` and the second from existing ErrorPage.
Should I stack all flash error messages, also detect if it's Network error or not, or merge all error handles in one place, if possible?

**Comment by thekatic** [comment]
Initial idea is to catch Network error [here](https://github.com/wandb/client/blob/master/wandb/board/ui/src/util/apollo.js#L124), by its type `Failed to fetch`,
but same error will be caught .e.g. [here](https://github.com/wandb/client/blob/master/wandb/board/ui/src/pages/Model.js#L34) and [here](https://github.com/wandb/client/blob/master/wandb/board/ui/src/setup.js#L24).
And in case of Model page, you will get Flash message and Error page with message `You may have found a bug.`.

**Comment by vanpelt** [comment]
Let’s remove the error catching in the second link it’s redundant.  The 3rd one you linked to should be changed to flash.  The more centralized the better!

**Comment by thekatic** [comment]
Ok, cool.

**Comment by thekatic** [comment]
@vanpelt thoughts on this [commit](https://github.com/wandb/client/commit/8a8ba4e0f4f4fb1825f1d25e776311be3c00c414)?
