### ISSUE TITLE
[CLI] UsageError: Error communicating with backend

### ISSUE THREAD

**Issue by nasimrahaman** [wandb/client#1752]
**Description**
Some of my jobs are failing (since around yesterday) with `UsageError: Error communicating with backend`. The relevant part of the stacktrace (w.r.t an earlier version of wandb-client) is: 

```
  File [redacted]
    run = wandb.init(job_type=self.WANDB_JOB_TYPE, dir=self.wandb_directory, resume=resume,
  File "[redacted]/miniconda3/envs/[redacted]/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "[redacted]/miniconda3/envs/[redacted]/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 422, in init
    raise UsageError(error_message)
```
It appears to be from [this line](https://github.com/wandb/client/blob/0d5b1785ccadf6d275d3fb084d226b7b91506c11/wandb/sdk/wandb_init.py#L462), which in turn appears to come from a time-out [here](https://github.com/wandb/client/blob/0d5b1785ccadf6d275d3fb084d226b7b91506c11/wandb/sdk/interface/interface.py#L555). I understand that timeouts due to network delays are handled by a different process/thread (i.e. independently from the main training script), but somehow this particular instance seems to slip through.

**Comment by tyomhak** [comment]
Hey @nasimrahaman , thanks for reporting this. Can you check which wandb version this is happening with?

**Comment by nasimrahaman** [comment]
Hi @tyomhak, I'm on `0.10.12`.

**Comment by tyomhak** [comment]
Can you update to the latest version (0.10.15) and check if the issue persists?

**Comment by chrischoy** [comment]
I am using 0.10.15 and I recently saw all my jobs are failing due to this error on clusters.

**Comment by leonleo997** [comment]
I'm getting the same issue, any update?

**Comment by tyomhak** [comment]
Sorry for the delay. Unfortunately no updates yet, but we're currently looking into this issue. It's one of the top priorities for us right now.

**Comment by tyomhak** [comment]
Hey everyone! Can you please update to the latest version (0.10.30), and let us know if the error persists?

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
