### ISSUE TITLE
[CLI] UnicodeEncodeError: 'ascii' codec can't encode character '\u2b50'

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [wandb/client#1757]
**Description**
Using wandb through a SLURM job, I get an `UnicodeEncodeError` on some nodes on which code is being executed (not all).
I narrowed down the issue and the character that raises the error (not obvious from the original message) is the "white medium star": `\u2b50`.

**How to reproduce**
Minimal script allowing to reproduce error: `test.py`
```
#!/usr/bin/env python
import wandb
wandb.init(reinit=True)
wandb.init(reinit=True)
```
launched with (SLURM command):
```
srun --pty test.py
``` 

**Environment**
- OS: Ubuntu 20.04
- Environment: anaconda
- Python 3.6.12
- WandB version: wandb-0.10.15

**Backtrace**
```
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home/gva/wandb-client/wandb/sdk/wandb_init.py", line 689, in init
    run = wi.init()
  File "/home/gva/wandb-client/wandb/sdk/wandb_init.py", line 486, in init
    run._on_start()
  File "/home/gva/wandb-client/wandb/sdk/wandb_run.py", line 1431, in _on_start
    self._display_run()
  File "/home/gva/wandb-client/wandb/sdk/wandb_run.py", line 1230, in _display_run
    click.style(project_url, underline=True, fg="blue"),
  File "/home/gva/wandb-client/wandb/errors/term.py", line 41, in termlog
    silent=not _show_info,
  File "/home/gva/wandb-client/wandb/errors/term.py", line 94, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/gva/miniconda3/lib/python3.6/site-packages/click/utils.py", line 272, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 20-21: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    wandb.init(reinit=True)
  File "/home/gva/wandb-client/wandb/sdk/wandb_init.py", line 726, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
    self._display_run()
  File "/home/gva/wandb-client/wandb/sdk/wandb_run.py", line 1230, in _display_run
    click.style(project_url, underline=True, fg="blue"),
  File "/home/gva/wandb-client/wandb/errors/term.py", line 41, in termlog
    silent=not _show_info,
  File "/home/gva/wandb-client/wandb/errors/term.py", line 94, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/gva/miniconda3/lib/python3.6/site-packages/click/utils.py", line 272, in echo
    file.write(message)
```

**Comment by gabriel-vanzandycke** [comment]
a quick fix is to change the following in the final block of `_log` defined in `wandb/errors/term.py`:
```
        try:
            click.echo(line, file=sys.stderr, nl=newline)
        except:
            click.echo(line.encode(), file=sys.stderr, nl=newline)
```

**Comment by gabriel-vanzandycke** [comment]
failing characters (so far): ⭐️  🚀

**Comment by tyomhak** [comment]
hey @gabriel-vanzandycke , thanks for reporting and sharing a fix! Can you please try disabling emojis like this
`wandb.init(settings=wandb.Settings(show_emoji=False), reinit=True)` , and check if that fixes the issue for you?

**Comment by gabriel-vanzandycke** [comment]
surprisingly, it doesn't :(

**Comment by andimarafioti** [comment]
I have the same problem, the solution proposed by Gabriel works for me. Thanks mate!

**Comment by gabriel-vanzandycke** [comment]
@tyomhak what do you think about making a pull request with this change?

**Comment by gabriel-vanzandycke** [comment]
Should be linked with #1723

**Comment by cvphelps** [comment]
Hi @gabriel-vanzandycke thanks for your help getting a solution for this, my wonderful colleague @annirudh tried a PR: https://github.com/wandb/client/pull/1484/files

Unfortunately this fix doesn't work on all platforms, but we're working to address!

**Comment by nitbix** [comment]
Another way to reproduce this is to use PuTTY in windows, then run the above minimal script inside a GNU screen session. (the screen session may not even be necessary).

**Comment by gabriel-vanzandycke** [comment]
A workaround is to set ```os.environ["WANDB_SILENT"] = "true"```

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
