### ISSUE TITLE
[Feature] - allow users to specify title for wandb.roc_curve and wandb

### ISSUE THREAD

**Issue by tvetterli-fn** [wandb/client#1759]
**Is your feature request related to a problem? Please describe.**
As a user, if I log multiple ROC curves to a run, they will all have the `ROC curve` title, and I then have to go and manually update the titles via the UI. 

**Describe the solution you'd like**
I would like to be able to set the title of plots programatically, by adding a `title` argument [here](https://github.com/wandb/client/blob/7e97e860daafa2a73cc816b9705e91b131172e46/wandb/plot/pr_curve.py#L9(, as the `wandb.plot.line` [supports](https://github.com/wandb/client/blob/7e97e860daafa2a73cc816b9705e91b131172e46/wandb/plot/line.py#L4).

**Describe alternatives you've considered**
Manually editing the plots title.

**Comment by tyomhak** [comment]
Hey Thomas! Thanks for the request. We have an internal ticket filed for this.

**Comment by ariG23498** [comment]
Hey @tvetterli-fn 
We have incorporated this feature request in this [PR](https://github.com/wandb/client/commit/3d7f6b6082e077494b678532d128bcd46466de3b)

Closing this issue!
