### ISSUE TITLE
Zoomable charts

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#176]
Let’s make line charts zoomable by selecting a range on the chart.  We can likely use a similar approach to: https://github.com/uber/react-vis/tree/master/showcase/examples/zoomable-chart  Let’s do a quick first pass and we’ll give feedback on the ui.

**Comment by thekatic** [comment]
@vanpelt here's a new branch [task/zoomable_charts](https://github.com/wandb/client/tree/task/zoomable_charts) with initial support for zoomable line charts. Note that I still need to make LinePlotCrosshair and zoomable to play along, and to resolve small issue with zoomed chart area.

**Comment by lukas** [comment]
The zooming breaks the crosshair feature that shows the values of the chart.  I'm not sure what the right UI is (@shawnlewis - do you have suggestions?).

Also, the zooming goes to the wrong place on some charts, for example the chart in the upper left at http://app.test/openai/dashboards/dashboards

We should hold off pushing wandb until this is resolved.

**Comment by thekatic** [comment]
@lukas can you show few screenshots with zooming issue?

And in terms of the UI, one of the options would be to show zoom icon and crosshair together, and once you click you can drag to zoom, where crosshair is hidden at that point.
Maybe other option could be to add a delay once mouse cursor is stopped, after few seconds we hide crosshair and show zoom icon.
Or to show crosshair only when you hover over X axis labels.

**Comment by thekatic** [comment]
@vanpelt any notes on setting openai on local env?

**Comment by vanpelt** [comment]
run `invoker start invoker_prod.ini`, then goto http://app.test/openai/dashboards/dashboards

**Comment by thekatic** [comment]
Don't have permissions for it, or em I missing something?

**Comment by vanpelt** [comment]
You weren't an admin, you are now.

**Comment by thekatic** [comment]
All good now. Will see to limit zoom level based on steps in datapoints.

**Comment by thekatic** [comment]
@vanpelt there is a new [pull request](https://github.com/wandb/client/pull/185) that should address all the issues with zoomable charts, except this issue 'Error: <rect> attribute width: A negative value is not valid. ("-50")' when you open chart in modal popup.
I will resolve this first thing in the morning.

**Comment by thekatic** [comment]
All set.
