### ISSUE TITLE
[CLI] Continuing to log on the same run without having to re-init

### ISSUE THREAD

**Issue by johncookds** [wandb/client#1762]
**Is your feature request related to a problem? Please describe.**
Hi,
I am using the huggingface/transformers library, they have a WandbCallback integrated. I run a transformers script, using subprocess.call(), from a script which initializes wandb. The WandbCallback in the Huggingface/transformers Trainer creates it's own run instead of using the run which is already initialized(it actually logs to both but the metrics only show up in the new one).

**Describe the solution you'd like**
I'd like to be able to log to my existing run instead of a new run, this may be possible and I have just not found the right resource, if that is the case apologies for misclassifying the issue.

**Describe alternatives you've considered**
I've tried passing a run_name to the WandbCallback init step, but that just duplicates the run, so I have 2 runs with the same name.
Additionally if I avoid the init step, I receive an error that initialization is required.

**Comment by johncookds** [comment]
I've found a solution so will post it here and close the request.
The current solution is:
1. Setting the WANDB_RUN_ID environmental variable will connect the runs
2. The logging should work as is but the system metrics will double up, so you'll need to disable the system logging on one of the two init statements by passing wandb.init() the parameter:  
settings=wandb.Settings(_disable_stats=True)

For the transformers case I did this on my first init call and the default WandbCallback began logging metrics to the correct run. The system information only showed up after the second wandb.init which was okay with me.

**Comment by johncookds** [comment]
Unfortunately, the summary statistics do not persist once the run is finished I assume this may be because of some overriding that the first wandb initialization is doing of the second. The second one is where the logging occurs.

**Comment by vanpelt** [comment]
Hey @johncookds, you should be able to use [resuming](https://docs.wandb.ai/library/resuming), to append metrics and system stats to existing runs.  Can you provide a code example of what you're trying to do and why it's not working?

**Comment by johncookds** [comment]
Hi so from an initial script I init wandb and set the environmental variables:
`
wandb_info = wandb.init(project='test')
os.environ["WANDB_PROJECT"] = "test"
os.environ["WANDB_RUN_ID"] =wandb_info.id
os.environ["WANDB_RESUME"] = "allow"
`

then this process calls a subprocess which is initialized as:
`
wandb_info = wandb.init(
                project=os.getenv("WANDB_PROJECT", "huggingface"),
                config=config,
                name=run_name,
                resume="allow",
                **init_args,
            )
`

Once the subprocess is called the script with the first wandb initialization just waits for the subprocess to finishes and finishes right after that.

The config dictionary that is passed in the second instance shows up correctly and stays after the run is finished. In the second process I make a number of wandb_info.log() calls, which correctly show up both in the plots section and in the summary. When the run finishes, the summary section becomes blank but the plots section still has it's original plots.

**Comment by vanpelt** [comment]
I see, you can only resume a finished run.  You can not have two processes logging to the same run in parallel.  If you want to have multiple processes show up as the same "experiment" in our UI you should [use grouping ](https://docs.wandb.ai/library/grouping)and have each run share the same group id.

**Comment by johncookds** [comment]
Ok, that makes sense, thank you very much for the help!
