### ISSUE TITLE
[CLI]  unfinished process

### ISSUE THREAD

**Issue by danilpolkov** [wandb/client#1767]
**Description**
hi, I used wandb for tracking my model training process, and accidentally delete record for running process in web app, after that every next time I tried to run new training few messages appears

wandb: Currently logged in as: danylopoliakov (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.10.15
wandb: Syncing run snowy-puddle-6
wandb: ⭐️ View project at https://wandb.ai/danylopoliakov/crop_density_corn_2
wandb: 🚀 View run at https://wandb.ai/danylopoliakov/crop_density_corn_2/runs/telt4fmm
wandb: Run data is saved locally in /home/dpoliakov/gitlab/crop_density_estimation/wandb/run-20210128_125905-telt4fmm
wandb: Run `wandb offline` to turn off syncing.

wandb: Waiting for W&B process to finish, PID 22911
wandb: Program failed with code 2.  Press ctrl-c to abort syncing.
wandb:                                                                                
wandb: Find user logs for this run at: /home/dpoliakov/gitlab/crop_density_estimation/wandb/run-20210128_125905-telt4fmm/logs/debug.log
wandb: Find internal logs for this run at: /home/dpoliakov/gitlab/crop_density_estimation/wandb/run-20210128_125905-telt4fmm/logs/debug-internal.log
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced snowy-puddle-6: https://wandb.ai/danylopoliakov/crop_density_corn_2/runs/telt4fmm

and cant even train my model

**Wandb features**
import wandb
wandb.init(project='crop_density_corn')
wandb_config = wandb.config
wandb_config.model_source = self.config["model"]['model_source']
....

**How to reproduce**
1. run model training process
2. check that record appears in web app
3. delete this line with runnin experiment
4. try to run new training process

**Environment**
- Ubuntu
- Python 3.7.4, wandb==0.10.15

**Comment by vanpelt** [comment]
Hey @danilpolkov, can you share a small snippet of code that reproduces this issue.  It's not clear to me from this description exactly what's happening.

**Comment by cvphelps** [comment]
Hi, it sounds like you deleted a run and are trying to still log to that run. The ID persists, to allow you to undelete runs that were accidentally deleted. Please start a new run to start logging to a new ID.

If you really want to undelete — to your project overview page to undelete runs from the project:
![image](https://user-images.githubusercontent.com/6355078/106307300-694a1080-621c-11eb-9eb3-5b46eb011b07.png)

**Comment by danilpolkov** [comment]
HI, I deleted experiment  while it was running, and future experiments failed to start, with messages that I added in ticket. I created new project, but still the same result occur. I don't need to undelete, I just wanted to continue tracking experiments.
So I restarted my machine and it helps.

**Comment by cvphelps** [comment]
Hi Danil, you're saying that restarting solved the issue? This is a strange one that we haven't been able to repro yet.
