### ISSUE TITLE
Initializing wandb prevents parallel processes from throwing errors

### ISSUE THREAD

**Issue by loeweX** [wandb/client#1771]
**Describe the bug**
When running parallel processing using torch.multiprocessing initializing wandb prevents the program from throwing errors and stopping the program.

**To Reproduce**
Minimal example:

```
import torch
import wandb

def main(rank):
    wandb.init()
    raise ValueError

if __name__ == "__main__":
    torch.multiprocessing.spawn(main, nprocs=4, args=())
```

**Expected behavior**
The program should throw an error and stop running. When I remove wandb.init() from the above example, it behaves as expected.

**Desktop (please complete the following information):**
 - OS: Linux

Edit:
Additional comment: `wandb.init()` prevents the processes from stopping altogether. When I remove `raise ValueError` the program does not stop either.

**Comment by ariG23498** [comment]
Hey @loeweX 
Thanks for the ticket
We will be looking into this shortly.

**Comment by itssimon** [comment]
I'm also encountering the issue of processes not stopping. Is there a workaround for this? Currently it prevents us from running training on more than one GPU.

_W&B Technical FAQ:_
> It is extremely important to us that we never interfere with your training runs.

**Comment by xvr-hlt** [comment]
Is there any progress on this? Also running in to the issue

**Comment by konstantinjdobler** [comment]
I am also experiencing this issue!

**Comment by vanpelt** [comment]
@xvr-hlt @konstantinjdobler we're working on a fix for this and hope to include it in the next release.

**Comment by konstantinjdobler** [comment]
Checking to see if this fix made it into the 0.10.32 release @vanpelt

**Comment by vanpelt** [comment]
It did not make it into the latest release, we expect better multi processing support in the next release.  You can likely set the WANDB_START_METHOD=thread environment variable to fix this specific issue.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by janvainer** [comment]
Happens to me too
