### ISSUE TITLE
[App] Can't delete 65.5 Gb worth of data

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/client#1777]
**Describe the bug**
![image](https://user-images.githubusercontent.com/10344742/106358737-01f39580-62dc-11eb-80ed-72cfbe12e038.png)

**Expected behavior**
I expect the runs to be deleted.

**Operating System**
 - OS: [e.g. iOS] Big Sur version 11.1
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 88.0.4324.96

**Comment by MartFire** [comment]
I have the same issue, it might be related to #1199
I have exceeded the 100GB limit and some of my deleted runs use many GB but I can't delete their files :(

**Comment by ariG23498** [comment]
Hey Folks
We are getting into this as soon as possible
We have flagged this internally.

**Comment by imyhxy** [comment]
Still can not delete local files from web API now. :boom:

**Comment by vanpelt** [comment]
@imyhxy can you describe what error your seeing or share a screenshot?

**Comment by sydholl** [comment]
This issue was resolved in Feb 2020. Please comment if anyone is still experiencing issues.
