### ISSUE TITLE
Add new column after run is finished

### ISSUE THREAD

**Issue by awsaf49** [wandb/client#1780]
I'm wondering is there any way to add any new column after the run finished? Sometimes we don't have all the data while training so we need to add them after the run is finished. It will be really nice if we could simply add new columns or data even the run is finished.

**Comment by ariG23498** [comment]
Hey @awsaf49 
I think this should help you with your query: https://docs.wandb.ai/ref/export-api/examples#update-metrics-for-a-run-after-run-finished

Let me know if this helped :smile:

**Comment by awsaf49** [comment]
@ariG23498  yes this is exactly what I was looking for, thanks 😄
