### ISSUE TITLE
Disk I/O Utilization vs Disk Utilization

### ISSUE THREAD

**Issue by johannespitz** [wandb/client#1784]
I believe this client records the disk utilization (i.e. allocated space/free space) while the W&B website reports it as Disk I/O Utilization.
This was very confusing to me.
 
https://github.com/wandb/client/blob/b01e637c9d7dc6674e9bb6a11f087880af56e892/wandb/sdk_py27/internal/stats.py#L266
https://psutil.readthedocs.io/en/latest/#psutil.disk_usage

**Comment by ariG23498** [comment]
Hey @johannespitz 
I am tagging along @cvphelps who can get you a better answer for this. 
Thanks for the ticket :smile:

**Comment by johannespitz** [comment]
@farizrahman4u 
Why did you close the issue?
As far as I can see nothing has changed. The web interface still labels the graph as I/O, while the client records free space.

At least some kind of explanation would be nice.

**Comment by ariG23498** [comment]
Hey @johannespitz 
@farizrahman4u has created a PR for this ticket yesterday. The PR is in a private repository hence cannot be tracked here.
Hope you don't mind.

**Comment by johannespitz** [comment]
Ah, thanks for the info!
