### ISSUE TITLE
[Q] Is it possible to use operators like `max`, `mean` or even a `range` in Bar chart's expressions?

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [wandb/client#1794]
I would like to compare accuracy of different runs. However, the last entry (epoch) is not representative.

1. Bar chart's expression doesn't seem to work (the suggested `1-${summary:testing_accuracy}` doesn't work)
2. Is there a way to extract the mean or max value over the last 50 entries (epochs)?

**Comment by ariG23498** [comment]
Hey @gabriel-vanzandycke 
> Bar chart's expression doesn't seem to work (the suggested 1-${summary:testing_accuracy} doesn't work)
When we log `summaries`, we only keep the latest value of that metric. Hence when you are using the `testing_accuracy` for bar-chart it will only show the value logged for the latest run.
> Is there a way to extract the mean or max value over the last 50 entries (epochs)?
When you talk about a range of entries, it is quite reasonable to use a `line-plot` where you could specify the range of epochs or entries for that matter. On the other hand, you could use a more sophisticated approach and use our [custom charts](https://docs.wandb.ai/app/features/custom-charts). 

Let us know if this helped you in your case.
