### ISSUE TITLE
[Feature] Is it possible to output CSV file with the changed legend names?

### ISSUE THREAD

**Issue by wizard1203** [wandb/client#1795]
I have edited the legend names of one line plot. And when I output its according CSV file, the legend names do not change, how can I output CSV file with the legend names that I want?

**Comment by ariG23498** [comment]
Hey @wizard1203 
Thanks for the feature request. I will get this flagged.

**Comment by sydholl** [comment]
@wizard1203 this feature should implemented as of Feb 2020.
