### ISSUE TITLE
Parallel coordinates hard to interact with

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#180]
Vlad I merged your parallel coordinates stuff into my task/filters branch. Thanks! It'll probably be in master by the time you read this.

I think there's a z-order issue. If you create a brush on a dense part of a parallel coordinates plot, it's hard to move the brush. Also hard to create brushes generally.

This may have been an issue before as well.

Good example here: https://app.wandb.ai/shawn/fashion-sweep3/runs

**Comment by thekatic** [comment]
@shawnlewis you were right, it was order issue. Here is a new [pull request](https://github.com/wandb/client/pull/188) with quick fix.
