### ISSUE TITLE
Is it possible to visualize any hyperparameter optimization run as a "sweep"?[Q]

### ISSUE THREAD

**Issue by jonzarecki** [wandb/client#1809]
I'm looking into w&b but already use optuna as my go-to hyperparam optimization library.
Is it possible to log an optuna (or any other library for that matter) search run as a sweep?

**Comment by tyomhak** [comment]
Hey @jonzarecki , you want to collect runs made with optuna under a single sweep, without actually creating runs with the wandb sweep, is that right? 

If that's the case, then you could do something like this:
1. Log the runs as usual, just add a tag, or a group for them, so you could easily filter and select these runs later.
2. In the project page, you can create/seed a new sweep from these runs. [Here's](https://docs.wandb.ai/sweeps/existing-project#seed-a-new-sweep-with-existing-runs) the documentation for more details.

Please let me know if that's not what you meant.

**Comment by jonzarecki** [comment]
Yeah, seems like this is it. 
Thanks! 👍
