### ISSUE TITLE
[Feature] setting time interval for wandb.video

### ISSUE THREAD

**Issue by hw-kim-ivan** [wandb/client#1816]
**Is your feature request related to a problem? Please describe.**
Hello:) Is there any handling for setting time interval for wandb.video?
gif moves so fast...

**Describe the solution you'd like**
Currently, manually setting time interval on off-line(using powerpoint)

**Comment by ariG23498** [comment]
Hey @hw-kim-ivan 
I think the [documentation for the `wandb.Video`](https://docs.wandb.ai/library/log#media) might be of use to you.

**Comment by cvphelps** [comment]
@hw-kim-ivan could you please specify frames per second, for example fps=1

`wandb.log({"video": wandb.Video(numpy_array_or_path_to_video, fps=4, format="gif")})`
