### ISSUE TITLE
python2 / python3 wandb version crossup

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#182]
If you have a system with python2 and python3 installed globally (like an AWS deep learning AMI), and you pip install wandb, then run python3, you can import the python2 version of wandb, but you'll get weird errors.

**Comment by shawnlewis** [comment]
Also maybe if you run "wandb" from a python2 install, but you're running a python3 program, stuff goes wrong?

**Comment by lukas** [comment]
This is fixed.
