### ISSUE TITLE
[Q] Suppress Run summary and history in Jupyter notebook?

### ISSUE THREAD

**Issue by lewtun** [wandb/client#1823]
Hello wandb team!

I'm using `wandb` together 🤗  `transformers` and when I use the latter's hyperparameter search I get a lot of meta info from `wandb` about each trial:

![Screen Shot 2021-02-09 at 6 34 06 pm](https://user-images.githubusercontent.com/26859204/107404006-1585d400-6b06-11eb-846a-77e064648329.png)

I also get this information whenever I call `wandb.finish()` after a run.

My question is: is there a way to suppress this output from `wandb`? I don't really need all these details cluttering up my Jupyter notebook so it would be great if there is a setting to remove them.

I've tried executing this snippet in a separate cell

```python
import logging
logger = logging.getLogger("wandb")
logger.setLevel(logging.ERROR)
```

but this still produces the run summaries.

Thanks!

**Comment by cvphelps** [comment]
Hi there, sure you can set the environment variable `os.environ["WANDB_SILENT"]="true"` to silence the wandb printout

**Comment by lewtun** [comment]
Thanks a lot @cvphelps! Sorry I didn't spot this in the FAQ (I was looking in the Jupyter integration docs): https://docs.wandb.ai/library/technical-faq#how-do-i-stop-wandb-from-writing-to-my-terminal-or-my-jupyter-notebook-output
