### ISSUE TITLE
[Q] Logging from multiple threads

### ISSUE THREAD

**Issue by chisarie** [wandb/client#1824]
Hi, thank you very much for this amazing tool!
I have a question: when logging from different threads, I get a RuntimeError: "dictionary changed size during iteration", see also this pull request: [https://github.com/wandb/client/pull/110](https://github.com/wandb/client/pull/110).
I have found a workaround, I share it here, it might be helpful to others. The solution for me was to log with wandb in one thread and with tensorboard in the other thread, and of course setting `sync_tensorboard=True`. 
My question for the future: is there a better way to deal with multithreading logging?
Thank you again!
Eugenio

**Comment by vanpelt** [comment]
Hey @chisarie, currently `wandb.log` is not thread safe.  We'll leave this ticket open as we may eventually make it thread safe.

**Comment by chisarie** [comment]
All right, thank you :)

**Comment by epignatelli** [comment]
Hi! What's the state of this?

**Comment by vanpelt** [comment]
@epignatelli we're currently focussing our efforts on multiprocessing and haven't circled back to multithreading.  Can you share a little more about your usecase and maybe provide some example code as to what wandb api calls you want to parallelize in a single process?

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.

**Comment by NeilGirdhar** [comment]
It might be easier to add thread safety if there were a context manager interface:
```python
from wandb import init_context_manager:

with init_context_manager(settings=...) as wandb_session:
    wandb_session.log(...)
```

**Comment by rayne-hernandez** [comment]
Any progress on this? I have a microservice that does metadata lookups, and the client currently does not appear to be thread safe
