### ISSUE TITLE
UI: Fix SVG exporting to remove black regions

### ISSUE THREAD

**Issue by kargarisaac** [wandb/client#1831]
**Is your feature request related to a problem? Please describe.**
At the moment I export svg and try to use other applications to convert it to pdf. But the svg file has some black parts.

**Describe the solution you'd like**
It would be great to be able to export a high-quality image of plots. At the moment, the report and png exports are not good enough to put it on paper.

**Comment by tyomhak** [comment]
Hey @kargarisaac , sorry to hear that the current resolution is not satisfactory. 
I'm afraid the only option to control the resolution of your exported charts is this menu: 
<img width="623" alt="Screen Shot 2021-02-12 at 7 03 50 PM" src="https://user-images.githubusercontent.com/16812535/107784633-1ec0ac00-6d65-11eb-9403-ee39abc6fc72.png">

I'm bringing this issue up with the team. What resolution would you prefer to have?

**Comment by kargarisaac** [comment]
Putting PNG format in PDF doesn't sound good, especially when zooming. By using the way you suggested, I think the text size would be small and not readable in picture. I export svg and use Figma to remove black parts and customize everything there. In Figma there is a black color that by setting its value to 0% it removes the black parts (Under the curve from start to end) I mentioned in the question.

**Comment by ariG23498** [comment]
Hey @kargarisaac 
Can you confirm this behaviour still exists?
I seem to have downloaded a loss plot from my experiment and did not visualise any black spots on it.

Could you also screenshot and let us know about the black spots in the SVG that you are seeing?

**Comment by kargarisaac** [comment]
> Hey @kargarisaac
> Can you confirm this behaviour still exists?
> I seem to have downloaded a loss plot from my experiment and did not visualise any black spots on it.
> 
> Could you also screenshot and let us know about the black spots in the SVG that you are seeing?

Can you explain how you visualize the downloaded svg? what is the software you use? I tested again to visualize it in diagram.net in google drive but it has the black parts again:

![image](https://user-images.githubusercontent.com/24753756/115542272-c815a800-a2a8-11eb-92ba-5fd82d3359ad.png)

**Comment by ariG23498** [comment]
Could you share the link to the chart here?

**Comment by kargarisaac** [comment]
The project is ongoing, so I cannot share it, but the downloaded file from wand is attached.

[W&B Chart 4_21_2021, 1_47_06 PM.zip](https://github.com/wandb/client/files/6352337/W.B.Chart.4_21_2021.1_47_06.PM.zip)

**Comment by kargarisaac** [comment]
Hi,
Any update on this?

**Comment by sydholl** [comment]
Hi @kargarisaac, are you still experiencing this issue? If so, can you send another example? The last file you sent looks to be correct.

**Comment by kargarisaac** [comment]
Hi @sydholl, Yes, The problem exists. I didn't get a clear answer. How can I use the SVG file? how to open and visualize it? any recommended software on ubuntu? I used to use https://app.diagrams.net/ in google drive but after a while, it dodn't work anymore and I see black parts. 
![image](https://user-images.githubusercontent.com/24753756/143056943-d393de5c-f1c9-454c-914f-f52af1d9f872.png)
[test.zip](https://github.com/wandb/client/files/7589317/test.zip)

**Comment by aidanjdonohue** [comment]
Hi @kargarisaac so the black regions are a result of not having a standardized SVG format across all different toolset. I know it's not your first choice but your best bet to avoid this issue is to export your chart as a PNG.

**Comment by vanpelt** [comment]
@kargarisaac we're using the browsers native SVG rendering functionality.  Have you tried exporting in exporting from a different browser?  What browser generated the attached SVG?  As @aidanjdonohue mentioned we export a high resolution PNG which should render nicely in embedded documents.

**Comment by kargarisaac** [comment]
@aidanjdonohue @vanpelt  
thank you. I use chrome. The browser can open it successfully. 
I have to use png then. the problem with png is that when I save it, it's not similar to what is shown in the browser. Legends size and style change.

**Comment by MohamedAteya** [comment]
Hey, any updates on this issue?

**Comment by aidanjdonohue** [comment]
Hi @MohamedAteya, no movement on standardization. If you're having issues please either try a different browser or export a PNG instead.
