### ISSUE TITLE
Be able to change the location of legend in plots

### ISSUE THREAD

**Issue by kargarisaac** [wandb/client#1832]
**Describe the solution you'd like**

It would be great to be able to change the location of the legend in plots. Putting it on top of plots takes space and sometimes in papers, for example, it can help to save space.

**Comment by tyomhak** [comment]
Hey @kargarisaac , is there another spot on the plot that you'd prefer to have as an option to be used for the legend?

**Comment by kargarisaac** [comment]
It depends on curves. Sometimes under curves inside figure. Some times some other places. like these in matplotlib:

![image](https://user-images.githubusercontent.com/24753756/107841262-26626e00-6dc2-11eb-989f-50665db1b777.png)

![image](https://user-images.githubusercontent.com/24753756/107841263-2e221280-6dc2-11eb-8b93-33058154f34a.png)

![image](https://user-images.githubusercontent.com/24753756/107841267-35492080-6dc2-11eb-80cf-9c02618f17a1.png)

**Comment by minhlong94** [comment]
+1 for this feature

**Comment by lukas** [comment]
Would it be enough to be able to move the legend to top/bottom/left/right or do you want more fine grained control?

**Comment by lukas** [comment]
You can now move the legend location to top, bottom, left, right - if this isn't sufficient please reopen and suggest what else you would need.

**Comment by ioneliabuzatu** [comment]
@lukas how do i move the legend in the website?

**Comment by ioneliabuzatu** [comment]
@lukas perhaps being able to put the legend on the plot and not just on one side would be a nice addition
