### ISSUE TITLE
[Feature] Workspace: Specify sections for charts from wandb.log()

### ISSUE THREAD

**Issue by ingambe** [wandb/client#1834]
**Is your feature request related to a problem? Please describe.**
Every logs metrics is plotted in the "Charts" section of WandB.
If you have a lot of metrics of different types it can soon be messy.

For example, in one of my projects, I have more than 5 timers. 
It is super convenient to add them into the same section.
This needs to be done manually for the moment. A way to do it programmatically would be nice.

**Describe the solution you'd like**
 I would like to have an extra parameter in the wandb.log function to log the data in a different section than the default "Graphs" one.

**Describe alternatives you've considered**
Or maybe if a dictionary of dictionaries is passed to WandB logs, it can be plotted into the section named by the key of the master dictionary. This solution would suit me best, but I don't know for the general use case.

**Additional context**
Here an example of data plot into different sections:
![Screenshot 2021-02-12 at 16 26 59](https://user-images.githubusercontent.com/17440405/107787295-355c0880-6d4f-11eb-862e-6c6137d2e9a9.png)

**Comment by cvphelps** [comment]
Hi there, you can add a `prefix/` to the beginning of your metric name to sort into a specific section programmatically.

**Comment by ingambe** [comment]
Thank you, I've asked on Slack and I was told it was not possible.
Thanks a lot :)
Is it in the doc?

**Comment by ariG23498** [comment]
> Is it in the doc?
We do have it now
Thanks for the ticket 😄

**Comment by athn-nik** [comment]
Hello, I have added a prefix but it is not grouped in the same section. Eg.
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/24339666/162537722-bdeecccd-2ce7-48f2-8f31-43ec5c07b0a3.png">
I was expecting kl to be grouped all together and when I open that I would see the subplots..

**Comment by armanhar** [comment]
Hey @athn-nik, the way this is currently working is everything before the last / will specify the section. So for example k1/text2motion is the section and the val is the chart name.

**Comment by taehyunzzz** [comment]
Unfortunately, my logs are sent under the "Charts" section, instead of being in separate sections that start with "layer{i}" as shown below.
![Image](https://github.com/user-attachments/assets/4cbb7cd3-4d84-43a3-b482-472f750c6abe)

My code snippet looks like this. Can anyone see what I am doing wrong?
![Image](https://github.com/user-attachments/assets/48b79b52-d09c-4407-a54f-5d40a8e7a099)

**Comment by nordmtr** [comment]
> Unfortunately, my logs are sent under the "Charts" section, instead of being in separate sections that start with "layer{i}" as shown below. ![Image](https://github.com/user-attachments/assets/4cbb7cd3-4d84-43a3-b482-472f750c6abe)
> 
> My code snippet looks like this. Can anyone see what I am doing wrong? ![Image](https://github.com/user-attachments/assets/48b79b52-d09c-4407-a54f-5d40a8e7a099)

Experiencing the same issue
