### ISSUE TITLE
[Feature]  Simple moving average

### ISSUE THREAD

**Issue by ingambe** [wandb/client#1836]
**Is your feature request related to a problem? Please describe.**
There is currently a smoothing option using an exponential moving average, but not a simple moving average.

**Describe the solution you'd like**
An additional option in the smoothing one to select the smoothing algorithm we want to use and if we use a simple moving average, select the horizon (i.e., the subset size to compute the running average on).

**Describe alternatives you've considered**
I need to plot this myself and the horizon needs to be defined beforehand. Not practical.

**Additional context**
In a lot of algorithms, especially RL, the variance of the results of each iteration can be high, a simple running average is the default way to smooth everything as we know the subset size.

**Comment by ariG23498** [comment]
Hey @ingambe 
Thanks for the feature request!

**Comment by ingambe** [comment]
This feature has been added to WandB. Thank you 👍
