### ISSUE TITLE
Cannot login or verify email address

### ISSUE THREAD

**Issue by sunshineatnoon** [wandb/client#1838]
Thanks for this awesome tool! I met the following bug when login and would be appreciate if someone gives a hand.

**Describe the bug**
I forgot to verify my email address when registering and after a week of using wandb, I cannot login to the web app and got the following error:

<img width="710" alt="Screen Shot 2021-02-13 at 4 35 11 PM" src="https://user-images.githubusercontent.com/7546747/107865292-ac5dd380-6e19-11eb-8a8a-68072ab9253c.png">

When I go back to verify my email address I got the following error

<img width="410" alt="Screen Shot 2021-02-13 at 4 35 21 PM" src="https://user-images.githubusercontent.com/7546747/107865296-ba135900-6e19-11eb-8d4a-cce833782aea.png">

**To Reproduce**

**Expected behavior**
Is it possible to resend a verify email?

**Screenshots**
Please see screenshots above.

**Operating System**
 - OS: macOS
 - Browser chrome, safari

**Additional context**

**Comment by Severac** [comment]
I have the same problem
Workaround is to open a private window and login again with Google account

**Comment by sunshineatnoon** [comment]
I login this morning and found I can resend a confirm email. Now I can successfully login
