### ISSUE TITLE
[Q]Can we use wandb with tensorboard log file (log_dir) directly?

### ISSUE THREAD

**Issue by aj7tesh** [wandb/client#1843]
Currently,I am using tensorboard logging for one of my MT work.
 I directly launch tensorboard logging using below cli
tensorboard --logdir='runs/logs' --port=8080

I wish to use the same logdir with wandb. Can I use it somehow.
I dont wish to make changes in my training script(train.py) and integrate wandb there.

**Comment by ariG23498** [comment]
Hey @aj7tesh 
You can take a look at our [tensorboard integration](https://docs.wandb.ai/integrations/tensorboard).
Let us know if this helped!

**Comment by aj7tesh** [comment]
I checked that,
The thing is I dont want to make change in my original train funtion.
I wanted to know can I use this log_dir runs/logs in wandb.

**Comment by davidwallacejackson** [comment]
@aj7tesh We have an experimental version of the client with support for syncing a tensorboard logdir after a run, per https://docs.wandb.ai/integrations/tensorboard#syncing-previous-tensorboard-runs -- would this work for you? We're actively working to get this into a proper release.

As far as syncing tfevents files: we patch the tensorboard library in place when you call `wandb.init(sync_tensorboard=True)` -- so if you could run custom code _before_ OpenNMT runs its training script, that would probably do it. I'm not familiar with OpenNMT, so I don't know if this would be practical or not?

**Comment by ariG23498** [comment]
Hey @aj7tesh 
I have created a GIST for you where wandb can indeed log from the `log_dir` folder directly.

GIST: https://gist.github.com/ariG23498/238dfbbe5d748bfbbdbead3dd843d727

The patch:
```python
wandb.tensorboard.patch(root_logdir=log_dir)
run = wandb.init()
```
