### ISSUE TITLE
[Q] Logging Metrics for Previous Runs

### ISSUE THREAD

**Issue by AshCher51** [wandb/client#1845]
I have a project that has multiple runs in it. I have logged certain statistics for the most recent run, but I wanted to see if I could log statistics that I calculated for a previous one. Is there a way for me to log statistics for a run that is not the most recent one?

**Comment by ariG23498** [comment]
Hey @AshCher51 
Could you elaborate on your use case some more?

If you want to log something after the run, you can probably look into this: [API Guide](https://docs.wandb.ai/library/public-api-guide)

**Comment by AshCher51** [comment]
Thanks for the guide @ariG23498. I don't know how I missed it.
