### ISSUE TITLE
[App] "group by" results in error rendering

### ISSUE THREAD

**Issue by kaiwenw** [wandb/client#1847]
**Describe the bug**
When I try to group by common_input...policy_regularization...weight, it shows an error: "There was a problem rendering these panels."
If I group by another field (like common_input...algo), it does work as expected.

**To Reproduce**
1. Go to https://wandb.ai/kaiwenw/CartPole-v0/sweeps/2hoqa0oe?workspace=user-kaiwenw.
2. Group by common_input...policy_regularization...weight
3. See error

**Expected behavior**
Expect group by to work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/24740405/108005185-e1e6f600-6fac-11eb-8179-63294249306f.png)

**Operating System**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 88

**Comment by vanpelt** [comment]
Hey @kaiwenw this is a server error likely due to the dots in the metric name.  We'll look into how we can handle this better.

**Comment by kaiwenw** [comment]
@vanpelt, thanks! is there a hacky fix for now? 
And do you have an ETA for when the UI would work?

**Comment by vanpelt** [comment]
@kaiwenw unfortunately there's no hacky fix currently.  My colleague @annirudh is working on this issue this week.  We'll hopefully have a fix by the end of the fix.

**Comment by kaiwenw** [comment]
Hi @vanpelt, any update on this? the UI is still broken for me unfortunately :/ 
It'd be great if there's a hacky fix since I need this group by result by next Tuesday (02/23).

**Comment by sydholl** [comment]
Hi @kaiwenw, this issue should have been fixed in April 2020. Please let us know if you're still experiencing issues.
