### ISSUE TITLE
UI: Cross-panel highlight broken on scatter plot and parallel coordinates

### ISSUE THREAD

**Issue by talesa** [wandb/client#1861]
**Describe the bug**
[apologies for a clumsy title of this issue]
When running sweeps I create a new scatter plot, a "Distortion vs Rate" plot in an image compression setting (top left on the screenshots below).
(side note: the "Plot running maximum y values" works really well to draw a pareto frontier in such multi-objective optimization settings 🙏 )

Then I would like to investigate my logs, this is where the problem occurs.

A) When I select points on the "Loss v. created" plot (this one gets created automatically when a new sweep is started) the corresponding runs on the custom scatterplot are not highlighted.
![image](https://user-images.githubusercontent.com/6434262/108471664-9de14300-7283-11eb-8b09-eaade495ef4d.png)

B) When I select points on the custom scatterplot the corresponding runs on the bottom plot are not highlighted.
![image](https://user-images.githubusercontent.com/6434262/108471705-ae91b900-7283-11eb-8f4b-20e646df4c79.png)

**To Reproduce**
1. Create a sweep.
2. Create a custom scatterplot.
3. Highlight a range of runs.

**Expected behavior**
I would expect the corresponding runs in all figures to always be highlighted.

**Screenshots**
Included above.

**Operating System**
 - OS: MacOS 10.13.6 (17G14033)
 - Browser: Chrome
 - Version: 88.0.4324.182 (Official Build) (x86_64)

**Comment by cvphelps** [comment]
@talesa thanks! Could you please share a link to a page where you're seeing this?
Here's an example from my own workspace, and the scatter plot seems to highlight the runs on the parallel coordinates chart correctly for me:
https://wandb.ai/carey/pytorch-sweep/sweeps/n8uyjli8?workspace=user-carey

![2021-02-19 10 51 17](https://user-images.githubusercontent.com/6355078/108548517-c88dc480-72a0-11eb-913f-edca02643ef5.gif)

**Comment by talesa** [comment]
Thanks @cvphelps!

In the workspace you've shared do the following to replicate:
1. Create a new scatter plot: "accuracy v. loss"
![image](https://user-images.githubusercontent.com/6434262/108639160-077f6e00-748b-11eb-86c1-c3287f674dec.png)
2. Select a range of values on "accuracy v. loss"
![image](https://user-images.githubusercontent.com/6434262/108639149-e4ed5500-748a-11eb-8166-aac5cc36a44d.png)

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
