### ISSUE TITLE
pudb ui when using wandb

### ISSUE THREAD

**Issue by ruotianluo** [wandb/client#1873]
**Describe the bug**

I use pudb to debug my code. Currently, when I use wandb, it will affect the pudb UI.
Usually pudb should fill the whole terminal window, whereas now it becomes fixed sized and very small.

Also reported here: https://github.com/CompVis/taming-transformers/blob/master/main.py#L441

Any clue why that happens?
**To Reproduce**

**Expected behavior**
Using wandb should not affect pudb?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ariG23498** [comment]
Hey @ruotianluo 
Would you be able to attach some screenshots of what is happening here?
