### ISSUE TITLE
CLI: Import wandb writes files, which should only happen on an explicit function call

### ISSUE THREAD

**Issue by EricCousineau-TRI** [wandb/client#1874]
**Describe the bug**
We use Bazel for development and CI. I upgraded from `wandb==0.9.4` to `wandb==0.10.19`.
In CI, due to how Bazel is configured via sandboxing, any tests that try to write outside of their sandbox fail.
However, `import wandb` triggers a write to the home directory, thus causing the test to fail.

Workaround would be to change whatever environment variable to lie to `wandb` (right now, `$WANDB_CONFIG_DIR`), but it's not great to have to do that at an import level.

**To Reproduce**
This is the callstack from a failing test (some text scrubbed):
```
Traceback (most recent call last):
  File "my_script.py", line 11, in <module>
    import wandb
  File "{venv}/lib/python3.6/site-packages/wandb/__init__.py", line 118, in <module>
    api = InternalApi()
  File "{venv}/lib/python3.6/site-packages/wandb/apis/internal.py", line 17, in __init__
    self.api = InternalApi(*args, **kwargs)
  File "{venv}/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 74, in __init__
    load_settings=load_settings, root_dir=self.default_settings.get("root_dir")
  File "{venv}/lib/python3.6/site-packages/wandb/old/settings.py", line 25, in __init__
    self._global_settings.read([Settings._global_path()])
  File "{venv}/lib/python3.6/site-packages/wandb/old/settings.py", line 105, in _global_path
    util.mkdir_exists_ok(config_dir)
  File "{venv}/lib/python3.6/site-packages/wandb/util.py", line 642, in mkdir_exists_ok
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/home/user/.config/wandb'
```

**Expected behavior**
`import wandb` has no disk side-effects. Only an explicit event, like `wandb.init`, does anything.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 Bionic
 - Browser N/A (software)
 - Version: 18.04

**Smartphone (please complete the following information):**
N/A

**Additional context**
See above.

**Comment by EricCousineau-TRI** [comment]
(FWIW All the implicit patching done by `wandb.init` does make it more usable, but at least the user has clear control of it at that point.)

**Comment by cvphelps** [comment]
Hi Eric, thanks for reporting this. We're prioritizing and will address in a future release.

**Comment by jarivk** [comment]
Facing same issue. Is there any workaround ?

**Comment by sydholl** [comment]
This issue was fixed in June 2020. Please let us know if you're still experiencing issues.
