### ISSUE TITLE
wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '224579-yzgdojv7' for key 'PRIMARY' (<Response [409]>)

### ISSUE THREAD

**Issue by zliangak** [wandb/client#1893]
**Description**
I run multiple python experiment with different hyper-parameters and get the error:
```
wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '224579-m0paw8n2' for key 'PRIMARY' (<Response [409]>)
```

In every experiment, I use 
```
wandb.init(
      project='the same project name',
      name='different name for this run',
      config='some thing'
)
```

I notice that there are similar issues in 
https://github.com/ultralytics/yolov3/issues/1650
and
https://github.com/ultralytics/yolov5/issues/1878.

Thx

**Comment by vanpelt** [comment]
Are you specifying WANDB_RUN_ID or ever setting the `id` attribute when calling wandb.init?  Can you provide us with a self contained example or colab that consistently causes this to happen?

**Comment by vanpelt** [comment]
It seems like this is the underlying cause of the id issue: https://github.com/ultralytics/yolov5/pull/1852/files

Are you using a version of yolo that has this fix applied to it?

**Comment by aligholami** [comment]
Hey I'm having the same issue on a different project. For some reason I get the following every single minute (even when I'm not running anything the terminal shows this). Seems like a zombie process somewhere throwing this into the terminal:
`
wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '222274-17r7r20k' for key 'PRIMARY' (<Response [409]>)
`

**Comment by ZhicongLiang** [comment]
> Are you specifying WANDB_RUN_ID or ever setting the `id` attribute when calling wandb.init? Can you provide us with a self contained example or colab that consistently causes this to happen?

I did not specifying the WANDB_RUN_ID or set the ID in any other mean. 

I don't know how to reproduce the problem. Yesterday, I wrote a bash file to run my main.py every 3 seconds for different hyper-parameters. At the end of the training, I encounter this error.  I think it is caused by my frequent invoking of wandb. After I cancel all the python experiment, I keep getting this error in my terminal, just like https://github.com/wandb/client/issues/1893#issuecomment-785256950 says. When I try to delete the local wandb folder, I was reminded that several files could not be deleted since "Device or resource busy."

Then I rewrote my bash file to run my main.py every 30 seconds and everything works fine. I guess the problem is caused by too frequent invoking of wandb.

**Comment by ZhicongLiang** [comment]
> It seems like this is the underlying cause of the id issue: https://github.com/ultralytics/yolov5/pull/1852/files
> 
> Are you using a version of yolo that has this fix applied to it?

I did not use yolo.

**Comment by ariG23498** [comment]
Hey @ZhicongLiang 
If I am getting you correctly, you have written a bash script that runs the main.py every 3 seconds with different hyper-parameters. I think it would be better for you to use our `sweep feature`. This is a hyper-parameter tuning tool that we provide off the top. Here you can specify a `yaml` folder that holds all the configuration details about your hyper-parameters and that is it.
For more details on wandb sweep you can check out our documentation: [wandb sweep](https://docs.wandb.ai/sweeps)

In terms of the ticket that has been raised, could you share the bash script that does the job? Maybe I could try reproducing the issue and have a better understanding of what happens. 😄

**Comment by ZhicongLiang** [comment]
> Hey @ZhicongLiang
> If I am getting you correctly, you have written a bash script that runs the main.py every 3 seconds with different hyper-parameters. I think it would be better for you to use our `sweep feature`. This is a hyper-parameter tuning tool that we provide off the top. Here you can specify a `yaml` folder that holds all the configuration details about your hyper-parameters and that is it.
> For more details on wandb sweep you can check out our documentation: [wandb sweep](https://docs.wandb.ai/sweeps)
> 
> In terms of the ticket that has been raised, could you share the bash script that does the job? Maybe I could try reproducing the issue and have a better understanding of what happens. 😄

Thx for your suggestion! I will try that.
And my bash is:

```
n=0
for type1 in 1 2 3 4 5
do
  for type2 in 1 2 3 4 5 6 7
  do
    for lr  in 1e-4 1e-3
    do
      for t in 1800 1850 1900  1950 2000 2050
      do
          for hidden_dim in 512
          do
              n=$((n + 1))
              r=$((n % 10))
              python main.py --epochs 100 --lr_decay_step 20 --lr $lr --batch_size 128 --gamma 0.1 --momentum 0.9 --hidden_dim $hidden_dim --t $t --type1 $type1 --type2 $type2 --gpu $r &
              sleep 3s
          done
      done
    done
  done
done
```

**Comment by karthi0804** [comment]
Hi i get this error after deleting a run in the dashboard which was synched before and again trying to sync. Any suggestions?

**Comment by vanpelt** [comment]
@karthi0804 you'll need to sync the run to a new id.  When you run `wandb sync` you can specify a new run_id.  To get a new unique id you can run `wandb.util.generate_id()`

**Comment by karthi0804** [comment]
> @karthi0804 you'll need to sync the run to a new id. When you run `wandb sync` you can specify a new run_id. To get a new unique id you can run `wandb.util.generate_id()`

Thanks. It worked. I could resolve this by specifying `wandb sync --id xxxxxx`

**Comment by ariG23498** [comment]
Hey @karthi0804 
Glad that the issue resolved
Would you like to close the ticket?

**Comment by karthi0804** [comment]
> Hey @karthi0804
> Glad that the issue resolved
> Would you like to close the ticket?

But I didn't open the ticket. So I am not sure if the original problem is resolved. @zliangak should close the ticket if resolved for him.

**Comment by waltsims** [comment]
I am also getting this error. Not sure why. I have tried to run `wandb sync --id <id>` but there is nothing to sync. I am currently not able to use wandb

**Comment by manestay** [comment]
I am also getting this issue, just starting today (it was working fine before today). I am using huggingface transformers, and my wandb call is 
`wandb.init(project=proj_name, name=exp_name)`. I tried passing in `id=wandb.util.generate_id()`, but it still gives Error 1062.

**Comment by waltsims** [comment]
It seems I had some zombie processes from wandb still running on my machine. I restarted my machine and things seem to be working once again.

**Comment by WilderLavington** [comment]
I am getting this error when I try to sync experiments generated by a sweep that were run elsewhere on different resources. Is there a flag to just ignore this error and replace the data upon syncing at a new resource? This error basically means that huge subsets of my experiments are now impossible or at least impractical to access.

**Comment by IvanHahan** [comment]
I'm having these issue now. Can't fix it. Don't have any local runs, so nothing to sync. I tried to reload a computer, also didn't help.

**Comment by BBerabi** [comment]
Deleting the local wandb folder that is created in the folder where the experiment is ran fixed it for me.

`rm -rf wandb/`
