### ISSUE TITLE
[CLI] api.sweep broken for large sweeps (read timeout)

### ISSUE THREAD

**Issue by vrodriguezf** [wandb/client#1894]
**Description**
When running `api.sweep` with "large" sweeps (actually not that large, just around 180 runs), this error appears:
```
CommError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=9)
``` 

I've realized that it also crashes when pressing the download icon in the wandb app, in the table view.

**Wandb features**
Just using the Python wanb api. 

**How to reproduce**
2 ways:
- execute `sweep = api.sweep("stardust-r/deep-learning-space-weather-forecasting/inztzkl4")`
- go to  the sweep in the app (https://wandb.ai/stardust-r/deep-learning-space-weather-forecasting/sweeps/inztzkl4?workspace=user-ecstevenson) and try to download the sweep table.

**Environment**
- OS: Ubuntu 20.04
- Environment: Jupyter Notebooks & docker
- Python Version: 3.8.5
- Wandb version: We've tried the multiple versions, including the most recent 0.10.19

**Comment by tyomhak** [comment]
Hey @vrodriguezf , thanks for reporting the issue. I'm trying to reproduce it through the UI right now, but it's downloading just fine for me. You're talking about this download button, and then exporting it as csv, right?
<img width="283" alt="Screen Shot 2021-02-26 at 7 11 37 PM" src="https://user-images.githubusercontent.com/16812535/109317889-a37fef80-7866-11eb-976e-ff6a5c2e4a3f.png">

I visualized all columns, to put max strain on it, but it still downloads just fine for me. 
Are you using a VPN or something similar?

**Comment by vrodriguezf** [comment]
Thank you for your help @tyomhak . I'm just interested in the run id column, but when I press the download button it takes ages. It's weird that it works for you! I'm not using a VPN, if I take sweeps with less runs it works good.

**Comment by tyomhak** [comment]
I have tried again, and now it's definitely not "snappy" for me either. We'll look into this, and see if we can improve the performance. Thanks for reporting! :) will let you know if we have updates.

**Comment by vrodriguezf** [comment]
Thanks! We've been recommended to log less things in each run, we'll try that as well to see if it alleviates the issue

**Comment by sydholl** [comment]
Hi @vrodriguezf, this should now be fixed. Please let us know if you're still experiencing issues.
