### ISSUE TITLE
[CLI] Synchronyzing artifact dataset with amazon S3 sometime fails

### ISSUE THREAD

**Issue by Yura32000** [wandb/client#1897]
We are using W&B artifact as dataset of links to S3 real data.
However, sometime doing the following command fails to update artifact with links to S3

wandb init -e XXX -p YYY
 wandb artifact put -n YYY -t dataset  s3://bucketyname/YYY

I see that dataset artifact is cretaed correctly but its links are missing

**Comment by tyomhak** [comment]
Hey @Yura32000 , thanks for reporting this. We're looking into it.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
