### ISSUE TITLE
CLI Clarification: How wandb handles the queue, writing to disk, and network requests

### ISSUE THREAD

**Issue by emilemathieu** [wandb/client#1904]
**Is your feature request related to a problem? Please describe.**
Logging can be expensive in read / write. Would like to be able to write to disk / send to network `every_n_steps`.

**Describe the solution you'd like**
Tensorboard's `SummaryWriter` has a `max_queue` parameter that is `Size of the queue for pending events and summaries before one of the 'add' calls forces a flush to disk.`

**Describe alternatives you've considered**
Thought that using `commit=False` in `Run.log` method could do the trick, but it's not suited since updating the `step` between this batch call of `log(..., commit=False)` with trigger
```
elif step > self.history._step:
                self.history._flush()
```

**Comment by cvphelps** [comment]
Hi there, could you tell me more about what perf issues you're seeing? Behind the scenes we do use a queue and communicate to a separate process that does the upload.

**Comment by emilemathieu** [comment]
Hi @cvphelps, we're using wandb over a NFS, and recently we've had big write requests, perhaps not from wandb, but generally we were trying to avoid writing to much, and hence not flush the loggers at every step.
Good news is that is already implemented behind the scene. Could you tell a bit more on that? Are the logs written on the disc or only uploaded?

**Comment by cvphelps** [comment]
Sure, thanks for the clarification. @vanpelt could you share a little more of the details here on how we handle writes.

**Comment by vanpelt** [comment]
Hey @emilemathieu we queue in memory but also [write the events to disk](https://github.com/wandb/client/blob/7cc4dd311f3cdba8a740be0dc8903075250a914e/wandb/sdk/internal/datastore.py) asynchronously to handle failures and for the `WANDB_MODE=offline` case where you can sync the data after it's been logged.

In your terminal, you can see a path to the local run directory.  This directory will contain a ".wandb" file that is the datastore above.  If you're also logging images, we write them to "media/images" in that directory before uploading them to cloud storage.

**Comment by ariG23498** [comment]
Hey @emilemathieu 
I am closing this ticket as it seems that CVP has already answered your question. Please feel free to comment on this thread if you wanted to know anything more. 😄
