### ISSUE TITLE
[Q] How do I silence terminal outputs from wandb?

### ISSUE THREAD

**Issue by kouroshHakha** [wandb/client#1905]
Hi, 

since the upgrade to 0.10.20, wandb operations print stuff like what follows. Is there any way to suppress these (maybe with an ENV variable)?

```I0226 08:01:20.197602 123145536217088 sender.py:122] send: files
I0226 08:01:20.197953 123145536217088 sender.py:730] saving file model.pt with policy live
I0226 08:01:20.200783 123145536217088 sender.py:122] send: telemetry
I0226 08:01:20.204282 123145546727424 handler.py:101] handle_request: poll_exit
I0226 08:01:20.382661 123145536217088 sender.py:122] send: exit
```

**Comment by cvphelps** [comment]
Good morning! Sure, you can set the environment variable `os.environ["WANDB_SILENT"] = "true"`

**Comment by kouroshHakha** [comment]
No this is not exactly what I was looking for. This will silent everything including the initial wandb.init() information, for example if there is a newer version or the other stuff that it prints .etc. Those are still useful. These specific things that I pasted in the issue appeared after I updated to 0.10.20, they didn’t exist before.

**Comment by vanpelt** [comment]
Hey @kouroshHakha we're looking into the root cause, but it seems like in your case its related to python logging.  A quick fix should be to add the following to your script until we find what's causing this:

```
import logging
logger = logging.getLogger("wandb")
logger.setLevel(logging.ERROR)
```

**Comment by kouroshHakha** [comment]
I did it after importing `wandb` and it still prints stuff. This is really annoying when I'm in pdb mode. It constantly keeps informing me about any exchange of information that happens in the backend with the server.

**Comment by vanpelt** [comment]
Hey @kouroshHakha understand this is really annoying.  We can’t reproduce this on our end.  Can you share a minimal amount of code and details about your environment so we can reproduce / offer a hot fix?

**Comment by Div99** [comment]
Seeing the same issue using Python 3.7 on a Mac

**Comment by ShreeshaN** [comment]
Facing the same issue. 

System specifics:

- Macbook | BigSur
- Python version: 3.7
- wandb version: 0.10.21 
- Logging module version: 0.5.1.2
- Torch version: 1.5.0

I get this warning message in the beginning `WARNING: Logging before flag parsing goes to stderr.`
And then the console gets flooded with:

> I0305 17:38:48.678295 123145375662080 meta.py:66] save pip done
> I0305 17:38:48.678462 123145375662080 meta.py:231] probe done
> I0305 17:38:48.684715 123145365151744 sender.py:122] send: files
> I0305 17:38:48.685180 123145365151744 sender.py:730] saving file wandb-metadata.json with policy now
> I0305 17:38:48.685804 123145365151744 sender.py:730] saving file code/covid_19/main.py with policy now
> I0305 17:38:48.686543 123145365151744 sender.py:730] saving file diff.patch with policy now
> I0305 17:38:55.770550 123145365151744 sender.py:730] saving file wandb-summary.json with policy end
> I0305 17:38:56.454938 123145365151744 sender.py:122] send: stats
> I0305 17:38:57.511369 123145365151744 sender.py:122] send: summary 

Please fix this!

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by ndvbd** [comment]
I did:

```
import logging
loggers = [logging.getLogger(name) for name in logging.root.manager.loggerDict]
for logger in loggers:
	logger.setLevel(logging.WARN)
```

**Comment by vanpelt** [comment]
You can set the WANDB_SILENT=true env var: https://docs.wandb.ai/guides/technical-faq/troubleshooting#how-do-i-stop-wandb-from-writing-to-my-terminal-or-my-jupyter-notebook-output
