### ISSUE TITLE
[App] UI bug - unable to change size of column with run names in the workspace tab

### ISSUE THREAD

**Issue by Spandan-Madan** [wandb/client#1909]
**Bug Description**
Run names for experiments can often be long and so it's useful to change the size of the column displaying run names. When in the workspace tab i.e. with all the charts, the size of this column doesn't change when dragging on the separator between columns. My current workaround is switching to the table tab, changing the column size and switching back to workspace mode.

Not a big issue, just a UI bug so I thought I should flag it!

**Browser Details**
 - Browser: Safari
 - Version: 14.0.2 (15610.3.7.1.10, 15610)

Thanks!

**Comment by ariG23498** [comment]
Hey @Spandan-Madan 
Thanks for the ticket, but I think we already implement the functionality as shown 👇 
https://www.loom.com/share/6865b14efe094a8baa9b7bed22226ee0

Hope this helps! 😄
