### ISSUE TITLE
[Q]How to avoid login

### ISSUE THREAD

**Issue by Jie-Yuan** [wandb/client#1911]
![image](https://user-images.githubusercontent.com/20265321/109475159-51320f00-7ab0-11eb-99e2-d58f7741e492.png)

**Comment by Jie-Yuan** [comment]
Login by default through a certain configuration

**Comment by vanpelt** [comment]
Hey @Jie-Yuan you can set the `WANDB_API_KEY=XXXX` [environment variable](https://docs.wandb.ai/library/environment-variables#optional-environment-variables) to avoid logging in manually.

**Comment by aeltorio** [comment]
@vanpelt @cvphelps 
as today it seems to not work:
![Image](https://github.com/user-attachments/assets/286865f2-6f61-4701-ade3-8761017bb467)
It is needed for login without user interaction.
Ronan
