### ISSUE TITLE
Launch sweeps and agents using API [Feature] 

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/client#1926]
I currently use a bash script to launch `wandb` sweeps and associated agents:
```bash
wandb_output=$(wandb sweep --name "$name" "$config" 2> >(tee >(cat 1>&2)))
id=$(echo $wandb_output | tail -n1 | awk 'END {print $NF}')

echo "Creating $nruns sessions..."

for i in $(seq $gpu0 $(($gpu0 + $nruns-1))); do
  gpu=$(($i % $ngpu));
  echo "tmux at -t $session$i"
  tmux new-session -d -s "$session$i" "CUDA_VISIBLE_DEVICES=$gpu wandb agent $id"
done
```
Parsing strings with bash is awkward and prone to error. I would like to rewrite my script in python using the `wandb` API. In the documentation, I see options for querying runs and sweeps and for creating an individual run, but not for creating a sweep or spawning agents for an existing sweep. 

Ideally I would like two methods: `create_sweep` and `launch_agent` or something to that effect. Please let me know if there is a good way to do this with existing `wandb` features.

**Comment by ariG23498** [comment]
Hey @ethanabrooks 
We do support sweeps from the `wandb API`.

## Initializing the sweep
```python
sweep_config = {
    "name": "My Sweep",
    "method": "grid",
    "parameters": {
        "param1": {
            "values": [1, 2, 3]
            }
    }
}
wandb.sweep(sweep_config, entity="xxx", project="xxx")
```

## Launch agent
```python
def train():
    run = wandb.init()
    print("config:", dict(run.config))
    for epoch in range(35):
        print("running", epoch)
        wandb.log({"metric": run.config.param1, "epoch": epoch})

wandb.agent("<SWEEP_ID>", function=train)
```

Docs: https://docs.wandb.ai/sweeps/python-api
Hope this solves your problem 😄

**Comment by ethanabrooks** [comment]
It certainly does! I guess I missed this. Thank you!
