### ISSUE TITLE
[CLI] Wandb causes hang at exit if run in a python subprocess

### ISSUE THREAD

**Issue by samsamoa** [wandb/client#1927]
**Description**
The following script will hang indefinitely:
```
def run():
    import wandb
    wandb.init()


if __name__ == "__main__":
    import multiprocessing as mp
    p = mp.Process(target=run)
    p.start()
    p.join()

```

**How to reproduce**
1. Run the script above
2. Observe that the script never exits

**Environment**
- OS: Observed on MacOS 11.2 and Linux/Ubuntu 18.04
- Python Version: 3.8.5

**Comment by samsamoa** [comment]
This seems to be related to the fact that `atexit` doesn't work in subprocesses: https://stackoverflow.com/questions/34506638/how-to-register-atexit-function-in-pythons-multiprocessing-subprocess

**Comment by samsamoa** [comment]
My current solution is to manually run the `atexit` functions if my Process exits:
```
    try:
        fn(**fn_kwargs)
    finally:
        atexit._run_exitfuncs()
```

**Comment by ariG23498** [comment]
Hey @samsamoa 
Thanks for the details.
We will look into this. 😄

**Comment by KyleGoyette** [comment]
Hi @samsamoa, thanks for your patience on this.  Could you add `wandb.finish()` to the end of your runs that are running in subprocesses? This should solve the issue.

**Comment by samsamoa** [comment]
Thanks @KyleGoyette - this works as well, since `run_exitfuncs()` above calls `wandb.finish()`.

I'd suggest adding this example snippet to your documentation, as it took me quite a while to track down:
```
def spawned_process_fn():
    try:
        train()
    finally:
        wandb.finish()
```

**Comment by samsamoa** [comment]
Thanks @KyleGoyette - this works as well, since `run_exitfuncs()` above
calls `wandb.finish()`.

I'd suggest adding this example snippet to your documentation, as it took
me quite a while to track down:
```
def spawned_process_fn():
    try:
        train()
    finally:
        wandb.finish()
```

**Comment by KyleGoyette** [comment]
Hi @samsamoa we've since improved the docs here: https://docs.wandb.ai/guides/track/advanced/distributed-training#hanging-at-the-end-of-training, thanks for your advice. Closing.
