### ISSUE TITLE
Resuming sweep returns wrong config.

### ISSUE THREAD

**Issue by ganitps** [wandb/client#1929]
**Describe the bug**
Hi, I'm trying to resume a sweep  run with resume = "PreviousRun.id" but the `wandb.config` I read after `wandb.init` are not always the interrupted run parameters 

**To Reproduce**
- create sweep
- start an agent (write `run.id` to file)
- read `wandb.cofig` (save wandb.config)
- start another agent(write `run.id` to file)
- stop first agent
- new run(wandb.init) with resume= `run.id`
- compare `wandb.cofig` to saved config. 
- see diff...

**Expected behavior**
`wandb.config` is  the same at first agent run and resumed run.

**Screenshots**
None

**Operating System**
 - OS: macOS Catelina
 - Browser: Chrome
 - Version: 88.0.4

**Additional context**
None.

Thanks!

**Comment by ariG23498** [comment]
Hey @ganitps 
As far as I understand your ticket, you want to resume a stopped run that is part of a sweep. I am a little confused as to why we need another agent for this ticket?

It would be great if you shared a working snippet of the issue that you are facing. That would help us reproduce and share our insights really quickly.

**Comment by ganitps** [comment]
Hi @ariG23498 , 
Thanks for your reply, I edited the "To Reproduce" your question was right, I dont start a new wandb agent...
like this:
run = wandb.init(project="my_project", entity="my_entitiy", config=default_config, resume="last_run_id")
print('config', wandb.config)

the output is same as default_config and not as sweep config printed on the first agent run.
but the run does resume and graphs resume from the same point. (visually seen in wandb site )

I hope I am clear, I'm new to wandb.
Tanks!
Ganit.

**Comment by ariG23498** [comment]
> run = wandb.init(project="my_project", entity="my_entitiy", config=default_config, resume="last_run_id")

Here you are passing the `default_config` to the run. This will eventually show the default config as you print the config of the run.

I tried reproducing the ticket that you had raised. A detailed walk-through is as follows 👇 

## `train.py`
```python
import wandb

# Set up your default hyperparameters before wandb.init
# so they get properly set in the sweep
hyperparameter_defaults = {
    "learning_rate": 1,
    "emb_dim": 32,
    "attention_heads": 2,
    "max_neighbors": 15,
}

# Pass your defaults to wandb.init
run = wandb.init(config=hyperparameter_defaults)
print(f"ID -> {run.id}")
config = wandb.config
print(f"CONFIG -> {dict(config)}")

# Log metrics inside your training loop
metrics = {
    "test_pos_rec": config["learning_rate"] * config["emb_dim"]
    + config["attention_heads"] / config["max_neighbors"]
}
with run:
    run.log(metrics)

```

## `sweep.yml`
```yaml
program: train.py
method: bayes
project: project_name
entity: entity_name
metric:
  name: test_pos_rec
  goal: maximize
parameters:
  learning_rate:
    min: 0.001
    max: 0.1
  emb_dim:
    min: 32
    max: 256
  attention_heads:
    min: 2
    max: 12
  max_neighbors:
    min: 15
    max: 50
```

- `$ wandb sweep sweep.yml`
- Running the sweep agent
- Ctrl + C in the console to abruptly stop the sweep run.
![image](https://user-images.githubusercontent.com/36856589/110354713-78fc1680-805e-11eb-8b4d-1c0cf6f495f7.png)
- In a python console trying to resume the run `run = wandb.init(project="project_name", entity="entity_name", resume="9b6qf4v9")`
![image](https://user-images.githubusercontent.com/36856589/110354842-9d57f300-805e-11eb-915a-5f8feee19480.png)

I do not seem to find any discrepancies with the config. I hope this helps you 😄

**Comment by ganitps** [comment]
Thanks @ariG23498 !!
That does solve my problem :) and now that you say it it sounds logical... 👍
