### ISSUE TITLE
[App] Missing bounding boxes in images in fullscreen/expanded mode

### ISSUE THREAD

**Issue by kielnino** [wandb/client#1930]
**Describe the bug**
I do log some images and add bounding_boxes to them with code like:

```python
masked_img = wandb.Image(deprocess_img(pad_image, self.config.experiment.model.backbone), 
                masks={
                    "predictions": {
                        "mask_data": np.squeeze(result),
                        "class_labels": class_labels
                    },
                    "groud_truth": {
                        "mask_data": np.squeeze(pad_target*2.),
                        "class_labels": class_labels
                    }
                },
                boxes={
                    "predictions": {
                        "box_data": [{"position": {"minX": bb[0], "maxX": bb[2], "minY": bb[1], "maxY": bb[3]}, "domain": "pixel", "class_id" : 1,} for bb in pred_bb],
                        "class_labels": class_labels,
                        },
                    "groud_truth": {
                        "box_data": [{"position": {"minX": bb[0], "maxX": bb[2], "minY": bb[1], "maxY": bb[3]}, "domain": "pixel", "class_id" : 2,} for bb in gt_bb],
                        "class_labels": class_labels,
                    }
                })
```

In the web app the images and bounding boxes are rendered fine, but when I click on one image to see it in detail, the boundin boxes are not rendered at all.
However if I click on the download-button on an image (top right corner), the bounding boxes are rendered on the saved image.

**To Reproduce**
1. Log images with boxes as shown above
2. In the web app, select the run
3. In the media tab the images are shown with bounding boxes rendered
4. Click on an image to see it in fullscreen/expanded view -> No bounding boxes are rendered

**Expected behavior**
I would expect to see the Bounding boxes in the fullscreen mode as well, as I want to inspect the image and the detection results in detail.

**Operating System**
 - OS: Windows 10
 - Browser Chrome (89.0.4389.82)

**Comment by ariG23498** [comment]
Hey @kielnino 
Thanks for the ticket. We are tracking it internally.

**Comment by kielnino** [comment]
Hi @ariG23498, do you have any news about the status of this issue to share with us?

**Comment by cvphelps** [comment]
HI @kielnino we're taking a look at this issue, haven't published a fix yet.

**Comment by aidanjdonohue** [comment]
Hi @kielnino, we pushed a fix this week!
