### ISSUE TITLE
[Q] HTTPError: HTTP Error 403: Forbidden while running Simple_PyTorch_Integration.ipynb in Colab

### ISSUE THREAD

**Issue by arvindchandel** [wandb/client#1931]
After running through all the cell, once we are executing the cell with below:

# Build, train and analyze the model with the pipeline
model = model_pipeline(config)

I am getting HTTP error. Any solution for this?

**Comment by ariG23498** [comment]
Hey @arvindchandel 
Could you share the colab link or the code snippet where you are facing this error?

**Comment by venkatasg** [comment]
I'm getting the same error as well - this is with the [Simple Pytorch Integration notebook](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch/Simple_PyTorch_Integration.ipynb#scrollTo=JPQG1_I8DB7U)

**Comment by arvindchandel** [comment]
@ariG23498 @venkatasg include following code and run it before running the cell, where you getting HTTP error, include User-agent as per yours setting.

from six.moves import urllib
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Chrome/35.0.1916.47')]
urllib.request.install_opener(opener)

**Comment by arvindchandel** [comment]
Issue is resolve, so closing it.
