### ISSUE TITLE
[Feature] Web client: extend "What makes this run special?" to multiple runs, or simply a "notepad"

### ISSUE THREAD

**Issue by rodrigo-castellon** [wandb/client#1933]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm constrained by the W&B web client to write a note for each specific run (i.e. the "What makes this run special?" editable text field). This is far too time-consuming if I want to keep a reminder for myself like "runs 1 to 11 were mainly for debugging purposes, before I had implemented XYZ technique" or "runs 55, 58, and 60 are particularly important because [insert reason here]".

**Describe the solution you'd like**
It would be great to have some sort of notepad associated with the project (maybe as a new "tab" on the left-hand bar), where I can freely jot down information relating to the runs, without being constrained to the specific way the web client handles note-taking for runs.

**Describe alternatives you've considered**
I haven't really considered any alternatives; the notepad would probably be the best option, unless there was some other way (which might be harder or more involved to implement) to have a GUI keep track of notes on multiple runs (select multiple runs and parallelize reminders/notes about those?) or something more user-friendly.

**Additional context**
N/A

**Comment by ariG23498** [comment]
Hey @rodrigo-castellon 
The main motive for a `notes` sections in run, is to attach a small description to the run on the fly.
I think the best option for you would be our [Reports](https://docs.wandb.ai/reports). Here you can jot down points at your free will and also put up panels that you find insightful.
Hope this solves your problem 😄

**Comment by cvphelps** [comment]
@rodrigo-castellon did you try reports?

**Comment by rodrigo-castellon** [comment]
Yep, thanks for the help!
