### ISSUE TITLE
[Feature] Sync time zone information with server

### ISSUE THREAD

**Issue by tshmak** [wandb/client#1940]
**Is your feature request related to a problem? Please describe.**
My local machine has a wrong time-zone config. So when I ran wandb, the run was registered on the wandb server as running x hours ago, whereas it should only be a few seconds. 

**Describe the solution you'd like**
I think this issue can be solved by syncing not only the time but also the time-zone (absolute time?) with the server. I suppose this will also be useful for people who collaborate internationally. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ariG23498** [comment]
Hey @tshmak 
Thank you for the feature request.

**Comment by ariG23498** [comment]
Hey @tshmak 
We have incorporated the feature request in our UI.
![image](https://user-images.githubusercontent.com/36856589/111108058-159e4700-857e-11eb-8d32-0af558607ed9.png)
The `updated` and the `end time` fields give us the **absolute-time**. Hope this helps 😄
