### ISSUE TITLE
[Feature] Also display corresponding value of x-axis along with y-axis.

### ISSUE THREAD

**Issue by seanswyi** [wandb/client#1945]
**Is your feature request related to a problem? Please describe.**
My request isn't related to a problem, rather I thought it'd be convenient if the value of the x-axis (e.g., step number) would also be displayed along with the y-axis value (e.g., F1 score) on the dashboard. It's convenient that the values of the y-axis are displayed as you move along the chart, but sometimes I'd like to know at what step that value was there.

**Describe alternatives you've considered**
I'm currently saving the best score and corresponding epoch/step so that I print that at the end of the process.

**Comment by lukas** [comment]
Could you post a screenshot of what you mean - in my basic graph the x-axis values show up:

![image](https://user-images.githubusercontent.com/29/110709873-c937bd80-81b1-11eb-90f2-a801c06c898a.png)

**Comment by seanswyi** [comment]
Sure, I should have been more explicit in my original post. The x-axis itself also shows for me as well, but what I was referring to is something like this:
![wandb_feature_request](https://user-images.githubusercontent.com/20367759/110715261-3a29b480-8248-11eb-9017-ac4e755608fd.png)

I'm not sure if you can see it, but I edited in a "Step: 130,302" on top of the y-axis values (it's supposed to be inside the box).

Perhaps it may be a bit verbose/unnecessary, but I thought that it'd be convenient if this were also displayed so that we can quickly find which step corresponds to which score.

**Comment by seanswyi** [comment]
Oh, I didn't realize that was the value until now. Seems like a misunderstanding on my part. Thanks for the clarification, I'll close this issue.
