### ISSUE TITLE
Logging 'reward_mean' does not log it... weird

### ISSUE THREAD

**Issue by drozzy** [wandb/client#1950]
If I try to log a dict with a key `reward_mean` it does not go though (i.e. wandb graph is empty).
However, if I change the key name to `reward_meaaaan` - it works!
```
wandb.log({'reward_std': std, 'reward_mean': mean})
```

<img width="1082" alt="Screen Shot 2021-03-11 at 9 56 57 PM" src="https://user-images.githubusercontent.com/140710/110885355-b3f78780-82b4-11eb-8e48-e1ffe32e9df4.png">

**Comment by ariG23498** [comment]
Hey @drozzy 
I tried a simple implementation:
```python
run = wandb.init(entity="xxx", project="xxx")
with run:
    for _ in range(1000):
        num = 0
        for _ in range(100):
            num = num + random.randint(1,10)
        avg = num / 100
        run.log({"reward_mean":avg, "reward_meaaaan":avg})
```

I did not find any problem with the UI
![image](https://user-images.githubusercontent.com/36856589/110964813-9b04da00-8379-11eb-9a61-bb59b9ba2c33.png)

**Comment by drozzy** [comment]
Oh ok. Thanks for checking it out. Weird. I'll let you know if it happens again.
