### ISSUE TITLE
[Q] how to resume other data from the previous training?

### ISSUE THREAD

**Issue by cs123951** [wandb/client#1961]
Hi,  

I trained and saved a model under the directory "offline-run-20210316_100104-2ywaztas", I know the id is 2ywaztas.
The directory "offline-run-20210316_100104-2ywaztas" also includes other logs.

Now I want to resume the training process, so I used:
```
id="2ywaztas"
wandb.init(id=id, resume="allow")
weights = torch.load(os.path.join(wandb.run.dir, "model-latest.pth"))
```

Error happened in the last line:
`FileNotFoundError: [Errno 2] No such file or directory: '/folder/wandb/offline-run-20210316_111531-2ywaztas/files/model-latest.pth'
`

I think maybe it is related to the wandb.run.dir. It automatically creates a new folder `offline-run-20210316_111531-2ywaztas` rather than resuming `offline-run-20210316_100104-2ywaztas` .

My requirement is to recover all the data that is generated by the previous training,  such as the saved loss.

Could you help me?

By the way, when I call `wandb.log({'loss':loss})`, where do the log files store?

Thanks a lot.

**Comment by vanpelt** [comment]
The data is stored in the wandb file within the `offline-run-20210316_111531-2ywaztas` directory.  You can only access data that's been logged to a server.  You need to run `wandb sync NAME_OF_DIRECTORY` to send the data to a server.  If you resume a run from a server, you need to download the file before reading it with [wandb.restore("model-latest.pth")](https://github.com/wandb/client/blob/master/wandb/sdk/wandb_run.py#L2285).  This enables you to use cloud infrastructure and resume runs from different computers on your network.

**Comment by cs123951** [comment]
Thank you for your quick reply. 

Can I set the current training directory to be the previous one?  That is offline-run-20210316_100104-2ywaztas.  Because I want the loss curve to be continued.  For example,  suppose that I have trained the model for 200 epochs.  Then I hope the new resumed losses can append to the previous losses. 

I think `wandb.restore("model-latest.pth")` can only restore model weights.  I want to resume the logs.

**Comment by cs123951** [comment]
Besides, when I run `wandb sync NAME_OF_DIRECTORY`, I got another error:
`wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '111531-2ywaztas' for key 'PRIMARY' (<Response [409]>)`
I have no idea how to solve this problem.

**Comment by vanpelt** [comment]
Hey @cs123951 specifying `id="2ywaztas"` and `resume="allow"` is what allows you to resume the logs.  The error you're seeing means the run is already synced.  Simply calling `wandb.log` after init will append logs to the previous run.  In the example above you tried to read the `model-latest.pth` file.  That file will not exist because we create a new directory when resuming.

If you just need to read logs from a previous run you can use our [public api](https://docs.wandb.ai/library/public-api-guide#export-metrics-from-a-single-run-to-a-csv-file).

**Comment by cs123951** [comment]
Thanks, I got it~
