### ISSUE TITLE
[Q] no custom x-axis (e.g. epoch) in report

### ISSUE THREAD

**Issue by timbmg** [wandb/client#1963]
I cannot select custom x-axis in the report (only step, wall time etc.). However, in the workspace I can chose different x-axis like epoch. Is this expected or am I doing something wrong?

**Comment by ariG23498** [comment]
Hey @timbmg 
I tried reproducing a similar scenario with the following code snippet
```python
run = wandb.init(entity="xxx", project="xxx")
with run:
    for i in range(100):
        run.log({"metrics":random.randint(1,10), "custom-x":i+10})
```

With this setup I can indeed query the `custom-x` parameter in the panel from reports and workspace.

A workaround for you would be to build the panel from the workspace (as you can query the custom x-axis there) and then move the panel to a report with the `Add to Report` button.
![image](https://user-images.githubusercontent.com/36856589/111482228-b432cf80-8759-11eb-9b26-d8a5c81ee4a2.png)

**Comment by vanpelt** [comment]
Hey @timbmg can you share a link to the workspace?  It could be that we are only showing metrics that monotonically increase as options for your x-axis.
