### ISSUE TITLE
[CLI] Slow uploads of offline runs

### ISSUE THREAD

**Issue by nsidn98** [wandb/client#1972]
Since 16th March 2021, I have been having this issue of slow upload speeds for `wandb sync my_wand_folder` for the offline runs (takes around 2 hours for a 100 MB file) even if the internet speed is good enough for other stuff. I am not sure if this is a bug from the wandb side or if there is something wrong on my end.

**Environment**
- OS: Mac OS Mojave 10.14 (the one from where I am uploading the logs)
- Python Version: 3.6.10
- Wandb Version: 0.10.12

**Comment by vanpelt** [comment]
Can you share a link to an example run that took 2 hours?  Do you have tensorboard files in your run directory?  I as because that's the only thing that's changed with sync recently.

**Comment by nsidn98** [comment]
Yes there are tensorboard files in that directory. I am using `torch.utils.tensorboard.SummaryWriter` with `sync_tensorboard=True`. Shall I send you the log files via email as a drive/dropbox link?

**Comment by vanpelt** [comment]
If you can create a tarball or zip of one of the run directories and send it my way that would be really helpful!  My email is vanpelt@wandb.com

**Comment by nsidn98** [comment]
Sent the logs via email. It would be great if I could get an update here once this is resolved because I do have a lot of logs to upload on the wandboard!

**Comment by vanpelt** [comment]
Hey @nsidn98 I found the root cause and just pushed a patch.  Hopefully this goes out in the next release, but you can install from this branch now:

```bash
pip install --upgrade git+git://github.com/wandb/client.git@feature/sync-speed#egg=wandb 
```

**Comment by nsidn98** [comment]
Thanks a lot for the patch @vanpelt. Do I have to install this patch in both systems (the one where I am running the experiment and the one from where I am uploading the logs) or just one is sufficient?

**Comment by vanpelt** [comment]
Just the one you're running `wandb sync` from!

**Comment by nsidn98** [comment]
Thanks a lot for the fix, it worked!

**Comment by raubitsj** [comment]
This will be released in 0.10.23

**Comment by savvaki** [comment]
Hi @vanpelt, I am also getting very slow sync speeds of offline runs with wandb version 0.12.9. I didn't want to create a new issue. May I share my experiment folder and perhaps you can investigate? My machine has 100Mbps upload speed so that is not the issue. The `wandb sync <folder_name>` command stays on `Syncing: https://wandb.ai/my_url` for a long period of time. The sync does eventually finish but after an unusual amount of time. I have noticed that if I look at the wandb web client that the files are there quite early, the sync just takes a long period of time to finish.

**Comment by vanpelt** [comment]
Hey @savvaki are you able to share one of the folders you're trying to sync with me?  You could send a zip or tarball to vanpelt@wandb.com so we can reproduce the slowness on our end.

**Comment by savvaki** [comment]
@vanpelt I have sent you an email. Thank you!

**Comment by yangze68** [comment]
> Hi @vanpelt, I am also getting very slow sync speeds of offline runs with wandb version 0.12.9. I didn't want to create a new issue. May I share my experiment folder and perhaps you can investigate? My machine has 100Mbps upload speed so that is not the issue. The `wandb sync <folder_name>` command stays on `Syncing: https://wandb.ai/my_url` for a long period of time. The sync does eventually finish but after an unusual amount of time. I have noticed that if I look at the wandb web client that the files are there quite early, the sync just takes a long period of time to finish.

I encountered the same issue when I uploaded my offline file by `wandb sync --sync-all`. My wandb version is also 0.12.9. Could I share the uploaded folder with you? Thank you very much

**Comment by yuvalarbel** [comment]
Hey! This is happening for me as well. Around 6 hours for a 35 MB run log file. Internet speed is fine. What can I do? Thanks!

**Comment by lkfo415579** [comment]
Why the sync command takes so long? My wand version is 0.21.0.
