### ISSUE TITLE
Automatic login when using Colab

### ISSUE THREAD

**Issue by vasudevgupta7** [wandb/client#1983]
**Is your feature request related to a problem? Please describe.**
When using `wandb` with Google Colab, we need to login with `wandb key` each time we run a session and will have to delete key if sharing Colab file with others.

**Describe the solution you'd like**
It would be great if wandb will automatically login to Colab (may be possible if connect gmail id and wandb somehow). But not sure if it's possible.

**Describe alternatives you've considered**
Allow us to login with wandb password instead of key (since we can't memorise & fill while copy/pasting key is frustrating.

**Comment by cvphelps** [comment]
@vasudevgupta7 if you're logged in to wandb.ai in your browser, Colab auto-logs in. Don't run wandb.login() and you won't get prompted for an API key — you can go directly to wandb.init()

**Comment by vasudevgupta7** [comment]
Thanks a lot! I didn't know that earlier.
