### ISSUE TITLE
[Q] Local controller - stopping a sweep

### ISSUE THREAD

**Issue by carloalbertobarbano** [wandb/client#1987]
I am configuring a local controller to orchestrate my sweeps. However, I cannot find a way to stop the sweep through the python API.

```python
sweep = wandb.controller(sweep_id)
while not sweep.done():
    sweep.print_status()
    sweep.step()
    time.sleep(1)

    if len(sweep._sweep_runs) >= 10:
        print('Reached 10 runs, stopping')
        # sweep.stop() ?
```

How can I achieve that?

**Comment by ariG23498** [comment]
Hey @carloalbertobarbano 
We are working on stopping sweeps programmatically. We will update the thread as we come up with the feature. CC: @farizrahman4u

**Comment by carloalbertobarbano** [comment]
Hi, is there any update regarding this issue? Also, being able to configure a maximum number of runs for a sweep (without a local controller) could be a useful solution

**Comment by carloalbertobarbano** [comment]
Great, looking forward for the next release! Thanks

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
