### ISSUE TITLE
[CLI] URGENT! The Network Bytes Transfer Leak

### ISSUE THREAD

**Issue by vwxyzjn** [wandb/client#1988]
**Description**

In the latest version of `wandb=0.10.22`, the Network Bytes transferred and received appears to increase drastically compared to a previous version `wandb=0.9.5` that I had been using. See [this report](https://wandb.ai/costa-huang/cleanRL/reports/Network-Bytes--Vmlldzo1NDY2ODg) for an example.

![image](https://user-images.githubusercontent.com/5555347/111883652-1a566700-8993-11eb-9494-89ba93482433.png)

I have started upgrading `wandb` to the latest version a couple of days ago and start running experiments on AWS as usual. As shown in the figure above, the network transfer for the latest `wandb` version is several magnitudes higher (about 100x more bytes transferred) than that of the older version. This issue unfortunately is URGENT and has a devastating effect on running on cloud providers that charge for data transfer such as AWS. As shown in the figure below, the EC2 costs have increased 10-15x due to the `DataTransfer-Out-Bytes`, costing thousands of dollars more on the same workload (about 28 concurrent experiments overnight).

![Screenshot from 2021-03-20 15-36-19](https://user-images.githubusercontent.com/5555347/111883715-76b98680-8993-11eb-9d6c-b080820dfaab.png)

**How to reproduce**
1. Download the [source code] (https://wandb.ai/costa-huang/cleanRL/runs/1vq7p5se/code?workspace=user-costa-huang) 
2. Install the [`requirements.txt`](https://wandb.ai/costa-huang/cleanRL/runs/1sqc9tyg/files/requirements.txt)
3. And just run with `python sdqn_atari.py`
4. Then install `wandb==0.9.5`, and run the same script by `python sdqn_atari.py`
5. On the report page, select those two experiments and compare the network transfer

**Environment**
- OS: Linux
- Environment: my own machine and on AWS
- Python Version: 3.8.8 (see the report)

**Comment by vwxyzjn** [comment]
Looks like this is a problem with syncing tensorboard. Setting `wandb.tensorboard.patch(save=False)` seems to reduce the data transfer significantly.

```
    import wandb
    wandb.init(
        project=args.wandb_project_name, entity=args.wandb_entity, 
        # sync_tensorboard=True,
        config=vars(args), name=experiment_name, 
        monitor_gym=True, save_code=True
    )
    wandb.tensorboard.patch(save=False)
```

**Comment by vwxyzjn** [comment]
Looks like this is not a problem with tensorboard specifically, but has to do with how files are synced in general. Had I recorded video through the gym interface (`monitor_gym=True`), the data transfer also explodes. Hmmm

**Comment by vwxyzjn** [comment]
Went through the `debug-internal.log` and `debug.log` and found a couple more things. It seems the problem is with the [`PolicyLive`](https://github.com/wandb/client/blob/f61308eac133b8aeb1eadf81e1412d544a297a42/wandb/filesync/dir_watcher.py#L84). Every run with the following debugging output seems to eventually blow up the data transfer.

```
saving file agent.pt with policy live
```


Given the same workload, this is the network usage of `wandb==0.10.22`

![image](https://user-images.githubusercontent.com/5555347/111917271-7d103700-8a55-11eb-8ffc-0e6c5972133b.png)


This is the network usage of the `wandb==0.9.5`:

![image](https://user-images.githubusercontent.com/5555347/111917166-dc217c00-8a54-11eb-937c-cd8c24602b0c.png)



My suspicion is that whenever a file is saved with that `PolicyLive`, it seems the client will try to upload it immediately once it was uploaded, resulting in the 15MB/s data sent. This means even if only the tensorboard files are saved, as they grow larger, the data transfer will explode. So is the case with any sort of file saving. In the earlier version of `0.9.5`, however, it seems regardless of how many files there were to be saved, the uploading speed was capped at 200 KB/s data sent.

**Comment by vanpelt** [comment]
Hey @vwxyzjn sorry to hear you're seeing such a large difference between these versions, I want to help get to the bottom of this ASAP.

The logic for PolicyLive should be the same in 0.9.x and 0.10.x.   PolicyLive which is what we use for tensorboard event files or any files that match calls to `wandb.save` will upload the file [atmost once every 15 seconds if the file changes](https://github.com/wandb/client/blob/master/wandb/filesync/dir_watcher.py#L84).  

There were changes to how we sync stdout / stderr between 0.9.x and 0.10.x.  Can you try running a job with `wandb.init(..., settings=wandb.Settings(console="off"))` and see if that changes anything?  Are you able to provide a sample script and the methodology you used to capture these stats?

**Comment by vwxyzjn** [comment]
Thanks for the prompt reply. I really appreciate your help. Below is a minimal script that I came up with the reproduce the data transfer issue:

```python
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.distributions.categorical import Categorical
from torch.utils.tensorboard import SummaryWriter
import wandb
import time
import random
import os

experiment_name = "test"+str(int(time.time()))

run = wandb.init(project="cleanRL", entity=None, 
                 sync_tensorboard=True, name=experiment_name, 
                 monitor_gym=True, 
                 save_code=True)

class Agent(nn.Module):
    def __init__(self, mapsize=16*16):
        super(Agent, self).__init__()
        self.mapsize = mapsize
        self.network = nn.Sequential(
            nn.Conv2d(27, 16, kernel_size=3, stride=2),
            nn.ReLU(),
            nn.Conv2d(16, 32, kernel_size=2),
            nn.ReLU(),
            nn.Flatten(),
            nn.Linear(32*6*6, 256),
            nn.ReLU(),)
        self.actor = nn.Linear(256, self.mapsize*78)
        self.critic = nn.Linear(256, 1)

    def forward(self, x):
        return self.network(x.permute((0, 3, 1, 2))) # "bhwc" -> "bchw"

device = torch.device('cpu')
agent = Agent().to(device)
optimizer = optim.Adam(agent.parameters())
writer = SummaryWriter(f"/tmp/{experiment_name}")
for i in range(20000):
    time.sleep(0.1)
    loss = agent.forward(torch.rand(4, 16,16, 27)).mean()
    optimizer.zero_grad()
    loss.backward()
    writer.add_scalar(f"test", loss.item(), i)
    print(i, loss.item())
    nn.utils.clip_grad_norm_(agent.parameters(), 0.5)
    optimizer.step()
    if not os.path.exists(f"models/{experiment_name}"):
        os.makedirs(f"models/{experiment_name}")
        torch.save(agent.state_dict(), f"models/{experiment_name}/agent.pt")
        wandb.save(f"models/{experiment_name}/agent.pt")
    else:
        torch.save(agent.state_dict(), f"models/{experiment_name}/agent.pt")
```

As shown in the following screenshot, the 


![image](https://user-images.githubusercontent.com/5555347/111929741-a2b93280-8a8d-11eb-81da-88e16c18a2f9.png)

And adding `settings=wandb.Settings(console="off"))` also does not help. See

![image](https://user-images.githubusercontent.com/5555347/111929875-f9267100-8a8d-11eb-97d2-12aea09f3c42.png)


In comparison, `wandb==0.9.5` does not have this issue.

![image](https://user-images.githubusercontent.com/5555347/111929987-43a7ed80-8a8e-11eb-88f2-057286c05293.png)

**Comment by vanpelt** [comment]
Thanks @vwxyzjn For now, let's change the your call to `wandb.save` and make it `wandb.save(f"models/{experiment_name}/agent.pt", policy="end")` and see if that fixes things.  We're still digging into the root cause of the difference between the versions.

**Comment by Bam4d** [comment]
Additionally its possible that this problem is accellerated when there are multiple runs in progress (these are all on different nodes)
![image](https://user-images.githubusercontent.com/1370765/112031697-87086780-8b33-11eb-938b-a69f230eaac3.png)

**Comment by vanpelt** [comment]
@Bam4d I @vwxyzjn reports are related to upload traffic.  Your report seems connected to download traffic.  Can you share code that's causing the increase in downstream traffic?

**Comment by vwxyzjn** [comment]
@vanpelt I can confirm on my end `wandb.save(f"models/{experiment_name}/agent.pt", policy="end")` fixes the data transfer temporarily. 

> The logic for PolicyLive should be the same in 0.9.x and 0.10.x. PolicyLive which is what we use for tensorboard event files or any files that match calls to wandb.save will upload the file atmost once every 15 seconds if the file changes.

Btw I tested it and it seems in `0.9.5` the 21 MB model file are uploaded every 80 seconds or so, while in the `0.10.22` the model file is uploaded every second.

**Comment by vwxyzjn** [comment]
Thanks so much for looking into it @vanpelt. I don't know if it is related, but it seems some 0.10.22 runs are missing requirements.txt like https://wandb.ai/costa-huang/cleanRL/runs/27d439rk/files, whereas the 0.9.5 runs almost always store the `requirements.txt`.

**Comment by vanpelt** [comment]
Thanks @vwxyzjn I'm really glad it's working now, we're going to prioritize a fix to ensure we don't save files in "live" mode so frequently.

I have runs with the latest version of the cli that contain requirements.txt, I'm not sure what's going on with your runs.  Can you send the `debug-internal.log` from one of the runs that isn't saving `requirements.txt`?

**Comment by vwxyzjn** [comment]
Thank you!

https://gist.github.com/vwxyzjn/ea9519a94c4469ad252fc1064aa94b2b, with corresponding run https://wandb.ai/costa-huang/cleanRL/runs/3c9rycrc/files?workspace=user-costa-huang. In comparison, the `requirements.txt` is present for https://wandb.ai/costa-huang/cleanRL/runs/3kymam3z/files. In both cases, I crash the process, which seems to make a difference.

I think what happens is if the process crashed, then the `requirements.txt` is not saved. You can reproduce this by simply running the script in a terminal and then just force kill it. The real use case is when I run experiments using preemptible instances, they usually crash as well, so resulting in the requirements.txt not saved.

I think in the earlier version of 0.9.5, the `requirements.txt` is saved right in the beginning instead of the end like the latest version.

**Comment by vwxyzjn** [comment]
Hi @vanpelt, I have tried to use `wandb==0.10.24` that seems to have fixed the frequent uploading issue. Thank you for the fix and I am closing the issue for now.

**Comment by chaitanya100100** [comment]
@vanpelt 
I am facing a similar issue. Within 2-3 minutes of the run, 'sent' and 'received' shows 500MB and 2GB respectively. And my wandb setup is increadibly simple. I am using only these wandb functions.
```
wandb.init(project='proj_name', name='exp_name', entity="username", dir='<exp_log_directory>')
wandb.config.update(<argparse_config>)

wandb.log({key: value}, step=itr_num)   # storing loss periodically
```
Total stdout log file doesn't exceed 2MB. I am not using wandb for any kind of model saving or anything. Any help to resolve this issue will be greatly appreciated. (I have just started using wandb and it is great. But being a newbie, I don't know how to debug things yet.)


![image](https://user-images.githubusercontent.com/20864384/152277463-40a0e900-fe5a-4880-9b69-96ada7b514b6.png)

**Comment by armanhar** [comment]
Hey @chaitanya100100, which wandb version are you using? Could you send the debug logs for this run?

**Comment by vanpelt** [comment]
@chaitanya100100 our network traffic graphs monitor network usage on the entire machine you're running on.  Is it possible there was a different user or process on that machine that was consuming bandwidth?

**Comment by chaitanya100100** [comment]
Hello @armanhar @vanpelt ,

I am using wandb version 0.12.10 .
I am running that experiment on a cluster machine. So yes, it might be possible that other processes are using that bandwidth.
Let me try to test this on an isolated machine. I will post my findings here soon.

**Comment by armanhar** [comment]
@chaitanya100100 Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
