### ISSUE TITLE
Remove slider from image widget

### ISSUE THREAD

**Issue by vanpelt** [wandb/client#199]
Let's use react-slick to make the images scroll across all epochs and get rid of the slider.  As we scroll to a new epoch, let's display the epoch number as happens now.  On page load we should always start the scroll on the most recent epoch instead of epoch 0.

**Comment by thekatic** [comment]
@vanpelt here is the [update](https://github.com/wandb/core/pull/324) on image widget. Let me know what do you think about UX and how the images are listed in slick slider.
