### ISSUE TITLE
[CLI] typo in wandb.sweeps.config.hyperopt.hy.loguniform function

### ISSUE THREAD

**Issue by nw13slx** [wandb/client#1993]
Hyperopt with loguniform distribution will file `Invalid sweep config: TypeError: 'NoneType' object is not callable` error.

The bug can be reproduced with the code below
```
import wandb
from wandb.sweeps.config import tune
from wandb.sweeps.config.tune.suggest.hyperopt import HyperOptSearch
from wandb.sweeps.config.hyperopt import hp

tune_config = tune.run(
    "train.py",
    search_alg=HyperOptSearch(
        dict(
            learning_rate=hp.loguniform(1e-6, 1e-2, 10),
        ),
        metric="validation_loss",
        mode="min",
    ),
    num_samples=4
)
# Create the sweep
wandb.sweep(tune_config)
```

Fix:
https://github.com/wandb/client/blob/13489f1fed731725a28ca46bfcf2d3494f124863/wandb/sweeps/config/hyperopt/hp.py#L23

should be
```
return self._config("hp.loguniform", [], local_args) 
```

**Comment by ariG23498** [comment]
Hey @nw13slx 
Thanks for the ticket. We will be looking into it.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
