### ISSUE TITLE
Get "AssertionError: can only test a child process" when using distributed TPU cores via Pytorch Lightning [CLI] 

### ISSUE THREAD

**Issue by adamDhalla** [wandb/client#1994]
Hi All, 

Having an error being thrown at me when trying to log my metrics and hyperparameters on W&B via PyTorch Lightning whilst running on 8 TPU cores. 

I first initialize the Weights and Biases run and project using the Lightning  `WandbLogger`  class, which practically runs wandb.init(). That goes fine.  But then, I run the `Trainer` on 8 TPU cores, and with keyword argument 'logger=my_WandbLogger', I get the error `AssertionError: can only test a child process`. 

![image](https://user-images.githubusercontent.com/69402866/112093360-8208df80-8b56-11eb-9988-7f35f80a1b45.png)

Note that I tried this on a single TPU core, and that went fine and dandy. So it seems to be a problem with the distributive processing part of things. 

**How to reproduce**
This isn't my code, but someone had the same issue a while back, although I couldn't find their solution. It's done using the bug-reproducer template ('The Boring Model') that Pytorch Lightning uses. Reproduction[ HERE.](https://forums.pytorchlightning.ai/t/tpu-failures-in-colab/310)

I'm running things on Google Colab, with Pytorch Lighting version 1.2.4 (most recent) and W&B version 0.10.22 (one version behind the latest version). 

Here's the full error stack trace if you're curious
```
GPU available: False, used: False
TPU available: True, using: 8 TPU cores
---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
<ipython-input-28-6650dc1eec9a> in <module>()
      3 wbLogger = WandbLogger(project='HPA Protein Localization Single Class Subset', name='Adam-128-0.001')
      4 trainer = Trainer(logger=wbLogger, deterministic=True, tpu_cores=8, max_epochs=epochNum, replace_sampler_ddp=False)
----> 5 trainer.fit(model, trainDL, valDL)
      6 
      7 print(time.time() - t0)

6 frames
/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    148         msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    149         msg += original_trace
--> 150         raise ProcessRaisedException(msg, error_index, failed_process.pid)
    151 
    152 

ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 100, in new_write
    cb(name, data)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 187, in publish_output
    self._publish_output(o)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 192, in _publish_output
    self._publish(rec)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 517, in _publish
    if self._process and not self._process.is_alive():
  File "/usr/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py", line 83, in new_process
    seed_everything(int(seed))
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/seed.py", line 54, in seed_everything
    log.info(f"Global seed set to {seed}")
  File "/usr/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1033, in emit
    self.handleError(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 946, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 100, in new_write
    cb(name, data)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 187, in publish_output
    self._publish_output(o)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 192, in _publish_output
    self._publish(rec)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 517, in _publish
    if self._process and not self._process.is_alive():
  File "/usr/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 334, in _mp_start_fn
    file=sys.stderr)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 100, in new_write
    cb(name, data)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 187, in publish_output
    self._publish_output(o)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 192, in _publish_output
    self._publish(rec)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 517, in _publish
    if self._process and not self._process.is_alive():
  File "/usr/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```

I'm wondering if there are any temporary workarounds for now since I need to find a way to connect and things are a bit time-sensitive!

**Comment by raubitsj** [comment]
@adamDhalla,
We are looking into this issue now.  We have some documentation and fixes related to DDP and multiprocess use that we are working on.

I am trying to reproduce the error, but for (based on that exception) i suggest a temporary workaround of turning the console logging off, Using env variable: `WANDB_CONSOLE=off`

**Comment by prash-p** [comment]
I'm having the same error. I found another issue reported here, and this comment helped me fix the issue temporarily: https://github.com/huggingface/datasets/issues/847#issuecomment-770744567

**Comment by adamDhalla** [comment]
> @adamDhalla,
> We are looking into this issue now. We have some documentation and fixes related to DDP and multiprocess use that we are working on.
> 
> I am trying to reproduce the error, but for now (based on that exception) i suggest a temporary workaround of turning the console logging off, Using env variable: `WANDB_CONSOLE=off`

Thanks! but - 
I tried doing that - doing `WANDB_CONSOLE='off'` (I assumed putting 'off' as a string since it doesn't work the other way?). I put it right above the definition of the wandb.init(). I still got the exact same error :(.

**Comment by adamDhalla** [comment]
> I'm having the same error. I found this issue reported on the huggingface page, and this comment helped me fix the issue temporarily: [huggingface/datasets#847 (comment)](https://github.com/huggingface/datasets/issues/847#issuecomment-770744567)

I'm guessing that means setting the environment variable `WAND_DISABLE=True` (setting to capital T for Python boolean)? I tried that too, right above the definition of the init(), and it also didn't seem to work - I got the same error!

**Comment by adamDhalla** [comment]
@raubitsj @prash-p I didn't write test these at the same time but just including them both in a screenshot so you can see if I messed up on any of the assumptions of the spellings of things: 
![image](https://user-images.githubusercontent.com/69402866/112261173-8e5d6d00-8c28-11eb-96d1-9c0b74ad96a4.png)

If these implementations are correct, sadly they both (independently) did not solve the problem :((

**Comment by borisdayma** [comment]
You need to use `os.environ['WANDB_CONSOLE''] = 'off'`

**Comment by prash-p** [comment]
@adamDhalla I didn't use `WANDB_CONSOLE`=`off`. What worked for me instead was commenting out lines 517 and 518 in `site-packages/wandb/sdk/interface/interface.py` :
```python
    def _publish(self, record: pb.Record, local: bool = None) -> None:
        #if self._process and not self._process.is_alive():
        #    raise Exception("The wandb backend process has shutdown")
        if local:
            record.control.local = local
        if self.record_q:
            self.record_q.put(record)
```

**Comment by raubitsj** [comment]
@prash-p 
Those lines are a safety check to make sure that the process that is storing console output is the process we are expecting, in this case it isn't (and we dont fully understand why)

Removing that check should be fine in the case of console output, but for other types of data, the code is trying to prevent a use case we haven't fully tested yet and which could lead to corrupted or incomplete data which we want to avoid.

We are still having trouble reproducing this failure so we can provide a safe workaround (and get the fix into a release ASAP)

**Comment by adamDhalla** [comment]
@borisdayma oh god yeah of course! Don't know what I was thinking. Still kind of a coding noob, but thank you.

**Comment by prash-p** [comment]
@raubitsj If it helps, I had this error when running my script as a notebook in vscode, using tqdm on my pytorch Dataloader. The exact same script ran without errors when running from the command line.

**Comment by adamDhalla** [comment]
Any progress on this?

**Comment by khvmaths** [comment]
I encounter the same error, when training ViT with torch_xla using TPUs. Any progress?

**Comment by KyleGoyette** [comment]
Hi @khvmaths and @adamDhalla we're working on a solution. This may require changes to the wandb logger in Pytorch-Lightning, which could take a couple weeks to get a release out. We'll let you folks know here when a branch is ready

**Comment by prikmm** [comment]
@KyleGoyette Hii, any progress on this issue? I didn't use pytorch-lightning. I got this issue while using transformers and pytorch-xla.

**Comment by KyleGoyette** [comment]
@prikmm Either the next release or the release after will have a new experimental mode of running that supports this case.

**Comment by sdmengxiangyu** [comment]
> @raubitsj If it helps, I had this error when running my script as a notebook in vscode, using tqdm on my pytorch Dataloader. The exact same script ran without errors when running from the command line.

I also have this error when using tqdm on my pytorch dataloader

**Comment by R0bk** [comment]
Hey, I've still got this issue training on TPUs with torch XLA.

**Comment by shaunster0** [comment]
I'm still getting this issue, using pytorch-lightninig in jupyter-lab ... any updates?

**Comment by Malachyiii** [comment]
Still getting this issue in Kaggle notebooks when using pytorch,

**Comment by andreimargeloiu** [comment]
Thumbs up, same issue.

**Comment by kptkin** [comment]
Hi and thanks for reporting this issue.
 
We are currently working on improvements to our multiprocessing and was wondering if you would be interested in trying it out. The new logic should be more robust and allow more flexibility when using multiprocessing with `wandb`.

In case you are interested in trying it out, see this link: https://github.com/wandb/client/blob/master/docs/dev/wandb-service-user.md

One thing to note is that this is still experimental, and although we did testing it is still developed and improved all the time.

**Comment by borisdayma** [comment]
Hi, we just introduced a tentative fix.
Could you update Pytorch Lightning from master branch and install the most recent version of wandb?

```bash
pip install --upgrade wandb
pip install --upgrade git+https://github.com/PytorchLightning/pytorch-lightning.git
```

**Comment by sreuvers** [comment]
> 

This unfortunately does not work for me, still getting the error

**Comment by tsuga** [comment]
I still have the same issue on Colab.
wandb: 0.12.11
pytorch lightning: 1.6.0dev

Colab reproducible code is 
https://colab.research.google.com/drive/1bH8tpR5U7SalfQpbPNVHABh3lSNjt9s9?usp=sharing

**Comment by borisdayma** [comment]
Looks like it works if you comment `wandb.login()`.

@raubitsj is it possible that this somehow prevents the `wandb.require("service")`?

**Comment by leoleoasd** [comment]
Hi @borisdayma I met the same problem with `torch.multiprocessing`.
The minimal reproduction codeis https://gist.github.com/leoleoasd/5d8dd5e1cec5bb2822656e66ede55c55

**Comment by borisdayma** [comment]
@leoleoasd I think you can just add `wandb.require("service")` at the top of your script.

**Comment by kptkin** [comment]
@zplizzi glad to hear that this solved your issue. Btw we have a pre-release where we have service activated by default if you want to try it out: https://docs.wandb.ai/guides/track/advanced/distributed-training#wandb-service-beta

**Comment by MoAKgit** [comment]
Hi, I got the same issue, using Pytorch Lightning in Google Colab!
