### ISSUE TITLE
[Feature] Add support for running Wandb inside of a celery task

### ISSUE THREAD

**Issue by JohnnyC08** [wandb/client#2000]
**Is your feature request related to a problem? Please describe.**
I am building a system to trigger training jobs via celery. Out of the box. I was unable to use Wandb because celery would kill it as wandb is using multiprocessing under the hood and celery won't allow the spawning of a daemon process in a child process.

**Describe the solution you'd like**
I would love to have the solutions to easily configure which multiprocessing backend wandb can use. I actually monkey patched the backend import of multiprocessing in `wandb.sdk.backend.backend` to billiard and my celery job now runs with wandb. Below is how I did it:

```
import billiard
from wandb.sdk.backend import backend
backend.multiprocessing = billiard
```

I wouldn't mind submitting a PR for this and I want some guidance on how the team could see this implemented. The init method calls and creates a `_WandbInit` object. That object has an init method where the backend is set. We could possibly pass some sort of config or option into the first init method that would get passed to `_WandbInit`.

Thanks and tell me what you think!

**Comment by vanpelt** [comment]
You can set the WANDB_START_METHOD environment variable to "thread" to have us not use multiprocessing.

**Comment by JohnnyC08** [comment]
Wow that works! Thanks! Thanks for getting back to me and for your work on this amazing library. I will close the issue.
