### ISSUE TITLE
[App] Cannot select min/max values of log-scale parameters in parallel coordinates panel

### ISSUE THREAD

**Issue by abaisero** [wandb/client#2006]
**Describe the bug**
When I run a sweep over a parameter with discrete values, and I choose to view that value in a parallel coordinates panel using the log-scale, I cannot select the runs with the min/max value for that parameter.  This always happens when using log-scales, and never when using linear-scales.

**To Reproduce**
1. Create sweep with discrete parameter
2. In the sweep page, go to the parallel coordinates panel
3. Edit the panel and turn on "log-scale" for the parameter in question
4. Try to select the min or max value of that parameter by click and dragging over the appropriate section in the parallel coordinates panel.  Do this by dragging from inside the panel towards the outside of the panel, so that you exceed the actual min/max value.
5. The selection will fail and a "No runs selected" pop-up will appear.

**Expected behavior**
I expect that I would be able to select the runs which have the min or max value for that parameter.

**Screenshots**
This screenshot shows how I try to select the runs:  I draw from the inside towards the outside, and release when I am completely outside the panel.  As soon as I release the mouse, I get the "No runs selected" pop-up.

![image](https://user-images.githubusercontent.com/1794938/112762497-f10a8c00-8fcd-11eb-8a52-6340fee65e86.png)

**Operating System**
 - OS: Debian
 - Browser:  Firefox
 - Version: 85.0.1

**Comment by ariG23498** [comment]
Hey @abaisero 
I tried reproducing this issue. I did not find a problem when selecting the run in log scale as shown in the screenshot below 👇 
![image](https://user-images.githubusercontent.com/36856589/112811079-524b6180-9099-11eb-8c12-f0890854679c.png)

System config:
- OS: macOS Big Sur
- Browser: Chrome
- Version: 89.0.4389.90 (Official Build) (arm64)

> Could this be a problem with the web-browser?

**Comment by abaisero** [comment]
Same issue happens with me on 

* OS: Debian
* Browser: Google-Chrome
* Version: 88.0.4324.182 (Official Build) (64-bit).

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
