### ISSUE TITLE
[App] Plotly animation isn't playable

### ISSUE THREAD

**Issue by nicolas-dufour** [wandb/client#2014]
**Describe the bug**
When logging plotly animated chart, the animation is freezed to the first frame

**Expected behavior**
The plot should not be freezed to the first frame of the animation

**Screenshots**

**Operating System**
 - OS: windows
 - Browser: Chrome
 - Version: 22

**Comment by vanpelt** [comment]
Hey @nicolas-dufour can you provide some example code, a colab, or a screenshot of the issue?

**Comment by sydholl** [comment]
Because this ticket has gone stale, we are closing it. Please comment to reopen.

**Comment by lucabaroni** [comment]
Hello, 

I'm facing the same issue. Here is a code example with a screenshot: 

```
import wandb
import plotly.express as px
wandb.init(project="plot tests")

data = io.imread("https://github.com/scikit-image/skimage-tutorials/raw/main/images/cells.tif")
img = data[25:40]
fig = px.imshow(img, animation_frame=0, binary_string=True, labels=dict(animation_frame="slice"))
wandb.log({"example": fig})`
wandb.log({"experiment/example": wandb.data_types.Plotly(fig)})
wandb.finish()
```

![bug_wandb](https://user-images.githubusercontent.com/40238065/159667110-0041a9ca-2ee6-4e51-a72b-6c656ebf50f9.png)

When clicking on "play" the slider should move an the figure should update, but nothing happens. 
The same behavior is present both for both logs (i.e. logging directly `fig` or `wandb.data_types.Plotly(fig)` 
I tested the same figure on a notebook and the animation works, so I imagine that the issue in on the wandb side. 

The following might be related, but not necessarily: when using Plotly in vscode python interactive sessions I was observing a similar behaviour that was only solved by changing the default renderer of plotly

`pio.renderers.default = 'notebook'
`

**Comment by wtianyi** [comment]
This problem is still present in version 0.12.15
A plotly animation that plays in Jupyter Notebook (but not in VS Code), will not play in W&B.

A workaround is, to export the Ployly figure to HTML, and log the HTML content instead to W&B.

```python
# ... plotting code generating a Plotly figure `animation_fig`
animation_html_file = "animation_tmp.html"
animation_fig.write_html(animation_html_file, full_html=False)
with open(animation_html_file, "r") as f:
    animation_html = "\n".join(f.readlines())

wandb.log({
    "evaluate_animation": wandb.Html(animation_html, inject=False)
})
```

**Comment by shoham-elad** [comment]
still happens in v 0.16.0

workaround does not work in this version

**Comment by willleeney** [comment]
+ 1 still broken in  0.17.5

**Comment by b-d-e** [comment]
Any plans to support this without the workaround?

**Comment by jonasjuerss** [comment]
More than 4 years later, this still doesn't work. Are there any updates?

> A workaround is, to export the Ployly figure to HTML, and log the HTML content instead to W&B.
> ```python
> # ... plotting code generating a Plotly figure `animation_fig`
> animation_html_file = "animation_tmp.html"
> animation_fig.write_html(animation_html_file, full_html=False)
> with open(animation_html_file, "r") as f:
>     animation_html = "\n".join(f.readlines())
> 
> wandb.log({
>     "animation": wandb.Html(animation_html, inject=False)
> })
> ```

A shorter version that works for me is:

```python
wandb.log({
    "animation": wandb.Html(plotly.io.to_html(animation_fig))
})
```

Note, however, that converting to HTML tends to increase the file size by a factor of ~1k in my experience.

**Comment by fedj99** [comment]
Still an issue on `wandb` version `0.23.0`. HTML export workaround "works" but now my plots media takes up multiple hundreds of MB per run.
