### ISSUE TITLE
how to implement a binarized PR curve for multi-class label

### ISSUE THREAD

**Issue by enpassanty** [wandb/client#2018]
I'm using w&b to visualize results from experiments I'm running from simple transformers wrapper. It's a multi-class label. W&B displays PR curves by class but I need a binarized PR curve for the multi-class. any idea how to implement this? thanks

**Comment by vanpelt** [comment]
Hey @enpassanty you can use our [custom chart](https://docs.wandb.ai/app/features/custom-charts) functionality to create a vega spec for your use case.   You can likely [tweak](https://docs.wandb.ai/library/log#custom-presets) the existing vega spec.  You can also always manually log  a [matplotlib](https://docs.wandb.ai/library/log#matplotlib) or plotly chart.

**Comment by enpassanty** [comment]
thanks.  I was hoping for something canned.  I'll look into the custom chart docs.

**Comment by sydholl** [comment]
Because this issue has gone stale, we are closing it. Please comment to reopen.
