### ISSUE TITLE
[Q] NOAUTH Authentication required

### ISSUE THREAD

**Issue by chenshen03** [wandb/client#2021]
I ran wandb local and then got this error. I guess this should be a conflict between wandb and redis. 
How can I configure wandb so that it can access redis?

<img src="https://user-images.githubusercontent.com/20432947/113084347-682f6280-9210-11eb-9647-704ec9bbbb41.png" alt="image" style="zoom:50%;" />

**Comment by ariG23498** [comment]
Hey @chenshen03 
Thanks for the ticket.
Does the documentation for [authentical for wandb local](https://docs.wandb.ai/self-hosted/local#authentication) help you with this issue?

**Comment by vanpelt** [comment]
@chenshen03 currently our local instance doesn't support authenticated external redis.  You don't get many benefits by enabling external redis, I would just stick with our internally managed redis instance.

**Comment by chenshen03** [comment]
> @chenshen03 currently our local instance doesn't support authenticated external redis. You don't get many benefits by enabling external redis, I would just stick with our internally managed redis instance.

Thank you for your answer
