### ISSUE TITLE
wandb.sklearn.plot_summary_metrics Example

### ISSUE THREAD

**Issue by SteEcker** [wandb/client#2023]
Hi! Is the [visualization](https://wandb.ai/lavanyashukla/visualize-sklearn/reports/Visualize-Scikit-Models--Vmlldzo0ODIzNg) for scikit-learn models still supported?

In the example notebook the summary statistic variables are in the wrong order.

**To Reproduce**
The provided code `wandb.sklearn.plot_summary_metrics(model, X_train, X_test, y_train, y_test)` throws an error ("Expected 2D array, got 1D array instead:"). 

**Expected behavior**
Should it be `wandb.sklearn.plot_summary_metrics(model, X_train, y_train, X_test, y_test)` instead?

**Comment by cvphelps** [comment]
Hi @SteEcker thanks for reporting this, yes you're right that's the correct order!

**Comment by raubitsj** [comment]
From the code:
```
def plot_summary_metrics(model=None, X=None, y=None, X_test=None, y_test=None):
    """
    Logs the charts generated by summary_metrics in wandb.

    Should only be called with a fitted model (otherwise an error is thrown).

    Arguments:
        model (clf or reg): Takes in a fitted regressor or classifier.
        X (arr): Training set features.
        y (arr): Training set labels.
        X_test (arr): Test set features.
        y_test (arr): Test set labels.

    Returns:
        Nothing. To see plots, go to your W&B run page then expand the 'media' tab
              under 'auto visualizations'.

    Example:
        wandb.sklearn.plot_summary_metrics(model, X_train, y_train, X_test, y_test)
    """
    wandb.log({"summary_metrics": summary_metrics(model, X, y, X_test, y_test)})
```

**Comment by SteEcker** [comment]
Hi @cvphelps,, thanks for the quick reply!

Sorry if I am missing something obvious, but when I compare the output metrics from `wandb.sklearn.plot_summary_metrics()` with _manually_ logged metrics I get different results in my dashboard.  

Here is a small example of what I mean. I build a naive LR model and log the F1 score in two different ways.  

```
from sklearn import linear_model
from sklearn.metrics import f1_score
import wandb

wandb.init( project="my_project")

# Load data
# [...]

classifier = linear_model.LogisticRegression()

# Fit model
classifier.fit(X_train, y_train)

# Predict classes
y_pred = classifier.predict(X_test)

# wandb logs
wandb.sklearn.plot_summary_metrics(classifier, X_train, y_train, X_test, y_test)
wandb.log({'f1': f1_score(y_test, y_pred)})
```

Resulting in this dashboard output:


![Summary statistic output](https://user-images.githubusercontent.com/42510777/113470217-3575ac00-9454-11eb-8885-feef41ae0eb9.png)



![W B Chart 03_04_2021, 08 15 03](https://user-images.githubusercontent.com/42510777/113470285-bdf44c80-9454-11eb-8c07-90e6ff84714c.png)




I would expect the summary statistic F1 to also be around 0.1. 

OS: Windows 10 64bit
pyhton 3.9.2
wandb==0.10.24
scikit-learn==0.24.1

**Comment by morganmcg1** [comment]
@SteEcker potentially the difference is that `wandb.sklearn.plot_summary_metrics` uses a `weighted` f1 score, you can see it [on this line here](https://github.com/wandb/client/blob/b181d10f518d356555925be21ea71f1b0c5bebdb/wandb/sklearn/__init__.py#L241)

sklearn's default averaging uses `binary` (sklearn [f1 docs here](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html?highlight=f1_score#sklearn.metrics.f1_score))

You can see the difference between the 2 here:
```
f1 = f1_score(y_test, y_pred)
f1, round(f1, 2)
>>> (0.9089233347297864, 0.91)

wgt_f1 = f1_score(y_test, y_pred, average="weighted")
wgt_f1, round(wgt_f1, 2)
>>> (0.9032258064516129, 0.9)
```

[Full gist here](https://gist.github.com/morganmcg1/2217ab5c93ac1e42985f5a51a722a250) to replicate this

Let us know if you are still seeing a difference, and if so if you could share the dataset you're working with that would help us reproduce :)

**Comment by SteEcker** [comment]
@morganmcg1 You are correct. Thanks for the clarification!
