### ISSUE TITLE
[Q] Some runs in a sweep have crashed. How to fix?

### ISSUE THREAD

**Issue by EdwardJB** [wandb/client#2031]
Hi,

I'm running a sweep and a GPU problem caused several runs to show as "crashed" and "failed". After a reboot the sweep is running again, but those runs don't seem to have been redone. 

How can I make the sweep re-do those runs? I'm tempted to delete them from the sweep via the UI. Will that help?

Thanks.

**Comment by cvphelps** [comment]
Hi Edward, yes please delete those runs from the UI and keep running the sweep.

**Comment by EdwardJB** [comment]
Thanks!
