### ISSUE TITLE
[App] wandb: ERROR Error while calling W&B API: invalid project name t5_large_5/checkpoint-60000/, cannot contain character "/" (<Response [400]>)

### ISSUE THREAD

**Issue by puraminy** [wandb/client#2033]
**Describe the bug**
I used `simpletransformers` api and set the `project_name` to `model_name` which contained slash `/`. I logged in offline mode. Now that I want to sync the logs with wandb website it gives the following error for the name 

[App] wandb: ERROR Error while calling W&B API: invalid project name t5_large_5/checkpoint-60000/, cannot contain character "/" (<Response [400]>)
How can I fix the name?

**Comment by tyomhak** [comment]
Hey @puraminy , you can us the --project setting from here: https://docs.wandb.ai/ref/cli#wandb-sync

Your command would look something like this:

wandb sync --project='project_name'   run_folder_path
