### ISSUE TITLE
AttributeError ("'str' object has no attribute 'item'",) 

### ISSUE THREAD

**Issue by feyzazeynep** [wandb/client#2034]
**Description**
I get this error every time I try to tweak the BERT with W&B: AttributeError (`` object 'str' has no attribute 'element' '') ... whether it's your instance in Google Colab or your own tweaking experience own machine and dataset .
I am getting this error in Loss.item () statement. I've listened to your release suggestions, but still haven't found a solution.

**Environment**
- Environment: [e.g. Google Colab]

**Comment by tyomhak** [comment]
Hey @feyzazeynep , can you share the full stack trace?
Also, do you think you could share a minimal example colab that reproduces this issue?

**Comment by feyzazeynep** [comment]
> 
> 
> Hey @feyzazeynep , can you share the full stack trace?
> Also, do you think you could share a minimal example colab that reproduces this issue?

Hey @tyomhak, unfortunately I can't share because of company rules. I found a solution to this problem, I can share the solution.

**Comment by tyomhak** [comment]
@feyzazeynep I understand. If you could share the solution that would be great!

**Comment by sydholl** [comment]
@feyzazeynep we are closing this issue as it is solved. If you are able to share the solution, that would be very helpful!
