### ISSUE TITLE
[Feature] Including the autogenerated name for local checkpoints of our data.

### ISSUE THREAD

**Issue by somedadaism** [wandb/client#2035]
When I run wandb I get a local checkpoint of the run data ins the `wandb` directory.
The checkpoint looks like: `wandb/run-20210404_003352-qwxqi48r`
At the same time my checkpoint is uploaded to wandb and has a automatically generated name, e.g. `mild-spaceship-1`
Is there a way to automatically rename the local checkpoint to `wandb/run-mild-spaceship-1-20210404_003352-qwxqi48r`
I have looked into the `Settings` class but it was not obvious to me if it can be done.
If there is no easy way to do this at the moment I would propose to make it a feature.

**Comment by vanpelt** [comment]
Hey @somedadaism this is not supported.  You can create a symlink if you'd like after you've called `wandb.init`.  I'm curious what your specific use case is?  Why do you ever need to go back to that local directory after the run has completed?

```
import os
wandb.init(...)
os.symlink(wandb.run.dir, wandb.run.dir.replace(wandb.run.id, wandb.run.name))
```

**Comment by somedadaism** [comment]
I think the link between local wandb folder and in browser wandb is difficult to make.
Naming the local folders with the autogenerated names would make it easier to see what is what.

**Comment by ash0ts** [comment]
@somedadaism Hello! We have put this in as a feature request with the engineering team! We will update you/the documentation if this behavior is added to the application. In the meantime did the solution proposed by @vanpelt help with your use case? If not I would love to know what your use case is to provide more context for the team!

**Comment by ash0ts** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved!

**Comment by somedadaism** [comment]
Hi linking the directory has worked for me so far.

**Comment by ash0ts** [comment]
Hey @somedadaism I'm glad the linking proposed by vanpelt worked! I'll be closing this ticket and will update if the method for accessing local directory after a run has been changed.

**Comment by TrentBrick** [comment]
Any update on this?

**Comment by Legend94rz** [comment]
I really want this feature. @ash0ts 
Just like @amitabe mentioned, some files are large and it's not proper to log them to the server. Furthermore, even if the wandb server does support logging codes or other files, it might be more convenient to open them locally. At present, users are required to make some efforts to find out which local dir corresponds to the exp name on the server.
