### ISSUE TITLE
[Q] logged histogram on the dashboard page

### ISSUE THREAD

**Issue by santelelle** [wandb/client#2041]
Hi, 

I would like to show a histogram logged with `wandb.log(wandb.Histogram(mydata))` on the dashboard page so that I can compare it with other runs (the visualization I already get in each specific run page is correct with [x:iterations, y:bins]).

I spent some time trying without success, is there any way to achieve this?

**Comment by ariG23498** [comment]
Hey @santelelle 
I think you could do something like this for you task
```python
wandb.log({"hist": wandb.Histogram(mydata)})
```

This will sync a histogram of `mydata` and you will be able to compare the different histograms corresponding to the different runs.

Does this solve your problem?

**Comment by santelelle** [comment]
I close the issue as I solved the problem using a custom chart
