### ISSUE TITLE
[Feature] Multiple histograms [x: step, y:bin] on the same panel

### ISSUE THREAD

**Issue by santelelle** [wandb/client#2043]
**Problem:**
I would like to track how two distributions (positive and negative classifications over scores between -1 and 1) evolve during training

**Solution I'd like:**
It would be nice if it was possible to show both of them in the same histogram plot with [x:step, y:bin] with different colors.
This would be useful to check the overlap area between the two.
The plot would be exactly like the one already available in the run page, just with two different sets for the Y axis.

![image](https://user-images.githubusercontent.com/10034153/113748574-f15f0180-9708-11eb-9028-496a15ca11ec.png)
![image](https://user-images.githubusercontent.com/10034153/113749731-40f1fd00-970a-11eb-920c-8b869d5ecfaa.png)

**Comment by vanpelt** [comment]
Hey @santelelle you can create this manually using our [custom charts](https://docs.wandb.ai/app/features/custom-charts) functionality.

**Comment by santelelle** [comment]
I am using now the [custom chart](https://docs.wandb.ai/app/features/custom-charts) functionality and I am quite satisfied, but I did not figure out how to make the **plot interactive** with respect to the **"global step pointer"** (the cursor that you can move hovering with the mouse on any scalar chart and that get synced with all the other charts).

How can I access this from inside my custom chart?

PS: It would be really nice to be able to look at the vega-lite code of all the standard charts (the custom ones don't have all the features I would like to copy)

**Comment by KyleGoyette** [comment]
Unfortunately, custom charts does not currently support the global step pointer that is synced with all other charts. If you logged your charts across steps, but your chart is set up such that it shows the histogram for one step at a time, you can add a step selector to your chart by going to the "Other Settings" tab in your custom chart editor page:
![image](https://user-images.githubusercontent.com/13547142/114066266-64bf5b00-9850-11eb-94fc-80b09202c796.png)
Here you can add a step selector, afterwards you'll have a step selector available in the gear modal in your custom chart.

![image](https://user-images.githubusercontent.com/13547142/114066369-84568380-9850-11eb-877e-1df9a5315532.png)


Many of our charts are not made using Vega/Vega-lite, so we don't have specs for them. What features are you missing?

**Comment by santelelle** [comment]
Thanks for the quick answer! 
I've seen the option with the step selector and it does work for me, the sync would be amazing though.

As you correctly pointed out I would like to show one histogram at a time (screen attached). It would be really nice if I could update this while moving the cursor on the other plots.
Do you think this feature will be available in the near future?

PS: Are all the cursor hover functions not yet available? Because I also spent some time trying to get the single panel cursor working without success (a minimal example that runs on the original vega-lite editor)

![image](https://user-images.githubusercontent.com/10034153/114068162-e5f10f00-989d-11eb-91f9-1665683901d1.png)

**Comment by KyleGoyette** [comment]
I don't believe there are current plans for this feature at this time. I'm not sure what you mean by cursor hover functions. Our custom charts Line Plot, Scatter plot and AUC support hovering using vega-lite. As do our histogram and bar charts.

**Comment by santelelle** [comment]
Ok I got it working, 

I think the issue was the _params_ definition of vega-lite v5 I was using.

A minimal example that could be useful for someone, moving the cursor on x axis changes the visualized curve:
```vega-lite
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Interactive line selection",
  "data": {
    "values": [
      {"x": 0, "y": 0, "iteration": 0},
      {"x": 1, "y": 1, "iteration": 0},
      {"x": 2, "y": 4, "iteration": 0},
      {"x": 3, "y": 9, "iteration": 0},
      {"x": 0, "y": 1, "iteration": 1},
      {"x": 1, "y": 1, "iteration": 1},
      {"x": 2, "y": 1, "iteration": 1},
      {"x": 3, "y": 1, "iteration": 1}
    ]
  },
  "transform": [],
  "layer":[
    {
      "mark": "line",
      "transform": [{"filter": {"selection": "hover"}}],
      "encoding":{
        "x": {
          "field": "x",
          "type": "quantitative"
        },
        "y": {
          "field": "y",
          "type": "quantitative",
          "scale": {"domain":[0, 10]}
        }
      }
    },
    {
      "mark": "rule",
      "encoding":{
        "x": {
          "field": "iteration",
          "type": "nominal",
          "axis": {"ticks": false, "labelAngle": 0, "labelOverlap":true}
        },
        "opacity": {
          "condition": {
            "selection": "hover",
            "value": 0.3
          },
          "value": 0
        }
      },
      "selection": {
        "hover": {
            "type": "single",
            "fields": ["iteration"],
            "nearest": true,
            "init": {"iteration": 0},
            "on": "mouseover",
            "empty": "none"
        }
      }
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/10034153/114175642-741ad300-993a-11eb-93b3-fa6e3fec92fb.png)
![image](https://user-images.githubusercontent.com/10034153/114175653-79781d80-993a-11eb-95b2-424b6c00e22b.png)
