### ISSUE TITLE
[CLI] The live log graph is not shown when running jupyter notebook in vscode 

### ISSUE THREAD

**Issue by surfii3z** [wandb/client#2046]
**Description**
Thank you for the amazing software, I have been enjoying using wandb.

I want to show the logged graph locally in my jupyter notebook (.ipynb), so I follow this [example](https://docs.wandb.ai/integrations/jupyter). However, it would not show the plot but this instead.

![Screenshot from 2021-04-07 18-41-09](https://user-images.githubusercontent.com/38914643/113845824-d8ba1e80-97d0-11eb-90fc-8ad2f2c6d259.png)

**Wandb features**
I follow the code exactly from this [link](https://colab.research.google.com/drive/1XarrwLYCGmMUGBSe7eymzofIfSwytuKC?usp=sharing#scrollTo=SCfw64uGfUPs)

**How to reproduce**
1. Run this [jupyter notebook](https://colab.research.google.com/drive/1XarrwLYCGmMUGBSe7eymzofIfSwytuKC?usp=sharing#scrollTo=SCfw64uGfUPs)  in vscode

**Environment**
- OS: Ubuntu 18.04
- Environment: vscode
- Python Version: 3.8.8

PS. I am not sure if it's wandb issue or vscode issue

**Comment by surfii3z** [comment]
My guess is this line here is throwing the error:
https://github.com/wandb/client/blob/b181d10f518d356555925be21ea71f1b0c5bebdb/wandb/apis/internal_runqueue.py#L533

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-jupyter/issues/5430#issuecomment-815049169_

**Comment by surfii3z** [comment]
> My guess is this line here is throwing the error:
> 
> https://github.com/wandb/client/blob/b181d10f518d356555925be21ea71f1b0c5bebdb/wandb/apis/internal_runqueue.py#L533
> 
> _Originally posted by @rchiodo in [microsoft/vscode-jupyter#5430 (comment)](https://github.com/microsoft/vscode-jupyter/issues/5430#issuecomment-815049169)_

**Comment by vanpelt** [comment]
@surfii3z looking at your notebook I noticed calling `wandb.init` in a for loop.  Can you share why you were doing this?

This specific error is due to the way vscode serves iframes.  The `%%wandb` magic was meant to be used in a web browser where you're already logged into wandb.ai.  I'll look into ways to authenticate the iframe in vscode and update the ticket here.

**Comment by surfii3z** [comment]
> @surfii3z looking at your notebook I noticed calling `wandb.init` in a for loop. Can you share why you were doing this?
> 
> This specific error is due to the way vscode serves iframes. The `%%wandb` magic was meant to be used in a web browser where you're already logged into wandb.ai. I'll look into ways to authenticate the iframe in vscode and update the ticket here.

Hi Thank you for your quick help. In fact, the notebook is from official; wandb website and I also don't know why they do that.

By the way, when I run it locally, I removed the loop for wandb.init

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
