### ISSUE TITLE
How do you disable Weights and Biases?

### ISSUE THREAD

**Issue by shrijan00** [wandb/client#2048]
Hi,
I recently started using WandB. I know this topic has been somewhat covered previously. **[https://github.com/wandb/client/issues/764](url)**
I did look at **wandb.init(mode="disabled")**
But does it completely turns of WandB or is there any other feature to set it to disabled mode just like this WANDB_MODE=dryrun.
I'm a bit confused about how to turn it off completely. Please help.
Thank you

**Comment by vanpelt** [comment]
Hey @shrijan00 here are detailed docs on wandb.init: https://docs.wandb.ai/ref/python/init

mode can be "online", "offline" or "disabled", defaults to online. 

online sends data to the cloud, offline just stores data on your local machine that you can later send to the cloud by running `wandb sync` and "disabled" entirely disables all logging but stubs out all of the api methods to still be callable.

"offline" is equivalent to "dryrun" which we are deprecating.
