### ISSUE TITLE
[CLI] wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '189160-gbp6y2en' for key 'PRIMARY' (<Response [409]>)

### ISSUE THREAD

**Issue by amirDahari1** [wandb/client#2056]
**Description**
I get this error message on the command line, tried to reinstall wandb and without the entity in the init call, didn't help.

**Wandb features**
I call wandb with 
wandb.init(project='SuperRes', config=args, name=progress_dir, entity='tldr-group')
I only log some losses and plots.

**How to reproduce**
https://github.com/amirDahari1/SuperRes/tree/develop/code/Architecture.py

**Environment**
- OS: Ubuntu 20.04
- Python Version: 3.8.5

* I saw some similar issues, but I don't use yolo

Thanks!

**Comment by cvphelps** [comment]
Thanks for reporting, this looks like a multiprocessing issue. Here's the workaround for now: https://docs.wandb.ai/library/distributed-training

This should be fixed in the next CLI release

**Comment by amirDahari1** [comment]
I restarted PyCharm and it solved the problem for some reason.. Thanks!
