### ISSUE TITLE
Client hanging + Leaked Semaphores

### ISSUE THREAD

**Issue by surya-narayanan** [wandb/client#2058]
Hi, 

My agent hangs sometimes and when I kill it, throws a warning about leaked semaphore objects.

Here is the warning:
```
 There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```
When it runs, sometimes (sometimes other than when it hangs) produces the following warning:
```
wandb: WARNING Config item 'combine_loss' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'combine_embeddings' was locked by 'sweep' (ignored update).
```

This warning is referenced in https://github.com/conda/conda/issues/9589. It seems to be a Python 3.8 thing. Will try with Python 3.7. 

My workflow is rather straightforward
-- Creating a yaml file
-- Creating wandb.init(config = {config1: ..., config2: ...)
-- wandb sweep sweep.yaml
And running the agent.

I am using Pytorch Lightning (1.2); when I run my train.py file standalone, it runs fine. Some of the sweep runs run fine too, but at times, the program hangs and when I kill it manually, it kills fine but leaves me a warning that 6 semaphores are still locked when the program was killed.

At one point, I ran into a CUDA out of memory error, which I think is somehow linked to the zombie files that were still locked (could have been locked on my GPU).

I didn’t face these issues before using wandb, and so think this locks not being released has something to do with it.

I referred to part of this issue (just the warnings in a comment under #1698) but want to make this a standalone issue to couple it with the agent hanging.

**Comment by ariG23498** [comment]
Hey @surya-narayanan 
I see that you have been replied to in the linked comment. Could you help us there?

We will be tracking this internally.

**Comment by krishnadurai** [comment]
I'm able to reproduce this by:

1. Initializing a run
2. Logging 6 different wandb.Table tables

It seems that wandb is trying to open file handles which are not closed for each table:

```
.../v2venv/lib/python3.7/site-packages/wandb/data_types.py:419: ResourceWarning: unclosed file <_io.BufferedWriter name='/var/folders/fk/vc2_843d1nd95dfvfy6zsdgr0000gp/T/tmpj_t5dzsqwandb-media/ifh8zhhw.table.json'>
  util.json_dump_safer(data, codecs.open(tmp_path, "w", encoding="utf-8"))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by krishnadurai** [comment]
Is this related to #1447?

**Comment by vanpelt** [comment]
@krishnadurai we recently fixed a process hang bug in 0.10.26.  These warnings should be ok to ignore.  Can you try the latest version and report back any errors or tracebacks besides the warning you're seeing?

**Comment by krishnadurai** [comment]
@vanpelt These warnings are the only ones that appear on the terminal. Sure, I'll update my client and see if this reappears.

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
