### ISSUE TITLE
[App] Diagram x-ticks are off when providing 'step'

### ISSUE THREAD

**Issue by vii33** [wandb/client#2059]
**Describe the bug**
Hi, I want to display metrics gathered from a log file. The log contains the `epoch` (= `step`) and some `metric`. The metric is only calculated after a few epochs, therefore I have to set the `step` attribute explicitly. 

**Problem**: When looking at the web dashboard, the step position (x-value) is _off by a changing amount_. The problem only occurs in the _project view_. When selecting a specific run, the values sit on the correct ticks (compare the screenshots).

**To Reproduce**
1. Run the following code.
2. Go to wand website and view project `step_example`. You will see the values don't start at 0.
3. Select the individual run1 in the group. You will see the values start at 0.

What is really weird is that the steps delta seems to get bigger the more far they are away from the 100 tick:
epoch tick (step) | diagram x-position delta 
---- | ----
0 | `+19.6` (see screenshot)
50 | `+9.8`
100 | `0`
150 | `-9.8`
200 | `-19.6`

**Code Example**
```
import os
import wandb
os.environ["WANDB_API_KEY"] = 'Your API Key'

step_metric = {
    0  : 2.2,
    50 : 29.3,
    100: 45,
    150: 67.4,
    200: 182
}

run = wandb.init(  project = "step-example", group = 'run1'  )

for key, value in step_metric.items():
    mydict = { "A": value , "B" : value*2 }
    wandb.log( mydict, step=int(key) )

run.finish()
```
**Expected behavior**
On the project view and details view the values are rendered the same (and correct) way.

**Screenshots**
Project view (wrong):
![grafik](https://user-images.githubusercontent.com/1887246/114324548-fff35180-9b2a-11eb-8579-a5de8743891e.png)

Run view (correct):
![grafik](https://user-images.githubusercontent.com/1887246/114324552-05509c00-9b2b-11eb-9be4-5b823efa23a9.png)

**Operating System**
 - OS: Windows 10
 - Browser Firefox

**Comment by ariG23498** [comment]
Hey @vii33 
Thanks for the issue

For custom x-axis logging we suggest you log a custom key while logging the metrics. We do not want the user to modify the step parameter as it is internal to the way wandb works.

The code snippet that you have presented can be changed like so:
```python
run = wandb.init(entity="xxx", project="xxx")
step_metric = {
    0  : 2.2,
    50 : 29.3,
    100: 45,
    150: 67.4,
    200: 182
}

for key, value in step_metric.items():
    mydict = {"A": value , "B" : value*2, "x-axis": key}
    run.log(mydict)

run.finish()
```

## Screenshot
![image](https://user-images.githubusercontent.com/36856589/114354584-0c5bc680-9b8c-11eb-92c2-fca841704d8b.png)

Hope this helps 😄

**Comment by vii33** [comment]
Hi @ariG23498,

thanks for the quick help, this works 👍 

Still, you note [here ](https://docs.wandb.ai/library/log#incremental-logging) and [here](https://docs.wandb.ai/ref/python/log) that people can adjust the global step for logging. Maybe you guys could clarify the usage in the documentation😄
