### ISSUE TITLE
[CLI] Code and weights not getting saved on the wandboard.

### ISSUE THREAD

**Issue by nsidn98** [wandb/client#2060]
I have been trying to save the code and the model weights on my project wandboard. They used to work a few months ago but have stopped. (I guess since I upgraded to the patched version mentioned [here](https://github.com/wandb/client/issues/1972#issuecomment-801609626)) but it didn't work.

I have been using:
```
wandb.init(project=project, entity=entity, sync_tensorboard=True, config=vars(args),
            name=experiment_name,save_code=True, dir=wandb_save_dir, **kwargs)
```
I tried adding `os.environ['WANDB_SAVE_CODE'] = "true"` as mentioned in  [here](https://github.com/wandb/client/issues/1248#issuecomment-696933966) #1248 

With regards to the weights, they are not getting synced with wandboard for some reason even when the weights are present in the `wandb` folder. For that matter, even the `config.yaml`, `diff.patch`, `requirements.txt`, `wandb-metadata.json`, `wandb-summary.json`, etc. files are not getting synced.

**Environment**
- OS: Mac OS Mojave
- Python Version: 3.6.10
- Wandb version: 0.10.25

**Comment by vanpelt** [comment]
He @nsidn98, can you share a link to a run that doesn't have code synced?

**Comment by nsidn98** [comment]
I am not sure about how to share links to runs from private projects.

**Comment by vanpelt** [comment]
You can email me at vanpelt@wandb.com

**Comment by nsidn98** [comment]
Am I supposed to email the folder which I sync to the wandboard to your email?

**Comment by vanpelt** [comment]
Just the link to a run in your project.

**Comment by nsidn98** [comment]
Wouldn't that link not work for you since it is a private project in wandb? An observation that I have made with this is that this happens only when I run offline jobs and then manually sync them using `wandb sync foldername`. The code, `wandb-metadata.json`, `requirements.txt` are saved in the folders but are not synced. And the `config.yaml` and `diff.patch` are not even getting saved in those folders in the offline run but work while running jobs in the online mode.

**Comment by vanpelt** [comment]
Because I'm an administrator I can access your private project for debugging purposes if you allow me to.

**Comment by nsidn98** [comment]
Have sent the link to your email id.

**Comment by vanpelt** [comment]
Thanks @nsidn98, I've been able to reproduce the bug.  We'll look into getting a fix implemented.

**Comment by vanpelt** [comment]
@nsidn98 I just tried this on the most recent version of the library and it's working for me!  Can you try running `pip install wandb --upgrade` and confirm the files are getting uploaded?  One thing to note, it can take 30-60 seconds for the files to show up in the UI.

**Comment by nsidn98** [comment]
Updated to wandb version `0.10.26`, executed `wandb sync folder_name` and then waited for a few minutes but the checkpoints, code, etc. has not been uploaded to the UI.

**Comment by vanpelt** [comment]
@nsidn98 can you make a tarball or zip of `folder_name` and send it to `vanpelt@wandb.com`?  Seems like there may be something about your specific data that's causing it not to sync.

**Comment by nsidn98** [comment]
Have sent the folder zip to your email id.

**Comment by vanpelt** [comment]
@nsidn98 thanks so much.  I was able to find the bug.  It happens if you have tensorboard event files in your directory.  We'll work on a fix, but until then you can add the `--no-sync-tensorboard` flag to your `wandb sync` command and all files should be uploaded.

**Comment by nsidn98** [comment]
Thanks a lot @vanpelt. Using `--no-sync-tensorboard` worked.
