### ISSUE TITLE
[Q] How to change the name of wandb.run.dir?

### ISSUE THREAD

**Issue by chenshen03** [wandb/client#2061]
The default name of **wandb.run.dir** is something like *run-20210412_0800-UUID*. How can I change the prefix *run-20210412_0800* to a user-custom name?

**Comment by vanpelt** [comment]
You can symlink a new directory with your own custom name to the existing one, for example:

```
import os
wandb.init(...)
os.symlink(wandb.run.dir, wandb.run.dir.replace(wandb.run.id, wandb.run.name))
```

I'm curious, why do you want to change the name of the run directory?

**Comment by chenshen03** [comment]
I just think the prefix is redundant and not easy to retrieve. Anyway, thank you for your reply.
