### ISSUE TITLE
[Q] Do we have a api that can create a project from python or command line?

### ISSUE THREAD

**Issue by HaoLiuHust** [wandb/client#2072]
I want to intergrate wandb into a training system, when user commit a training job, then create a project for him and visualization for him

**Comment by ariG23498** [comment]
Hey @HaoLiuHust 
Could you describe the problem a little better?

For the time being
```python
run = wandb.init(project="new-project")
with run:
    run.log({"metric": metric})
```
this should create a project named "new-project" where "metric" is logged.

**Comment by HaoLiuHust** [comment]
> Hey @HaoLiuHust
> Could you describe the problem a little better?
> 
> For the time being
> 
> ```python
> run = wandb.init(project="new-project")
> with run:
>     run.log({"metric": metric})
> ```
> 
> this should create a project named "new-project" where "metric" is logged.

thanks for your reply, I thought init must ha
