### ISSUE TITLE
[Q] Metric data exceeds maximum size of 4.1MB

### ISSUE THREAD

**Issue by bfs18** [wandb/client#2080]
My log is not synced after 250k steps. When I sync the log manually, the following error occured.
```bash
wandb: ERROR Metric data exceeds maximum size of 4.1MB (4.2MB)
Exception in thread Thread-1:                                                                                                                      
Traceback (most recent call last):                                       
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner                                                                          
    self.run()                                                                                                                                     
  File "/usr/local/lib/python3.6/site-packages/wandb/sync/sync.py", line 209, in run
    data = ds.scan_data()                                                                                                                          
  File "/usr/local/lib/python3.6/site-packages/wandb/sdk/internal/datastore.py", line 131, in scan_data
    record = self.scan_record()                                                                                                                    
  File "/usr/local/lib/python3.6/site-packages/wandb/sdk/internal/datastore.py", line 115, in scan_record
    assert checksum == checksum_computed                                                                                                           
AssertionError  
```
My model is rather large, when `wandb.watch(model)` is used, the metric file would exceeds 4m soon. How to change this limit?

####################################

I think there should be some notification of exceeding limits when logging. It is very wired that wandb.ai page does not update anymore while the experiment is still running.

**Comment by tyomhak** [comment]
Hey @bfs18 , I'm not sure if there's an option to change the limit, but you might want to change/decrease the [logging frequency](https://docs.wandb.ai/guides/integrations/pytorch#options) as a workaround for the issue.

**Comment by vanpelt** [comment]
The other thing that could be causing this is logging numpy arrays or other large data structures in your calls to `wandb.log`.

**Comment by bfs18** [comment]
> Hey @bfs18 , I'm not sure if there's an option to change the limit, but you might want to change/decrease the [logging frequency](https://docs.wandb.ai/guides/integrations/pytorch#options) as a workaround for the issue.

Hi @tyomhak , thanks for your reply, I comment the watch line.
