### ISSUE TITLE
[Q] How to track a hard-coded config?

### ISSUE THREAD

**Issue by bfs18** [wandb/client#2089]
Sometimes there are so many configuration options and I know an option would always be set to the same value after comparison. I don't want to complicate the global configuration parser anymore. So I prefer to copy the code and hard code the option in different copies. Such an option still needs to be tracked for comparison. What's the easiest way to do this? Is there anything like a wrapper which I can add to the hard-coded option line and track it?

**Comment by ariG23498** [comment]
Hey @bfs18 
By hard-coded config do you mean the configurations that are used to run the python script like 👇 
`python train.py -a a -b b -c c`?

> So I prefer to copy the code and hard code the option in different copies

What do you mean by copying the code to different copies?

**Comment by bfs18** [comment]
For example, I might use different dropout rates or different activation functions. 
```
dropout = 0.5     
act_layer = nn.ELU()
```
These 2 values are passed to  other functions. These 2 assignment expressions are hard coded configurations. How to track assignment expressions with `wandb.Config`?

**Comment by ariG23498** [comment]
You could do something like
```python
wandb.config.dropout = 0.5
wandb.config.act_layer = "elu"
```

And that will update the config for your run.
