### ISSUE TITLE
[CLI] / [APP] First upload on an image with group fails

### ISSUE THREAD

**Issue by luifire** [wandb/client#2096]
**Description**
I want to do a sanity check when I start a run. That is uploading some samples out of a training batch.
However these images will not be uploaded until the end of the entire training when I add a group to them (like 'sanity/sample_1').
If I don't add a group they get uploaded right away.
My training takes up to 12 hours which is to long for me to wait. Also I sometimes stop the training in between (using PyCharms "Stop" - not ctrl+c), in this case they won't be uploaded either.

![image](https://user-images.githubusercontent.com/53562633/115668070-ed58f380-a346-11eb-8299-76b9d6740841.png)

Thank you very much for wandb 😊

**How to reproduce**
```
import torch
import wandb
import time

run = wandb.init(project='name', dir='~/test/')
run.name = time.strftime("%H-%M-%S - test")

rand = torch.rand((1, 28, 28))
img_2 = wandb.Image(rand, caption='foo')
wandb.log({'doh/doesnt_work' : img_2}, step=0)

rand = torch.rand((1, 28, 28))
img2 = wandb.Image(rand, caption='bar')
wandb.log({'works' : img2}, step=0)
wandb.log({})

print('upload started')
# simulate some work
for x in range(100000000):
    a = 0

    # simulate some more logging
    if x % 1000 == 0:
        wandb.log({})

print('finished')
```

**Environment**
- OS: Win 10
- Environment: Pyharm
- Python Version: 3.9.2
- Wandb Version:  wandb conda-forge/noarch::wandb-0.10.20-pyhd8ed1ab_0 (0.10.27 is not yet available with conda)

**Comment by luifire** [comment]
I just figured out that no image with a group will be uploaded until the end of a run.

```
import torch
import wandb
import time

run = wandb.init(project='some_project', dir='C:/test/')
run.name = time.strftime("%H-%M-%S - test")

print('upload started')
for x in range(100000000):
    if x % 10000 == 0:
        rand = torch.rand((1, 28, 28))
        wandb_img = wandb.Image(rand, caption='foo')
        wandb.log({f'doh/doesnt_work_{x}': wandb_img})

print('finished')
exit(0)
```

**Comment by luifire** [comment]
One more comment:
I just realized that briefly before the '?' is shown, a small download button appears.
When you hit it, you can actually download the original image. 
**So this is actually an app problem!**

Reproduce: run the script I posted, go online, if the '?' is already shown, refresh the page and press the download button on the upper right corner.
![image](https://user-images.githubusercontent.com/53562633/115729217-83137380-a385-11eb-91b1-d2f90803a49a.png)

**Comment by cvphelps** [comment]
@luifire could you please share a link to the UI for this?

**Comment by cvphelps** [comment]
It sounds like PyCharm "stop" sends a different signal than ctrl+c to our process, which could break something about setting media panel keys

**Comment by luifire** [comment]
This also happens when I finish or when I start the a training as a shell script.

Here you can see two identical finished runs, except they are in different projects (for random reasons this seems to make a difference). In Media they show the exact same information ("samples" and "5_test")
The first displays the images, the second one doesn't.
https://wandb.ai/luifire/bug-reproduction-2/runs/r4taq7rq?workspace=user-luifire
https://wandb.ai/luifire/ood-deep-gen-models/runs/kb5uafg6?workspace=user-luifire

Use this link if you want to be able to press the download link (there are a lot more pictures and thus it takes longer to load). When you download you can see that the pictures actually got uploaded.
https://wandb.ai/luifire/ood-deep-gen-models/runs/2d5xw7ej?workspace=user-luifire

Note that all runs finished:
![image](https://user-images.githubusercontent.com/53562633/116059929-ad18ae80-a681-11eb-9528-6cb435500fc5.png)
![image](https://user-images.githubusercontent.com/53562633/116060003-c15cab80-a681-11eb-8995-aa7600938dea.png)

**Comment by ariG23498** [comment]
Hey @luifire 

I tried reproducing the ticket by using the code snippet that you had sent in. I have provided a few changes of my own. Upon running the code I did not find any error with the images.

Changes:
- Used the `run.log` instead of `wandb.log`
- Did not use the `step` parameter as it is an internal parameter that wandb takes care of.
- Used the `finish` method to stop the run programatically.

## Code
```python
run = wandb.init(entity="xxx", project='xxx')

rand = torch.rand((1, 28, 28))
img_1 = wandb.Image(rand, caption='foo')
# Not using the `step` parameter
# as it is an internal parameter
# used by wandb for incrementing
run.log({'doh/doesnt_work' : img_1})

rand = torch.rand((1, 28, 28))
img2 = wandb.Image(rand, caption='bar')
run.log({'works' : img2})

print('upload started')
# simulate some work
for x in range(100):
    run.log({"metric":x})

print('finished')
# Using `.finsih()` to complete the run
run.finish()
```

I hope this is helpful for you!

**Comment by luifire** [comment]
I could bypass the issue by creating a new project and uploading my logs to it. The issue never reoccurred in the new project.
