### ISSUE TITLE
[CLI] Cannot print large models with wandb

### ISSUE THREAD

**Issue by loeweX** [wandb/client#2097]
**Description**
When logging my experiments and trying to print a large model, the program freezes mid-way into the print statement.

**Wandb features**
wandb.init()

**How to reproduce**
Minimal Example
```
import torch
import wandb

if __name__ == "__main__":
    wandb.init()

    str = ""
    for _ in range(1000):
        str += " \n"

    print(str)

    model = torch.nn.ModuleList(
        torch.nn.Conv2d(1, 1, 1, bias=False)
        for _ in range(1000)
    )

    print(model)
```

`print(str)` works fine. `print(model)` causes the program to freeze somewhere midway into printing. Without `wandb.init()` both print statements work fine.

**Environment**
- OS: Ubuntu
- Environment: Terminal
- Python Version: 3.8.5

**Comment by vanpelt** [comment]
We'll reproduce and work on a fix.  For now you can call `wandb.init(settings=wandb.Settings(console="off"))` and it should no longer hang.
