### ISSUE TITLE
[Feature] Show custom chart in all runs

### ISSUE THREAD

**Issue by luifire** [wandb/client#2098]
**Is your feature request related to a problem? Please describe.**
When I create a custom chart, I usually want to see this chart in all runs.
Unfortunately it is usually not shown in other runs.

Sometimes it gets copied over to the next run, but usually it doesn't.
This might be because sometimes not all metrices get upload and then charts won't be display in the current run and thus the next run can't copy from them. I.e. metrices that appear during evaluation every x'th step but I stop the run before evaluation.

Example scenario: During evaluation I create multiple metrices.
Later on I would like to display them in one chart and not see 5 lines in 5 different charts.
Thus I create a custom chart. However as I am debugging my model, I will often stop and rerun.
Unfortunately I have to create the custom chart over and over again and also have to delete the plots with only one line.

**Describe the solution you'd like**
A functionality where you can select something like this for any chart:
"show chart in all runs (if possible)"

Also for hiding ("hide chart in all runs")
Otherwise a lot of unwanted charts are shown in every run.

**Describe alternatives you've considered**
Maybe you can create a board and store it as "board X".
Now in any run you can switch between boards.
This would give you the opportunity to look at runs in different ways.

Though I feel like the first solution is more intuitive.

Thank you very much.

**Comment by ariG23498** [comment]
Hey @luifire 

Thanks for the great feature request. I am delegating this request to our UI team! We will be tracking this internally.

**Comment by cvphelps** [comment]
@luifire could you please share a link? I believe this behavior happens already, where if we can show a chart we do indeed show it across all runs.

**Comment by luifire** [comment]
Hi, 
sorry for bothering. I am currently unable to reproduce it (and I deleted all test Runs :/  )
What happens though is that the regex for line plots did not catch all metrics.
Throughout my testing it kept on catching fewer and fewer metrices (and they existed and had the same name schema as the metrics that were collected - but I deleted the Runs :( ). 
I assume that this was the actual problem I had.
Here you can see an example where the regex doesn't work:
https://wandb.ai/luifire/bug-reproduction/runs/326tss0i?workspace=user-luifire

**Comment by ariG23498** [comment]
Hey @luifire 
Could you send us a `colab` that could help in the reproduction of the issue? The workspace you have shared is a read only, hence I cannot really look into the problem here.

It would be great if you could hand in a bug report as a wandb `Report`. That would help us not only reproduce it but also see what goes wrong with the regex.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
