### ISSUE TITLE
On-boarding for new user through web UI needs link to "Getting started"

### ISSUE THREAD

**Issue by rguerrettaz** [wandb/client#210]
### Description

After signing up through the website, there's no direction on how to get started. I figured it out by reading the ["Getting started" documentation](https://docs.wandb.com/docs/started.html). Might propose an alert box for accounts with 0 projects, linking to getting started docs.

Also, found it odd the nav links were disabled by default. I was expecting to be able to click the links and see a default state (which could also push me to the getting started docs).

### What I Did
1. Logged into Linkedin
2. Saw news about W&B
3. Got fucking excited
4. Signed up for W&B account through website
5. Scratched head, wondering what to do  (screenshot of landing page below)...
6. Found docs and figured it out

Screenshot of landing page after signing up: 
![screen shot 2018-06-07 at 21 17 32](https://user-images.githubusercontent.com/1142155/41138905-47f481f4-6a99-11e8-947d-531dc419bde0.png)

**Comment by rguerrettaz** [comment]
This repo is probably the wrong place for this. If there's a better location I'd be happy to drop it there.

**Comment by lukas** [comment]
I think this is great - really appreciate the feedback.  We'll work on fixing this.

**Comment by vanpelt** [comment]
@rguerrettaz you are destined to become a power user of our software!  Just fixed the bulk of this issue by adding a link to getting started docs.  I agree the disabled nav links are confusing, we're working on a broader navigation overhaul.
