### ISSUE TITLE
[App] Missing Scrolling on Artifacts -> Files tab

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/client#2102]
**Describe the bug**
I could not scroll to the end of the page on the Artifacts -> FIles tab, only see the top of the frame. I have to zoom out to see the end of the file list and the page switcher. 

**Expected behavior**
Well, I want to scroll along the long list without a need to zoom out

**Screenshots**
Scrolling on Normal zoom just gets me this far: 
![image](https://user-images.githubusercontent.com/6837635/115809713-4bdcab00-a3f5-11eb-8fa5-1591b292d3a4.png)

The end of the file list and the pages switcher become visible on 33% scale
![image](https://user-images.githubusercontent.com/6837635/115809824-7c244980-a3f5-11eb-9e0c-80c5676eb519.png)

**Operating System**
 - OS: Win 10
 - Browser: Chrome
 - Version: 90.0.4430.85 (latest, as far as I know)
 - Screen resolution: 1920 x 1080

**Additional context**
I see this in the Browser console, in case it's related

![image](https://user-images.githubusercontent.com/6837635/115809913-afff6f00-a3f5-11eb-8b04-1b9e5e137fc6.png)

**Comment by ariG23498** [comment]
Hey @maria-korosteleva 
Thanks for the bug report!
We will be tracking it internally.
