### ISSUE TITLE
[Q] Is it possible to change the location where the cache folder is created?

### ISSUE THREAD

**Issue by ronentk** [wandb/client#2107]
Hi, 
Currently the default cache folder is created for me in a directory with space limitations imposed by my organization, so my runs are failing when I try to use large artifacts. Is there a way to relocate the cache to a different directory?
Thanks!

**Comment by vanpelt** [comment]
Yes, you can set the WANDB_CACHE_DIR environment variable.  If you need to reclaim space from your cache directory you can run the following as documented [here](https://docs.wandb.ai/guides/artifacts/artifacts-faqs#how-do-i-clean-up-my-local-artifact-cache).

```
wandb artifact cache cleanup 1GB
```

**Comment by ariG23498** [comment]
Closing this issue as has been resolved.

**Comment by BitCalSaul** [comment]
> Yes, you can set the WANDB_CACHE_DIR environment variable. If you need to reclaim space from your cache directory you can run the following as documented [here](https://docs.wandb.ai/guides/artifacts/artifacts-faqs#how-do-i-clean-up-my-local-artifact-cache).
> 
> ```
> wandb artifact cache cleanup 1GB
> ```

This variable doesn't work. It did set up a folder as I assigned, but the cache md5 file was still stored into the default dir which is ~/.cache/wandb.
