### ISSUE TITLE
[CLI] Missed data(media files, logs) in case of late directory creation

### ISSUE THREAD

**Issue by ikhlestov** [wandb/client#2137]
**Description**
If directory for wandb run was created after `wandb.init()` call then media files from run not synced to the W&B board and there is no any wandb run text logs saved.

**Wandb features**

```
wandb.init()
wandb.Table()
wandb.log()
```

**How to reproduce**

just run example code as `python example.py`

```python

import os
import random
import string

import wandb


if __name__ == '__main__':
    random_dir_path = os.path.join(
        '/tmp',
        ''.join(random.choice(string.ascii_lowercase) for _ in range(10))
    )
    wandb.init(
        project="classifier",
        dir=random_dir_path,
    )
    # this is important part - directory created after wandb init call
    os.makedirs(random_dir_path, exist_ok=True)
    data = []
    for i in range(10):
        data.append([i, random.random()])
    table = wandb.Table(data=data, columns=["cls_idx", "AP"])
    wandb.log(
        {"AP_scatter": wandb.plot.scatter(
            table, "cls_idx", "AP", title="average precisions")}
    )

```

Expected output:

- Table and scatter plot are displayed at the W&B dashboard
- run logs `logs/debug.log` and `logs/debug-internal.log` are saved to the directory

Received output:

- No table and scatter plot at the dashboard
- logs were not saved

Received directory structure below
```
/tmp/serkyvuvvx/
└── wandb
    └── run-20210429_150324-1h0goci5
        └── files
            └── media
                └── table
                    └── AP_scatter_table_0_f4cbed65.table.json
```

**Environment**
- OS:
```Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
- Environment: local host, virtualenv
- Python Version: Python 3.6.10
- wandb, version 0.10.28

**Comment by vanpelt** [comment]
@ikhlestov currently when you're specifying a `dir` argument with wandb.init, that directory must already exist.  Are you able to refactor your code to create directory prior to calling wandb.init?

**Comment by ikhlestov** [comment]
@vanpelt Yes, sure, I've already made refactoring. Still it very suspicious when you have some data synced(regular log files) and others are not. Maybe it's possible to raise an exception if it is a strong requirement?
