### ISSUE TITLE
[Q] Multiple scalars same plot

### ISSUE THREAD

**Issue by luigicampanaro** [wandb/client#2138]
Hi guys,

I have a dictionary with multiple scalars computed every epoch `rewards = {'x': 0.1, 'y': 0.4, 'z': 0.5, ...}`, I'd like to log all of them in the same figure as a "multiple" line plot.

Do you have any suggestion? I tried with `wandb.plot.line_series`, but I didn't manage to achieve a behaviour similar to tensorboard's `SummaryWriter.add_scalar('Rewards', rewards (dict above), epoch (int))`.

Thank you in advance!

**Comment by ariG23498** [comment]
Hey @luigicampanaro 

I have tried describing a solution to your ticket 👇 
## Code
```python
run = wandb.init(entity="repro", project="GH-2138")
with run:
    a = 0
    b = 0
    c = 0
    d = 0
    for i in range(1,100):
        a = a + random.randint(0,10)
        b = b + random.randint(0,10)
        c = c + random.randint(0,10)
        d = d + random.randint(0,10)
        reward = {
            "a": a/i,
            "b": b/i,
            "c": c/i,
            "d": d/i,
        }
        run.log(reward)
```

## Screenshot
### The UI we see
![image](https://user-images.githubusercontent.com/36856589/116680431-4f5dcc80-a9c9-11eb-8515-c77b9a4dfd97.png)

### Multiplot UI
We can change the y_axis of a single line plot to take all the metrics together. After we do that we can find the UI to look something like this.
![image](https://user-images.githubusercontent.com/36856589/116680618-80d69800-a9c9-11eb-876c-1f3d82a82e19.png)


Hope this helps 😄

**Comment by luigicampanaro** [comment]
Hey @ariG23498,

thx for replying! 
How can I generate the plot automatically, without having to do it by hand? This way every time I run the script and for everyone else using it, the rewards will be displayed and organised in the same way.

**Comment by ariG23498** [comment]
Hey @luigicampanaro 

I don't think that there is an automatic generation of plot workaround for the problem. Once you make the chart with all the metrics, the same setting will be used for future runs.

![image](https://user-images.githubusercontent.com/36856589/116847141-920ce800-ac07-11eb-8794-7b3bb3a1864e.png)
