### ISSUE TITLE
[Feature] Rest API

### ISSUE THREAD

**Issue by Ierezell** [wandb/client#2141]
**Is your feature request related to a problem? Please describe.**
Having a Rest api to log minimal features in every languages (NodeJs for my useCase)

**Describe the solution you'd like**
Having a Rest documentation on which (graphql) queries to make. 

If graphql is needed (as seen in the source code) then it's easy to install and use it in many languages. 

We would then call it to log In, get an API token and log metrics, enjoy the wonderful W&B features (parameters correlation, beautiful easy plots etc..)

We're not asking for the full api. Artifacts, sweeps, hardware is too complicated (or can come in a second time). 
But logging names or numbers like metrics (accuracy / logs) or confusion matrix, (maybe images) should be doable. 

By doing ML outside of the python ecosystem we loose many tools we really like and that could be really nice for many users (NLP in a web stack in our case).

We're willing to put efforts as it would really help our R&D / production pipeline. 

**Describe alternatives you've considered**
- Using MLFlow as they support REST Calls (but the interface is not as nice...).
- Using tensorboard (from nodejs) but they includes even less features than mlflow.

**Additional context**
We checked the code and it would be feasible but a pain to reverse engineer the small part we want. 

Thanks for the nice library. 
Have a great day

**Comment by ariG23498** [comment]
Hey @Ierezell 
Thanks for the well thought feature request.
I will be filing a ticket for the same so that a core engineer can come ahead and update this thread better.

**Comment by Ierezell** [comment]
Hi, hope the team is doing well. 

Any update about this issue? 
If a client is too much, it can also be documentation of the API. 

Have a great day

**Comment by vanpelt** [comment]
The graphql api is self documenting, you can use an extension like [ChromiQL](https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij?hl=en) to explore it.  Just set the endpoint to https://api.wandb.ai/graphql

You can also see examples of making API requests in our [public api](https://github.com/wandb/client/blob/master/wandb/apis/public.py) and find examples of using our public api interface in [our documentation](https://docs.wandb.ai/guides/track/public-api-guide).

**Comment by mpost** [comment]
The link at https://api.wandb.ai/graphql does not work. 405.

**Comment by prattsoroco** [comment]
Any update @mpost ? The link indeed doesnt work

**Comment by lukasbm** [comment]
Is it possible anymore to access the GraphQL api?
