### ISSUE TITLE
[App] cannot view logged video in run stats

### ISSUE THREAD

**Issue by pragyakale** [wandb/client#2143]
**Describe the bug**
Video file type is not recognized correctly

**To Reproduce**
1. Log a video using 
`wandb.log(
  {"video": wandb.Video(numpy_array_or_path_to_video, fps=4, format="gif")})`
2. Go to run>files>Media on the browser

**Expected behavior**
Expected to see the .mp4 video

**Screenshots**

![Screenshot from 2021-04-30 14-10-47](https://user-images.githubusercontent.com/14981373/116693336-110ee000-a9be-11eb-857c-fa285ab1ac06.png)

![Screenshot from 2021-04-30 14-11-07](https://user-images.githubusercontent.com/14981373/116693354-179d5780-a9be-11eb-9f01-592f1156c870.png)

**Operating System**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**
When I download and play the logged file it plays correctly.

**Comment by cvphelps** [comment]
@pragyakale It looks like we don't have the right codec hooked up for MP4s yet, thanks for reporting this!

**Comment by NotAnyMike** [comment]
Hi @cvphelps, any idea when will this be fixed?

**Comment by vanpelt** [comment]
@NotAnyMike, it looks like you're logging an "mp4" video but telling us it's a "gif" video.  Can you try logging with `format="mp4"` instead of `format="gif"`?

**Comment by NotAnyMike** [comment]
It was a typo, we are using `format="mp4"`

**Comment by vanpelt** [comment]
How are you generating the mp4?  Can you share a link to the problematic run?  We're just using an HTML5 `video` tag in our web page.  If the mp4 was generated with a codec that modern browsers don't support it won't be able to play it.  A table of browsers and what codecs are supported can be [found here](https://en.wikipedia.org/wiki/HTML5_video).

**Comment by NotAnyMike** [comment]
We are using opencv to generate the video, save it in disk and pass the path to wandb. The codec we use is `cv2.VideoWriter_fourcc(*'MP4V')` or `mp4v`.

**Comment by NotAnyMike** [comment]
@vanpelt thank you, if we change the encoding to libx264 it works,. Looks like mp4v does not work well with HTML5 video tag. Thank you. I think it is save to close this issue.

**Comment by najwalb** [comment]
Reopening this issue because I got the same error when logging an mp4 video from slurm. When I log the video locally I can play it on Google chrome, but not on mozilla for example. I save the video as mp4 with imageio and upload it with the format specified as mp4. Any tips?

**Comment by Jianghanxiao** [comment]
`fourcc = cv2.VideoWriter_fourcc(*"avc1")  # Codec for .mp4 file format
video_writer = cv2.VideoWriter(save_path, fourcc, FPS, (width, height))`

Opencv with acv1 for extension '.mp4' works for me to log the video into wandb, mp4v doesn't work

**Comment by smirnovlad** [comment]
I also encountered a problem with loading videos from the Minigrid environment. I'm using gym==0.21.0 and gym-minigrid==1.0.3. For recording videos, I use the wrapper:
```python
env = gym.wrappers.RecordVideo(env, os.path.join(args.videos_dir, f"env_{agent_idx}/{run_name}"))
```
I had to patch the ImageEncoder class in the gym/wrappers/monitoring/video_recorder.py file and modify the command for video recording:
```python
        self.cmdline = (
            self.backend,
            "-nostats",
            "-loglevel",
            "error",  # suppress warnings
            "-y",
            # input
            "-f",
            "rawvideo",
            "-s:v",
            "{}x{}".format(*self.wh),
            "-pix_fmt",
            ("rgb32" if self.includes_alpha else "rgb24"),
            "-framerate",
            "%d" % self.frames_per_sec,
            "-i",
            "-",  # this used to be /dev/stdin, which is not Windows-friendly
            # output
            "-vf",
            "scale=trunc(iw/2)*2:trunc(ih/2)*2",
            "-vcodec",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-movflags",
            "+faststart",
            "-profile:v",
            "baseline",
            "-level",
            "3.0",
            "-r",
            "%d" % self.output_frames_per_sec,
            self.output_path,
        )
```
