### ISSUE TITLE
[App] Artifact graph visualization bug

### ISSUE THREAD

**Issue by vwxyzjn** [wandb/client#2154]
**Describe the bug**

Hello, I am trying to view the graph of this artifact in the documentation: https://wandb.ai/stacey/dsviz-demo/artifacts/val_epoch_preds/val_pred_55oxnv95/e7956e9367bf5369712c/graph

but had the error `graphql: got nil for non-null "Project"`

**To Reproduce**

1. Go to https://wandb.ai/stacey/dsviz-demo/artifacts/val_epoch_preds/val_pred_55oxnv95/e7956e9367bf5369712c/graph
2. See error

**Comment by ariG23498** [comment]
Thanks for tagging this @vwxyzjn 
We will be looking into it!

**Comment by sydholl** [comment]
This issue was fixed in May 2021
