### ISSUE TITLE
[CLI] `wandb.watch` causes `RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace.` during the forward pass

### ISSUE THREAD

**Issue by rafi-cohen** [wandb/client#2157]
**Description**
Calling `wandb.watch` on a PyTorch model causes a `RuntimeError` during the forward pass of said model. The error seems to be related to hooks:
```
RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can remove this warning by cloning the output of the custom Function.
```

**Wandb features**
`wandb.watch` on a PyTorch model

**How to reproduce**
Running the code below reproduces the error:
```python
import wandb
from torch.utils.data import DataLoader
from torchvision.models import resnet18
from torchvision.datasets import FakeData
from torchvision.transforms import ToTensor


def main():
    data = FakeData(transform=ToTensor())
    dataloader = DataLoader(data)
    model = resnet18()
    wandb.init()
    wandb.watch(model)
    input, _ = next(iter(dataloader))
    model(input)


if __name__ == '__main__':
    main()
```
By omitting the `wandb.watch(model)` line, there are no errors and the code executes successfully.

**Environment**
- OS: Ubuntu 18.04.5 LTS (x86_64)
- Environment: conda
- Python version: 3.8 (64-bit runtime)
- wandb version: 0.10.29
- PyTorch version: 1.9.0.dev20210502
- Torchaudio version: 0.9.0.dev20210502
- Torchvision version: 0.10.0.dev20210502

**Additional context**
Perhaps this is related to https://github.com/wandb/client/issues/2140

**Comment by vanpelt** [comment]
Yep, this is indeed related to the other ticket.  I'm working on [a PR ](https://github.com/wandb/client/pull/2150) to add a way to override this behavior that should land in the next release.

**Comment by rafi-cohen** [comment]
If I understand correctly, that PR adds an option to use `register_backward_hook` instead of `register_full_backward_hook`?
I actually believe using `register_full_backward_hook` is the correct thing to do, seeing as `register_backward_hook` is a deprecated function.

Note that on wandb version 0.10.27 the reproduction code produces the following warning:
```
UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
```

I don't think `register_full_backward_hook` is the cause of the original `RuntimeError`, but rather the logic of the hook registered by `wandb.watch`.

**Comment by morganmcg1** [comment]
I encountered this also, downgrading to torchvision 0.8.2 solved the issue for me, in case thats of any help

[Pytorch forums thread](https://discuss.pytorch.org/t/runtimeerror-module-backward-hook-for-grad-input-is-called-before-the-grad-output-one-this-happens-because-the-gradient-in-your-nn-m-odule-flows-to-the-modules-input-without-passing-through-the-modules-output/119763/8)
