### ISSUE TITLE
[CLI] Connection error, and we cannot find the requested files in the cached path

### ISSUE THREAD

**Issue by GillesJ** [wandb/client#2158]
**Description**
`wandb` fails on connection attempt (sometimes before training starts, sometimes after training and logging has been working fine for a few runs).
The process errors with: 
`Run xxxxxxxx errored: ValueError('Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.')`

I checked connection with curl + ping, internet on the server is up and connection to domain is working:
```
> curl -s --head  --request GET https://wandb.ai/site
HTTP/2 200
```

Tried:
- Re-login: `wandb login --relogin`
- Update 0.10.28 -> 0.10.29: issue persists

Q:
- Are their any other ways to check connection failure?
- Is there a webpage for checking wandb server/services status?

**Wandb features**
- Using sweeps with wandb.init() and wandb.log() and Huggingface integration to upload dicts of metrics and 2 Table objects.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
2. Describe what we have to do in order to trigger the issue
3. Add a zip file with the run folder

Cf. attached .zip for source script + run files. 
[wandb-connection-issue.tar.gz](https://github.com/wandb/client/files/6421415/wandb-connection-issue.tar.gz)

**Environment**
- OS: Ubuntu 20.4
- Environment: Pipenv venv
- Python Version: 3.8.8
- wandb pypi version: 0.10.29

**Comment by vanpelt** [comment]
Hey @GillesJ we maintain a status page at https://status.wandb.com.  We were not having an outage at this time.  Looking at your script the only error I'm seeing is around attempting to attach a signal in thread.  You could try adding `settings=wandb.Settings(console="off")` to your call to wandb.init and see if that changes anything.

Can you share another run directory or two that this is happening in?

**Comment by GillesJ** [comment]
Thanks for the status page link, very handy! It seems that the connection issues were spotty on our side due to a large-scale DDoS attack on our network infrastructure.
