### ISSUE TITLE
Add tests for file renaming

### ISSUE THREAD

**Issue by tsholmes** [wandb/client#217]
The new behavior to handle renamed files added in #216 is untested. Add some tests.

**Comment by vanpelt** [comment]
😇 actually, there are 2 scenarios beyond the default scenario that would be good to investigate.

1. Does a regular TensorFlow run trigger a bunch of renames and does that impact the debug log size negatively.
2. Should we handle delete explicitly?  Currently I believe delete is handled by gracefully passing if the file no longer exists when it comes time to upload.
