### ISSUE TITLE
How to log best metrics in Table[Q]

### ISSUE THREAD

**Issue by awsaf49** [wandb/client#2173]
In **Keras** after training only `best_epoch` & `best_loss` can be seen in the **Table**. Is there any way to log the **best result** for other metrics as well like, `best_accuracy`? Unfortunately, `WandbCallback` doesn't show the **best value** for the metrics.

**Comment by vanpelt** [comment]
Hey @awsaf49 we're working on better documentation for a [new feature](https://docs.wandb.ai/ref/python/run#define_metric) that supports this.

After you call `wandb.init` you can call:

```
wandb.run.define_metric("accuracy", summary="best", goal="maximize")
```

Then a new column will be added to the table named `accuracy.best`.
