### ISSUE TITLE
Is it possible to transfer a run from one project to another (including all artifacts)?

### ISSUE THREAD

**Issue by lucaguarro** [wandb/client#2174]
I realized that I had initialized my run to the wrong project after it had trained for 3 hours. 
I was wondering if I could simply transfer the run from one project to another instead of having to retrain the whole model again with the correct project name. I also saved the model to the artifacts and would also like to place this in the artifacts of the corresponding project.

Is this possible?

**Comment by vanpelt** [comment]
Hey @lucaguarro you can move a run to another project in the UI.

![image](https://user-images.githubusercontent.com/17/117341883-8283de00-ae57-11eb-9b74-2381d273f8c1.png)

The artifacts will not be moved.  To add the artifact to the other project, you'll need to download the original and re-upload it.  You can do this via the command line with:

```
wandb artifact get vanpelt/reproducibility/my-artifact:v0
wandb artifact put -n vanpelt/new_project/my-artifact -t model ./artifacts/my-artifact:v0
```
