### ISSUE TITLE
How to log ROC curve and Confusion matrix

### ISSUE THREAD

**Issue by shrijan00** [wandb/client#2176]
Hi,

I recently started using wandb, and I was trying to log the roc as well confusion matrix for a binary classification.

```python
outputs = net(inputs.to(device))
preds = torch.sigmoid(outputs).data

outputs_data = preds.cpu().numpy()

labels_data = labels.cpu().numpy()

for x in range(len(outputs_data)):
    y_true.append(labels_data[x])
    # print(y_true)
    y_score.append(outputs_data[x])

fpr, tpr, thresholds = roc_curve(y_true, y_score)
wandb.log({'roc': wandb.plots.ROC(y_true, y_score, labels= None)})
wandb.log({'confusion matrix' : wandb.plot.confusion_matrix(preds=y_score, y_true=y_true)})
```

I receive an error i.e.
```
y_true, probas[:, i], pos_label=classes[i]
IndexError: index 1 is out of bounds for axis 1 with size 1
```

Could you please point out the right way to do it?

**Comment by ariG23498** [comment]
Hey @shrijan00 
I have tried reproducing the issue, here are my observations:
- We can use [custom charts](https://docs.wandb.ai/guides/track/log#custom-charts) preset to plot ROC with `wandb.plot.roc_curve()` and Confusion Matrix with `wandb.plot.confusion_matrix()`.
- While doing binary classification, the prediction array must be of the shape `(number_of_preds, 2)`. The `2` stands for each of the class. We default to multi-class classification, hence with binary classification we need to modify the prediction array.
    ```python
    y_pred_changed = np.zeros((NUMBER_PREDS,2))
    y_pred_changed[:,0] = y_pred
    y_pred_changed[:,1] = 1.0-y_pred
    ```
- `y_pred_changed` is sent here:
    - ROC:
       ```python
       wandb.log({'roc': wandb.plot.roc_curve(y_true, y_pred_changed)})
       ```
    - Confusion Matrix:
       ```python
       wandb.log({'confusion matrix' : wandb.plot.confusion_matrix(probs=y_pred_changed, y_true=y_true)})
       ```
       > Note the `probs` parameter here.

**Comment by shrijan00** [comment]
Hi,
Thanks for your reply. I did try in the beginning to just log pyplot to wandb. I haven't tried the option you suggested but just wanted to let you know when I try to log the curve from the pyplot curve as shown below I receive this:

![image](https://user-images.githubusercontent.com/4169231/117415923-26818e00-af19-11eb-836a-c5f0cb58e5c3.png)

![image](https://user-images.githubusercontent.com/4169231/117416172-62b4ee80-af19-11eb-9a05-5957deaab142.png)

**Comment by ariG23498** [comment]
Could you reorder the code like this 👇 
```python
plt.scatter(...)
wandb.log(...) # This goes above plt.show()
plt.show(...)
```

Just move `wandb.log` above the `plt.show()`

**Comment by shrijan00** [comment]
I tried the same but unfortunately, receive the same error. 

![image](https://user-images.githubusercontent.com/4169231/117417635-d7d4f380-af1a-11eb-9ae3-ea75476e96f5.png)

**Comment by ariG23498** [comment]
Could you send in a Colab notebook for me to reproduce the current issue?

**Comment by shrijan00** [comment]
I believe either the matplotlib version is the issue or something else because tried to just plot a simple array and I receive the same error.
`
        plt.plot([1, 2, 3, 4])
        plt.ylabel("some interesting numbers")
        wandb.log({"chart": plt})`

**Comment by ariG23498** [comment]
I don't seem to have any problem with the implementation of the above code.
![image](https://user-images.githubusercontent.com/36856589/117422152-ea602480-af3c-11eb-9eda-cd1f8ed2818e.png)


Wandb version: 0.10.29
Matplotlib version: 3.2.2

**Comment by shrijan00** [comment]
I believe it's something related Matplotlib version. Anyway, thank you for your help. I'll try to figure it out
My Matplotlib version: 3.3.3
Wandb version: 0.10.19
