### ISSUE TITLE
[Feature] Delete multiple runs at a time from the web app

### ISSUE THREAD

**Issue by timothybrooks** [wandb/client#2185]
I sometimes run large sets of many runs all at once (possibly in a group, or possibly independently). Occasionally I make a mistake when launching, such as using a wrong hyperparameter, and need to terminate the runs and launch a new set. When this happens, I find myself deleting runs one-by-one on the W&B web app. It would be great if I could instead select multiple runs at once, and delete them all together.

**Comment by ariG23498** [comment]
Hey @timothybrooks 
You can indeed select a group of runs together
![image](https://user-images.githubusercontent.com/36856589/117564130-207ddf80-b0c8-11eb-91e8-042105dd3321.png)

And then delete the group all at once. Hope this helps 😄
