### ISSUE TITLE
Plotly plots not showing properly on the dashboard

### ISSUE THREAD

**Issue by mariatirindelli** [wandb/client#2191]
I am trying to plot a stack of images as an animation frame (example "Exploring 3-D images and timeseries with animation_frame" in https://plotly.com/python/imshow/). I can correctly plot with plotly, but when I log on wandb I see an empty space, with the sliding bar. 

The code I'm running is: 

```python
import wandb
wandb.init(project="plot tests")

import plotly.express as px
from skimage import io
data = io.imread("https://github.com/scikit-image/skimage-tutorials/raw/main/images/cells.tif")
img = data[25:40]
fig = px.imshow(img, animation_frame=0, binary_string=True, labels=dict(animation_frame="slice"))

wandb.log({"my_chart": fig})
```

And here's what I get in wandb
![Acquisisci2](https://user-images.githubusercontent.com/48152056/117969374-9c299780-b327-11eb-8f11-1953b737ba19.JPG)

I run the code on my Windows machine: 
 - OS: Windows 10
 - Browser: tested on both Chrome and Safari 
 - Version [e.g. 22] wandb version: '0.10.30', plotly version: 4.14.3

**Comment by ariG23498** [comment]
Hey @mariatirindelli 
Thanks for the ticket. We will be tracking this internally.

> Note: In a colab notebook we probably need to upgrade plotly to the latest release to avail the `animation_frame` parameter.

**Comment by cvphelps** [comment]
Thanks for reporting this! The issue is that Plotly is not maintaining their converter to JSON well. We can't fix this on our side since it's a plotly bug, but if you log the plot as an image we will render that faithfully.

**Comment by lucmos** [comment]
It is possible to do the following as a workaround:

```python
wandb.log({"my_chart": wandb.Html(plotly.io.to_html(fig)})
```
