### ISSUE TITLE
[App] Segmentation Masks aren't shown

### ISSUE THREAD

**Issue by teufelweich** [wandb/client#2198]
**Describe the bug**
I'm logging images, their predicted segmentation and the ground truth during the end of a validation epoch (PyTorch Lightning).
They probably get synced to my local WandB server, but are not displayed on the web app. I'm only getting "This run didn't log any images for key".

I've found the path to the temporary folder where the PNGs inside the `<wandb.sdk.data_types.Image object>` and found the images which look good to me (see screenshot down below).

**To Reproduce**
I'm logging with the following piece of code:
```python      
def log_sem_seg(self, rgbs, preds, gts=None, title='Predictions'):
    img_list = []
    for rgb, pred, gt in zip(rgbs, preds, gts):
        masks = {'prediction': {'mask_data': pred.cpu().numpy().astype('uint8'),
                                'class_labels': self._class_label_dict_wo_void}}
        if gt is not None:
            masks.update({'ground_truth': {'mask_data': gt.cpu().numpy().astype('uint8'),
                                           'class_labels': self._class_label_dict}})
        img_list.append(wandb.Image(rgb.cpu().numpy().astype('uint8'), masks=masks))

    wandb.log({title: img_list}, commit=False)
```
each rgb array has shape `(480, 640, 3)` 
each pred and gt array have shape `(480, 640)`

**Expected behavior**
The segmentations should show up in the web app or, if something is wrong with my logging, the error should be more precise.

**Screenshots**
![This run didn't log any images for key](https://user-images.githubusercontent.com/33784413/118332889-11a18d80-b50b-11eb-8379-930e76083913.png)

![Tmp folder containing missing images](https://user-images.githubusercontent.com/33784413/118333996-08b1bb80-b50d-11eb-9dbf-2d9a7522024e.png)

**Operating System**
 - OS: Gentoo
 - Browser Firefox
 - Version 88.0.1 (64-bit)

- wandb.__version__ '0.10.28'
- W&B Local 0.9.40
- PyTorch Lightning __version__ '1.3.1'

**Additional context**
When the website tries to load masks, it cycles through all the previous steps to find a mask. During this I can click the download button and download the RGB image.

**Comment by ariG23498** [comment]
Hey @teufelweich 
In your code you seem to have missed the quotes around the `title` that you are loggin.
Could you check if that is the problem?
```python
def log_sem_seg(self, rgbs, preds, gts=None, title='Predictions'):
    img_list = []
    for rgb, pred, gt in zip(rgbs, preds, gts):
        masks = {'prediction': {'mask_data': pred.cpu().numpy().astype('uint8'),
                                'class_labels': self._class_label_dict_wo_void}}
        if gt is not None:
            masks.update({'ground_truth': {'mask_data': gt.cpu().numpy().astype('uint8'),
                                           'class_labels': self._class_label_dict}})
        img_list.append(wandb.Image(rgb.cpu().numpy().astype('uint8'), masks=masks))

    wandb.log({title: img_list}, commit=False) ##### Here you seem to have missed the quotes around title
```

**Comment by teufelweich** [comment]
What quotes do you mean? `title` is an argument of my function and contains a `string`.
```python
>>> title='predictions'
>>> title
'predictions'
>>> {title: 'foo'}
{'predictions': 'foo'}
```
When calling the function, I'm setting `title='val/Predictions'` as you can see in the screenshot of the WandB app.

**Comment by ariG23498** [comment]
Makes sense!
Could you send in a colab of a minimal implementation?

**Comment by teufelweich** [comment]
Well... as I expected running the example on colab with your hosted WandB instance I'm not experiencing this issue:
Results: https://wandb.ai/teufelweich/seg-test/runs/a77q2zn8
Colab: https://colab.research.google.com/drive/1nRbNMvpaVujmxLc2tpklPtxQsIN_6yfK?usp=sharing

I've also tried the exact same code on my local WandB instance and have the issue as described above. Maybe you could try it with an own local instance.

**Comment by ariG23498** [comment]
That is interesting.

Could you send in a zip file of the images and masked prediction that you are using in this colab notebook? It would be easier for me to iterate on a specifically smaller version of the entire dataset that way. 

Thanks

**Comment by teufelweich** [comment]
Sure. I thought they would stay inside the colab. 🤷🏻‍♂️ 
Because I don't know if I have the rights to distribute these images, I've put a password on the zip and send the password to your gmail adress.
[segm-mask.zip](https://github.com/wandb/client/files/6506552/segm-mask.zip)

**Comment by ariG23498** [comment]
Thanks for the update!
I am trying to repro this, will update as soon as I have something! 😄

**Comment by teufelweich** [comment]
Hey :)
I think it is a broader issue, since I stumbled into the same behavior for `wandb.plot_table()`
![image](https://user-images.githubusercontent.com/33784413/119271774-4399aa80-bc03-11eb-81f9-249fe451e114.png)
I have not verified this on your hosted instance, but the coincidence seems pretty clear to me.

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
