### ISSUE TITLE
[CLI] Process saving to NFS hangs, possibly related to wandb client

### ISSUE THREAD

**Issue by eric-mitchell** [wandb/client#2207]
**Description**
Long-running jobs regularly hang without an identifiable cause. The jobs do not crash or complete; they become stuck, waiting on I/O (process state S/Sl). `strace` suggests wandb _might_ be involved, maybe something specific to wandb + NFS.

**Wandb features**
Currently using `wandb.init`, `wandb.log`, `wandb.watch`.

**How to reproduce**
Very difficult to reproduce; cause unknown. The problem has occurred in 6 jobs run on a slurm cluster in the past 24 hours. See the system logs from wandb, which show a large network activity spike a bit before GPU utilization went to zero (i.e. the process hung). Not sure if this is related. Note these figures are zoomed in; the process stayed frozen, without crashing, for another 8 hours (still hanging).
![network_traffic](https://user-images.githubusercontent.com/56408839/119039970-b687f480-b969-11eb-9a5b-865c7fc972e9.png) ![gpu_util](https://user-images.githubusercontent.com/56408839/119040021-c6073d80-b969-11eb-9857-2c081d927535.png)

Output of running `strace -p` on the hung process is also [attached](https://github.com/wandb/client/files/6518443/strace.txt).

Potentially relevant excerpt:

```
[pid 1966949] futex(0x7fe6d80016b0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff <unfinished ...>
[pid 1966782] write(14, "\0\0\0y\200\3cwandb.proto.wandb_interna"..., 125) = 125
[pid 1966782] futex(0x7fe6e0000f50, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff <unfinished ...>
[pid 1966781] <... poll resumed> ) = 1 ([{fd=15, revents=POLLIN}])
[pid 1966781] read(15, "\0\0\0m", 4) = 4
[pid 1966781] read(15, "\200\3cwandb.proto.wandb_internal_pb"..., 109) = 109
[pid 1966781] futex(0x7fe6d80016b0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 1966949] <... futex resumed> ) = 0
[pid 1966781] <... futex resumed> ) = 1
[pid 1966949] futex(0x558e9becf004, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 353833, {1621533262, 492110000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
[pid 1966781] futex(0x558e9becf004, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x558e9becf000, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1} <unfinished ...>
[pid 1966949] futex(0x558e9becf000, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 1966781] <... futex resumed> ) = 0
[pid 1966949] <... futex resumed> ) = -1 EAGAIN (Resource temporarily unavailable)

```

**Environment**
- OS: Ubuntu 16.04
- Environment: slurm cluster with NFS
- Python Version: 3.6.13
- wandb version: 0.10.30

Happy to provide any other information possible to help identify the cause of this issue (if it is in fact wandb related, which it might not be).

**Comment by ariG23498** [comment]
Hey @eric-mitchell 
Thanks for the detailed issue. We will be tracking it internally.

**Comment by eric-mitchell** [comment]
@ariG23498 I should also note in case it's helpful, I'm seeing an error along the lines of:

`wandb: Network error resolved after 0:06:01.586198, resuming normal operation.`

showing up in a lot of the logs for the runs in which this issue occurs.

**Comment by vanpelt** [comment]
Hey @eric-mitchell both of these errors indicate you are having networking issues both to the NFS share and to the W&B server.  We retry all network requests to the W&B server so that should be fine, but I would suggest using a non networked filesystem for the wandb directory.  

When you call `wandb.init` you can specify the `dir` argument or you can set the WANDB_DIR environment variable to a path on your machine that isn't a networked file system, such as `/tmp`

**Comment by eric-mitchell** [comment]
@vanpelt thanks for the recommendation- I'll give this a try and report back.

**Comment by eric-mitchell** [comment]
Closing because

    wandb.init(..., dir=tempfile.mkdtemp())`

seems to have solved the problem. [This issue](https://github.com/wandb/client/issues/340) also suggests using

    username = pwd.getpwuid(os.getuid()).pw_name
    wandb.init(..., dir=f"/tmp/wandb_{username}"`

Thank you for the help @vanpelt and @ariG23498!
