### ISSUE TITLE
How to quickly delete the output.log files? And how to choose not uploading output.log files?

### ISSUE THREAD

**Issue by wizard1203** [wandb/client#2221]
Hi, when I conduct experiments, I print too many things out. So I have many output.log files, each of them is 60MB to 400MB large in every run. I want to delete these output.log files but not the wandb-summary.json files.

1.  How could I quickly delete these output.log files? I have run thousands of experiments, it is too difficult to manually choose them and delete.
2. Could I choose not to upload output.log files in my python programs?

**Comment by vanpelt** [comment]
Hey @wizard1203 you can use our api to delete the files:

```
runs = api.runs("username/project")
for run in runs:
    log = run.file("output.log")
    if log:
        log.delete()
```

You can set the WANDB_IGNORE_GLOBS environment variable to "output.log" which should prevent that file from being uploaded.  Unfortunately there's currently a bug that uploads that file even when the environment variable is set.  I'm working on a fix which should come in the next release.

**Comment by wizard1203** [comment]
> Hey @wizard1203 you can use our api to delete the files:
> 
> ```
> runs = api.runs("username/project")
> for run in runs:
>     log = run.file("output.log")
>     if log:
>         log.delete()
> ```
> 
> You can set the WANDB_IGNORE_GLOBS environment variable to "output.log" which should prevent that file from being uploaded. Unfortunately there's currently a bug that uploads that file even when the environment variable is set. I'm working on a fix which should come in the next release.

Thank you very much. I will try this.

**Comment by wizard1203** [comment]
Thanks! It works well !  @vanpelt
