### ISSUE TITLE
[CLI] Wandb does not log wandb.Histogram

### ISSUE THREAD

**Issue by nbortych** [wandb/client#2232]
**Description**
I am trying to log a histogram and even the simplest examples do not work. However, logging scalars work. 

**Wandb features + How to reproduce**

` 
wandb.log({"histogram": wandb.Histogram([1,2,3])})
`
The above line does not log anything and does not give any errors. If I submit a np_histogram, it also fails. Logging integers work. 

**Environment**
- OS: Mac OS Catalina 10.15.5
- Environment: venv
- Python Version: 3.9
- wandb version: 0.10.31

**Comment by vanpelt** [comment]
I just tried this and was able to see a histogram in my workspace.  Can you share a link to the specific run that isn't displaying a histogram for you?  Also, a histogram is generally more useful when it's summarizing a larger vector.  Have you tried passing `np.random.uniform(size=1000)` to wandb.Histogram?

**Comment by nbortych** [comment]
Thanks a lot for a quick reply. I just saw by going inside the run-level workspace that the histogram is being displaced there, but not at the project level. It makes sense since I guess it's hard to display multiple histograms in the same graph. 
Sorry for bothering and thanks for pointing me to finding the issue!
