### ISSUE TITLE
能不能支持手机查看训练过程？[Q]

### ISSUE THREAD

**Issue by zjp9574** [wandb/client#2238]
能不能支持手机查看训练过程？

**Comment by tyomhak** [comment]
We don't have a dedicated app, but you can always use a mobile internet browser for viewing your workspace :)

**Comment by SonicCodes** [comment]
@zjp9574 I've published a polished & efficient WandB mobile client,

For iOS: https://apps.apple.com/us/app/wandview/id6477268896?platform=iphone
For Android: https://play.google.com/store/apps/details?id=com.read21.wandview.wandview&hl=en&gl=US
