### ISSUE TITLE
[Q] How to update wandb.plot.histogram iteratively?

### ISSUE THREAD

**Issue by NumberChiffre** [wandb/client#2241]
Hello Everyone,

I'm looking to update wandb.plot.histogram() for every k steps during training. It seems every time I can wandb.log() on the table, it just overwrites previous steps. I was wondering if there's a way to append the existing histogram other than saving previous steps locally.

Thanks in advance!

**Comment by cvphelps** [comment]
@NumberChiffre I recommend using wandb.Histogram() instead, this allows you to see all steps in one histogram

**Comment by NumberChiffre** [comment]
@cvphelps Thanks for the reply, I did use `wandb.Histogram()`. For my specific case, I have a step counter that aggregates many episodes (in reinforcement learning term), and another step counter that keeps track of episode counts, then another to keep track of the number of steps (an episode has many steps). I think its easier to just store the episode/step data and plot them in Matplotlib then post on wandb if needed.
