### ISSUE TITLE
[CLI] Recursion error when saving a numpy array with dtype float 128

### ISSUE THREAD

**Issue by GeraldCSC** [wandb/client#2255]
**Description**
Hi there, there seems to be a bug when trying to log a np.float128 array onto wandb. It ends up giving a "RecursionError: maximum recursion depth exceeded in comparison" error. Code to reproduce it is attached below. 

**Wandb features**
wandb.log and init. 

**How to reproduce**
```python
import numpy as np
import wandb
wandb.init()
x = np.float128(0.0)
wandb.log({"test": x})
```

**Environment**
Weights and Biases version: 0.10.31
Python version: 3.9.5

**Comment by vanpelt** [comment]
Hey @GeraldCSC we've fixed this and hope to get a new release out with the fix this week.

**Comment by GeraldCSC** [comment]
thank you!
