### ISSUE TITLE
Boxplot wrong range in reports[App] 

### ISSUE THREAD

**Issue by mjohenneken** [wandb/client#2256]
**Describe the bug**
A picture says more than a thousand words. 

The position and range of the vertical boxplot is plotted wrong. In the first screenshot, the range of the green plot is visible.

**To Reproduce**
It's not clear to me why it happens.
- Originally the issue was on two plots. I managed to fix one by deleting it and recreating it. 
- Reloading of the page does not help
- Maybe a numeric issue due to small numbers?
- Happens only in vertical box plots

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5088045/120939103-981a4b00-c716-11eb-869e-e8454e93d289.png)

![image](https://user-images.githubusercontent.com/5088045/120939118-b8e2a080-c716-11eb-8292-581421da21a9.png)

**Operating System**
 - OS: Windows 10
 - Browser Brave
 - Version Version 1.25.68 Chromium: 91.0.4472.77 (Offizieller Build) (64-Bit)

**Additional context**
If it helps i can give a wandb person a link to the report.

**Comment by cvphelps** [comment]
Oof thanks for reporting this

**Comment by cvphelps** [comment]
@mjohenneken could you please share a link to the page where this box plot issue was showing up for you?

**Comment by mjohenneken** [comment]
I shared the panel via mail

**Comment by cvphelps** [comment]
Hi @mjohenneken what email did you send your repro to? Could you please message support@wandb.com?

**Comment by lukas** [comment]
I believe that @altay fixed this by upgrading our plotting library - thanks so much for flagging this and please reopen if it is not fixed on your end.
