### ISSUE TITLE
[Q] Is it possible to recursively upload a tensorboard directory?

### ISSUE THREAD

**Issue by cinjon** [wandb/client#2259]
I don't see a way to do this in the docs, but could just be missing it.

**Comment by vanpelt** [comment]
`wandb sync path_to_tensorboard_dir`.  If you have multiple experiments, you'll want to call `wandb sync` for each experiment directory.  You can also do this via python with:

```
api = wandb.Api()
api.sync_tensorboard(path_to_tensorboard_dir)
```

**Comment by vanpelt** [comment]
Here's a link to the SDK method: https://github.com/wandb/client/blob/master/wandb/apis/public.py#L259
