### ISSUE TITLE
[CLI] Sweep creation name parameter

### ISSUE THREAD

**Issue by manuel-delverme** [wandb/client#2281]
Usage: wandb sweep [OPTIONS] CONFIG_YAML_OR_SWEEP_ID

  Create a sweep

Options:
  -p, --project TEXT  The project of the sweep.
  -e, --entity TEXT   The entity scope for the project.
  --controller        Run local controller
  --verbose           Display verbose output
  --name BOOLEAN      Set sweep name
  --program BOOLEAN   Set sweep program
  --update TEXT       Update pending sweep
  --stop              Finish a sweep to stop running new runs and let
                      currently running runs finish.
  --cancel            Cancel a sweep to kill all running runs and stop running
                      new runs.
  --pause             Pause a sweep to temporarily stop running new runs.
  --resume            Resume a sweep to continue running new runs.
  --help              Show this message and exit.

I'm expecting to see
  --name TEXT      Set sweep name
i get:
  --name BOOLEAN      Set sweep name

**Comment by tyomhak** [comment]
Hey @manuel-delverme , can you please share the details on how you got this? Also, which wandb version are you using?

**Comment by vanpelt** [comment]
This llkes a bug, we should change this line to be `default=None` instead of `default=False`

**Comment by manuel-delverme** [comment]
I'm not able to reproduce it myself, but it was in a bug report for my repo (https://github.com/ministry-of-silly-code/experiment_buddy/)
![image](https://user-images.githubusercontent.com/1309922/121943527-f74d1080-cd51-11eb-8278-48e13a63b138.png)

https://github.com/wandb/client/commit/b653c333680a71b77956dfd9b39a95798d719c8c#diff-7a44f7c1d012d75ecf9ae33152ba567bdf056ba3998cc86948298cd34508b564  introduces some changes to the sweep interface if that can help, there should be a bool default that gets inferred wrongly.

**Comment by adrnswanberg** [comment]
Looks like this has since been fixed. Closing..
