### ISSUE TITLE
[App] Visualize bbox wrong

### ISSUE THREAD

**Issue by honguyenhaituan** [wandb/client#2290]
**Describe the bug**
The visualize bbox image in wandb don't correct when image has different size. 

**To Reproduce**
1. I change code yolov5 to save the original image
```
def cvtOriginalImage(image, shape): 
    ori_shape, (ratio, (dw, dh)) = shape
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    org_image = image[:, top : -bottom, left : -right]
    org_image = F.interpolate(org_image.unsqueeze(dim=0), ori_shape)

    return org_image.squeeze(dim=0)
```
```
org_image = cvtOriginalImage(img[si], shapes[si])
box_data = [{"position": {"minX": xyxy[0], "minY": xyxy[1], "maxX": xyxy[2], "maxY": xyxy[3]},
                                "class_id": int(cls),
                                "box_caption": "%s %.3f" % (names[cls], conf),
                                "scores": {"class_score": conf},
                                "domain": "pixel"} for *xyxy, conf, cls in predn.tolist()]
boxes = {"predictions": {"box_data": box_data, "class_labels": names}}  # inference-space
wandb_images.append(wandb_logger.wandb.Image(org_image, boxes=boxes, caption=path.name))
```
```
if wandb_images:
    wandb_logger.log({"Bounding Box Debugger/Images": wandb_images})
```
2. Click see "Bounding Box Debugger/Images" on the web 

**Expected behavior**
The bbox correct visualize in each image.

**Screenshots**

![image](https://user-images.githubusercontent.com/85393497/121992113-2eabd380-cdcb-11eb-8b6b-253b521179be.png)

Anh this is a image i download from it
![image](https://user-images.githubusercontent.com/85393497/121992354-ab3eb200-cdcb-11eb-9c26-4f38f0742fae.png)

It prove the visulize in the web wrong not because i draw bbox wrong.

**Operating System**
 - Browser: Chrome Version 91.0.4472.101 (Official Build) (64-bit)

**Comment by jsbroks** [comment]
Hi @honguyenhaituan, sadly this is a known issue.

We have plans to fix this but currently it requires a large underlining change. You should be seeing an [warning message](https://github.com/wandb/client/pull/1477) when logging images of different sizes.

Alternatively you can give [tables](https://docs.wandb.ai/guides/data-vis) a try which should not have the same issue.

**Comment by ayushjain1144** [comment]
Hi @jsbroks,

I also faced the same issue, and after hours of debugging, I found this issue. I am using WandB Version: 0.10.33 which is the latest pip version, and it didn't throw a warning for me. It would be very useful if you add this bug description in docs till the time its not fixed. Thanks for the awesome work on wandb, really appreciate it!

**Comment by jsbroks** [comment]
@ayushjain1144 Do you have a snippet of code I could look at for how you are logging the images? We must be missing a excution path in this warning message.

**Comment by ayushjain1144** [comment]
Hi @jsbroks, sure here it is:

```
display_ids = {"t1": 0, "t5": 1, "gt": 2}
class_id_to_label = { int(v) : k for k, v in display_ids.items()}
all_boxes = []
for i, pred_box in enumerate(sorted_boxes[:5]):
    if i==0:
        class_id = 0
        key_label = "t1"
    else:
        class_id = 1
        key_label = "t5"
    box_data = {
        "position": {
            "minX": pred_box[0].item(),
            "minY": pred_box[1].item(),
            "maxX": pred_box[2].item(),
            "maxY": pred_box[3].item()
        },
        "class_id": class_id,
        "box_caption": f"{key_label} {sorted_scores[i]:.2f}",
        "domain": "pixel",
        "scores": {"score": sorted_scores[i]}
    }
    all_boxes.append(box_data)

gt_box_data = {
    "position": {
            "minX": converted_bbox[0],
            "minY": converted_bbox[1],
            "maxX": converted_bbox[2],
            "maxY": converted_bbox[3]
        },
        "class_id": 2,
        "box_caption": "gt",
        "domain": "pixel",
        "scores": {"score": 1.0}
}
all_boxes.append(gt_box_data)

# log to wandb image
box_image = wandb.Image(
    self.imgs[image_id],
    boxes = {"predictions": {"box_data": all_boxes, "class_labels" : class_id_to_label}},
    caption = img_info["caption"]
)
wandb.log({"vis": box_image})
```
