### ISSUE TITLE
[Q] Is there a way to merge sweeps?

### ISSUE THREAD

**Issue by artur-deluca** [wandb/client#2303]
Hello everyone,

I've executed two random sweeps with the same set of hyperparameters. I was wondering if it's possible to bundle their runs and analyze them all at once as a single sweep.

Thanks in advance!

**Comment by tyomhak** [comment]
Hey @artur-deluca , I think there's a couple of things you could do: 

1. Create a [Report](https://docs.wandb.ai/guides/reports), and add the runs from both sweeps to the run set.

or 

2. Seed a new Sweep ([docs](https://docs.wandb.ai/guides/sweeps/existing-project#seed-a-new-sweep-with-existing-runs)) with the runs from both of your sweeps that you want to join.

**Comment by artur-deluca** [comment]
Great! Thanks, @tyomhak
