### ISSUE TITLE
[CLI] (Sweep API) `wandb.errors.UsageError: 400 Bad Request: Failed to decode JSON object: Expecting property name enclosed in double quotes`

### ISSUE THREAD

**Issue by diegoquintanav** [wandb/client#2307]
**Description**
I have this sweep config

```python
d_input_names = "|".join(
    ["dim1", "dim2", "dim3", "dim4"]
)
d_output_names = "|".join(["dim_target"])
d_model = 64

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

sweep_config = {
    "name": "transformer-sweep",
    "method": "random",
    "metric": {"name": "val loss", "goal": "minimize"},
    "parameters": {
        "d_model": {"value": d_model},
        "q": {"value": int(sqrt(d_model))},
        "v": {"value": int(sqrt(d_model))},
        "h": {"value": int(sqrt(d_model))},
        "N": {"values": [2, 3, 4]},
        "attention_size": {"values": [100, 200]},
        "dropout": {"min": 0.1, "max": 0.4},
        "pe": {"value": None},
        "chunk_mode": {"value": None},
        "d_input_names": {"value": d_input_names},
        "d_input": {"value": len(d_input_names.split("|"))},
        "d_output_names": {"value": d_output_names.split("|")},
        "d_output": {"value": len(d_output_names)},
        "epochs": {"values": [10, 30, 50]},
        "device": {"value": str(device)},
        "lr": {"min": 1e-4, "max": 0.1},
        "window_size": {"values": [1, 2, 7, 31]},
        "loader_shuffle": {"values": [True, False]},
        "batch_size": {"values": [1, 10, 100]},
        "num_workers": {"value": 0},
        "overfitting": {"value": False},
        "scaling": {"values": ["normalize", "minmax"]},
    },
}
```

**Wandb features**
```python
sweep_id = wandb.sweep(sweep_config)
```

produces

```ipython
CommError: 400 Bad Request: Failed to decode JSON object: Expecting property name enclosed in double quotes: line 1 column 461 (char 460)
```

**How to reproduce**
Try to produce a sweep id with the config provided. 

I don't know how to debug it, It seems to be coming from https://github.com/wandb/client/blob/c4548d3871c4cbdd8c253e46c912c95205bbc7f6/wandb/sdk/internal/internal_api.py#L1243 or https://github.com/wandb/client/blob/c4548d3871c4cbdd8c253e46c912c95205bbc7f6/wandb/vendor/graphql-core-1.1/graphql/language/parser.py#L11, but in the end, the config is being parsed to YAML in https://github.com/wandb/client/blob/c4548d3871c4cbdd8c253e46c912c95205bbc7f6/wandb/sdk/internal/internal_api.py#L1336 which is not raising any errors.

I tried also

```python
from wandb.sdk.internal.internal_api import Api
_api = Api()
_api.upsert_sweep(sweep_config)
```

which raises the same error

**Environment**
- linux mint tricia
- Python '3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) \n[GCC 9.3.0]'
- wandb 0.10.31

**Comment by diegoquintanav** [comment]
The error disappears when I change the key `"N"` in `"parameters"` to anything else e.g. `"name"`. `"n"` also raises the error. :man_shrugging:

**Comment by cvphelps** [comment]
@diegoquintanav thank you for calling out this issue. @dannygoldstein could you please take a look? Might be related to your work on sweeps YAML validation
