### ISSUE TITLE
[CLI] Sweep on SLURM sbatch error: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by 7Z0nE** [wandb/client#2308]
**Description**
Running a sweep agent from a python script with wandb.agent results in a correct call of the training function but then at some point an error occurs:
```
Set SLURM handle signals.
wandb: Waiting for W&B process to finish, PID 1931794
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.01MB of 0.01MB uploaded (0.00MB deduped)^Mwandb: \ 0.01MB of 0.01MB uploaded (0.00MB deduped)^Mwandb: | 0.01MB of 0.01MB uploaded (0.00MB deduped)^Mwandb: / 0.01MB of 0.02MB uploaded (0.00MB deduped)^Mwandb: - 0.02MB of 0.02MB uploaded (0.00MB deduped)^Mwandb: \ 0.02MB of 0.02MB uploaded (0.00MB deduped)^Mwandb: | 0.02MB of 0.02MB uploaded (0.00MB deduped)^Mwandb: / 0.02MB of 0.02MB uploaded (0.00MB deduped)^Mwandb: - 0.02MB of 0.02MB uploaded (0.00MB deduped)^Mwandb: \ 0.02MB of 0.02MB uploaded (0.00MB deduped)^Mwandb:
wandb: Find user logs for this run at:******
wandb: Find internal logs for this run at: ******
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb:
wandb: Synced blooming-sweep-1: 
Run 88zsh0ib errored: ValueError('signal only works in main thread of the main interpreter')
wandb: ERROR Run 88zsh0ib errored: ValueError('signal only works in main thread of the main interpreter')
```

I noticed this error only occurs from an sbatch. Running the sweep from an srun works fine!
`signal only works in main thread of the main interpreter` is still printed to std out but there is no error and the training script keeps running.

**Wandb features**
wandb.agent()

**How to reproduce**
My training script cannot be shared. As soon as I have found the time to create a simple reproduction script I will update the issue.

**Environment**
- OS: [CentOS Linux]
- Environment: [e.g. conda, SLURM]
- Python Version: [eg. 3.9]

**Comment by tyomhak** [comment]
Hey @7Z0nE , thanks for reporting. 

re: As soon as I have found the time to create a simple reproduction script I will update the issue.
That would be great!

Also, can you confirm if this is the case with the latest wandb version?

**Comment by sydholl** [comment]
@7Z0nE we wanted to follow up on this and see if you had a reproducible script?
