### ISSUE TITLE
[App] No longer can use the relative time as the x-axis

### ISSUE THREAD

**Issue by vwxyzjn** [wandb/client#2316]
**Describe the bug**
Hello, reporting a bug here. It seems that in the newer version of the wandb client, I could no longer use the relative time as the x-axis. 
![bug](https://user-images.githubusercontent.com/5555347/123109073-edd63f00-d408-11eb-8cf7-9ac73004f8a4.gif)

**To Reproduce**
Here is a notebook that reproduces it: 

1. Go to https://colab.research.google.com/drive/1EBk2UU91dBrtcEGk790Cidp1FPGopX-p?usp=sharing
2. Run the notebook
3. Head to the generated run such as https://wandb.ai/wandb/cartpole_test/runs/iwpuk8m0?workspace=user-costa-huang
4. Play with any metircs by trying to change it x-axis to relative time
5. See the bug that you can't do that

**Expected behavior**
It was working in 0.9.*. For example, it works [here](https://wandb.ai/cleanrl/cleanrl.benchmark/runs/37cf7g9t/overview?workspace=)

**Operating System**
 - OS: linux
 - Browser chrome
 - Version 0.10.32

**Comment by tyomhak** [comment]
Hey @vwxyzjn , thank you for reporting this issue. We're looking into it.

**Comment by marcosfelt** [comment]
Any update on this?

**Comment by vwxyzjn** [comment]
@marcosfelt The latest release should have already fixed it
