### ISSUE TITLE
[Feature] show the historical curves based on the same step.

### ISSUE THREAD

**Issue by Sun-Rider** [wandb/client#2323]
I'm a beginner of the wandb, and I'm wondering is it possible to synchronize all the steps of the existing curves. From the observation, when I log the values based on the batch size, the existing curves might be really different. As you can see from the figure below,

![temp](https://user-images.githubusercontent.com/33716428/123219643-46423500-d50c-11eb-8a43-4cb39ba93504.png)

It will be nice if the curves can be automatically matching with others based on the step, and it will be much more easier for users to compare the result.

**Describe the solution you'd like**
a step matching operation.

**Comment by vanpelt** [comment]
@Sun-Rider if you're logging metrics at different intervals you can log a seperate metric as a unifying step.  Then you can choose a custom x-axis for all of your charts with the "X->" Icon in the upper right of your workspace or for individual metrics by editing the chart.  By default we increment our step counter every time you call `wandb.log`.  If you don't want us to increment that counter you can specify `commit=False` and then call `wandb.log` later in your code when you're ready to commit.  Here are some examples:

```
wandb.log({"global_batch": X, "global_epoch": Y, "loss": Z}, commit=False)
# Some other code
wandb.log({"acc": A}) # this increments the default step counter, but you could choose "global_batch" or "global_epoch" in the UI instead of using our default step counter.
```
