### ISSUE TITLE
[App] Bar Chart Design Issue and Legend missing in Boxplot

### ISSUE THREAD

**Issue by mjohenneken** [wandb/client#2329]
**Describe the bug**
The design of bar charts seems to have changed recently. The run_name is now displayed above the bars in the color of the run. While I think it is a valid way to label bar charts, I would argue that this is a less common way of doing it. But, I'm okay if the decision was made that this should be the new design. The old design allows for more runs in the same horizontal space. The new design allows for longer bars that visualize the differences of the runs better.

What bothers me is that the text is colored in the run color which results in low contrast and makes the legend hard to read (especially in a figure of a report). 
An additional problem is when the bar chart plot is configured as boxplot. The legend seems to be missing entirely in the new design.

**To Reproduce**
1. Create a report, with a panel
2. Add a bar chart
3. Observe the design
4. Edit the bar chart to show as box  plot
5. Observe the missing labels

**Expected behavior**
I would expect to have a legend in black font. If the font is black it might be not clear if the legend refers to the bar above or below. I would prefer the old design which makes it clear what the bar represents. But there might be other solutions.

**Screenshots**
*Old design*
![image](https://user-images.githubusercontent.com/5088045/123510985-fafc6380-d67e-11eb-8139-d8bc8c86239c.png)

*New design*
![image](https://user-images.githubusercontent.com/5088045/123511546-259beb80-d682-11eb-8a81-158d303c4de6.png)

*Missing legend*
![image](https://user-images.githubusercontent.com/5088045/123511295-c4274d00-d680-11eb-9ce5-bc4bec0d00a5.png)

**Operating System**
 - OS: Windows 10
 - Browser: Brave
 - Version 1.25.73 Chromium: 91.0.4472.106 (Offizieller Build) (64-Bit

**Additional context**
- happens only in horizontal bar charts

**Comment by mjohenneken** [comment]
I might add that the display of 0 (DSM) looks odd as well

**Comment by cvphelps** [comment]
Thanks for your recommendation. We had to move the legend so it's legible for long names. We can look at changing the color of the text.

**Comment by lukas** [comment]
Added the legend back to the bar plot - thanks so much for reporting this.
