### ISSUE TITLE
wandb.monitor(display=False) still displays run page inline

### ISSUE THREAD

**Issue by eric-czech** [wandb/client#233]
* Weights and Biases version: 0.6.18
* Python version: 3.5.2
* Operating System: Ubuntu 16.04.4
* JupyterLab version: 0.33.8

### Description

In a [JupyterLab] notebook, passing display=False to the monitoring context still shows the embedded stats widget.  Perhaps I misunderstood the docs, but they seem pretty clear that this flag should stop that (let me know if I've got that wrong).

<img width="326" alt="jupyter_screenshot" src="https://user-images.githubusercontent.com/6130352/45177109-f6214900-b1df-11e8-80fc-5551077ad816.png">

**Comment by vanpelt** [comment]
Hey Eric, we're actually in the process of refactoring our jupyter integration.  If you're up for trying it, you can run:  pip install --upgrade git+git://github.com/wandb/client.git@master#egg=wandb to get the edge version of our client.  The new version does away with `wandb.monitor` and only displays live results if you add `%%wandb` magic to the cell.  Let me know if you have any issues.

**Comment by eric-czech** [comment]
Ah ok cool, I'll try that instead.  Thanks Chris!
