### ISSUE TITLE
[Q] Avoid logging to local filesystem but continue sending logs to W&B servers

### ISSUE THREAD

**Issue by MatthewGleeson** [wandb/client#2332]
I'm running multiple training jobs on a computing cluster, which writes script outputs/W&B logs to my home directory. The cluster runs into problems when many compute nodes simultaneously try to create, read, or delete files in home directories, which causes jobs to fail. I'm experiencing this problem when I run more than a few training jobs with W&B logging.

I think my problem is that each W&B job is simultaneously trying to log training info to my home directory, which is causing jobs to fail. Is there a way to tell W&B to avoid logging to my home directory and instead send the logs directly to the W&B server?

**Comment by vanpelt** [comment]
You can set the WANDB_DIR environment variable or the dir keyword argument of wandb.init to write to an ephemeral disk such as /tmp.  For disaster recovery and buffering reasons we need to be able to write to disk.

**Comment by MatthewGleeson** [comment]
Thanks for the tip! I was able to get it working that way.
