### ISSUE TITLE
Parameters are not logged when model is watched with log='all'

### ISSUE THREAD

**Issue by zplizzi** [wandb/client#2342]
**Description**
This is the same bug as in #1471, which was closed without resolution of the problem.

When using `logger.watch(model, log='all', log_freq=1)`, the gradients are logged, but the parameters are not.

I am also using pytorch lightning, as was the author of that issue, so perhaps that's related.

**How to reproduce**

I don't have a clean way to reproduce. When I tried to reproduce the problem in this wandb lightning colab: http://wandb.me/lit-colab, everything worked as expected. I'm not sure what's different about my setup.

**Environment**
- ubuntu 18.04
- wandb version: '0.10.33'
- pytorch lightning version: '1.3.7post0`
- pytorch version: '1.9.0+cu102'

**Comment by vanpelt** [comment]
Hey Zack!  Good to know.  We recently refactored the hook logic but it looks like you're on the latest version.  Is it possible the other environment where this happened was using an older version of wandb?

**Comment by zplizzi** [comment]
Hey! The issue is definitely showing up on 0.10.33.

**Comment by cvphelps** [comment]
Hi @zplizzi thanks for letting us know! If you do manage to repro this, we'd love to get it fixed, but we haven't been able to track down the problem yet.

**Comment by zplizzi** [comment]
Totally understand. Not sure I have time to track it down at the moment but I'll circle back if I do.

**Comment by borisdayma** [comment]
We use Pytorch hooks to log the parameters.

Are you doing the forward step in a non standard way (without using `model(inputs)` which uses `model.__call__()`).
If so, that could explain the issue.

There may be a way also to log the parameters manually otherwise.

**Comment by zplizzi** [comment]
Aha, that's what it was - I was calling `model.forward(inputs)` instead of `model(inputs)`. Once I changed that the parameters are being logged properly. I'll go ahead and close this issue, although it might be worth adding a note to the docs to help other people who are confused like me :) Thanks for the help troubleshooting!
