### ISSUE TITLE
[CLI] Error when trying to disable wandb

### ISSUE THREAD

**Issue by santelelle** [wandb/client#2349]
**Description**
I am getting
`torch.nn.modules.module.ModuleAttributeError: '<my model name>' object has no attribute '_wandb_hook_names' `
when I try to disable wand either with the env variable WANDB_MODE=disabled or with wandb.init(mode='disabled')

**How to reproduce**
Minimal example
```
import wandb
import torch as th

wandb.init(mode='disabled')
# wandb.init()


class Model(th.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = th.nn.Conv2d(3, 9, 3)

    def forward(self, x):
        x = self.conv(x)
        return x


model = Model()

wandb.watch(model, log='all', log_freq=10)
```

**Environment**
- Ubuntu 20.04
- Python Version: 3.7
- Pytorch version 1.7.1
- Wandb 0.10.33

**Comment by cvphelps** [comment]
@borisdayma could you please take a look
