### ISSUE TITLE
[WB-5925][CLI] plot_feature_importances is plotting the features in the wrong order

### ISSUE THREAD

**Issue by alexandrehsd** [wandb/client#2351]
https://wandb.atlassian.net/browse/WB-5925

**Description**
The `plot_feature_importances` function is plotting the features in the wrong order because it sorts the `feature_names` array but it does not do the same to the `importances` array. Consequently, when the data is sent to the server, the `feature_names` does not match their respective importances.

**Wandb features**
This happens to the `plot_feature_importances` function in the `wandb.sklearn.__init__.py` file. 

**How to reproduce**
1. To see a reproducible example, go to: https://colab.research.google.com/drive/1_mPoemcaRGmTar4CIqBCPh5PsKSp5xC6?usp=sharing

In this colab notebook, I explain exactly what should be done and what WandB does.

2. To trigger the issue, you just have to fit any sklearn model that has the attribute `.feature_importances_` such as a `DecisionTreeClassifier`s
3. Access the run by clicking on https://wandb.ai/alexandre-hsd/issue_plot_feature_importances?workspace=user-alexandre-hsd

**Environment**
- OS: Ubuntu 20.04
- Python Version: 3.8.0
- Scikit-Learn Version: 0.24.1

**Comment by anmolmann** [comment]
Hi @alexandrehsd , thanks for reporting this. We do have an internal ticket already filed for this. We'll keep you posted once there's any progress.

**Comment by anmolmann** [comment]
Hey @alexandrehsd , just wanted to follow-up here. We deployed a fix for this issue.
