### ISSUE TITLE
[App] Cannot delete a run

### ISSUE THREAD

**Issue by santelelle** [wandb/client#2363]
**Describe the bug**
I am not able to delete a run (and relative artifacts). I am getting **context deadline exceeded**

**To Reproduce**
I tried in the following ways:

1. from workspace tab, press the 3 dots on the left of the run name -> **Delete run**. Select the checkbox **Delete ALL n output arifact(s)** and then press the button **Delete this run** 
2. from table tab, same procedure 
3. from table tab, checkbox the run and the press the **BIN** icon. Select the checkbox and then **Delete 1 run**

**Expected behavior**
Run (and relative artifacts) to be deleted

**Operating System**
 - OS: Ubuntu 20.04
 - Browser: Chrome 91.0.4472.106 (Official Build) (64-bit)
 - Version 

**Additional context**
The run has 738 artifacts

![image](https://user-images.githubusercontent.com/10034153/124474301-ab194d00-dda0-11eb-9efc-fa06953bd302.png)

**Comment by tyomhak** [comment]
Hey @santelelle , thank you for reporting this issue. We're looking into it.

**Comment by santelelle** [comment]
Hi, any news on this?

**Comment by annirudh** [comment]
Hi @santelelle, we're currently working on a fix for the issue. Apologies for the delay here, but we need to redo how deletion works so that artifacts are cleaned up in the background instead of immediately when the run is deleted. This is a fairly big change, but we're hoping to have a fix with the next week or two.

I will follow up here when we release a fix for the issue. We sincerely appreciate your patience.

**Comment by Mo-youssef** [comment]
Hi, any updates or workarounds?
My space usage is preventing me from running experiments

**Comment by vanpelt** [comment]
hey @Mo-youssef how is your space usage preventing you from running experiments?  Are you running out of disk space on your local machine?  This specific issue when deleting runs with lots of artifacts from the system should be fixed soon, but it currently doesn't prevent you running new experiments.

**Comment by Mo-youssef** [comment]
Sorry, I didn't clarify enough. I meant I can't log more experiments on wandb. It is great to know that this issue will be fixed soon.

**Comment by santelelle** [comment]
@annirudh any update? I have reached the 100GB limit but I cannot delete the old longest runs

**Comment by santelelle** [comment]
I am closing this as the issue is solved, I was able to delete my runs.

Thanks :)
