### ISSUE TITLE
[Q] Turn off wandb logging for part of the code

### ISSUE THREAD

**Issue by akshaykvnit** [wandb/client#2364]
I'm using wandb with inbuilt tensorboard sync i.e. `wandb.init(project='project_name', sync_tensorboard=True)`. Is there a way to stop wandb from logging a specific `writer.add_...` while logging others? 

For example, I have some `writer.add_scalar` and `writer.add_image` (for writing scalars like losses, metrics, etc. and visualizing images respectively). Since images take up a lot of memory and they would already be written to my local memory (since tensorboard), I want to avoid those getting logged in wandb. Is there some context manager type solution available (`with wandb.temporary_turn_off: .....`) or something else?

I suppose one solution would be to use the actual wandb commands instead of tensorboard but is there any other simpler solution?

**Comment by vanpelt** [comment]
Hey @akshaykvnit currently there are no ways to control the granularity of which tensorboard events are logged.   I'm curious what kinds of memory issues you're seeing, we flush images to disk as we get them so we shouldn't cause aggresive memory pressure on your instance.
