### ISSUE TITLE
[Q]Why do the pictures keep changing?

### ISSUE THREAD

**Issue by yllgl** [wandb/client#2370]
I use pytorch_lightning, and I found that trainer/global_step keeps changing in the wandb, I don't know why.
![picture](https://user-images.githubusercontent.com/23625282/124711137-4856bb80-df30-11eb-87a1-a311009bd9e1.gif)

**Comment by tyomhak** [comment]
Hey @yllgl , was the run still running when you saw this happen?
Could you share the url link to this run so we could check it out?

**Comment by vanpelt** [comment]
"trainer/global_step" is a metric that's being logged against our default auto incrementing step.  The 0 value may indicate there was no value for "trainer/global_step"in that call to `wandb.log`.  If you can share a link to a run we can further diagnose how the data is coming in.
