### ISSUE TITLE
[Q] Custom number of columns in each Panel

### ISSUE THREAD

**Issue by nero1342** [wandb/client#2382]
I plot 3 images, each image contains two kinds of masks (Prediction, Ground Truth).
When it was display in wandb.ai, the size of them is too small because the columns in panel here is 8 automatically. I need to go into "Edit Panel" and set the number of columns to 3 for better display.

So are there any ways to set the columns of the panels when I log them in python? 

Thanks

**Comment by vanpelt** [comment]
@nero1342 currently there isn't a way to do this programmatically but we'll track this feature request here.

**Comment by cvphelps** [comment]
@nero1342 I actually think this is a great case for our new feature, Tables, which allows you to log rows of examples with columns for sample - prediction - ground_truth

Tables Docs: https://docs.wandb.ai/guides/data-vis

Sample screenshot: 
![image](https://user-images.githubusercontent.com/6355078/127966805-04ce8a64-2395-4af0-a872-bf6efa868c74.png)
