### ISSUE TITLE
[App] Unexpected value of custom step x-axis when visualising a plot from the groups

### ISSUE THREAD

**Issue by loicsacre** [wandb/client#2384]
**Describe the bug**
When visualising a plot from the groups , there is an error with the value of the custom step when going with the cursor over the line. The problem does not appear when visualising a plot directly from a run.

**Expected behavior**
The value of the custom step should correspond to what has been logged.

**Screenshots**

Here is a plot visualisation from the groups (the step shown should be 30000 and not 33912.652)
![Screenshot 2021-07-12 at 11 29 33](https://user-images.githubusercontent.com/32166486/125266466-241b2600-e306-11eb-90a1-b817a02f3d83.png)

Here is a plot visualisation from the run (the step is 30000)
![Screenshot 2021-07-12 at 11 29 26](https://user-images.githubusercontent.com/32166486/125266475-254c5300-e306-11eb-9140-ecaa3bccf8d9.png)

**Comment by vanpelt** [comment]
@loicsacre when we group runs that don't have x-axis that line up exactly, we create buckets or windows across the group of runs to show values in the same "bucket".  Can you share a link to a workspace that has the grouping configured so we can verify that's what's happening here?

**Comment by loicsacre** [comment]
I don't know how to share a link which would be visible to anyone, but here it is https://wandb.ai/integria/experiment-1-tf/groups/INTEGRIA-609/workspace. The only group which is set to visible is Job Type: task_1. All the runs among the group have a log every 10k 'global_step'.

**Comment by vanpelt** [comment]
Hey @loicsacre I've verified that discrepancy is due to the bucketing logic (W&B support staff can access private experiments for debugging purposes).  We randomly sample points from each series and when the "global_step"s that were sampled don't line up exactly we show the data that shares the same bucket.

**Comment by loicsacre** [comment]
Hi @vanpelt, sorry for coming back to this issue a bit later. I understand the way you handle it. However, wouldn't it be better not to sample randomly if all points have the same abscissa ? It would be more convenient for both visualising and reporting. It think it would be useful for others too. I have noticed that the problem does not occur when using the default `step` metric. Maybe we are doing something wrong when logging our custom `training step` (which is logged during the single `wandb.log()` call after each training iteration ?

**Comment by loicsacre** [comment]
I think this problem is linked too. When visualising according to default `step` metric, everything is ok and all the points are displayed. Nevertheless, when switching to the `training step` metric, the number of points is reduced and therefore it is difficult to compare the graphs. We clearly see that the look of the graph is no longer the same.

![Screenshot 2021-08-17 at 14 48 53](https://user-images.githubusercontent.com/32166486/129728534-e98a0e88-2dd3-47e6-91ed-0f6c1619cfde.png)
![Screenshot 2021-08-17 at 14 49 20](https://user-images.githubusercontent.com/32166486/129728530-0bc41790-4c51-46e4-8be4-099983e35695.png)

**Comment by vanpelt** [comment]
@loicsacre unfortunately this is due to the way we need to sample metrics to avoid too much data being rendered in the browser.   Because your steps have such a large span across 1.5 million training_steps we're sampling more aggressively then when you're only looking at a span of 25 steps.

**Comment by loicsacre** [comment]
Yes but there is not millions of points, the training_step is just a label. We only log 1 value every N training_steps, resulting in only 25 points per curve.

Maybe the condition that is used to trigger the bucketing logic should look at the number of points to render instead of the value of the span of the abscissa?
