### ISSUE TITLE
[App] Certain table names cannot be displayed in the app

### ISSUE THREAD

**Issue by vwxyzjn** [wandb/client#2385]
**Describe the bug**

Consider the following snippet to log some `wandb.Table` data
```python
import wandb
import pandas as pd
run = wandb.init(
    project="table_bug",
    save_code=True,
)
data = pd.DataFrame({'workerRushAI': [0, 0, 10], 'agent_sota.pt': [0, 0, 5]}, index=["win", "tie", "loss"]).T
wandb.log({"this_name_works": wandb.Table(dataframe=data.reset_index(level=0))})
wandb.log({"this_name_does_not_work.pt": wandb.Table(dataframe=data.reset_index(level=0))})
```

By running the code above, you will see a run like [this](https://wandb.ai/costa-huang/table_bug/runs/2i2wimma?workspace=user-costa-huang0, where the app does not display the table with the name `this_name_does_not_work.pt`, whereas it displays the table with the name `this_name_works`.

![image](https://user-images.githubusercontent.com/5555347/125333218-fa6afa80-e317-11eb-90ce-a30dedbd3ee2.png)

However, the data is actually logged and accessible in the [artifact page](https://wandb.ai/costa-huang/table_bug/artifacts/run_table/run-2i2wimma-this_name_does_not_workpt/33b458f77281cac458aa/files/this_name_does_not_work.pt.table.json). 

![image](https://user-images.githubusercontent.com/5555347/125333510-53d32980-e318-11eb-99f4-f779624e0d38.png)

**Operating System**
 - OS: Linux
 - Browser chrome

**Comment by tyomhak** [comment]
Hey @vwxyzjn , thanks for reporting this issue. We're looking into it.

**Comment by sydholl** [comment]
Hi @vwxyzjn! This issue has been fixed. Please let us know if you're still experiencing issues.
