### ISSUE TITLE
[CLI] Media data not synced locally

### ISSUE THREAD

**Issue by SirWyver** [wandb/client#2404]
**Description**
When working offline and syncing locally, media files are missing. Other logging information are shown but images for examples are not synced.
<img src="https://user-images.githubusercontent.com/19650385/125968148-d1430b03-7d89-49fc-82c6-cd2c0eb1ed80.png"  height="500">

**Wandb features**
```python
wandb.init
wandb.Image
wandb.log
```

**How to reproduce**
```python
import wandb
import os
import numpy as np

os.environ["WANDB_MODE"] = "offline"
wandb.init(project="my_project")
for i in range(100):
    wandb.log({"loss": 100 - i, "accu": float(i) / 10.0})
    if i % 10 == 0:
        image = wandb.Image(np.random.randint(0, 255, (320, 300, 3)), caption=f"{float(i)}")
        wandb.log({f"image/{i}": image})`

```
**Environment**
- OS: Fedora 34
- Environment: localhost
- Python Version: 3.7.0
- wandb: 0.11.0

**Comment by cvphelps** [comment]
This looks like a high priority issue to investigate for us, thank you for reporting it. To clarify, do you mean you're using a W&B Local install instead of our hosted cloud?

**Comment by tanmayshankar** [comment]
I've been facing this issue too today, but not with the offline mode. 
Wandb version 0.8.35. 
Python: 3.6.9.

**Comment by SirWyver** [comment]
> This looks like a high priority issue to investigate for us, thank you for reporting it. To clarify, do you mean you're using a W&B Local install instead of our hosted cloud at wandb.ai?

Yes exactly, I'm using  W&B local install (self-hosted). 
I am not sure if this is related but I pulled the latest W&B image, the build.yaml inside the docker says:  
```
buildDate: 2021-07-01
gitHash: 482ffb9e8
version: 0.9.42
```
but I still get the message: "A new version of W&B local is available"

**Comment by vanpelt** [comment]
Hey @SirWyver there's a chance the queue wasn't properly configured in version 0.9.42.  We have a fix going out in the next release, but you can manually fix your instance by running:

```
docker exec -it wandb-local bash
mc event add local/local-files arn:minio:sqs:wandb-local:_:redis --event put
```

**Comment by SirWyver** [comment]
> Hey @SirWyver there's a chance the queue wasn't properly configured in version 0.9.42. We have a fix going out in the next release, but you can manually fix your instance by running:
> 
> ```
> docker exec -it wandb-local bash
> mc event add local/local-files arn:minio:sqs:wandb-local:_:redis --event put
> ```

Amazing, this fix solved the issue, thanks a lot!
