### ISSUE TITLE
[App] Dragging to resize images sometimes crashes the Report page.

### ISSUE THREAD

**Issue by scottire** [wandb/client#2409]
**Describe the bug**
In a Report, when I drag a side of an image to resize, it crashes the page sometimes.

**To Reproduce**
1. Go to a Report with an image ([mine](https://wandb.ai/wandb/wandb_spacy_integration/reports/-insert-NLP-task-using-spaCy-and-Weights-Biases--Vmlldzo4NjM2MDk/edit))
2. Click on the side of an image
3. Drag right or left

**Expected behavior**
When I drag a side of an image, it should adjust the size of the image.

**Screenshots**
![ezgif-3-f1c142cc09da](https://user-images.githubusercontent.com/8557070/126158235-d51a01f5-9891-4ecd-af7b-105ad61528d9.gif)

**Operating System**
 - OS: macOS Big Sur 11.4
 - Browser: Safari & Chrome
 - Version Safari 14.1.1, Chrome 91.0

**Additional context**
I asked someone to reproduce and they couldn't so it seems to be an issue with my setup. It also works now, so it seems to only be an issue sometimes.

**Comment by tyomhak** [comment]
Hey @scottire , thanks for reporting. I'm afraid I'm unable to reproduce it as well. 
Please let us know if you keep getting this crash.

**Comment by scottire** [comment]
Ok, I will do. Closing for now.
