### ISSUE TITLE
[Q] Sweep: Separate each run in a group

### ISSUE THREAD

**Issue by kangsan0420** [wandb/client#2415]
Hi, I'm using Sweep but all runs in a group are represented as a single curve. How can I detach each run from a group so that each run can be represented to each curve?

**Comment by vanpelt** [comment]
Hey @kangsan0420 you can remove the "group" from the table you're viewing.

![image](https://user-images.githubusercontent.com/17/126344250-1ea977e1-0990-4181-9a02-b6fc416d9536.png)
