### ISSUE TITLE
[CLI] Permission denied: '/users' on remote cluster from `wandb agent`

### ISSUE THREAD

**Issue by tom-andersson** [wandb/client#2420]
I'm trying to run a sweep on a remote cluster via SLURM by executing the `wandb agent` command within a SLURM script. I'm getting a `PermissionError` because some `wandb` default directory is set to my user's home directory, but I'm unable to access `/users` via SLURM. I've tried setting `WANDB_DIR`, `WANDB_CONFIG_DIR`, and `WANDB_CACHE_DIR` environment variables before importing `wandb`, but this hasn't fixed it. `wandb` must have some other default path set to my home directory -- what could this be?

wandb version: 0.11.0
Python version: 3.7.6

Here's the full stack trace:
[log.txt](https://github.com/wandb/client/files/6850440/log.txt)

**Comment by vanpelt** [comment]
Hey @tom-andersson that specific stack trace is coming from [here](https://github.com/wandb/client/blob/master/wandb/old/settings.py#L105).  `env.CONFIG_DIR` is `WANDB_CONFIG_DIR`.  Can you ensure this is being set a writable directory.  I would suggest something like `os.environ["WANDB_CONFIG_DIR"] = "/tmp"`.

**Comment by vanpelt** [comment]
It only needs to be set before you call `wandb.init`

**Comment by tom-andersson** [comment]
Thanks for the info @vanpelt. That's weird, I already have that exact `os.environ` command before `wandb.init` in my train script. Perhaps I'm doing something stupid. In the meantime, could there be any other possible solutions?

**Comment by tom-andersson** [comment]
Update: This error only occurs when running sweeps on SLURM via `wandb agent`. I'm able to run my train script directly and log stuff to `wandb` with no problem.

Is there any way I can access `env.CONFIG_DIR` to debug?

**Comment by vanpelt** [comment]
Very strange.  `env.CONFIG_DIR` can be accessed by reading `os.environ["WANDB_CONFIG_DIR"]`.  You might need to set the environment variable before executing `wandb agent`.  For example:

```
WANDB_CONFIG_DIR=/tmp wandb agent username/project/sweep_id
```

**Comment by tom-andersson** [comment]
Thanks @vanpelt. Adding the environment variable declaration to the SLURM script before running `wandb agent` hasn't fixed it. The agent command isn't getting to the point of running my train script, so it must be relying on some default config dir path before getting to my train script where I set it to a writable directory.

**Comment by vanpelt** [comment]
@tom-andersson can you share the logs / stacktrace you're getting now.  You may also need to specify the `WANDB_DIR` env variable with the agent as well.

```
WANDB_CONFIG_DIR=/tmp WANDB_DIR=/tmp wandb agent username/project/sweep_id
```

**Comment by tom-andersson** [comment]
@vanpelt Wandb is still using the default dir in `/users` - see stack trace below
[log.txt](https://github.com/wandb/client/files/6894916/log.txt)

And this is with the following in my SLURM script:

```
WANDB_CONFIG_DIR=/local/tmp/                           
WANDB_DIR=/local/tmp/                                  
WANDB_CACHE_DIR=/local/tmp/                            
wandb agent <agent-id> > log.txt 2>&1
```

**Comment by vanpelt** [comment]
Hey @tom-andersson are you sure they are actually set in the environment?  If the SLURM script is running bash you would need to do:

```
export WANDB_CONFIG_DIR=/local/tmp/                           
export WANDB_DIR=/local/tmp/                                  
export WANDB_CACHE_DIR=/local/tmp/                            
wandb agent <agent-id> > log.txt 2>&1
```

**Comment by vanpelt** [comment]
Or the following would also work:

```
WANDB_CONFIG_DIR=/local/tmp/ WANDB_DIR=/local/tmp/ WANDB_CACHE_DIR=/local/tmp/ wandb agent <agent-id> > log.txt 2>&1
```

**Comment by tom-andersson** [comment]
Thanks again @vanpelt and apologies for the delay while I've not been working on this. I just tried the `export` commands and it seems to have worked, but I've run into a new issue where `wandb agent` is saying I'm not logged in, despite running `wandb login <api-key>` beforehand. Here is my [log.txt](https://github.com/wandb/client/files/7212726/sweep.txt)

**Comment by vanpelt** [comment]
Hey @tom-andersson `wandb login API_KEY` writes the credentials to the current users home directory.  If the `wandb agent` is being run as a different user it can't pick up these creds.  The simplest fix is likely to specify the API_KEY as an environment variable:  `WANDB_API_KEY=<api-key> wandb agent <username/project/agent-id>`

**Comment by tom-andersson** [comment]
Hey @vanpelt, I tried that (replacing `wandb login` with `export WANDB_API_KEY=...` in the slurm script just before the agent command) just as you replied and........... it did the trick!!!! Amazing. So great to be able combine wandb sweeps with slurm. Thanks again.
