### ISSUE TITLE
[Q] Bar chart with multiple variables on same plot

### ISSUE THREAD

**Issue by MatthewGleeson** [wandb/client#2424]
The wandb dashboard automatically creates separate bar charts for each variable in an experiment I'm running. I want to create bar chart with 2 variables displayed on the same chart. 

Is there a way to do this without writing a custom vega specification? If not, I was reading online that I need to flatten the data first, is this the correct approach?

**Comment by vanpelt** [comment]
Hey @MatthewGleeson you can explicitly log a bar chart for a specific run using our [custom charts](https://docs.wandb.ai/guides/track/log#custom-charts) functionality.

```
data = [[label, val] for (label, val) in zip(labels, values)]
table = wandb.Table(data=data, columns = ["label", "value"])
wandb.log({"my_bar_chart_id" : wandb.plot.bar(table, "label",
                               "value", title="Custom Bar Chart")
```
