### ISSUE TITLE
[Q]how to save chart

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2427]
how can I save and download chart exactly?

**Comment by vanpelt** [comment]
![image](https://user-images.githubusercontent.com/17/126548424-e97d9ebb-bf68-414d-8cfd-6bb6cf0eb4b2.png)

Does that make sense?

**Comment by vanpelt** [comment]
You get that menu by hovering over a chart in the UI and clicking the 3 vertical dots.

**Comment by besbesmany** [comment]
Thank you so much
