### ISSUE TITLE
[Q] how to decrease steps of x access for some experiments in chart

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2430]
I want to decrease steps to 200 for x axis so all experiments have the same x axis value(steps)

![W B Chart 7_21_2021, 9_57_36 PM](https://user-images.githubusercontent.com/35992924/126552112-cc693ffe-90cf-4fbb-92ef-b4bd988360bd.png)

**Comment by vanpelt** [comment]
You can click the "pencil" icon in the upper right of the chart when you hover over it.  That will open the edit modal.  From there you can set the "Max" value of the "X-Axis" property to 200.

**Comment by besbesmany** [comment]
thanks so much
