### ISSUE TITLE
[Q] how to draw hyperparameter chart

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2442]
I want to draw chart like this in yolov5

what should I do please?

![10](https://user-images.githubusercontent.com/35992924/126874805-7b61e649-452a-4b5a-8c90-a2e30ceb5a2a.png)

**Comment by vanpelt** [comment]
In your workspace, click the "+" button on the right of the screen and choose "Parallel Coordinates"

![image](https://user-images.githubusercontent.com/17/126908846-5f2e6c4d-2ceb-4c54-ab2a-aac3f8ac0b87.png)

**Comment by besbesmany** [comment]
thank you sir
