### ISSUE TITLE
[App] Logging image tables

### ISSUE THREAD

**Issue by sachinruk** [wandb/client#2446]
Hi all, I'm trying to log images as tables and have the following simple example which isn't working with PyTorchLightning WandbLogger. Just wondering if I'm doing anything obviously wrong. Thanks in advance.

```python
logger = WandbLogger("DINO", "/kaggle/working/logs/", project="DINO")

rows = []
for _ in range(5):
    idx = np.random.choice(10000, 5)
    rows.append([wandb.Image(files[i]) for i in idx])
columns = [str(i) for i in range(5)]
table = wandb.Table(data=rows, columns=columns)

logger.experiment.log({"test table 2": table})
```

wandb version: `'0.10.26'`

On the wandb page, all I see is this (stating "Weave expressions are limited to 25 runs. Of the first 25 runs selected, none have data to visualize for the provided expression."): 
![image](https://user-images.githubusercontent.com/1410927/126891727-7b812883-56b4-46b7-8108-f52f77a6e6d8.png)

**Comment by vanpelt** [comment]
Hey @sachinruk I would definitely suggest upgrading your wandb library.  However, the issue you're seeing is likely exactly what the error message says.  In your workspace can you add some filters so that only the run which logged "test table 2" are filtered?

**Comment by sachinruk** [comment]
I'm afraid I don't really know what weave expressions are. sorry :(

**Comment by vanpelt** [comment]
You don't need to use weave expressions.  You just need to filter the workspace table to only include runs that actually logged "test table 2".  The filters are available in your workspace with the green filter icon:

![image](https://user-images.githubusercontent.com/17/127009671-637a2196-0341-494a-aaf2-5551162db3d9.png)

**Comment by annirudh** [comment]
Hi @sachinruk, when modifying the filters as suggested above do you still see error?
