### ISSUE TITLE
[Q]how to display yolov5 test result in wandb

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2447]
I run yolov5 test 

```
import wandb
wandb.init
python val.py --task test
```
where I can find result and charts of the test data like accuracy and loss, percision and recall 
for object detected and output classes

**Comment by vanpelt** [comment]
@besbesmany `val.py` itself would need to call `wandb.init(project="YOUR_PROJECT")` and then make calls to `wandb.log(...)` to log metrics / tables.  More documentation on our library can be found here:  https://docs.wandb.com 

 I'm not familiar with `val.py` or what it does, but you can never call `wandb.init` in one process then start another python process with `python val.py` and expect it to have any effect.

**Comment by besbesmany** [comment]
can you please give me an example of code to add wandb to disply val result and test result for yolov5 for yolo code like this

[https://colab.research.google.com/drive/1AQ64y-DV51aXRpowlw79bXanhmsYEz59?usp=sharing](url)

**Comment by vanpelt** [comment]
What's the issue?  The colab you linked to does not call `val.py`.  The built in yolo logger should send metrics to wandb just fine.  Just be sure to call `wandb.login()` in your colab before executing `val.py` or `train.py`

**Comment by besbesmany** [comment]
is this correct

```
import wandb
wandb.login()
wandb.init
```
`val.py` or `train.py`

I was just coding withoud `login()`
```
import wandb
wandb.init
```

**Comment by vanpelt** [comment]
```
import wandb
wandb.login()
!python val.py ...
```

**Comment by besbesmany** [comment]
ok is the validation appears as a separate run  or with the same training run , is there an example in wandb of 
train , val, test for the same dataset

**Comment by vanpelt** [comment]
It will be in a new run.  I don't believe we have any examples of train, val, test but I'll tag my colleague @AyushExel who may be able to point you in the right direction.

**Comment by AyushExel** [comment]
@besbesmany Hi. The default behavior is to not log validation only runs to W&B. The `WandbLogger` instance is initialized in train.py. In fact, all the calls to loggers are made on the train.py file so there isn't a clean one-liner that can work with val.py only.
I have a simple solution for your case that should not mess with other operations like train, inference.
in the val.py, add:
```
def on_train_val_end(results):
    if not wandb.run:
      return
    vals = list(results)
    keys = ['metrics/precision', 'metrics/recall', 'metrics/mAP_0.5', 'metrics/mAP_0.5:0.95',  # metrics
            'val/box_loss', 'val/obj_loss', 'val/cls_loss',  # val loss
            ]
    x = {k: v for k, v in zip(keys, vals)}  # dict
    wandb.log(x)
```
Change line 336,337 to:
```
results, _, _ = run(**vars(opt))
on_train_val_end(results)
```
Finally, in `__main__`:
```
if __name__ == "__main__":
    wandb_run = wandb.init(project='yolov5_validation', name='validation')
    opt = parse_opt()
    main(opt)
    wandb_run.finish()
```
This is some work, but it makes sure that the other logging for train, detect works just as expected. 
Let me know if something is unclear. 
P.S. I have also answered your other question on YOLO [here](https://github.com/ultralytics/yolov5/issues/4226)

**Comment by besbesmany** [comment]
Thank you sir I will try this
