### ISSUE TITLE
[Q]where I can find the summary of each run like in the figure

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2450]
where I find this data numbers in summary https://wandb.ai/

Run summary:
wandb:                 train/box_loss 0.03868
wandb:                 train/obj_loss 0.05482
wandb:                 train/cls_loss 0.05741
wandb:              metrics/precision 0.24984
wandb:                 metrics/recall 0.45605
wandb:                metrics/mAP_0.5 0.38431
wandb:           metrics/mAP_0.5:0.95 0.26096
wandb:                   val/box_loss 0.03014
wandb:                   val/obj_loss 0.02415
wandb:                   val/cls_loss 0.05598
wandb:                          x/lr0 0.00083
wandb:                          x/lr1 0.00083
wandb:                          x/lr2 0.06293
wandb:                       _runtime 288
wandb:                     _timestamp 1619139799
wandb:                          _step 10

![10](https://user-images.githubusercontent.com/35992924/126913403-1147289b-81b7-4eab-97d0-161b8268f6c7.png)

**Comment by vanpelt** [comment]
These values are in the table of your workspace, or they can be viewed from the run overview page for an individual run.  You can access the run overview tab by clicking the circle icon with an i in the center on the upper left hand side of the individual run page.  The summary metrics are in the lower right of the overview page.

![image](https://user-images.githubusercontent.com/17/127009362-2a7653a5-bed3-49f5-b8ab-f2b956f782c0.png)

**Comment by besbesmany** [comment]
thank you sir
