### ISSUE TITLE
[Q]how to get accuracy for runs as in figure

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2458]
how to get accuracy column for runs in yolov5

<img width="925" alt="mail" src="https://user-images.githubusercontent.com/35992924/127086159-dba3e256-fffb-423b-9038-a960fc5905a6.png">

**Comment by vanpelt** [comment]
I don't understand the question.  The final accuracy of each run is displayed in this image in the accuracy column.  You have a circle around the "sweep" icon but it's not clear how that's related to your question.  Can you try asking it again?

**Comment by besbesmany** [comment]
sorry I mean accuracy tab how to get it beside name (visualized) tab

![2](https://user-images.githubusercontent.com/35992924/127194714-d9e838e3-3078-42c1-a011-4ce7f6bc4b75.png)

**Comment by vanpelt** [comment]
Choose "Pin Column"

![image](https://user-images.githubusercontent.com/17/127347575-9f5f9524-4bf2-4782-a4d7-a1120551ea9f.png)

**Comment by besbesmany** [comment]
thank you
