### ISSUE TITLE
[CLI] Sweep API only returns 500 runs

### ISSUE THREAD

**Issue by emalgorithm** [wandb/client#2467]
**Description**
When getting runs from a sweep through the python API, if the sweep has more than 500 runs, the API will only return 500 runs:
sweep = api.sweep()
runs = sweep.runs

**Environment**
- OS:  Mac OS Catalina 10.15.7
- Environment: Python file
- Python Version: 3.7

**Comment by anmolmann** [comment]
Hi @emalgorithm , currently we've a limit set on `Api().sweep().runs` to return at most 500 runs. 
However, there is a workaround which might help you with your use case. Use `wandb.Api().runs()` with specifying the sweep_id in filters:
﻿`runs = wandb.Api().runs(path="entity/project", filters={"sweep":"your_sweep_id"})`.
