### ISSUE TITLE
[Q]want to make percision/recall chart

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2468]
I want get figure like this for yolov5 
![7](https://user-images.githubusercontent.com/35992924/127332534-32d5aedc-f1c9-44cd-a9b6-3c7fb551b555.png)

I get this one  how to get it percison/recall 

![6](https://user-images.githubusercontent.com/35992924/127332606-4e07afd9-ed6b-46ef-bc49-e34009171f37.png)

**Comment by vanpelt** [comment]
You would need to explicitly log this: https://docs.wandb.ai/ref/app/features/custom-charts

**Comment by besbesmany** [comment]
Please Sir
I don't understand how to use your code with yolov5 documnets gives code I don't know where to put it 

can you give me complete example for code of yolov5 with `wandb.plots.pr_curve`

should I put it before `train.py` and how to put it 
what to put inside brackets of` wandb.plots.pr_curve()`

**Comment by vanpelt** [comment]
Unfortunately it's rather complicated to construct a PR curve with the Yolov5 data.  I won't be able to provide any example code for this today.  As our implementation improves in maturity this will likely happen automatically or be an option in the future.

**Comment by AyushExel** [comment]
@besbesmany This is more of a YOLOv5 question, probably it's better to open an issue there. We log every metric that is computed, so once that metric gets computed in YOLOv5, you should be able to see it in the dashboard.

**Comment by AyushExel** [comment]
@besbesmany This seems more related to YOLOv5 than wandb. Can we open an issue there to propose the custom charts solution to this problem?

**Comment by besbesmany** [comment]
yes yolov5 gives PR curve in log directory
but I want to compare PR curves for several runs together in the same chart , how to do this please?

**Comment by AyushExel** [comment]
@besbesmany I'm not sure, haven't done that before. I'll get back to you in a day or two after trying it

**Comment by besbesmany** [comment]
@AyushExel  don't forget me sir

**Comment by besbesmany** [comment]
@AyushExel hello sir, I want pr curve for several runs on same chart please

**Comment by AyushExel** [comment]
@besbesmany This feature request has been noted. But we likely won't be able to get to it this week. We're in the middle of revamping the entire W&B section in YOLOv5 among other smaller updates. I'll get this into the repo once I have a bit a bandwidth

**Comment by besbesmany** [comment]
ok , waiting you sir
thank you
