### ISSUE TITLE
[Q] How to compare config between two or more runs?

### ISSUE THREAD

**Issue by chris-tkinter** [wandb/client#2470]
Hi one cool feature from neptune is that we can compare the config between two or more runs, and so far I am not sure how to do the same in wandb. By comparing the config I mean comparing config in this table 
![image](https://user-images.githubusercontent.com/86935669/127385225-30527a02-a7d3-42cc-b68f-5678cee5ed45.png)
Thanks!

**Comment by vanpelt** [comment]
@chris-tkinter you bet!  You can click the "+" icon in your project workspace and choose [Run Comparer](https://docs.wandb.ai/ref/app/features/panels/run-comparer) from the list of panels.
