### ISSUE TITLE
[Q] Log multiple steps in one call / batch log

### ISSUE THREAD

**Issue by maxhuettenrauch** [wandb/client#2472]
Hi!

In my optimization, a single optimizer step is quite fast which can result in many wandb.log calls per second. Is there a way of "collecting" step data before actually submitting it to the servers? I.e. something like a log interval?

Cheers

**Comment by vanpelt** [comment]
Hey @maxhuettenrauch, you bet.  You can specify the `commit=False` method to accumulate metrics into a single step.  A simple loop could look like:

```
for epoch in range(100):
  for batch in range(1000):
    wandb.log({"loss": random.random()}, commit=False)
    if batch % 100 == 0:
      wandb.log({})
```

When `commit=False` we actually just maintain a dictionary and update it with the new metrics.  In the example above, only the last random value for "loss" will be reported to wandb every 100 batches.  For example, if I did:

```
wandb.log({"loss": random.random()}, commit=False)
wandb.log({"acc": random.random()}, commit=False)
wandb.log({"epoch": 3})
# Is equivalent to wandb.log({"loss": random.random(), "acc": random.random(), "epoch": 3})
```

**Comment by maxhuettenrauch** [comment]
Hey @vanpelt, thanks for the quick answer. I already found the `commit` option, but it's not exactly what I want. Using `commit=False` overwrites the data in the "loss" field in your example, but I actually want to keep it. But in order to keep the server communication lower, I would like to send it only every 10 iterations for example.

In your example

`
for epoch in range(100):
  for batch in range(1000):
    wandb.log({"loss": random.random()}, commit=False)
    if batch % 100 == 0:
      wandb.log({})
`
I would like the outer `wandb.log` call to send 1000 "loss" values, instead of only the last one. Maybe something along the lines of a dict of lists, and a custom history callback?

**Comment by vanpelt** [comment]
Hey @maxhuettenrauch we "batch" up the calls automatically for you.  When you call `wandb.log` we add an event to a queue which our process (which is independent from yours) processes and batches up api calls to our servers every N seconds.

**Comment by maxhuettenrauch** [comment]
I see, thanks. The reason why I thought I should take care of this myself is the following output in my log files

```
[34m[1mwandb[0m: 429 encountered (Filestream rate limit exceeded, retrying in 2.4560444709165368 seconds), retrying request
[34m[1mwandb[0m: 429 encountered (Filestream rate limit exceeded, retrying in 4.990224060935212 seconds), retrying request
```

But maybe that's caused by the system my code is running on instead of wandb?

**Comment by maxhuettenrauch** [comment]
Yeah, I do have many running in parallel. Trying to keep it at below rate limit levels :)
