### ISSUE TITLE
[Q] Plot multiple 'tables' from one run on one custom chart

### ISSUE THREAD

**Issue by prash-p** [wandb/client#2478]
Hi, 

I am logging multiple tables per run using wandb.Table(). Each table stores an array of floats. I then log them using wandb.log('Table A': wandb.plot.histogram(table_a), 'Table B': wandb.plot.histogram(table_b)).

I want to plot boxplots of these tables using the Vega functionality - but I want them on the same axis (all tables from each run across multiple runs). At the moment I can only plot the data across runs if the key is the same - so all 'Table A' data will populate on one chart and all 'Table B' data on a different chart. Can I plot Table A and Table B on the same axis?

Thanks

**Comment by anmolmann** [comment]
Hey @prash-p , to clarify do you want to do this through the script or if they are willing to create the chart through the UI?
Through the api, something like is doable: `wandb.plot.histogram(tables=[tableA, tableB])`. Please let us know if this helps.

**Comment by prash-p** [comment]
I would like to do this via the UI online if it's possible.

**Comment by anmolmann** [comment]
Hey @prash-p, this should be possible by querying for multiple tables I think. If you can provide more details about your use-case we can brainstorm a solution.

**Comment by prash-p** [comment]
Here is my project: https://wandb.ai/prashant-pand3y/uncertainty-bone-seg/workspace?workspace=user-prashant-pand3y

Here is an example of trying to query multiple tables, and unfortunately I cannot enter multiple keys in the 'Value field':
![image](https://user-images.githubusercontent.com/5707552/129114432-6934f486-9f13-41c5-bf51-d8914a34bd79.png)

**Comment by anmolmann** [comment]
Hey @prash-p , you can import multiple tables by adding a new query row like shown in the snippet. Then, the spec needs some information to split these boxes on the x-axis. Eg. you would need to specify an x-axis scale that has a domain of the width of the plot, and a range of the run names.
Now, to add multiple values, we don't support putting multiple for each of these mapped values. However, you can add a new `${field:val2}` in the specs. You could add a second layer for this new field and have it tiled directly beside the first field.
![image](https://user-images.githubusercontent.com/20401632/129387753-0bc1c75a-2cea-44e4-8c7a-5b67d11996ee.png)

**Comment by prash-p** [comment]
> Then, the spec needs some information to split these boxes on the x-axis. Eg. you would need to specify an x-axis scale that has a domain of the width of the plot, and a range of the run names.
> Now, to add multiple values, we don't support putting multiple for each of these mapped values. However, you can add a new `${field:val2}` in the specs. You could add a second layer for this new field and have it tiled directly beside the first field.

How exactly do you do both of these in the spec? Could you give an example for my use case?

**Comment by anmolmann** [comment]
@prash-p you could use our new feature: weave panel in order to have multiple tables in one chart. Please checkout `List of: <Panel>` in the [weave panel selector](https://docs.wandb.ai/ref/app/features/panels/weave#weave-panel-selector).
