### ISSUE TITLE
how to run sweeps for yolov5

### ISSUE THREAD

**Issue by besbesmany** [wandb/client#2482]
how to run sweeps for yolov5
in this code

[https://colab.research.google.com/drive/19fiDEOl3zEeLHTCLFbrnWxGahwuDx7O0#scrollTo=r4VjKui20N3j](url)

should I add 
`train.py --img 416 --batch 16 --epochs 500 `
after last line in code
`wandb.agent(sweep_id, train, count=5)`

and which .yaml have parameters to change

**Comment by AyushExel** [comment]
@besbesmany YOLOv5 has built-in support for W&B sweeps. Follow the instructions [here](https://github.com/ultralytics/yolov5/issues/607), once [this PR](https://github.com/ultralytics/yolov5/pull/4276) is merged.

Also, for better visibility, it is recommended that you ask YOLOv5 related questions on Ultralytics github so I can bring in the maintainers of the repo to answer questions/address feature requests. Thanks :)

**Comment by besbesmany** [comment]
thank you sir for your help

**Comment by besbesmany** [comment]
hello sir
I run 
`python train.py --epochs 10 --data coco128.yaml --weights yolov5s.pt --cache --evolve `
this will get best value of `hyp.scratch.yaml `file, right?

1- how to change genetic operators values( crossover, mutation)
2- how to use the best result of hyperparameters, should I run again train.py or what

3- after that should I change hyperparameters limit in `data/hyps/sweep.yaml`, right?
4- how to make sweep in wandb, should I run the next line before` train.py` or what?
`wandb sweep utils/wandb_logging/sweep.yaml`

**Comment by AyushExel** [comment]
For sweeps:
* Set the hyperparameter limits in `utils/logging/wandb/sweep.yaml` and define dataset path and search strategy.
* run `wandb sweep utils/loggers/wandb/sweep.yaml` . You can optionally pass `--project name` and `--count max_run_count`
* The above command will output an id. Start the sweep with `wandb agent sweep_id`. This will start W&B sweep over the defined search space in `sweep.yaml`

**Comment by besbesmany** [comment]
in Set the hyperparameter limits in utils/logging/wandb/sweep.yaml and define dataset path and search strategy.
where to define dataset path 

![2](https://user-images.githubusercontent.com/35992924/128087608-5874431f-0316-43b4-8194-96d618ba5d5a.png)
is search strategy means min/max values? is that according to the resulting file `yolov5/runs/evolve/hyp_evolved.yaml `?

**Comment by AyushExel** [comment]
* The search strategy means how want to search the hyper-parameter space( in `method: random`). I'd say stick to random because if you change that, you'll have to change the distribution of values to support that. (More on this in wandb Sweeps doc)
* Dataset path can be set by modifying line 26 in the above screenshot. set `value="your_dataset_path"`

**Comment by besbesmany** [comment]
- how to change genetic operators values( crossover, mutation)?
- should I run 
run wandb sweep utils/loggers/wandb/sweep.yaml . You can optionally pass --project name and --count max_run_count
before `train.py `

- The above command will output an id. Start the sweep with wandb agent sweep_id. This will start W&B sweep over the defined search space in sweep.yaml
can not understand last line

**Comment by AyushExel** [comment]
* Cannot use genetic mutation with sweeps, it can be used in evolve. That's different
* You don't have to call train.py manually, the sweeps command will take care of that
* the above command will output an id. then you just have to run `wandb agent {sweep_id}`

**Comment by besbesmany** [comment]
how to change crossover , and mutation in evolve
![6](https://user-images.githubusercontent.com/35992924/128150553-7ea69f0d-1617-49f3-aeea-31a001b5d3f8.png)

**Comment by AyushExel** [comment]
@besbesmany you should ask that in the same thread in YOLOv5. Sweeps and evolve operations are independent, so you likely want to use them separately

**Comment by besbesmany** [comment]
where I can find the generated id

**Comment by AyushExel** [comment]
> For sweeps:
> 
> * Set the hyperparameter limits in `utils/logging/wandb/sweep.yaml` and define dataset path and search strategy.
> * run `wandb sweep utils/loggers/wandb/sweep.yaml` . You can optionally pass `--project name` and `--count max_run_count`
> * The above command will output an id. Start the sweep with `wandb agent sweep_id`. This will start W&B sweep over the defined search space in `sweep.yaml`

When you run the 2nd step here, you'll find a generated ID
