### ISSUE TITLE
[CLI] `Artifact.download()` produces files in a different directory

### ISSUE THREAD

**Issue by diegoquintanav** [wandb/client#2486]
**Description**
Specifying `root` dir in `artifact.download` downloads a copy in `./artifacts`

**Wandb features**
problem is reproduced in 
https://colab.research.google.com/gist/diegoquintanav/99364d4a83463ad121a7fbf4deb03175/wandb_issue_1912.ipynb

**How to reproduce**
1. Go to https://colab.research.google.com/gist/diegoquintanav/99364d4a83463ad121a7fbf4deb03175/wandb_issue_1912.ipynb
2. Expect to have `dummy.csv` in `wandb_sample_data_b`, specified in `root` parameter
3. End up with a copy in `/content/artifacts` 

**Environment**
- Environment: [e.g. Google Colab]
- wandb 0.11.1
python 3.7.11 (default, Jul  3 2021, 18:01:19) 
[GCC 7.5.0]
pandas 1.1.5

**Comment by anmolmann** [comment]
Hey @diegoquintanav, `artifact.file()` downloads a single file artifact to dir specified by the <root>. If root is not specified, then it defaults to `./artifacts/<self.name>/`. For your use case: you can do `artifact.file("/content/wandb_sample_data_b")` to avoid a copy in `/contents/artifacts`.
Hope this helps.

**Comment by jpcenteno80** [comment]
Related to the discussion, I'm not sure if `dir` inside `wandb.init()` is working as expected. The doc string for `dir` in `wandb.init()` is the following:
```
# wandb version: '0.12.4'
dir: (str, optional) An absolute path to a directory where metadata will
    be stored. When you call `download()` on an artifact, this is the
    directory where downloaded files will be saved. By default this is
    the ./wandb directory.
```
I can see that metadata is being stored there (in `dir`), but when running `artifact.download()`, inside a `with wandb.init()` statement, `dir` does not control the download location. Only `root`, inside `artifact.download()` governs that process.

**Comment by anmolmann** [comment]
@jpcenteno80 if you don't specify `root` inside `artifact.download()`, what's your download location in this case? Is it the one you specified in `wandb.init(dir='...')`?

**Comment by anmolmann** [comment]
@jpcenteno80 thanks for pointing this out, this is a bug on our end. Currently, our lib's default behaviour is to check if root path is specified or not: if not, then an `artifacts` dir is created in the `pwd` and the artifact is downloaded there. I'll check in with our eng team if this is the desired behaviour, in which case, we'll update our docs.

**Comment by ranshadmi** [comment]
Any update regarding this issue?

**Comment by anmolmann** [comment]
@ranshadmi, this issue has been fixed. Also, we can't reproduce this issue in our latest [cli v0.12.18](https://github.com/wandb/client/releases/tag/v0.12.18). Please let us know if you're still encountering this issue.

**Comment by patrickjdarrow** [comment]
I still get this behavior when invoking a download function from a python file (lets call it `data/wandb/get_file.py`).

```
# get_file.py
import wandb

def get_file(root_dir):
  with wandb.init(project=...) as run:
    artifact = run.use_artifact(...)
    artifact.download(root=root_dir)
  return ...
```

in a script (`./script.py`)
```
from ... import get_file
get_file(root_dir='data/wandb/')
```

The file is saved to `./artifacts`.
