### ISSUE TITLE
[CLI] Cannot unmarshal string into Go value of type map[string]interface. Program does not terminate

### ISSUE THREAD

**Issue by alexus37** [wandb/client#2489]
**Description**
With the newest version of wandb (0.11.2), the process is getting stuck after the training is finished with the following error message.

```bash
wandb: Waiting for W&B process to finish, PID 15267
wandb: Program ended successfully.
wandb: ERROR Error while calling W&B API: json: cannot unmarshal string into Go value of type map[string]interface {} (<Response [500]>)
wandb: ERROR Error while calling W&B API: json: cannot unmarshal string into Go value of type map[string]interface {} (<Response [500]>)
wandb: ERROR Error while calling W&B API: json: cannot unmarshal string into Go value of type map[string]interface {} (<Response [500]>)
....
```

**Wandb features**
I am using this [template](https://github.com/ashleve/lightning-hydra-template) with artifacts and log calls. 

**Environment**
- OS: ubuntu 20
- Environment: python script
- Python Version: 3.7.10

**Comment by dannygoldstein** [comment]
Hi @alexus37, just to confirm: are you only seeing this in 0.11.2? Do you not see it with earlier versions such as 0.11.0?

**Comment by vanpelt** [comment]
@alexus37 the backend error is being caused by invalid metadata in an `Artifact`.  It's been double encoded for some reason.  Are you manually constructing any artifacts in your code?

**Comment by alexus37** [comment]
Hi, 
yes, I am and I am even using metadata. 
here is my code snippet that uses it.

```python
ckpts = wandb.Artifact(f"{self.artifact_prefix}_densities", type="densities")
# meta data is just a dict eg. {"name": "test"}
ckpts.metadata = self.meta_data
files = [
    (original_density, "original_density.npz"),
]
for (data, name) in files:
    file = os.path.join(self.working_dir, name)
    np.savez(
           file, data=data.detach().cpu().numpy()[0, 0],
     )
     ckpts.add_file(file)

experiment.use_artifact(ckpts)
```

@dannygoldstein  I am using the wandb version 0.11.2. I didn't test any earlier versions.

**Comment by vanpelt** [comment]
@alexus37 can you try specifying `metadata` as an argument to `wandb.Artifact` and see if that works?  I would also verify `isinstance(self.meta_data, dict)`.

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
