### ISSUE TITLE
[Feature] Containerized notebook environment still using v0.8.1 (breaking changes encountered)

### ISSUE THREAD

**Issue by michaelwooley** [wandb/client#2495]
**Is your feature request related to a problem? Please describe.**

Decided to give this a try. Once installed I started up the containerized notebook environment:

```bash
poetry run wandb docker --jupyter # Can elaborate on poetry versions, etc. in a moment
```

Created a notebook then tried to run a basic data upload as described [here](https://docs.wandb.ai/guides/artifacts/artifacts-core-concepts#terminology). However, got a very basic error. 

Here is a minimum reproducible example:

```python
!python --version
!pip freeze | grep wandb

import wandb

wandb.Artifact
```

The output is as follows:

```
Python 3.6.8
wandb==0.8.1

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d1d248e14b00> in <module>
      4 import wandb
      5 
----> 6 wandb.Artifact

AttributeError: module 'wandb' has no attribute 'Artifact'
```

Artifact not found?! Eventually I noticed the python version change + the fact that the `wandb` version looks to be pretty old.

(I am running v0.11.2 in my local py3.9.1 environment but this is docker so all bets are off :man_shrugging:)

**Describe the solution you'd like**

1. Bump your package (that being said, I understanding that "just" bumping versions willy-nilly can be fraught.)
1. Clarity on python version being run in jupyter env
2. Clarity in docs regarding any python version limitations. It appears to be running fine in an ipython console with py3.9.1, though.

**Describe alternatives you've considered**

I have a perfectly good jupyter setup. I was just trying to paint in the lines when trialing this.

**Additional context**

I don't think it will be necessary but just in case here is some info from my dev environment (outside of container):

```bash
➜  py git:(dev) ✗ poetry show --no-dev | grep wandb
wandb                        0.11.2              A CLI and library for interacting with the Weights and Biases API.
➜  py git:(dev) ✗ python --version                 
Python 3.9.1
➜  py git:(dev) ✗ docker version                                                  
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df35096d
 Built:             Fri Jun  4 08:14:39 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

- Operating System: Manjaro Linux

("Feature request" because I suppose this isn't a bug per se. Just unexpected behavior.)

**Comment by vanpelt** [comment]
Thanks for reporting this @michaelwooley.  We'll update the base image to have the most recent wandb lib.

**Comment by vanpelt** [comment]
Hey @michaelwooley we just updated the images.  Can you try again?
