### ISSUE TITLE
[CLI] `KeyError` with `wandb.plot.confusion_matrix()`

### ISSUE THREAD

**Issue by karl-joan** [wandb/client#2497]
**Description**
When using `wandb.plot.confusion_matrix()` on the outputs of my model, I get a `KeyError` with the message `tensor(0)`.

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_51196/41843745.py in <module>
      4 
      5 wandb.init()
----> 6 wandb.log({"conf_mat" : wandb.plot.confusion_matrix(
      7                     y_true=labels,
      8                     preds=preds,

~/anaconda3/envs/pytorch/lib/python3.9/site-packages/wandb/plot/confusion_matrix.py in confusion_matrix(probs, y_true, preds, class_names, title)
     70     counts = np.zeros((n_classes, n_classes))
     71     for i in range(len(preds)):
---> 72         counts[class_mapping[y_true[i]], class_mapping[preds[i]]] += 1
     73 
     74     data = []

KeyError: tensor(0)
```

**Wandb features**
When using `wandb.plot.confusion_matrix()`  inside `wandb.log`.

**How to reproduce**
```python
import wandb
import torch

preds = torch.tensor([0, 1, 2])
labels = torch.tensor([0, 2, 1])
class_names = ['cat', 'dog', 'other']

wandb.init()
wandb.log({"conf_mat" : wandb.plot.confusion_matrix(
                    y_true=labels,
                    preds=preds,
                    class_names=class_names)})
```

**How to fix**
The pytorch tensors should be first converted to a numpy array to fix the `KeyError`. For example, the [plot function](https://github.com/wandb/client/blob/master/wandb/plot/pr_curve.py) for precision and recall converts the arrays to a numpy array first.

**Environment**
- OS: Linux Ubuntu
- Environment: Jupyter Notebook
- Python Version: 3.9.6
- IPython Version: 7.25.0

**Comment by anmolmann** [comment]
HI @karl-joan, the test set labels and test set predicted labels should be of type `arr`. You can read more about the confusion matrix plot [here](https://docs.wandb.ai/guides/integrations/scikit#confusion-matrix). Hope this helps.
