### ISSUE TITLE
[Q] How to switch off image smoothing by default?

### ISSUE THREAD

**Issue by ZhekaHauska** [wandb/client#2504]
Hello everyone! 
I used to log tiny(10x10 pixels or so) images into runs and they just enlarged in wandb, so I could see everything fine. However, recently, images and gifs have started to appear smoothed and I don't see how to switch it off. As a solution, I can load pictures of normal size, but, I think, I can save a lot of space by logging small images. 

Example of smoothed image:
![изображение](https://user-images.githubusercontent.com/47570311/128379874-980d5ffd-9e15-4036-94ab-985f8d1bdbb7.png)

**Comment by tyomhak** [comment]
Hi @ZhekaHauska , thanks for reporting this. Would you be able to share a link for a run page with an example of this issue?

**Comment by ZhekaHauska** [comment]
> Hi @ZhekaHauska , thanks for reporting this. Would you be able to share a link for a run page with an example of this issue?

Hi @tyomhak, thanks for your response. [Here](https://wandb.ai/hauska/test/runs/22oohx7f?workspace=user-hauska) it is.

**Comment by jsbroks** [comment]
Hey @ZhekaHauska could you also share what browser you are using? I opened the example in chrome and it does not have the smoothing effect.

**Comment by ZhekaHauska** [comment]
> Hey @ZhekaHauska could you also share what browser you are using? I opened the example in chrome and it does not have the smoothing effect.

Hi @jsbroks! That's interesting, I didn't think the issue may be connected with the browser. I am using Mozilla Firefox 90.0.2 (64-bit).
