### ISSUE TITLE
[Q] Does Wandb replicate images in logs?

### ISSUE THREAD

**Issue by adizhol** [wandb/client#2514]
Hi,
I've just started to explore Wandb (*local setup*), and I want to create a table artifact with images or/and videos.
These images/videos exist in a test dataset, logged in wandb.
In the examples I read, when creating a table with images, the actual numpy arrays are logged.
These seems like a huge redundant storage consumption.
Can wandb show images in a table without actually saving a copy of them in the log?
Can I embed an image HTML tag in the table? If so, could I use a static s3 link (or use minIO on local storage)?

Thanks

**Comment by vanpelt** [comment]
Hey @adizhol wandb.Artifacts are content aware.  We automatically capture the md5 of every piece of binary data added to a wandb.Table.  This includes Images, Audio, HTML, etc.  We will never store the same data twice for an individual artifact.  For example:

1. You log a table that has images A, B, and C
2. You log another version of this artifact with a table that has images A, B, and D

In the above scenario we would only upload image D as we already uploaded A and B in the previous version.

To answer your last question, you can log custom HTML that points to external assets however the user experience and access controls are much better when you just log the raw data to wandb.

**Comment by adizhol** [comment]
@vanpelt Thanks for the clear answer.
Could you suggest a way, in a local wandb setup, to log artifacts (images, checkpoints) that already exist on the hard-drive, while consuming minimal storage? 
Is the custom HTML the only option?

**Comment by vanpelt** [comment]
@adizhol you should checkout [Artifact References](https://docs.wandb.ai/guides/artifacts/references).  This allows you to store pointers to files on your local filesystem or an S3 bucket.  It's important to note we won't be able to render reference artifacts in our UI's and there's nothing we can do to prevent someone from deleting or misplacing the references that were logged.
