### ISSUE TITLE
Run not found

### ISSUE THREAD

**Issue by LisburnLad** [wandb/client#2533]
It appears that wandb has stopped working in Jupyter notebooks when trying to display the results of a run in a notebook cell. 
This was working fine until a couple of days ago, but now always produces the "Run not found" error.

This happens for me in notebooks that are running in both Kaggle and Colab, and all other wandb notebooks I've looked at in Kaggle that previously displayed the wandb graphs have now all lost their graphical output.

For example, this notebook from kaggle used to display its wandb graphs in the notebook cell:

[https://www.kaggle.com/dliend/rapid-iteration-and-experiment-tracking-with-wandb](https://www.kaggle.com/dliend/rapid-iteration-and-experiment-tracking-with-wandb)

This also occurs if I run the wandb sample jupyter notebook from here:
[https://docs.wandb.ai/guides/track/jupyter](https://docs.wandb.ai/guides/track/jupyter)

This only effects the display in the jupyter notebook itself, the experiment is still correctly sent and displayed in my page on wandb.

**Comment by vanpelt** [comment]
Hey @LisburnLad we're aware of the issue and are working on a fix.  We'll update this ticket once it's been resolved.

**Comment by vanpelt** [comment]
Hey @LisburnLad this has been fixed!  You may have to logout of wandb and then log back in for it to work in your browser.
