### ISSUE TITLE
[CLI] Service worker produces 403 Error in sweep whereas user API Key doesn't 

### ISSUE THREAD

**Issue by savvaki** [wandb/client#2540]
**Description**
I am running a complicated cloud set up for sweeps on Google Cloud Platform. To summarise:
- All configuration of W&B is happening through environment vars, for example: WANDB_API_KEY, WANDB_ENTITY, WANDB_USERNAME, WANDB_PROJECT are set in the environment
- When I use a **service worker API key**, it is unauthorized to upload logs for the sweep runs. I get the following error:  `dropped chunk 403 Client Error: Forbidden for url: https://api.wandb.ai/files/{TEAM_NAME}/{PROJECT_NAME}/{RUN_ID}/file_stream"`
- I have ommited the actual values in the URL above, but the values are correct.
- When I use a User API key, the logging works.

Why is the service worker not working for this configuration? I am unable to view the wandb logs in the container unfortunately.

Thank you in advance

**Comment by vanpelt** [comment]
Hey @savvaki is the service account in the {TEAM_NAME} you're logging to?

**Comment by savvaki** [comment]
Yes, when I navigate to my team name and click _Team Settings_ the service account appears there alongside the other members.

**Comment by vanpelt** [comment]
Very odd.  I just ran an experiment with a service account with a sweep and it executed fine.  Are you able to see the console output when the script executes?  One of the first lines should look like:

```
wandb: Currently logged in as: wandb (use `wandb login --relogin` to force relogin)
```

The service account should say you're logged in as {TEAM_NAME}.  Are the runs themselves showing up in the UI?

**Comment by vanpelt** [comment]
I tested this with the most recent version of `wandb` can you also be sure you're using 0.12.0 by running `pip install wandb --upgrade`?

**Comment by savvaki** [comment]
@vanpelt I have attached more logs, the team name does appear as you stated above for both the User API key and the Service account API key. You can also see here that a sweep is designated as well as a run. The Conda env exception there can be ignored (it occurs with the User API key as well yet those runs work). Each package should default to the latest `wandb` but let me check specifically for you.

![image](https://user-images.githubusercontent.com/86887075/129790780-5dd005e1-ad6d-429a-abd3-7892a26a5cf8.png)

**Comment by vanpelt** [comment]
Are you able to access a `debug-internal.log` file from one of the failing runs?  If you could sent that to vanpelt@wandb.com that would help us find the root cause.

**Comment by vanpelt** [comment]
Can you also try setting the WANDB_ENTITY environment variable to your team or username?

**Comment by savvaki** [comment]
The WANDB_ENTITY is set to the team name that the service account falls under. Let me try and see if I can access a ```debug-internal.log```

**Comment by savvaki** [comment]
I am going to close this issue since I have not had time to get to it. I will reopen one day if need be.
