### ISSUE TITLE
[App] Logged audio not in sync in the app.

### ISSUE THREAD

**Issue by PiotrDabkowski** [wandb/client#2544]
**Describe the bug**

I am logging a pair of audio files via `[wandb.Audio(..., caption="original"),  wandb.Audio(..., caption="reconstructed")]`, in the app I would expect that the left and right audios are always shown in sync (they come from the same time step), but sometimes this is not the case when I slide between time steps. Also the step sliders sometimes are not updated correctly when switching between runs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://wandb.ai/piter/trans?workspace=user-piter
2. Click select between 2 experiments (one has ~80k steps, another just ~2k), see that the steps from the large experiments are sometimes shown in the small experiment. Also observe that sometimes left and right audios are not in sync (coming from different steps).

**Expected behavior**

All the shown audios are from the same time-step, the leakage between steps should *never* happen as this is very confusing. If some audio files are pending load, then it is better to show empty space (or better a loading animation) rather than incorrect one. The sliders should be updated correctly when switching between experiments.

**Screenshots**
In this specific case the audio is in sync, this is to just illustrate how the logged audio looks like.
![Audio Log Wandb](https://i2.paste.pics/DJG2L.png)

**Operating System**
 - OS: macOS
 - Browser chrome
 - Version 92.0.4515.131

**Comment by PiotrDabkowski** [comment]
Thanks a lot, really cool tool, just this single bug is making debugging audio synthesis a bit painful :)

**Comment by PiotrDabkowski** [comment]
Hey, what is the status of the fix?

**Comment by anmolmann** [comment]
Hi @PiotrDabkowski, this is on our roadmap, however, I'm not certain about the timeline for the fix yet. We'll follow-up with you here once there's an update.

**Comment by anmolmann** [comment]
Hey @PiotrDabkowski , this issue has been been fixed. Please let us know if you encounter it again.

**Comment by PiotrDabkowski** [comment]
Hey, I am still experiencing it (don't see any improvement). Btw, it happens much more often when viewing audio while training.
Also, the step being viewed switches on its own to another step - this is super annoying. 
I can send you a video demonstrating the issue if that helps.

**Comment by anmolmann** [comment]
@PiotrDabkowski we clamped the slider to existing step values. Could you please send the video for your issue? That would be very helpful.

**Comment by PiotrDabkowski** [comment]
Thanks!
Please see the video: www.youtube.com/watch?v=imITetOL18c

Notice that the audio samples come from different steps (I log the step number). Expected behavior is that all the audio samples come from a single step (say step 250). 

Also it would be nice to not have the auto-refresh in the case of audio - this does not help and does not allow to listen to the sample (switches during listening).

**Comment by PiotrDabkowski** [comment]
What is the status of this? This must be affecting other users as well. Can we at least reopen the bug please?

**Comment by anmolmann** [comment]
@PiotrDabkowski , I've escalated to our eng team, we'll have an update for you soon. Apologies for the delay here.

**Comment by anmolmann** [comment]
@PiotrDabkowski , could you please also share the link to your wandb workspace where you're seeing the issue? We tried finding it as well reproducing the issue on our end but couldn't. The video is very helpful so far, however, a link to your workspace would be even helpful.

**Comment by PiotrDabkowski** [comment]
Thanks, it happens while training, after training is done I cannot reproduce it reliably anymore.

**Comment by anmolmann** [comment]
@PiotrDabkowski , I've passed these details to our eng team. Also, they recently pushed some fixes relate to step slider which might've resolved your issue. Please let us know if they’re still experiencing issues?

**Comment by PiotrDabkowski** [comment]
Still does happen while training - it is easy to reproduce for new steps (up to 5 minutes in the past).

**Comment by PiotrDabkowski** [comment]
It seems to be fixed now, can't reproduce anymore :) Thanks a lot!
