### ISSUE TITLE
[App] Graphs not rendering in macOS Safari.

### ISSUE THREAD

**Issue by PiotrDabkowski** [wandb/client#2545]
**Describe the bug**
Graphs are not rendering in macOS Safari (they were rendered correctly a few months ago when I last tried).

**To Reproduce**
1. Go to 'https://wandb.ai/piter/trans?workspace=user-piter'
2. See empty graphs when using macOS Safari.

**Screenshots**
![No graphs](https://i2.paste.pics/184be589a3334c3843ded499279ba74a.png)

**Operating System**
 - OS: macOS 11.1
 - Browser Safari
 - Version 14.0.2

**Comment by laxels** [comment]
Hey there @PiotrDabkowski. Sorry about that! Can you upgrade your Safari and see if the problem persists? I'm on 14.1.2 and all the graphs are working properly on that page.

**Comment by lukas** [comment]
This should be fixed now - reopen if you still see it.

**Comment by PiotrDabkowski** [comment]
Thanks a lot, I confirm it works now.
