### ISSUE TITLE
WARNING:root:Only 108 Image will be uploaded.

### ISSUE THREAD

**Issue by sophiaas** [wandb/client#2559]
I am attempting to log images of kernel filters during training. My logging dictionary looks like this:

`log_dict = {'epoch': 0, 'U': [list of wandb.Image objects], 'V': [list of wandb.Image objects], 'W': [list of wandb.Image objects]}`

There are 256 images per variable. When I call `wandb.log(log_dict)`, I get the following error:

`WARNING:root:Only 108 Image will be uploaded.`
`WARNING:root:Only 108 Image will be uploaded.`
`WARNING:root:Only 108 Image will be uploaded.`

It appears to print one time for each variable. On the web app, there are indeed only 108 uploaded images per variable name.

I have reproduced this issues using different images, numbers of images, and numbers of variables. Any idea where the limit of 108 comes from? Any way to avoid this issue and upload everything I send?

**Environment**
- OS: Ubuntu 18.04.4 LT
- Environment: Python
- Python Version: 3.9.2

**Comment by vanpelt** [comment]
Hey @sophiaas we enforce a limit of 108 images per key when logged as lists.  It would likely be better to just log these images as a table:

```
table = wandb.Table()
table.add_column("U", [256 wandb.Images])
table.add_column("V", [256 wandb.Images])
table.add_column("W", [256 wandb.Images])
log_dict = {'epoch': 0, 'images': table}
```

**Comment by sophiaas** [comment]
Thanks for the quick response! It would be nice to have note of this restriction in the documentation so the error is not mysterious when it comes up.

**Comment by off99555** [comment]
Just found this out 2 years later man. It's indeed a mystery. I thought I did a bug. Warning message should be more prescriptive. It should tell us that it's not user error and it's the way wandb is designed and it should suggest an alternative approach like the table thing above.
