### ISSUE TITLE
Adding custom naming capibility for wandb runs

### ISSUE THREAD

**Issue by praateekmahajan** [wandb/client#256]
* Weights and Biases version: 0.6.27
* Python version: 3.6+
* Operating System: Linux

### Description

It would be great if there is a feature that allows custom naming of the run. 

Instead of 6 random characters https://app.wandb.ai/user/project/runs/wsl8or9u, we can have something like https://app.wandb.ai/user/project/runs/13_layer_cnn_wsl8or9u or https://app.wandb.ai/user/project/runs/4_layer_rnn_wsl8or9u.

In my opinion this will be a UI enhancement as you can see which models result do you want to look at, instead of going through the entire width of the table.

**Comment by vanpelt** [comment]
Hey @praateekmahajan you can do this with the current version!   Checkout WANDB_RUN_ID and notes on resuming here: https://docs.wandb.com/docs/automated.html
