### ISSUE TITLE
[Q] The metric graph in Sweep not rendering correctly

### ISSUE THREAD

**Issue by jihwan-jeong** [wandb/client#2566]
Hi.

In the Sweep Workspace where summary plots are shown, I see a graph titled `my_metric v. created` which is supposed to show the obtained metric values from all runs against the time the results were created. However, as you can see from the screenshot below, I can only see a single point (when there are more than 100 finished runs).

![image](https://user-images.githubusercontent.com/51473118/130211695-46688882-d119-4fdc-8b54-662cdee40828.png)

Besides, the limits of the time created axis are pretty weird.

Furthermore, in the part where multiple lines with different configurations should be plotted, I can only see a single line whose configuration seems to be sort of an average of all runs (see below).
![image](https://user-images.githubusercontent.com/51473118/130211987-2a622659-e1ad-479c-ad2f-13d5c0c5b8ef.png)

When I click a specific run, I can see the correct results uploaded to the server. 

Please let me know what's going wrong here. 

Thanks,
Jihwan

**Comment by vanpelt** [comment]
Hey Jihwan, can you share a link to the sweep workspace where you're seeing this behaviour?

**Comment by jihwan-jeong** [comment]
https://wandb.ai/jhjeong/offline_mbrl/sweeps/4f4uc92k?workspace=user-jhjeong

Here it is :)

**Comment by vanpelt** [comment]
Ahh, you'll need to "Un-Group" your runs to see them individually, by clicking the "X" next to the group setting:

![image](https://user-images.githubusercontent.com/17/130302851-ceefe14b-0d6e-4c5f-84f4-a44968a2d1d5.png)

**Comment by jihwan-jeong** [comment]
Hi Chris, 

Thanks! That worked :)
