### ISSUE TITLE
[App] Undesired interpolation of points

### ISSUE THREAD

**Issue by loicsacre** [wandb/client#2567]
**Describe the bug**

Let me introduce the problem with screenshots. In screenshot (1), showing run 1 only, 10 random values are logged (a seed is set for them). The point 7 corresponds to 0.7887. In screenshot (2), showing run 1 and 2 , the same random points are plotted except that the step is set initially to 10. As you can see, the point 7 is replaced by a 6.5. In screenshot (3), showing run 1, 2 and 3, the same experiment is replicated (run 3) but the 20 points are logged at once. We can clearly see that the points are aligned and the point 7 has come back. From our observations, the issue seems to occur when there is at least one value mismatch. See run 4 in screenshot(4) which starts at step 1 and the grouping of both run 1 and 4 in screenshot(5). The issue is certainly due to the bucketing logic mentioned [in this issue](https://github.com/wandb/client/issues/2384#issuecomment-878724949). 

**To Reproduce**
For screenshots(1-3)
```python
import wandb
import random

def log(id, nb_points=0, init_step=0):
    wandb.init(project="your_project", entity="your_entity",
               group="BUG" if id != 3 else "BUG-1", job_type=f"job",
               name=f"{id}", reinit=True)
    for i in range(nb_points):
        if i == 0 or i == 10:
            random.seed(1)
        wandb.log({"i": i + init_step, "value": random.random()}, step=init_step + i)

log(1, nb_points=10)
log(2, nb_points=10, init_step=10)
log(3, nb_points=20)
```

**Expected behavior**

The results of the grouping of run 1 and 2 should appear as in screenshot(3) and not  screenshot(2). In this case, I don't see why the 20 points could not be rendered correctly and why the bucketing logic should be applied in that case.

**Screenshots**

Screenshot(1)
![Screenshot 2021-08-20 at 11 51 40](https://user-images.githubusercontent.com/32166486/130215618-61982cd6-00a1-4554-abfd-1f44c21df805.png)

Screenshot(2)
![Screenshot 2021-08-20 at 11 51 51](https://user-images.githubusercontent.com/32166486/130215627-3743a508-ab33-4ee7-bb5a-18ca73c65456.png)

Screenshot(3)
![Screenshot 2021-08-20 at 16 11 31](https://user-images.githubusercontent.com/32166486/130246989-3934d140-a7ee-406e-8529-15b5e023445a.png)

Screenshot(4)
![Screenshot 2021-08-20 at 15 34 06](https://user-images.githubusercontent.com/32166486/130241307-fad34f2d-01b6-4185-9279-44b1547a586b.png)

Screenshot(5)
![Screenshot 2021-08-20 at 15 38 21](https://user-images.githubusercontent.com/32166486/130241902-9a3086df-ee9a-429c-aded-9cf7593397a4.png)

**Operating System**
 - OS: MacOs
 - Browser Chrome

**Comment by anmolmann** [comment]
Hey @loicsacre, when runs (which don't have x-axis that line up exactly) are grouped, we create buckets or windows across the group of runs to show values in the same "bucket" and points are downsampled. These windows are evenly sized and within each window all points are averaged. This average value is used as a value of that metric. This is why value `6.5` is displayed in screenshot [3] because run [2] is missing steps: 0,1,...,9 and the values are averaged in each window.

**Comment by anmolmann** [comment]
Hey @loicsacre , we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by loicsacre** [comment]
Hello, yes the explanation you gave is what I have observed. However if it is how the logic behind Wandb works and it cannot be changed then the issue can be closed. I was just surprised that the bucket logic is always applied even if all the points can be easily displayed.

I will let a small hack for those who will see the issue later: create a "mock" group with a run where you have all the points of the x-axis and put set the alpha (A) of color to 1 (it will be invisible on the curves). By adding it, you will be able to see red curves of screenshot (2) the same way as screenshot (3), i.e. without the interpolation.
