### ISSUE TITLE
Failed to detect the name of this notebook + The `IPython.html` package has been deprecated

### ISSUE THREAD

**Issue by roboserg** [wandb/client#2571]
Having 3 issues while running the following lines using jupyter notebook in the VS Code IDE:
```
import wandb
wandb.init(project='Kaggle - Amazon Forest')
```

1. Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
2. ShimWarning: `The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.`
3. It draws a big, empty window clugging my notebook "Run(16moyzxu)" "Run not found Sorry, this run was not found."

https://i.imgur.com/byomyJd.png

![Code_LdOLTQuSQt](https://user-images.githubusercontent.com/4758917/130326808-07bfbe4d-6d32-4e95-aed0-1090671602db.png)

**Comment by vanpelt** [comment]
Hey @roboserg unfortunately because of the way vscode notebooks works we're unable to extract the notebook information which is what the first warning is about.

We'll look into to detecting the Ipython version and address the deprecation warning.

We may be able to enable run viewing in vscode, but you would have to login.  Until then, just make sure the last item in your cell is not an unbounded `wandb.run` variable.  If you set `run = wandb.init(project="Kaggle - Amazon Forest")` we will not render the iframe.

**Comment by roboserg** [comment]
@vanpelt Thanks. Using "run=" help to remove the empty white box in VS Code.
However on Kaggle it prints too much information and on Kaggle I can't  even manually remove the cell output!
![chrome_DAgUAIZRes](https://user-images.githubusercontent.com/4758917/130373323-d6adb0ab-4abe-41db-b344-b3f708cc58f8.png)

And after training when I want to train again, I press "run all", so obviously all cells are run again and WANDB does this - 
https://i.imgur.com/X3exE8u.png

Is there any way to control what WANDB outputs?

**Comment by vanpelt** [comment]
Sure, you can pass the following to wandb.init:

`settings=wandb.Settings(silent=True)`

**Comment by roboserg** [comment]
> Sure, you can pass the following to wandb.init:
> 
> `settings=wandb.Settings(silent=True)`

Thanks, but getting an error `TypeError: Settings field silent: True is not a boolean`
```
import wandb
run = wandb.init(project='Kaggle - Amazon Forest')
settings = wandb.Settings(silent=True)
```
https://i.imgur.com/6AmFFnq.png
Using wandb ver. 0.12

**Comment by vanpelt** [comment]
Whoops, sorry, `settings=wandb.Settings(silent="True")`

**Comment by roboserg** [comment]
> Whoops, sorry, `settings=wandb.Settings(silent="True")`

Thanks! Setting it to silent helps, the output is tighter in the Kaggle notebook now. 
However, in VS Code the output is still to big, using unnecessary empty lines. 
Is there a way to completely reduce the output of wandb? Ideally I'd need only 1-2 lines:

`Syncing run kind-glitter-19 to Weights & Biases (Link to the run).`

**Comment by vanpelt** [comment]
You need to pass settings into `wandb.init`, i.e. `wandb.init(project="Kaggle = Amazon Forest", settings=wandb.Settings(silent="True")`.  We'll also look into making the experience better directly in VSCode as we've yet to optimize that environment.

**Comment by roboserg** [comment]
> You need to pass settings into `wandb.init`, i.e. `wandb.init(project="Kaggle = Amazon Forest", settings=wandb.Settings(silent="True"))`. We'll also look into making the experience better directly in VSCode as we've yet to optimize that environment.

That worked, thanks! Should I open separate issues about "Failed to detect the name of this notebook" and package deprecation or is it already in your to-do list?

**Comment by Tzoulio** [comment]
@vanpelt Hello, after importing wandb and running wandb.init I also get the same IPython problem. When starting training and checking the wandb website i am able to see the project running and graphs about my cpu/gpu usage. However, I cannot see important metrics such as percission, mAP, loss etc... When I open the charts tab it says **"No metrics logged yet"**. Any ideas?

**Comment by aidanjdonohue** [comment]
@Tzoulio it sounds like there might be an issue with your code that's not quite related to this thread. For the sake of keeping this clean, I'm going to close out this thread but I'd be happy to help you if you open a new issue and @ me or if you'd like to write in to support@wandb.ai
