### ISSUE TITLE
[Q]Network traffic in offline mode

### ISSUE THREAD

**Issue by sandylaker** [wandb/client#2573]
I run an experiment in offline mode, and then synchronized the wandb log after the experiment finished. However, I found that the network traffic was the same as in the online mode. So I would like to ask why the network traffic is so large even in offline mode, and how we can avoid it.

<img width="614" alt="Screen Shot 2021-08-22 at 10 50 00" src="https://user-images.githubusercontent.com/30265066/130348787-27e5eb05-3c03-4914-a689-66a270908d53.png">

**Comment by vanpelt** [comment]
Hey @sandylaker we just monitor all network traffic on the machine while the process is running.  The network traffic you're seeing could be from any process on the machine or a network attached filesystem.
