### ISSUE TITLE
Sweep: different seed in every run for bayesian search of hyperparams [Q]

### ISSUE THREAD

**Issue by sudarshanregmi** [wandb/client#2574]
In my code, I run each experiment with a random seed generated from random.choice(range(n)). Does having different seed for each run affect the hyperparameter search using bayesian searching technique? Should I be using the same seed across all the runs created by the sweep?

**Comment by lukas** [comment]
Using a different seed will be fine for Bayesian search.

I would recommend logging the seed so that your runs are reproducible.
