### ISSUE TITLE
[CLI] CondaEnvException since v0.12.0

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [wandb/client#2578]
**Description**
When using `wandb`, I get a `CondaEnvException`:

```
CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.
```

**Wandb features**
`wandb.init()` is enough to reproduce the bug but it occurs also on more complex codes.

**How to reproduce**
```
import wandb
run = wandb.init()
run.finish()
```

**Environment**
- OS: Mac OS BigSur 11.3.1
- Environment: Conda environment
- Python Version: [eg. 3.8.5]

**Comment by vanpelt** [comment]
You just need to activate a conda environment before running the python code: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment

**Comment by gabriel-vanzandycke** [comment]
Is it not allowed to use in the root environement? :O

**Comment by vanpelt** [comment]
Our library detects if we're running in conda and attempts to save the current conda environment by running `conda env export` which is likely causing this error.  You can prevent us from attempting to save the environment by adding the following to `wandb.init`, but I would suggest leveraging formal conda environments for reproducability.

```
wandb.init(settings=wandb.Settings(_save_requirements=False))
```

**Comment by vanpelt** [comment]
I'll go ahead and re-open this issue so we catch this error and print a warning instead of raising the exception.

**Comment by gabriel-vanzandycke** [comment]
Any update on this issue? Is it hard to fix?

**Comment by vanpelt** [comment]
@gabriel-vanzandycke were you not able to fix this with the settings update?  We will not be able to save the conda environment if you're not running in one.  The fix on our end would be to catch this exception and not save the environment.  If you want to capture a reproducible environment you'll need to activate one before running your script.

**Comment by scho97** [comment]
Hi, I am having a same problem in a `Docker` container. I have tried
```
conda env export -n root
conda activate root
```
but it requires me to do `conda init` and then close and restart my shell. However, I cannot do this because I am in my Docker container. I am hesitant to set the `_save_requirements=False` because I want to ensure reproducibility. Is there any suggestion or work arounds to solve this problem?

**Comment by vadimkantorov** [comment]
I have stumbled on this as well. If wandb can't determine conda env name, I'd prefer it not print this exception:
```

CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

```
