### ISSUE TITLE
[Q] hyperparameter tuning with multiple metrics

### ISSUE THREAD

**Issue by alikaz3mi** [wandb/client#2585]
Hello, is it possible to use more than one metric for sweep config? 
i.e. maximizing accuracy and minimizing error rate at the same time?

**Comment by lukas** [comment]
It's not directly supported but that's because it's really easy to set up - just log a third metric and compute it for each run from accuracy and error rate.

**Comment by Mahendra114027** [comment]
> Hello, is it possible to use more than one metric for sweep config? i.e. maximizing accuracy and minimizing error rate at the same time?

Hi, I had the same question, is the approach of creating a third metric from the original metrics still the workaround for this or are there new ways to get this done?
