### ISSUE TITLE
[CLI] AttributeError: Can't pickle local object 'TorchGraph.create_forward_hook.<locals>.after_forward_hook'

### ISSUE THREAD

**Issue by sophiaas** [wandb/client#2588]
I am trying to save a model in PyTorch. I am using `wandb.watch()` on the model with `log_graph=True`
When I call `torch.save(model, PATH)`, I get the following error:

`AttributeError: Can't pickle local object 'TorchGraph.create_forward_hook.<locals>.after_forward_hook'`

This only happens when `log_graph=True`, so I believe it is about the wandb callback. Is there a way to remove the callback for saving?

I know that I can avoid this issue by saving `model.state_dict()` instead of the entire object, but I really do want to save the entire object for a number of reasons. 

**Environment**
- OS: Ubuntu 18.04.4 LT
- Environment: Python
- Python Version: 3.9.2

**Comment by dannygoldstein** [comment]
@borisdayma

**Comment by borisdayma** [comment]
Hey @sophiaas 
Try calling `wandb.unwatch()` or `wandb.unwatch(model)` before saving your model.

**Comment by dipta007** [comment]
> Hey @sophiaas Try calling `wandb.unwatch()` or `wandb.unwatch(model)` before saving your model.

Is there any way to do `wandb.rewatch(model)`
What I want to do is to save the model in training loops, so if I unwatch, I can't make it watch again.

**Comment by lminer** [comment]
If it helps anyone, this only happens to me if I use pytorch-lightning, setting `strategy` to null

**Comment by HernandoR** [comment]
> If it helps anyone, this only happens to me if I use pytorch-lightning, setting `strategy` to null

can you give an short snippet of where to set strategy?
