### ISSUE TITLE
rate limit exceeded

### ISSUE THREAD

**Issue by Arij-Aladel** [wandb/client#2597]
I have many experiments in parallel and I am using wandb to track experiments, but suddenly on wandb all processes crashed but experiments on my server are still in progress. What should I do to get the control again without interrupting my processes?
from wandb log file
"rate limit exceeded, retrying in 2.040469904300563 seconds), retrying request "

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
