### ISSUE TITLE
[Q]how to remove useless agent when using sweep?

### ISSUE THREAD

**Issue by wmkai** [wandb/client#2603]
I want to remove some useless agents when using sweep, but I don't know how do do.

**Comment by JeremySMorgan** [comment]
There's no way to stop an agent directly in the web ui.

A trick however - What you can do is stop the sweep, then cancel the run that the agent you want to stop is doing, and then the agent should stop. Then you can resume the sweep

 Also - Not quite sure what you mean by useless. Could you be more specific?
