### ISSUE TITLE
[Feature] Add unwatch() function to wandb.Run

### ISSUE THREAD

**Issue by AlessioQuercia** [wandb/client#2612]
**Is your feature request related to a problem? Please describe.**
I am using wandb together with Pytorch Lightning and I found out that there is no `Run.unwatch(model)`. In fact I get the following error when trying to unwatch the model from the Run (`logger.experiment.unwatch(model)` in PL):

> AttributeError: 'Run' object has no attribute 'unwatch'

**Describe the solution you'd like**
Even if it should be working by calling `wandb.unwatch(model)`, since Run has a `watch(...)` wouldn't it be more consistent to also add `unwatch(model)` to it?

**Comment by aidanjdonohue** [comment]
Hi @AlessioQuercia I'll pass this along to the client team.
