### ISSUE TITLE
[Q] How to add histograms as a column in a table?

### ISSUE THREAD

**Issue by avijit9** [wandb/client#2613]
Hi, 

Let's say, I have 10 validation samples. For each of them, I would like to plot predictions scores as histograms. All the plots should one column of a table. Is it possible to do that?

TIA

**Comment by vanpelt** [comment]
@avijit9 sure, you can [log a table](https://docs.wandb.ai/guides/data-vis/log-tables):

```
table = wandb.Table(["input","scores1", "scores2",...])
for res in results:
  table.add_data([wandb.Image(res["image"]), wandb.Histogram(res["scores1"]), wandb.Histogram(res["scores2"]), ...])
```

The above assumes scores are arrays of numbers that you want to convert to histograms.  Our table functionality will also automatically create histograms if you just log scalars and then [group by any values](https://docs.wandb.ai/guides/data-vis/tables#group) in the cells.
