### ISSUE TITLE
[Feature]  Sort plots alphabetically

### ISSUE THREAD

**Issue by shehryar-malik** [wandb/client#2618]
**Is your feature request related to a problem? Please describe.**
I often log my metrics into different sections (e.g., Train, Val). Each of these section usually contains several metrics. An example is below
![metrics](https://user-images.githubusercontent.com/28758711/131522218-c1df70e9-2286-4fc9-9cd1-d3f032d52f44.png)

The metrics are sorted alphabetically here, and so all metrics corresponding to Unorm* appear together. Now ideally I would want the plots to appear in the same order in W&B, but the problem is that W&B shuffles all of these plots, and it sometimes becomes frustrating to find the one I'm looking for. 

**Describe the solution you'd like**
It would be nice if there is option to sort plots alphabetically (by their name).

**Describe alternatives you've considered**
Right now, I manually sort the plots. But that consumes time, and each time I add a new plot I need to manually adjust all of them again.

**Comment by armanhar** [comment]
Hey there, you can already sort panels alphabetically by clicking on the 3 dots at the top of a section
<img width="311" alt="Screen Shot 2021-09-01 at 18 21 50" src="https://user-images.githubusercontent.com/89597668/131688447-ad48aa87-ff20-4cf1-857c-4a2b58d60f1c.png">
<img width="286" alt="Screen Shot 2021-09-01 at 18 21 57" src="https://user-images.githubusercontent.com/89597668/131688449-ae9c2229-8999-48d7-9132-68e838c990cf.png">

**Comment by shehryar-malik** [comment]
Thanks a lot.
