### ISSUE TITLE
[CLI] wand.Api.artifact.verify doesn't work

### ISSUE THREAD

**Issue by AndreaPi** [wandb/client#2619]
**Description**
After downloading an artifact to a folder `data_dir`, `wand.Api.artifact.verify(data_dir)` returns `None`, even though based on the signature of the function one would expect it to return `True`:
https://github.com/wandb/client/blob/849b2a9279dc2fa8e814fa83f999c0e5650ee06c/wandb/sdk/interface/artifacts.py#L620

**Wandb features**
`wandb.Api.artifact`, `artifact.download` and `artifact.verify` 

**How to reproduce**
The following script downloads an artifact to a folder and then verifies the folder content against the artifact itself. The result is `None` instead of `True`, as one would expect. Note that you need to substitute the artifact URI with a valid one. I'm not sharing our dataset because I would expect other people not to be able to access it, but if necessary I can share it.

```python
from pathlib import Path
import wandb

artifact_URI = "entity/project/artifact:v0"
data_dir = Path('.').parent / 'data'

api = wandb.Api()
artifact = api.artifact(artifact_URI)

if not data_dir.is_dir():
    data_dir.mkdir(parents=True)

artifact.download(data_dir)

is_same = artifact.verify(data_dir)
print(is_same)  # prints None
```

**Environment**
- OS: Mac OS Catalina 10.15.7
- Environment: Visual Studio Code 1.59.1
- Python Version: 3.8.11

**Comment by vanpelt** [comment]
Hey @AndreaPi this is a lapse on our part.  Currently `verify` will return None on success.  If it finds an invalid file or digest it will raise a `ValueError` exception.

**Comment by AndreaPi** [comment]
Good to know! I'll modify my code accordingly, thanks!
