### ISSUE TITLE
Is there a way to make plots of intermittently logged media? [Q]

### ISSUE THREAD

**Issue by jmusiel** [wandb/client#2621]
I am training a model with some intermittent steps that get logged by wandb but do not contain certain data, so that media is set to "None" in python when it gets logged during those steps. This causes the entire plot on the wandb.ai webapp to display the message 

`Selected runs are not logging media for the key: parent_energy, but instead are logging type`

here is an example printout of the parent_energy value that I am referring to when I get it from the wandb api.run.history() in python

```
0       0.000000
1            NaN
2            NaN
3            NaN
4     -57.726136
         ...    
228          NaN
229          NaN
230          NaN
231          NaN
232          NaN
Name: parent_energy, Length: 233, dtype: float64
```

There are maybe 30 or so steps where the parent energy is logged out of 233 steps.

I would like to be able to log these intermittent steps during training, just like any other step, and be able to display a plot of the "parent_energy" on the steps where it does occur, is this possible?

**Comment by vanpelt** [comment]
@jmusiel can you share a link to a run that exhibits this behavior?

**Comment by jmusiel** [comment]
Well this is very odd.

I went to go do as you asked and found a run that seems to behave this way:

https://wandb.ai/ulissi-group/train_on_points_0_and_2/runs/1r5ad4m1

However when I open that link while logged out of my wandb account, it appears to display the plots I am interested in the way I want them (parent_energy being the main one). It fails to display the plots when I am logged in however. So this is only happening to me when I am logged in to wandb as far as I can tell. Not sure if it has something to do with my account or if you will see the same thing when you are logged in.

**Comment by jmusiel** [comment]
Switching to the default workspace (bottom left hand corner of the workspace page) and back seems to have solved my issue
