### ISSUE TITLE
[Q]Wandb seems not logging the gradient for parameters that updated in optimizer during training

### ISSUE THREAD

**Issue by jihwanp** [wandb/client#2625]
Hi, I recently work on transfer learning so I dynamically update the optimizer to unfreeze the model parameters.
What I found was that the parameters that I unfreeze compute gradients and were updated but it seems that wandb does not log those parameters' gradients. Is it a bug or can it be fixed by calling ` wandb.watch(model)` later during the training ?

I have some doubts about this situation so I remain this issue for Question.

Thanks

**Comment by anmolmann** [comment]
Hi @jihwanp, the gradients come for calling `wandb.watch` which has a `log_freq` parameter telling us how often to log the gradients. 
To log gradients and store the network topology, you can call `.watch` on your model. Then use `.log` for anything else you might need to track.

**Comment by anmolmann** [comment]
Hi @jihwanp, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
