### ISSUE TITLE
[View-only report will still expose whole project to others] 

### ISSUE THREAD

**Issue by MendelXu** [wandb/client#2626]
**Is your feature request related to a problem? Please describe.**

I  am working on a private project and I have to show some results to others. For some reason, I would like only the report visible to others instead of the whole project. Is there any way to perform such an operation?

**Describe the solution you'd like**

Select which part of a project to be visible only.

**Describe alternatives you've considered**

**Additional context**

**Comment by armanhar** [comment]
Hey there, you can create a report for a private project and share a view-only link to it. Here is the [link](https://docs.wandb.ai/guides/reports#view-only-report-links) to the docs

**Comment by MendelXu** [comment]
It is not enough. For example, I create a view-only link [here](https://wandb.ai/mendelxu/astro/reports/Untitled-Report--Vmlldzo5ODQyOTc?accessToken=do7j1kq5fn08mqgsgdt00nboxtzmqtdmke89s1trvhl8hlc5ouk5cxt514v7qd29). However, by clicking on the project name in the navigator, you can still see all of my experiments in the project name.

**Comment by MendelXu** [comment]
> It is not enough. For example, I create a view-only link [here](https://wandb.ai/mendelxu/astro/reports/Untitled-Report--Vmlldzo5ODQyOTc?accessToken=do7j1kq5fn08mqgsgdt00nboxtzmqtdmke89s1trvhl8hlc5ouk5cxt514v7qd29). However, by clicking on the project name in the navigator, you can still see all of my experiments in the project.

I have to close it now as it may expose my github token....

**Comment by armanhar** [comment]
I see, I am opening a ticket so that the team can look into this. Will keep you updated.

**Comment by armanhar** [comment]
Hey there, the issue should be fixed now. Thanks for reporting this.

**Comment by MendelXu** [comment]
I see. Thanks for your hard work.
