### ISSUE TITLE
How to perform a sweep?[Q]

### ISSUE THREAD

**Issue by al967** [wandb/client#2630]
I have a model setup up where I pass arguments through a .sh file, and the wandb arguments to log the metrics are in a .py file.

The arguments in the .py file are as follows:

```
def train_model():

    # Get args
    args = Args().parse_args()

    # Setup wandb
    wandb.init(entity="xxx", project="xxx", name=args.experiment_name)
    wandb.tensorboard.patch(save=False, tensorboardX=True, pytorch=True)
    wandb.config.update(args.as_dict())

    # Change save_dir to wandb run directory
    args.save_dir = wandb.run.dir
    save_dir = Path(args.save_dir)

    # Save files to cloud as the run progresses
    files_to_save = [
#        save_dir / "fold_0" / "*.csv",
        save_dir / "args.json",
        save_dir / "fold_0/model_0/model.pt",
    ]
    for file in files_to_save:
        wandb.save(str(file), base_path=str(save_dir))


    # Run training
    cross_validate(args=args, train_func=run_training)
```

Most of the tutorial on using sweep in wandb involve .py files, but could the setup described above still be used to perform a sweep?

**Comment by vanpelt** [comment]
Yep that should work fine.  You will want to move `wandb.tensorboard.patch` before your call to `wandb.init` and you could just set `config=args` in your `init` call as well, but config.update works.  In your sweep config you'll specify a program that you want our agent to run.  In your case that program should be the `.sh` file which will call your python script.  Given the following example:

```
wandb agent USERNAME/PROJECT/SWEEP
# The agent will now execute: my_script.sh --arg1 X --arg2 Y --arg3 Z
```

As long as your shell script is passing the original script arguments to your python script the code you shared should work fine.  The python script would of course need something like:

```
if __name__ == '__main__':
    train_model()
```
