### ISSUE TITLE
[CLI] wandb: WARNING Config item 'hyperparam_name' was locked by 'sweep' (ignored update)

### ISSUE THREAD

**Issue by maxwass** [wandb/client#2641]
**Description**
When running basic hyper parameter search (following this [tutorial](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch/Organizing_Hyperparameter_Sweeps_in_PyTorch_with_W%26B.ipynb#scrollTo=rHpan13W6UZD) very closely) I get:
`wandb: WARNING Config item 'hyperparam_name' was locked by 'sweep' (ignored update).`
for many, but not all, of my hyper parameters

**Wandb features**
Using WandB with Pytorch Lightning to perform simple hyper parameter search. WandB logger callback for pytorch lightning used to log relevant metrics.

######### Pseudo Code ######### 
```
import wandb
from pytorch_lightning.loggers import WandbLogger
import pytorch_lightning as pl


sweep_config = {
    "method" : "random",
    "metric" : {"name": "val/error_epoch", "goal": "minimize", "target": 0.05}, #error of 5%
    "early_terminate" : {"type": "hyperband", "min_iter": 20, "eta": 3},
    "parameters" :
        {
        "share_parameters": {"value": share_parameters},
        # architecture hps
        "iterations": {"values": [2, 5, 10]},
         .... more params ...
        # trainer hps
        "epochs": {"value": 500},
        "batch_size": {"values": [16, 32, 64, 128, 256]},
        }
}


def train(config=None):
    with wandb.init(config=config):
        # Config is a variable that holds and saves hyperparameters and inputs
        config = wandb.config

       # construct trainer, model, & data module  by setting relevant arguments with 'config.param_name'
       dm = my_dm(batch_size = config.batch_size, ....)
       trainer = pl.Trainer(max_epochs = config.epochs, WandbLogger(project=my_project_name), ....) 
       model = my_model(iterations=config.iterations, ...)

       trainer.fit(model, train_dataloader=dm.train_dataloader(), val_dataloaders=dm.val_dataloader())

       #if on colab
       wandb.finish()

wandb.agent(sweep_id, train)
```

**Environment**
Occurs both on my local machine (2015 MacBook Air, macOS Big Sure 11.2.3) using Python 3.7.9 and Google Colab with a GPU using Python 3.7.11. Using most up to date Pytorch Lightning and WandB.

It seems [someone else has had this issue](https://github.com/wandb/client/issues/1698) as well but it has not been resolved. Interestingly I am also getting a CUDA out of memory error; someone else in the aforementioned unresolved issue also had these two exact issues. Not sure if these issues are connected, but I will post a new issue for that soon.

Thanks,
Max

**Comment by vanpelt** [comment]
Hey @maxwass are you calling `wandb.config.update(...)` anywhere in your code?  The pytorch lightning integration calls config.update which would be triggering the error.  In this case you should be able to ignore the error because `wandb.run.config` will be prepopulated with the appropriate config.  We can look into fixing this in the integration in a future release.

**Comment by maxwass** [comment]
Nope not calling `wandb.config.update()` , all the methods called using wandb are shown.

So just to be clear, even though pytorch lightning calls `wand.update` causing these warnings, everything should be working as expected?

**Comment by vanpelt** [comment]
Yep, everything should still work.

**Comment by csestili** [comment]
hi, is there any way to unlock the sweep parameters so I can update the config anyway?

**Comment by erlebach** [comment]
Hi, 

I received the message "locked by 'sweep' (ignored update)." and am not using pytorch lightning. What is the origin of this error message? Thanks.

**Comment by csestili** [comment]
@erlebach this happens when you try to update a value inside `wandb.config` during a sweep. this object seems to be locked during sweeps, maybe so that you don't inadvertently set a value that the sweep would change.
