### ISSUE TITLE
[Q] How to log data with custom x-axis flexible and convenient？

### ISSUE THREAD

**Issue by StepNeverStop** [wandb/client#2642]
For some training tasks, we usually log some data in `epoch` and others in `step` of the x-axis.

If I write code like:

```python
for i in range(10):
    wandb.log({'x': i}, step=i)

for j in range(0, 20, 2):
    wandb.log({'y': j}, step=j)
```

then it doesn't work:

```python
wandb: WARNING Step must only increase in log calls.  Step 0 < 9; dropping {'y': 0}.
wandb: WARNING Step must only increase in log calls.  Step 2 < 9; dropping {'y': 2}.
wandb: WARNING Step must only increase in log calls.  Step 4 < 9; dropping {'y': 4}.
wandb: WARNING Step must only increase in log calls.  Step 6 < 9; dropping {'y': 6}.
wandb: WARNING Step must only increase in log calls.  Step 8 < 9; dropping {'y': 8}.
```

One promising way is calling `.log` like this:

```python
for i in range(10):
    wandb.log({'x': i, 'x_step': i})

for j in range(0, 20, 2):
    wandb.log({'y': j, 'y_step': j})
```

but this way needs to select the x-axis of `x` to `x_step` and `y` to `y_step` manually on the website, which is so inconvenient.

Is there any better way to deal with situations like this more flexible?

**Comment by vanpelt** [comment]
Hey @StepNeverStop if you want to log multiple x-axis values you'll need to use the second approach.  You can assign custom axis to charts programmatically by calling [define_metric](https://docs.wandb.ai/ref/python/run#define_metric), i.e.

```
wandb.run.define_metric("y", step_metric="y_step", goal="maximize")
wandb.run.define_metric("x", step_metric="x_step", goal="minimize")
```
