### ISSUE TITLE
[CLI] wandb.watch leaks system memory (i.e. not gpu memory)

### ISSUE THREAD

**Issue by crizCraig** [wandb/client#2644]
**Description**
System memory is stable during training, but large 1GB chunks are utilized shortly after taking checkpoints. When I comment out `wandb.watch(model)`, the issue goes away.

**Wandb features**
`init` `watch` `log` `lightning`

**How to reproduce**
1. I can share the private repo if you want to reproduce

**Environment**
- OS: Ubuntu 18.04.5 LTS 
- Environment: Anaconda
- Python Version:  3.8.10
```
pytorch-lightning==1.3.8
torch==1.9.0
torchaudio==0.9.0a0+33b2469
torchmetrics==0.4.1
torchvision==0.10.0
wandb==0.11.0
...
```

**Comment by vanpelt** [comment]
Hey @crizCraig `wandb.watch` pulls down histograms of all gradients in your network and copies them from GPU to CPU.  We would expect memory to increase while logging these histograms, but it should be released immediately.  If you can share a private repo we can determine if this is a bug.

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
