### ISSUE TITLE
[CLI] Crash when making a request to localhost/graphql during initialization

### ISSUE THREAD

**Issue by Dencher92** [wandb/client#2645]
**Description**
During the initialization of wandb the error occurs while it is trying to make a request to localhost/graphql:

> 400 response executing GraphQL.
> {"error":"EOF"}

The installation is local.

Full trace:

> 400 response executing GraphQL.
> {"error":"EOF"}
> 
> 400 response executing GraphQL.
> {"error":"EOF"}
> 
> wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
> Thread SenderThread:
> Traceback (most recent call last):
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
>     return func(*args, **kwargs)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1087, in upsert_run
>     response = self.gql(mutation, variable_values=variable_values, **kwargs)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
>     result = self._call_fn(*args, **kwargs)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 136, in execute
>     six.reraise(*sys.exc_info())
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/six.py", line 719, in reraise
>     raise value
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
>     return self.client.execute(*args, **kwargs)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
>     result = self._get_result(document, *args, **kwargs)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
>     return self.transport.execute(document, *args, **kwargs)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
>     request.raise_for_status()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:11112/graphql
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 52, in run
>     self._run()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
>     self._process(record)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 290, in _process
>     self._sm.send(record)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 184, in send
>     send_handler(record)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 623, in send_run
>     self._init_run(run, config_value_dict)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 645, in _init_run
>     server_run, inserted = self._api.upsert_run(
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 26, in wrapper
>     raise CommError(err.response, err)
> wandb.errors.CommError: <Response [400]>
> wandb: ERROR Internal wandb error: file data was not synced
> Problem at: test_wandb.py 3 <module>
> Traceback (most recent call last):
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 775, in init
>     run = wi.init()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 531, in init
>     backend.cleanup()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
>     self.interface.join()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 830, in join
>     _ = self._communicate(record)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
>     return self._communicate_async(rec, local=local).get(timeout=timeout)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
>     raise Exception("The wandb backend process has shutdown")
> Exception: The wandb backend process has shutdown
> wandb: ERROR Abnormal program exit
> Traceback (most recent call last):
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 775, in init
>     run = wi.init()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 531, in init
>     backend.cleanup()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
>     self.interface.join()
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 830, in join
>     _ = self._communicate(record)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
>     return self._communicate_async(rec, local=local).get(timeout=timeout)
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
>     raise Exception("The wandb backend process has shutdown")
> Exception: The wandb backend process has shutdown
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "test_wandb.py", line 3, in <module>
>     wandb.init(project='matcher', entity='denis-ivashkov')
>   File "/home/denis.ivashkov/anaconda3/envs/denis_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 812, in init
>     six.raise_from(Exception("problem"), error_seen)
>   File "<string>", line 3, in raise_from
> Exception: problem

**Wandb features**
I run the script from console like this:
`WANDB_API_KEY=$MY_API_KEY WANDB_BASE_URL="http://localhost:11112/" python test_wandb.py`
The script itself is very basic:
```
import wandb
wandb.init(project='my_project', entity='denis-ivashkov')
```
as can be seen from the trace, init() function throws the exception.
However when I use wandb logger for Lightning the problem appears as well (may provide scripts etc. if needed).

**How to reproduce**
1. Create a python environment as `python3 -m venv denis_env`
2. Install wandb as `pip install wandb`
3. Launch it locally as `wandb local --upgrade -p 11112`
4. It will download an image wandb/local and run a container
5. When it prompts go to `http://localhost:11112/authorize`, obtain an api_key (or register first)
6. Copy paste the key back to the console
7. Run the script as showed above
8. Observe the Exception

**What I tried**
1. Registered two different accounts
2. Refreshed api key
3. Removed wandb and docker image and run wandb local again
4. Removed and made a clean python environment 
5. Tried anaconda environment
6. Tried using `0.0.0.0` as the `base_url` instead localhost
7. Tried version 0.11.0 instead of 0.12.1

**Environment**
- OS: Linux 18.04.1-Ubuntu (also tried on MacOS Catalina 10.15.7)
- Environment: just a clean python environment (although I also tried conda 4.8.3 with no luck)
- Python Version: 3.8.5
- Wandb version: 0.12.1 (tried 0.11.0 as well)

**Comment by vanpelt** [comment]
@Dencher92 there could be a couple things going on here.  Can you try the following:

```
docker stop wandb-local
wandb local -e HOST=http://localhost:11112
wandb login --host=http://localhost:11112
python test_wandb.py
```

The trailing slash in `WANDB_BASE_URL` in your example may have caused an issue.  Calling `wandb login --host=http://localhost:11112` will configure your machine to always connect to that local server so you don't need to pass environment variables.  If this doesn't work, can you got to http://localhost:11112/system-admin and download the Debug Bundle from the menu in the upper right?  You can send it to vanpelt@wandb.com

**Comment by Dencher92** [comment]
@vanpelt removing the trailing slash did the trick. Thank you for your support!
