### ISSUE TITLE
[Q] How to change the default camera angle of `wandb.Object3D` panel in web interface ?

### ISSUE THREAD

**Issue by dasayan05** [wandb/client#2646]
I am writing a pointclouds in `np.ndarray` (specifically of `[x,y,z,c]` [style](https://docs.wandb.ai/ref/python/data-types/object3d)). However, all my 3D clouds are actually 2D (i.e. `z=0`). So, I need to visualize them along z axis from above.

The default camera angle in the panel in not very good. I need to rotate them with mouse all the time. I have a lot of such pointclouds so its infeasible to do so.

Is there a way to change the default camera angle while viewing pointclouds ?

PS: I am new to `wandb` and maybe I missed something obvious.

**Comment by aidanjdonohue** [comment]
Hi @dasayan05 it sounds like using a [custom scatter plot](https://wandb.ai/wandb/plots/reports/Custom-Scatter-Plots--VmlldzoyNjk5NDQ) would be more appropriate for this use case.

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
