### ISSUE TITLE
[Q] How to log a list of matplotlib axes so that I can use the "example index" slider

### ISSUE THREAD

**Issue by dasayan05** [wandb/client#2649]
I want to log a list of matplotlib axes via `.log()` call. The way I currently do is create a subplot of all axes and log the whole figure using
```python
fig, ax = plt.subplots(2, 2, ...)
...
wandb.log({'samples': fig})
```
However, this doesn't treat individual axis as "one example" in the panel. I tried creating multiple plots
```python
fig1, ax1 = plt.subplots(1,1)
fig2, ax2 = plt.subplots(1,1)
...
wandb.log({'samples': [fig1, fig2]})
```
but ened up in an error saying
```bash
TypeError: Object of type Figure is not JSON serializable
```
What is the right way to do it ?

**Comment by vanpelt** [comment]
If you wrap each fig in a `wandb.Plotly(fig1)` or a `wandb.Image(fig1)` it should work.

**Comment by dasayan05** [comment]
Thank you @vanpelt , the `wandb.Image(..)` is indeed working but not `wandb.Plotly(..)`. With `Plotly`, it isn't logging anything for the specific panel.

Even though its fine for the time being but I would love to keep the figures interactive rather than rasterized.

**Comment by vanpelt** [comment]
Ahh, that's too bad.  `wandb.Plotly` will convert the matplotlib figures into interactive json but we don't currently support logging lists of interactive plots.  For now the best compromise is logging each figure at a different key:

```
wandb.log({'sample1': fig1, 'sample2': fig2})
```

**Comment by vanpelt** [comment]
If you call the above example multiple times in the same script, you'll get the slider.  In your case it may make more sense to run:

```
for fig in [fig1, fig2]:
   wandb.log({'sample': fig})
```

**Comment by vanpelt** [comment]
Can you share a link to the run where this isn't working for you?

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
