### ISSUE TITLE
[Feature, App] Move runs to different group

### ISSUE THREAD

**Issue by magehrig** [wandb/client#2653]
I created a run under a certain group. Afterward, I would like to have the opportunity to move this run to a different group. Currently, this is not possible, which means that my initial assignment to a group is permanent.

**Comment by armanhar** [comment]
Hey Mathias, thanks for writing in. We already have an internal ticket for changing the group of a run. I'll bump up its priority and let you know once the feature is available.

**Comment by collinmccarthy** [comment]
@armanhar Does the current ticket include adding runs to a group via the UI, if they're not already in a group? Basically I'm looking to "create a group" and group some selected runs together in the UI, just to organize things better.

**Comment by kagura0108** [comment]
> I created a run under a certain group. Afterward, I would like to have the opportunity to move this run to a different group. Currently, this is not possible, which means that my initial assignment to a group is permanent.

hi, i want to do the same thing
if wandb staffs got this done, i would be happy

**Comment by trahflow** [comment]
Is this possible by now? The ticket was closed as completed, suggesting it would be. But I couldn't figure out how. Is there an update/documentation for this?
