### ISSUE TITLE
[Feature] Trash can for runs

### ISSUE THREAD

**Issue by richardrl** [wandb/client#2659]
We need to delete hundreds of runs a day. This is very common. However, the current method for deletion is extremely dangerous - it is easy to accidentally delete a _valid_ run that took 100 hours to run and $xxxx cost.

You should add a trash can that stores the runs after deletion for 30 days. This way, we can still delete runs to keep our main workspace organized, but there's no risk of serious data loss.

**Comment by vanpelt** [comment]
Hey @richardrl deletion is already implemented this way, we always soft-delete your runs.  We don't currently expose the un-delete functionality in our UI but we can manually un-delete runs if you need us to.  I'll leave this ticket open as we eventually plan to support un-delete in the UI.

**Comment by armanhar** [comment]
Hey Richard, at the moment you can undelete all the runs that have been deleted for the past 7 days. The option is in the overview section of a project
<img width="303" alt="Screen Shot 2021-09-16 at 16 48 47" src="https://user-images.githubusercontent.com/89597668/133614842-c1cbfd94-8cfb-4878-82bd-2ce273fee139.png">

**Comment by cgebbe** [comment]
Old thread, but I would like to upvote a feature to...
- more selectively undelete runs (not just undelete ALL runs from past 7 days)
- make it more transparent which runs are available for undeleting
- make it more transparent when runs are hard-deleted (7 or 30 days?)
