### ISSUE TITLE
[CLI] Cannot delete artifact with only one version

### ISSUE THREAD

**Issue by magehrig** [wandb/client#2660]
**Description**
When an artifact of a wandb run has only one version, it cannot be deleted successfully (tested with the Python API).

**Wandb features**
I am using [wandb.apis.public.Api](https://docs.wandb.ai/ref/python/public-api/api) to delete artifacts.

**How to reproduce**
1. Create a run with an artifact that has only one version. The same holds if a run has multiple artifacts with only one version each.
2. Run the following code:

```Python
import wandb
api = wandb.Api()
runpath = 'YOUR_RUN_PATH'
run = api.run(runpath)
for artifacts in run.logged_artifacts():
	artifacts.delete()
```
This will raise a `wandb.errors.CommError`

**Environment**
- OS: Ubuntu Server 18.04 (kernel version 4.15.0-154-generic)
- Environment: conda
- Python Version: 3.8.11
- wandb version: 0.12.1

**Comment by aidanjdonohue** [comment]
Hi @magehrig looking into this for you. Could you let me know which version of `wandb` you're using?

**Comment by magehrig** [comment]
0.12.1
