### ISSUE TITLE
[App] Unable to display values in bar chart legend without hover

### ISSUE THREAD

**Issue by MatthewGleeson** [wandb/client#2661]
I'm trying to modify the legend of the bar chart that gets displayed, and can do so perfectly well with variables in the run's configuration( for example, using `${config:objective_function_name}`. 

However I am unable to add the actual value of the variable that is getting displayed in the bar chart. I want it to show something like: 
"objective_function:erm test_error:.00005"

So, my legend template for the bar chart is:

`objective_function:${config:objective_function_name} test_error: ${x}`

However the output I'm getting is:
"objective_function:erm test_error:"

I know that `${x}` is the correct variable because when I have it inside of the double brackets, like `[[${x}]]` in the legend template it displays when hovered over. 

Am I doing something wrong or is this just an unsupported feature?

**Comment by cvphelps** [comment]
@MatthewGleeson thanks for reporting this, I'll need to reproduce the issue to dig in here. Would you be able to generate a report link for me here (or email support@wandb.com) to show a case where this is happening?

**Comment by cvphelps** [comment]
@MatthewGleeson could you share a link to a bar chart where you're having this issue?

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
