### ISSUE TITLE
[Q] Is there a way to combine runs from different `wandb local` into a single one?

### ISSUE THREAD

**Issue by optimass** [wandb/client#2662]
Hello,

I'm trying to aggregate the runs I collected with different `wandb local` instances into a single one, so that I can look at all my runs simultaneously.

Is there a simple way to do that? Also, could I run wandb in an offline mode and then somehow add up the collected runs in a folder and then run `wandb local` on it?

**Comment by vanpelt** [comment]
Hey @optimass we do not support merging multiple instances of `wandb local`.  It's meant for trying out the service, we would suggest configuring a production install by obtaining a license and configuring an external MySQL and object store.

You can sync local run folders to any wandb server.  Just make sure you're logged in to the appropriate server with `wandb login --host=http://localhost:8080` and then run `wandb sync wandb/run-XXX-XXXXXXX` where the XXX's are replaced with the actual local run folders.

**Comment by optimass** [comment]
Great, that worked!

Some extra notes if someone else is switching between standard and self-hosted `wandb` and gets here:

after `wandb local`, maybe `wandb login --host=http://localhost:8080` will work fine but `wandb sync` will throw :
```bash
    raise CommError("Invalid or missing api_key.  Run wandb login")
wandb.errors.CommError: Invalid or missing api_key.  Run wandb login
```
in this case, run `wandb login --relogin --host=http://localhost:8080` and paste the API key of your local account
