### ISSUE TITLE
File download fails

### ISSUE THREAD

**Issue by rmst** [wandb/client#267]
* Weights and Biases version: `wandb.__version__ == '0.6.27'`
* Python version: 3.6.5 Anaconda
* Operating System: Ubuntu 18.04

### Description

When trying to download a file via `wandb.Api().run("rmst/ssvg/rm8dpyrx").file('blip').download()` it fails with

```
500 Server Error: Internal Server Error for url: https://api.wandb.ai/rmst/ssvg/rm8dpyrx/blip
```

The download via the web interface works. The metadata for 'blip' is also available through the API. Just `download()` seems to fail.

**Comment by vanpelt** [comment]
Hey @rmst.  I'm planning to release a new package today to address this issue.  In the meantime you can install from master to fix it:  `pip install --upgrade git+git://github.com/wandb/client.git@master#egg=wandb`

**Comment by rmst** [comment]
Awesome, such a quick answer and it works! Thank you!
