### ISSUE TITLE
[Feature] Manually add columns in tables

### ISSUE THREAD

**Issue by harveenchadha** [wandb/client#2670]
**Is your feature request related to a problem? Please describe.**
I am using wandb for kaggle trainings now but the problem is that I am not able to update test set score for a particular model in tables tab.

**Describe the solution you'd like**
Give add, delete, edit, update option in columns of tables

**Describe alternatives you've considered**
Writing in reports but can't compare in the tables column.

**Comment by aidanjdonohue** [comment]
Hi @harveenchadha can you please post a screenshot of the table you're trying to update? It seems like this could be better achieved by joining two tables but I'd like to understand your use case more.

**Comment by harveenchadha** [comment]
For example if I want to add a new column here in which I can save the test set results. There is no way to do it and hence I cannot track parameters outside of my model training.

![Screenshot from 2021-09-16 01-53-03](https://user-images.githubusercontent.com/30959215/133504146-0c108c31-c9da-4842-8c0c-fc9702c46bd2.png)

**Comment by aidanjdonohue** [comment]
So if you logged something during the run or even added something to the run summary post run using the API, then you should be able to visualize that value as a column in your runs table. My two suggestions would be to 1). update the run summary using the API to include the test set results or 2). create new runs with job_type="testing" that take in the model artifacts and testing set as inputs. You could then visualize the results of just the testing jobs through a simple filter and be able to see which run produced the model that achieved that test score.

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.

**Comment by phamthaihoangtung** [comment]
I also need that feature. Sometimes, we can come up with new metrics or new information that comes from old columns. Therefore, it is better to allow quick manual creation instead of rerunning.

**Comment by jasperhyp** [comment]
+1

**Comment by arogozhnikov** [comment]
I need to use spreadsheets to track additional info, and this feature would be very valuable

**Comment by jhagege** [comment]
Hi any possibility to add this feature? Would be very helpful thanks!

**Comment by cpudan** [comment]
Also looking for this feature to support basic mathematical operations for adding in new computed metrics to individual runs or for all runs in a sweep. For example, it would be incredibly useful to be able to create a new column `summary['computed_column'] = summary['column_a'] + summary['column_b']` without having to use the API. Thank you!
