### ISSUE TITLE
[App] Cannot create account on wandb.ai

### ISSUE THREAD

**Issue by Godofnothing** [wandb/client#2677]
I am trying to create an account on the wandb.ai, and I have encountered the following issue:

1) I fill the name, organization and the user name in the fields

<img width="393" alt="Снимок экрана 2021-09-17 в 14 24 26" src="https://user-images.githubusercontent.com/29793750/133775184-90e0a406-3719-447c-9522-5be6a196b3e6.png">

2) On the next page I receive an error message

<img width="713" alt="Снимок экрана 2021-09-17 в 14 25 13" src="https://user-images.githubusercontent.com/29793750/133775365-2bd11689-04f1-4628-be23-7ab9f6707edc.png">

Is there some server maintenance at the moment, or there is some other reason for this error message. 

My account has been created via `GitHub`

Thanks in advance for help!

**Comment by cvphelps** [comment]
@Godofnothing thank you for reporting this concerning issue! Could you please message support@wandb.com with your username from the email associated with your GitHub account? We want to get this fixed for you asap.

**Comment by cvphelps** [comment]
@Godofnothing talking to the team internally, this error means you already have an account associated with that email address. Have you previously signed up using an email+password or a Google login rather than GitHub?

**Comment by Godofnothing** [comment]
@cvphelps  Yeah, seems like probably I've logged in via email. I've tried to log in via email and I have this window:
<img width="313" alt="Снимок экрана 2021-09-17 в 20 59 26" src="https://user-images.githubusercontent.com/29793750/133833326-fba9ee1f-640d-4840-ae73-463d9a546f54.png">

But after clicking on this windows I am again redirected to the create account page, where I receive the same error message as before.

**Comment by Godofnothing** [comment]
@cvphelps  seems like something was fixed and now I can enter the page. Thanks for support!
