### ISSUE TITLE
[App] Text box expands every time I type

### ISSUE THREAD

**Issue by samuela** [wandb/client#2683]
**Describe the bug**
See https://user-images.githubusercontent.com/226872/133910942-1b1ea85d-0569-4249-b103-af95d2f2d51d.mov

**To Reproduce**
Unclear exactly how to reproduce this but I saw the effect in the plot detail modal.

**Expected behavior**
The text box to stay in one place.

**Screenshots**
n/a

**Operating System**
 - OS: macOS 11.5.2
 - Browser Firefox 92.0

**Additional context**
n/a

**Comment by anmolmann** [comment]
Hey @samuela, thanks for reporting the bug. This looks like a frontend bug to me, I'm filing a bug report for this one.

**Comment by anmolmann** [comment]
Hey @samuela , this issue has been fixed. Please let us know if you still encounter it.
