### ISSUE TITLE
AttributeError: partially initialized module 'wandb' has no attribute 'data_types' (most likely due to a circular import)

### ISSUE THREAD

**Issue by sumalatha8280** [wandb/client#2685]
I am trying to extract a sentence from keywords and I have installed keytotext in anaconda prompt using pip command (pip install keytotext). now, when I have used the below line of import command, i am getting attribute error. 

from keytotext import pipeline
nlp = pipeline("k2t-base")  #loading the pre-trained model
params = {"do_sample":True, "num_beams":4, "no_repeat_ngram_size":3, "early_stopping":True}    #decoding params
print (nlp(['Delhi', 'India', 'capital'], **params))

**Comment by vanpelt** [comment]
Can you try adding import wandb at the top of your file?  If that doesn't work, please provide a traceback.

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
