### ISSUE TITLE
[CLI] ModuleNotFoundError: No module named 'wandb.integration'; 'wandb' is not a package

### ISSUE THREAD

**Issue by roboserg** [wandb/client#2686]
Code from the Basic Example from here https://gitbook-docs.wandb.ai/guides/integrations/other/stable-baselines-3

```
(fastchan) E:\DeepLearning\RLgym>python wandb.py
Traceback (most recent call last):
  File "wandb.py", line 5, in <module>
    import wandb
  File "E:\DeepLearning\RLgym\wandb.py", line 6, in <module>
    from wandb.integration.sb3 import WandbCallback
ModuleNotFoundError: No module named 'wandb.integration'; 'wandb' is not a package
```

If I comment out the 6th line (so only import wandb), still an error:

```
(fastchan) E:\DeepLearning\RLgym>python wandb.py
Traceback (most recent call last):
  File "wandb.py", line 5, in <module>
    import wandb
  File "E:\DeepLearning\RLgym\wandb.py", line 14, in <module>
    run = wandb.init(
AttributeError: partially initialized module 'wandb' has no attribute 'init' (most likely due to a circular import)
```

**Comment by vanpelt** [comment]
The error is being caused by the python import system thinking that you want to import the `wandb.py` file when you run `import wandb`.  Just change the name of your script from `wandb.py` to `train.py` or `main.py` anything other than `wandb.py`.

**Comment by roboserg** [comment]
@vanpelt Thanks, this was shameful :) 
Another issue I am having is that wandb doesn't upload tensorboard logs  to wandb. I only see "gradients" and "system" in wandb, image - https://i.imgur.com/TeqGHKN.png
I am using your example code:

```

import gym
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import *
import wandb
from wandb.integration.sb3 import WandbCallback


config = {
    "policy_type": "MlpPolicy",
    "total_timesteps": 10000,
    "env_name": "CartPole-v1",
}
run = wandb.init(
    project="sb3",
    config=config,
    sync_tensorboard=True,  # auto-upload sb3's tensorboard metrics
    monitor_gym=True,  # auto-upload the videos of agents playing the game
    save_code=True,  # optional
)


def make_env():
    env = gym.make(config["env_name"])
    env = Monitor(env)  # record stats such as returns
    return env


env = make_env()
#env = VecMonitor(env)

model = PPO(config["policy_type"], env, batch_size=512, n_steps=512, verbose=1, tensorboard_log=f"runs/{run.id}")
model.learn(
    total_timesteps=config["total_timesteps"],
    callback=WandbCallback(gradient_save_freq=100, model_save_path=f"runs/{run.id}", verbose=2,),
)
run.finish()

```

**Comment by vanpelt** [comment]
Hey @roboserg not shameful, it's happened to me a few times and always makes me scratch my head.

For the tensorboard sync issue, can you share a link to a run that was created by this code?  I want to confirm if the tensorboard files are getting uploaded to wandb.  

This shouldn't make a difference but you can scope our tensorboard syncing to a specific logdir.  This would only matter if you were creating a number of different tfevent files in the logdir which I doubt is the case.

```python
id = wandb.util.generate_id()
logdir = f"runs/{id}"
wandb.tensorboard.patch(root_logdir=logdir)
run = wandb.init(
    project="sb3",
    id=id,
    config=config,
    monitor_gym=True,  # auto-upload the videos of agents playing the game
    save_code=True,  # optional
)
```

**Comment by roboserg** [comment]
The issue is resolved. Running the terminal as admin solves it. Is there a way to force the new Windows terminal to start as "admin"?
