### ISSUE TITLE
[CLI] ~/.cache directory unbounded in size

### ISSUE THREAD

**Issue by dlangerm** [wandb/client#2690]
**Description**
wandb apparently keeps a folder for caching objects at ~/.cache/wandb. When running a ton of sweeps, some of which may fail, the size of this directory can be pretty huge since the objects aren't cleaned up. For example, mine was ~400GB. This obviously needs to be cleaned up automatically somehow or at least monitored to warn the user that this is happening.

**Wandb features**
Sweeps w/ Pytorch Lightning

**How to reproduce**
1. Run a sweep which keeps things in the .cache directory
2. Observe growth

**Environment**
- OS: Linux
- Environment: GCP
- Python Version: 3.9

**Comment by vanpelt** [comment]
Hey @dlangerm we have plans to automatically cleanup this cache.  Until then we do provide a command.  You can run the following:

```
wandb artifact cache cleanup 10GB
```

This will remove the most stale objects from the cache keeping only 10GB of the most recently accessed objects.

**Comment by dlangerm** [comment]
@vanpelt Thanks! 

I have an automation tool I'm building around the CLI, is this command going to have guaranteed support going forward or is it just a temporary fix?

**Comment by vanpelt** [comment]
It's officially supported!
