### ISSUE TITLE
[App] I can not create a team because the organization hasn't any private teams left

### ISSUE THREAD

**Issue by bablf** [wandb/client#2693]
**Describe the bug**

**To Reproduce**
I click on Invite your team. Enter a name and an error occurs. 
The Error says 
`organization does not have any private teams left

An application error occurred.

Click to refresh the page.`

**Expected behavior**
I should be able to create a team.

**Screenshots**
![image](https://user-images.githubusercontent.com/57184353/134349743-7480cbf7-2196-431c-b29e-230cf4f3a207.png)

**Operating System**
 - Browser : Firefox

**Comment by armanhar** [comment]
Hey there, can you tell me your organization name?

**Comment by bablf** [comment]
Hi, it's lary tech. As you might notice a colleague of mine was able to create a new team (Lary Tech GmbH). So I don't have the problem any more. But maybe this helps you find the error on your end :sweat_smile:

**Comment by armanhar** [comment]
Hey there, just wanted to confirm that you were able to create a team and that the issue is resolved.
