### ISSUE TITLE
[CLI] Rate limiting on HP Sweep

### ISSUE THREAD

**Issue by maxwass** [wandb/client#2696]
**Description**
Running hyperparameter sweep  with ~7 agents across ~5 machines (I am simply executing the same function `python my_sweep.py` each time to start up a new agent - is this the correct way to do this?). Using the wandb Pytorch lightning callback, I am logging ~100 scalars (no images, audio, etc) every 2-10 seconds for each machine run (could be ~3 runs on a given machine).

Most of my machines print: `wandb: Network error (HTTPError), entering retry loop.` every time I run my validation step (every 15 epochs), which is where most of my logging is happening.

I also often get:
```
429 response executing GraphQL.
{"error":"rate limit exceeded"}

Retry attempt failed:
Traceback (most recent call last):
  File "/home/jovyan/conda/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 138, in execute
    six.reraise(*sys.exc_info())
  File "/home/jovyan/conda/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/jovyan/conda/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 132, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/jovyan/conda/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.wandb.ai/graphql
```

When I attempt to view my runs on W&B's UI, I often get a blank screen with 'rate limit exceeded' in the middle of the page:
![Screen Shot 2021-09-23 at 10 39 18 AM](https://user-images.githubusercontent.com/9613809/134528144-cefa7861-f026-4635-bc94-d6f1fdf57089.png)
 and I often to refresh it many times to get it to display things. 

Also, when working with data on the UI, it often cuts out and displays this error message 
![Screen Shot 2021-09-23 at 10 33 27 AM](https://user-images.githubusercontent.com/9613809/134527152-700227d3-cffb-4acc-a475-5e3884547278.png)

Some of these problems seem to go away when I reduce the number of agents to 1 or 2, but seem to stile present at 3.

Is this expected behavior? I thought I was able to run ~20 agents simultaneously, especially if I am not logging anything big like images. Or maybe I am not invoking agents correctly?

**Wandb features**
PyTorch Lightning integration, random hp sweep

**Environment**
- OS: Ubuntu on AWS
- Environment: AWS g4dn.12xlarge instance (and others instances as well)
- Python Version: 3.7

**Comment by anmolmann** [comment]
Hi @maxwass , sorry for your performance issues. This is an area we really care about and we recently rolled out a new fix for such issues. Answers to some of the questions below would be very helpful for us to debug what's happening.
Firstly, I see that you're only logging scalars, in this case, would I be correctly assuming that your runs might be shorter? 
But still there might be a moderate amount of data to sync. So, Each run finishing can cost us significant resources to handle these queries. Hence, it would be really useful to know this info.

Secondly, could you please also share what you are trying to sweep over (are you using random/grid/ or bayes)?

**Comment by maxwass** [comment]
Yes, my runs are not super long (anywhere from a few minutes for pruned runs, or 1-2 hours for successful runs. Not more than a few hundred runs in total thus far though.

I have only tried random. I would like to do a grid/bayes search for some things as well, but I have not been able to get an answer on the forum/here on how to properly spawn multiple agents for a hp sweep (can I simply execute the same exact program - i.e. same project name, same train func, etc. And can I change the search space in the sweep if I find a tighter range on learning rate for example?). Thus I am not confident that the sampling in Bayes will be correct, or if the grid search will be complete.

Perhaps the most important issue is the UI. I need to be able to analyze the results without the site crashing every 2-3 minutes.

**Comment by anmolmann** [comment]
Hi @maxwass , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
