### ISSUE TITLE
Roll back from local to cloud

### ISSUE THREAD

**Issue by chyphen7** [wandb/client#2697]
I had wandb working on cloud.  Then I switched to local, and got "Retry attempt failed:" error.  I tried to switch back from local to cloud, but it seems that my system got stuck at wandb/local model.  Trying to "docker stop wandb/local", and ran the code again.  I am still getting the error:

TensorBoard: Start with 'tensorboard --logdir yolov5', view at http://localhost:6006/
wandb: Network error (ConnectionError), entering retry loop.

How do I switch the model to cloud to view training metrics at "wandb.ai/home".  

Thanks,
C. Chien

**Comment by chyphen7** [comment]
Ok.  The problem seems to have been resolved by setting 
WANDB_BASE_URL="https://api.wandb.ai"

**Comment by vanpelt** [comment]
Yep!  @chyphen7 you can also run `wandb login --cloud` to configure the whole machine to use https://api.wandb.ai.  If you then want to switch back to your local instance you would run `wandb login --host=http://localhost:6006`.

**Comment by chyphen7** [comment]
Hi, Chris:
Thanks for useful tips.
