### ISSUE TITLE
[Q] Python API runs, filter by tags

### ISSUE THREAD

**Issue by abaisero** [wandb/client#2699]
Hello,

I'm using the python API to download the data associated with my runs (using `wandb.Api().runs(...)`, so that I can make my own custom plots.  The examples I've found have covered how to filter based on config values, but I found nothing explaining how to filter based on tag values (or if it is even possible), like it is possible in the dashboard UI.  For the time being, I will proceed by downloading all the data associated with all the tags, and applying a filter locally, but that seems like a wasteful usage of bandwidth, both mine and wandb's.

Is there currently a way to apply a filter based on tag values?  If there is not, I will reopen this as a feature request.

Thank you!

**Comment by vanpelt** [comment]
`runs = api.runs("username/project", filters={"tags": {"$in": ["best"]}})`

**Comment by abaisero** [comment]
Seems like I was just not familiar enough with the MongoDB query language;  thank you!

**Comment by vanpelt** [comment]
You bet!  Yeah, we can do a better job documenting examples and have plans to make a more intuitive python helper to construct filters.

**Comment by alexcoca** [comment]
That would be much appreciated

**Comment by BurgerAndreas** [comment]
For future reference: 
https://www.mongodb.com/docs/manual/reference/operator/query-comparison/
