### ISSUE TITLE
Don't always auto-create wandb/

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#27]
Currently for example if you run "wandb --help", we'll create a wandb directory, wherever you happen to be.

We need to think about the correct behavior here.

**Comment by vanpelt** [comment]
Maybe just do it on import?

**Comment by shawnlewis** [comment]
Yeah, or even later maybe.

**Comment by shawnlewis** [comment]
New behavior is: we only create it when the user does "wandb init", in cases where it's not there we log to ./wandb-debug.log.
