### ISSUE TITLE
[Q] Trying to get GPU utilization etc with `wandb.Api()`

### ISSUE THREAD

**Issue by harpone** [wandb/client#2712]
Looking at `run.history()` I can only see the logs for things that I've explicitly logged... is there a way to get also the GPU utilization and other system metrics with the wandb API?

**Comment by armanhar** [comment]
Hey Heikki, you can download the system metrics like this:
`import wandb
api = wandb.Api()

run = api.run("<entity>/<project>/<run_id>")
system_metrics = run.history(stream="events")`

**Comment by harpone** [comment]
Oh yeah that works great, thanks!! I guess I missed the "events" kwarg somehow. Problem solved, thanks @armanhar!
