### ISSUE TITLE
[Feature] List uploaded artifacts (models) based on the metadata

### ISSUE THREAD

**Issue by alvarobartt** [wandb/client#2713]
**Describe the solution you'd like**

Like in e.g. MLFlow, it'd be cool if `wandb` allowed to list all the artifacts in the current project ("experiment") so as to download the best one based on e.g. the eval_accuracy stored as metadata of that run. This would imply a much cleaner and automated MVC (Model Version Control).

I think this could be a nice feature for `wandb` also to somehow "compete" against solutions like MLFlow, as this is one of the few things that I see missing to actually use `wandb` during the whole ML lifecycle.

Anyway, keep on the great work you're all doing! 🎉

**Comment by vanpelt** [comment]
Hey @alvarobartt we can definitely improve this interface, but this is something you can do today:

```
api = wandb.Api()
runs = run = api.runs("USERNAME_OR_TEAM/PROJECTS", filters={"created_at": {"$gt": '2020-12-07T00:20:40'}}, order="-summary_metrics.eval_accuracy")[0]
best_model = [a for a in runs[0].logged_artifacts() if model.type == "model"][0]
model_file = best_model.download()
```

**Comment by vanpelt** [comment]
Here are some more examples: https://docs.wandb.ai/guides/track/public-api-guide

**Comment by alvarobartt** [comment]
WOW, cool! Thanks a lot @vanpelt I'll check that, but at least there's a workaround!

Anyway, I think that an easier way to manage the artifacts would be a HUGE improvement :tada:
