### ISSUE TITLE
[Q] What is gorilla?

### ISSUE THREAD

**Issue by stroypet** [wandb/client#2714]
Sorry, I'm new to wandb development. What are all of the env vars related to "GORILLA_*" for? I've never heard of gorilla, can't find what it is referencing.

Thanks.

**Comment by cvphelps** [comment]
Hi Stanley, you can ignore those environment variables. Those are internal use for our backend.

**Comment by cvphelps** [comment]
May I ask @stroypet where were you seeing these env vars?

**Comment by cvphelps** [comment]
Here's the list of user-facing environment variables: https://docs.wandb.ai/guides/track/advanced/environment-variables

**Comment by stroypet** [comment]
Ah I see, okay. Thanks for the list. I was testing out the dockerized version for a potential use case, ended up poking around inside the docker image and got curious.
