### ISSUE TITLE
[Q] extend teminal logging characters

### ISSUE THREAD

**Issue by jihwanp** [wandb/client#2716]
HI I have a question about terminal logging.

I log terminal values on wandb, but the following message appears and the latter part is not written.

**(line truncated to 1000 characters)**

Where can I modified the maximum character length?

**Comment by vanpelt** [comment]
Hey @jihwanp we have a limit for max line length but it's much larger than 1000 characters.  Can you share the exact output your seeing in your terminal?  Also, the version of the wandb library would be helpful.  I searched our code base for the message "line truncated" and couldn't find any instances of it.

**Comment by sydholl** [comment]
This issue has gone stale and we are now closing it. Please comment to reopen.
