### ISSUE TITLE
[App]  The WandB backend shutdown running a sweep in google colab

### ISSUE THREAD

**Issue by Rami-Ismael** [wandb/client#2720]
**Describe the bug**

** Wandb Feature**
- wandb.init()

**To Reproduce**
1. There is the notebook
2. Run all celss
3. It crashed after the first sweep run

**Expected behavior**
Run all 5 sweep

**Screenshots**
![Screenshot from 2021-10-03 13-23-56](https://user-images.githubusercontent.com/39520903/135766651-11d14260-d02d-478c-a4b2-3186be3271b0.png)

**Operating System**
 - OS: google  colab
 - brave browser and firfox
 - Version python3.7

**Additional context**
Waiting for W&B process to finish, PID 963... (failed 1). Press ctrl-c to abort syncing.

**Comment by aidanjdonohue** [comment]
Hi @Rami-Ismael, could you post the error log files so I can see exactly what's going on? Alternatively you can email them to support@wandb.com

**Comment by aidanjdonohue** [comment]
@Rami-Ismael just following up on this thread

**Comment by JayThibs** [comment]
@Rami-Ismael Which version wandb are you using? You may want to upgrade to +0.12.3.

**Comment by Rami-Ismael** [comment]
1 .First, the weight and bias version is 0.12.6
2. How do I post the error logs.

**Comment by JayThibs** [comment]
@Rami-Ismael 0.12.6 wasn't out when you posted this, did you try to rerun with the new version?

If so, you can check how I run a hyperparameter sweep in my notebook here: https://github.com/JayThibs/map-floodwater-satellite-imagery/blob/main/notebooks/jacques_drivendata_map_floodwater_benchmark_tutorial.ipynb

Colab version: https://colab.research.google.com/drive/17K-gXacwxdgW6PAt5cpCpGi-dplg2IrH?usp=sharing

**Comment by Rami-Ismael** [comment]
1. I did rerun the program. I got the same result. 
2. I will look through your notebook to run hyperparamter sweep.

**Comment by Rami-Ismael** [comment]
@JayThibs  Is there a reason why you save the hyperparemters in a yaml file. instead , a dictionary

**Comment by JayThibs** [comment]
@Rami-Ismael Yes, it's because I'm also running that code outside of a notebook and it's cleaner to use yaml when I use scripts (though you can still use a dictionary if you want). If you're only going to use a notebook for your sweep, either one is fine.

**Comment by aidanjdonohue** [comment]
Closing this ticket out but if you have further questions comment back or write in to support.
