### ISSUE TITLE
[CLI] Some images logged via `wand.Image` are completely balck

### ISSUE THREAD

**Issue by shaibagon** [wandb/client#2722]
**Description**
When logging images using `wandb.log({'img':wandb.Image(...)})` some of the logged images are black (all zeros). Some images are logged correctly, while others are simply black.

**Wandb features**
The problematic lines are:
`wandb.log` combined with `wandb.Image`. I log a batch of images (inputs as well as predicted/generated output images):
`wandb.log({'train/input': [wandb.Image(_pred_to_img(x[b, ...])) for b in range(x.shape[0])]})`

Converting an input image to RGB is using this simple code:
```
def _pred_to_img(pred):
    # to numpy
    nimg = pred.cpu().numpy().transpose(1, 2, 0)
    # denormalize
    nimg = nimg * np.array([0.229, 0.224, 0.225]).reshape((1, 1, 3))
    nimg = nimg + np.array([0.485, 0.456, 0.406]).reshape((1, 1, 3))
    return nimg
```

**How to reproduce**
Since the error is not consistent - it happens at random I do not have a concise way to reproduce.

**Environment**
- OS: Linux
- Environment: GPU server (DGX 1 with 8 V100)
- Python Version: 3.6
- Pytorch 1.9.0
- wandb 0.11.2

**Comment by shaibagon** [comment]
@vanpelt thank you for your reply.
I'll make sure my images are **strictly** in the right range, and see if this resolves the issue.

I am working with float-type images that should be in the range of [0, 1]. It may happen, occasionally, that the values slightly exceed these limits, e.g., when using bicubic interpolation. Wouldn't it be better if you were a little bit more "relax" when deciding if an image is in the range of [0, 255]?

**Comment by shaibagon** [comment]
@aidanjdonohue if this already became a "feature request", or if it is already implemented -- then this issue can be closed.

Thanks.

**Comment by aidanjdonohue** [comment]
Hi @shaibagon, so after discussing with the team we're not going to implement this so as not to cause unexpected behaviour with other users.
