### ISSUE TITLE
[Q] How to remove wandb account information from a machine

### ISSUE THREAD

**Issue by mineshmathew** [wandb/client#2745]
I earlier  logged into wandb from a Unix machine in my lab . Upon  `wandb login` it signs into my account. I want to logout/remove my account information from the machine. How do I do it

**Comment by rohitgr7** [comment]
hey!

why not provide a simple cli call for it?
something like `wandb logout` should be enough?

**Comment by derpda** [comment]
Incredible that there is no logout function :O

**Comment by ronghanghu** [comment]
> why not provide a simple cli call for it? something like `wandb logout` should be enough?

+1 on this: it would be great to have a `wandb logout` function

**Comment by ihalage** [comment]
If you want to disable wandb, `wandb disable` would do. Try `wandb --help` for more options.

**Comment by elaaaf** [comment]
What solved the problem for me is that I removed everything from the /root/.netrc file

**Comment by gxxu-ml** [comment]
you can reset the base_url so that it will prompt you to relogin:
and remove API_KEY:

```
export WANDB_BASE_URL="https://api.wandb.ai"

export WANDB_API_KEY=None
```
