### ISSUE TITLE
[Q] How to Log multiple times per second?

### ISSUE THREAD

**Issue by Ademord** [wandb/client#2750]
Hello
I am using `wandb.log({k: v})` multiple times per second -> I have ran into the warning you give in your docs:
> wandb.log is not intended to be called more than a few times per second. If you want to log more frequently than that it's better to aggregate the data on the client side or you may get degraded performance.

What can I do to upload aggregated logs to wandb? I can aggregate them in a `list of dicts`  on my side, but 
1.  how will this keep the order of "publishment"? running `wandb.log` keeps the temporal order of when the logs were published 
2.  I can't find anywhere in the docs how to push aggregated data and 
3.  I prefer using wandb to tensorboard, so i hope there is a way

**Comment by Ademord** [comment]
@vanpelt : I tried what you mentioned with `commit=False` and interestingly my `wand.finish` outputs
```bash
wandb: Waiting for W&B process to finish, PID 11439... (success).
wandb:                                                                                
wandb: Run history:
wandb:            Drone[test]/Leaf Nodes Visited ▁
wandb:               Drone[test]/Lingering Count ▁
wandb:             Drone[test]/Lingering Penalty ▁
wandb:     Drone[test]/LingeringPenaltyStrength  ▁
wandb:                    Drone[test]/Look Error ▁
wandb:                Drone[test]/Moving Forward ▁
wandb:              Drone[test]/Objects Detected ▁
wandb:       Drone[test]/Octree Discovery Reward ▁
wandb:        Drone[test]/Octree New Nodes Count ▁
wandb:    Drone[test]/RationalizedShannonEntropy ▁
wandb:             Drone[test]/Scan Points Found ▁
wandb:                   Drone[test]/Speed Error ▁
wandb:   Drone[test]/SumOfElementsInSemanticMap  ▁
wandb:        Drone[test]/Total Objects Detected ▁
wandb:         Drone[test]/Total Objects Scanned ▁
wandb:          Drone[test]/Total Voxels Scanned ▁
wandb:                Drone[test]/Voxels Scanned ▁
wandb:                    Drone[test]/Walk Error ▁
wandb:                               global_step ▁
wandb:                                  time/fps ▁
wandb: 
wandb: Run summary:
wandb:            Drone[test]/Leaf Nodes Visited 0.0
wandb:               Drone[test]/Lingering Count 0.0
wandb:             Drone[test]/Lingering Penalty -0.0
wandb:     Drone[test]/LingeringPenaltyStrength  1.0
wandb:                    Drone[test]/Look Error 0.0
wandb:                Drone[test]/Moving Forward 0.0
wandb:              Drone[test]/Objects Detected 0.0
wandb:       Drone[test]/Octree Discovery Reward 0.0
wandb:        Drone[test]/Octree New Nodes Count 0.0
wandb:    Drone[test]/RationalizedShannonEntropy 0.0
wandb:             Drone[test]/Scan Points Found 0.0
wandb:                   Drone[test]/Speed Error -4.69411
wandb:   Drone[test]/SumOfElementsInSemanticMap  0.0
wandb:        Drone[test]/Total Objects Detected 0.0
wandb:         Drone[test]/Total Objects Scanned 0.0
wandb:          Drone[test]/Total Voxels Scanned 0.0
wandb:                Drone[test]/Voxels Scanned 0.0
wandb:                    Drone[test]/Walk Error 0.0
wandb:                               global_step 2048
wandb:                                  time/fps 61.0
```
and my plots look like this
![image](https://user-images.githubusercontent.com/4501464/137641261-1a4cfeaf-d610-4739-83bc-7afcd3949a32.png)


instead of like this
![image](https://user-images.githubusercontent.com/4501464/137641286-b34e1402-11f6-4aa7-94c1-28fa4326d224.png)

i assume `wandb.log` is not aggregating in the background things like you said it would. it is just overwriting with the latest value received for the given dictionary, instead of creating a time series? maybe you can correct me.

otherwise, can you show me exactly how to aggregate my dictionaries into a table that can then be pushed at the end of training?

**Comment by sydholl** [comment]
@Ademord We are going to close this issue, but please let us know if we can help in any other way.
