### ISSUE TITLE
[Q]  Which operations communicate with server?

### ISSUE THREAD

**Issue by adamoyoung** [wandb/client#2758]
I am trying to reduce the frequency with which I get "rate limit exceeded" errors on hyperparameter sweeps. I am wondering which operations cause a communication with the wandb server. Am I right in assuming that it is only the functions that explicitly involve communication, like: `wandb.log`, `wandb.init`, `wandb.save`, and `wandb.restore`, or is it possible that there is some background communication that I am not aware of?

**Comment by armanhar** [comment]
Hey Adam, I'll need double-check with the team on this. What I'd recommend as a workaround is to run your experiments offline and sync them with wandb sync
