### ISSUE TITLE
[Q] Is there anyway to solve the issue : Error while calling W&B API: Invalid artifact name without re-running the experiment again?

### ISSUE THREAD

**Issue by yorard123** [wandb/client#2760]
Hi, When I am trying to sync an experiment that I run it previously in offline mode I found that I am having issues to do it. The error that I get is this one:

`wandb: ERROR Error while calling W&B API: invalid artifact name run-test_64_128_test_64_aggr_max_twobranch_512_predv1_b1global_none_b2global_none_01-Test_new_testbewnethodresultswiththresh04, must be 128 characters or less (<Response [400]>)`

In addition,when I try to check the project associated to this experiment,  I get the following error:

![Screenshot_20211013_064113](https://user-images.githubusercontent.com/48563127/137068435-3d7a7896-d9fa-4212-9aab-63b98137b42f.png)

Is there anyway that I can change the name of the artifact in order to recover these results without having to re-run the experiment again?

Thanks,

**Comment by anmolmann** [comment]
Hi @yorard123, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
