### ISSUE TITLE
[CLI] Doesnt log tensorboard with wandb

### ISSUE THREAD

**Issue by Programmer-RD-AI** [wandb/client#2772]
**Description**
Doesn't log tensorboard with wandb,
[00.zip](https://github.com/wandb/client/files/7350884/00.zip)
The above is the link for the jupyter lab notebook.

I have checked the issue a few times but it seems not to log the logs to tensorboard.

And it doesn't when I use
wandb.init(project=PROJECT_NAME,name=NAME,sync_tensorboard=True)
it doesn't sync.

**Wandb features**
What lines of wandb code are you using? This could be wandb.init(), wandb.log(), or features like the Keras callback, the Hugging Face integration, or PyTorch Lightning integration, for example.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
2. Describe what we have to do in order to trigger the issue
3. Add a zip file with the run folder 

**Environment**
- OS [Ubuntu:20.04.3 LTS (Focal Fossa)"
- Environment: [Local Conda]
- Python Version: [eg. 3.8.11]

Can someone pls help with this?

With best regards

**Comment by Programmer-RD-AI** [comment]
hi @vanpelt 

I checked and I found that detectron2 logs the metrics to a output/metrics.json file

so I load the json and log that metrics.json

I don't think that this is a fix for the problem but my detectron2 problem is resolved.

I will keep this issue open so if anyone wants to go through this.

And also my wandb version is '0.10.0'

WIth best regards,
Ranuga

**Comment by sydholl** [comment]
@Programmer-RD-AI We are going to close this issue but please comment if you would like to reopen.
