### ISSUE TITLE
[App] `wandb.log` and `run.log_artifact(...)` not showing in browser 

### ISSUE THREAD

**Issue by Wilann** [wandb/client#2778]
**Describe the bug**
When using `wandb.log` and `run.log_artifact(...`), nothing is being logged in the browser. 

**To Reproduce**
```
wandb.init()
wandb.config = {lr: lr}
for i in range(5):
    wandb.log({'i': i})
```

```
run = wandb.init()
artifact = wandb.Artifact('name', type='dataset')
artifact.add_dir('./logs')
run.log_artifact(artifact)
```

**Expected behavior**
Expecting UI to display chart of `i` and `./logs`

**Screenshots**
![Screenshot from 2021-10-16 07-41-38](https://user-images.githubusercontent.com/40744757/137585953-31783f13-c72d-458b-98f5-8d1a80373b63.png)
![Screenshot from 2021-10-16 07-59-49](https://user-images.githubusercontent.com/40744757/137586465-710590a7-374d-488f-91e3-4227a5edcf9e.png)

**Operating System**
 - OS: Pop!_OS 20.04 LTS
 - Browser: Chrome
 - Version 94.0.4606.61 (Official Build) (64-bit)

**Additional context**
It seems that after waiting a few minutes, I get this output message:
```
wandb: Waiting for W&B process to finish, PID 36549... (success).
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
ERROR:root:dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/wilan/CALF/3lqirfgr/file_stream
NoneType: None
```

**Comment by Wilann** [comment]
For some reason, after leaving the system open overnight, it works now. Not sure what the issue was. 
Can anyone shed some light on why this was the case?

**Comment by Wilann** [comment]
Currently the last outputs in the terminal are:
```
wandb: Adding directory to artifact (./Dataset/BWF TV)... Done. 470.4s

wandb: Waiting for W&B process to finish, PID 93679... (success).
```

I assume this means its still uploading, despite saying "success"?

There's no artifact yet in the UI, but at least the folder is there:
![Screenshot from 2021-10-18 18-19-04](https://user-images.githubusercontent.com/40744757/137814405-2c3746d4-d93c-4c13-be2a-b58816829be6.png)

**Comment by Wilann** [comment]
Hey @vanpelt, looks great. Everything got uploaded. As a suggestion, maybe print the percentage uploaded during the upload so that there's an ETA of sorts?

**Comment by EvanBrownVTM** [comment]
Same issue hanging on
