### ISSUE TITLE
[CLI] 

### ISSUE THREAD

**Issue by jambran** [wandb/client#2779]
**Description**
It seems I'm getting an issue when trying to run distributed training on Sagemaker. 

I've taken a look at the [documentation](https://docs.wandb.ai/guides/track/advanced/distributed-training) regarding distributed training, and I'm trying to get the second approach to work, `wandb.init()` on all processes.

The training job fails with the exception
```
[1,3]<stderr>:  File "train.py", line 75, in <module>
[1,3]<stderr>:    group="DDP",
[1,3]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 846, in init
[1,3]<stderr>:    six.raise_from(Exception("problem"), error_seen)
[1,3]<stderr>:  File "<string>", line 3, in raise_from
[1,3]<stderr>:Exception: problem
```

I've created a repository to recreate the issue: https://github.com/jambran/wandb_sagemaker_bug_report

Thank you very much in advance. I'd like to continue using `wandb` while running distributed training!

**Wandb features**
`wandb.init()` with `HuggingfaceEstimator` from sagemaker

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
    https://github.com/jambran/wandb_sagemaker_bug_report/blob/main/train_sagemaker.py
2. Describe what we have to do in order to trigger the issue
    Clone the repository, and run `train_sagemaker.py`

**Environment**
- OS: ![image](https://user-images.githubusercontent.com/20362115/137593478-7f60ecd4-a08b-4b74-bd61-3a47c0cdbb53.png)
- Environment: [AWS Sagemaker]
- Python Version: [3.6]

**Comment by purplexed** [comment]
Hey @vanpelt , could you please share some details/links on the newly introduced functionality you mentioned above?
Thanks!

**Comment by vanpelt** [comment]
Hey @purplexed it's very early with our multiprocessing support, but you can see an example specific to pytorch-lightning and DDP [here](https://github.com/wandb/client/blob/master/functional_tests/lightning/train-ddp.py#L75).  With the latest release of wandb (0.12.5), you can now opt-in to our experimental multi process support by calling the following before calling `wandb.init`:

```python
wandb.require(experiment="service")
```

Note, if you're using pytorch-lightning you need to install it from our custom fork for multiprocessing to work correctly:

```shell
pip install --force git+https://github.com/wandb/pytorch-lightning.git@wandb-service-attach
```

We'll be slowly rolling this out more broadly over the coming weeks and provide more documentation.  We're hoping that the new logic makes multiprocessing just work for most cases, but there are some additional methods that may need to be called in certain circumstances.  If you continue to see issues with multiprocessing while using this functionality please file a new issue in our repo and we'll see if we can provide more guidance.
