### ISSUE TITLE
Can't find git commit

### ISSUE THREAD

**Issue by rmst** [wandb/client#278]
* Weights and Biases version: '0.6.29'
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

Wandb doesn't seem to recognize my git repo (anymore). When clicking on "View on Github" I get: "[...] we couldn't find a git commit for this particular run."

### What I Did
I should mention that my repo isn't initialized with wandb. Instead I do

``` wandb.init(dir=mkdtemp(), entity=entity, project=project, config=config) ```

**Comment by vanpelt** [comment]
When you run the script we check to see if it's run inside of a git repository and store the commit.  Is the script definitely being run from within a git repo?

**Comment by rmst** [comment]
Maybe you could add a `git_path` argument to the init function? Alternatively, to always get the dir of the __main__ module we could do

```
import __main__
run_dir = os.path.dirname(getattr(__main__, '__file__', ''))
```

That would give
- `.../agents/td3` for `python -m agents.td3`
- `.../agents/td3` for `python -m agents.td3.vis` (executing vis.py)
- `.../agents/td3` for `python ~/agents/agents/td3/vis.py`
- `''` in the repl

**Comment by vanpelt** [comment]
Can you try executing the python command from inside the git repo?  We could add checking the working directory of the file wandb.init was called in.

**Comment by rmst** [comment]
That works, thank you! Do you think it would still be possible to add a git_path option to wandb.init? That would allow for custom logic such as above.

**Comment by rmst** [comment]
Oh, actually I just realized that links in config strings are automatically parsed. So I can just make my own github link. That's an even better solution for me :)
