### ISSUE TITLE
History quietly accepts a single string and then behaves weirdly

### ISSUE THREAD

**Issue by lukas** [wandb/client#28]
* Weights and Biases version: 0.4.19
* Python version: 2.7
* Operating System: os x

### Description
If I call:
history = wandb.History('loss')

I get a csv that looks like
l,o,s,s
,,,
,,,
,,,
,,,
,,,
,,,
,,,

I would prefer it to fail and ask me to initialize with an array.

**Comment by shawnlewis** [comment]
The user doesn't initialize wandb.History anymore so it's not an issue. But I did add some other type checking to history.add and summary.update
