### ISSUE TITLE
[Q] wandb.save(file_path) creates the whole recursive path 

### ISSUE THREAD

**Issue by jingxixu** [wandb/client#2809]
I am calling `wandb.save(file_path)` to save a log file. However, when I check the saved files in the cloud GUI, I noticed that this file is saved using the exact `file_path`. For example, if `file_path` is `dir1/dir2/file.txt`, then `dir1` and `dir2` are created accordingly in Files in the GUI even though I just want to save `file.txt`. Any suggestions?

**Comment by vanpelt** [comment]
Hey @jingxixu you can use the `base_path` argument, i.e. `wandb.save("dir1/dir2/file.txt", base_path="dir1/dir2")` should save a file named `file.txt` in the gui.
