### ISSUE TITLE
[Q] HP sweep (grid search) with offline logging on an HPC

### ISSUE THREAD

**Issue by DavidSlayback** [wandb/client#2810]
I'm a PhD student studying RL. I've really loved using wandb, and I particularly find the sweep API to be a convenient way to setup runs. I've run into a problem recently when I tried to scale up.

I'm logging a fair amount of data on many agent processes, but I'm using tensorboard and the "offline" mode on an HPC cluster. Given that I'm using grid search with no early stopping, I'm thinking that my agents should only need to communicate with wandb to get new parameter sets. I am using a lot of agents (>800), but I've introduced random jitter to their start times as well to try not to overwhelm the rate limit. Yet I still keep hiting 429 GraphQL rate limit errors.

If I'm just trying to use grid search for a bunch of agents logging offline, what would best practices be? Starting a local controller process didn't seem to help matters. The HPC in question is also SLURM (no docker support), so I'd have some difficulty setting up a wandb server instance even if I had access.

**Comment by wizofe** [comment]
@DavidSlayback Can you please give some info on how you solved this? Thanks

**Comment by DavidSlayback** [comment]
@wizofe Ultimately I had to stop using the agent framework. I would pregenerate a text file of all runs in the sweep (e.g., `python script.py --arg1 1 --arg2 2`), and each process would retrieve the next script in the queue (using locks). At the end of my training scripts, I synced the run and then removed it (see below).

```python
    run = wandb.init(
        project=args.wandb_project_name,
        entity=args.wandb_entity,
        sync_tensorboard=False,
        config=vars(args),
        name=run_name,
        monitor_gym=True,
        save_code=True,
        mode='offline',
        id=generate_id(16),
        group=f'MultistoryFR_{args.grid_z}_{args.obs_type}'
    )
    rdir = os.path.split(run.dir)[0]
    .
    # insert training code here
    .
    if rdir:
        wandb.finish()
        print(f'Syncing {rdir}...')
        import subprocess

        subprocess.run(['wandb', 'sync', rdir])  # Sync afterward if we're running offline
        print(f'Removing {rdir}...')
        import shutil

        shutil.rmtree(rdir)  # Remove directory after sync
```
