### ISSUE TITLE
[CLI] Runs filters don't work with config names that contain periods

### ISSUE THREAD

**Issue by rjbruin** [wandb/client#2819]
**Description**
When the logged config keys contain a period (e.g. `config.model.type`), any filters in `wandb.api.runs(filters={...})` seem to be ignored.

**Wandb features**
I am using `wandb.Api().runs()` only.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
2. Describe what we have to do in order to trigger the issue
3. Add a zip file with the run folder 

Reproducible script, assuming it queries a workspace with at least one run that has a config key named `example.key`:

```python
import wandb
api = wandb.Api()
runs = api.runs(path="<entity>/<project>", filters={"config.example.key": "test_value"})
print(len(runs))

"""
Output:
0
"""
```

**Environment**
- Client version: 0.12.5 (latest version on Conda Forge)
- OS: Ubuntu 20.04.3 LTS
- Environment: Local Anaconda installation on linux-64 platform
- Python Version: 3.9.7

**Comment by rjbruin** [comment]
As a further clarification: what *does* work is to filter by a configuration key with a single period in it, i.e. `'config.key': 'value'`.

**Comment by aidanjdonohue** [comment]
Ok thanks for the context. I'll look into this further and let you know what's going on here.

**Comment by aidanjdonohue** [comment]
Hi @rjbruin what exactly is failing for you? `rjbruin/rnn/pkrqqgnr` has `model.type = CIFARReResNetSharedBN` not `CIFARReResNet32SharedBN ` so that could be the issue.

**Comment by rjbruin** [comment]
Sorry for the confusion, but I've updated the `model.type` values in the meantime. If you use `model.type = CIFARReResNetSharedBN` it should work, but it doesn't. I've just confirmed that myself.

**Comment by aidanjdonohue** [comment]
Hi @rjbruin can you try the original query on the updated version of the client: `runs = api.runs(path="rjbruin/rnn", filters={"config.model.type": "CIFARReResNet32SharedBN"})`

**Comment by rjbruin** [comment]
Sure! I tried this line (since the one you suggested doesn't match any models anymore in the interface):
`runs = api.runs(path="rjbruin/rnn", filters={"config.model.type": "CIFARReResNetWrongStride"})`

Still no luck, no runs in `runs`.

**Comment by anmolmann** [comment]
@rjbruin , could you please try: runs = api.runs(path="rjbruin/rnn", filters={"config.model.type.value": "CIFARReResNetWrongStride"}), I hope this'll work.
So, if we log config keys like this: 
```
config = {
   'example_1': {'key_1': 'value_1'},
   'model.type': 'CIFAR'
}
```
and then try to filter out runs via:
`runs = api.runs(path="entity/project", filters={"config.example_1.key_1": "value_1"})`: this would work, however, if we use a filter like this one: `filters={"config.model.type": "CIFAR"}` won't because of the difference in the way these keys are logged. `example_1` is a nested key but `model` isn't. If you click on the `Raw` button on the runs overview page - you'll see that the config also depicts the same.
```
"example_1": {
        "desc": null,
         "value": {
              "key_1": "value_1"
          }
},
"model.type": {
        "desc": null,
        "value": "CIFAR"
}
```

**Comment by rjbruin** [comment]
That does indeed work! Thanks so much! :)
