### ISSUE TITLE
ResourceWarning when call wandb.log

### ISSUE THREAD

**Issue by Boyden** [wandb/client#2837]
https://github.com/wandb/client/blob/6530fa5e839e3eb1e4f151c133801654a5db6af6/wandb/sdk/data_types.py#L1249
When I call the wandb.log function in my code as follows:
`wandb.log({tag: wandb.Image(image, masks=segms_dict)}, commit=False)`
It will raise the ResourceWarning in the wandb/sdk/data_types.py#1249 which execute the code
`codecs.open(tmp_path, "w", encoding="utf-8")` without close the tmp file fp. The warning is as follows:
`wandb/sdk/data_types.py:1249: ResourceWarning: unclosed file <_io.BufferedWriter name='/tmp/tmp3xmugx8hwandb-media/233lh50m.boxes2D.json'>`
Was it a bug or the wrong use of wandb.log

**Comment by aidanjdonohue** [comment]
Got it, thanks for reporting. We're looking into this further.

**Comment by aidanjdonohue** [comment]
Hi @Boyden, so sorry for the delay. That's definitely a bug with us. I'll ping this thread back when we fix it.

**Comment by sydholl** [comment]
Hi @Boyden, so sorry for the delay. That's definitely a bug with us. I'll ping this thread back when we fix it.

**Comment by aidanjdonohue** [comment]
@Boyden , we fixed this in our most recent client release. Thanks for reporting 👍
