### ISSUE TITLE
[Q] Is it possible to query for the currently active run?

### ISSUE THREAD

**Issue by phrasenmaeher** [wandb/client#2851]
In `script1.py`, I create a fresh training run, which saves some data to disk, and the **path depends on the W&B id**. For example, it might save to `/workspace/runs/89kkes8o`.

I'd like to get this data automatically to work with in another scripts. Rather than manually extracting the ID or the path, I'd like to query W&B for the ID of the latest/current run.

Is this possible? And, how would this behave if I'd start more than one training run; which ID would be queried then?
Otherwise, I am open for any other suggestions on how to handle this setup. Thanks!

**Comment by ramit-wandb** [comment]
Hi @phrasenmaeher! Thanks for your question.

Yes, the `wandb.api` class allows for a way to access your runs. I have written a little test script for you as an example:

```
import wandb

api = wandb.Api()
runs = api.runs(path='<your_entity_name>/<your_project_name>')

latest_run = runs[0]
```

By default, the `api.runs` method will return all your runs in order of their time created, with the latest run being the first. You can change this by specifying an `order` parameter to the `api.runs` call, which is set by default to `"-created-at"`.

Optionally, you can also filter your runs by providing a `filter` argument.

You can read more about `Run` objects [here](https://docs.wandb.ai/ref/python/run) and about the `api.runs` method [here](https://docs.wandb.ai/ref/python/public-api/runs).

I hope this solves your problem.

Best,
Ramit

**Comment by phrasenmaeher** [comment]
Hi @ramit-wandb , that was exactly what I was looking for! Thanks for the fast response, my issue is solved!

**Comment by alexandervlpl** [comment]
Correction: it's `"-created_at"` (underscore), not `"-created-at"` (dash). And this is the value you want to get the latest run first.
