### ISSUE TITLE
[App] wandb.plot.bar no permission to view 

### ISSUE THREAD

**Issue by arnav-gudibande** [wandb/client#2856]
**Describe the bug**
As of recently, none of the `wandb.plot.bar` plots are displaying in any of my projects

**To Reproduce**
I tried a simple test such as this
`wandb.init(...)`
`testData = [[0,5], [1,10], [2,3], [3,20]]`
`testTable = wandb.Table(data=testData, columns=['index', 'block'])`
`wandb.log({'testTable': wandb.plot.bar(testTable, 'index', 'block', title='test')})`

**Expected behavior**
A bar chart should appear. Instead, getting the message: "This chart does not exist or you don't have permission to view it."

**Screenshots**

<img width="525" alt="Screen Shot 2021-10-31 at 1 56 18 PM" src="https://user-images.githubusercontent.com/15108659/139601011-2fa2dc31-fe23-4084-9568-4e090a361722.png">

I can manually edit the plot to make it a histogram, but this is not formatted as a bar chart
<img width="1922" alt="Screen Shot 2021-10-31 at 1 57 16 PM" src="https://user-images.githubusercontent.com/15108659/139601034-061ce427-04af-4632-b6ee-ee40c05e6e8f.png">

**Operating System**
 - OS: [e.g. iOS] MacOS 12.0.1
 - Browser [e.g. chrome, safari] Safari 15.1
 - Wandb version 0.12.6

**Additional context**
I cannot view the Bar chart on this wandb report as well: https://wandb.ai/wandb/plots/reports/Custom-Bar-Charts--VmlldzoyNzExNzk
<img width="1270" alt="Screen Shot 2021-10-31 at 1 55 33 PM" src="https://user-images.githubusercontent.com/15108659/139600979-3dde3d24-2ad6-4ac4-9dbe-77f76c2dc0fe.png">

**Comment by rtaori** [comment]
+1 encountering this issue as well

**Comment by jmpark-swk** [comment]
I also encounter this issue as well. 😢

**Comment by KUASWoodyLIN** [comment]
+1

**Comment by ngocuong0105** [comment]
This issue is still ongoing, correct? I still seem to have it.

**Comment by nate-wandb** [comment]
Hi All, this should now be fixed. Please reach out and let us know if you still see this anywhere or have any issues. Thank you!
