### ISSUE TITLE
[Q] Can we sync the same run twice without getting a duplicate? 

### ISSUE THREAD

**Issue by optimass** [wandb/client#2858]
Hello,

I'm using the wandb in offline mode, and then I sync my runs from time to time during training.
Unfortunately, this creates duplicated entries in my project.
Is there a workaround for this?

Thanks

**Comment by vanpelt** [comment]
When calling `wandb sync` you can specify the `--id` argument to replace an existing run id.

**Comment by optimass** [comment]
ok thanks, that's helpful!
