### ISSUE TITLE
[CLI] Metaflow integration should forward the api key to Batch jobs

### ISSUE THREAD

**Issue by ogoid** [wandb/client#2864]
Metaflow library allows one to execute workflow steps as a AWS Batch job with custom Docker container images. But they fail with the current wandb integration as it is not forwarding the api key from the executer/original environment to these jobs.  Currently we have to manually pass the key as a custom environment variable to get it to work:

```python
import wandb
from wandb.integration.metaflow import wandb_log
from metaflow import FlowSpec, step, environment, batch

print("has api: ", wandb.api.api_key != None)

env_vars=dict(WANDB_API_KEY = wandb.api.api_key)

@wandb_log
class TestFlow(FlowSpec):

  @batch(image="ogoid/test") # python with wandb@master (257c74238f92940c20659afe490a50c643283131)
  @environment(vars=env_vars)
  @step
  def start(self):
    print("aws batch job")
    self.next(self.end)

  @step
  def end(self):
    pass

if __name__ == '__main__':
    TestFlow()
```

I think this is something the integration should do automatically. Even because there may be other important information that should be forward too.

(Another Metaflow feature to be handled is its deployments to AWS Step Functions. I suppose in this case the deployer host environment should be used.)

**Comment by aidanjdonohue** [comment]
@ogoid this seems reasonable. Let me check with some folks to see if there are any strong reasons why we wouldn't want to do this.

**Comment by aidanjdonohue** [comment]
Hi @ogoid, it looks like you actual can do this via the decorator. It's a little verbose but `@wandb_log(settings=wandb.Settings(api_key=wandb.api.api_key))` should do the trick

**Comment by ogoid** [comment]
Yeah, that's another way to do it.

But I wish `wandb_log` did it automatically.

**Comment by aidanjdonohue** [comment]
Got it. We'll take a look at this and see if there's a way to clean things up.

**Comment by andrewtruong** [comment]
Hi @ogoid , can you please try [this branch](https://github.com/wandb/client/tree/andrew/metaflow-apikey-fix) and let me know if it works for you?

**Comment by ogoid** [comment]
@andrewtruong, this works. Thanks!
