### ISSUE TITLE
[Feature] Get Access to all paths in reference artifact

### ISSUE THREAD

**Issue by BenSpex** [wandb/client#2866]
**Is your feature request related to a problem? Please describe.**
I would like to use the paths saved in a reference artifact (stored in S3 or GCP) to be used in the same way as described here: 
[https://wandb.ai/wandb/arttest/reports/Intro-to-W-B-Artifacts--VmlldzozNTAzMDM ](url)
Without the need to use the data_at.download() function. 

**Describe the solution you'd like**
Something like data_at.get_reference_paths()
Returning a list of all paths, just like displayed in the Web Interface under Files. 
Then we can use the same logic as above to perform splits, alterations etc. 
This is especially useful when working in the cloud, where downloading the data is not needed, nor advised.

**Comment by aidanjdonohue** [comment]
Hi Ben, there's currently not an equivalent argument for getting references but I definitely think that's something we can explore adding. If your artifact is only made up of references to external stores, then calling artifact.download() might be your best bet as the reference paths, not the data they point to will be downloaded and then you can access the references from there.

**Comment by anmolmann** [comment]
Hey @BenSpex , you can fetch paths out of reference artifacts via our public API using `artifact.get_path(...).ref`. This is elaborated further in [our docs](https://docs.wandb.ai/guides/artifacts/api#using-and-downloading-artifacts).

**Comment by BenSpex** [comment]
@anmolmann and @aidanjdonohue Thanks a lot
