### ISSUE TITLE
[Q] Local controller use cases

### ISSUE THREAD

**Issue by DavidSlayback** [wandb/client#2888]
I was wondering what exactly the use cases for the local controller are?

For background, I've been unsuccessfully trying to use a local controller to manage an offline sweep (grid search and no early stopping, so no dependencies between runs) on an HPC. Given the number of simultaneous processes I'm running, even though all the data logging is offline (using wandb.init(..., mode='offline')), the normal cloud-based sweeping still gets choked with 429 rate limit exceeded errors.

In the documentation, it suggests that I could use a local controller to manage this. But I found I was encountering the same issue. Digging through the code, it looks like the agents are still making the same API calls to the cloud regardless, and the controller is making its own calls as well. It appears that the controller takes over scheduling, but doesn't meaningfully reduce the burden.

Ideally, what I'm looking for is the ability to tie agents directly to the controller as fully offline agents.

**Comment by aidanjdonohue** [comment]
Hi @DavidSlayback local controllers are designed to give users the flexibility to run sweeps that wandb doesn't support natively with the full wandb UI sweep options. Truly offline controllers are something we might consider supporting in the future. If you are trying to support running massively parallel sweeps I would consider looking into self-hosting wandb with local.

**Comment by aidanjdonohue** [comment]
Hey @DavidSlayback, so in talking to the team it doesn't look like we plan on supporting "truly" offline controllers for our cloud deployment. Local is still a solid option, but if you're just trying to run a simple grid sweep and don't want to deal with the overhead of self-hosting, you might just calculate the cartesian product of your hyperparameters and divide those among your processes manually.
