### ISSUE TITLE
You need a license for this instance of W&B Local[Q]

### ISSUE THREAD

**Issue by xieyipeng** [wandb/client#2890]
* It tells me that I need a license：

`You need a license for this instance of W&B Local`

![image](https://user-images.githubusercontent.com/32957035/140598709-650b7fb2-2f65-4276-a35d-0649d9263f65.png)

![image](https://user-images.githubusercontent.com/32957035/140598692-012701a8-3928-4adf-bff9-35dc7d0bab1c.png)

* But：
![image](https://user-images.githubusercontent.com/32957035/140598699-763ad8f4-94fe-4dec-884b-163dc917a64c.png)

**Comment by cvphelps** [comment]
Hi @xieyipeng have you created a local license in the Deploy Manager previously? Could you use the license from that existing deployment?

**Comment by xieyipeng** [comment]
> Hi @xieyipeng have you created a local license in the Deploy Manager previously? Could you use the license from that existing deployment?

* I don't quite understand what you mean, But `wandb` is work. I just want to remove the red hint in the first picture...

Thank u!

**Comment by jsbroks** [comment]
Hi @xieyipeng, if you go to https://deploy.wandb.ai/. Does it show you an existing deployment? If so use that license on your instance to remove the banner.

**Comment by xieyipeng** [comment]
> Hi @xieyipeng, if you go to https://deploy.wandb.ai/. Does it show you an existing deployment? If so, please copy the license and use that to remove the banner.

* Very good, I have got the license, and it shows that it is available for 356 days：

![image](https://user-images.githubusercontent.com/32957035/141707879-18f88b21-50c9-429b-adf0-5925f81a09fa.png)

* But when I update the settings:

![image](https://user-images.githubusercontent.com/32957035/141707985-f1c05313-4397-4b4b-8c2d-a8de60aae6b0.png)

* It pops up error:

![image](https://user-images.githubusercontent.com/32957035/141707951-c88f6f6f-7450-4fad-a4f8-e9add503ba6e.png)

**Comment by cvphelps** [comment]
Thank you. The solution is to go to deploy.wandb.ai and get a free license for your installation :)

**Comment by chenshen03** [comment]
the same problem

**Comment by jordangong** [comment]
The problem still exists in the latest version 0.39.0. The personal license expired after a month of deployment. But there is no way to regenerate a license on the [deploy page](https://deploy.wandb.ai/).
