### ISSUE TITLE
[CLI] logged table not displayed in the UI

### ISSUE THREAD

**Issue by pini-kop** [wandb/client#2893]
I trying to log a dataframe, however I don't see the table inside UI charts
the dataframe value is 

[{"T0":"7979","T1":"7979","GT":"7979"},{"T0":"2894","T1":"3016","GT":"3016"},{"T0":"images/raw/a/20200621180317562533.jpg","T1":"images/raw/a/20200718210324019085.jpg","GT":"annotations/2021_08_04/20200516120303976612.jpg___fuse.png"},{"T0":"37","T1":"3","GT":"3"}]

Please suggest what should I do to visualize this dataframe

**Comment by anmolmann** [comment]
Hey @pini-kop , how did you log your Dataframe? I'm assuming you might've a script similar to the one below?

```
df_data = [{"T0":"7979","T1":"7979","GT":"7979"},
           {"T0":"2894","T1":"3016","GT":"3016"},
           {"T0":"images/raw/a/20200621180317562533.jpg",
            "T1":"images/raw/a/20200718210324019085.jpg",
            "GT":"annotations/2021_08_04/20200516120303976612.jpg___fuse.png"},
           {"T0":"37","T1":"3","GT":"3"}]
data = pd.DataFrame(df_data)

# 1. initialize a run
wandb.init(...)

# 2. log wandb table
run.log({"debug_table": wandb.Table(data=data, columns=data.columns.to_list())})

# 3. finish the run
wandb.run.finish()
```

The above code snippet provided me this table in the "Table" panel in UI:
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/20401632/140812059-afaa988a-5406-45e4-af1c-78e0c7ba27cc.png">

Could you please provide a link to your workspace and the code snippet you ran to log the table above? That would help us in debugging this further.

**Comment by pini-kop** [comment]
first i'll describe the bigger issue we are facing - we are trying to log multiple dataframes and their descriptions. 
they are logged as artifacts and we can access the corresponding json files, but they are not properly displayed in the UI. 
 
I have multiple datasets from different sources that I want to log in their raw form before merging them to a single dataset. each dataset (as pandas datafrmae) has between few dozens to thousand of records. and each record is a triplet of 3 paths (strings) of images, T0, T1 and a mask. 
for example:
trainset1 = pd.read_csv(train1.csv)
so trainset1 has roughly 5k rows and 3 columns (T0, T1, mask). and I'm logging both trainset1 dataframe and trainset1.describe() dataframe. 

the code snippet: 

train_files = [path/to/train1.csv, path/to/train2.csv,...]
val_files = [path/to/val1.csv, path/to/val2.csv,...]
test_files = [path/to/test1.csv, path/to/test2.csv,...]

train_ds = {fnmae: pd.read_csv(fname) for fname in train_files} 
val_ds = {...}
test_ds = {...}

from wandb.sdk.interface._dtypes import AnyType
run = wandb.init(...)

for name, df in train_ds.items():
    wandb.log({
        f'Mapping File/{name}': wandb.Table(dataframe=df, allow_mixed_types=True, dtype=AnyType), 
        f'Mapping File Description/{name}': wandb.Table(dataframe=df.describe(), allow_mixed_types=True, dtype=AnyType)
        })

for name, df in val_ds.items():
   ...
...
run.finish()

and this is how they appear in the UI
![Screenshot from 2021-11-09 11-16-33](https://user-images.githubusercontent.com/81951018/140896631-19e6d2da-8763-43f5-8c25-2c4912b6532d.png)
:

https://wandb.ai/percepto/multi_ds/runs/73efonze?workspace=user-olga

specifically, to produce the example in the original post, I manually uploaded only a single description with the following snippet: 
run = wandb.init(...)
wandb.log({f'Mapping File Description/{name}': wandb.Table(dataframe=df.describe().astype(str))})
run.finish()
but now, when looking on the 'experiment' this specific table looks okay (see under DataframesZ3/bobik), the rest are still missing
https://wandb.ai/percepto/multi_ds/runs/2dxtdw6v?workspace=user-olga

I'm using: 
wandb version 0.12.6
python 3.6.9
os: Ubuntu18.04 (Linux-5.4.0-1058-aws-x86_64-with-Ubuntu-18.04-bionic)

**Comment by tssweeney** [comment]
hi @pini-kop, thank you for reporting the issue. In fact, this has to do with dots (.) in the key name. I have a fix that needs to get reviewed and merged.

In the meantime, you can log the tables without dots in the name and the UI should reflect the expected tables.

Note: after the change is released, you will need to "Reset your Workspace" (an option in the bottom left of your workspace).
