### ISSUE TITLE
[App] Expressions not working

### ISSUE THREAD

**Issue by LucaHermes** [wandb/client#2896]
**Describe the bug**
Whenever I want to use an expression in any panel I get ```Oops, something went wrong. If this keeps happening, message support@wandb.com with a link to this page```. I tried to add an expression for multiple panel types and in two different projects on different browsers (firefox/chromium/chrome).
This message is shown as soon as I type the closing bracket '}'. Afterward, all options to set up the panel disappear, and the only options 'OK', 'Cancel', and 'Delete' are shown.

**EDIT:** The console outputs the following:
```
ReferenceError: Buffer is not defined
    qX expr.ts:466
    qX expr.ts:463
    Xh expr.ts:527
    n PanelExpressionOptions.tsx:58
    hl PanelExpressionOptions.tsx:58
    u PanelRunsLinePlot.tsx:1479
    React 2
    rIe PanelRunsLinePlot.tsx:1477
    React 9
    unstable_runWithPriority scheduler.production.min.js:18
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
ErrorBoundary.tsx:24:12
```

(I have sent an EMail to support@wandb.com as well)

**To Reproduce**
1. Go to ```https://wandb.ai/t4c_team/<project>?workspace=user-<user_name>```
2. Click on ```Edit panel``` (either on a freshly added panel, or on an existing panel)
3. Change to tab ```Expressions```
4. Click on ```Add an expression```
5. Type in ```${Step}``` (or choose any of the available metrics)
6. See the error as soon as you type ```}```

**Expected behavior**
A line plot should appear containing the Step variable

**Operating System**
 - OS: Ubuntu 20.04
 - Browser Firefox (v.94.0); Chromium (v.95.0.4638.69); Chrome (v.93.0.4577.82)

**Comment by anmolmann** [comment]
Hi @LucaHermes , we deployed some fixes a few hours ago today which should've fixed this issue. Could you please refresh once and check if your issue has been resolved?
I tried reproducing the issue (following the steps as described above), however, I was able to add expressions.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/20401632/140840333-7b40b3da-57b5-461d-a441-df55ce00e466.png">

**Comment by LucaHermes** [comment]
Hi, thank's for looking into this.
Your example also works for me but the error doesn't seem to be resolved.
Could you try something like this: ```${summary:loss}```?
My use case is to combine metrics from different sections, like the train and validation section, e.g.:
```${train/score} / ${validation/score}```

**Comment by anmolmann** [comment]
This might be because I can see 2 loss metrics in your project: one is of type string and the other one is a float as seen below. Also, if you simply use: ${loss}, this should work.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/20401632/140843742-6df0e65b-e231-4ff7-a2a9-365a2d18217e.png">

**Comment by LucaHermes** [comment]
I tried using ```${loss}``` but get exactly the same error.

> one is of type string and the other one is a float as seen below.

I wasn't aware that one of my metrics is of type string, should that even be possible? Sorry about my confusion, but in your screenshot it also looks like plenty of my metrics are called 'mse'?

So I have two metrics which come from two different validation sets respectively. The first I log with key ```train_val/val_score``` and the second I log using the key ```train_val_spatial/val_score```. I can see the line plots are working of both metrics, so I assume that they are correctly logged. I now create another panel where I want to display the ratio of both and the following expression should do that, right?
```${train_val/val_score} / ${train_val_spatial/val_score}```

**Comment by anmolmann** [comment]
Glad things got sorted out for you!
