### ISSUE TITLE
[App][CLI] wandb.ai/authorize creates team token instead of personal token

### ISSUE THREAD

**Issue by epistoteles** [wandb/client#2898]
**Describe the bug**
I have created a new personal project under `wandb.ai/<username>/<projectname>` on the website.
In the then visible setup instructions, it gives me an authorization token that is identical to the token that I get when visiting `wandb.ai/authorize`
If I log in with this token from the command line it says 'logged in as <teamname>' instead of 'logged in as <username>' 
When I start a new run, the just created project is ignored and a new project is created under `wandb.ai/<teamname>/<projectname>` and synced.
It seems like I have no way of creating a personal (non-team) login token to sync personal projects.

**To Reproduce**
1. Be member of one team
2. Create a new personal project
3. Log in with the shown authorization token from the command line
4. Start run

**Expected behavior**
The website gives me a token that makes the CLI say 'logged in as <username>' and the CLI syncs to the just created personal project instead of creating a new team project.

**Additional context**
Google Colab
Python 3.7.12
wandb version 0.12.6
Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by vanpelt** [comment]
Hey @epistoteles the token showed on `/authorize` is the same as the first token in your personal settings page: https://wandb.ai/settings

If you want projects to be logged to a team by default, you can set your default entity in the settings page to that team.  You can also set the `WANDB_ENTITY` environment variable, or the entity keyword arg of wandb.init to send results to a team.

You can create a service account for a specific team by going to https://wandb.ai/teams/$TEAM_NAME and adding a "Service" user to the team.  This api token can then be used to post experiments to that team.  If you want to attribute experiments to actual members of the team you can set the `WANDB_EMAIL` or `WANDB_USER_NAME` environment variables.

**Comment by epistoteles** [comment]
Thank you for the thorough explanation!

I tried out the entity parameter and this resulted in the run being synced to the right project.

Maybe you can include this parameter by default in the shown instructions when default and project entity diverge? This would have helped me a lot, as they only included the line `logger = WandbLogger(project="<projectname>")` instead of `logger = WandbLogger(project="<projectname>", entity='<username>')` in my case (in the pytorch-lightning example, I didn't check the others).

Again, thanks for the help!
