### ISSUE TITLE
[Q] Update Run config to correct name changes

### ISSUE THREAD

**Issue by leonvarga** [wandb/client#2903]
Hey all,

WandB is one of my favorite tools to support my research. It helps a lot to structure your experiments.
But today I encountered a situation, which I could not solve. 

Following situation:
By solving a typo in a parameter name, I have runs with a parameter _label-a_ and runs with a parameter _label-b_. To solve this inconstancy, I want to add the parameter _label-b_ with the value of parameter  _label-a_ to my older runs. This would allow easier filters. 

The basic idea is very simple:

```
import wandb
api = wandb.Api()
runs = api.runs("entity/project_name", {"tags": "relevant"})

for run in runs:
    if "_label-b_" not in run.config.keys():
        run.config["_label-b_"] = run.config["_label-a_"]
```

But this way, the values aren't synced with the cloud. I already tried "run.update" with the same outcome. And I couldn't find anything in the documentation regarding this topic.

Is there a way to update the run-config after the run is finished, or is it a bad idea?

Best regards
Leon

**Comment by ramit-wandb** [comment]
Hi Leon,

Yes, you can use the `wandb.Api` class to update your run configs how you require. Here's what I would suggest:

```python
import wandb
api = wandb.Api()
runs = api.runs("entity/project_name", {"tags": "relevant"})

for run in runs:
    if "_label-b_" not in run.config.keys():
        run.config["_label-b_"] = run.config["_label-a_"]
        del run.config["_label-a_"] # Only if you don't want Label A to be in your config anymore
        run.update() # This line sends the updated information over to your W&B Dashboard
```

Please let me know if this solves your issue.

Thanks,
Ramit
Weights and Biases Support

**Comment by leonvarga** [comment]
Thank you!
That was the missing part. Now it updates the values.

Best regards,
Leon

**Comment by paulgavrikov** [comment]
@ramit-wandb is it also possible to do this from the web UI?

**Comment by V0XNIHILI** [comment]
I would also really appreciate it if we could do it via the web interface? It will save me a lot of time and hassle if I can quickly rename some fields.

**Comment by V0XNIHILI** [comment]
Any update on adding this to the web UI?

**Comment by thesofakillers** [comment]
would also be interested in a Web UI solution
