### ISSUE TITLE
[CLI] W&B Network Usage Bug -- 1.6TB of egress charges of GCP train 4 YOLOv5n models

### ISSUE THREAD

**Issue by glenn-jocher** [wandb/client#2905]
First raised with @AyushExel in https://github.com/ultralytics/yolov5/issues/5071 a month ago, but no progress in the intervening time period so raising this issue directly here.

I trained 4 (very small) models, only 4MB each, over 3 days on a GCP instance, and saw enormous network egress costs related to 1,600 GB of data sent from the instance. I'm assuming **all of this is W&B traffic**, as there were no other processes running on the instance. The egress to W&B steadily rose over the training time and by the end of the training was steadily increasing around 8 MB/s, nonstop 24/7, dropping back to zero after training completion.
<img width="1607" alt="Screen Shot 2021-10-06 at 5 21 10 PM" src="https://user-images.githubusercontent.com/26833433/136301406-2ae8d36c-3c00-465b-a15b-94fb28818054.png">

Yesterday October 5th GCP charged us $67 just for that day for this network traffic:
<img width="1474" alt="Screen Shot 2021-10-06 at 5 25 35 PM" src="https://user-images.githubusercontent.com/26833433/136301648-067c9797-61d7-451e-aa1c-500e9abdb79d.png">

I've also been seeing steady errors on the console related to the W&B connection:
<img width="1551" alt="Screen Shot 2021-10-06 at 5 28 18 PM" src="https://user-images.githubusercontent.com/26833433/136301834-4e20e6d4-a2e7-440f-a18f-1e14be87c21d.png">

An example run from this project that caused the above problem is here. I can't imagine what would have caused these four runs to transmit 1,600 GB of data off the instance in just 3 days. Please send this to the team for review. Thank you.
https://wandb.ai/glenn-jocher/yolov5_v6/runs/1yyym1gq?workspace=user-glenn-jocher

**Comment by vwrj** [comment]
Hi Glenn, apologies for the delay. We have been working on this, but it doesn't look like that was communicated -- sorry about that.

We have a fix that we believe should solve this issue; it's been merged into master and awaiting release next week. Here's what you can do in the meantime:

1. Use wandb from a branch we've created for you (with the fix):

```
pip uninstall wandb
pip install --upgrade git+git://github.com/wandb/client.git@yolov5_egress#egg=wandb
```

Now you should have wandb with the fix we've created.

2. Alternatively, you can always turn off console log streaming by passing in an env variable: `WANDB_CONSOLE=off python train.py`

Could you give us the exact command you use to run your train script? We're having trouble reproducing the issue on GCP with your exact environment (n1-standard-8 with T4 GPUs + Docker image).

**Comment by aidanjdonohue** [comment]
@glenn-jocher bumping @vwrj's comment

**Comment by glenn-jocher** [comment]
@aidanjdonohue @vwrj thanks for looking into this! The commands to reproduce this are in the W&B run as mentioned originally in https://github.com/ultralytics/yolov5/issues/5071:
https://wandb.ai/glenn-jocher/yolov5_v6/runs/1yyym1gq

```bash
train.py --data coco.yaml --batch 64 --weights '' --cfg yolov5n.yaml --epochs 300 --project yolov5_v6 --name yolov5n --img 640 --hyp hyp.scratch-low.yaml --linear --device 0
```

Though I don't think there's anything specific about the train command, I was assuming any train command would cause similar behavior since they all log the same information to wandb.

Is the fix in the current wandb pip package? If so I can try to verify the issue is resolved on our side.

**Comment by AyushExel** [comment]
@glenn-jocher Yes, the new version of CLI was released yesterday. The fix is in current wandb package

**Comment by glenn-jocher** [comment]
@AyushExel awesome thanks! I will test today.

**Comment by glenn-jocher** [comment]
@AyushExel @aidanjdonohue @vwrj network usage bug appears resolved now based on tests yesterday with most recent pip package. Closing issue!
