### ISSUE TITLE
[Q ] Ignored wandb.init() arg project when running a sweep 

### ISSUE THREAD

**Issue by lucasdevries** [wandb/client#2907]
Hi,

Every time I start a sweep, I get the message: 
`wandb: WARNING Ignored wandb.init() arg project when running a sweep `. The sweeps end up in a project folder called: `uncategorized`. This started to occur only when I created a new project. For my old projects, the sweeps are listed in the correct wandb project. When I simply run the project, without starting a sweep, the runs end up in the correct project.
 I initialize my project as follows:
`wandb.init(config=config, project='unet', entity='lucasdevries')`. My global WANDB_MODE variable has been set to 'online'. Am I forgetting something?

Thanks a lot,
Lucas

**Comment by vanpelt** [comment]
Hey @lucasdevries when you run a sweep the runs will inherit the project of the sweep.  Can you share how you're running your sweep agents?  It should be:

```bash
wandb agent lucasdevries/unet/$SWEEP_ID
```

or if you're running agents from python:

```python
wandb.agent($SWEEP_ID, train, entity="lucasdevries", project="unet")
```

**Comment by lucasdevries** [comment]
When starting a sweep through `wandb sweep sweep.yaml`, I get the message to tun `wandb agent lucasdevries/uncategorized/$SWEEP_ID`, instead of `wandb agent lucasdevries/unet/$SWEEP_ID`. When simply starting a run without a sweep, the runs do get assigned to the correct project. Could it have something to do that the project folder is not a GitHub repository?

**Comment by lucasdevries** [comment]
Initializing the project folder as a GitHub repo seems to solve the problem.

**Comment by vanpelt** [comment]
@lucasdevries you can specify the project you want to use when you create the sweep.

```
wandb sweep -p unet sweep.yaml
```

If we can't figure out the project from the environment we name the project after the name of the current git repo, or "uncategorized" if we're not in a git repo.  You can also create a settings file that can be checked into your git repo specifying the default project for any commands executed from that directory:

```
wandb init
```

This will create a settings file at `./wandb/settings` with the entity and project you specify.
