### ISSUE TITLE
[App] Table scaling hides audio player controls

### ISSUE THREAD

**Issue by larsrgit** [wandb/client#2908]
The scaling of tables including audio sometimes prevents the user from accessing the audio player controls. This also happens in some tables of the tables tutorial https://wandb.ai/stacey/cshanty/reports/Tables-Tutorial-Recreating-Whale-Melodies-on-Orchestral-Instruments--Vmlldzo4NDI3NzM

See also this screenshot from the tutorial:
![audio_table_scaling_wandb](https://user-images.githubusercontent.com/20171227/141274092-fd06864d-0fc7-4c0a-af39-01c29c04f4db.png)

I observed this behavior in both Firefox and Chromium browsers on Linux and Windows using 4k and 1080p Screens.

**Comment by tssweeney** [comment]
Hello - thank you for the bug report. This sizing issue has now been fixed in production!
