### ISSUE TITLE
[App] Limited number of prior runs for sweep.

### ISSUE THREAD

**Issue by PhilSk** [wandb/client#2940]
Hello, wandb team!

I tried to create a new sweep from existing runs, selected 36000 runs, in a window before creation it showed a correct number (screen attached), but after sweep creation only 1000 runs we showed as prior runs (another screen attached).

Is there a way to avoid this limitation?
Or this is just a bug?

Thank you in advance.

<img width="896" alt="Screenshot 2021-11-19 at 14 22 48" src="https://user-images.githubusercontent.com/11798485/142616999-2556750e-2a7b-4a57-879c-b3e02131a14d.png">
<img width="1718" alt="Screenshot 2021-11-19 at 14 36 49" src="https://user-images.githubusercontent.com/11798485/142617004-199ad7a0-d7dd-428a-8f51-b649b2cb418e.png">

**Comment by aidanjdonohue** [comment]
Hi @PhilSk, we do indeed limit 1000 prior runs. There's no way around this at the moment.

**Comment by PhilSk** [comment]
Got it, thanks!
