### ISSUE TITLE
[CLI] panic: Can't create default user

### ISSUE THREAD

**Issue by mmeendez8** [wandb/client#2941]
**Description**

I was trying to set up a local wandb following the documentation. In the [quickstar guide](https://docs.wandb.ai/guides/self-hosted#quickstart-guide) you can read the following:

![image](https://user-images.githubusercontent.com/15969667/142621976-1c031ab2-8c5e-4033-9065-f16b4384c29c.png)

So basicaly I tried to directly run the Docker directly without installing wand in my Python env and I got the following error:

```console
$ mmendez@Visualizacion1:~$ docker run -it --rm -v /home/mmendez/wandb:/vol -p 8080:8080 --name wandb-local wandb/local
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
mkdir: cannot create directory ‘/vol/env’: Permission denied
find: ‘/vol/env’: No such file or directory
*** Loading settings...
2021/11/19 12:22:39 Error adding user: open /vol/env/users.htpasswd: no such file or directory
panic: Can't create default user

goroutine 1 [running]:
main.ensureDefaults({{0x1064f8e, 0x4}, {0x0, 0x0}, {0xc000039830, 0x16}, {0xc0004ee970, 0xa}, {0x107bd07, 0x1a}, ...})
	/mnt/ramdisk/core/services/local/cmd/local/main.go:574 +0x565
main.commands({{0x1064f8e, 0x4}, {0x0, 0x0}, {0xc000039830, 0x16}, {0xc0004ee970, 0xa}, {0x107bd07, 0x1a}, ...})
	/mnt/ramdisk/core/services/local/cmd/local/main.go:393 +0x1518
main.main()
	/mnt/ramdisk/core/services/local/cmd/local/main.go:672 +0xf8
!!! Failed to load settings. If this issue persists, please contact support@wandb.com.
*** Booting runit daemon...
*** Runit started as PID 41
```

I see that when you run wandb local you get promted with `wandb: Paste an API key from your profile and hit enter: ` and error dissapears. It would be good to update documentation accordingly or provide a way to pass the API key to the docker run command.

**How to reproduce**

```bash
mkdir wandb
docker run -it --rm -v $(pwd)/wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```

**Environment**
- OS: Ubuntu 18.04
- Environment: Docker

**Comment by vanpelt** [comment]
@mmeendez8 this is due to file system permissions.  You need to ensure the filesystem you mount gives write permission to the root group:

```
chgrp -R 0 $(pwd)/wandb
chmod -R g+rwX $(pwd)/wandb
```

**Comment by mmeendez8** [comment]
Ok! I did not interpret the log properly! I was checking the docker command that cli runs when running wandb local:
https://github.com/wandb/client/blob/master/wandb/cli/cli.py#L1388

Si it seems that docker creates automatically a folder with the right priviliges when volume path does not exist, didn't know this!
https://github.com/moby/moby/issues/13121

Thanks for your help!
