### ISSUE TITLE
[Q] How to batch-add/edit tags to runs?

### ISSUE THREAD

**Issue by Wilann** [wandb/client#2942]
Hi, as I realized an issue with my training pipeline after performing many runs, but would like to keep these runs, I need a way to add a tag such as "Bug" to ~800 runs so they can easily be filtered in the UI. 

Is there a way to do this with the API instead of by-hand?

**Comment by armanhar** [comment]
Hey WIlson. Yes, you can do it like this:

```
run = wandb.Api().run("{entity}/{project}/{run-id}"})
run.tags.append("tag1")  # you can choose tags based on run data here
run.update()
```

**Comment by Wilann** [comment]
Hi @armanhar,

Thank you for the quick reply. 

Is there a way to get a batch of runs between 2 dates/times? I would like to add/edit the tags for those runs. 

Also, how would I remove or edit the tag? Your code above seems to only add a tag.

**Comment by armanhar** [comment]
The tags attribute returns a list so you should be to make the appropriate changes to the list.
You can pass a [filter](https://docs.wandb.ai/ref/python/public-api/runs) dict to api.runs(). Using that the api.runs() call will return the runs matching your criteria

**Comment by Wilann** [comment]
Checking the source code, it seems the filter uses MangoDB to query to DB, which I'm unfamiliar with. It seems that I can use `createdAt` in the filter dict. It's unclear what the format of the value for this should be. 
It also seems that `wandb.apis.public.Runs()` needs a `client` parameter - what's that?

**Comment by Wilann** [comment]
@armanhar I'd greatly appreciate it if you could explain more clearly how to use the `filter` dict to `wandb.apis.public.Runs()` in order to get a batch of runs based on creation time.

**Comment by armanhar** [comment]
Hey @Wilann Sorry about the delay on this. Here is an example on how to filter runs: runs = api.runs("project_path_here", filters={"createdAt": {"$in": ["date"]]}})

**Comment by armanhar** [comment]
You can find more on how to query runs here: https://docs.mongodb.com/manual/tutorial/query-documents/
