### ISSUE TITLE
[CLI] Unable to retrieve a run with parameter in scientific notation

### ISSUE THREAD

**Issue by PhilSk** [wandb/client#2947]
Hi, wandb team!

I found it's not possible to retrieve a run with one of the parameters as a small float in scientific notation.
I have two runs with the same parameter being 0.0001 and 0.00001 (which is 1e-05).
`wandb.Api.runs` is used to download runs.

Step 1: Download both runs - correct
<img width="1471" alt="Screenshot 2021-11-21 at 10 06 16" src="https://user-images.githubusercontent.com/11798485/142753252-b31bc90b-a52a-4c28-9c36-224eae49f339.png">

Step 2: Download only run with `config.beta_f=0.0001` - correct
<img width="1477" alt="Screenshot 2021-11-21 at 10 06 43" src="https://user-images.githubusercontent.com/11798485/142753297-14807877-e17a-4899-9b01-078629523b3e.png">

Step 3: Download only run with `config.beta_f=0.00001` - problem
<img width="1470" alt="Screenshot 2021-11-21 at 10 06 57" src="https://user-images.githubusercontent.com/11798485/142753324-7084f4d6-e653-42e1-8301-e4a48796bf91.png">
<img width="1471" alt="Screenshot 2021-11-21 at 10 07 15" src="https://user-images.githubusercontent.com/11798485/142753331-433dc3c3-6949-45b8-a0d2-529cd3678fa5.png">
<img width="1466" alt="Screenshot 2021-11-21 at 10 18 43" src="https://user-images.githubusercontent.com/11798485/142753367-d6f3675d-fd53-41e6-bff9-8c3bb2edb38b.png">

Looks like there is some problem on the server side.

**Environment**
- Mac OS Monterey 12.0.1
- Jupiter Notebook in VSCode
- Python 3.8.9

**Comment by PhilSk** [comment]
For simplicity I made a simple public project with only 3 runs: https://wandb.ai/phil_s/for_testing/

It has only 2 runs with two parameters in their config files: `alpha` and `beta`.
`alpha` is always 1, `beta` can be 0.0001 or 0.00001.

The code I download these runs with is:
```python3
import wandb


api = wandb.Api(timeout=19)
betas = (0.0001, 0.00001, 1e-05)
for beta in betas:
    runs = api.runs("for_testing", filters={
        "config.alpha": 1,
        "config.beta": beta,
        })

    print(f'Beta {beta} got {len(runs)} runs.\n')
```
As you see in `betas` array, for `beta=0.00001` I tried its scientific notation also.

The output of this script is:
```
Beta 0.0001 got 1 runs.

Beta 1e-05 got 0 runs.

Beta 1e-05 got 0 runs.
```

Hope this little experiment will help in finding the problem.

**Comment by ramit-wandb** [comment]
Hi @PhilSk!

There is probably no issue with how you are using scientific notation, but this is likely MongoDB's behavior that you are facing. [Runs](https://docs.wandb.ai/ref/python/public-api/api#runs) are filtered by the MongoDB Query Language, and due to some of the underlying logic of MongoDB, people get unintended effects - like your floating point equality check failing.

You can likely remedy this by changing:
```python
filters = {'config.some_key' : 1e-05}
```
to 
```python
filters = {'config.some_key' : {"$lte" : 1e-05, "$gte" : 1e-05}}
```

**Comment by PhilSk** [comment]
Thank you very much!
