### ISSUE TITLE
[Q] how to track a tensorflow Cloud Model using Weights and biases platform 

### ISSUE THREAD

**Issue by Oussamayousre** [wandb/client#2948]
I'm trying to track my TensorFlow Cloud Model with weights and baises platform using Kaggle notebook, but I'm getting an error when I try to login into Wandb using tfc : 
![image](https://user-images.githubusercontent.com/47725118/142780609-d4484c5a-075c-48a1-82b8-4e5c01bcfac7.png)
![image](https://user-images.githubusercontent.com/47725118/142780613-942c2b36-a45c-4cc6-8844-e0a9642f3b26.png)
![image](https://user-images.githubusercontent.com/47725118/142780618-b96786b1-ae68-4bb8-bce9-a5f71ffab593.png)

here is my requirement.txt file 

![image](https://user-images.githubusercontent.com/47725118/142780642-e9c0bed9-dedc-4361-964d-3d0ee6afee4d.png)
 
 and the code to login intop Wandb : 
 
!wandb login API-KEY

**Comment by vanpelt** [comment]
The error your getting is from calling `get_ipython()` which is returning null.  Instead of calling wandb login you can just set the WANDB_API_KEY environment variable.  This could be set in the job spec you're sending to TensorFlow Cloud or directly in python:

```
import os
os.environ["WANDB_API_KEY"] = "XXXXXXXXX"
```
