### ISSUE TITLE
[Q] How to exit from "Exception: The wandb backend process has shutdown"

### ISSUE THREAD

**Issue by makinzm** [wandb/client#2952]
Now, I learn how to use wandb (from https://docs.wandb.ai/quickstart).

And then, I tried to interrupting implementation during training in keras-intro.

![image](https://user-images.githubusercontent.com/40193664/142956714-b03dc637-eca4-4ebb-87c9-2d3aa1dafc2f.png)
![image](https://user-images.githubusercontent.com/40193664/142956747-b595e202-2c78-475c-b762-15b897b38c40.png)

and then, I can't implement any code : 
![image](https://user-images.githubusercontent.com/40193664/142956824-9d6a1678-a78b-4c83-a8da-7f76e9a08db0.png)

Therefore, I would appreciate it if you teach me how to exit from this condition.

**Comment by aidanjdonohue** [comment]
Hi @makinzm, can you try calling `wandb.finish()` after interruption to see if that helps?

**Comment by makinzm** [comment]
@aidanjdonohue 
Thank you for your answering.

However, I can't re-produce this condition today , but I think your answer may be correct.

Thank you anyway.
