### ISSUE TITLE
[Feature] UI filter tags based on `in` or `.startswith(...)`

### ISSUE THREAD

**Issue by Wilann** [wandb/client#2960]
**Is your feature request related to a problem? Please describe.**
I have multiple tags in the form of: "Error - ...", which I use to keep track of errors that occur in various runs. This makes it easy to see all runs with the same issue, but when you have many tags like this, I would have to filter "Tags" by each error tag. 
Ex. Filtering by "Error - 1", "Error - 2", ...

**Describe the solution you'd like**
It would be great if we could filter tags that contain or start with a string. Something like python's `in` or `.startswith(...)`. 

**Describe alternatives you've considered**
(Please see first paragraph)

**Additional context**
An example of having to filter with each individual tag:
<img width="610" alt="Screen Shot 2021-11-24 at 8 54 17 PM" src="https://user-images.githubusercontent.com/40744757/143362335-2db8e28a-25a7-4252-a36e-b86952209d25.png">

**Comment by Wilann** [comment]
Thank you very much, Leslie.

**Comment by JulienStanguennec-Leddartech** [comment]
That'd be cool indeed.

**Comment by kavanase** [comment]
Agreed, this would be a very useful feature if possible!
