### ISSUE TITLE
[Q] How to sync wandb exam dir when some files is missed

### ISSUE THREAD

**Issue by chenshen03** [wandb/client#2967]
During training, I executed `wandb.save(args.config_file)`, and found that the soft link to the `config_file` file was saved in the experimental directory of wandb.
I then accidentally deleted `config_file` and got the following error when running `wandb sync wandb/offline-XXX-ID`:
![image](https://user-images.githubusercontent.com/20432947/143810394-77707bf2-56bc-4ee3-9851-fce8de4cb064.png)

So, how to sync wandb exam dir when some files is missed.
Thank you very much!

**Comment by aidanjdonohue** [comment]
Hi @chenshen03, `wandb.save()` symlinks your files into the run directory and `wandb sync` tries to sync those to the cloud. Can you try removing the reference from your run directory and see if that works?

**Comment by chenshen03** [comment]
This approach works, but doesn't really solve my concern because I have a lot of run directories. I was wondering if `wandb.save` could provide a parameter that would copy the source files instead of sysmlink.

**Comment by chenshen03** [comment]
I'm running wandb on a local server and expect that each run directory is self-contained without any dependencies with other files, so I can share them direcly across different machines.

**Comment by aidanjdonohue** [comment]
We're moving towards deprecating `wandb.save` eventually so it's not likely that we'll implement this. Copying the source files yourself is always an option. If you call `wandb.save` on something inside your `./wandb/run_xyz` dir you will obviously avoid the symlink issue.
