### ISSUE TITLE
[Feature] Add the option to save continuously the weights of your model online in the Keras Callback

### ISSUE THREAD

**Issue by zaccharieramzi** [wandb/client#2969]
**Is your feature request related to a problem? Please describe.**
I was frustrated when I discovered that the Keras Callback actually only saved the model weights online once [here](https://github.com/wandb/client/blob/v0.12.7/wandb/integration/keras/keras.py#L373), and then only saved to a local file [in this function](https://github.com/wandb/client/blob/v0.12.7/wandb/integration/keras/keras.py#L901L920).

**Describe the solution you'd like**
I would like to have the possibility to save the model online, i.e. `wandb.save(self.filepath)`, at the end of every epoch.
This could be activated by a flag, but I think it should be the default.

**Describe alternatives you've considered**
I could definitely have my own callback but it defeats a bit the purpose of this callback imho.
For example:

```python
class MyWandbCallback(WandbCallback):
    def _save_model(self, epoch):
        super()._save_model(epoch)
        wandb.save(self.filepath)
```

**Additional context**
https://docs.wandb.ai/guides/track/advanced/save-restore#how-can-i-sync-files-before-the-run-ends

**Comment by aidanjdonohue** [comment]
Hi @zaccharieramzi this seems reasonable. Let me look into this and update you on what we plan on doing.

**Comment by aidanjdonohue** [comment]
Hi @zaccharieramzi I apologize for the confusion. `wandb.save` defaults to a live saving policy, meaning that every time the local file gets overwritten, `wandb.save` will save the new version. You can read more about `wandb.save` [here](https://docs.wandb.ai/ref/python/save)

**Comment by zaccharieramzi** [comment]
Ha interesting! However, my weights file was not getting updated for some reason. I will try to create a reproducible example for this behaviour then.

**Comment by aidanjdonohue** [comment]
Hey @zaccharieramzi, we're going to close out this issue. If you manage to create a reproducible example, feel free comment it here and we'll open this back up.
