### ISSUE TITLE
[CLI] Resumed runs lose pre-resumed data

### ISSUE THREAD

**Issue by abaisero** [wandb/client#2971]
**Description**
I'm trying to use wandb in a computing cluster setting which poses some limitations:  I have to run everything offline, and I have time limits on all my processes.  Offline wandb runs on their own work fine, but resuming them is causing some issues.  I'm not 100% sure if the issue is in the data being lost altogether, or technically it's also possible that this is only a visualization issue on the wandb website (although I doubt that).

Here is my pipeline:

1. I start some offline runs.  They work fine and always complete without any issue.  Before the time limit runs out, each run saves a checkpoint with a snapshot of the run, needed to pick the work up, and then ends properly, achieving "finished" status.
2. I sync the data, and view it on the wandb website:

![image](https://user-images.githubusercontent.com/1794938/144137612-415f0f0a-47c6-42b5-a264-cd261ebcdca8.png)

(note that the logging starts at 50k because of internal program logic;  this is correct as it stands).

3. now I resume the runs;  to do this, I load the snapshot, which among other things contains the run id, and use wandb.init(..., resume='must', id=run_id_from_snapshot).  It looks like the run is resumed correctly, and there are no other issues with it.  Before the time limit runs out, each run saves a checkpoint with the snapshot of the run, and ends properly, achieving "finished" status again.

4. I sync the data, and view it on the wandb website:

![image](https://user-images.githubusercontent.com/1794938/144139522-01eab18b-e3f2-467d-a4d6-5e148bd3ebc3.png)

These are the same runs as shown in the first image.  You'll note that only one of them is now starting from 50k, as it should.  All the other runs, seem like they are starting either from the point where they were resumed, or, in the case of the orange line, between the real start (50k) and the point where they resumed, i.e., the previous data seems lost.

5. I repeat the process again:  resume the runs, then sync the data, and view it on the wandb website:

![image](https://user-images.githubusercontent.com/1794938/144142807-9f55863e-d721-48ee-89c2-c658cc0cff23.png)

Again, same issue is repeating itself (with different runs now demonstrating the issue, i.e., the orange and gray lines now are "pushed back" and have lost data compared to what was available before resuming).

**Wandb features**
I primarily just use wandb.init() to initialize a run, and as a context manager to also finish it, and wandb.log to log data.

**How to reproduce**
Don't have a MWE yet, but I could make one if required.

**Environment**
- OS: Red Hat 4.8.5-44
- Environment: Command line execution on SLURM-based computing cluster
- Python Version: 3.8.3

**Comment by abaisero** [comment]
I made a MWE, and figured out both the problem and the solution through it.  The problem was that, even though the runs were resumed, the respective `step` counter was starting from 0 again, and the new logs associated with a given step were overwriting the previous logs associated with the same step.  A simple fix is for each subsequent resumed run to also increase the `step` manually, such that this never happens.. it is a bit annoying to do, but it is possible.  I hope the way to resume offline improves in future versions, but for now I think I can close this issue.  I'll add the MWE below:

mwe.sh (must be run multiple times)

```bash
#!/bin/bash

export WANDB_API_KEY= # fill this in
export WANDB_ENTITY= # fill this in
export WANDB_PROJECT=mwe
export WANDB_MODE=offline

python mwe.py
wandb sync --sync-all

exit 0
```

mwe.py

```python
#!/usr/bin/env python
import pickle
import random
from dataclasses import dataclass

import wandb


@dataclass
class ProgramState:
    """Program state"""

    x: int = 0
    y: float = 0.0


def save_data(data):
    """saves data to file"""
    with open('checkpoint.pkl', 'wb') as f:
        pickle.dump(data, f)


def load_data():
    """loads data from file"""
    with open('checkpoint.pkl', 'rb') as f:
        return pickle.load(f)


def program(program_state: ProgramState) -> ProgramState:
    x_start, y = program_state.x, program_state.y
    x_stop = x_start + 100

    for x in range(x_start, x_stop):
        y += random.random() - 0.5
        wandb.log({'x': x, 'y': y}, step=x)  # removing step=x reintroduces the logging problem

    return ProgramState(x_stop, y)


def main():
    wandb_init_kwargs = {'tags': ['mwe']}

    # try loading checkpoint
    try:
        data = load_data()
    except FileNotFoundError:
        program_state = ProgramState()
    else:
        wandb_init_kwargs.update(
            {
                'resume': 'must',
                'id': data['run_id'],
            }
        )
        program_state = data['program_state']

    # perform run
    with wandb.init(**wandb_init_kwargs):
        program_state = program(program_state)
        run_id = wandb.run.id

    # save checkpoint
    save_data(
        {
            'run_id': run_id,
            'program_state': program_state,
        }
    )


if __name__ == '__main__':
    main()
```

**Comment by NiccoloCavagnero** [comment]
This issue is persisting, does anyone know a simpler and cleaner way to fix it?

**Comment by NiccoloCavagnero** [comment]
The issue is persisting, and cannot be easily avoided for example when using PyTorch Lightning, as the default logging function does not accept a "step" argument.

Does anyone know how to fix it without specifying the step?

**Comment by kabouzeid** [comment]
I have the same problem with PyTorch Lightning, it's very annoying :/

**Comment by NiccoloCavagnero** [comment]
I found a workaround, not elegant but it does work.

Once the experiment is finished, generate a new unique id, then log the last log directory to the new id. After you logged the last one, you are able to log all the others to the same new id.
