### ISSUE TITLE
can I run two accounts at the same GPU, if can, how should I do?

### ISSUE THREAD

**Issue by Letget** [wandb/client#2972]
I am a newbie, I observed when the new account logins, the old Key API has covered the specified file, such as /Home/xxx/.netrc, does this mean that the account login is loaded from here when the ' wandb' is started? If so, can I specify this file name instead of the default?
In other words, can I run two accounts at the same GPU, if can, how should I do it?

**Comment by aidanjdonohue** [comment]
Hi @Letget, the easiest way to navigate between using two accounts would probably be `wandb login <account-1-api-key>` to login with the first account and using your other accounts api key to login to the second one. If you are having trouble finding your api key, it can be found by going to www.wandb.ai/authorize
