### ISSUE TITLE
[App] Sweep does not re-run failed runs, even after deleting

### ISSUE THREAD

**Issue by zimmer-m** [wandb/client#2980]
When I create a sweep grid search, I want to explore all possible parameter configurations. Sometimes however, some runs fail because of an implementation bug or just due to network issues. When I delete these failed runs from the sweep while it is running, these runs will not be repeated. As soon as the sweep reaches the predefined number of runs, it will go on "pause" mode. Then after reactivating the sweep, the remaining runs will be finished. This is increasingly annoying since I often fix bugs on the fly and expect failed runs to be completed when I delete them from the already running sweep.

Interestingly, I did not observe this behaviour a couple months ago - I feel like this must have changed with a recent update.
Best,
Max

**Comment by aidanjdonohue** [comment]
Hi @zimmer-m is the blocker that your sweeps sit "nominally" finished for a while or simply that this happens often enough that reactivating it manually is a big hassle?

**Comment by aidanjdonohue** [comment]
Hey @zimmer-m wondering if you've had a chance to look at this. If it's no longer an issue we'd like to close this.

**Comment by zimmer-m** [comment]
Hi @aidanjdonohue, reactivating manually is indeed a big hassle, I have large sweeps where I'd like to simply delete the failed runs when something unexpected happens, without having to send jobs to the cluster again.

A bigger problem however, which is noticed after writing the above, is that some sweeps, where I manually delete failed runs and click on resume after it has finished, are unable to send jobs to the agents. In other words, the agents can stay forever in an idle mode waiting for a job that never comes. This seems like a proper bug.

**Comment by aidanjdonohue** [comment]
Hi @zimmer-m that does sound like a proper bug. Could you link me to the sweeps page where this is happening so I can take a look things?

**Comment by zimmer-m** [comment]
Unfortunately I cannot point you to a sweep where this happened, I deleted it and redid it as a whole. Will update once this happens again.

**Comment by ramit-wandb** [comment]
Hi @zimmer-m, I wanted to follow up on this issue. Were you able to reproduce this issue in another sweep?

**Comment by zimmer-m** [comment]
@ramit-wandb Not yet, if you want we can close this issue and I will report back as soon as I notice the error again.

**Comment by ramit-wandb** [comment]
Sure, you can comment here again if you see this error and we can pick it up from there!

**Comment by hlzl** [comment]
> Hi @zimmer-m is the blocker that your sweeps sit "nominally" finished for a while or simply that this happens often enough that reactivating it manually is a big hassle?

I've also ran into this issue multiple times and did not know that reactivating the sweep solves this issue. This is definitely a bug IMO.

Regarding reproduction, this can easily be replicated by introducing any bug that causes a run to fail. E.g. renaming the script specified in the grid sweep such that it won't be able to find it anymore.

**Comment by kaczmarj** [comment]
i am facing the same issue right now. i have a sweep, and several runs failed. my sweep is still in "running" state, so i deleted the failed runs and started another worker to re-run them. the worker is sitting idle.

```
wandb: Starting wandb agent 🕵️
2022-11-14 09:47:35,718 - wandb.wandb_agent - INFO - Running runs: []
```

i still have a few runs running, so once they finish, i will stop the sweep and then resume it. i hope this will prompt the worker to pick up the deleted runs.

my sweep is at https://wandb.ai/kaczmarj/champkit-journal/sweeps/4dd840ch
