### ISSUE TITLE
[Q] Drop dependency on backported configparser?

### ISSUE THREAD

**Issue by jbylund** [wandb/client#2992]
If I'm reading the setup.py correctly, python version must be 3.6+ which means wandb shouldn't need the backported configparser as a dep? and should be able to get along using the stdlib one?

[configparser dependency](https://github.com/wandb/client/blob/master/requirements.txt#L13)

**Comment by aidanjdonohue** [comment]
@jbylund looks like a vestigial dep from when we supported `2.7` and `3.5` but let me double check.

**Comment by jbylund** [comment]
Looks like typing, enum34, and subprocess32 can maybe also be added to the list to go?

**Comment by aidanjdonohue** [comment]
We're going through and cleaning up some of our dependencies. I'll update this thread when we finish this.

**Comment by aidanjdonohue** [comment]
Done and merged.
