### ISSUE TITLE
[CLI] Artifact API: "KeyError: 'cursor'"

### ISSUE THREAD

**Issue by rjbruin** [wandb/client#2996]
**How to reproduce**
```python
import wandb

api = wandb.Api(overrides={
    'entity': 'rjbruin',
    'project': 'rnn',
})
models = list(api.artifact_type('model').collections())
```

Error message:

```
Traceback (most recent call last):
  File "/redacted/cleanup_artifacts_minimal_example.py", line 7, in <module>
    models = list(api.artifact_type('model').collections())
  File "/redacted/miniconda3/envs/rnn/lib/python3.9/site-packages/wandb/apis/public.py", line 655, in __next__
    if not self._load_page():
  File "/redacted/miniconda3/envs/rnn/lib/python3.9/site-packages/wandb/apis/public.py", line 639, in _load_page
    self.update_variables()
  File "/redacted/miniconda3/envs/rnn/lib/python3.9/site-packages/wandb/apis/public.py", line 2339, in update_variables
    self.variables.update({"cursor": self.cursor})
  File "/redacted/miniconda3/envs/rnn/lib/python3.9/site-packages/wandb/apis/public.py", line 2332, in cursor
    return self.last_response["project"]["artifactType"]["artifactSequences"][
KeyError: 'cursor'
```

**Environment**
- W&B client version: 0.12.7
- OS: Ubuntu 20.04.3 LTS
- Environment: Local installation
- Python Version: 3.9

**Comment by aidanjdonohue** [comment]
Hi @rjbruin looking into this

**Comment by aidanjdonohue** [comment]
Hey @rjbruin how many artifacts do you have in this project?

**Comment by rjbruin** [comment]
Quite a lot. I don't know exactly, but the Artifacts page shows at least 500 entries. 

The script I was using was actually meant to remove all but the artifacts for the best/latest models. I couldn't find a way to remove artifacts during a training run, so my workflow is to track many model checkpoints and remove obsolete ones later.

**Comment by anmolmann** [comment]
Hi @rjbruin , apologies for the delay here. Thanks for the details. Could you try upgrading to our latest cli version (`0.12.9`) and try this out once again? Also, as it's mentioned above that you're on a local wandb installation -- is that right? If yes, could you please also share which wandb local version are you on? (You can check it out on `/system-admin`).

**Comment by rjbruin** [comment]
Thanks! I'll sit tight :)

**Comment by anmolmann** [comment]
Hi @rjbruin, I just wanted to let you know that we've pushed a fix for this issue in our latest cli release v0.12.10. Please let us know if you still encounter any issues.

**Comment by rjbruin** [comment]
Indeed, it works now. Thanks very much! :)
