### ISSUE TITLE
[Q] Use sweeps from python script and have n parallel execution at the same time  

### ISSUE THREAD

**Issue by RomainCendre** [wandb/client#3010]
Hi everyone, 
I came here to get answers about some problems I'm facing with sweeps. Actually, I want to choose the best hyperparameters for a CNN architecture and tadaaa sweeps can do it. From this point, I'm getting what I want, I mean it's working but I'm using only 25% of my GPU capacity.

So I tried to implement a Process/Thread solution, that can manage multiple runs to fully charge my GPU, in this way :

`sweep_id = wandb.sweep(sweep_config)
    procs = []
    for process in range(args.sweep_process):
        proc = mp.Process(target=wandb.agent, args=(sweep_id, lambda: launch_train(args), args.wandb_entity, args.wandb_project, args.sweep_count))
        procs.append(proc)
        proc.start()

    # complete the processes
    for proc in procs:
        proc.join()`

The code is working, but I'm little skeptical about what I've done. When I'm going inside the agent panel, it seems like there is a "Run" column that give the number of tasks actually running, so probably I need a single agent as I'm on a single machine with multiple run as I need ? But it seems that I can't make multiple init at the same time or perhaps I missed something?

I would be glad if you can provide a little tips on that =)
Thanks

**Comment by aidanjdonohue** [comment]
@RomainCendre can you post a link to your sweeps page so I can take a look? It doesn't have to be public

**Comment by RomainCendre** [comment]
@aidanjdonohue Yep sure, you can find it here and it's public : https://wandb.ai/rom1ash/uncategorized/sweeps/j6x5cttv/overview?workspace=user-rom1ash

**Comment by aidanjdonohue** [comment]
@RomainCendre I don't believe running multiple agents will negatively impact your Bayesian sweep. Your multiprocessing code looks totally fine to me. Is there anything specific you are worried about?

**Comment by RomainCendre** [comment]
@aidanjdonohue Hi again, thanks for the feedback ! I was more worried about the way and the context I was calling the API =)
Thanks a lot for that reply !
Best regards!
