### ISSUE TITLE
Cannot view images via slider manipulation on Firefox

### ISSUE THREAD

**Issue by tobyclh** [wandb/client#3033]
**Describe the bug**
I cannot view  images properly using slider. 

**To Reproduce**
1. Go to any project with image
2. Move the step slider for images
3. See error

**Expected behavior**

**Screenshots**
Above is the proper behaviour that I can see the image history on Chrome. 
Below is the behaviour on FIrefox, but the image is not displayed except for the first and the last one. 
![chrome_wandb](https://user-images.githubusercontent.com/12501995/145669679-5807e317-8f77-499c-b19b-18a8845ef85a.gif)
![firefox_wandb](https://user-images.githubusercontent.com/12501995/145669680-023dc779-d334-4599-a41f-8450211b7085.gif)

**Operating System**
 - OS: Ubuntu 16.04, 18.04
 - Browser Firefox
 - Version 95.0

**Additional context**

**Comment by aidanjdonohue** [comment]
Thanks for reporting. Taking a look.

**Comment by aidanjdonohue** [comment]
Can you link me to the project page where you created those gifs?

**Comment by tobyclh** [comment]
@aidanjdonohue 
Thanks!
Please take a look at https://wandb.ai/toby/Makeup/

**Comment by laxels** [comment]
Hey there @tobyclh! I just pushed a fix that should address the issue. Can you refresh the page and try again? Please let us know if it's still misbehaving.

**Comment by tobyclh** [comment]
Thanks for the update!
I can confirm that the issue has been resolved. Thank you!
