### ISSUE TITLE
[Q]when I run the sweep agent "wandb agent caimingxue/MagRobot_RL/i7b2ug3h", it occurs some following errors, however, when i run this script, it will ok.

### ISSUE THREAD

**Issue by caimingxue** [wandb/client#3034]
![erroe](https://user-images.githubusercontent.com/45029643/145705077-6cb63d69-493b-474c-9279-1ecb47f6d955.png)

**Comment by armanhar** [comment]
Hey there, can you send the full stack trace and the script so we can repro the issue?
