### ISSUE TITLE
[Q] How to compare multiple lines on the same plot?

### ISSUE THREAD

**Issue by Ynjxsjmh** [wandb/client#3035]
In the document of [Line Plot - Documentation](https://docs.wandb.ai/ref/app/features/panels/line-plot), it says 

> Visualize metrics, customize axes, and compare multiple lines on the same plot

But how to do these? There is not even one line of code to show this matter.

**Comment by vanpelt** [comment]
You just call `wandb.log`: https://docs.wandb.ai/guides/track/log

**Comment by Ynjxsjmh** [comment]
@vanpelt  Thanks for your reply, I have tried the code following:

```python
import wandb
import numpy as np


wandb.init(project="test", entity="xxxx")

wandb.log({"my_custom_id":
           wandb.plot.line_series(
               xs=range(100),
               ys=[range(100), np.random.randint(100, size=100)],
               keys=["y1", "y2"],
               title="Multiline",
               xname="steps"
           )})
```

The picture I get after choosing *Edit Panel* is following:

![image](https://user-images.githubusercontent.com/40143136/145912432-787350eb-3bbd-49c0-b2e3-6f9333a1e4a3.png)

The picture I **want to** get is like

![image](https://user-images.githubusercontent.com/40143136/145912494-03004388-7c1e-4dc1-bcd1-f5618d64dd5b.png)

Difference between with these pictures are
- Mine doesn’t have **Data, Group** etc tabs.
- There are **two types** of legend *name* and *lineKey* in mine rather than one type.

**Comment by vanpelt** [comment]
Hey @Ynjxsjmh you likely don't want to use our custom plot functionality but instead just log the raw data, i.e.

```
import random
import wandb

wandb.init(project="test", entity="xxxx")
for i in range(100):
    wandb.log({"y1": random.random(), "y2": random.random(), "x": i})
```

Then you can edit any chart in your workspace to show both y1 and y2 plotted against "x":

![image](https://user-images.githubusercontent.com/17/145919134-5379fd51-befc-4751-8df7-277918b7e553.png)

**Comment by Ynjxsjmh** [comment]
@vanpelt  Thanks you for letting me know I should manually select **y** on **Data** tab to compare multiple lines on the same plot. I start to know that the [Line Plot - Documentation](https://docs.wandb.ai/ref/app/features/panels/line-plot) is talking about how to use the web interface to customize the plot rather than with code.

My confusion is that is it possible to customize the plot with code like `matplotlib`? For example, in `matplotlib`

- With `plt.plot(x, y, c=(0.25, 0.25, 1.00), lw=2, label="Blue signal", zorder=10)`, I could plot a line with **color** *(0.25, 0.25, 1.00)*, **line width** *2*, **zorder** *10* and **legend name** *Blue signal*
- With `plt.legend()`, I could show the legend.
- With `plt.title()`, I could set the plot title.
- With `plt.fill_between()`, I could fill the area between two horizontal curves.

However in `wandb`, it seems I need to manually set them through web interface:

![image](https://user-images.githubusercontent.com/40143136/145933579-11966d78-0b7a-4d55-bdb3-daf4a1f17485.png)

It would be inconvenient if I want to compare y1, y2 etc. through Experiment1, Experiment2 etc.

It's possible to log [Matplotlib and Plotly Plots | Log Plots - Documentation](https://docs.wandb.ai/guides/track/log/plots#matplotlib-and-lotly-plots) directly but it lacks some wandb features like Smoothing(Exponential Moving Average, Gaussian, Running Average).

```python
import wandb

import numpy as np
import matplotlib.pyplot as plt


wandb.init(project="test", entity="xxx")

figure, ax = plt.subplots()
ax.plot(range(100), np.random.randint(100, size=100), label='y1', color='blue')
ax.plot(range(100), np.random.randint(100, size=100), label='y2', color='red')
ax.set_title("Experiment")

ax.legend()
plt.tight_layout()

wandb.log({'chart': plt})
```

![image](https://user-images.githubusercontent.com/40143136/145934756-8575b0f7-bdc0-4063-bbc7-a8029863c052.png)

**Comment by Ynjxsjmh** [comment]
Thank you for your generosity!

**Comment by ArikVoronov** [comment]
Hi, I'm in need of the same feature (multi line plots) and the proposed solutions aren't really working in my case -

Uploading line_series or matplotlib plots can't be done incrementally per epoch which is how other metrics are done (am I correct here?) and is very time consuming at the end of the training session. It also removes many helpful features from the plot, such as changing the x axis and smoothing. 

The other option requires manual intervention which just isn't realistic for many training sessions (I'm running a large sweep)

Are there any plans to add this feature?

**Comment by ArturPrzybysz** [comment]
@vanpelt  Came here to mention that it is indeed a need functionality and it is a pain to have to either collect the plot data and access it only after the session is done, or have configure the plot manually each time.

Is there any plan to revisit this?

Same with 1 level of nested planes like `wandb.log({"level1": {"level2": {"value": 1.0}}}`.

**Comment by flavioschenker** [comment]
@ArturPrzybysz  agree! Demand is still there. Especially the simplest case, where you want to compare training with validation loss on the same plot. This is still not possible without manually configure the plot each time.

**Comment by spfrommer** [comment]
Bump. This is basic functionality in tensorboard via the "custom_scalars" feature and it's frustrating that there is nothing comparable in wandb.

**Comment by ugurbolat** [comment]
Any updates on this feature?

**Comment by ArturPrzybysz** [comment]
Lol, this customer support is awful. To think that I used to pay for this service.
It is such a simple feuture to implement.
Good bye wandb :disappointed:

**Comment by JirkoRu** [comment]
I also would love this feature!

**Comment by ezhang7423** [comment]
Bump! It seems that being able to configure the panel programmatically similar to how one can currently edit a report [programmatically](https://docs.wandb.ai/guides/reports/edit-a-report) would be the easiest way to do this..

**Comment by assafbk** [comment]
Any updates on this feature?

**Comment by vaibhav-entrupy** [comment]
I would like to see this feature as well. I have several groups of line plots to show on the separate graphs. doing them all on the UI is too much work.
