### ISSUE TITLE
[Feature] Dark mode

### ISSUE THREAD

**Issue by OverLordGoldDragon** [wandb/client#3043]
**Is your feature request related to a problem? Please describe.**

_my eyes_

**Comment by armanhar** [comment]
Hey OverLordGoldDragon, If you put the word "night" in your bio, you will activate dark mode. It is note a fully supported feature yet. We are planning to improve the dark mode in the near future.

**Comment by armanhar** [comment]
Hey OverLordGoldDragon, If you put the word "night" in your bio, you will activate dark mode. It is note a fully supported feature yet. We are planning to improve the dark mode in the near future.
