### ISSUE TITLE
Training with Sparse Embeddings

### ISSUE THREAD

**Issue by anthonytec2** [wandb/client#305]
* Weights and Biases version:0.7.0
* Python version: 3.7
* Operating System: Ubuntu 18.04

# 
## 
### Description

I had a watch on a Pytorch model that I was running for training embeddings which uses sparse gradient updates. I wanted it to log the model although it resulted in the bellow error:

# 
## 
### What I Did

Traceback (most recent call last):
File "scripts/pytorch_negsamp.py", line 88, in <module>
main(args)
File "scripts/pytorch_negsamp.py", line 66, in main
loss.backward()
File "/home/abisulco/.local/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/home/abisulco/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
allow_unreachable=True)  # allow_unreachable flag
File "/home/abisulco/.local/lib/python3.7/site-packages/wandb/wandb_torch.py", line 129, in _callback
self.log_tensor_stats(grad.data, name)
File "/home/abisulco/.local/lib/python3.7/site-packages/wandb/wandb_torch.py", line 101, in log_tensor_stats
flat = tensor.view(-1)
RuntimeError: _th_view is not implemented for type torch.cuda.sparse.FloatTensor

**Comment by anthonytec2** [comment]
class embedding_model(torch.nn.Module):
    def __init__(self, input_dim, embedding_dim):
        super(embedding_model, self).__init__()
        self.emb = embedding_dim
        self.words = torch.nn.Embedding(input_dim, embedding_dim, sparse=True)
        self.context = torch.nn.Embedding(
            input_dim, embedding_dim, sparse=True)
Here is the model should that help:
def forward(self, word, postive_context, negative_context):
        x1 = self.words(word)
        x2 = self.context(postive_context)
        x3 = self.context(negative_context)
        l1 = torch.bmm(x1.view(-1, 1, self.emb), x2.view(-1, self.emb, 1))
        l2 = torch.bmm(x3.view(-1, 1, self.emb),
                       x1.repeat(1, 5).view(-1, self.emb).view(-1, self.emb, 1))
        return torch.sum(torch.nn.functional.logsigmoid(l1))+torch.sum(torch.nn.functional.logsigmoid(-1*l2))

**Comment by raubitsj** [comment]
Thank you for the code snippet.  I have reproduced the problem and am working on a solution.  For now you can disable gradient logging with:
```wandb.watch(embedding_model, log=None)```

**Comment by ariG23498** [comment]
Hey @anthonytec2 did you happen to find a solution to the issue you had mentioned?
The current wandb version is `0.10.11`. It would be great if you could check and reply to this thread. Being dormant for more than a year now, it could be better if we know about the issue and close the thread if it is solved. 
CC: @raubitsj
