### ISSUE TITLE
[Q] how to synchronize the step of images visualized?

### ISSUE THREAD

**Issue by yolkandwhite** [wandb/client#3053]
Hello, I have question about visualizing image with wandb.

I want to visualize the images within the same step

I am using the code below.

```
    fake = wandb.Image(x_fake[0])
    real = wandb.Image(target[0])
    wandb.log({'fake': fake})
    wandb.log({'real': real})
```

but wandb is showing the different step of images.

I want to look in to the images with the same step.

not like 1162, and 1161 (image below)

![스크린샷 2021-12-15 오후 5 57 19](https://user-images.githubusercontent.com/53941554/146289758-d415db9f-1e74-4197-8806-18c89ad8ab48.png)

how can I sync both image with same step??

**Comment by ramit-wandb** [comment]
HI @yolkandwhite,

There are 2 ways you can sync your steps:

```python3
real = wandb.Image(torch.rand(1, 3, 224, 224)) 
fake = wandb.Image(torch.rand(1, 3, 224, 224))

run.log({'real': real, 'fake': fake})
```

Or

```python3
real = wandb.Image(torch.rand(1, 3, 224, 224))
fake = wandb.Image(torch.rand(1, 3, 224, 224))

run.log({'real': real}, commit=False)
run.log({'fake': fake})
```

Either one of these methods above should give you the following result:

<img width="352" alt="Screen Shot 2021-12-16 at 9 25 06 AM" src="https://user-images.githubusercontent.com/93002515/146419922-57b494e8-5441-4508-8e2e-08c216f1ea60.png">
