### ISSUE TITLE
[Q] modify data plotted on charts

### ISSUE THREAD

**Issue by EmanueleFrancazi** [wandb/client#3057]
I have a simulation in which some data are collected during the run:
`wandb.log({'x': x[i],
                           'y': y[i]}) `
In the above example during the run some measures `x[i]` and `y[i]` are computed and for each `i` logged into wandb.
After the run ended I enter into wandb dashboard and I'd like to visualize the chart customizing the axis; for example I want to rescale the data, i.e. visualize, instead of **x** vs **y**, **x/R** vs **y**, where **x** and **y** are the logged data from the simulation and **R** is a generic constant.
I'm aware that **during** the logging stage (during the run) is it possible to specify many possible choises for the x axis but here I want to modify one of them **after** the simulation ends (because for example I don't know the value of **R** and I have to infere it from different data returned from the same simulation).
How can this be done?

**Comment by ramit-wandb** [comment]
Hi @EmanueleFrancazi,

Yes, you can do this using Expressions in your chart. I created a small example to demonstrate:

Once you have logged your `x` and `y` variables (in my case, `y = i` and `x = i**2`), you can then set up an expression in a line chart as shown below to get your desired result.

<img width="1376" alt="Screen Shot 2021-12-16 at 10 08 01 AM" src="https://user-images.githubusercontent.com/93002515/146425735-e246a376-41b3-4a72-b936-b7a6a313f2f4.png">
 
 I hope this helps solve your issue.

**Comment by EmanueleFrancazi** [comment]
Thank's! 
If I have now 2 different simulations where the same measure `y` was logged. Is it possible to apply the chart expression to only  one of the two simulations. 
To rephrase this in term of your above example I have two run; each of them collect `x` and `y`.  `x` and `y` represent the same quantity but in the first simulation we have, for example, `x=i` and `y=i**2`, while in the second one  `x=i` and `y=4*i**2`.
What I want is to plot on the same chart only **x** vs **y** from the first simulation and **x/2** vs **y** from the second one.
Is it possible to apply an expression to only one of the simulations plotted in this way?

**Comment by ramit-wandb** [comment]
Hey @EmanueleFrancazi ,

This is not possible currently. You can run an expression over one kind of metric of all your runs, but I don't think it is possible to single out a run, apply an expression to it, and merge it into another graph.

You can apply the expression on all your metrics, which should give you something close to what you want though:

<img width="380" alt="Screen Shot 2021-12-22 at 3 03 36 PM" src="https://user-images.githubusercontent.com/93002515/147164849-d4a3d0ce-bee8-44b0-8379-206ff23560fc.png">

**Comment by EmanueleFrancazi** [comment]
Thank's @ramit-wandb

**Comment by EmanueleFrancazi** [comment]
I have a last doubt about this: in the above example @ramit-wandb show how to plot in the same chart 2 curves with same x-axis values (**y** variable in the example) and different y-axis expressions (**x** and **x/2.5**). What I really need is the opposite; plot togheter curves with the same y-axis expression but different ones for the x-axis. **Is it possible to do this?**

**Comment by ramit-wandb** [comment]
Hi @EmanueleFrancazi ,

You should be able to change the variables in your expression to render curves between any 2 metrics. You should be able to invert the metrics to get the following graph:

<img width="1361" alt="Screen Shot 2021-12-28 at 1 00 38 PM" src="https://user-images.githubusercontent.com/93002515/147606817-43f7dd47-5015-4cca-aefe-1196d91a24e3.png">

However if your goal was to apply multiple X-Axis Expressions to a single Expression, I don't think that's possible currently.

**Comment by EmanueleFrancazi** [comment]
@ramit-wandb thank's, you had been clear in the past replies; now I'm starting to save variables as tables and try to understand how to customize the charts directly from the vega script. Anyhow I think would be also very practical to have the discussed features available in a more high level (as I wanted to proceed, through the axis' expressions customization); for this reason I asked for the implementation of this feature. Thank you again for your time and explanations

**Comment by ramit-wandb** [comment]
Of course! I'll go ahead and close this request out, and we will follow up on your other issue where you have made a feature request for the same.

**Comment by samuelstevens** [comment]
Is there documentation about which expressions are usable? I would like to add a custom expression using the natural log of a config option: something like `${val/loss} / ${log(config:batch_size)}` but it doesn't seem to work. I tried `Math.log` (like Javascript), `math.log` (like Python) and `ln()` and `log()`.
