### ISSUE TITLE
[Q] progressively growing metric data load..

### ISSUE THREAD

**Issue by Yoonho-Na** [wandb/client#3063]
<img width="453" alt="스크린샷 2021-12-17 오후 3 58 48" src="https://user-images.githubusercontent.com/53941554/146502801-629361b0-52dd-4b71-9fe9-c420e7a93253.png">

I'm having this kind of error. and after few hours it crashes with the wandb backend process shutdown.

Is this something to do with `wandb.watch()` ?

I'm using 4 `watch()` functions with log_freq of 100.

and also I'm visualizing the loss and 3 images via wandb by 100 step.

how can I fix this problem??

**Comment by vanpelt** [comment]
You'll need to remove or reduce the number of watch calls you're making.  They add a lot of data to the payloads and the maximum amount of data we allow is 10MB

**Comment by anmolmann** [comment]
Hi @yolkandwhite, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
