### ISSUE TITLE
[App] Bug: scalar chart shows inaccurate MIN/MAX because it uses only the last logged value

### ISSUE THREAD

**Issue by andreimargeloiu** [wandb/client#3075]
**Describe the bug**
I created a scalar chart that should show the MAX value of a logged value. However, it seems to show the last value of that metric.

Here's the formula from the scalar chart, clearly showing that I selected to show the MAX value.
![CleanShot 2021-12-21 at 21 34 33](https://user-images.githubusercontent.com/18227298/146987429-95153dc2-f601-4516-a735-ae7b054b3f07.png)

However, the MAX value logged in wandb is around 0.46 rather than 0.34. This makes me believe there's a bug that wandb shows the last value in scalar charts.
![CleanShot 2021-12-21 at 21 34 58](https://user-images.githubusercontent.com/18227298/146987472-71ba8604-5b9d-41b9-9f65-32747f41b5ba.png)

I confirm that scalar charts use only the last logged value by showing a MIN/MAX range. The MAX value should be around 85.

![CleanShot 2021-12-21 at 21 38 18](https://user-images.githubusercontent.com/18227298/146987885-3f105b16-c0cb-4515-bb26-45e310ed14d4.png)

![CleanShot 2021-12-21 at 21 39 21](https://user-images.githubusercontent.com/18227298/146987977-f2126e51-4402-4c3d-82e4-90aa3687e646.png)

**Operating System**
 - OS: [e.g. iOS] Macod
 - Browser [e.g. chrome, safari] Microsoft Edge
     - wandb 0.12.9 
     - logs created from the wandb integration with pytorch-lightening 1.5.5
     - python 3.7.9

**Comment by laxels** [comment]
Hey there @andreimargeloiu! This is due to the Scalar Chart only aggregating summary values across multiple runs. It doesn't actually have the functionality to aggregate across a single run's history. For that, you'll need to use [`wandb.define_metric`](https://docs.wandb.ai/guides/track/log#customize-the-summary).

We've edited the UI to prevent this confusion in the future. Sorry about that!

**Comment by andreimargeloiu** [comment]
Thank you for making the changes to the UI. However, they don't seem consistent.

Here I'm having three identical scalar charts, from similar data sources. One scalar chart works fine, while the others don't.

![CleanShot 2021-12-23 at 08 25 11](https://user-images.githubusercontent.com/18227298/147197901-4f9344a8-8ee0-4001-8ec1-85351048c023.png)

![CleanShot 2021-12-23 at 08 27 48](https://user-images.githubusercontent.com/18227298/147198003-82991be2-3f30-4d55-b48d-cfa098df00c6.png)

![CleanShot 2021-12-23 at 08 28 11](https://user-images.githubusercontent.com/18227298/147198029-2ae0d493-0961-4a06-987d-6ccdcceecdd0.png)

![CleanShot 2021-12-23 at 08 28 38](https://user-images.githubusercontent.com/18227298/147198073-fe8d9d88-75e5-481d-bc43-6f9035d1a2ae.png)

**Comment by laxels** [comment]
@andreimargeloiu so sorry for getting back to you so late; I just replied on the other issue you opened about this. Let's keep the discussion there; I'll close this one.
