### ISSUE TITLE
[App] Many features on wandb dashboard are disabled/not available

### ISSUE THREAD

**Issue by Mayur28** [wandb/client#3076]
**Describe the bug**
I have been experiencing several issues in the past few days when using the wandb dashboard. Some of the issues I am facing include:
- Unable to delete an individual run (the 'delete run' option is greyed out)
- When I select multiple runs (either to add tags to these runs or to delete them), the options at the top to tag the runs or to delete the runs are greyed out (do not work).

I have tried logging into the wandb dashboard from different browsers but the problem persists.

**To Reproduce**
Try to select multiple runs (on the tables page of the workspace) to add tags or to delete runs
OR
Select a single run, go to the info page, and attempt to delete the run (the confirm delete run option is greyed out for me)

**Expected behavior**
I should be able to delete a single run, or to perform actions on multiple runs on the tables page of the workspace (such as adding tags or deleting runs)

**Screenshots**
![image](https://user-images.githubusercontent.com/26574827/147062580-af5f543f-08d1-42e2-aa4a-9b7151e8a01b.png)
![InkedScreenshot-2021-12-21-224411_LI](https://user-images.githubusercontent.com/26574827/147062774-f1b16844-3cfb-4986-8899-529a3220477f.jpg)

**Operating System**
 - OS: Windows 10
 - Browser Firefox and Chrome
 - wandb version: 0.12.7

**Comment by armanhar** [comment]
Hey there, this is a known issue that we are working on right now. I'll notify you once the issue is resolved.

**Comment by Mayur28** [comment]
Hi,

The issue seems to be resolved, thanks!
