### ISSUE TITLE
[Q] Sharing results with WandB in double-blind review

### ISSUE THREAD

**Issue by nikvaessen** [wandb/client#3078]
I would like to share training runs with WandB in a paper submission which will be reviewed double blind. I see a few issues which I cannot easily circumvent: 

1. 'wandb-metadata.json' contains the 'username', 'host' and 'executable` keys, which can easily leak identity
2. errors/warnings in the 'log' can leak system paths, which can contain your usrname. (This can be disabled in the code, though)
3. In the overview the author's profile is visible, which can only be circumvented by making a new fresh account?

Do you have any suggested solutions to the issues above, and maybe things I've missed on the feasibility of sharing results in a double-blind review?

**Comment by vanpelt** [comment]
Hey @nikvaessen the simplest way to share results ensuring none of this information is exposed is to use private projects and then [create a report](https://docs.wandb.ai/guides/reports) with the results you want to share.  You can then [export ](https://docs.wandb.ai/guides/reports) this report as either PDF or LaTeX.  Do you think that would work for your use case?
