### ISSUE TITLE
PReLU has no len error in WandbCallback

### ISSUE THREAD

**Issue by cottrell** [wandb/client#308]
In [3]: tf.__version__
Out[3]: '1.14.1-dev20190312'

In [4]: tf.keras.__version__
Out[4]: '2.2.4-tf'

~/anaconda3/envs/gi/lib/python3.6/site-packages/wandb/keras/__init__.py in set_model(self, model)
    110     def set_model(self, model):
    111         self.model = model
--> 112         wandb.run.summary['graph'] = wandb.Graph.from_keras(self.model)
    113
    114     def on_epoch_end(self, epoch, logs={}):

~/anaconda3/envs/gi/lib/python3.6/site-packages/wandb/data_types.py in from_keras(cls, model)
    125             nodes = []
    126             for v in nodes_by_depth:
--> 127                 if (len(v) > 1) or (len(v) == 1 and len(v[0].inbound_layers) > 1):
    128                     # if the model has multiple nodes
    129                     # or if the nodes have multiple inbound_layers

TypeError: object of type 'PReLU' has no len()

**Comment by lukas** [comment]
Hi - I'm having trouble reproducing your bug.  Could you run model.summary() and paste in the result?  Or attach your training script?

**Comment by cottrell** [comment]
I'll pop on slack or somewhere with DM.

**Comment by vanpelt** [comment]
Fixed in 0.8.0
