### ISSUE TITLE
[Q] How can I configure only see best values on run table?

### ISSUE THREAD

**Issue by JihwanEom** [wandb/client#3086]
Hello, thank you for your amazing works. 

When I train the model, wandb logger tracks the model performance and update on run table. But I can confirm only **latest** values from the log.

How can I see **best** values from logs on run table? 

Thank you.

**Comment by JihwanEom** [comment]
Hello, thank you for your kind answer. 

But I wanna to see the best values **overall table, not only specified column.** With your code, I should update best variables manually.. No way for this?

**Comment by vanpelt** [comment]
@JihwanEom you can programmatically configure metrics to store the max or min value for individual runs with [define_metric](https://docs.wandb.ai/guides/track/log#customize-axes-and-summaries-with-define_metric).  To view the max across all runs in a table just sort by the column or columns you care about.
