### ISSUE TITLE
[Q] Handling runs

### ISSUE THREAD

**Issue by ManiadisG** [wandb/client#3104]
Is there a way to do the following?

- Download existing runs and save them locally.
- Reupload them in their original project (or in others).
- Copy/duplicate existing runs in the cloud (e.g. for backup reasons).

Many thanks in advance.

**Comment by ramit-wandb** [comment]
Hi @ManiadisG,

- Run data is automatically stored locally in the directory in which you ran your code, in a directory called `wandb`. 
- Yes, you can use `wandb sync` to upload your run data to the cloud. You can read more about it [here](https://docs.wandb.ai/ref/cli/wandb-sync).
- Yes, you should be able to store the `wandb` folder wherever you need for backup, and then calling `wandb sync` will upload the run files to W&B.

Thanks,
Ramit

**Comment by ManiadisG** [comment]
Thank you for your reply @ramit-wandb.

You covered my 2nd and 3rd questions.

Regarding the 1st, I was refering to the case where I do not have the locally stored directory (e.g. when working from different machines). Essentially I was wondering if it is possible to download a run's data from the cloud, not each file individually (as in `wandb.restore`) but the entire folder as it is saved locally during a run.

**Comment by ramit-wandb** [comment]
Hi @ManiadisG, 

I apologize about that. As it stands right now, you can not download your complete run data from W&B in the way you desire. We generate a `run-XYZ.wandb` file which contains all your run data (other than files and logs), and this gets translated to your run workspace, but we do not store the serialized `.wandb` object on the cloud.

If you want to back up your runs, I think the best way right now would be to store your `wandb` folder from your local machine.

Thanks,
Ramit

**Comment by ManiadisG** [comment]
Thank you very much for your help @ramit-wandb!

That covers my questions and I will close the issue.
