### ISSUE TITLE
UsageError: Line magic function `%%wandb` not found .  (in Jupyter Lab)

### ISSUE THREAD

**Issue by cpoptic** [wandb/client#311]
* Weights and Biases version: '0.7.2'
* Python version: 3.6
* Operating System: Mac

### Description

In Jupyter Lab, I have a training loop, and it is preceeded by the magic function %%wandb

### What I Did
According to   m
> Call `%%wandb` in the cell containing your training loop to display live results.
```
import wandb
wandb.init()

%%wandb
def train_model(params):
....
```

> UsageError:  Line magic function `%%wandb` not found.

What is needed to display live results while training?  And why is %%wandb not found even though wandb is installed and imported

**Comment by vanpelt** [comment]
Hey @cpoptic, `%%wandb` is cell magic so it has to be called at the beginning of a cell.

**Comment by vanpelt** [comment]
I can create a line magic that at least prints a warning message in this case, will keep this open.

**Comment by cpoptic** [comment]
Ah thanks; I had a single comment line above the   `%%wandb`  line in the cell. 

Put the cell magic line before the comment and it's fine now.
