### ISSUE TITLE
[CLI] Syncing all offline runs using `wandb sync --sync-all`

### ISSUE THREAD

**Issue by zaccharieramzi** [wandb/client#3111]
**Description**
When I run `wandb sync --sync-all --include-synced` I get the following error: `wandb: ERROR Nothing to sync.`.

**Wandb features**
I am using `wandb sync` in the CLI, and `wandb.init` as well as the `WandbCallback` for keras training.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
Unfortunately I can't link the script and I don't have a minimal reproducible example just yet.
2. Describe what we have to do in order to trigger the issue
I guess just running wandb offline and trying `wandb sync --sync-all --include-synced` in the runs directory.
3. Add a zip file with the run folder 
It's more than 1 run: should I still add it here?
One of the runs' logs are available [here](https://github.com/wandb/client/issues/1297#issuecomment-1005754497).

**Environment**
- OS: RedHat version 8.1
- Python Version: 3.7.9

**Misc**
I had another error with offline post-sync, I reported it [here](https://github.com/wandb/client/issues/1297#issuecomment-1004936577), and managed to solve it by basically repeatedly using `wandb sync`, but it didn't work with `wandb sync --sync-all`.

**Comment by armanhar** [comment]
Hey there, if you can add one run folder that caused the error that would help us reproduce the issue.

**Comment by armanhar** [comment]
It seems like the issue is with the .wandb file of the run. That's why I'm asking for the directory.

**Comment by zaccharieramzi** [comment]
ah ok sure, I have some problems with my vpn atm, but I will upload it asap.

**Comment by zaccharieramzi** [comment]
[wandb_sync_all_error.zip](https://github.com/wandb/client/files/7829288/wandb_sync_all_error.zip)
@armanhar  here is a full folder containing many runs that cause the `--sync-all` problem.

**Comment by anmolmann** [comment]
@zaccharieramzi , could you also add the flag `--include-offline` when syncing all offline runs? The cmd should be: `wandb sync --include-synced --include-offline --sync-all`. The reason we need to include this flag is that in offline mode all your runs have a prefix `offline` (you can check these out in the wandb dir or the zip file you shared above). Therefore, the [code at this line](https://github.com/wandb/client/blob/1a83a85f79e95b5f2de33254365586f00630c80e/wandb/sync/sync.py#L366) suggests that if this flag is provided, all runs in `offline-run-*` will be included when syncing to W&B.

**Comment by zaccharieramzi** [comment]
No even with this command, I am still getting the error: `wandb: ERROR Nothing to sync.`.

**Comment by anmolmann** [comment]
I see, I just tried this cmd and it worked for me: `wandb sync --include-offline /wandb/offline-*`. This should sync all offline runs for you.

**Comment by anmolmann** [comment]
@zaccharieramzi, unfortunately today you can not re-use deleted run ids in a project. We provide a helper method `wandb.util.generate_id()` which can be used to generate a random set of characters to append to your experiment name.  
Here's a quick way to generate a new id: `python -c "import wandb; print(wandb.util.generate_id())"`
This way you can re-upload the data from your old run under a new ID by passing the --id argument to `wandb sync`. For ex: you can try to sync to a new `run_id` using `wandb sync --id new_run_id [PATH_TO_THE_OLD_RUN]`. 

Note that if you have an existing run that isn't deleted which you want to append data to you should see the [resuming documentation](https://docs.wandb.ai/guides/track/advanced/resuming).

**Comment by zaccharieramzi** [comment]
In my case I basically have a directory on my server where there are a lot of runs, some of them I deleted in the cloud with the web UI.
It's not practical for me to have to also delete them on my server if I want to sync all the remaining ones.

**Comment by anmolmann** [comment]
In this case, even if the runs were deleted in cloud you won't be reuse the same run ID. Hence, the reason I recommended the above [solution](https://github.com/wandb/client/issues/3111#issuecomment-1016939410). Please let me know if you still encounter any issues implementing this solution (syncing old runs to new run IDs).

**Comment by zaccharieramzi** [comment]
I understand the solution, but I don't want to have to care about it, hence I use [this script](https://github.com/zaccharieramzi/submission-scripts/blob/master/jean_zay/syncall-wandb) which applies a sync to all the offline runs one by one every 5 minutes.

I also don't want to have to do a local clean up.

But I understand now why the issue I raised happens, so I am closing this, but I am fine with my current solution.

**Comment by klieret** [comment]
In case someone else stumbles on this thread or on similar offline synchronization issues: I recently wrote [a small package](https://github.com/klieret/wandb-offline-sync-hook) that allows to solve this elegantly by having the compute nodes trigger incremental synchronizations of the right directories using the internet connection of the head node.

**Comment by tongyx361** [comment]
> 

Note: Currently (2023-09-03), commands like `wandb sync --project <project_name> <run_path>` are able to reuse the run ID (at least in my case).
