### ISSUE TITLE
[Q] How to Organize simulations keeping them apart on the chart

### ISSUE THREAD

**Issue by EmanueleFrancazi** [wandb/client#3124]
Hi,
Inside my projected to organize my simulations I divided them according to their` job type`; for example one of the `job type ` is "evaluation", where I perform small simulation to find the optimal hyper-parameters.
Into this `job type ` I have one simulation for each combination of hyper-parameters' values.
 I'd like to visualize charts with each curve associated to an individual combinations of values (not ` job type`'s grouping ); if I remove from the grouping option ` job type` I'll automatically loose also the structure on the simulations' list, getting a messy list of simulations' names. 
How can I disentangle the chart's grouping keeping a well structured list of simulations?

**Comment by armanhar** [comment]
Hey Emanuele, if you don't want to mess up the grouping in the workspace I'd suggest creating a report. In there you can group the runs by all the hyperparameters. If there are runs with the same combination then they will and up in the same group. An easier solution would be to append tags to runs based on the run data like [this](https://docs.wandb.ai/ref/app/features/tags#how-to-add-tags).

**Comment by EmanueleFrancazi** [comment]
Thank you @armanhar for your comment! 
So by putting a tag on the run I will be able to divide the list of simulations in the dashboard according to the tag and, in the same time, exclude the tag from the chart grouping (i.e. 2 simulations with the same tag will be visualized as 2 independent curves and not averaged togheter), is it right?

**Comment by EmanueleFrancazi** [comment]
Thank you for the suggestion; is there a guide/tutorial that explain how to create such a report and reproduce your idea?

**Comment by EmanueleFrancazi** [comment]
> Thank you for the suggestion; is there a guide/tutorial that explain how to create such a report and reproduce your idea?

Just for future users having the same doubt there is this video that you can use as introduction:
https://youtu.be/2xeJIv_K_eI
