### ISSUE TITLE
wandb.plot.line does not work

### ISSUE THREAD

**Issue by farhad-dalirani** [wandb/client#3125]
Hello,

I used this example that was provided by WandB. However, in the web interface, it just shows a table instead of a figure.
```
data = [[i, random.random() + math.sin(i / 10)] for i in range(100)]
        table = wandb.Table(data=data, columns=["step", "height"])
        wandb.log({'line-plot1': wandb.plot.line(table, "step", "height")})
```
![Screenshot from 2022-01-08 20-56-23](https://user-images.githubusercontent.com/65308831/148666224-469bc1ff-eb16-4d21-a5ba-0b440c9dd7fc.png)

Also, I have the same problem with other kind of figure and charts that use a table.

**Comment by armanhar** [comment]
Hey there, can you send the link to the run? Also which wandb version are you using?

**Comment by farhad-dalirani** [comment]
Thank you, it was inside the custom charts.
