### ISSUE TITLE
Confision matrix does not work, it just shows a table[Q]

### ISSUE THREAD

**Issue by farhad-dalirani** [wandb/client#3126]
Hello,

I used this code to create a confusion matrix:
```

# confusion matrix
        wandb.log({"confusion-matrix-test": wandb.plot.confusion_matrix(
            probs=None,
            y_true=all_gt, preds=all_pre,
            class_names=classes_names)})
```

However, Wanda's website only shows a table instead of the confusion matrix. This is a screenshot from the issue:
![Screenshot from 2022-01-09 20-58-35](https://user-images.githubusercontent.com/65308831/148710744-d9989fd6-1832-409c-9108-738a2aba64b6.png)

**Comment by armanhar** [comment]
Hey there, if you open the Custom Charts section the confusion matrix should be there.

**Comment by farhad-dalirani** [comment]
Thank you, it was inside the custom charts.
