### ISSUE TITLE
[Feature] Dark theme for Wandb

### ISSUE THREAD

**Issue by yanghoonkim** [wandb/client#3127]
Hi, I want to know if there is any plan for dark theme.

**Comment by armanhar** [comment]
Hey there, if you put the word "night" in your bio you'll activate the dark mode. Bear in mind that this is not a fully supported feature yet. We are planning to add a full fledged dark mode soon.

**Comment by yanghoonkim** [comment]
@armanhar It looks cool enough now! Thanks!

**Comment by mariomeissner** [comment]
Looking forward to the full release of night mode. Please also consider having the "system" option, so that it follows whatever the system-wide setting is!

**Comment by drscotthawley** [comment]
@armanhar Used to be that removing "night" from the profile text restored normal theme, but now I'm apparently locked into Dark theme even without the word "night".   Do we need to put it something like "day" to switch back?

**Comment by yanghoonkim** [comment]
@drscotthawley I think the night mode in the beta features is activated. check out the beta features in  the user settings

**Comment by aced125** [comment]
This doesn't work for me (adding night to bio)

**Comment by theProcrastinatr** [comment]
What about docs.wandb.ai? Does it support night mode? I'm struggling to find if its there, any suggestion would be appreciated.

**Comment by kerkathy** [comment]
just found that ctrl+M does the trick FYI
