### ISSUE TITLE
Cannot access `history` or `scan_history` from `Run` object. 

### ISSUE THREAD

**Issue by TiansuYu** [wandb/client#3135]
**Description**
I am trying to find the history connected to a particular run but run into this issue. As far as I understand, if one wants to find history, must use the `wandb.Api().run` in order to use method `history` or `scan_history`. 

But through the following code, I run into issue `TypeError: 'History' object is not callable` or `AttributeError: 'Run' object has no attribute 'scan_history'` while calling `run.history` and `run.scan_history` respectively.

```
import wandb
import uuid 

PROJ = "some-test"
ID = f"{PROJ}_{uuid.uuid4()}"
run = wandb.init(project=PROJ, id=ID)
for i in range(1000):
    wandb.log({"dummy_metric": i})
print(run.scan_history(keys=["dummy_metric"]))
```

Browsing the doc and source code, I dont not find any particular reason why my approach does not work. Therefore I want to ask here: is this behavior simply a misusage from my side or something more deliberate?

**Comment by armanhar** [comment]
Hey there. You are right, you should use wandb.Api().run once the run is finished. The code you posted doesn't use that.

**Comment by TiansuYu** [comment]
Thx for pointing that out. However, I find another related problem. In offline mode `wandb.Api().run("<entity>/<project>/<run_id>") could not find the run, yet the same identifier can work for online mode. And I saw in call stack there is some http calls being made, which is not right for a "offline mode".

**Comment by vanpelt** [comment]
@TiansuYu The public api does not work in offline mode, it requires a connection to a wandb server.  offline mode is only meant for logging data with `wandb.log` and `wandb.init`.
