### ISSUE TITLE
[CLI] Latest versions of client and wandb/local throws SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by Multihuntr** [wandb/client#3144]
**Description**
The latest versions of the `wandb` client and the `wandb/local` aren't working together for me. When you try to connect, you get a `SSL: WRONG_VERSION_NUMBER` after providing the api key.

**How to reproduce**
1. `docker build -t test_wandb .`: Build the following Dockerfile
```dockerfile
FROM python:3.9
RUN pip install wandb
```
2. `docker pull wandb/local`: Pull the latest wandb/local
3. `docker run --rm -d -p 8080:8080 --name wandb-local wandb/local`: Start the `wandb/local` server without mounting a volume (so you know it's fresh)
4. Authorize/Setup server:
    1. Visit "https://localhost:8080"
    2. Create initial account
    3. Visit "https://deploy.wandb.ai/" to get your licence
    4. Enter licence into "system settings"
    5. Visit "https://localhost:8080/authorize" to get the api key

5. Try to connect via commandline:
```bash
WANDB_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' wandb-local)
docker run --rm -it -e WANDB_BASE_URL="https://$WANDB_IP:8080" tst_wandb \
    python3 -c "import wandb; wandb.init(project='debug', id=wandb.util.generate_id(), name='just_init')"
```
6. Provide api key

This is what it looks like when you've done all that:
```
me@mine:~/code/testing/wandb_ssl$ docker run --rm -d -p 8080:8080 --name wandb-local wandb/local
e72b673f923d849dd358d7507c7d8e189e51ecfd3f82396ef665517aed48fc17
me@mine:~/code/testing/wandb_ssl$ WANDB_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' wandb-local)
me@mine:~/code/testing/wandb_ssl$ docker run --rm -it -e WANDB_BASE_URL="https://$WANDB_IP:8080" tst_wandb \
>     python3 -c "import wandb; wandb.init(project='debug', id=wandb.util.generate_id(), name='just_init')"
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 2
wandb: You chose 'Use an existing W&B account'
wandb: You can find your API key in your browser here: https://172.17.0.2:8080/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: Appending key for 172.17.0.2 to your netrc file: /root/.netrc
Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

```

**Environment**
- OS: Ubuntu 20.04
- Environment: python
- Python Version: 3.9

**Extra context**
I was using wandb==0.12.7 previously, and it was working fine. I then accidentally upgraded to 0.12.9, and this error occurred. So I installed 0.12.7 again, but the error is still there. I'm not sure if 0.12.7 has changed somehow? I know that it was working, and I didn't (initially) update the server, so I assume it's the client, or I'm missing something horrifically obvious. One of the two.

**Comment by armanhar** [comment]
Hey Brandon, thanks for reporting this. I'll share the issue with the team and get back to you.

**Comment by Multihuntr** [comment]
It was caused by an obvious error. My apologies.

This error is because I am using `https://`. I should instead have used `http://`.

**Comment by vanpelt** [comment]
@Multihuntr yep, you can use https but you would need to configure a load balancer infront of the installation.  Most of our customers use kubernetes to deploy this into production and can leverate k8s ingress records to terminate SSL.
