### ISSUE TITLE
[Q] Compare runs across different job types via the API

### ISSUE THREAD

**Issue by phrasenmaeher** [wandb/client#3152]
For a project, I have a structure similar to the one the grouping [tutorial](https://docs.wandb.ai/guides/track/advanced/grouping#distributed-training-with-grouping), where runs are grouped together.
Within each group, I have several `job_types`, such as `eval` or `baseline`.
Usually, within these types, only one run is stored.

What I am looking for is a way to "iterate" over this structure like so:

1. Select a group
2. Within this group:
     1. Pull data from various job types
     2. Compare the collected data
3. Proceed to the next group

So far, I do not want to compare between different groups,  only within a group I want to compare between different `job_types`'s runs.

This snippet should give a further idea of what I want to accomplish:

```
import wandb

api = wandb.Api()

#both runs below are from the same group
runA = api.run("user_name/project_name/runs/123456K")  # eval run, from within eval job type
runB = api.run("user_name/project_name/runs/82921L7")  # baseline, from within baseline job type

compare_two_runs(runA, runB) # pull data from the runs; do actual computation ...
```

What it misses is a way to iterate over the groups, and then find the runs within a `job_type`.
How do I best go about this? Doing this manually via the web dashboard is prohibitive, I have a prohibitively large number of groups and runs within them, and more are to be added.

**Comment by armanhar** [comment]
Hey Pascal, the run object that is returned using the public API has job_type and group attributes. So you should be able to do the filtering in the script.

```
runs = api.runs("entity_name/project_name")
for run in runs:
  print(run.job_type, run.group_name)
```

**Comment by phrasenmaeher** [comment]
Thanks @armanhar for pointing me to this simple solution! It works, and I have discovered many additional helpful attributes!

This is what I used in the end:

```
for run in runs:
  print(run.job_type, run.group) #it's just group
```

**Comment by armanhar** [comment]
@phrasenmaeher glad to hear it worked!
