### ISSUE TITLE
[Feature] Only begin logging after n steps or epoch

### ISSUE THREAD

**Issue by ed-fish** [wandb/client#3157]
If my model fails before the first epoch I have to go and delete the run from the W&B dashboard. 

It would be great if there was an arg for only log after 1 successful epoch or n steps. Or even some clean up options on a failed run E.g if you kill the run an option asking.. "delete the log in W&B?"

Perhaps this feature is already possible in the API but I haven't been able to find it.

**Comment by ramit-wandb** [comment]
Hi @ed-fish,

Thanks for your feature request! I'll ticket this for our engineering team to review, and I'll keep you updated on its status.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hey @ed-fish,

I wrote a little script for you to programmatically delete crashed runs from our API:

```python3
entity = 'entity_name'
project = 'project_name'

api = wandb.Api()

runs = api.runs(f'{entity}/{project}')

for run in runs:
    if run.state == 'crashed':
        print(f'Deleting {run.id}')
        run.delete()
```

This should be able to delete your runs programmatically. Please refer to our docs on [API Run Objects](https://docs.wandb.ai/ref/python/public-api/run) in case you want to make more complicated expressions to delete your runs.

Thanks,
Ramit

**Comment by ed-fish** [comment]
That's great thank you! 

Ed
