### ISSUE TITLE
[Q] How to use API to edit `job_type`? 

### ISSUE THREAD

**Issue by Wilann** [wandb/client#3160]
Using a script similar to the one below, I can edit group names, but not job types. I also see that `job_type` is not listed in the [`wandb.Run` API](https://docs.wandb.ai/ref/python/run). Is it possible with the API, and if so, how? 
```
api = wandb.Api()
runs = api.runs(path="{}/{}".format(wandb_username, project_name))

for run in runs:
    run.job_type = new_job
    run.update()
```

**Comment by Wilann** [comment]
Hi Leslie, thank you for the quick reply. My project currently contains multiple tasks, models, and number of outputs for each model. I'm currently using:
- Groups to differentiate between tasks (same dataset, but different labels) 
- Tags to differentiate models 
- And wanted to use job type for number of outputs (2, 3, 5, etc.) 

Previously I used tags for everything, but that resulted in too many tags. I've considered using groups to differentiate between task and number of outputs (eg. Task 1 - 2 outputs, Task 1 - 3 outputs, Task 2 - 2 outputs, etc.), but thought I should ask if there was a way to change job type first.

**Comment by Wilann** [comment]
Hi, sorry for the late reply. Thank you for your advice on using tags instead. I have considered that, but quite liked the min-max range for the graphs when grouping by "Group" and "Job Type". As edit job type isn't possible, I'll stick to using tags for now.

**Comment by miccio-dk** [comment]
Is there a timeline for implementing editable job_type? 
Tags and notes are not as useful as the job_type field because I cannot sort or group by them. 
It seems quite strange that editing the job type is prevented.
Alternatively, is there a way to upload an a new run (with the correct job_type in place) containing all the data from an existing run?

Thanks.
