### ISSUE TITLE
[App] BUG: wandb lost data while training

### ISSUE THREAD

**Issue by kevinlee325** [wandb/client#3164]
**Describe the bug**
I trained my model in pycharm. The output information in pycharm shows that 81 epochs has been trained. However,  I can only find the data of 13 epochs in wandb. 

**Screenshots**
I can only find the first 13 epochs in wandb
![QQ截图20220124094900](https://user-images.githubusercontent.com/82894448/150710560-28d6568a-380c-4b7d-b677-17b3daf24f4a.jpg)
The two screenshots below are from pycharm
![2022-01-24 09-57-52屏幕截图](https://user-images.githubusercontent.com/82894448/150710636-1f70c61c-91c0-480b-8015-2c6dcafe28d6.png)
![2022-01-24 10-00-36屏幕截图](https://user-images.githubusercontent.com/82894448/150710650-6b3e5734-6ecd-456c-a50d-e0ada934986f.png)

**Operating System**
 - OS: ubuntu 18.04.4
 - Browser: firefox

**Additional context**
Maybe it is caused by internet problems? If so, how do I upload the missing training data to wandb?

**Comment by nate-wandb** [comment]
Hi @kevinlee325,
Could you try using wandb sync? [Here](https://docs.wandb.ai/ref/cli/wandb-sync) is some information on how to use it.

Also could you possibly share your debug.log and debug-internal.log files so we can look into why the files didn't get uploaded?

Thank you,

Nate

**Comment by kevinlee325** [comment]
Hi @nate-wandb :
I tried `wandb sync` in terminal:
![QQ截图20220125092547](https://user-images.githubusercontent.com/82894448/150893575-dbd5c422-2ac9-4018-a81b-51cf33292600.jpg)
However, I failed to wait for this command to finish and closed the terminal. While waiting, I checked the Run page in wandb.ai and it seemed to have no updates.  

Here is the debug.log:
[debug.log](https://github.com/wandb/client/files/7929971/debug.log)

The debug-internal.log is to big. Is it necessary to upload the whole file? or just a part of the file and which part?

Thanks for your help.

Kevin

**Comment by nate-wandb** [comment]
Hi @kevinlee325,
Could you try running wand sync again but let it finish?  It may take a second as it is only a single threaded process.  

Could you also share what the run status is on the Run Overview page on the W&B UI? It should be either logged as finished, failed, or crashed.

Also if you're comfortable sharing the link to your workspace we can look into it from our side.

Thank you, 
Nate

**Comment by kevinlee325** [comment]
Hi @nate-wandb:

The run status is 'killed'.  It is interesting that the missing data has been uploaded when I check the status just few seconds ago.

Three days ago, after stopping the training several hours later,  I checked the W&B UI and I saw there was a green circle behind the name, whcih indicated something still active. Is there a possibility that wandb keeps uploading data although the training is stopped? 

I guess there was a network error while training and wandb keeps trying to upload data. And the amount of data is huge, so it keeps doing it for two days? I stopped the trainning by clicking the stop button in pycharm. Can't it stops wandb?

Thanks for your help.

Kevin

**Comment by nate-wandb** [comment]
Hi @kevinlee325,
Glad to hear that the data eventually showed up. If you keyboard interrupt the training script W&B will usually still try to sync but what I would guess is that it was just a very large amount of data that was being uploaded or as you said there was a network error. 

It also may have been that using the stop button in Pycharm killed the W&B process as well. I'd recommend in the future using the stop button on the W&B UI if you need to kill a run early. 

Also [here](https://docs.wandb.ai/guides/track/limits) is some info on best practices for logging to help make sure you don't get throttled during the upload process which could have also been the cause. 

Let me know if that helps or if you want clarification on any of this.

Thank you,
Nate

**Comment by kevinlee325** [comment]
Hi @nate-wandb:

Thank you for helping me. I will follow the guide for logging. If it happens again, I will also try running wand sync and let it finish.

Thanks for your help and advice.

Kevin
