### ISSUE TITLE
[App] Disabled scrolling for markdown on full screen view

### ISSUE THREAD

**Issue by digantamisra98** [wandb/client#3169]
**Describe the bug**
The scrolling for a markdown panel works in default view however there is no scrolling for full screen view.

It only happens on my desktop while viewing on laptop does allow scrolling. 
Desktop viewing details:
screen resolution: 2560x1440 pixels. The aspect ratio is 16:9.
browser's inner resolution: 2560x1247 pixels

Pls fix

**Comment by ramit-wandb** [comment]
Hi @digantamisra98,

Could you share a link to the page where you experience this issue?

Thanks,
Ramit

**Comment by digantamisra98** [comment]
@ramit-wandb I can send the link on maybe email? It's a private project and I won't be comfortable sharing it here

**Comment by ramit-wandb** [comment]
@digantamisra98 Absolutely! You can email us at support@wandb.com
