### ISSUE TITLE
[Q] Documentation for custom sweep logic

### ISSUE THREAD

**Issue by BearNinja123** [wandb/client#3172]
On the [Sweeps page](https://wandb.ai/site/sweeps), it says that a user can provide custom logic in a sweep, yet I couldn't quite find any documentation that allows the logic that I want to run in my sweep natively. Is there currently a way to do this in W&B?

Essentially, what I want to do is to change a config's hyperparameters based on others. For example, if a config allows a network to contain up to 4 layers and each layer is initialized with a random neuron count, but a specific run only contains 2 layers, reassign the neuron counts for the 3rd and 4th layer to be 'N/A' since they are not involved in the model construction.

**Comment by aidanjdonohue** [comment]
Hi @BearNinja123 there isn't really comprehensive documentation for supporting custom sweeps. A more public facing customizable API with better documentation is something we might provide in the future but is not something we're focusing on at the moment. However, the [code for sweeps](https://github.com/wandb/sweeps) is open source so feel free to extend the functionality how you see fit. 

As for your specific example, support for sweeping over conditional parameters is something that we will likely implement in the future; however, in the meantime, enumerating the permutations will be an effective, albeit intelligent, solution.
