### ISSUE TITLE
[CLI] GCS handler uses backslash as path separator under windows

### ISSUE THREAD

**Issue by CorentinJ** [wandb/client#3177]
**Description**
When adding artifact references to a GCS bucket, paths to the individual files within the bucket will be constructed using `os.path.join`, creating backslashes under windows instead of forward slashes. This causes problems further down the line, as GCS does not recognize backslashes and thus fails to identify the files.

**Wandb features**
I am using code presented in [this article](https://wandb.ai/stacey/artifacts/reports/Tracking-Artifacts-by-Reference--Vmlldzo1NDMwOTE).

**How to reproduce**
1. Run on Windows
2. Have a google bucket containing a directory with some files.
3. Run the following code:
```python3
import wandb

run = wandb.init(project="debug", job_type="upload")
# path to my remote data directory in Google Cloud Storage
bucket = "gs://<bucket_name>/<dir_name>"
# create a regular artifact
dataset_at = wandb.Artifact("debug", type="raw_data")
# creates a checksum for each file and adds a reference to the bucket
# instead of uploading all of the contents
dataset_at.add_reference(bucket)
run.log_artifact(dataset_at)
```
4. Check the artifact files on wandb.ai, they will have filepaths of the form `gs://<bucket_name>/<dir_name>\<fname>`

**Possible fix**
I solved the issue on my end by replacing all instances of `os.path.join` in [this method](https://github.com/wandb/client/blob/master/wandb/sdk/wandb_artifacts.py#L1632-L1653) to a concat with a forward slash. It might have unwanted side effects.

**Environment**
- OS: Windows 10 Home ver 1803
- Environment: Desktop
- Python Version: 3.7.5
- Wandb version: wandb==0.12.9

**Comment by ramit-wandb** [comment]
Hi @CorentinJ!

Thanks for pointing this out. I have created a ticket for our engineering team about this, and we should have a fix out for this soon. I'll let you know as soon as I have some news on the status of this ticket.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @CorentinJ!

This issue should now be resolved in our latest release of our SDK : `wandb 0.12.16`. Please let us know if you still find issues with this!

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Closing this issue out, if you have any other concerns please feel free to reopen this issue and we can continue the discussion!
