### ISSUE TITLE
[CLI] When run sweep on my python code, entity and project is not loaded from config

### ISSUE THREAD

**Issue by Shunpoco** [wandb/client#3186]
**Description**
When I wanted to run sweep on my Python code, wandb.sweep() didn't parse both `entity` and `project` values neither in my yaml file nor in config dictionary. And finally, its project became `uncategorized`.
[The document](https://docs.wandb.ai/guides/sweeps/configuration#structure-of-the-sweep-configuration) said that we can set `entity` and `project` in a configuration, so wandb.sweep() method also should parse the values.

**Wandb features**
wandb.sweep()

**How to reproduce**
https://github.com/Shunpoco/wandb-reproduce-sweep

**Environment**
- OS: Ubuntu 20.04
- Environment: Local (Both using Python directory and Poetry)
- Python Version: 3.9.0

**Comment by aidanjdonohue** [comment]
Hi @Shunpoco , my apologies that the docs are bit confusing. You need to also set the `entity` and `project` kwargs for `wandb.agent()`

https://docs.wandb.ai/ref/python/agent

**Comment by Shunpoco** [comment]
Hi @aidanjdonohue ,
Thank you for your quick response!

Now I understand that wandb.sweep() has `entity` and `project` as kwargs and I also understand that wandb.agent() also has them.

However, when I tried to run sweep through CLI command (e.g., `$ wandb sweep sweep_config.yaml`), the command can parse both `entity` and `project` in the config file. So if we set the values in our config files, we don't have to use options `--project` and `--entity`. I think it is better that the ways to fetch the values both on `wandb sweep` and on `wandb.sweep()` are synchronized as much as possible for easy to understand and easy to use.
So in my opinion, wandb.sweep() should parse `entity` and `project` in its config dictionary.
If you have enough time, I want to know your opinion.

**Comment by aidanjdonohue** [comment]
Hi @Shunpoco , I agree with you in principle. I believe the redundant behaviour was implemented to account for the different challenges in launching sweeps from the command line and from code from both scripts and notebook environments. Let me chat with some other folks on the client team and see if this is something that we could clean up moving forward.

**Comment by Shunpoco** [comment]
Thanks! I will wait for your discussion!

**Comment by aidanjdonohue** [comment]
Hi @Shunpoco , my apologies for the delay. The reason why we have this implemented the way that we do is actually to keep wandb related configurations separate from hyper parameter tuning configs. We can definitely be more clear about this in our documentation but this is likely a practice that we will keep in place.
