### ISSUE TITLE
[CLI] file data was not synced

### ISSUE THREAD

**Issue by Crayon-new** [wandb/client#3208]
**Description**
When I use sweeps, the program sometimes failed.
output in terminal:
```
FileExistsError: [Errno 17] File exists: '/home/wandb/run-20220203_155210-r0qhkwh9/run-r0qhkwh9.wandb'                                                      
wandb: ERROR Internal wandb error: file data was not synced
```
It is occasional. Can anyone help me?

**Wandb features**
What lines of wandb code are you using? This could be wandb.init(), wandb.log(), or features like the Keras callback, the Hugging Face integration, or PyTorch Lightning integration, for example.

**How to reproduce**
1. wandb sweep yaml
3. wandb agent sweep-id

**Environment**
- OS: Ubuntu 18.04
- Python Version: 3.7.11

**Comment by Crayon-new** [comment]
Can anyone help me?

**Comment by Crayon-new** [comment]
Is it because I use distributed training?

**Comment by ramit-wandb** [comment]
Hi @Crayon-new,

Based on this error, it seems like you are making multiple `wandb.init()` calls in parallel to the same `id`. Each call to `wandb.init()` must have a unique ID.

**Comment by Crayon-new** [comment]
> Hi @Crayon-new,
> 
> Based on this error, it seems like you are making multiple `wandb.init()` calls in parallel to the same `id`. Each call to `wandb.init()` must have a unique ID.

Thank you for your reply! I have found a solution.

**Comment by PratikStar** [comment]
I am facing the same issue.
In DDP this is bound to happen. `wandb.init` will be called by non-zero ranked processes.

For example take a look at an example code by @borisdayma , https://github.com/borisdayma/lightning-kitti/blob/master/train.py

**Comment by a-rich** [comment]
I'm also curious about this...

I need to continue writing data to the same charts across multiple executions of a script that calls `wandb.init` while maintaining a global step...

Should `wandb.init` only be called for the rank-0 node? 
Should the `id` be made to include the rank in it?

**Comment by Crayon-new** [comment]
> Should `wandb.init` only be called for the rank-0 node?

That's right, and I used broadcast in torch.distributed to broadcast the hyperparameters from rank 0 to other ranks.
