### ISSUE TITLE
Export API doesn't provide username for team projects

### ISSUE THREAD

**Issue by ankeshanand** [wandb/client#321]
Hi,

I was using the export API, and it seems there is no way to get the username from the run. `run.username` gives the project-name, not the username who ran the run. Is there an alternate way to get the username?

**Comment by lukas** [comment]
Hi - we are working on a fix.

**Comment by vanpelt** [comment]
I just pushed a fix in a new branch.  You can call run.user.username if you install from here:  `pip install --upgrade git+git://github.com/wandb/client.git@feature/retry_public#egg=wandb`

I’ll push this to the main line early next week.

**Comment by vanpelt** [comment]
This is now in 0.8.0
