### ISSUE TITLE
[CLI] wandb_logger.log_image DOES NOT EXIST

### ISSUE THREAD

**Issue by tsuijenk** [wandb/client#3215]
**Description**
Hello, I am trying to log_image but it says it doesn't exist.

**Wandb features**
![image](https://user-images.githubusercontent.com/44915621/152626165-1aa6990e-52ef-4252-a35d-3bb11a000518.png)

**Comment by ramit-wandb** [comment]
Hi @tsuijenk, 

What version of PyTorch lightning are you using currently? I just tried a simple test script on the latest version on pytorch lightning (1.5.9):

```python3
from pytorch_lightning.loggers import WandbLogger
import torch

wandb_logger = WandbLogger(project='log_image')

print(wandb_logger)
print(wandb_logger.log_image)

image = torch.rand((3, 64, 64))

wandb_logger.log_image('image', [image])
```

I saw the following output for the print statements and was successfully able to log an image into W&B:
```
<pytorch_lightning.loggers.wandb.WandbLogger object at 0x7fa8b2d8edf0>
<bound method WandbLogger.log_image of <pytorch_lightning.loggers.wandb.WandbLogger object at 0x7fa8b2d8edf0>>
```
which indicates to me that `log_image` exists and is functioning correctly.

If you are running the latest version of Lightning, I would recommend reinstalling Pytorch Lightning and wandb once. Please let me know if you still run into issues after reinstalling.

Thanks,
Ramit

**Comment by awaelchli** [comment]
I can confirm this feature was introduced in Lightning 1.5.0, so you will have to upgrade lightning to the latest version. 
`pip install --upgrade pytorch_lightning`
Happy logging!

**Comment by ramit-wandb** [comment]
Closing this issue out. If you still experience issues with logging images, please let us know!
