### ISSUE TITLE
Jupyter Lab hangs when declaring WandB config variables

### ISSUE THREAD

**Issue by cpoptic** [wandb/client#322]
* Weights and Biases version:  '0.7.3'
* Python version:  3.6
* Operating System:

### Description

Just trying to declare some hyperparameters in Jupyter Lab

### What I Did

```
wandb.init()
config = wandb.config
```

```
config.learning_rate = 0.1
config.mini_batch_size = 32
config.anneal_factor = 0.5
config.patience = 5
config.max_epochs = 1000
```

While executing that 2nd cell, Jupyter Lab just hangs indefinitely.  Curiously when I stop the kernel and run `config`, it returns  a list of the odict keys that I assigned (learning_rate, mini_batch_size, etc).  Jupyter keeps showing the asterisk, indicating that it's working, indefinitely.

**Comment by vanpelt** [comment]
Thanks @cpoptic, I'll try to reproduce and get a fix ASAP.

**Comment by vanpelt** [comment]
Hey @cpoptic, I tried to reproduce this with the current version of the CLI 0.7.3 and couldn't.  Here's a colab notebook (that should be using the same jupyter kernel backend):  https://colab.research.google.com/drive/1cT3jyoEBmIQkGTX5H08exTk09fPyQ8Lx

Can you create a notebook that can run in mybinder.org that could reproduce this?

**Comment by vanpelt** [comment]
We do serialize the dictionary as YAML when you set a key and write it to disk.  Is it possible you have a funky yaml library or an issue writing to disk?

**Comment by vanpelt** [comment]
@cpoptic ping

**Comment by vanpelt** [comment]
@cpoptic are you still seeing this?
