### ISSUE TITLE
[Q] How do I make my already existing projuct public?

### ISSUE THREAD

**Issue by SkaarFacee** [wandb/client#3221]
At the end it would be amazing if I could share a link to someone so that they can access all the runs

**Comment by AntreasAntoniou** [comment]
I did this on Friday when I wanted to share some results with my group and it worked, but somehow I can't do it right now. It won't let me switch a private to a public project, even though 2 days ago it worked just fine. 

Here is what I did.

![image](https://user-images.githubusercontent.com/10792502/152690898-f0513969-b451-450b-a7bb-bb62e8b07c2d.png)

I clicked on the lock on the right hand side of the project name and then simply switched it to public. Then I shared it with everyone.

No idea why it doesn't work anymore though. 

Perhaps there is a limit to public repos?

**Comment by SkaarFacee** [comment]
@AntreasAntoniou  I don't have any existing public repos. So it should work for me right. I can't click the public option just like how you mentioned you did it before

**Comment by AntreasAntoniou** [comment]
Good to know. So it's probably not any limitation on number of public repos. Hopefully one of the devs can enlighten us.

**Comment by ramit-wandb** [comment]
Hi @SkaarFacee @AntreasAntoniou, 

This was a bug introduced earlier this week. You are correct, we do not have a limitation on the amount of public repos you can create. This has been fixed now, and you should be able to change any repo to public.

Please let me know if you experience any issues with this.

Thanks,
Ramit

**Comment by SkaarFacee** [comment]
Thanks alot. I'll check it out right away.🎉

**Comment by ramit-wandb** [comment]
Closing this issue out since this has been fixed. If you are still experiencing issues, please let us know!
