### ISSUE TITLE
[Q] How to change directory of `wandb.run.dir` post `wandb.init`?

### ISSUE THREAD

**Issue by bhavitvyamalik** [wandb/client#3227]
By default, the logs for a particular run are saved in `wandb/run-20220208_000209-za6v4ogm` when `wandb.init` is not supplied with any directory. I want logs to be saved in directory after calling `wandb.init` without any `dir`. Is it possible to do that? I've already tried `os.symlink` for that but looking for a better solution

**Comment by vanpelt** [comment]
We must know the directory before init is called.  You can specify the directory with an environment variable.  If you're able to execute some python before wandb.init is called in your process you could do:

```python
import os
# some code to create a directory
os.environ["WANDB_DIR"] = "/tmp/some_directory_that_exists"
```

**Comment by bhavitvyamalik** [comment]
Thanks for the prompt response, @vanpelt! However, I want to save my `checkpoints` and `wandb` folders inside a folder which is named after the `id` of my run for which `wandb.init` has to be called to fetch the `id`. So, creating `symlink` is only viable option here since you mentioned that `wandb.init` must know the directory before being called?

**Comment by vanpelt** [comment]
You can create the id as well ahead of time, either by an environment variable or as the `id` argument of `wandb.init`.  We have a helper to generate a unique id, so the code could look like:

```python
import os
import wandb

run_id = wandb.util.generate_id()
# code to create a directory with the run_id in it
os.environ["WANDB_RUN_ID"] = run_id
os.environ["WANDB_DIR"] = "/tmp/some_directory_that_exists"
```
