### ISSUE TITLE
trying to see model Visualizations under the web portal:  "No Access .  You do not have permission to view this page."

### ISSUE THREAD

**Issue by cpoptic** [wandb/client#323]
* Weights and Biases version:
* Python version:
* Operating System:

### Description

under `https://app.wandb.ai` <username> \ <project>

### What I Did

Clicking on the "Visualizations" pane under "Project Workspace" no longer lets me see the visualizations that I could two weeks ago. What changed?  Why can I not see the visualizations?

> No Access .  You do not have permission to view this page.

**Comment by vanpelt** [comment]
Hey @cpoptic what project are you trying to access?  Can you add a link to the specific page you're seeing this on?

**Comment by cpoptic** [comment]
All of them, actually:
https://app.wandb.ai/chris-poptic/olive-sentence-classification?workspace=user-chrispoptic
https://app.wandb.ai/chris-poptic/free-metrics-project?workspace=user-chrispoptic

I can see the table of `Runs`, but the `Visualizations` are blocked. Weird.

**Comment by vanpelt** [comment]
Weird, try going to https://app.wandb.ai/logout then login again.  The olive-sentence-classification project doesn't have any metrics to visualize, but I was able to visualize on free-metrics-projects.  Can you add a screenshot of the error if you see it again?

**Comment by cpoptic** [comment]
So I logged out and logged back in, and all is fine; visualizations are back.

However, now, when I try to add a WandB param in Jupyter Lab notebook, `config.embedding_configuration = document_pooled_embeddings`
it hangs that cell indefinitely.  Any idea why?

**Comment by vanpelt** [comment]
Hey @cpoptic, it's sounds like a bug with our jupyter integration.  Try setting config when you call init, i.e. `wandb.init(config={"embedding_configuration": "foo", "something_else": "bar"})`.  I'll look into the jupyter issue and track progress in the other issue you filed.

**Comment by cpoptic** [comment]
Another aspect of this Jupyter integration bug I noticed:  When I have several lines declaring a config variable in the same cell and execute that cell, the kernel hangs of course.  But after interrupting it and running `config.keys()`, it will have successfully added the first line of that cell to the config variable, but not the subsequent ones.  It only adds the first.  So for example, if the cell contains: 

`config.mini_batch_size = 32
config.anneal_factor = 0.5
config.patience = 5
config.max_epochs = 1000`

only the the mini_batch_size variable will be added.  Strange behavior.

**Comment by cpoptic** [comment]
Hi @vanpelt , thanks, but I was definitely using the two-step process on a project in a Jupyter Lab notebook a few weeks ago, where you define   `config = wandb.init()` .  and then in the next cell add each hyperparam to be tracked with `config.<param_name> = _____` . e.g. `config.learning_rate = 0.001`

But frustratingly, today this procedure no longer appears to work.

So I don't think that's the solution.

**Comment by vanpelt** [comment]
@cpoptic totally agree, there was a regression that was introduced, it's not a long term fix.  We'll get a fix out likely early next week, until then hopefully the single line solution can be a bandaid.

**Comment by cpoptic** [comment]
Ok, yeah the workaround I discovered was:

-  putting each config.hyperparam declaration in a separate Jupyter cell, 
- executing that cell, 
- the notebook freezes, 
- stopping the kernel, 
- restarting the kernel, 
- and then executing the next cell.  

Then repeating this process for each of the ~dozen config params.  

I'm more confused what changed recently, but I definitely did not have to do this round-about way a few weeks ago.
