### ISSUE TITLE
Windows separate drives execution issue

### ISSUE THREAD

**Issue by VenturaFranklin** [wandb/client#324]
* Weights and Biases version: 0.7.3
* Python version: 3.7.0
* Operating System: Windows 10

### Description
My main working directory in a directory that is not the C: drive but a different drive, specifically the D: drive.

### What I Did
Running from the command line and wandb execution eg:
```
wandb login
or
wandb --help
or
wandb --version

I get the error:

Traceback (most recent call last):
  File "C:\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\workspace\.virtualenvs\conx\Scripts\wandb.exe\__main__.py", line 5, in <module>
  File "d:\workspace\.virtualenvs\conx\lib\site-packages\wandb\__init__.py", line 66, in <module>
    GLOBAL_LOG_FNAME = os.path.relpath(GLOBAL_LOG_FNAME, os.getcwd())
  File "d:\workspace\.virtualenvs\conx\lib\ntpath.py", line 564, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'
```

Looks like it's looking for a relative path on two different drives. 

A quick work around I did was to comment the line 66 in `wandb.__init\\__.py`
`GLOBAL_LOG_FNAME = os.path.relpath(GLOBAL_LOG_FNAME, os.getcwd())`

**Comment by VenturaFranklin** [comment]
Temp directory by tempfile.gettempdir() for the wandb debug log file is:
C:\Users\venturf2\AppData\Local\Temp\wandb-debug.log

getcwd is:
D:\workspace\conx

**Comment by vanpelt** [comment]
Hey @VenturaFranklin our current windows support is really spotty.  Have you considered using docker in windows?  Our cli has a command `wandb docker` that will launch you into an ML optimized docker environment and mount your code into it.

**Comment by VenturaFranklin** [comment]
@vanpelt I did not know this. 
I was taking the ODSC class you did on Wednesday and wanted to test things out on my system. The entire workshop was mostly working on Windows. There was this initial error described above, wandb would only work when running `wandb run`, and it would not upload any of the media files. 
But overall, it would get the rest of the basic run information. 
I'll mark as closed, but I don't think full Windows support will take you too much more work.
Thanks for a great class!
