### ISSUE TITLE
[CLI] Metrics are not uploaded

### ISSUE THREAD

**Issue by RamiAI** [wandb/client#3242]
**Description**
Hi. I'm currently working with stable baselines2 and I'm trying to upload the tensorboard metrics to the web UI, but unfortunately not all metrics are uploaded.

Here is an image of the Google Colab tensorboard instance:
![tensorboard](https://user-images.githubusercontent.com/95527924/153758760-4aa337b6-75e0-4a3d-9957-464f4aeddcfa.png)

And now the tensorboard instance in the web UI:
![wandb_ui](https://user-images.githubusercontent.com/95527924/153758755-8cf820e9-8610-4076-bdfa-759aed322429.png)

Did I forget any configuration or is this a bug?

**Wandb features**
See Colab link below.

**How to reproduce**
1. [Google Colab](https://colab.research.google.com/drive/1grmHc1QH80egTOK_ANgUtcx_ndmbq6wx?usp=sharing)

**Environment**
- Google Colab

**Comment by aidanjdonohue** [comment]
Hi @RamiAI , thanks for reporting. Let me look into this for you.

**Comment by aidanjdonohue** [comment]
@RamiAI, I am not able to reproduce this issue. Could you link me to your project page? This is what I get when I run the colab you shared:
![Screen Shot 2022-02-17 at 12 04 20 AM](https://user-images.githubusercontent.com/26048813/154432096-3dbc4566-5439-4bba-bbff-8ee259288047.png)
![Screen Shot 2022-02-17 at 12 04 06 AM](https://user-images.githubusercontent.com/26048813/154432099-6a38d017-e7a8-4b28-a130-534f904837b4.png)

**Comment by RamiAI** [comment]
Hi @aidanjdonohue. I have added a call to the function `set_global_seeds` with which you can now better recreate this. After the training run is finished you have to refresh the tensorboard UI using the button in the upper right corner (in my case this took about 10 seconds). If all this doesn't work try to increase the `total_timesteps` a little bit (e.g. to 30e3).

It looks like stable-baselines adds the additional metrics only after a short time period. This could also be the source of this error. The client seems to only include the metrics that are available to it from the beginning.

**Comment by aidanjdonohue** [comment]
Hi @RamiAI thanks for reporting, we're looking into this and will let you know when we have a fix for this here.
