### ISSUE TITLE
OSError: [Errno 95] Operation not supported: './project/logs/wandb/model_final.onnx' -> './project/wandb/run-20220214_142959-2oruw061/files/logs/wandb/model_final.onnx'

### ISSUE THREAD

**Issue by dranreb1660** [wandb/client#3243]
- Weights and Biases version: 0.12.10

- Python version: 3.7
- pytorch lightning: 1.5.10
- Operating System: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic, (google colab)

### **Description**
_following the "supercharge your training with Pytorch lightning + weight and biases"_
I am trying to save a model after it's been exported to onnx but getting the error below.

### Code

```
  def validation_epoch_end(self, validation_step_outputs):
          dummyImput = torch.zeros(
              (1, self.seq_length, self.n_features), device=self.device)
          model_filename = f'model_final.onnx'
          torch.onnx.export(self, dummyImput, model_filename)
          wandb.save(model_filename)
          outputs = [out['loggits'] for out in validation_step_outputs]
          flattened_outputs = torch.flatten(
                torch.cat(outputs))
          self.logger.experiment.log(
          {'valid/logits': wandb.Histogram(flattened_outputs.to('cpu')),
            'epoch': self.current_epoch}
          )
logger = WandbLogger( 'onnx', save_dir='./logs', project='surface_pred')
```

### Traceback

```
[<ipython-input-27-b4ab814812db>](https://localhost:8080/#) in validation_epoch_end(self, validation_step_outputs)
     57     model_filename = f'./logs/wandb/model_final.onnx'
     58     torch.onnx.export(self, dummyImput, model_filename)
---> 59     wandb.save(model_filename)
     60     outputs = [out['loggits'] for out in validation_step_outputs]
     61     flattened_outputs = torch.flatten(

[/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py](https://localhost:8080/#) in save(self, glob_str, base_path, policy)
   1425                 os.symlink(abs_path, wandb_path)
   1426             elif not os.path.exists(wandb_path):
-> 1427                 os.symlink(abs_path, wandb_path)
   1428             files.append(wandb_path)
   1429         if warn:
```
```

OSError: [Errno 95] Operation not supported: 
'./project/logs/wandb/model_final.onnx' -> 
'./project/wandb/run-20220214_142959-2oruw061/files/logs/wandb/model_final.onnx'
```

**Comment by ramit-wandb** [comment]
Hi @dranreb1660,

Thanks for writing in! From the error message, it seems like you do not have permissions to create symlinks. I noticed this was running in a Colab, could you share the link to it? It will help us debug this issue better for you.

Thanks,
Ramit

**Comment by dranreb1660** [comment]
> Hi @dranreb1660,
> 
> Thanks for writing in! From the error message, it seems like you do not have permissions to create symlinks. I noticed this was running in a Colab, could you share the link to it? It will help us debug this issue better for you.
> 
Hi @ramit-wandb Thanks for the reply. Yes, that might be the issue. I didn't realize there'd be a restriction to creating a symlink. below is the notebook. 
[notebook](https://colab.research.google.com/drive/1bZq9qPwwb6xld09eaWYyr8jjSpOEPdBm?usp=sharing)

**Comment by ramit-wandb** [comment]
Hi @dranreb1660,

I just went through your notebook, but was unable to reproduce the error. Is this still an issue? One potential workaround to this could be to use Artifacts instead of saving the model files through `wandb.save` - they are more suited to saving and tracking model files.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @dranreb1660,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Thanks

**Comment by ramit-wandb** [comment]
Hi @dranreb1660, since we haven't heard back from you, we are closing this support request. If you would like to continue this conversation, please let us know!
