### ISSUE TITLE
[CLI] `wandb.restore` restoring incorrect file

### ISSUE THREAD

**Issue by samuela** [wandb/client#3247]
**Description**
```python
import subprocess
import wandb
f = wandb.restore("checkpoint_49", "skainswo/playing-the-lottery/n83xc9z7")
subprocess.run(["md5sum", f.name])
```
prints `92819919bf3b9c9669d4b20ccfb711d6`, but if I download the file from https://wandb.ai/skainswo/playing-the-lottery/runs/n83xc9z7/files?workspace=user-skainswo I get a file which has the md5 hash `17709b8ae64414cbab216bd5487d00db`. By inspecting the two files I can tell that the downloaded file is correct and `wandb.restore` one is wrong.

Why is `wandb.restore` giving me the wrong file back?

**Wandb features**
See the example code above. I'm saving files into `wandb.run.dir` to get them uploaded in the script that created the original run.

**How to reproduce**
See example code above. The run should be public. Happy to provide any other information that may be helpful in debugging.

**Environment**
- OS: Linux 5.10.95, NixOS, 21.11 (Porcupine)
- Environment: Running in nix-shell with wandb 0.12.10.
- Python Version: 3.9.9

**Comment by ramit-wandb** [comment]
Hi @samuela,

Is this error reproducible? I just tested your code on 2 separate machines - Ubuntu and MacOS - and they provided me the expected MD5 hash of `17709b8ae64414cbab216bd5487d00db`. 

If possible, please share the file / diff of the wrongly downloaded file. I will dig in further into what is happening here.

Thanks,
Ramit

**Comment by vanpelt** [comment]
Hey @samuela `wandb.restore` is a little tricky.  There's a `replace` [argument](https://github.com/wandb/client/blob/master/wandb/sdk/wandb_run.py#L2891-L2897) that defaults to False.  This means we won't download anything if an existing file with that name exists in the current directory, which is what's likely happening in your case.  A sure fire way to always get the checkpoint with wandb.restore is:

```python
f = wandb.restore("checkpoint_49", "skainswo/playing-the-lottery/n83xc9z7", replace=True, root=os.getcwd())
```

**Comment by samuela** [comment]
@vanpelt That's likely the problem. This really feels like a footgun. Why not have `wandb.restore` throw an error if the filename already exists (when `replace` is False`)?

**Comment by vanpelt** [comment]
@samuela totally agree, it's a big time foot gun.  Our plan is to deprecate `save` and `restore` and direct users to our [Artifacts api's](https://docs.wandb.ai/guides/artifacts/artifacts-core-concepts).
