### ISSUE TITLE
[Q] model checkpoint group by run in Artifact

### ISSUE THREAD

**Issue by JJBT** [wandb/client#3248]
What is the proper way to save model checkpoints from one run?

I`ve tried to save in one Artifact obejct, 

`snapshot_artifact = wandb.Artifact(name=wandb.run.id, type='model')`
`snapshot_artifact.add_file(os.path.join(wandb.run.dir, 'snapshots', latest_snapshot), os.path.join('snapshots', latest_snapshot)) `
`wandb.run.log_artifact(snapshot_artifact)`

but  `ValueError: Can't add to finalized artifact` when I try to save checkpoint in second time. (Problem is in `finalize` in log_artifacts and the way to disable `.finalize()` is might be decision of my problem)  

I have no found the clear way in documentation to organize model checkpoints from one run in one folder. 

Structure I want is:
```
run_id
│   
└─── checkpoints
          │─ checkpoint_000100.pt 
          │─ checkpoint_000200.pt
```

**Comment by lesliewandb** [comment]
Hi, is it important that you save the checkpoints to Artifacts? Also, can you tell me which deep learning framework you are using? If you're using [PTL](https://docs.wandb.ai/guides/integrations/lightning#what-does-the-integration-log-without-any-additional-code), you can use os.environ["WANDB_DIR"] to set up the model checkpoints directory. If you are using Keras, we have [WandbCallback](https://docs.wandb.ai/ref/python/integrations/keras/wandbcallback) to log model checkpoints

**Comment by JJBT** [comment]
Hi, Im using artifacts because `wandb.save` cannot tell me when my file has synced with W&B server. [issue](https://github.com/wandb/client/issues/3238)
