### ISSUE TITLE
[CLI] agent run slow

### ISSUE THREAD

**Issue by 2er0** [wandb/client#3252]
**Description**
By running a script with python directly and with the wandb client a performance difference of 20 seconds per epoch to 153 seconds occurs.

What can the problem be?

The run script contains wandb.init(), wandb.log(), wandb.watch() and wandb.config.update()

**Environment**
- OS: [e.g. Ubuntu 20.04]
- Environment: [e.g. GPU TitanX]
- Python Version: [eg. 3.8.12]

**Comment by aidanjdonohue** [comment]
Hi @2er0 , `wandb.log()` and `wand.watch()` will definitely add to compute time of an epoch; however, most of the heavy lifting is done asynchronously where possible. Are you saying that with wandb each epoch is between 20 and 153 seconds slower? If so, how long are the epochs overall. There may be some room to optimize your logging behaviour.

**Comment by 2er0** [comment]
Somehow the GPU and the Nvidia driver was the issue.
