### ISSUE TITLE
[Q] passing environement variables to sweep command arguments

### ISSUE THREAD

**Issue by JADGardner** [wandb/client#3255]
I have a sweep .yaml config file that looks something like this:

```javascript
program:
  some_code.py
entity: foo
project: bar
parameters:
  batch_size:
    value: 30
  lr:
    distribution: uniform
    max: 0.01
    min: 0.0001
command:
  - torchrun
  - "--nproc_per_node" 
  - ${WOLRD_SIZE}
  - "--nnodes"
  - 1
  - "--node_rank"
  - 0
  - ${program}
```

I use the 'command' section in the config above to have the sweep agent launch the run using torchrun for multi-gpu training. However I want to be able to specify the "--nproc_per_node" argument  via an environment variable WOLRD_SIZE that I set in a bash script such as that below:

```bash
#! /bin/bash
export CUDA_VISIBLE_DEVICES=0,1,3,4,6,7

export WOLRD_SIZE=6

NUM=10
ENTITY="foo"
PROJECT="bar"
SWEEPID="s8shs8f"

wandb agent --count $NUM --entity $ENTITY --project $PROJECT $SWEEPID
```

But when I do the value of WORLD_SIZE for the "--nproc_per_node" argument is always blank as shown in the information about the run printed in the console:

```bash
2022-02-18 10:24:37,346 - wandb.wandb_agent - INFO - About to run command: torchrun --nproc_per_node --nnodes 1 --node_rank 0 some_code.py
```
Is there a way to pass environment variables to the command arguments?

**Comment by vanpelt** [comment]
@JADGardner unfortunately we don't currently support resolving env variables in the `command` section.  The best workaround I could propose today is to make your sweep config command actually execute another bash script, i.e.

```yaml
command:
  - runner.sh
  - ${program}
```

Then in a script named runner.sh:

```bash
#!/bin/bash

torchrun --nproc_per_node $WOLRD_SIZE --nnodes 1 --node_rank 0 $1
```

The environment that the agent is running in should be passed down to all sub processes.

**Comment by robertavram-md** [comment]
Ty this was helpful for me.

**Comment by listaction** [comment]
hi super team! 
what sort of shell does wandb agent run (when running) - if we use a bash script for the runner and have things like $(date) or `date` it throws errors when running on Ubuntu 22.04.4 LTS \n \l bash shell.
