### ISSUE TITLE
[CLI] Artifact.add_reference method throws error for files with same names but in different folders.

### ISSUE THREAD

**Issue by salehahr** [wandb/client#3256]
**Description**
* I have folders of video frames where the filenames correspond to video timestamps.  
    As a result, some filenames occur across different folders.
* These files are then wrongly detected as duplicates;  
    when trying to add these files as reference artifacts using the `Artifact.add_reference` method, `ValueError: Cannot add the same path twice: 0000_16840.png` is raised.

**Wandb features**
[wandb.Artifact.add_reference](../blob/412f7eb4f53fb36a91422ea477ecabe6a8ad52c2/wandb/sdk/wandb_artifacts.py#L423..L455)

**How to reproduce**
1. To reproduce the error:  
    https://gist.github.com/salehahr/b90f79ccd9960fbca1890277791b92c0 
    ```python
    import wandb

    files = [
        "/graphics/scratch/schuelej/sar/data/256/GRK011/0000_00000__0000_39000/skeleton/0000_16840.png",
        "/graphics/scratch/schuelej/sar/data/256/synthetic-bladder09/skeleton/0000_16840.png",
        # "/graphics/scratch/schuelej/sar/test/folder1/0000_16840.png",
        # "/graphics/scratch/schuelej/sar/test/folder2/0000_16840.png",
    ]

    with wandb.init(project="dataset2") as run:
        data = wandb.Artifact(name="temp-data", type="dataset")

        for file in files:
            uri = f"file://{file}"
            data.add_reference(uri)

        run.log_artifact(data)
    ```
2. Describe what we have to do in order to trigger the issue  
    * Create a similar file structure as in the `files` list in the code above, and run the code.
    * Commenting the first two files in `files` and uncommenting the bottom two gives different errors when running the code:  
        * Running with only the first two files results in `ValueError: Cannot add the same path twice: 0000_16840.png`
        * Running with only the bottom two files results in a successful run, but only the last file is saved (overwrites the second to last file).

**Traceback**
```
Traceback (most recent call last):
  File "/graphics/scratch/schuelej/sar/tfgraph/mwe_duplicate_artifacts.py", line 15, in <module>
    data.add_reference(uri)
  File "/graphics/scratch/schuelej/system/miniconda3/envs/tfgraph/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 455, in add_reference
    self._manifest.add_entry(entry)
  File "/graphics/scratch/schuelej/system/miniconda3/envs/tfgraph/lib/python3.8/site-packages/wandb/sdk/interface/artifacts.py", line 94, in add_entry
    raise ValueError("Cannot add the same path twice: %s" % entry.path)
```

**Additional notes**
I saw that the `entry` objects created [here](../blob/412f7eb4f53fb36a91422ea477ecabe6a8ad52c2/wandb/sdk/wandb_artifacts.py#L1263..L1265) end up having the base filename in the `entry.path` attribute instead of the full filepath. Could this possibly be the cause for the false duplicates?  

![](https://user-images.githubusercontent.com/80096792/154693823-4197bb98-ea77-44ab-a27b-9414d09f78fc.png)

**Environment**
- OS: Ubuntu 18.04.6
- wandb version: 0.12.10
- Python Version: 3.8.12

**Comment by ramit-wandb** [comment]
Hey @salehahr,

Thanks for writing in! You are right, this is a known bug in `add_reference` right now. We try to infer `path` through the filepath passed in and this seems to be creating conflicts for you.

You should be able to resolve this for now by changing your code to have the following structure:
```python3
artifact.add_reference("file://path1//file1.txt", "path1//file1.txt")
artifact.add_reference("file://path2//file1.txt", "path2//file1.txt")
```

as opposed to
```python3
artifact.add_reference("file://path1//file1.txt")
artifact.add_reference("file://path2//file1.txt")
```

We plan to resolve this through our client in the future, but that change has not been implemented yet, so I am hoping this resolves the issue for you. Please let me know if this workaround works for you.

Thanks,
Ramit

**Comment by salehahr** [comment]
Hi Ramit,

Thanks for the speedy response! I have implemented your workaround in my updated test code as below, while also making use of [this example from the docs](https://docs.wandb.ai/ref/python/artifact#get):
```python
import wandb

files = [
    "/graphics/scratch/schuelej/sar/data/256/GRK011/0000_00000__0000_39000/skeleton/0000_16840.png",
    "/graphics/scratch/schuelej/sar/data/256/synthetic-bladder09/skeleton/0000_16840.png",
]

# check that files exist before running wandb
for path in files:
    assert os.path.isfile(path)

# project settings
project_name = "dataset2"
dataset_name = "temp-data2"

# create the artifact
with wandb.init(project=project_name, name="create-artifact") as run:
    data = wandb.Artifact(name=dataset_name, type="dataset")
    for path in files:
        data.add_reference(f"file://{path}", path)
    run.log_artifact(data)

# download the artifact
with wandb.init(project=project_name, name="download-artifact") as run:
    data = run.use_artifact(f"{project_name}/{dataset_name}:latest", type="dataset")
    for path in files:
        img = data.get(path)
        assert img is not None
```

This results in a successful run for creating the artifact! However, I saw in the web app that an empty folder was uploaded:  

![image](https://user-images.githubusercontent.com/80096792/154792117-0adb46b7-b9c9-406c-a699-44423306b89e.png)

As a result, the object returned by `data.get` in the penultimate line of the code above is `None` and the final assert fails.

Is there something else I'm missing in order to properly upload and download the artifact? Would be grateful if you could point me in the right direction once again!

Thanks,
Salehah

**Comment by ramit-wandb** [comment]
Hey @salehahr,

I apologize for the delay here. I tested this on my end, and it looks like switching the file paths from absolute paths to relative paths fixes this issue.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @salehahr,

I wanted to follow up here and ask if I can be of further assistance.

Thanks,
Ramit

**Comment by salehahr** [comment]
Hi Ramit,

Thank you—using relative paths did the trick!

While testing the downloading of the artifacts, `data.get` didn't work for me (returns None), but `data.get_path` was what worked instead. So just to confirm, and also in case it helps anyone with the same problem stumbling across this issue, would the normal procedure for uploading/downloading be
* for normal artifacts added with `add` --> download with `get`
* for artifact references added with `add_reference` --> download with `get_path`?

Since my issue has been resolved, I'm closing this with thanks!
Salehah

**Comment by CatalinAlexandruPX** [comment]
Hi @ramit-wandb,
Just bringing this up as I just had this issue, and maybe it can be added to the backlog.
For my pipeline, I have to use absolute paths, so I cannot change to relative as above described, but using your fix to add the file path as the artifact names seems to solve this.
