### ISSUE TITLE
Can we use W&B with Haystack QAG?

### ISSUE THREAD

**Issue by UmarEm** [wandb/client#3268]
Got error
ValueError: Expected a pytorch model (torch.nn.Module). Received <class 'haystack.nodes.reader.farm.FARMReader'>

**Comment by aidanjdonohue** [comment]
Hi @UmarEm , we don't currently have an integration with Haystack.

**Comment by UmarEm** [comment]
Hey @aidanjdonohue 
Thank you for the quick reply.

How about using Question Answer generation models/simple transformers like "deepset/roberta-base-squad2" which have tokenizers?
