### ISSUE TITLE
[Q] How do I access a saved table form a completed run?

### ISSUE THREAD

**Issue by itsmemala** [wandb/client#3269]
Hi, I have saved a table "doc_topic_map" during a run and I can see it in the UI but how do I retrieve the contents of the table from a python notebook?

run.summary["doc_topic_map"] gives me the _latest_artifact_path but if I try to pass that to the run.use_artifact() function, it errors - 
"CommError: You must pass a wandb.Api().artifact() to use_artifact"

Using the below line (after filling in the run id and table name) also results in the same error:
run.use_artifact("run-RUN_ID-table_name:v3").get("table_name")

Note: The run was completed in a previous session.

**Comment by asafarevich** [comment]
I tried this it did not work
my_table = run.summary["table_name"]
gives a type of wandb.old.summary.SummarySubDict
which does not have data from the table

**Comment by Serebryanskiy** [comment]
Every time you try to get logged table you have to reinvent the wheel. Guys, why this should be so hard? Is there a way to get saved tables in some direct way?
