### ISSUE TITLE
[Q] Retrieving sweep names via api

### ISSUE THREAD

**Issue by mbosc** [wandb/client#3275]
Hi everyone,

I'm working on a grid search for a series of models with different sets of parameters. For this reason, I'm defining multiple sweeps within my project (one per model with its specific hyperparameters). I would need to have an agent polling all my sweeps to see whether they still include runs to be completed, but I cannot find any API query to retrieve a list of **all sweeps associated to a given project**.

Is there any way to get a list of all sweep ids other than webscraping `https://wandb.ai/<entity>/<project>/sweeps`?

Thank you all and thanks for the good work you're doing with the platform!

**Comment by ramit-wandb** [comment]
Hey @mbosc,

You can find all your sweeps for a sweep as
```
sweeps = wandb.Api().project(PROJECT).sweeps()
```

where `PROJECT` is your project's name.

Thanks,
Ramit

**Comment by mbosc** [comment]
Thanks, that's great!
