### ISSUE TITLE
[CLI]:  can't integrate the wand callback in Tensorflow

### ISSUE THREAD

**Issue by mv96** [wandb/client#3291]
### Describe the bug

the model does not seem to log anything on the dashboard

```python 

from transformers import create_optimizer

batches_per_epoch = len(tokenized_datasets["train"]) // batch_size
total_train_steps = int(batches_per_epoch * num_epochs)

#uses adamw optimizer
optimizer, schedule = create_optimizer(
    init_lr=learning_rate, num_warmup_steps=0, num_train_steps=total_train_steps
)
model.compile(optimizer=optimizer, loss=loss,
             metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])


model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=num_epochs,
    callbacks=[WandbCallback()]
)
```

```shell
Epoch 1/5
    6/38997 [..............................] - ETA: 3:32:09 - loss: 0.5019 - sparse_categorical_accuracy: 0.7500WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.1345s vs `on_train_batch_end` time: 0.1916s). Check your callbacks.
   30/38997 [..............................] - ETA: 3:31:29 - loss: 0.5895 - sparse_categorical_accuracy: 0.7229
```

### Environment

WandB version:'0.12.10'

OS: liinux

Python version:Python 3.9.7

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Hi @mv96,

I'm sorry you are experiencing this? Could you share a link to your workspace where you see this issue, along with the `debug.log` and `debug-internal.log` associated to the run where this issue is happening. It will give me some more information into why this might be happening for you.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @mv96,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,
Weights & Biases

**Comment by mv96** [comment]
Hi the issue has been resolved, I am able to track my metrics,

However I have two more questions, that I figured while using wandb:

1. Previously I was using wandbcallback inside the Keras Model, I am just curious what is the difference between WandB callback and wandblog ?

2. how can I log my Wandb metrics on offline computing, for security reasons I can't access the internet on the compute machine and hence have to transfer my files to the compute system to be able to run my machine learning experiments, I was wondering if I can get some log file from my compute engine and then upload it to wandb server just to keep a track of it ?

**Comment by ramit-wandb** [comment]
Closing this thread since this issue has been resolved - If you would want to continue this conversation, please let us know!
