### ISSUE TITLE
[App]: Init function jumbles the order of configuration parameters in dictionary

### ISSUE THREAD

**Issue by azinonos** [wandb/client#3298]
### Current Behavior

Hello

I'm using Hydra and Weights & Biases to configure my application and log all the configuration parameters. Hydra produces nested dictionaries which wandb doesn't properly process, so I use the function _flatten_dict from the link below, to flatten the dictionary before passing it to wandb.
https://github.com/PyTorchLightning/pytorch-lightning/blob/87bd54aedfcd990b935860d020ca89d192e2ba40/pytorch_lightning/utilities/logger.py

I've updated the code above a bit to return a sorted dictionary by key. I then log the parameters as follows:
wandb.init(project=cfg.project_name, config=_flatten_dict(cfg), mode=cfg.logger.mode)

If I print the keys, values in _flatten_dict(cfg) I get what I expect, which is a dictionary sorted by the key. However, once it is logged in wandb the order is completely jumbled and I have parameters all over the place, which makes it very difficult to see what is happening. Furthermore, there is no option to sort by key on the wandb UI.

### Expected Behavior

Passing a sorted dictionary to wandb should keep the ordering and present it as such. Also there should be a way to sort keys/values on the actual UI.

### Steps To Reproduce

1. Produce a big dict of configs such as:
mydict = {"data": "mnist", "data/image_size": 32, "model": resnet, "model/output_dim": 256, "logger": "wandb", ...}

2. log it with:
wandb.init(project="TEST", config=mydict)

3. See the results on the UI

### Environment

OS: Unix/Linux

Browsers:

Version:

**Comment by azinonos** [comment]
Hi, thank you for the response. Unfortunately, on my project they don't even seem to be in reverse alphabetical order - they just seem to be kind of random? Thanks for increasing priority.

**Comment by azinonos** [comment]
Hello,
It looks like this was fixed as now the configs seem to be sorted and categorised, thank you. Here's the link to my project, though it is private:
https://wandb.ai/azinonos/byol_video

**Comment by BitCalSaul** [comment]
i'm wondering if this issue has been solved since i also encounted the same issue here.
