### ISSUE TITLE
wandb.Image inside wandb.Table don't work 

### ISSUE THREAD

**Issue by vadimkantorov** [wandb/client#3313]
### Current Behavior

It just displays a word "Image" instead of showing the image.

It doesn't behave at all as suggested in https://docs.wandb.ai/guides/data-vis#rich-media

![image](https://user-images.githubusercontent.com/1041752/156224548-80ce4322-cf56-4ceb-92c9-552237cf2fa0.png)

### Environment

OS:

Browsers:

Version:

**Comment by ash0ts** [comment]
Hey @vadimkantorov, I'm sorry to hear you're facing this issue. Can you provide details about how you're logging these images to the table, how many images you're logging are, and where these images are coming from? [I'm trying to reproduce your issue to provide context for the engineers to work on a fix but I am unable to do so](https://colab.research.google.com/drive/14YUvR-L97YV1Wi31bo3h4ZPjKPzXbMBO?usp=sharing). Thank you!

**Comment by vadimkantorov** [comment]
It's exactly as in the screeshot above - 4 images in two columns and two rows. The images are coming from a PyTorch data loader (with some conversion to denormalize). Logging a list of images works, using these same Image objects as part of wandb.Table does not, so the Image objects themselves are fine. 

I've abandoned tables since they don't work for images and am now just using two panels, logging lists of images (this works fine)

**Comment by ash0ts** [comment]
Thank you for providing this context. I will be working to recreate this situation to ensure you can use images with your tables once a fix is out, as this behavior is not intended.

**Comment by ash0ts** [comment]
@vadimkantorov Hello! Upon deeper investigation of this issue, we found that directly using `runs.summary` to load a table with deleted artifact versions causes this behavior. It is best to directly load the table from the artifact in this case as we fix this issue. Thank you for bringing this to our attention and we hope to have a fix out soon!
```
runs
  .loggedArtifactVersion("name_of_artifact:version_number")
  .file("name_of_table.table.json")
```

**Comment by simaiden** [comment]
I have the same behavior :(

**Comment by tssweeney** [comment]
Hey Folks, I think that the observed behavior is due to using an older Table component instead of the Weave (Table) component. 

In the screenshot below, you can see a full-featured table. This is using the "weave" panel and should be automatically generated if you are logging a wandb.Table to the run.

<img width="1234" alt="Screen Shot 2022-04-05 at 5 37 39 PM" src="https://user-images.githubusercontent.com/2142768/161873027-ec10d438-153c-49ed-be89-c5082f2edd0c.png">

Do you mind sharing a link to your workspace? I am sure we can help configure the correct panel. You can also try resetting your workspace from the bottom left, which should use the latest component automatically:

<img width="206" alt="Screen Shot 2022-04-05 at 5 41 46 PM" src="https://user-images.githubusercontent.com/2142768/161873385-30a328c3-0ed1-419a-8cce-a77355949629.png">

**Comment by ash0ts** [comment]
@vadimkantorov and @simaiden Was @tssweeney's comment able to help?

**Comment by simaiden** [comment]
@vadimkantorov Yes, now it works, thanks @tssweeney !

**Comment by ash0ts** [comment]
@simaiden I'm glad to hear that! 
Is there any lingering issues with you @vadimkantorov?

**Comment by vadimkantorov** [comment]
I don't have a setup right now to check if this is fixed I'll be closing this issue. If I hit this again, I'll reopen in. Thanks for looking into this issue.

**Comment by cs-mshah** [comment]
I am still facing this issue. Did as per these docs: https://docs.wandb.ai/guides/track/log/media
![image](https://github.com/wandb/wandb/assets/56499208/03b0bfcf-86b2-4346-a8ca-55011b2b6e09)

**Comment by cs-mshah** [comment]
@vadimkantorov can you kindly help.

**Comment by BillGatesPriv** [comment]
> Hey Folks, I think that the observed behavior is due to using an older Table component instead of the Weave (Table) component.
> 
> In the screenshot below, you can see a full-featured table. This is using the "weave" panel and should be automatically generated if you are logging a wandb.Table to the run.
> 
> <img alt="Screen Shot 2022-04-05 at 5 37 39 PM" width="1234" src="https://user-images.githubusercontent.com/2142768/161873027-ec10d438-153c-49ed-be89-c5082f2edd0c.png">
> 
> Do you mind sharing a link to your workspace? I am sure we can help configure the correct panel. You can also try resetting your workspace from the bottom left, which should use the latest component automatically:
> 
> <img alt="Screen Shot 2022-04-05 at 5 41 46 PM" width="206" src="https://user-images.githubusercontent.com/2142768/161873385-30a328c3-0ed1-419a-8cce-a77355949629.png">

Jooo,
deleted my workspace and now it works. 
Weird.
