### ISSUE TITLE
[Q] Using wandb with M1 Mac Rosetta

### ISSUE THREAD

**Issue by hv10** [wandb/client#3348]
Hello dear WandB-Team,

I am currently forced to use a Rosetta-based Conda Environment as some of my ML Dependencies are Intel Architecture only.
When installing wandb through conda or pip within one of those environments I get the error message that WandB is requiring the AVX instruction set - which is not available within rosetta (as far as I know form googling the issue).

Any pointers on how to use WandB in this kind of environment?

**Comment by ramit-wandb** [comment]
Hi @hv10,

I'm sorry you are facing this issue. Could you share the error message reported on your computer? It would also help to know what libraries you are using alongside `wandb` to run this.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @hv10,

I wanted to follow up on this support request. Has this issue been resolved? Please let us know if we can be of further assistance.

Thanks,
Ramit

**Comment by hv10** [comment]
Hi Ramit,

sorry for the late answer.

I am running this on an M1 Macbook Air (2020 Edition).

When creating a new conda environment I can decide to let it run via the rosetta translation layer or as a native m1 application.

When running wandb in an empty conda environment which runs via rosetta I get the following error message:
```
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
```
Which after some googling made sense as the rosetta system does not provide AVX translation.
When running wandb within an empty conda environment on bare m1 everything works as expected.

The package I have a dependency on is the pytorch-geometric library which as of now does not provide osx-amd64 versions of their library.

Installing wandb/client from source within the first environment did not resolve the issue.

Best,
Noel

**Comment by vanpelt** [comment]
Hey @hv10 those errors are likely coming from the pytorch-geometric library.  Wandb doesn't have any compiled / x86 native logic.  Are you able to run your code without wandb in the first environment?

**Comment by hv10** [comment]
Again: sorry for the late reply. The issue I was facing stems from the mkl-version of numpy - when using an environment without mkl the issue subsides.

As the issue is not within wandb I am going to close the issue now.
