### ISSUE TITLE
Resuming distributed runs?

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#335]
Right now I'm doing something like this
```
    wandb.init(project="transformer-xl", name=f'one_machine-{os.environ["RANK"]}', group='my-run')
```

When one of the machines gets pre-empted, all processes are killed and then restarted from earlier checkpoint. 

What's the recommended way of resuming this run?

**Comment by vanpelt** [comment]
Hey @yaroslavvb, you can use our [resuming](https://docs.wandb.com/docs/resuming.html) feature to achieve what you're looking for.  If resume is set to True we write a file to `wandb/wandb-resume.json` which persists until a run exits successfully.  If the new machine will not have the same persistent disk you can specify a unique id and use it in the restarted instance i.e.:

```python
wandb.init(project="transformer-xl", id=os.environ["GLOBALLY_UNIQUE_ID"], resume=True)
```

Then you can check for `wandb.run.resumed` and use `wandb.restore` to pull down the latest checkpoint from wandb if you're saving them to us.

**Comment by yaroslavvb** [comment]
Should I use different unique id's for different workers in the same resumed run?

**Comment by vanpelt** [comment]
Each worker should retain the same id during the lifetime of an individual
experiment.  I.E. if a run crashes and you resume from another machine it
should have the same id.  Each new experiment needs to use a different id
that is globally unique for that project.

**Comment by yaroslavvb** [comment]
I see thanks, my understand is that you will need to do something like this to resume distributed runs

```
rank=os.environ['RANK'];
project = "transformer-xl"
if not os.path.exists(f'/remote_fs/{project}/{rank}'):
    unique_id =  # generate unique id for each worker somehow
    open(f'/remote_fs/{project}/{rank}').write(unique_id)
wandb.init(project=project, name=f'one_machine-{rank}',
               group='distributed', id=open(f"/remote_fs/{project}/{rank}).read())
```

**Comment by vanpelt** [comment]
@yaroslavvb not quite.  The group should use the same unique id, then you can append the rank to each worker.  You can use our id generation like so:

```python
rank=os.environ['RANK'];
project = "transformer-xl"
if not os.path.exists(f'/remote_fs/{project}/group_id'):
    group_id = wandb.util.generate_id()
    open(f'/remote_fs/{project}/group_id').write(wandb.util.generate_id())
else:
    group_id = open(f"/remote_fs/{project}/group_id").read()
wandb.init(project=project, group=group_id, id=f"{group_id}-worker-{rank}", job_type="worker")
```

You could also track the parameter server or a different type of worker by specifying `job_type="parameter-server"` and then giving it an id of `f"{group_id}-parameter-server"`.  Does that make sense?

**Comment by yaroslavvb** [comment]
I see, thanks!
