### ISSUE TITLE
[API] Web pages not responsive in VSCode

### ISSUE THREAD

**Issue by andreimargeloiu** [wandb/client#3353]
### Describe the bug

I'm using the API in the VSCode to export some data in table format. I noticed that calling `wandb.init()` and then displaying a run prompts an embedded w&b webpage where I shall log in. However, this web page is frozen. Clicking on any button doesn't do anything.

What can I do to be able to use the embedding webpage?

![CleanShot 2022-03-10 at 06 41 07](https://user-images.githubusercontent.com/18227298/157604098-85ab113d-1dc9-496f-86d0-5912b0bcb3f2.png)

### Environment

WandB version: 0.12.11 (latest)

OS: Macos

Python version: 3.7.9

Versions of relevant libraries: VSCode 1.65.1 (latest)

**Comment by vanpelt** [comment]
Hey @andreimargeloiu unfortunately the way VSCode creates browser contexts in it's python plugin don't allow us to persist a logged in session.  We have plans on the roadmap to eventually create an official VSCode plugin that would enable logged in session, until then you'll need to click the links and open the pages in a regular web browser.
