### ISSUE TITLE
[Q] How to make API queries about dates in the MongoDB style?

### ISSUE THREAD

**Issue by andreimargeloiu** [wandb/client#3355]
I am using the python API to select specific runs, and I want to filter based on the `created_at` using the MongoDB style queries. I tried in three ways and all failed to return any run.

How to make API queries about dates in the MongoDB style?

![CleanShot 2022-03-10 at 07 59 01](https://user-images.githubusercontent.com/18227298/157615332-87890bd4-de2c-48e8-b587-b2556406e1f6.png)

**Comment by vanpelt** [comment]
I haven't verified this, but I *believe the following will work:

```
datetime.datetime.now(datetime.timezone.utc).isoformat()
```

**Comment by andreimargeloiu** [comment]
@vanpelt It worked. Thank you!

**Comment by andreimargeloiu** [comment]
It would be great to have an example in the documentation:

```
runs = api.runs('user/project_name', {
	"$and": [{
		'created_at': {
			"$lt": '2022-03-09T10',
			"$gt": '2022-03-07T17'
		}
	}]
})
```

**Comment by janosh** [comment]
Can't find this in the docs. Could someone point me at where to look?
