### ISSUE TITLE
Older runs not showing (run count is off?)

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#336]
https://app.wandb.ai/yaroslavvb/transformer-xl?workspace=user-yaroslavvb

It says I have 40 runs, but the table ends at 30

![Screenshot 2019-05-16 14 51 09](https://user-images.githubusercontent.com/23068/57889666-424e6f80-77ea-11e9-89a1-8215e6948951.png)

**Comment by vanpelt** [comment]
Looks like the page may have gotten into a funky state.  If you refresh and page through does it work now?  There's definitely a funky underlying state issue, but I was able to page through all 4 pages of 10 runs just now.

**Comment by yaroslavvb** [comment]
Ah, yes, now I can get through all of them
