### ISSUE TITLE
Feature: Silent mode?

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#337]
Right now when I do "CTRL+C" it would run final eval and print accuracy. But now this gets scrolled away with several screens of logs from wandb (things like `wandb: Synced https://app.wandb.ai/yaroslavvb/transformer-xl/runs/yq4r2ru7`), it would be useful to have this go to some logfile instead

**Comment by vanpelt** [comment]
Is the output getting jumbled (i.e. mixed with your eval metrics) or you just want to eliminate all `wandb:` output in your terminal?

**Comment by yaroslavvb** [comment]
Eliminate all output, I'm trying to keep stdout for things that are of immediate interest to the user (ie, someone running my training script)

**Comment by vanpelt** [comment]
0.8.2 now supports an environment variable `WANDB_SILENT=true`
