### ISSUE TITLE
[CLI]: args for "Command" are not saved with the run when using `wandb.require("service")`

### ISSUE THREAD

**Issue by eladsegal** [wandb/client#3370]
### Describe the bug

When `wandb.require("service")` is used and a new wandb experiment is created, the command line arguments of the python script are not saved at all - not in the local files/logs and not in the server.  

To reproduce:
```python 
import sys
import wandb
sys.argv=["script.py", "--arg1", "--arg2"]
wandb.require("service")
wandb.init()
```
The web UI will show `Command` `script.py`  

---
Expected behavior can be seen with the following code:
```python 
import sys
import wandb
sys.argv=["script.py", "--arg1", "--arg2"]
wandb.init()
```
The web UI will show `Command` `script.py --arg1 --arg2`  

### Environment

WandB version: 0.12.11

OS: Ubuntu 20.04

Python version: 3.9.7

**Comment by kptkin** [comment]
Hi @eladsegal! 
Thanks for reporting this issue! We looked into it and was indeed an issue on our end (we had an issue when converting lists to protobuf messages)  we have a solution for this and would be part of the next release. 
In the mean time if you need this information you could add this one-liner change in the following file:
https://github.com/wandb/client/pull/3371/files#diff-432d500a1d77db4e4a22825d98e99cb860fee78777f6540b85395c1e5ee28e94L1292

**Comment by eladsegal** [comment]
Thanks, the fix works great!
