### ISSUE TITLE
[Feature]: Allow to disable code saving from tracking code

### ISSUE THREAD

**Issue by psinger** [wandb/client#3372]
### Description

Currently, a user can enable code saving from the UI settings and Wandb will send the entry-point code to the tracking service.

If Wandb logging is integrated in other applications, it would be crucial for app developers to disable code saving. Allowing this feature to be enabled from user side, instead of from app developer side, can have bad repercussions.

### Suggested Solution

Allow to force-disable any code saving from application code.

**Comment by vanpelt** [comment]
Hey @psinger you can set the `WANDB_DISABLE_CODE` environment variable to true, or you can call `wandb.init(save_code=False)`

**Comment by psinger** [comment]
@vanpelt thanks - but that's what I already tried

Changing the client setting in the UI appears to override these settings.
Could you please re-open this issue?

**Comment by psinger** [comment]
@vanpelt I opened another issue, so we can close one of them.

The replication is simple:
- Enable code saving in UI
- Disable code saving in code (by environment variable and init flag)

Then I can still see the code being logged in an experiment in the UI.
