### ISSUE TITLE
Feature request: network bandwidth

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#338]
IE, in Gbps, for received and sent, average over last reporting interval

**Comment by lukas** [comment]
I agree this would be useful

**Comment by yaroslavvb** [comment]
For distributed troubleshooting, a fine-grained graph would be especially useful, by sampling bytes sent more often, or with ethtool like here
https://github.com/horovod/horovod/issues/255#issuecomment-386772483

If it's too expensive be gated on env var like "$WANDB_ENABLE_FINEGRAINED_BANDWIDTH".

**Comment by vanpelt** [comment]
Yeah we've heard the the request for higher resolution metrics before.  We actually implemented it!  It's a switch on our backend that we can turn on for specific projects.  It's not currently exposed to the user but I could imagine letting users toggle it off and on.

**Comment by cvphelps** [comment]
This looks solved to me:
![image](https://user-images.githubusercontent.com/6355078/73032025-cf32d980-3e0b-11ea-8c80-ed3ea9ed7607.png)
