### ISSUE TITLE
[Q] How can I configure the hostname to access from the client side

### ISSUE THREAD

**Issue by pevogam** [wandb/client#3382]
Hi all,

I am running Jypiter server in a docker container and wanted to use W&B with local hosting. However, the local hosting exposes the `localhost:8080` while the client's default configuration after initialization seems to be:
```
machine api.wandb.ai
  login user
  password <api-key>
```
and the host where the actual server service is running in the case of default docker configuration is `172.17.0.1`. I tried overwriting this config but this doesn't improve the fact that I get "Permission denied" in the internal debug log and from what I can see the client keeps trying to connect to the remote cloud API address instead and always fails at the `wandb.init(project="X", entity="Y")` stage. Is there a way to configure the hostname in order to make the client work well from within a docker container on the same host?

**Comment by vanpelt** [comment]
Hey @pevogam if you're running local but accessing it from an IP address other than localhost:8080, you should set the HOST env variable: `wandb local -e HOST=http://172.17.0.1:8080`.

In terms of logging in your machines you have 3 different options:

1. From your terminal run `wandb login --host=http://172.17.0.1:8080`.
2. In your jupyter notebook rom `wandb.login(host="http://172.17.0.1:8080")`.  (_Only needed if you haven't done #1 or have a machine where the users home directory doesn't persist_)
2. Set the `WANDB_BASE_URL` environment variable to http://172.17.0.1:8080, and set the `WANDB_API_KEY` environment variable to your api key.  (_This method is generally used in automated environments like kubernetes or slurm_)

**Comment by pevogam** [comment]
Hi @vanpelt this all worked like a charm, thanks a bunch! Just as a side note it might be good if some of this is included in the documentation for self-hosted runs. At least I failed to find it there but I might be wrong.

**Comment by pevogam** [comment]
Hi again, after accommodating this sometimes I still get:
```
wandb: Appending key for 172.17.0.1 to your netrc file: /home/jovyan/.netrc
wandb: ERROR Attempting to use a local API key to connect to https://api.wandb.ai/
```
Is there an explanation why the API key would be used to connect to the FQDN `https://api.wandb.ai`?

My changes are exactly as suggested, i.e. starting locally with
```
wandb local -e HOST=http://172.17.0.1:8080
```
and in the jypiter notebook connecting as
```python
wandb.login(host="http://172.17.0.1:8080")
wandb.init(project="projX", entity="userY")
```
```
```

**Comment by vanpelt** [comment]
@pevogam we're aware of the regression and are working on a fix to be released today.  For now you can run `pip install --force wandb==0.12.11`, this will be fixed in 0.12.13

**Comment by pevogam** [comment]
Hi @vanpelt what you say probably makes sense in a different context since
```
# pip show wandb
Name: wandb
Version: 0.12.11
Summary: A CLI and library for interacting with the Weights and Biases API.
Home-page: https://github.com/wandb/client
Author: Weights & Biases
Author-email: support@wandb.com
License: MIT license
Location: /home/pevogam/.local/lib/python3.6/site-packages
Requires: python-dateutil, docker-pycreds, setproctitle, pathtools, GitPython, promise, protobuf, yaspin, requests, PyYAML, psutil, sentry-sdk, six, shortuuid, Click
Required-by: 
```

**Comment by pevogam** [comment]
> Hi @vanpelt what you say probably makes sense in a different context since
> 
> ```
> # pip show wandb
> Name: wandb
> Version: 0.12.11
> Summary: A CLI and library for interacting with the Weights and Biases API.
> Home-page: https://github.com/wandb/client
> Author: Weights & Biases
> Author-email: support@wandb.com
> License: MIT license
> Location: /home/pevogam/.local/lib/python3.6/site-packages
> Requires: python-dateutil, docker-pycreds, setproctitle, pathtools, GitPython, promise, protobuf, yaspin, requests, PyYAML, psutil, sentry-sdk, six, shortuuid, Click
> Required-by: 
> ```

I stand corrected, I guess you meant to fix the version for the client, I reported the server version above. Thanks, matters closed.
