### ISSUE TITLE
Experiment link robustness?

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#339]
Are the experiment links meant to be suitable for long-term storage? IE https://app.wandb.ai/yaroslavvb/transformer-xl/runs/qxh04lj4

Or are you guys still in beta and plan to change things around?

With promise of persistence I could save these links in readme's/code etc. IE, like with wolfram cloud objects, objects are accessible at same links years later ([example](https://www.wolframcloud.com/objects/67b4f45b-d2d8-401f-90ca-b806aa4c6b4b))

**Comment by vanpelt** [comment]
Yep, we will not break run links they're here to stay.  It's possible runs may be archived in the future but the links will still resolve.
