### ISSUE TITLE
[App]: New bell icon overlaps with plot

### ISSUE THREAD

**Issue by awsaf49** [wandb/client#3394]
### Current Behavior

I think the new bell icon has been moved from beside name to beside the last **pinned** column. This creates a bit problem if we have multiple pinned columns. Then, the bell icon overlaps with the existing plot hence it's difficult to understand if it's actually running or not.

### Expected Behavior

I think the previous position of the bell icon was very nice. 

### Screenshots

![image](https://user-images.githubusercontent.com/36858976/158718798-a604b484-c161-46df-9483-5f31c529c8c1.png)
![image](https://user-images.githubusercontent.com/36858976/158718879-7311356f-096a-4455-a778-50e3eec1079d.png)

### Environment

OS:

Browsers:

Version:

**Comment by armanhar** [comment]
Hey there, thank you for reporting this. I'll file a ticket for the engineering team.

**Comment by awsaf49** [comment]
I think this issue has been resolved :)
