### ISSUE TITLE
Default debug.log path permission problems on servers

### ISSUE THREAD

**Issue by Microsheep** [wandb/client#340]
* Weights and Biases version: 0.8.0
* Python version: 3.7
* Operating System: ubuntu 18.04

### Description
Default debug.log path might have permission problems on servers.
If two different users are using wandb on the same server, the default log location might collide and produce a permission problem which requires the first user or admin to resolve this.

### What I Did
```
wandb login XXX

wandb: ERROR Failed to set up logging: [Errno 13] Permission denied: '/tmp/wandb-debug.log'
```

I think this can easily be avoided if default debug.log path includes a timestamp
https://github.com/wandb/client/blob/master/wandb/__init__.py#L66

For example
```
cur_time = datetime.now().strftime("%Y%m%d-%H%M%S")
GLOBAL_LOG_FNAME = os.path.join(tempfile.gettempdir(), f"wandb-debug-{cur_time}.log")
```

Could submit a PR if needed.

**Comment by vanpelt** [comment]
It should just overwrite the previous debug log.  It looks like your "/tmp" directory is not writable.  I can update the code to use `tempfile.gettempdir()` which should return a writable directory.  Until then you can specify a directory with `WANDB_DIR=/home/username/tmp`

**Comment by Microsheep** [comment]
I think the problem is that another user using wandb had created the file '/tmp/wandb-debug.log' first.
As a second user, that file will not be writable. 

`tempfile.gettempdir()` returns a writable dir, but `os.path.join(tempfile.gettempdir(), 'wandb-debug.log')` is not writable.

Adding the timestamp by default just makes it harder for users to collide.

**Comment by vanpelt** [comment]
I see, but it's at the cost of making it hard to find the debug log as well as keeping lots of debug logs hanging around.  I thought `tempfile.gettempdir()` would return a different directory for each user.  I suppose I could see if the file exists and use a different name if it does.  For your usecase, it seems like setting WANDB_DIR to something unique for each user would fix this.

**Comment by ariG23498** [comment]
Hey @Microsheep due to the inactivity of this thread it is only fair if we knew whether you have the fix for your solution by now. We would rather want this thread closed if the solution to your issues are met. Cheers :smile:

**Comment by Microsheep** [comment]
Hi @ariG23498, I think we can close this issue for now.

To prevent collisions under `/tmp/` for different users on shared servers, we have already adopted guidelines to set directories according to usernames.
```
username = pwd.getpwuid(os.getuid()).pw_name
config.wandb_dir = f"/tmp/wandb_{username}/"
```

The original question mainly occurs when setting up the environment for the first time.
We opted to add the environment variable `WANDB_DIR` even for `wandb login`.

**Comment by louiskirsch** [comment]
Setting `wandb_dir` seems to have other side-effects in terms of changing not only the tmp directory but also
> Set this to an absolute path to store all generated files here instead of the wandb directory relative to your training script. be sure this directory exists and the user your process runs as can write to it

So I don't think this is an appropriate solution?

**Comment by vanpelt** [comment]
You can set the `TMPDIR` environment variable if the default system tmpdir isn't writable.

**Comment by yuvalkirstain** [comment]
@vanpelt I am also experiencing this issue. Can you please come up with a fix? 
Currently, I'm setting the `TMPDIR`, but it is not very elegant. 
Thank you :)

**Comment by sounakdey** [comment]
Same here experiencing the same issue ... `PermissionError: [Errno 13] Permission denied: '/tmp/debug-cli.log'`
