### ISSUE TITLE
[CLI]: Sporadic error in callback _WandbInit._resume_backend() in jupyter notebooks

### ISSUE THREAD

**Issue by zahar-chikishev** [wandb/client#3403]
### Describe the bug

After using a notebook for some time, the below error can appear. When it appears, no cell can be executed anymore. It is a state of notebook kernel. It is not clear what exactly triggers that state, does not look like a specific command.

```
Error in callback <function _WandbInit._resume_backend at 0x7f65b3a0df70> (for pre_run_cell):
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/venv/lib/python3.8/site-packages/backcall/backcall.py in adapted(*args, **kwargs)
    102                 kwargs.pop(name)
    103 #            print(args, kwargs, unmatched_pos, cut_positional, unmatched_kw)
--> 104             return callback(*args, **kwargs)
    105 
    106         return adapted

~/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in _resume_backend(self)
    307         if self.backend is not None:
    308             logger.info("resuming backend")
--> 309             self.backend.interface.publish_resume()
    310 
    311     def _jupyter_teardown(self):

~/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py in publish_resume(self)
    548     def publish_resume(self) -> None:
    549         resume = pb.ResumeRequest()
--> 550         self._publish_resume(resume)
    551 
    552     @abstractmethod

~/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py in _publish_resume(self, resume)
    268     def _publish_resume(self, resume: pb.ResumeRequest) -> None:
    269         rec = self._make_request(resume=resume)
--> 270         self._publish(rec)
    271 
    272     def _publish_run(self, run: pb.RunRecord) -> None:

~/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py in _publish(self, record, local)
     47     def _publish(self, record: "pb.Record", local: bool = None) -> None:
     48         if self._process_check and self._process and not self._process.is_alive():
---> 49             raise Exception("The wandb backend process has shutdown")
     50         if local:
     51             record.control.local = local

Exception: The wandb backend process has shutdown

Error in callback <function _WandbInit._pause_backend at 0x7f65b3a14280> (for post_run_cell):
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/venv/lib/python3.8/site-packages/backcall/backcall.py in adapted(*args, **kwargs)
    102                 kwargs.pop(name)
    103 #            print(args, kwargs, unmatched_pos, cut_positional, unmatched_kw)
--> 104             return callback(*args, **kwargs)
    105 
    106         return adapted

~/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in _pause_backend(self)
    302                 res = self.run.log_code(root=None)
    303                 logger.info("saved code: %s", res)
--> 304             self.backend.interface.publish_pause()
    305 
    306     def _resume_backend(self):

~/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py in publish_pause(self)
    540     def publish_pause(self) -> None:
    541         pause = pb.PauseRequest()
--> 542         self._publish_pause(pause)
    543 
    544     @abstractmethod

~/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py in _publish_pause(self, pause)
    264     def _publish_pause(self, pause: pb.PauseRequest) -> None:
    265         rec = self._make_request(pause=pause)
--> 266         self._publish(rec)
    267 
    268     def _publish_resume(self, resume: pb.ResumeRequest) -> None:

~/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py in _publish(self, record, local)
     47     def _publish(self, record: "pb.Record", local: bool = None) -> None:
     48         if self._process_check and self._process and not self._process.is_alive():
---> 49             raise Exception("The wandb backend process has shutdown")
     50         if local:
     51             record.control.local = local

Exception: The wandb backend process has shutdown
```

### Environment

WandB version: 0.12.10

OS: ubuntu

Python version: 3.8.10

**Comment by henilp105** [comment]
Hi , I am facing the same issue , and have tried WANDB_START_METHOD='thread' . Please help.

Thanks and Regards,
Henil

**Comment by sainisatish** [comment]
Hi , I am also faced this issue during fine tuning of a model.
`Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa8141a0d90>> (for pre_run_cell):
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:443, in _WandbInit._resume_backend(self, *args, **kwargs)
    441 if self.backend is not None and self.backend.interface is not None:
    442     logger.info("resuming backend")  # type: ignore
--> 443     self.backend.interface.publish_resume()

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/interface/interface.py:664, in InterfaceBase.publish_resume(self)
    662 def publish_resume(self) -> None:
    663     resume = pb.ResumeRequest()
--> 664     self._publish_resume(resume)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py:359, in InterfaceShared._publish_resume(self, resume)
    357 def _publish_resume(self, resume: pb.ResumeRequest) -> None:
    358     rec = self._make_request(resume=resume)
--> 359     self._publish(rec)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py:51, in InterfaceSock._publish(self, record, local)
     49 def _publish(self, record: "pb.Record", local: Optional[bool] = None) -> None:
     50     self._assign(record)
---> 51     self._sock_client.send_record_publish(record)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:221, in SockClient.send_record_publish(self, record)
    219 server_req = spb.ServerRequest()
    220 server_req.record_publish.CopyFrom(record)
--> 221 self.send_server_request(server_req)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:155, in SockClient.send_server_request(self, msg)
    154 def send_server_request(self, msg: Any) -> None:
--> 155     self._send_message(msg)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:152, in SockClient._send_message(self, msg)
    150 header = struct.pack("<BI", ord("W"), raw_size)
    151 with self._lock:
--> 152     self._sendall_with_error_handle(header + data)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:130, in SockClient._sendall_with_error_handle(self, data)
    128 start_time = time.monotonic()
    129 try:
--> 130     sent = self._sock.send(data)
    131     # sent equal to 0 indicates a closed socket
    132     if sent == 0:

BrokenPipeError: [Errno 32] Broken pipe
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa8141a0d90>> (for post_run_cell):
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:438, in _WandbInit._pause_backend(self, *args, **kwargs)
    436 if self.backend.interface is not None:
    437     logger.info("pausing backend")  # type: ignore
--> 438     self.backend.interface.publish_pause()

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/interface/interface.py:656, in InterfaceBase.publish_pause(self)
    654 def publish_pause(self) -> None:
    655     pause = pb.PauseRequest()
--> 656     self._publish_pause(pause)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py:355, in InterfaceShared._publish_pause(self, pause)
    353 def _publish_pause(self, pause: pb.PauseRequest) -> None:
    354     rec = self._make_request(pause=pause)
--> 355     self._publish(rec)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py:51, in InterfaceSock._publish(self, record, local)
     49 def _publish(self, record: "pb.Record", local: Optional[bool] = None) -> None:
     50     self._assign(record)
---> 51     self._sock_client.send_record_publish(record)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:221, in SockClient.send_record_publish(self, record)
    219 server_req = spb.ServerRequest()
    220 server_req.record_publish.CopyFrom(record)
--> 221 self.send_server_request(server_req)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:155, in SockClient.send_server_request(self, msg)
    154 def send_server_request(self, msg: Any) -> None:
--> 155     self._send_message(msg)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:152, in SockClient._send_message(self, msg)
    150 header = struct.pack("<BI", ord("W"), raw_size)
    151 with self._lock:
--> 152     self._sendall_with_error_handle(header + data)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py:130, in SockClient._sendall_with_error_handle(self, data)
    128 start_time = time.monotonic()
    129 try:
--> 130     sent = self._sock.send(data)
    131     # sent equal to 0 indicates a closed socket
    132     if sent == 0:

BrokenPipeError: [Errno 32] Broken pipe`

**Comment by sainisatish** [comment]
> Leslie commented: Hi, thank you for writing in! Can you set the environment variable to `WANDB_START_METHOD='thread'` and see if this helps? If it doesn't, can you send us your debug logs (internal-debug.log and debug.log) located in your wandb run directory so we can get more information on this issue?

I have also tried this but still producing same issue.

**Comment by thistlillo** [comment]
+1 here
