### ISSUE TITLE
[Q] How can I clean local wandb log files?

### ISSUE THREAD

**Issue by Cyberpuncrush** [wandb/client#3430]
Wandb is a perfact tool for logging and visualizing! However I found that each run's folder in local machine consume much more disk than in wandb.ai cloud, for example:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/57980447/160084367-8b06bb63-d91b-4170-bde3-db2c79ab06e8.png">
<img width="708" alt="image" src="https://user-images.githubusercontent.com/57980447/160084964-8f14894c-866d-490a-9b90-69a3a4154f2b.png">
I want to know why such a huge different in disk consumption and how can I clean local files(I just want to free more local disk space, and DO NOT want to delete them all, in order to save them as a local backup)
This really bothering me, I just consume ~5G in wandb.ai cloud, however more then 1T in local machine.
Can you help me?

**Comment by Cyberpuncrush** [comment]
Note that each run in my experiment log similar steps(~500), so experiment's log file size between each run should be close, what I want to show by these pics is `./log` folder and `xxx.wandb` file consume most disk space, and I don't know if I can delete them **safely**.

**Comment by armanhar** [comment]
Hey there, could you send a link to one of these runs and the debug logs?

**Comment by Cyberpuncrush** [comment]
As it is an on-going research, I can share local stored file and some screenshot for one run(if I open acess to one run, whole project would be public).
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/57980447/160409753-9045470a-6a75-4f2a-af83-8fd9663d794a.png">
files:
[run-20220328_161931-19mss86k.zip](https://github.com/wandb/client/files/8363226/run-20220328_161931-19mss86k.zip)
Salute 🫡

**Comment by armanhar** [comment]
@Cyberpuncrush You don't need to change the privacy of the project. If you share the link with us we can investigate, In the meantime I'll dig into the stuff you sent.

**Comment by vanpelt** [comment]
@Cyberpuncrush you can delete the local files safely if you can see them in the browser.  The local files are only there in the case of an inability to communicate with a server.  If you can see them on the server, it's safe to delete all files in your `./wandb` folder locally.

**Comment by Cyberpuncrush** [comment]
> @Cyberpuncrush you can delete the local files safely if you can see them in the browser.  The local files are only there in the case of an inability to communicate with a server.  If you can see them on the server, it's safe to delete all files in your `./wandb` folder locally.

Thanks! problem solved
