### ISSUE TITLE
[App]: Internal wandb error: file data was not synced

### ISSUE THREAD

**Issue by heintzcode** [wandb/client#3433]
### Current Behavior

Model training stops at an arbitrary point when the process is synced to the online app. Processes run fine when done 'offline'. The error has occurred at various times, eg ~1750 epochs, ~2000 epochs, ~4000 epochs. The error message is clear but the cause is not; why would a local log file suddenly become unavailable?

```
<Normal logging...>
epoch: 1500, loss:  2.184e+06, time:   934.3, log_vars: 14.7473, -0.3149
epoch: 1750, loss:  9.470e+05, time:  1091.9, log_vars: 14.4531, -0.3113
Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_util.py", line 54, in run
    self._run()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_util.py", line 105, in _run
    self._process(record)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal.py", line 312, in _process
    self._sm.send(record)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\sender.py", line 237, in send
    send_handler(record)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\sender.py", line 830, in send_summary
    self._update_summary()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\sender.py", line 842, in _update_summary
    with open(summary_path, "w") as f:PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Iblah\\blah\\blah\\wandb\\run-20220324_140524-2zt53myz\\files\\wandb-summary.json'
wandb: ERROR Internal wandb error: file data was not synced
```

And then tracebacks from a particular log command:
`run.log({"train/loss":loss.item()**.5})`
leading to 
`Exception: The wandb backend process has shutdown`

### Expected Behavior

Expectation is for model training to continue through the prescribed number of epochs, with pretty standard logging statements. Instead it breaks at arbitrary times.

### Environment

OS: Windows

Browsers: MS Edge

Version: MS Edge Version 99.0.1150.46 (Official build) (64-bit)

### Additional Context

Earlier I'd run up to 10k epochs with pretty much the same code. I changed the loss function and the models a bit, but not sure why it would affect logging, in particular why anything I did in the model building code would affect access to a log file on my local file system.

**Comment by nate-wandb** [comment]
Hi @heintzcode,
I'm sorry you're getting this issue. Is the directory that your `wandb` folder is in a network synced directory? Such as One Drive or Dropbox?

It seems that Python lost permissions to this folder for some reason which is usually related to network synced folders. If this isn't the case is there any other changes that have been made that could have cause this interruption in permissions?

Thank you,
Nate

**Comment by heintzcode** [comment]
Hi, yes, it is a synced folder. Are you suggesting that I move the log directory to a folder that is not network synced?

**Comment by nate-wandb** [comment]
@heintzcode that would be my recommendation but if running scripts from your network directory is necessary you should be able to specify `wandb.init(dir=<path/to/non-synced/directory>)` and W&B will create the run folder outside of the network drive. This will allow you to run from the network synced drive but your runs metadata will be saved elsewhere. 

Another option would be to adjust the permission settings of your network directory to allow Python write access to your network directory.

**Comment by heintzcode** [comment]
I did the first and that seems to have addressed the problem. Thanks for your response.

**Comment by orena1** [comment]
@nate-wandb I get this error:
```
Thread HandlerThread:
Traceback (most recent call last):
    if not pathlib.Path(NEURON_LS_COMMAND[0]).exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [Errno 5] Input/output error: '/opt/aws/neuron/bin/neuron-ls'
```
I am not sure how this path `/opt/aws/neuron/bin/neuron-ls` is related, do you have any idea what is going on?

**Comment by orena1** [comment]
@raubitsj any idea?

**Comment by orena1** [comment]
@tonyyli-wandb @kptkin @jacobromero any idea what is this ?
https://github.com/wandb/wandb/issues/3433#issuecomment-2571335935
Should I open a new ticket?

**Comment by Mediaabsorbing508** [comment]
> [@tonyyli-wandb](https://github.com/tonyyli-wandb) [@kptkin](https://github.com/kptkin) [@jacobromero](https://github.com/jacobromero) any idea what is this ? [#3433 (comment)](https://github.com/wandb/wandb/issues/3433#issuecomment-2571335935) Should I open a new ticket?





https://pythoner.space/questions/sorry-you-do-not-have-permission-to-access-this
