### ISSUE TITLE
[Q] PermissionError: [Errno 13] Permission denied: '/tmp/debug-cli.log'

### ISSUE THREAD

**Issue by coderlemon17** [wandb/client#3437]
### Describe the bug

Hi, I'm currently working on a group-shared Linux machine, which means the authority setting is pretty strict. I think the issue is mainly caused because I don't have enough permission. However, I just wonder is this log directory customizable? Or maybe can I disable this logging completely?

```shell
» wandb
Traceback (most recent call last):
  File "/home/zhouxinning/CodeApps/Anaconda/anaconda3/envs/pyg_cuda/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/home/zhouxinning/CodeApps/Anaconda/anaconda3/envs/pyg_cuda/lib/python3.7/site-packages/wandb/cli/cli.py", line 53, in <module>
    datefmt="%Y-%m-%d %H:%M:%S",
  File "/home/zhouxinning/CodeApps/Anaconda/anaconda3/envs/pyg_cuda/lib/python3.7/logging/__init__.py", line 1898, in basicConfig
    h = FileHandler(filename, mode)
  File "/home/zhouxinning/CodeApps/Anaconda/anaconda3/envs/pyg_cuda/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/zhouxinning/CodeApps/Anaconda/anaconda3/envs/pyg_cuda/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/debug-cli.log'
```
Just a few additional info:
- I do check the permission of `/tmp` and it's `drwxrwxrwt  358 root    root    2.3M Mar 29 10:50 tmp`, and I think the permission looks enough to me.
- I try `touch /tmp/debug-cli`, it works, but `touch /tmp/debug-cli.log` does trigger a permission denied, if anyone knows how to correct the permission, it'll also be appreciated.

### Environment

WandB version: 0.12.11

OS: Ubuntu 18.04.5 LTS

Python version: Python 3.7.11

**Comment by coderlemon17** [comment]
Found the reason, another person in my group has already created `/tmp/debug-cli.log`, so I don't have permission to change or remove his file.
So I think the solution can either be setting a customizable output directory or adding a user-specific postfix for the filename.

**Comment by coderlemon17** [comment]
A current workaround for me is to modify this line: [cli.py](https://github.com/wandb/client/blob/c42c130b285ddb593dcb9c0c1d431a1a3629361b/wandb/cli/cli.py#L50). Hopefully, you can find a more stable solution.

**Comment by nate-wandb** [comment]
Hi @coderlemon17, you can specify the run directory with `wandb.init(dir="<path/to/dir/with/permissions>")` and I think this will solve you issue for you. Let me know if this is not what you were looking for.

Thank you,
Nate

**Comment by coderlemon17** [comment]
Yeah, I think that might work, but I was using the shell interface so the problem occurs. Anyway, the workaround works for me now, and I thought it's better to let you guys know, closing the issue now.
