### ISSUE TITLE
[Q] What word bank/corpus is used when generating run names for sweeps or upload artifacts?

### ISSUE THREAD

**Issue by evdcush** [wandb/client#3478]
Can someone point me to the location in the code where run names are generated for sweep runs or uploaded artifacts, as well as the word bank or corpus from which the names are generated?

**Comment by ramit-wandb** [comment]
Hi @evdcush,

The word bank which is used for our run name generation in under a private repo, but the code used to generate the run names is based on [this repository](https://github.com/goombaio/namegenerator).

Please let me know if I can help with anything else.

Thanks,
Ramit

**Comment by evdcush** [comment]
Hi @ramit-wandb,
I'm wondering why the word bank would be private, but I appreciate your response and sharing what you can, thank you!
