### ISSUE TITLE
[Feature]: download the whole data of an experiment in a python pickle

### ISSUE THREAD

**Issue by MiladInk** [wandb/client#3501]
### Description

Hi wandb community. 

As far as I know one can download the csv data of a plot or export a table to csv. However, I am wondering if there can be any feature that lets researchers and machine learning practitioners download the whole data that is bound to one of their experiments maybe in a pickle maybe in a python dictionary format?

something like:
{(step:1, loss: 120), (step:2, loss:80)}

### Suggested Solution

Let the user download their data.

**Comment by ramit-wandb** [comment]
Hi @MiladInk,

We do allow for all your data from a run to be downloaded programmatically through our Public API. [Here](https://docs.wandb.ai/guides/track/public-api-guide#read-metrics-from-a-run) is an example illustrating how to read metrics from a run. The metrics are downloaded as a Pandas Dataframe, so they can be easily serialized and stored.

Please let me know if this doesn't fullfill your use case and what might be missing, and I will be happy to open a feature request for you.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @MiladInk, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​

**Comment by abhisheknaik96** [comment]
Hello, how can I download the data of multiple runs at once? 

The use-case I have in mind is downloading the data from a set of runs (if say, I run out of space on the wandb cloud), deleting the cloud copies, and having the option to upload the now-local copy to the wandb cloud at a later point.

**Comment by SimonKoop** [comment]
@abhisheknaik96 have you found a good way to do this? Because your example use case is exactly what I'm dealing with and I'd love to hear if you've made it work.

**Comment by lucasdevries** [comment]
Same here. Just looking for a download all button for a project to deleter the cloud copy afterwards..

**Comment by tlpss** [comment]
I would also love to have this feature
