### ISSUE TITLE
[Q] How to force stop runs?

### ISSUE THREAD

**Issue by Yoonho-Na** [wandb/client#3506]
In wandb.ai I clicked stop for some runs but it won't stop even I waited few hours.

It just keeps showing stopping.

<img width="369" alt="스크린샷 2022-04-11 오후 2 31 13" src="https://user-images.githubusercontent.com/53941554/162670949-b439ef95-13e5-4578-ad5e-2a98af2834ce.png">

is there any way to force stop those runs?

I want to delete it but It won't.

**Comment by armanhar** [comment]
Hey there, we are investigating the issue at the moment. Could you share the link to the run?

**Comment by armanhar** [comment]
Hey @Yoonho-Na, are you still experiencing this?

**Comment by Yoonho-Na** [comment]
I haven't stopped any runs after that.

I'll inform you when it happens again.

thank you.

**Comment by lucienwang1009** [comment]
Hi, I run into the same issue, the run path is lucienwang/mvtec/1fgsjbvc.

**Comment by armanhar** [comment]
Hey @lucienwang1009, did you delete the run? I can't find a run with the specified id.

**Comment by lucienwang1009** [comment]
Hi @armanhar, yes I deleted it as it stopped somehow. Thank you.

**Comment by fereenwong** [comment]
@armanhar Hi, in wandb, the log state is always running no matter whether the project is finished or not. And the stop running bottom does not work
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/43628797/195375070-28b4abcc-f6ac-4064-a4f1-4eb87146212b.png">

**Comment by AroofAimen-wai** [comment]
I am facing the same issue too. I don't want to delete the run but it just dosn't stop.

**Comment by liuyaox** [comment]
I run into the same issus: https://wandb.ai/littlecatx/huggingface/runs/mrk8sx6n/overview
