### ISSUE TITLE
[Q] wands.log stops uploading to the server

### ISSUE THREAD

**Issue by andrewliao11** [wandb/client#3515]
### Describe the bug

I used wand.log({"my_loss": loss, "epoch": epoch}) to log the training curves. The run successfully run till the end (200 epochs) and from the local wandb file `wandb/run-<date>-<run_id>/files/wandb-summary`, it successfully logs the values until the final epoch. However, on the wandb server, it stops at the 115th epoch (I tried many times and the number it stops is unpredicable).

Is there any way that I can retrieve those missing values? or maybe are they supposed to be stored somewhere in my local machine? under `wandb/run-<date>-<run_id>`

I am using wandb 0.12.11 

```python 

```

```shell

```

### Environment

WandB version: 0.12.11 

OS: Ubuntu Ubuntu 16.04.5 LTS 

Python version: 3.7.11

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Hi @andrewliao11,

Yes! It is absolutely possible to upload this data back up. You can use `wandb sync` to do so. You are right, the folders under `wandb/run-<datetime>-<run-id>` store the run data locally.

Thanks,
Ramit

**Comment by andrewliao11** [comment]
Thanks! `wandb sync wandb/<file_name>` works for me!

**Comment by 07Agarg** [comment]
Hi, I am constantly getting this wandb log even after the experiment has been stopped. I have deleted the experiment also. 
How to stop this log? 
```wandb: | 0.030 MB of 0.034 MB uploaded (0.000 MB deduped) ```

I tried ``` wandb sync --clean ``` also but that didn't work for me. 

Thanks for the help, 
Ashima
