### ISSUE TITLE
[App]: 

### ISSUE THREAD

**Issue by Dianagle2** [wandb/client#3536]
### Current Behavior

When running more than 1 training with the same wandb.tensorboard.patch(root_logdir=logdir) having this error:
ValueError: Tensorboard already patched, remove `sync_tensorboard=True` from `wandb.init` or only call `wandb.tensorboard.patch` once.

Because the last wandb.tensorboard.patch() is still active 

 

### Expected Behavior

Being able to initializing again the wandb.tensorboard.patch (wandb.patched["tensorboard"]),
and being able to change the root_logdir of wandb.tensorboard.patch for each run. 

### Screenshots

<img width="744" alt="image" src="https://user-images.githubusercontent.com/70809604/164052345-fb18c923-a5aa-4b48-bb65-15d6964ff103.png">

### Environment

OS: Linux

Browsers: Chrome
Inside JupyterLab

Version: 0.12.14

**Comment by anmolmann** [comment]
Hi @Dianagle2, could you please also share:
1. How you're trying to structuring your `.tfevents` file?
2. What use-case do you have to change the root logdir multiple times in the same process?
3. Also, are you using `sync_tensorboard = True` along with `wandb.tensorboard.patch`?

**Comment by Dianagle2** [comment]
Thank you for answering .
I have an outer loop to run few training sessions one after another. 
1. I'm writing to tf.summary my metrics. 
2. I wish to change my logdir because for every run I'm making a new logdir to write my logs into.
3. Yes I'm also using sync_tensorboard = True. Even if i will remove it, it still causes the same error.

**Comment by anmolmann** [comment]
Thanks for the details @Dianagle2. Could you please also share your code snippet as well? This would help us in reproducing the issue on our end.
Also, did you face this issue before for cli version < v0.12.4? This would help us determine if this is a regression on our or a logical descision.

**Comment by anmolmann** [comment]
Hi @Dianagle2 , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by Dianagle2** [comment]
I've fixed the error with using:
if len(wandb.patched["tensorboard"]) > 0:
        wandb.tensorboard.unpatch()
I don't know if this is something you planned to use. 

I just have:
  wandb.tensorboard.patch(root_logdir=logdir)
  run = wandb.init(project="my-project", name=f"experiment_{time()}", sync_tensorboard=True, reinit=True)
  wandb.config.update(args)
  config = wandb.config

.... (My training)

wandb.finish()

probably the reason why after i do finish, 'patch' stays because I'm using jupyterlab. 

Thanks for the help :)

**Comment by anmolmann** [comment]
Thanks for the update @Dianagle2.
