### ISSUE TITLE
[App]: Wandb for Huggingface Trainer shows logs for only first model

### ISSUE THREAD

**Issue by kgarg8** [wandb/client#3537]
### Current Behavior

I am finetuning multiple models using a for loop but `wandb` website shows only one experiment.

### Expected Behavior

`wandb` website should show logs and plots for all models.

### Steps To Reproduce

I am finetuning multiple models using for loop as follows. 

```
for file in os.listdir(args.data_dir):
    finetune(args, file)
```

BUT `wandb` website shows plots and logs only for the first file i.e., `file1` in `data_dir` although it is training and saving models for other files. It feels very strange behavior.

```
wandb: Synced bertweet-base-finetuned-file1: https://wandb.ai/***/huggingface/runs/***
```

This is a small snippet of **finetuning** code with Huggingface:
```
def finetune(args, file):
    training_args = TrainingArguments(
        output_dir=f'{model_name}-finetuned-{file}',
        overwrite_output_dir=True,
        evaluation_strategy='no',
        num_train_epochs=args.epochs,
        learning_rate=args.lr,
        weight_decay=args.decay,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        fp16=True, # mixed-precision training to boost speed
        save_strategy='no',
        seed=args.seed,
        dataloader_num_workers=4,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset['train'],
        eval_dataset=None,
        data_collator=data_collator,
    )
    trainer.train()
    trainer.save_model()
```

### Environment

OS: MacOS 10.14.6

Browsers: Chrome 100.0.4896.88 (Official Build) (x86_64)

Version:
python 3.7.11
wandb 0.12.14

**Comment by anmolmann** [comment]
@kgarg8, could you please also share your W&B workspace link in which you're saving the model?
Also, in order [to log models](https://docs.wandb.ai/guides/integrations/huggingface#turn-on-model-versioning), you could also set the env var `WANDB_LOG_MODEL` as [specified in our docs here](https://docs.wandb.ai/guides/integrations/huggingface#additional-w-and-b-settings). Once you set this env var, any Trainer you initialize from now on will upload models to your W&B project.

Note that your model will be saved to W&B Artifacts as `run-{run_name}`.

**Comment by anmolmann** [comment]
@kgarg8 , I'll go ahead and close out this issue as this was [resolved in our community forums](https://community.wandb.ai/t/wandb-for-huggingface-trainer-saves-only-first-model/2270/3?u=anmolmann).
