### ISSUE TITLE
Memory leak using pytorch

### ISSUE THREAD

**Issue by AliRazavian** [wandb/client#354]
* Weights and Biases version: 0.8.1
* Python version: 3.6.7
* Operating System: Ubuntu 18.04

### Description

It seems to me that when I log pytorch tensor values, I end up with memory leak, and it is quite severe (my code consumes around 40GB of memory in less than an hour just by logging the loss values), but if I log `tensor.item()` memory leak disappears. 

logging tensor:
![without](https://user-images.githubusercontent.com/12988205/58555224-36ff3900-8219-11e9-8d90-0f97861d6ff6.png)

logging tensor.item()

![with](https://user-images.githubusercontent.com/12988205/58555300-63b35080-8219-11e9-91cc-812fd80a9f52.png)

**Comment by vanpelt** [comment]
That’s not good.  To clarify, you were calling `wandb.log({loss: single_element_tensor})` which was causing the leak, and calling item stopped the leak?

**Comment by vanpelt** [comment]
This is fixed in 0.8.2
