### ISSUE TITLE
[App]: Some plots disappear after the run is finished.

### ISSUE THREAD

**Issue by mehravehs** [wandb/client#3544]
### Current Behavior

All my train and validation accuracy and loss plots disappear after the run is finished (and sometimes in the middle of the run.)

### Environment

OS: Linux

Browsers: Chrome and Safari

Version: version 0.12.14

**Comment by sydholl** [comment]
Hi @mehravehs. Thank you for reporting and sorry for the inconvenience. Our backend team is addressing the issue and we should have this resolved shortly. I'll follow up once I have an update on this.

**Comment by sabetAI** [comment]
I'm still having this issue

before:
![image](https://user-images.githubusercontent.com/28828395/227736634-8a0ca1a3-f1e6-41d5-9680-8c1074a2d461.png)

after:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/28828395/227736672-539ab1e3-db9d-455c-87e2-4d7b68829f69.png">

**Comment by g-lopes** [comment]
I am also having this issue. Any news on that?

**Comment by dinonovak** [comment]
I am also having the same issue just now.
after wandb.finish() I am just left with single point on train/loss graph

**Comment by tpurtell** [comment]
It happens every time it finishes for me too

**Comment by tpurtell** [comment]
@dinonovak  I stumbled across this because I thought it was happening to me too,  but it turns out I wasn't looking closely.  train/total_loss appears on the first screen after the run finishes and train/loss is bumped to the second page.  Double check it
