### ISSUE TITLE
[Q] Is there a way to tell whether wandb is initialized?

### ISSUE THREAD

**Issue by jojo23333** [wandb/client#3551]
As titled, I want some logic like
`if wandb.is_initialized():
    wandb.log()
`
is there such an api for accessing wandb status?
Many thanks!

**Comment by ramit-wandb** [comment]
Hi @jojo23333,

When a run is not initialized, the `run` object is set to `None`. Therefore, you should be able to do the following:

```python3
if wandb.run is not None:
    wandb.log()
```

Thanks,
Ramit
