### ISSUE TITLE
[Q] How to check the storage of a single run or a project in wandb

### ISSUE THREAD

**Issue by Marxlp** [wandb/client#3554]
I want to know the used storage after each run. I know the  [https://wandb.ai/subscriptions](https://wandb.ai/subscriptions) wil give me information of storage of all the runs in my account. But I want to know it for a single run. How could I make it?

**Comment by ash0ts** [comment]
Hello @Marxlp,

I have attached a video showing how to go about accessing the storage information of runs and artifacts for a project. Let me know if you have any questions. 

Uploading Screen Recording 2022-04-22 at 2.21.01 PM.mov…

**Comment by Marxlp** [comment]
Thanks a lot. It cann't be more clear.

**Comment by trevineoorloff** [comment]
Hi, 
Could you please let me know how to access the first page on the above screen recording? Thanks
