### ISSUE TITLE
[Feature]: early terminate on NaN during hyperparameter sweeping

### ISSUE THREAD

**Issue by wztdream** [wandb/client#3563]
### Description

Hi,
During hyperparameter sweeping it is possible that a run it will trigger NaN. But current wandb will continue the run with NaN, and this is a waste of computation resource. It will be better wandb can early terminate these kind of runs and trigger a alarm to the users will be better.

### Suggested Solution

Early terminate the  NaN, and trigger alarm for the users

**Comment by ramit-wandb** [comment]
Hi @wztdream,

This should already be possible. The following little code snippet should do this for you:

```python3
if torch.isnan(loss):
    wandb.alert(f'Loss is NaN')     # Will alert you via email or slack that your metric has reached NaN
    raise Exception(f'Loss is NaN') # This could be exchanged for exit(1) if you do not want a traceback
```

While I have assumed usage of `torch` here, this should be possible in any framework. Please let me know if there is anything else I can do for you.

Thanks,
Ramit

**Comment by wztdream** [comment]
@ramit-wandb 
Nice! thank you.
