### ISSUE TITLE
[Q] Relevance for general purpose research (not ML)

### ISSUE THREAD

**Issue by Avidanborisov** [wandb/client#3573]
Hi!

A friend showed me this platform, and I have found many of its features interesting for general purpose research, not related to ML at all.
Is this platform generally suitable for non-ML environments too? How easy is it to set it up with something else?

**Comment by Avidanborisov** [comment]
Hi Arman!
I have a complex system that I'm trying to optimize performance-wise. I currently have a semi-automatic system where I can modify some code and some configuration options, run tests and generate data and graphs, using matplotlib and plotly. I keep the results manually on my test server, with a folder for each experiment.
I'm interested in making this process more scalable, organized, reproducible and so forth. The main objective is that each experiment will be logged, with all of its hyperparameters (which are the config options + git tag/commit) and result data and graphs easily and nicely accessible, just as for ML experiments.
Now, assuming I'm willing to invest in this non-out-of-the-box integration with with wandb, I'm just wondering if this is generally supported, whether there are some non-trivial challenges with this idea and so on.

Thanks!

**Comment by armanhar** [comment]
Hey @Avidanborisov, apologies about the late response on this. While we specialize on Deep Learning everything you mentioned is possible with W&B. W&B [automatically logs the git commit](https://docs.wandb.ai/guides/track/launch#how-can-i-save-the-git-commit-associated-with-my-run). You can [log metrics](https://docs.wandb.ai/ref/python/log) and wandb will generate the charts or you can [log matplotlib or plotly charts](https://docs.wandb.ai/guides/track/log/plots#matplotlib-and-plotly-plots). Please let me know if this answers your question.

**Comment by armanhar** [comment]
​Hi @Avidanborisov, I wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by Avidanborisov** [comment]
Yes, thanks :)
