### ISSUE TITLE
Feature request: An option to invert the y-axis log scale for visualizations.

### ISSUE THREAD

**Issue by elliotwaite** [wandb/client#358]
When a visualization plots a value that approaches the bottom of the graph (such as loss), enabling the y-axis log scale helps by showing more detail in the lower values, but when the visualization plots a value that approaches the top of the graph (such as accuracy), enabling the y-axis log scale squashes the values at the top, making them less readable.

It would be nice to have an option to invert the y-axis log scale so that values towards the top would be expanded.

This screenshot shows how enabling the y-axis log scale helps with the loss, but makes the accuracy harder to read.

![log-demo](https://user-images.githubusercontent.com/1767836/58744889-75951f00-83e4-11e9-811f-aa682651b983.png)

**Comment by tsholmes** [comment]
hey @elliotwaite we recently released a feature which should help with this. You can now specify a custom expression to map the y-axis values and the advanced tab while editing a graph. Inverting the accuracy with `1 - acc` will allow you to use the log y scale to better see changes in the error rate. If any of your acc values hit 1, the error rate will be 0, which will break the log scale (`log 0` is undefined), so you can add a small offset value (`1 - acc + 1e-9`)

![Screen Shot 2019-06-10 at 4 09 28 PM](https://user-images.githubusercontent.com/2865426/59232719-707d6000-8b9a-11e9-9d80-993aa7148c5f.png)

**Comment by elliotwaite** [comment]
Interesting. Is there a way to try it out yet? I don't see any tabs on the edit-visualization modal window.

**Comment by tsholmes** [comment]
@elliotwaite It's currently only available on the project page or in a report (not on the page for a single run). We'll be expanding it to all pages soon.

**Comment by elliotwaite** [comment]
Ah, I see. In my opinion, this feature doesn't add much since it's already possible to do this by just logging different values, such as logging both the accuracy and the error:
```
wandb.log({'acc': acc, 'error': 1 - acc + 1e-9})
```

The feature I'm interested in is one that would invert the y-axis log scale so that I could see more detail in the accuracy values. I don't want to mentally have to do the conversion of error to accuracy when reading the graph (e.g. reading 0.143 and having to calculate 0.857 accuracy).

Perhaps you could implement a log intensity slider that would allow for adjust the log scaling in both the positive and negative directions. Here's an example of how it might work: https://www.desmos.com/calculator/maffkvkvki

You can adjust the "log intensity slider" at the top, and you can also change the data points to see how the scaling would adapt to changes in the minimum and maximum data values. Not a perfect implementation, but it demonstrates the idea.

**Comment by elliotwaite** [comment]
Here's a better version. The grid lines are for actual significant values, and the height of the displayed graph stays constant:
https://www.desmos.com/calculator/y6zxcvd0y3

**Comment by lukas** [comment]
I think this a perfect use case for our custom vega plots
