### ISSUE TITLE
Entering a smoothing number without a leading zero doesn't work (e.g. ".5").

### ISSUE THREAD

**Issue by elliotwaite** [wandb/client#359]
When using the online dashboard, if you enter a smoothing number for a visualization using the text input field, it requires that you add a leading zero (e.g. "0.5"). It would be nice if it would allow floating point numbers that start with a decimal (e.g. ".5"). At first, I thought the text input field was broken and that you could only use the slider until I realized it required the leading zero.

**Comment by vanpelt** [comment]
Thanks @elliotwaite we added this to our backlog!
