### ISSUE TITLE
Feature request: An easy and intuitive way to edit projects and delete empty projects.

### ISSUE THREAD

**Issue by elliotwaite** [wandb/client#363]
When using the online dashboard, I haven't found a way to edit projects (change their name, description, privacy level). Let me know if it exists and I just haven't found it. But this would be a nice feature to have.

Also, there is an option to delete a project by using the menu in the top right of the project page, but when the project is empty, that menu button isn't displayed. It would be nice to be able to delete an empty project. Perhaps this menu button could remain visible even when the project is empty.

**Comment by cvphelps** [comment]
Hey there @elliotwaite, all great ideas. These can be better supported, but here's how you do them right now:

Change project name
- Create a project with the new, correct name
- Go to the old project and select all your runs in the table
- Click "Move" and select your new project

Change project description
- Click on the project description at the top of the project page to edit the text

Change project privacy level
- Click on the colored privacy badge
- Change settings in the modal that pops up

Delete projects
- Run a random run with wandb.init(project="project-to-delete") and then delete that project from the UI

Thanks for bringing these issues up! It would be great to make all these features better supported.

**Comment by elliotwaite** [comment]
Ah, got it. Thanks for pointing those options.
