### ISSUE TITLE
[Q]

### ISSUE THREAD

**Issue by YerePhy** [wandb/client#3630]
Hi everyone!

**Questions**
- Is it possible to train a model in a K-Fold set up with the [PyTorch Lightning Loop API](https://pytorch-lightning.readthedocs.io/en/stable/extensions/loops.html) and use [WANDB as logger](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.wandb.html)?
- How are the logs managed? What is logged in WANDB? How WANDB shows the results of the different folds?
- What about multi GPU/clusters in this scenario?

**Comment by ash0ts** [comment]
Hello @YerePhy 

- What do you mean by the `Loop API`? Regardless you can use `wandb` for a variety of uses for your modeling task as shown in this [image](https://1039519455-files.gitbook.io/~/files/v0/b/gitbook-legacy-files/o/assets%2F-Lqya5RvLedGEWPhtkjU%2F-MjWyygstFtfMrBD1N_X%2F-MjWzA_zt-9vgPF0IXgn%2FW%26B%20Diagram%20-%2020210913.png?alt=media&token=4ef27c1e-dc8b-43cf-9435-99ba770bc42d) present in our [documentation](https://docs.wandb.ai).

If you are using experiment tracking you can log immediately using
```
wandb.init(project='my-xgb', config={'lr': 0.01, ...})
wandb.log({'loss': loss, ...}) 
```

We offer many resources on how to also utilize our [Hyperparameter Tuning via Sweeps](https://docs.wandb.ai/guides/sweeps), [Dataset Versioning via Artifacts](https://docs.wandb.ai/guides/artifacts), and [Model Evaluation via Tables](https://docs.wandb.ai/guides/data-vis).

- If you are using our public cloud offering your logs are stored securely in our cloud storage. How those logs are managed in a dashboard is up to you! Depending on how you logged your information, (which can be anything using our convenient [Artifacts](https://docs.wandb.ai/guides/artifacts/artifacts-core-concepts)), you can format your logged data in a way such that you can make [Parallel Coordinate plots](https://1039519455-files.gitbook.io/~/files/v0/b/gitbook-legacy-files/o/assets%2F-Lqya5RvLedGEWPhtkjU%2F-M_7vqy0Heo24R5CC-VE%2F-M_7wfoOXtNBgFUGFwyT%2Fimage.png?alt=media&token=95a1c634-a65b-4765-aac6-1015e53072d5) or use [Tables to select your visualization of choice](https://docs.wandb.ai/guides/data-vis/tables)

- Weights and Biases 🤝 Multi GPUs/Clusters. [We offer a variety of resources showing how to use Distributed Training techniques alongside `wandb`. ](https://docs.wandb.ai/guides/track/advanced/distributed-training).

[We have a large repo of examples of different workflows and frameworks available to use as a good reference. I'd suggest taking a look!](https://github.com/wandb/examples)

**Comment by YerePhy** [comment]
Hi @ash0ts, 

Sorry, but I forgot to add "PyTorch Lightning" before "Loop". PyTorch Lightning has an API that allows you to modify the training loop. One of the possibilities is to configure a K-Fold based training.

I am a WANDB and Lighting user for almost a year and a really appreciate WANDB tracking functionality (I have developed 2 deep learning projects). However, I have never seen a WANDB+Lightning example with a K-Fold set up, so I don't have an idea of how WANDB manage logs in this scenario, how many runs are launched, etc.

Thanks in advance.

**Comment by ash0ts** [comment]
Hello @YerePhy,

[There is a related thread](https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1651223213462089) on the[ official PTL Slack channel](https://www.pytorchlightning.ai/community)

To recap what they said:

> You should be able to write a simple function using our [kfold example](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/loop_examples/kfold.py) and return the average results from each kfold to wandb which you use to orchestrate the sweep.

> Note: You could also have a look at [pl_cross](https://github.com/SkafteNicki/pl_cross) from @Nicki Skafte who handles the kfold and the model ensembling

> The only “issue” I see here is how to organize logging. @Nicki Skafte does it with a unique version per fold, however this would mean that you would get a new w&b run for each fold in each run of the sweep. You could also try to customize the loggers he offers to add a logging prefix corresponding to the fold, that way you would have all the results in one run for the entire kfold

Let me know if these resources help!

**Comment by ash0ts** [comment]
We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by YerePhy** [comment]
I am a little bit overwhelmed with the projects I am driving now. I will try your proposal without no doubt when implementing K-Fold in the already mentioned projects.

I will mark this as solved and maybe I will upload a tutorial/example of how to perform K-Fold with the described set up or at least with single GPU and track the results in WANDB.

Thanks and sorry for the delay.

**Comment by ash0ts** [comment]
@YerePhy

No need for the apology! I hope the resources I provided were able to help (and that your other projects go well!). 

If you do end up creating a tutorial/example utilizing K-Fold in this set up we would love to share this with our community! Feel free to drop your submission to https://wandb.ai/fully-connected.

Happy experimenting!
