### ISSUE TITLE
[Q] Is there a way to delete multiple files in a project by pattern matching?

### ISSUE THREAD

**Issue by Chianugoogidi** [wandb/client#3633]
My specific use case: I have a project where I upload PyTorch checkpoints named `latest.pt` at the end of every run. I am on the Basic Storage Plan and I'm running out of space. I have hundreds of runs at this point and would like to delete the checkpoints to conserve some space. How do I select and delete all files named `latest.pt` in all the runs under my project? I'm currently doing this manually and it's tedious.

Thanks in advance for the help.

**Comment by armanhar** [comment]
Hey @Chianugoogidi, you can use our Public API for that. Here is a code exaple:
```
import wandb
api = wandb.Api()

runs = api.runs("<entity>/<project>")
file_name = "latest.pt"

for run in runs:
    files = run.files()
    for file in files:
	if file.name == file_name:
		file.delete()
```
Best,
Arman

**Comment by armanhar** [comment]
Hey @Chianugoogidi, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
​

**Comment by Chianugoogidi** [comment]
That worked. Thanks!
