### ISSUE TITLE
[Q] logging code run.log_code()

### ISSUE THREAD

**Issue by rogelioamancisidor** [wandb/client#3635]
Apart from saving the code from my main training file, say `main.py`, where `wandb.init()` is, I want to log other files that are used in `main.py`, e.g. `utils.py` that is located in the same folder, but I do not want to log all `py`files in the folder. 

Can I use `wandb.run.log_code()` for such a purpose?

**Comment by rogelioamancisidor** [comment]
@ash0ts I dont want to log all `.py` files, only some of them.

**Comment by ash0ts** [comment]
@rogelioamancisidor 

The provided example was demonstrative on how to utilize both the `include_fn` and/or `exclude_fn` parameters. As the paths within a folder are a string you can use any string methods/functions that return a `boolean` to determine if said file will be included/excluded.

Example: `run.log_code("../", include_fn = lambda path: path.startswith("main") or path.startswith("utils"))`

**Comment by rogelioamancisidor** [comment]
thanks!
