### ISSUE TITLE
logging environment variables?

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#364]
Is there a recommended way to log environment variables? I feel they logically belong under "Overview" tab.

Env vars in general can contain secrets, but there is a common set of env config vars that are useful for debugging

gpu environment
`NCCL_*, CUDA_*`

mpi environment:
`WORLD_SIZE, RANK`

python environment:
`PYTHON*, CONDA_*,ENV_NAME`

linux environment:
`PATH, LD_LIBRARY_PATH, DYLD_LIBRARY_PATH`

**Comment by yaroslavvb** [comment]
Here's an example, I ran a benchmark and the speed logged the result here under "avg_bus_bandwidth": https://app.wandb.ai/yaroslavvb/nccl_multiversion/runs/axh1hegq/overview

The performance is tied to a custom setting of env var "NCCL_NSOCKS_PERTHREAD", but that value is not captured anywhere

**Comment by yaroslavvb** [comment]
I think you could add another box under "Command" called "Environment", and put values of all whitelisted environment variables there as a space separated list, ie "VAR1=stuff VAR2=stuff ...". The whitelist would have all interesting non-secrets variables + variables used to configure CUDA or any of the major frameworks

**Comment by vanpelt** [comment]
Hey @yaroslavvb the simplest way to accomplish this today is by putting them in config.  I'll keep this open because I think it would make sense for us to encapsulate this logic in a helper function:

```python
import re
import os
for key in os.environ:
    if re.match(r"^NCCL|CUDA|PATH|^LD|USER|PWD", key)
        wandb.config[key] = os.getenv(key)
```

**Comment by cvphelps** [comment]
Closing for now as the snippet provided is good enough. Please upvote if other folks want this encapsulated directly in the client.
