### ISSUE TITLE
Entries in Overview missing for run that's in state "running"

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#369]
A few fields are missing when run is in state running or crashed, ie Python version, command, system hardware

https://app.wandb.ai/yaroslavvb/nccl_multiversion/runs/ijgl6afm/overview

That information, especially "Command" is useful for debugging hanging/crashing runs

**Comment by vanpelt** [comment]
We have a fix in master that will push the metadata when the process
starts, currently we only push on a clean exit.  We should cut a new
release next week.

**Comment by vanpelt** [comment]
0.8.2 uploads the command when the process starts

**Comment by yaroslavvb** [comment]
![squash-all-the-bugs](https://user-images.githubusercontent.com/23068/59931827-b2a86c00-93fa-11e9-8728-923099f9792f.jpg)
