### ISSUE TITLE
Getting logs through Python Export API 

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#373]
I want to download training log (output.log) for my runs through export API. Is it possible? I don't see anything about it under https://docs.wandb.com/docs/integrations/api.html

**Comment by vanpelt** [comment]
This will be coming in the next release!

**Comment by vanpelt** [comment]
0.8.2 uploads the entire log file at the end of your run, you can access it via the files api.

**Comment by FranzKnut** [comment]
Sorry for commenting on an old closed issue but I can't seem to access the output.log file via the API. What I tried:

```
run.load()
run.files()  # <- returns only wandb-metadata.json 
```

**Comment by maximilianmordig** [comment]
This is not working for me.
