### ISSUE TITLE
Log sys.executable for all runs

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#374]
I think sys.executable should be automatically saved for all runs. Maybe as "config.executable"?

PS, don't want to spam this list too much, let me know if it's more productive to batch feature requests rather than posting them as individual github issues

**Comment by vanpelt** [comment]
This is great, keep them coming!  We’ll likely add sys.executable to wandb-metadata.json which has things like os, Cuda, and args in it.  We don’t index this file.  Does your usecase involve filtering by this value in the tables?

**Comment by yaroslavvb** [comment]
The use-case is to be able to reproduce the run later. The environment has multiple conda envs, and having python interpreter tells me which conda env was used to run it.

Filtering by this value could be useful to find regressions -- ie, when I upgrade PyTorch, I install it into new conda env and redo the runs. An alternative is to automatically log framework versions in wandb. (using `torch.__version__` or [pip freeze](https://github.com/studioml/studio/blob/62bd177e5956cf8acbf3d965acf5efa1fddc7515/studio/experiment.py#L138-L155))

**Comment by vanpelt** [comment]
I just released this in 0.8.2, it's stored in `wandb-metadata.json` I'll expose it in the overview UI shortly.
