### ISSUE TITLE
OSError: [Errno 49] Can't assign requested address

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#379]
I just tried upgrading 0.7.3 to 0.8.1 and my runs are failing with error below. Downgrading back to 0.7.3 fixes the problem
```
Traceback (most recent call last):
  File "launch_interact.py", line 49, in <module>
    wandb.init(project='moonscrub', name=args.run_name)
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/__init__.py", line 778, in init
    _init_headless(run)
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/__init__.py", line 184, in _init_headless
    server = wandb_socket.Server()
  File "/Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/wandb_socket.py", line 29, in __init__
    self.socket.bind(('localhost', 0))
OSError: [Errno 49] Can't assign requested address

> /Users/yaroslavvb/anaconda3/envs/main/lib/python3.6/site-packages/wandb/wandb_socket.py(29)__init__()
-> self.socket.bind(('localhost', 0))
(Pdb) 
```

This is MacOS 10.13.6, Python 3.6.8 :: Anaconda, Inc.

**Comment by vanpelt** [comment]
That's no good.  We switched to localhost instead of the 0.0.0.0 to prevent firewall warnings.  It's working fine for me on OSX, I'll look into the root cause, but I can get a quick fix out that falls back to 0.0.0.0.

**Comment by vanpelt** [comment]
Actually, can you run `cat /etc/hosts` and tell me if there's an entry for localhost there?  Mine looks like:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by yaroslavvb** [comment]
Did not have that entry (I automatically my /etc/hosts to give my jobs human-readable DNS names), I guess I need to keep localhost in there

**Comment by vanpelt** [comment]
Yeah, that will fix it.  I'll make sure our code falls back to 127.0.0.1 in this case though.

**Comment by vanpelt** [comment]
0.8.2 falls back to 127.0.0.1
