### ISSUE TITLE
TypeError: list indices must be integers or slices, not float .How to get rid of it 

### ISSUE THREAD

**Issue by 05MrTom** [wandb/client#3792]

**Comment by 05MrTom** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/87299828/173338786-407f5a4b-421f-4b29-89fb-d8903d956091.png)

**Comment by ramit-wandb** [comment]
Hi @05MrTom,

This error does not seem to be stemming from `wandb`. Could you check by disabling `wandb`?

Thanks,
Ramit

**Comment by RamitGoolry** [comment]
​Hi @05MrTom, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​
