### ISSUE TITLE
Feature request: Tooltips for column headers in run overview 

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#385]
There's no way to make last column wider, so header gets cut-off (ie [here](https://app.wandb.ai/yaroslavvb/nccl_bench?workspace=user-yaroslavvb)) and impossible to read. A quick fix would be to add tooltip on hover -- show full name of the header

![last-col](https://user-images.githubusercontent.com/23068/59860438-a3aab680-9333-11e9-8287-36c78e736cb9.gif)

**Comment by vanpelt** [comment]
This totally makes sense.  We're working on a table rewrite now, we should have something better soon!

**Comment by cvphelps** [comment]
The tooltips are back and working!
![fix - hover column header to see tooltip](https://user-images.githubusercontent.com/6355078/61748157-6d0df480-ad54-11e9-828e-ecbfccca33cc.gif)
