### ISSUE TITLE
[Feature]: Enable replacing Run by SweepRun

### ISSUE THREAD

**Issue by tchaton** [wandb/client#3852]
### Description

I am trying to create a Wandb Sweep where I control the Sample Generation. 

The Sweeps package is quite rigid and it seems to be controlled only from the SweepController.

I would like to be able to replace Run by SweepRun where I add my own sampled parameters. 
Using the SweepRun, I can log my models, etc... and find the beautiful Sweep UI from Wandb.

### Suggested Solution

Make SweepRun and Run inter-changeable.

**Comment by lesliewandb** [comment]
Hi @tchaton, since you haven't responded I'm going to close out this ticket. However, if you still want to create this feature request please let me know!
