### ISSUE TITLE
[App]: Builtin presets problem.

### ISSUE THREAD

**Issue by DaBihy** [wandb/client#3868]
### Current Behavior

All charts using built-in methods `wandb.plot` are not working anymore in all my projects. It was working just fine until 2 days ago all the charts started showing me the error in the screenshot.

I tried to create a custom one from the query but it didn't work

### Screenshots

![image](https://user-images.githubusercontent.com/32498917/176422447-8abbdc0b-5193-4817-931f-fa08bbb7a7b6.png)

### Environment

OS:

Browsers:

Version:

**Comment by DaBihy** [comment]
> Hello @DaBihy,
> 
> Can you provide us a link to a workspace where this error occurs or provide a minimal reproducible script?
> 
> Thank you!

@ash0ts 
Here is the link for an example: https://wandb.ai/bihy/ConvEntionROC2?workspace=user-bihy

Thank you.

**Comment by DaBihy** [comment]
@ash0ts  any solution for the problem?

**Comment by ash0ts** [comment]
Hello @DaBihy,

I apologize for the delay on this. It seems during one of our upgrades we mistakingly removed some of our Vega Specs. We intend having these back in soon. I apologize for the delay and inconvenience!

**Comment by ash0ts** [comment]
@DaBihy 
We fixed the issue 🎉! Thank you for the patience. I confirmed with your provided workspace.
