### ISSUE TITLE
Filtering bug in runs overview 

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#387]
To reproduce -- go to https://app.wandb.ai/yaroslavvb/nccl_bench?workspace=user-yaroslavvb and try to add Filter by name. The result is empty no matter what you put for filter value

![filter-bug](https://user-images.githubusercontent.com/23068/59882380-ecc82e00-9366-11e9-922c-48aab00c0f97.gif)

**Comment by vanpelt** [comment]
Yep, definitely a bug in our backend filtering logic.  I'm tracking this internally for a fix.

**Comment by yaroslavvb** [comment]
Seems to be fixed
