### ISSUE TITLE
[CLI]: Have to call API twice to get wanted information 

### ISSUE THREAD

**Issue by miguelvalente** [wandb/client#3872]
### Describe the bug

When I make a single call nothing gets returned. 

![image](https://user-images.githubusercontent.com/39302216/176639697-4bb2127f-e312-4793-a0e2-6a59cf24e03a.png)

```python 
        self.api = wandb.Api({'entity': self.entity,
                              'project': self.project})

        # redundancy needed due to a W&B bug
        logging.info('Establishing W&B API connection established')
        self.runs = self.api.runs()   # this variable will contain no information about the runs
        self.runs = self.api.runs()   # this one will have the expected information
        logging.info('W&B API connection established')

```

### Environment

WandB version:  0.12.18

OS: Arch Linux

Python version: 3.10.4

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Hi @miguelvalente,

Our API lazily loads runs as they are accessed, which is why you were not seeing anything on the first call through the debugger. Could you try iterating through the runs once just to confirm if you are able to print the names / run id's for all of the runs? If you can, the API is working fine.

**Comment by miguelvalente** [comment]
@ramit-wandb 
PS:
Forgot to confirm what you said. Yes indeed it works as expected.

![image](https://user-images.githubusercontent.com/39302216/176895736-2c866844-4bcf-4408-bb49-a10a4ae4d2dd.png)

**Comment by ramit-wandb** [comment]
Hey @miguelvalente,

`len(self.runs)` should give the expected number of runs.

Thanks,
Ramit

**Comment by miguelvalente** [comment]
@ramit-wandb Thanks!
