### ISSUE TITLE
[Feature]: Custom LineSeries

### ISSUE THREAD

**Issue by ludwigwinkler** [wandb/client#3873]
### Description

Hi, 

I have multiple runs which share the config value 'length' (basically a hyperparameter) with different values (in my case 16, 32, 128, 256).

I would now like to plot the values of 'NN' and 'iFFT' on the y-axis with 'length' providing the x-axis.

Unfortunately, wandb only let's me pick a single value to plot as shown in the field 'lineVal', but I want two or more values to be plotted.

I am aware that one could log line_series, but I would like to create such a multi-line plot a posteriori.

![image](https://user-images.githubusercontent.com/29676773/176673552-61dba154-87a5-49f2-8653-9a2bf067345e.png)

How could I plot different logged values in a single plot with a shared x-axis which is provided from the config?

### Suggested Solution

I'd like to pick an arbitrary number of line series after running experiments and plot them jointly.

**Comment by ramit-wandb** [comment]
Hi @ludwigwinkler,

I'm not sure how exactly you intend your data to be represented. Could you plot a small example in matplotlib so that me and our engineering team could get a better sense for what you are looking for?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @ludwigwinkler, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
