### ISSUE TITLE
No way to delete project with no runs

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#388]
Trying to delete a temporary org/project

There are no runs in the project so the button "delete project" never shows up
https://app.wandb.ai/testtest/test

Also I don't see a way to delete org
https://app.wandb.ai/testtest

**Comment by vanpelt** [comment]
The empty project is a know issue, we working on a fix.  Until then you can add a single run to the project and then delete it.  We don't currently expose org deletion, you can remove yourself from the org by going to https://app.wandb.ai/teams/testtest

**Comment by yaroslavvb** [comment]
This seems to be fixed, I now see a delete option

**Comment by Kashu7100** [comment]
I do not see a delete button for a sample project (or example project).
