### ISSUE TITLE
Logging figure: ValueError: Un-supported shape for image conversion

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#393]
* Weights and Biases version:
* Python version:
* Operating System:

(please provide command to obtain this info easily, see https://github.com/wandb/client/issues/392)

```
fig = plt.figure()
plt.hlines(y=0, xmin=10.5, xmax=13.5, color="red")
wandb.log({"figure": fig})
```
yields
```
ValueError: Un-supported shape for image conversion [3, 288, 432]
```

**Comment by vanpelt** [comment]
This looks like an issue with the plotly library.  Can you try `wandb.log({"figure": wandb.Image(fig)})` and see if that works?

**Comment by dreamflasher** [comment]
That yields the same error.

**Comment by vanpelt** [comment]
Must be something about your system, I was able to get it to work fine in collaboratory:

https://colab.research.google.com/drive/1EzPxF4_y_351-M6w91_RJvvMsLrUEWOW

What OS and python version are you using?  Can you also type `pip freeze > requirements.txt` and attach it here?

**Comment by dreamflasher** [comment]
I moved to the built-in tensorboardX patch, and there the error does not happen.

**Comment by chrysm** [comment]
i'm getting this error because [your code](https://github.com/wandb/client/blob/2e79cf9c01cb98665c960679d9971407aa72fce3/wandb/sdk/data_types/image.py) doesn't support dimensions at the beginning of the array

**Comment by niniack** [comment]
This is still an issue for me

```
  File "/.venv/lib/python3.10/site-packages/avalanche/logging/wandb_logger.py", line 209, in log_single_metric
    self.wandb.log({name: self.wandb.Image(array(value))}, step=self.step)
  File "/.venv/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 161, in __init__
    self._initialize_from_data(data_or_path, mode)
  File "/.venv/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 302, in _initialize_from_data
    self.to_uint8(data), mode=mode or self.guess_mode(data)
  File "/.venv/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 454, in guess_mode
    raise ValueError(
ValueError: Un-supported shape for image conversion [3, 228, 454]
```

I'm happy to contribute if someone could point me vaguely in the right direction!

**Comment by alexaatm** [comment]
had the same issue with my numpy image, which i obtained by conversion from a tensor image.
Tensor order of dimensions was `c, h, w`, but wandb expects` h, w, c `.
It looks, like your dimensions are also reversed, so they need to be **transposed**:
(assuming image is in numpy format)
`image = image.transpose(1, 2, 0)`
