### ISSUE TITLE
System Data: Automatically capture AWS instance metadata with run

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#395]
Wandb could add support for cloud-specific machine information. On AWS, information is available through [instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-instance-metadata.html). There are no secrets in this metadata so the whole contents could be saved.

I'm accessing/logging useful bits manually using something like this
```
pip install ec2-metadata
...
    
def extract_ec2_metadata():
    from ec2_metadata import ec2_metadata
    return {
        'region': ec2_metadata.region,
        'account_id': ec2_metadata.account_id,
        'ami_id': ec2_metadata.ami_id,
        'availability_zone': ec2_metadata.availability_zone,
        'instance_type': ec2_metadata.instance_type,
        'public_ipv4': ec2_metadata.public_ipv4,
        'private_ipv4': ec2_metadata.private_ipv4
        }

wandb.config.update(extract_ec2_metadata())
```

**Comment by cvphelps** [comment]
Closing for now. Please upvote if other folks want this feature supported directly in the client.
