### ISSUE TITLE
Overlapping text in log window

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#398]
When you resize the console log window it overlaps text
https://app.wandb.ai/yaroslavvb/nccl_bench/runs/baf41u1f/logs

![wraparound](https://user-images.githubusercontent.com/23068/60276024-b2ebb000-98af-11e9-9b26-ece5e8892ec1.gif)

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
Could you check if the issue still persists?
I think the logs now do not have overlapping text anymore. Due to the thread going stale, we could do with closing this issue if the behaviour is no longer noticed.
