### ISSUE TITLE
Stale run names on overview page

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#409]
If you go to https://app.wandb.ai/cybertronai you'll see run names like `8vl4zj29`. 

<img width="896" alt="Screenshot 2019-07-01 22 38 10" src="https://user-images.githubusercontent.com/23068/60485272-3f4ff700-9c51-11e9-88a0-f2ea07fcd983.png">

Click on the run, then go back, it becomes `train_squad`
<img width="881" alt="Screenshot 2019-07-01 22 38 17" src="https://user-images.githubusercontent.com/23068/60485267-3bbc7000-9c51-11e9-85e5-e675b740665b.png">

**Comment by vanpelt** [comment]
Yeah, this is an issue with our apollo cache, tracking it.

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
I think this issue does not persist any more. I went into the project and found nothing of the sorts of `8vl4zj29`. 
If you think the solution to your issue has been achieved, could you please report?
CC: @cvphelps @vanpelt
