### ISSUE TITLE
can't sort runs by Runtime

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#414]
Warum nicht?
https://app.wandb.ai/cybertronai/moonscrub?workspace=user-yaroslavvb
![Screenshot 2019-07-03 10 21 13](https://user-images.githubusercontent.com/23068/60611925-5e977300-9d7c-11e9-9d8b-d8eccb890f15.png)

**Comment by vanpelt** [comment]
Yeah, we're working on exposing this one!

**Comment by yaroslavvb** [comment]
I can sort by Runtime now
