### ISSUE TITLE
Caption of wandb.Image does not display newlines

### ISSUE THREAD

**Issue by borisdayma** [wandb/client#416]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.3
* Python version: 3.7.3
* Operating System: Linux

### Description

When using newline character "\n" in the caption of `wandb.Image`, the newline is not displayed in the interface.

### What I Did

I used a command such as `wandb.Image(sample_image, caption='line1\nline_2')` and no newline was displayed.

On below example, I expected to have the ground truth and prediction on 2 separate lines.

![image](https://user-images.githubusercontent.com/715491/60762784-c2e05e00-a02c-11e9-8c64-6fdc9758a505.png)

You can see it by changing the zoom to high value at this link: https://app.wandb.ai/borisd13/simpsons-fastai/runs/g34gpga7

**Comment by austinmw** [comment]
Does a `<br>` happen to work?

**Comment by borisdayma** [comment]
@austinmw Good idea but it didn't work: https://app.wandb.ai/borisd13/simpsons-fastai/runs/nkvghhd2?workspace=user-borisd13

![image](https://user-images.githubusercontent.com/715491/64399433-0f94e500-d02e-11e9-9843-ee108dcb71d7.png)

**Comment by shawnlewis** [comment]
Fix incoming!

**Comment by shawnlewis** [comment]
This is fixed. Use '\n' to make newlines in captions.
