### ISSUE TITLE
Number of displayed runs in dashboard capped to 10?

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#438]
I'm seeing only last 10 runs now, wasn't there a way to do 50 before?
10 is kind of a lot of scrolling

https://app.wandb.ai/yaroslavvb/nccl_bench?workspace=user-yaroslavvb

<img width="1168" alt="Screenshot 2019-07-17 17 22 17" src="https://user-images.githubusercontent.com/23068/61420457-719b5e80-a8b7-11e9-964d-5d8c50fd4638.png">

**Comment by vanpelt** [comment]
You can click the 1-10 link at the bottom of the table to change the number of runs to show.  We’ll likely change this interface to an infinite scroll in a future revision.
