### ISSUE TITLE
Graph smoothing

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#440]
Here's an example of graph where smoothing would be useful:
https://app.wandb.ai/yaroslavvb/imagenet18/runs/brxz6ce5?workspace=user-yaroslavvb

<img width="409" alt="Screenshot 2019-07-18 14 44 38" src="https://user-images.githubusercontent.com/23068/61494275-9b618d80-a96a-11e9-904d-15458c29422b.png">

What's my images per second? 

Here's what this looks like in my [TensorBoard](http://54.236.42.108:6006/#scalars&runSelectionState=eyJlYnMtaW1hZ2VuZXQtMS4wMSI6dHJ1ZSwiZWJzLWltYWdlbmV0LTEiOnRydWV9) with smoothing. I can read my average images per second from the tooltip.

<img width="882" alt="Screenshot 2019-07-18 14 53 53" src="https://user-images.githubusercontent.com/23068/61494754-e29c4e00-a96b-11e9-9e51-afc030f11fbb.png">

Additional nice feature of Tensorboard, I can type "images" in the top textbox, and it gives me my images_per_second graph right away, no need to click around

**Comment by vanpelt** [comment]
Hey @yaroslavvb you can set global smoothing with the iron icon next to "Auto Visualizations".  Also if you type "time/" i the search box it will filter down to just that run.  If you pin the chart you can click the edit icon and change smoothing just for that chart.  Let me know if you aren't getting the values you want from the hover event, we could definitely improve the tool tips.

![Screen Shot 2019-07-18 at 3 08 59 PM](https://user-images.githubusercontent.com/17/61495498-082a5700-a96e-11e9-900f-82b24faecd8f.png)

**Comment by yaroslavvb** [comment]
Aha, now I see them, thanks for the tip!
