### ISSUE TITLE
adding system metrics to reports

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#443]
It would be useful to add system metrics to reports.

IE, here I wanted to add GPU utilization for comparison
https://app.wandb.ai/yaroslavvb/imagenet18/reports?view=yaroslavvb%2F300GB%20vs%20500GB%20io2%20disk

**Comment by ariG23498** [comment]
Hey @yaroslavvb I think the present version of wandb does support system metric logging.
![image](https://user-images.githubusercontent.com/36856589/100516221-6d1fcf00-31a8-11eb-89c4-9cfb15bd14b8.png)

Feel free to close this if the feature request meets.
CC: @cvphelps
