### ISSUE TITLE
Suppress info messages

### ISSUE THREAD

**Issue by gismo07** [wandb/client#457]
* Weights and Biases version: 0.8.5
* Python version: 3.7.3
* Operating System: Linux

### Description

WANDB prints a lot infos to the jupyter cell like:

```
INFO - wandb.run_manager - file/dir modified: /home/ubuntu/Projects/XX/XX/wandb/run-20190729_122935-r8x77nbl/wandb-summary.json
INFO - wandb.run_manager - file/dir modified: /home/ubuntu/Projects/XX/XX/wandb/run-20190729_122935-r8x77nbl/wandb-history.jsonl
INFO - wandb.run_manager - file/dir modified: /home/ubuntu/Projects/XX/XX/wandb/run-20190729_122935-r8x77nbl/model-best.h5
```

Is there a way to suppress these messages?

### What I Did
Read the entire doc, but did not found something related

**Comment by vanpelt** [comment]
This shouldn't be happening in the most recent release.  Is there anything special about your jupyter environment or instructions on how I could recreate it?

**Comment by AakashMallik** [comment]
@vanpelt I am using W&B in my own pytorch pipeline and I am very particular with the output on my stdout. I really need to suppress all terminal outputs from W&B. Is there a kwarg or a global settings for the functions to suppress this?? Really need it.

**Comment by vanpelt** [comment]
Hey @AakashMallik are you running in Windows or Unix?  Also are you always running python from the command line or within a jupyter kernel?  If it's unix and the command line, you can disable stdout mirroing by adding this before your call to wandb.init:

```python
from wandb import io_wrap
def redirect_noop(self):
    pass
io_wrap.FileRedirector.redirect = redirect_noop
```

If it's one of the other scenarios, let me know and I'll share some code.

**Comment by AakashMallik** [comment]
> Hey @AakashMallik are you running in Windows or Unix? Also are you always running python from the command line or within a jupyter kernel? If it's unix and the command line, you can disable stdout mirroing by adding this before your call to wandb.init:
> 
> ```python
> from wandb import io_wrap
> def redirect_noop(self):
>     pass
> io_wrap.FileRedirector.redirect = redirect_noop
> ```
> 
> If it's one of the other scenarios, let me know and I'll share some code.

Silly me. Just found this thread https://github.com/wandb/client/issues/337
Now I am setting the env variable from the pipeline itself. All good now. Thanks for your reply.

**Comment by tshmak** [comment]
Hi, I have the same problem, and I'm running on ipython. I suppose it's the same as jupyter. I tried setting `os.environ['WANDB_SILENT'] = 'true'`, but that did not work either. @vanpelt, you have some code to share that may solve the problem?

**Comment by tshmak** [comment]
Actually, I found that the info can be suppressed following the instructions here: https://docs.wandb.com/library/integrations/jupyter#disable-info-messages-from-wandb-in-jupyter

**Comment by vanpelt** [comment]
We're working on a big new release that will address this issue for good.  It's due out at the end of the month!

**Comment by ariG23498** [comment]
Hey folks,
This issue has been resolved in the present `wandb` package.
Closing this thread.
Please feel free to comment on this thread if the issue persists any longer. :smile:
