### ISSUE TITLE
Filtering by tags

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#460]
I think wandb needs a better way to use Tags.

The common use case could be this -- you have many bad runs, and a few good ones you want to compare against, so you want an easy way to label them/retrieve tagged runs.

1. Add ability to filter by Tag in the filter menu. Currently it's missing.
<img width="628" alt="Screenshot 2019-07-30 08 21 44" src="https://user-images.githubusercontent.com/23068/62142378-1730d380-b2a3-11e9-8ee1-cdb0ebdacd6b.png">

2. Add selector with popular tags at the top of runs overview. Clicking on a tag would work as a shortcut to filtering by that tag.

**Comment by itssimon** [comment]
I think you can now filter by a specific tag, but it would be great to be able to filter by tagged (any tag) or the inverse, not tagged.

**Comment by ariG23498** [comment]
Hey @itssimon @yaroslavvb 
I think wandb has imbibed this feature in the UI.

![image](https://user-images.githubusercontent.com/36856589/100751397-46160700-340d-11eb-9bf7-c7624fb9a447.png)
Here I have created the tag `good` and can filter the runs along with tags.
I hope we can close this feature request :smile: 
CC: @cvphelps
