### ISSUE TITLE
ValueError: Tensorboard already patched

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#463]
wandb, version 0.8.5   
Python 3.7.3 
Linux

Code to reproduce error
```
wandb.init(sync_tensorboard=True)
wandb.init(sync_tensorboard=True)
```

Throws:
```
ValueError: Tensorboard already patched, remove tensorboard=True from wandb.init or only call wandb.tensorboard.patch once.
```

Of course I wouldn't call two times init right after each other, but I regularly run into the error because I call my training script from a loop in a notebook.
Suggestion for improvement: Instead of raising the error, just not try to patch it again and accept multiple init calls.

**Comment by vanpelt** [comment]
We're working on an overhaul to make wandb work better when called multiple times in the same process.  Until we release something, you *should be able to call `wandb.uninit()` before calling `wandb.init` if you're calling it multiple times.  This hasn't been tested, so let me know if you see anything funky.

**Comment by vanpelt** [comment]
Hey @dreamflasher I just fixed this in master.  You can install with `pip install --upgrade git+git://github.com/wandb/client.git@master#egg=wandb`  We'll be pushing 0.8.8 today or tomorrow.

**Comment by vanpelt** [comment]
Just pushed 0.8.8, `pip install wandb --upgrade` will fix this now.
