### ISSUE TITLE
wandb.config is None sometimes

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#468]
I'm launching 16 processes on 2 machines through mpirun and `wandb.config` is None for 14 of these processes which crashes `wandb.config ... = ...` lines

I got around this crash by adding checks like below
```
if wandb.confg is not None:
  wandb.config['key'] = ...
```
Surprisingly that worked, so I'm confused why `wandb.config` would be `None` but leave the rest of the logging infrastructure functional.

Here are all 16 runs -- https://app.wandb.ai/yaroslavvb/imagenet18/groups/enable_efa_spawn-i9d

Not sure if related, but this co-occurred with me changing the launching mode of additional data crunching processes to [spawn](https://github.com/cybertronai/imagenet18_/blob/6a423eb57a90a9c9c19d0043fb07f3120f0d7e6f/training/dataloader.py#L41)

**Comment by vanpelt** [comment]
Hey @yaroslavvb I'm about to push a new release that prints a better error message in this case.  `wandb.config` will be uninitialized until `wandb.init` is called.  With my fix, you'll get an exception when attempting to set or access attributes on an uninitialized config object.

**Comment by vanpelt** [comment]
I could imagine a different approach where we just print a warning saying nothing will be saved until `wandb.init` is called.  I'm not a fan of this as it could lead to really unexpected behavior.  Was `wandb.init` being called in the spawned processes?

**Comment by yaroslavvb** [comment]
Yes, wandb init was being called in a spawned process. Wandb.config caching instead of hard crash is is a little more convenient and a little more bug-prone, don't really have an opinion which one is better

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
Is this ticket still relevant?
Could you give this a go with the latest release of wandb?
:smile:
