### ISSUE TITLE
CLI: Turn off system metrics logging

### ISSUE THREAD

**Issue by umgupta** [wandb/client#473]
This is a general query. I want to know if there is a way to stop logging system metric like CPU etc. usage. I really don't want to log this information.

**Comment by vanpelt** [comment]
You can fork this repo and comment out this line: https://github.com/wandb/client/blob/63573a9f5e701071aa7c755d53a112543a2a7b2b/wandb/run_manager.py#L901

We’ll add an ENV flag to disable system metrics in a future release.

**Comment by umgupta** [comment]
@vanpelt  Thanks, Is there a contribution guideline (so that I can add a PR)? or reference where I can see how to use env variables?

**Comment by asanakoy** [comment]
Also find it unnecessary to log all bunch of stats. Especailly on the machines with multiple GPUs when you run a job merely on a single GPU. The web-client eatas a lot of RAM and starts to lag.

**Comment by huyvnphan** [comment]
Any updates on this ?

**Comment by raubitsj** [comment]
We just released an update that has a way to turn off system metrics (but it isn't fully supported yet -- the full fix will be out in the next week or so)

To use the experimental feature make sure you are on wandb==0.10.0
```
wandb.init(settings=wandb.Settings(_disable_stats=True))
```

In later versions we will rename this flag and give you more ways to configure this as a default

**Comment by yashasvi97** [comment]
Hi @raubitsj, 
Is there a way to log only specific system metrics? like gpu performance, and temperature. Other stats like disk I/O, process CPU are not so important for my use case, and since all of the data generates a big log, it is difficult to render on the portal. An option of logging specific stats via passing arguments might be useful.

**Comment by raubitsj** [comment]
@yashasvi97 , good idea.  We are about to launch more configurable settings and we can include finer settings like you suggest.

**Comment by ariG23498** [comment]
Hey folks,
We are closing this issue as the feature request is resolved. For the finer details in settings, we are internally tracking it. :smile:

**Comment by CosmicHazel** [comment]
`_disable_stats` doesn't work. `wandb.init(settings=wandb.Settings(_disable_stats=True))` It still sends stats to WANDB, which in turn leads to BSOD due to incompatibility with the old PYNVML dependency in the vendor folder.
