### ISSUE TITLE
Add GPU power to system metrics

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#474]
Power draw in Watts is accessible through nvidia-smi and nvml and it is a better measure of GPU utilization. IE, power draw is be low when GPU is bottlenecked by memory bandwidth or network but other utilization measures are high

GPU Power state could also be useful to make sure GPU is not being throttled

**Comment by the-lay** [comment]
(Py)NVML supports [power readings](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g7ef7dff0ff14238d08a19ad7fb23fc87), and it would require addition of just a line or two [around here](https://github.com/wandb/client/blob/714518a582d3e7b0dccd57ffd042a558999031b8/wandb/stats.py#L94).

I will make a pull request this weekend :)

**Comment by yaroslavvb** [comment]
I think this needs to get piped through the front-end as well, it's currently not showing under system metrics page

**Comment by raubitsj** [comment]
We have added this to the cli 0.8.20 and the frontend displays it in the system metrics.
