### ISSUE TITLE
Problem with nn.Module object in config

### ISSUE THREAD

**Issue by umgupta** [wandb/client#475]
`wandb --version && python --version && uname`

wandb, version 0.8.5
Python 3.7.3
Linux

### Description

I am trying to sync my run to the wandb dashboard. 
### What I Did
`wandb sync <folder path>`
```
yaml.constructor.ConstructorError: while constructing a Python object
module 'torch.nn.modules.container' is not imported
  in "output/wandb/dryrun-20190811_013519-vymem890/config.yaml", line 32, column 14

```

Potential Issue: In my config I have `nn.Module` objects which is having trouble syncing to the cloud.

**Comment by vanpelt** [comment]
This should be fixed in 0.8.8, can you see if it still happens for you after running `pip install wandb --upgrade`
