### ISSUE TITLE
wandb.config.update doesn't work

### ISSUE THREAD

**Issue by lukas** [wandb/client#49]
* Weights and Biases version: 0.4.22
* Python version: 2.7
* Operating System: OS X

### Description
wandb.config.update(FLAGS) leads to the following error - maybe this is expected behavior?

Traceback (most recent call last):
  File "mnist_cnn.py", line 29, in <module>
    wandb.config.update(FLAGS)
AttributeError: 'module' object has no attribute 'update'

**Comment by shawnlewis** [comment]
I'm going to close this, we can revisit as people start using the API
