### ISSUE TITLE
Logs not syncing after switching from tensorboardx to torch.utils.tensorboard

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#493]
Metrics for my run are not showing up:
https://app.wandb.ai/yaroslavvb/test-graphs_test/runs/lbuht9lu?workspace=user-yaroslavvb

```
Train Epoch: 100 [44928/60000 (75%)]	Loss: 7.943522, Accuracy: 0/44928 (0.00%), Elapsed Time: 225.7s
Train Epoch: 100 [51328/60000 (86%)]	Loss: 7.655457, Accuracy: 0/51328 (0.00%), Elapsed Time: 225.9s
Train Epoch: 100 [57728/60000 (96%)]	Loss: 6.832315, Accuracy: 0/57728 (0.00%), Elapsed Time: 226.1s

wandb: Waiting for W&B process to finish, PID 98062
wandb: Program ended successfully.
wandb: Syncing files in wandb/run-20190821_231347-lbuht9lu:
wandb:   upstream_diff_692e4cc15b4b6acd32f627215194be23445e9d69.patch
wandb: plus 7 W&B file(s) and 0 media file(s)
wandb:                                                                                
wandb: Synced result: https://app.wandb.ai/yaroslavvb/test-graphs_test/runs/lbuht9lu

Process finished with exit code 0
```

Debug log --
[debug.log](https://github.com/wandb/client/files/3527695/debug.log)

My current work-around is to use local tensorboard to visualize the run, it looks something like this:
<img width="983" alt="Screenshot 2019-08-21 16 22 30" src="https://user-images.githubusercontent.com/23068/63474971-f128ca00-c42f-11e9-8f9c-2088ff41ba80.png">

**Comment by shawnlewis** [comment]
We just reproduced. It's a p0. Looking into it.

**Comment by vanpelt** [comment]
Hey @yaroslavvb can you share the code you're using with us?  If not, are you just calling init with sync_tensorboard?

**Comment by yaroslavvb** [comment]
I was using sync_tensorboard, can share code in 60 min

**Comment by vanpelt** [comment]
My best guess as to what's happening is we're not patching tensorboard properly.  If this was the case you should see the following as the first "wandb: " line in your logs:

```txt
wandb: Found tensorboardX and tensorflow, pass tensorboardX=False to patch regular tensorboard.
```

If we find tensorboardX in sys.modules we patch it instead of regular tensorboard.  You can force tensorboard patching by running: `wandb.tensorboard.patch(tensorboardX=False)` (instead of sync_tensorboard=True) or not importing tensorboardX.

**Comment by yaroslavvb** [comment]
Actually I just switched to using SummaryWriter that comes with pytorch and
upgraded to tb 1.14.0

**Comment by vanpelt** [comment]
We should handle that case: https://github.com/wandb/client/blob/master/wandb/tensorboard/__init__.py#L60

Try the manual patch call and also add pytorch=True (although we should detect that case automatically).  If you share the code, I’m happy to debug it.

**Comment by yaroslavvb** [comment]
Thanks that fixed it. The issue was switching to PyTorch version of Tensorboard from TensorboardX.
The manual patch version worked without needing `pytorch=True`

**Comment by vanpelt** [comment]
I think this will happen to others.  If I detect latest tboard and pytorch I should patch it alongside tboardx.

**Comment by jsrozner** [comment]
I believe I am having a similar problem. 

`wandb.init(project="my_project", dir=./save/, sync_tensorboard=True)`
tensorboard summary is also written to the same dir. I am using `tensorboardx.summarywriter`

Tensorboard when run locally shows all the metrics.

But metrics do not appear on wandb for any runs.

torch 1.7.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensoboardX==2.1

**Comment by ariG23498** [comment]
I tried reproducing the problem with the following code snippet:
```python
import wandb
from tensorboardX import SummaryWriter
wandb.tensorboard.patch(root_logdir="exp")
wandb.init(entity="repro", project="tensorboard")
writer = SummaryWriter("exp")
scalars = {
    'scalar_1': 1.0,
    'scalar_2': 2.0,
    'scalar_3': 3.0
}
writer.add_scalars("test", scalars, global_step=1)
writer.close()
wandb.finish()
```
Somehow `wandb` is unable to patch the tensorboard to the `logdir` I suggest here.

On the other hand I tried modifying the code and used `torch.utils.tensorboard.SummaryWriter()`
```python
import wandb
from torch.utils.tensorboard import SummaryWriter
wandb.tensorboard.patch(root_logdir="exp")
wandb.init(entity="repro", project="tensorboard")
writer = SummaryWriter("exp")
scalars = {
    'scalar_1': 1.0,
    'scalar_2': 2.0,
    'scalar_3': 3.0
}
writer.add_scalars("test", scalars, global_step=1)
writer.close()
wandb.finish()
```
This worked fine for me.
My best guesses would be some complication with the `tensorboardX` integration.

**Comment by ira7bar** [comment]
I have experienced the same problem (using `from torch.utils.tensorboard import SummaryWriter`) and solved it by first initializing wandb and only then initializing the tensorboard writer.
There was no need for manual patching before wandb init.
