### ISSUE TITLE
Feature Request: Sweep configuration via python

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#501]
wandb, version 0.8.9
Python 3.7.4
Linux

### Description

Currently hyperparameter sweeps are configured via sweep.yaml (https://docs.wandb.com/docs/sweep.html). It would be great if there were also a python interface for configuration and starting sweeps (passing a function to optimize).

**Comment by ariG23498** [comment]
Hey @dreamflasher 
Could you explain on the feature request a little more?

How would you envision to use the sweep with the python interface that you are talking about? Pseudocode would do just fine here. Knowing the specifications can help others to look into the ticket a little better I suppose. :smile:

**Comment by vanpelt** [comment]
This is actually supported now: https://docs.wandb.com/sweeps/python-api

**Comment by dreamflasher** [comment]
Amazing! Exactly as I imagined @vanpelt! thank you.
