### ISSUE TITLE
Charts take a while to load

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#504]
This run: https://app.wandb.ai/yaroslavvb/curv_train_tiny/runs/rfx5pat5?workspace=user-yaroslavvb

It takes roughly 11 second to load new page of graphs with the spinners going
<img width="1068" alt="Screen Shot 2019-08-27 at 4 28 34 PM" src="https://user-images.githubusercontent.com/23068/63815001-c8994800-c8e7-11e9-8f28-a418bccc3b9a.png">

The event file is about 180M right now

Hosted TensorBoard version takes 1-2 seconds:
https://app.wandb.ai/yaroslavvb/curv_train_tiny/runs/rfx5pat5/tensorboard

**Comment by yaroslavvb** [comment]
I'm assuming the issue is too many individual events? (a few million in that run) The hosted tensorboard from wandb is working well for me atm, I'd rather wait for a general performance fix

**Comment by shawnlewis** [comment]
We have three stages of fixes (all are general). The first will go out
tomorrow and should cut the load time in half. The next is probably a week
or two out and reduces the load time to 2s. The final should make the load
feel instant, but it's maybe 4-6 weeks out.

Most of the metrics only have 50k events for that run.

The issue has to do with our storage layout.

**Comment by yaroslavvb** [comment]
It seems like this got worse -- this one logged just a couple of metrics, several times a minute, for a couple of hours. The chart doesn't load at all

https://app.wandb.ai/yaroslavvb/train_ciresan/runs/m7blvhmo?workspace=user-yaroslavvb

**Comment by yaroslavvb** [comment]
Just got reminded of this when trying to view this run 
https://app.wandb.ai/yaroslavvb/train_ciresan/runs/m7blvhmo?workspace=user-yaroslavvb

It's currently timing out with "Deadline exceeded"

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
Thanks for the ticket.
For more details about the limits of logging we have a detailed page on this: https://docs.wandb.com/library/limits

CC: @cvphelps

**Comment by vanpelt** [comment]
We've since made improvements to caching and print warnings when limits are exceeded.
