### ISSUE TITLE
Fastai WandbCallback with multilabel datasets

### ISSUE THREAD

**Issue by austinmw** [wandb/client#519]
* Weights and Biases version: 0.8.9
* Python version: 3.6.9
* Operating System: Linux-4.14.133-88.112.amzn1.x86_64-x86_64-with-Ubuntu-16.04-xenial

### Description

I'm trying to see prediction samples for fastai image classification, where the images are multilabel. I'd like  it to be ran on the validation data at the end of each epoch and to see captions of ground truth/predictions.

When I use a multilabel dataset, instead of ground truth/prediction captions for each image, I get a three copies of each image side by side, where each is labeled, "Input data", "Prediction", "Ground Truth" (but not the actual categories)

### What I Did

`callback_fns += [partial(WandbCallback, input_type='images', monitor='acc_thresholded')]`

**Comment by cvphelps** [comment]
@borisdayma could you take a look at this please?

**Comment by borisdayma** [comment]
@austinmw do you have a coffee sample I can look at?
The callback tries to guess the type of problem (classification, segmentation...) based on the type of input/output seen.
This case is probably not handled and it would be good to see in which category of problems the callback is classifying it.

**Comment by austinmw** [comment]
Hmm I'm not familiar with what a coffee sample is. The category of problem is a CNN classifier that is multilabel. So, each image can have between 0 and 4 labels, and each output value uses a sigmoid activation, so they don't sum to 1. My fastai databunch is created using `.label_from_df(label_delim=' ')`.

**Comment by borisdayma** [comment]
Sorry I had a typo.
What is the shape of output tensor?
Is it (batch_size, 4) with each value representing probability of a class?

A simple example may make it easier to debug if possible. Maybe you are even adapting one of fastai notebooks that I can look at?

**Comment by austinmw** [comment]
Yes that's the output shape. It's difficult for me to create a minimum reproducible example, because my code is currently completely intertwined with aws sagemaker. However, a good example of an almost identical problem (fastai, cnn, multilabel) fastai's course example using the planets dataset: https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-planet.ipynb

**Comment by borisdayma** [comment]
Ok the issue is that multi-classification problems are not automatically detected yet. Let me look a bit more into it.

**Comment by borisdayma** [comment]
I think this can now be handled correclty with commit https://github.com/borisdayma/client/commit/5f43f7dac4068bc0bfe4a91d13469f8a0b36649c

I just need to do some more testing to ensure it does not affect other types of problems.

Feel free to test it in the meantime.

Here is a [sample run](https://app.wandb.ai/borisd13/course-v3-nbs_dl1/runs/kabv3wiv?workspace=user-borisd13).
