### ISSUE TITLE
graphing not working?

### ISSUE THREAD

**Issue by lukas** [wandb/client#52]
* Weights and Biases version: 0.4.24
* Python version: 2.7.12
* Operating System: linux

### Description

I'm using  WandbKerasCallback() but I'm not getting a graph or I'm only getting a single point on the graph.  Weirdly, the point moves around inside a single epoch.

https://app.wandb.ai/l2k/simple-test/runs/q0ji253u

**Comment by shawnlewis** [comment]
I think this went away with recent changes.
