### ISSUE TITLE
Syncing don't update existing runs but create new ones

### ISSUE THREAD

**Issue by Ierezell** [wandb/client#531]
* Weights and Biases version: wandb, version 0.8.9
* Python version: Python 3.7.4
* Operating System: Linux 5.2.11 (Archlinux)

### Description
Trying to sync runs launched on an offline compute server. 

Downloading runs from the server to my local machine via ssh and then running `wandb sync run-xxxxxx` to push them online.  

It works and push everything on wandb.com but instead of updating existing runs with new datas, it creates a new runs everytime. 

If I sync it x times I will get x similar runs (just longer steps) on the website.

### What I Did
Downloading runs from the server : `rsync -r --copy-links user@server:folder local_folder`

Syncing the downloaded runs (go to the folder and run) :` find wandb/run* -maxdepth 0 -type d -exec wandb sync {} \; > result.out `  so it update for all runs

Everything of this works but duplicate each of the runs. 
This issue is to allow the sync command to update existing runs

Thanks in advance

**Comment by jwiszowata** [comment]
I have a very similar issue, I try to work on two projects. One of them is a team project, and the other one is my private one. Every time I try to run a private one, the app creates a new project for the team. I tried to create a project in the right place, I put setting that new project should be created under my private account but it didn't help.
I work on:
Linux Mint 19.2 Tina 64-bit
Python 3.6.9
wandb version 0.8.19

**Comment by noklam** [comment]
any update on this issue?

I guess the current `wandb sync` is more like `wandb upload` instead. Sometimes my wandb uploading process is broken, but the local file is intact, so I want to run `wandb sync` to recover full history, but it will create a new experiment instead.

**Comment by ariG23498** [comment]
Hey @noklam 
Does the `--id` help you to overcome this issue?
In the [documentation](https://docs.wandb.ai/ref/cli#wandb-sync) we have provided with all the options there are to be used with the `sync` CLI. The issue here particularly pertains to duplication. If we provide the `--id` of the run, the sync attaches to the run we mention.

On the other hand, if we want to resume a run here is the [documentation](https://docs.wandb.ai/library/resuming) for that.

**Comment by noklam** [comment]
sorry I cannot confirm on this, I have not used it in a while.
