### ISSUE TITLE
logging one plot per step

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#537]
Here's an example of logging neural network spectra through matplotlib/ `SummaryWriter.add_figure`

TensorBoard gives a nice interface to scroll between them
https://app.wandb.ai/yaroslavvb/curv_train_tiny/runs/gjekrtio/tensorboard

![scroll2](https://user-images.githubusercontent.com/23068/64672292-e73b2b00-d41f-11e9-8d53-2f8b0ee28df2.gif)

Wandb version shows a single image, and the sizes are too large
https://app.wandb.ai/yaroslavvb/curv_train_tiny/runs/gjekrtio?workspace=user-yaroslavvb

<img width="869" alt="Screenshot 2019-09-10 23 08 51" src="https://user-images.githubusercontent.com/23068/64672315-fae69180-d41f-11e9-8bdf-ae81b8c778b5.png">

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
