### ISSUE TITLE
Agent loads newest file when sweeping

### ISSUE THREAD

**Issue by KeAWang** [wandb/client#544]
`wandb --version && python --version && uname`

wandb, version 0.8.9
Python 3.7.4
Linux

### Description

When I'm sweeping a set of hyperparameters, my running agent will load the newest version of the python script. This means that if I make any edits to the python script right before the running agent finishes a run and continues to the next one, the changes won't be logged in the logs. Even worse, the run may silently do completely different behavior than what was logged.

You can test this out with the following

### What I Did
Sweep on some settings with more than one runs.
```
wandb sweep sweep.yml
wandb agent <sweep hash>
```
Now go in and edit the run script by adding `import pdb; pdb.set_trace()` for example. Upon finishing the first run, the agent will start the second run with this change. The agent will then block because of the `set_trace()`.

**Comment by vanpelt** [comment]
We will record the local changes in a diff.patch file associated with the run at the time the agent runs the command.  Are you suggesting we should enforce sweeps to all run the same code?  This could be tricky as any dependency could change on the machine running the agent as well.  Currently we just record as much state about the system every time a run is created.

**Comment by KeAWang** [comment]
Ah I see. I was hoping that for a sweep, it would save a local copy of the repo or something and run files in there. It might still be good to do this even if you can't ensure that the entire dependency tree across the system stays the same.

Otherwise this would prevent the user from doing any code edits while running the sweeps

**Comment by vanpelt** [comment]
Makes sense, we'll consider the "snapshot" option you described to allow editing the local files after the sweeps starts.

**Comment by ariG23498** [comment]
Hey @KeAWang 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
