### ISSUE TITLE
Wrong debug.log location in crash message

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#547]
In the following message, the location doesn't take into account custom logging dir

```W&B process failed to launch, see: wandb/debug.log```

Example of initializing wandb client
```
        wandb.init(project=project_name, group=logdir_name,
                   name=f'worker-{util.get_global_rank()}', dir=wandb_dir,
                   sync_tensorboard=True)
```

**Comment by yaroslavvb** [comment]
(ps, it feels like wandb logs should go into /tmp by default and not . which has scripts and is under version control)

**Comment by vanpelt** [comment]
We write a .gitignore file if you call wandb init in the directory.  We put it in the wandb dir because we wanted it close to the runs.  We need to refactor logging in general, we'll address this ticket in the refactor.

**Comment by yaroslavvb** [comment]
My script directory is automatically synced to dropbox, google drive and rsynced to all of my AWS instances. This is influenced by Google where modifications in . are automatically uploaded (citc filesystem)

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen. :smile:
