### ISSUE TITLE
log window shouldn't autoscroll to bottom

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#549]
Currently if your stdout is constantly updating, it's hard to look at logs in the beginning, window jumps to the bottom of log at each update
https://app.wandb.ai/yaroslavvb/Transformer-XL%20source%20code/runs/hyxhg8qm/logs

**Comment by yaroslavvb** [comment]
suggested behavior -- if you are already at the bottom, it will autoscroll, but if you scroll up, this behavior is suspended

**Comment by vanpelt** [comment]
Yep, this is a great suggestion.  Will file.

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
