### ISSUE TITLE
wandb client confused by spaces in in project name 

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#551]
Correct link:
https://app.wandb.ai/yaroslavvb/Transformer-XL%20source%20code/runs/1a70q8no/logs

What wandb client prints in console:
https://app.wandb.ai/yaroslavvb/Transformer-XL+source+code/runs/1a70q8no

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
