### ISSUE TITLE
wandb: ERROR To use wandb on Windows, you need to run the command "wandb run python <your_train_script>.py"

### ISSUE THREAD

**Issue by MbProg** [wandb/client#560]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.10
* Python version: 3.6.4
* Operating System: Windows 8

### Description
I want first at all run the sample file: https://github.com/wandb/tutorial/blob/master/tutorial.py, but it fails when running code line: wandb.init(project="sample-project")

### What I Did
I installed the packages for wandb. And then I run the code file mentioned above on my Windows 8 machine.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
I just ran the file tutorial.py with python: `python tutorial.py`
But I am getting the following error message:
`wandb: ERROR To use wandb on Windows, you need to run the command "wandb run python <your_train_script>.py"`

**Comment by raubitsj** [comment]
What happens when you run:
```wandb run python tutorial.py```

That is the only supported way to use wandb with windows.

**Comment by MbProg** [comment]
> 
> 
> What happens when you run:
> `wandb run python tutorial.py`
> 
> That is the only supported way to use wandb with windows.

I get the following error message:
```
wandb: Program failed with code 2. Press ctrl-c to abort syncing.
wandb: Process crashed early, not syncing files
Traceback (most recent call last):
  File "c:\...anaconda3\lib\site-packages\wandb\compat\weakref.py", line 140, in _exitfunc
    f()
  File "c:\...\anaconda3\lib\site-packages\wandb\compat\weakref.py", line 64, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "c:\...\anaconda3\lib\site-packages\wandb\compat\tempfile.py", line 57, in _cleanup
    _rmtree(name)
  File "c:\...\anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\...\anaconda3\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\...\anaconda3\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\...\\AppData\\Local\\Temp\\tmpyf3qve3iwandb\\wandb-metadata.json'
```

But why cannot run wandb in Windows?

**Comment by TKassis** [comment]
Does that mean we cannot use it along with Jupyter notebooks in Windows?

**Comment by vanpelt** [comment]
Hey @TKassis it should work fine in jupyter.  @MbProg we're going to push a new version of the cli this week that removes the requirement for `wandb run` on windows and fixes the error above.  If you would like to try it now you can install with `pip install --upgrade git+git://github.com/wandb/client.git@feature/windows_no_run#egg=wandb`

**Comment by TKassis** [comment]
Can't install this branch for some reason:

`(tf) D:\>pip install --upgrade git+git://github.com/wandb/client.git@feature/windows_no_run#egg=wandb
Collecting wandb from git+git://github.com/wandb/client.git@feature/windows_no_run#egg=wandb
  Cloning git://github.com/wandb/client.git (to revision feature/windows_no_run) to c:\users\timothy\appdata\local\temp\pip-install-sbpybyu1\wandb
  Running command git clone -q git://github.com/wandb/client.git 'C:\Users\Timothy\AppData\Local\Temp\pip-install-sbpybyu1\wandb'
  WARNING: Did not find branch or tag 'feature/windows_no_run', assuming revision or ref.
  Running command git checkout -q feature/windows_no_run
  error: pathspec 'feature/windows_no_run' did not match any file(s) known to git
ERROR: Command errored out with exit status 1: git checkout -q feature/windows_no_run Check the logs for full command output.`

**Comment by WaGGstoun** [comment]
I have an identical error.

**Comment by TKassis** [comment]
> I have an identical error.

They released version 0.8.13 already, but the sweep functionality still doesn't work with Windows.

**Comment by vanpelt** [comment]
Yeah, we’re working on the sweep functionality.  0.8.13 does remove the need for `wandb run` which is a big improvement.  I’ll update the thread once we have an update.

**Comment by WaGGstoun** [comment]
I just solved the issue this way: https://docs.wandb.com/library/advanced/environment-variables. Maybe it will help you. Although this is a bit strange.

**Comment by raubitsj** [comment]
@WaGGstoun , which issue did you solve? what environment did you set?

**Comment by WaGGstoun** [comment]
Hi @raubitsj, I simple added an environment variable to my code, and thus, synchronization starts automatically, and not through `wandb run python`. Since an error occurs when starting through `wandb run python`.

### Terminal output { when starting through `wandb run python`}
```
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\main\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\main\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Anaconda3\envs\Main\Scripts\wandb.exe\__main__.py", line 4, in <module>
  File "c:\users\user\anaconda3\envs\main\lib\site-packages\wandb\cli.py", line 691, in <module>
    @display_error
  File "c:\users\user\anaconda3\envs\main\lib\site-packages\click\decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "c:\users\user\anaconda3\envs\main\lib\site-packages\click\core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'
```

**Comment by raubitsj** [comment]
Sweeps are functional in windows with the latest versions of the wandb client.

Windows users no longer need to use wandb run to start the training script.

Closing this issue. Please reopen it if there is still an issue.
