### ISSUE TITLE
Can't save model, h5py returned error: Not JSON serializable

### ISSUE THREAD

**Issue by alberduris** [wandb/client#562]
* Weights and Biases version: 0.8.10
* Python version: 3.6.1
* Operating System: Windows 10

### Description

I was running a training script with wandb integration on Windows with the `python train.py` command instead of the required `wand run python train.py` (this is because while developing on Pycharm, the run option just executes that command).

I expect wandb to do nothing more than displaying the warning message: 

`wandb: ERROR To use wandb on Windows, you need to run the command "wandb run python <your_train_script>.py"`

But instead more errors start to appear, as the mentioned in #557 and this one:

`wandb: ERROR Can't save model, h5py returned error: Not JSON Serializable: <dtype: 'string'>
`

I expect that if you are on Windows but run the training script just with the `python train.py` command, wandb _only_ alert you about how to correctly do it in Windows, but not try to do anything else, as it is known in advance that it won't work. 

### What I Did

```
py -3 Train-NNLM.py

wandb: ERROR To use wandb on Windows, you need to run the command "wandb run python <your_train_script>.py"
wandb: ERROR wandb.init hasn't been called, can't configure run
wandb: ERROR Can't save model, h5py returned error: Not JSON Serializable: <dtype: 'string'>
```

**Comment by ariG23498** [comment]
Hey @alberduris 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
