### ISSUE TITLE
Plotly conversion fails for multiple subplots

### ISSUE THREAD

**Issue by kdmcdrm** [wandb/client#563]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.10
* Python version: 3.6.5
* Operating System: Linux

### Description
I export a number of figures at the end of training showing a variety of metrics by threshold, etc. I tried doing this with the standard logging syntax but I found that most plots that were complicated resulted in plotly UserWarnings indicating that it does not know how to handle them. Plotly version 3.6.1. I found this specifically with a precision and recall figure that contained two subplots, there were other errors but I didn't track them. Is there a way to handle this or would I need to convert my plotting to Plotly to avoid the conversion step?

I tried switching to exporting them as images but I found the space provided on the run page for media is too small to see each plot.

**Comment by faberf** [comment]
Im having the same problem. Wandb makes some mistakes when converting from matplotlib to plotly. For example the subplot titles are missing.

**Comment by vanpelt** [comment]
Currently there are 3 options if matplotlib to plotly conversion isn't working for you.

1. User our new custom charts functionality:
     https://docs.wandb.com/library/log#custom-charts
     https://docs.wandb.com/app/features/custom-charts/walkthrough
2. Convert your plots to Plotly charts explicitly and log them with `wandb.Plotly`.
3. Convert the matplotlib objects to images with `wandb.Image(figure_or_plot)`

Plotly has deprecated their official matplotlib to plotly conversion logic.  We may release a custom matplotlib conversion library in the future.  Our custom charting logic is using the same underlying engine as [Altair](https://altair-viz.github.io/) so we may have a deeper integration with altair in the future as well.
