### ISSUE TITLE
Smoothing displays double lines; does not change line opacity

### ISSUE THREAD

**Issue by prash-p** [wandb/client#568]
* Weights and Biases version: 0.8.9
* Python version: 3.5.3
* Operating System: Linux-4.9.0-9-amd64-x86_64-with-debian-9.9

### Description

On my run page, my smoothed plots show up as double lines because wandb doesn't change the opacity of the original lines. Only happens on run page, project page smoothing works as expected. Example:

![image](https://user-images.githubusercontent.com/5707552/65355264-69f18200-dba6-11e9-8d69-504b2e007aeb.png)

**Comment by prash-p** [comment]
This also happens on wandb 0.8.12 and python 3.6.3

**Comment by lukas** [comment]
Could you post a link to the page where this is happening?

**Comment by prash-p** [comment]
It's a private project. Is there a way I could add only you as a member to the run/project?

**Comment by adrnswanberg** [comment]
Thanks for reporting this. I was able to reproduce and have a PR out to fix it. Should hopefully be gone by tomorrow!
