### ISSUE TITLE
stdout suppressed, some charts not being displayed

### ISSUE THREAD

**Issue by ankeshanand** [wandb/client#569]
* Weights and Biases version: 0.8.12
* Python version: 3.6
* Operating System: Linux

I am seeing a strange issue, after the W&B process has started I can't see any stdout on my screen. Further most charts are not being displayed (even though their summary metrics are being logged). Here's a run with the issue: https://app.wandb.ai/abs-world-models/awm/runs/l1eetxul?workspace=user-ankeshanand

Any idea what could be going wrong here?

**Comment by vanpelt** [comment]
Strange, was everything working fine for you with a previous release.  If you can try pip install wandb==0.8.9 and see if the screen issue still happens that would help.

For the run you linked to, it looks like all 7 charts are present corresponding to the 7 summary metrics.  Am I missing something?

**Comment by ankeshanand** [comment]
Oops sorry that was false alarm! Seems the issue was from my end, and a browser extension was to blame. I still can't see stdout but I am able to see the logs on the W&B run dashboard which suffices.

**Comment by vanpelt** [comment]
I'm still concerned about stdout not showing up in your terminal.  Was it working before?
