### ISSUE TITLE
wandb.log called without a step keyword argument

### ISSUE THREAD

**Issue by Danmou** [wandb/client#571]
* Weights and Biases version: 0.8.12
* Python version: 3.6.9
* Operating System: Debian 10

### Description
Creating a `tf.summary.FileWriter` with a graph makes wandb give a warning about a missing step argument. Graphs are typically not associated with a specific step, so wandb should IMO not give a warning in this case.

### What I Did
Python script:
```python
import tensorflow as tf
import wandb

wandb.init(project="test", sync_tensorboard=True)

[...]

writer = tf.summary.FileWriter('logs/', tf.get_default_graph())
```

Output:
```
wandb: WARNING wandb.log called without a step keyword argument.  Pass the same step that tensorboard is using to avoid data loss see:
wandb: WARNING https://docs.wandb.com/docs/integrations/tensorboard.html#custom-metrics
```

**Comment by vanpelt** [comment]
Good catch, we'll fix this in the next release.

**Comment by ariG23498** [comment]
Hey @Danmou 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
