### ISSUE TITLE
Save Visualisations/Plots 

### ISSUE THREAD

**Issue by mlmu** [wandb/client#574]
Hi, thanks a lot for the great work!

I have one question regarding the plots, namely:
Is it possible to save the visualisations from dashboard in a good quality?
Now it seems to very compressed...

Many thanks in advance!

**Comment by vanpelt** [comment]
With the latest version of the library images are saved as png’s which shouldn’t have any quality loss.  Can you link me to a specific example of poor quality images?

**Comment by mlmu** [comment]
Hi! Thanks a lot for the fast response!
I use the latest version of wandb as well, however PNGs seem to be blurred if downloaded.
Please, see the attached file.

![W B Chart 9_25_2019, 9_57_52 AM](https://user-images.githubusercontent.com/45629113/65581238-6af62b00-df7b-11e9-92c9-7c5d75425a8c.png)

**Comment by rahulvigneswaran** [comment]
@mlmu One easy workaround for the time being is to download the `.csv` for that specific graph and port it to [plotly](https://chart-studio.plot.ly/create/).

**Comment by ariG23498** [comment]
Hey @mlmu 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by Amritpal-001** [comment]
Wandb generates awesome plots and is very helpful. Few issues I have experienced:
1.  plot quality reduces on downloading it as png. 
2. pdf export of figures not working. It prints the figures on bigger white background, instead of just the figure (I Tried Firefox and Chrome browser).   
3. Using Plotly from csv file works fine, but that defeats the effort of creating beautiful plots on the Wandb dashboard in the first place. 


I hope this is improved. Great product. Good work team Weights & Biases!

**Comment by nishanth-shetty** [comment]
> Wandb generates awesome plots and is very helpful. Few issues I have experienced:
> 
>     1. plot quality reduces on downloading it as png.
> 
>     2. pdf export of figures not working. It prints the figures on bigger white background, instead of just the figure (I Tried Firefox and Chrome browser).
> 
>     3. Using Plotly from csv file works fine, but that defeats the effort of creating beautiful plots on the Wandb dashboard in the first place.
> 
> 
> I hope this is improved. Great product. Good work team Weights & Biases!

I have the exact same issues even now.

**Comment by omgwenxx** [comment]
+1

**Comment by daniel-strauss** [comment]
Please, let there be an option to choose the size, that does not change the font size. 
Or maybe just the option to type in a number value to choose the font size. 
As is, the only usable option is to download CSV.
