### ISSUE TITLE
wandb pull not working

### ISSUE THREAD

**Issue by umgupta** [wandb/client#575]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.9
* Python version: 3.7
* Operating System: Linux

### Description
I was trying to pull an experiment by ID and project. 

### What I Did
I ran `wandb pull <ID> -p <project_name> `
and this happend. 
```
Error: 'NoneType' object is not subscriptable
```

I went ahead and further looked into the code... it seems that the error is in `apis/internal.py, line 905`. It seems the gql result is `{model: None}` which cause the problem while querying `bucket` key etc.

**Comment by raubitsj** [comment]
Please set your "entity" with the -e argument.  if you do that you will find that the command will work.

You are correct that the error message is not helpful and should be improved.

**Comment by umgupta** [comment]
I am sorry but what is entity? I am not sure what it means so I left empty.

**Comment by umgupta** [comment]
Oh! nevermind. I found it here: https://docs.wandb.com/wandb/init

If anyone stumbles on this issues... here is the relevant information. 

entity — the team posting this run (default: your username or your default team)
