### ISSUE TITLE
wandb: ERROR Unable to log event No module named 'PIL'

### ISSUE THREAD

**Issue by altay** [wandb/client#577]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.12
* Python version: 3.7.4
* Operating System: Linux

### Description

Trying to instrument https://github.com/wandb/transformer

### What I Did

Ran the script

```
Paste the command(s) you ran and the output.

python train.py --batch_size 64 --vocab_size 100

wandb: ERROR Unable to log event No module named 'PIL'

If there was a crash, please include the traceback here.
```

**Comment by raubitsj** [comment]
Try:
pip install pillow

**Comment by ariG23498** [comment]
Hey @altay 
I think you have met your solution
Closing this as the ticket is stale :smile:
