### ISSUE TITLE
RuntimeError: threads can only be started once

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#584]
wandb, version 0.8.12
Python 3.7.4
Linux

### Description
Code to reproduce:

```
from fastai.vision import *
import wandb
from wandb.fastai import WandbCallback

wandb.init(project="projectname")

learn = cnn_learner(data, model, metrics=[accuracy, mean_squared_error], callback_fns=[WandbCallback])
learn.model = nn.DataParallel(learn.model)
learn.fit_one_cycle(6)
learn.unfreeze()
learn.fit_one_cycle(40, slice(1e-5,3e-4))
learn.validate()
```

yields: `RuntimeError: threads can only be started once`

**Comment by cvphelps** [comment]
Thanks for reporting this! We'll look at it in our weekly meeting.

**Comment by vanpelt** [comment]
Hey @dreamflasher we may have fixed this in the latest release.  We just tried to reproduce the code you sent and couldn't.  Can you try again?

**Comment by dreamflasher** [comment]
Yes, fixed, thank you!
