### ISSUE TITLE
Cannot change wand.init save_dir on Windows 10

### ISSUE THREAD

**Issue by PBarde** [wandb/client#587]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.12
* Python version: 3.7.3
* Operating System: Win 10

### Description

I cannot overwrite the default wandb save location './wandb/' nor the name of the run, here is a small script showing this: 

### What I Did
```
    os.environ['WANDB_DIR'] = str(dir_manager.seed_dir.absolute())
    os.environ['WANDB_DESCRIPTION'] = str(dir_manager.storage_dir.name)
    print(os.environ['WANDB_DIR'])
    # F:\PhD\my-irl-framework\direct_rl\storage\Pa30_e9c57d2_envhash_sacmh_cartpole_test_refacto\experiment1\seed131214
    print(os.environ['WANDB_DESCRIPTION'])
    # Pa30_e9c57d2_envhash_sacmh_cartpole_test_refacto

    wandb.init(dir=str(dir_manager.seed_dir.absolute()), name='test')

    print(os.environ['WANDB_DIR'])
    # F:\PhD\my-irl-framework\direct_rl\storage\Pa30_e9c57d2_envhash_sacmh_cartpole_test_refacto\experiment1\seed131214
    print(os.environ['WANDB_DESCRIPTION'])
    # test
    print(wandb.run.dir)
    # F:\PhD\my-irl-framework\direct_rl\wandb\run-20191001_142446-tdu4w2ge
```

I tried the following both in the Git-Bash and in the Command prompt
```
wandb run python main.py
```
main.py is located at F:\PhD\my-irl-framework\direct_rl\

**Comment by cvphelps** [comment]
Thanks for letting me know about this! I'll go over this issue in our weekly meeting.

**Comment by vanpelt** [comment]
We're pushing a fix this week, you can install with `pip install --upgrade git+git://github.com/wandb/client.git@windows-no-run#egg=wandb`

**Comment by lukas** [comment]
This should be fixed now - could you verify?
