### ISSUE TITLE
new wandb requires interactive prompt 

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#592]
After upgrading wandb I found a bunch of my distributed workers hanging at the following prompt. Is there some python arg to get the old behavior? (ignore missing credentials with a warning)

```
Logging to run05
wandb: W&B is a tool that helps track and visualize machine learning experiments
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
```

**Comment by vanpelt** [comment]
Ugg, didn’t think about that scenario.  If you set WANDB_MODE=dryrun on those machines we shouldn’t prompt.  Do you think the right behavior in this case is to wait for N seconds and default to dryrun if no input was received?

**Comment by yaroslavvb** [comment]
I see, `WANDB_MODE=dryrun` seems like a good work-around. Waiting "N seconds" seems like a bad idea, people would not realize why wandb makes their distributed runs take "N seconds" longer to start

**Comment by WilliamAshbee** [comment]
this seems to make output get directed to stderr?
