### ISSUE TITLE
Files window limited to 20 scrolls?

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#595]
Is there a limit to files window?

I'm missing some files in this list
https://app.wandb.ai/yaroslavvb/Transformer-XL%20source%20code/runs/g6u4zz20/files

**Comment by yaroslavvb** [comment]
Uhm ... the files are still missing :P

**Comment by adrnswanberg** [comment]
Apologies! This automerged when I merged a fixing PR in our private repo. We'll get a deploy out shortly, and then your missing files will be back.
