### ISSUE TITLE
GIFs are tiny and don't react to zoom

### ISSUE THREAD

**Issue by Danmou** [wandb/client#599]
My model saves gif summaries of size 640x128. In the web interface they look like this:
![image](https://user-images.githubusercontent.com/7031745/66306082-16e73100-e901-11e9-8feb-9acb4be421bf.png)

and changing the zoom setting has no effect. Images of the same size work fine.

**Comment by cvphelps** [comment]
Hi! Thanks for reporting this issue. We'll take a look.

**Comment by nbardy** [comment]
@Danmou This has been fixed and deployed.
