### ISSUE TITLE
MIME encoding inconsistency for some files

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#602]
Most of text files in my Files list open in browser, but occasionally a file will trigger a download. I suspect it's something to do with how the server reports Mime type which is inconstent for some reason

IE, this file `sample-uncond-6500step.txt` triggers a download
https://app.wandb.ai/yaroslavvb/Transformer-XL%20source%20code/runs/c81802pd/files

<img width="417" alt="Screenshot 2019-10-09 14 30 31" src="https://user-images.githubusercontent.com/23068/66522048-5cdafb00-eaa1-11e9-809b-3bbbb2aa082e.png">

**Comment by cvphelps** [comment]
Thank you for letting us know Yaroslav!

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
