### ISSUE TITLE
save content of auto-visualizations searchbox in workspace

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#605]
I think things typed inside "AUTO VISUALIZATIONS" box should be saved in workspace. I recently wanted to share the view below, and there was no easy way

https://app.wandb.ai/yaroslavvb/train_ciresan/runs/zsbxp84k?workspace=default

<img width="1111" alt="Screenshot 2019-10-09 20 41 48" src="https://user-images.githubusercontent.com/23068/66537478-6bdba080-ead5-11e9-9340-1faa3f547508.png">

**Comment by cvphelps** [comment]
Good idea, thank you Yaroslav!

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
