### ISSUE TITLE
Sweep does not work on Windows

### ISSUE THREAD

**Issue by TKassis** [wandb/client#612]
* Weights and Biases version: 0.8.12
* Python version: 3.6.7
* Operating System: Windows 10

### Description
When I run `wandb agent [sweep ID]` on Windows I get:
`wandb: ERROR Agent is not supported on Windows`

Does the Windows client not support the sweep functionality?

**Comment by vanpelt** [comment]
@TKassis Thanks for the documentation contribution.  I have a branch that supports sweeps that we're planning to push to 0.8.13 this week.  You can try it with `pip install --upgrade git+git://github.com/wandb/client.git@feature/windows-no-run#egg=wandb`

**Comment by TKassis** [comment]
Ah, sounds great! I can't install the branch for some reason. I'll wait for the 0.8.13 release.
