### ISSUE TITLE
"Export as report" turns single chart with multiple series into multiple charts

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#622]
workspace: https://app.wandb.ai/yaroslavvb/train_ciresan/runs/2xo28nk2?workspace=default
report: https://app.wandb.ai/yaroslavvb/train_ciresan/reports?view=yaroslavvb%2Fregret-ratios

Workspace
<img width="629" alt="Screenshot 2019-10-18 09 39 40" src="https://user-images.githubusercontent.com/23068/67112065-37c64680-f18b-11e9-8c3e-ce98350bab4e.png">

becomes

<img width="640" alt="Screenshot 2019-10-18 09 40 22" src="https://user-images.githubusercontent.com/23068/67112109-5298bb00-f18b-11e9-96e5-e690840d0fec.png">

**Comment by cvphelps** [comment]
Hello Yaroslav! At the moment, only the run page supports a single chart with multiple metrics on it. We're hoping to fix this soon!

**Comment by ariG23498** [comment]
Hey @yaroslavvb 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
