### ISSUE TITLE
UI bug in a chart with multiple series

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/client#623]
Trying to select a region around step 1M makes all the lines disappear, in this workspace https://app.wandb.ai/yaroslavvb/train_ciresan/runs/2xo28nk2?workspace=default

<img width="640" alt="Screenshot 2019-10-18 09 43 41" src="https://user-images.githubusercontent.com/23068/67112373-e9fe0e00-f18b-11e9-8bab-8af8c6860111.png">

<img width="529" alt="Screenshot 2019-10-18 09 43 48" src="https://user-images.githubusercontent.com/23068/67112381-ee2a2b80-f18b-11e9-8354-3351b5d42539.png">

**Comment by cvphelps** [comment]
Hi Yaroslav, thank you for reporting this!

**Comment by cvphelps** [comment]
Looks like this is fixed! ([link](https://app.wandb.ai/yaroslavvb/train_ciresan/runs/2xo28nk2?workspace=default))
![bug fix - zooming](https://user-images.githubusercontent.com/6355078/72227111-8b0f2180-354d-11ea-8c6c-3da0949b80a3.gif)
