### ISSUE TITLE
Feature Request: Bar charts or tables in reports

### ISSUE THREAD

**Issue by DNGros** [wandb/client#632]
Hello!
 
I'm new to wandb and have been exploring it and other experiment logging solutions to see what makes the most sense for my needs. A more unique feature of wandb that I really like is the reports feature, which seems like a convenient way summarize key results to share with others on the team (or just keep organized for your own sanity).

However, currently the kinds of visualizations available to tell a story in a report seems somewhat limited.

I was wondering if it was possible or planned to add a bar chart or table of single metrics between runs. Currently the only option only seems to be an option to add line charts. This is fine, but a lot of times I only care about one result of an experiment to compare with others (final loss, highest accuracy, compute time, etc), and having a spaghetti of lines over the whole training just adds clutter and cognitive burden when interpreting.

It would be great if one could select a bar chart with customizable x, y, and hue (or "barmode" grouping in plotly) to compare runs.

If not a bar chart, a table with customizable rows and column parameters would also work for comparing results between runs, and is something that is presented all the time in papers.

I understand you can log custom plots and tables during a run, but this does not seem to help when comparing between runs.

Alternatively, without bar charts visualizations or table, how have others found the best way to compare non-step-dependent results between runs?

**Comment by lukas** [comment]
Hi - I definitely think we could support this better.  We do support tables of data, for example check out https://app.wandb.ai/qualcomm/scikit-dec4?workspace=user-l2k2 and we will visualize bar charts across multiple runs (but you confusingly need to select line plot right now which is a bug).

**Comment by DNGros** [comment]
Hi Lukas, thanks for your reply.

I haven't been able to recreate the chart in the link you shared in my own separate project (not sure if it is only enabled in certain projects), and even within that linked project, the UI does seem rather buggy as you mentioned.

Still looks exciting to see that such charts are somehow possible or might be eventually.

(also, if this feature request exists somewhere on your WebClient backlog, feel free to close this github issue. This isn't really related to the W&B python client, but this seemed like an available place to post an issue).

**Comment by ariG23498** [comment]
Hey @DNGros 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
