### ISSUE TITLE
Lost run: wandb/settings source contains parsing errors

### ISSUE THREAD

**Issue by mboratko** [wandb/client#637]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.13
* Python version: 3.7.4
* Operating System: Linux

### Description

When running multiple simultaneous jobs on a cluster it seems as though the wandb/settings file can become corrupted. In particular, I believe the cluster I was working on uses NFS storage, and different wandb processes (on different machines) were trying to read/write to the wandb/settings file at the same time.

### What I Did

1. Created a test file initializing wandb:
```
# wandb_test.py
import wandb
from random import random
from time import sleep
wandb.init(project="testing-concurrency")

wandb.config.something = 3.1459
for i in range(200):
    sleep(random())
    wandb.log({"epoch": i/10, "loss": 1/i**0.5})
```
2. Ran 100 jobs using SLURM.

### Results
99 jobs were logged into the Weights and Biases online interface. When researching why, I found this in the output logs:
```
slurm-5468220_30.out:configparser.ParsingError: Source contains parsing errors: '/path/to/file/wandb/settings'
```

**Comment by cvphelps** [comment]
Hello mboratko, thank you for reporting this issue!

**Comment by vanpelt** [comment]
Hey @mboratko I believe this is an issue with the shared filesystem.  We're working on a fix, until then you can get around this by adding the following to your wandb.init calls:

```python
import tempfile
wandb.init(project="testing-concurrency", dir=tempfile.mkdtemp())
```

**Comment by ariG23498** [comment]
Hey @mboratko 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
