### ISSUE TITLE
missing uploaded images

### ISSUE THREAD

**Issue by vict0rsch** [wandb/client#650]
* Weights and Biases version: 0.8.13
* Python version:  3.6.4
* Operating System: Darwin

### Description

Testing the image upload functionality I can't understand why I only get 19 uploaded images, for some reason the last image is not on the run's page

### What I Did

```python
$ ipython

In [1]: import numpy as np

In [2]: import time

In [3]: import wandb

In [4]: wandb.init()
   ...: for i in range(20):
   ...:     wandb.log({
   ...:     "some_image": [
   ...:         wandb.Image(
   ...:             np.random.randint(0, np.random.randint(100, 256), (256, 256, 3)),
   ...:             caption='image ' + str(i) + " " + str(j))
   ...:         for j in range(3)
   ...:         ]
   ...:     }, step=i)
   ...:     time.sleep(1)

<IPython.core.display.HTML object>
Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable

In [5]:
Do you really want to exit ([y]/n)? ^D
```

This happens consistently: last image never uploaded

**Comment by vanpelt** [comment]
This is a bug in Jupyter.  We’re working on a fix.  For now you can call wandb.log({}) once outside of your forloop to push the final image.

**Comment by ariG23498** [comment]
Hey @vict0rsch 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
