### ISSUE TITLE
Support Google Storage Buckets as output directory

### ISSUE THREAD

**Issue by aidangomez** [wandb/client#652]
* Weights and Biases version: 0.8.13
* Python version: 3.7
* Operating System: Debian

### Description

On Google Cloud, gs:// buckets are not recognised by `wandb.init(..., dir="gs://etc/etc")`

Reading and writing to buckets requires doing something like this: https://cloud.google.com/appengine/docs/standard/python/googlecloudstorageclient/read-write-to-cloud-storage#writing_to_cloud_storage

Or using tf.gfile

Since TPUs can **only** read and write checkpoints to `gs` this prevents us from using wanb whenever we want to use TPU hardware.

**Comment by vanpelt** [comment]
This would be a great feature, I'm concerned implementing it this way will be rather involved.  W&B uses the local filesystem to listen for events and trigger api calls.  What's the exact environment you're using the TPU's from?  I want to mess around and see if there's a creative solution.

**Comment by aidangomez** [comment]
Glad you agree it's an important feature! 

The environment is just the default Debian gcloud CPU instance, create a bucket on Google Storage, try running `wandb.init(dir="gs://your-bucket")` and have a look at `wandb.run.dir`

**Comment by aidangomez** [comment]
@vanpelt any updates? Does it fail for you too?

**Comment by vanpelt** [comment]
Hey @aidangomez it will definitely not work when specifying gs:// as a directory.  We may be adding this functionality in the future, but it is fairly low on our list of priorities.  You should still be able to write to a local directory on the gcloud instance and all files written to it will be synced to our managed google cloud storage bucket.  Is this not working for you?

As a stop gap, you could call `wandb.restore("checkpoint.cpk")` to save the file locally, then push it to your cloud storage bucket.

**Comment by aidangomez** [comment]
So when using TF w/ TPUs you actually can't read or write data + checkpoints locally, it's all done with gs:// (there isn't an alternative). 

So we could transfer checkpoints and summaries from the bucket to the local machine and then sync with wandb, but if I have a model with 5GB checkpoint files I don't want to have to pause training to perform that large of a sync, so we'll need to write logic to do this asynchronously.

I think that since read/write from gs buckets is considered standard for TF, wandb stands to gain a great deal from supporting it. The overhead of writing and incorporating into a training script a daemon syncing between gs:// and the local fs means that a lot of people simply won't use wandb.

Hopefully it will be prioritised at some point to improve usability of wandb for TPU users.

**Comment by ariG23498** [comment]
Hey @aidangomez 
Thanks for the lovely explanation.
I am closing this ticket due to the inactivity. In the past year we've majorly reworked the CLI and UI for Weights & Biases. Please comment to reopen.

**Comment by AdityaKane2001** [comment]
@vanpelt @ariG23498 

Is this a part of WandB now?

**Comment by vanpelt** [comment]
@AdityaKane2001 you can store data directly in google cloud storage and use [artifact references](https://docs.wandb.ai/guides/artifacts/references#s3-gcs-references).
