### ISSUE TITLE
There should be an easier way to get default entity and project from Python

### ISSUE THREAD

**Issue by Danmou** [wandb/client#655]
`wandb.init()` reads the entity and project from the `wandb/settings` file if they are not specified. However, when using `wandb.Api()`, the functions fail if you don't specify the entity and project. It would be more intuitive if they would use the same default settings. Also, there is no documented way to get the default settings. I found a way, but it's not very elegant:
```python
entity = wandb.settings.Settings().get('default', 'entity')
project = wandb.settings.Settings().get('default', 'project')
```

**Comment by lukas** [comment]
That's a good point.  Seems like we should make wandb.Api look at the settings file for defaults.  @vanpelt do you have an opinion?

**Comment by vanpelt** [comment]
Yeah, we'll add this in the next release.

**Comment by ariG23498** [comment]
Hey @Danmou 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
