### ISSUE TITLE
Web App AutoViz creates New Names based on time & hostname

### ISSUE THREAD

**Issue by tshrjn** [wandb/client#664]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.14
* Python version: 3.7.5
* Operating System: Linux

The auto viz tool on the web app is making a new chart each time with date & hostname, & isn't plotting on the same section.

Also, if multiple sections are open, I'm unable to scroll down on the webpage.

**Comment by vanpelt** [comment]
Hey @tshrjn can you add a link to the page you’re seeing this on?

**Comment by tshrjn** [comment]
Hi this issue is on: https://app.wandb.ai/al_nlu/al_data_acquistion

**Comment by vanpelt** [comment]
Hey @tshrjn, how are you logging your metrics?  Those metrics names are defined by the keys in your calls to `wandb.log`.  Are you calling wandb.log manually or using a callback?

**Comment by tshrjn** [comment]
Using `sync_tensorboard` at init and logging via `torch.utils.tensorboard`.

It was because of import order, import wandb before torch resolved it.

**Comment by vanpelt** [comment]
Good to know, I think it was namespacing your runs by the logdir which had a date in it.  When you change the order are you still seeing all the metrics you're logging to tboard?

**Comment by ariG23498** [comment]
Hey @tshrjn 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
