### ISSUE TITLE
WandbCallback fastai failed to show prediction images on wandb app

### ISSUE THREAD

**Issue by phucnsp** [wandb/client#672]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.15
* Python version: 3.6
* Operating System: Linux (google colab)

Hi,
I was using `wandb.fastai.WandbCallback` with setting `input_type="images"` to send prediction images after each epoch to wandb app. It did send prediction images to wandb app but it did not show anything in _AUTO VISUALIZATION/MEDIA/Prediction Samples_ 
(it appears the message of "this run didn't log images for key "Prediction Samples, step 2, index 0." )
I digged into the source code of WandbCallback and replace the line 193 - `wandb.log({"Prediction Samples": pred_log}, commit=False)` by this `wandb.log({"prediction": pred_log}, commit=False)`, and it worked. Now the images can show in _AUTO VISUALIZATION/MEDIA/prediction_

Please help to check this issue.

**Comment by vanpelt** [comment]
Hey @phucnsp, sorry for the delay.  Can you point me to a run url this was happening for you in?  I think it may be fixed now.

**Comment by ariG23498** [comment]
Hey @phucnsp 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
