### ISSUE TITLE
Error while calling W&B API: permission denied

### ISSUE THREAD

**Issue by bamal** [wandb/client#673]
Hello, 

I am training a model on a remote server and I got this error after running on the terminal `wandb login` and running the training script itself. 

```
wandb: Tracking run with wandb version 0.8.15
wandb: Run data is saved locally in wandb/run-20191107_074736-rjih2419
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
wandb: ERROR Launch exception: Permission denied to access wandb/Dressyou Recommender system/rjih2419
wandb: ERROR To disable wandb syncing set WANDB_MODE=dryrun
wandb: ERROR W&B process (PID 19599) did not respond
wandb: ERROR W&B process failed to launch, see: wandb/debug.log
Traceback (most recent call last):
  File "script/train.py", line 168, in <module>
    wandb.init(entity="wandb", project="Dressyou Recommender system")
  File "/home/amal/miniconda3/envs/all_dep_cuda/lib/python3.7/site-packages/wandb/__init__.py", line 1051, in init
    _init_headless(run)
  File "/home/amal/miniconda3/envs/all_dep_cuda/lib/python3.7/site-packages/wandb/__init__.py", line 288, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.log
```
Do you have an idea how to solve this please ?

**Comment by vanpelt** [comment]
Hey @bamal it looks like you're trying to launch runs into the "wandb" team.  The quickest fix is to set entity="bamal" (or your wandb username) when you call wandb.init

**Comment by radoye** [comment]
@vanpelt This indeed solves the problem. It is a bit confusing when the `sample-project` instructions fail, though. Maybe mention this there?

**Comment by shawnlewis** [comment]
Where did you get the sample project instructions? From the UI? Can you paste what you're seeing?

It looks like that run was from an old version of wandb, 0.8.15. The latest version shouldn't have this issue.

**Comment by radoye** [comment]
Sure, here's the output

```bash
wandb: Appending key for api.wandb.ai to your netrc file: /home/rrs/.netrc
Successfully logged in to Weights & Biases!

[rrs@/home/rrs/tf.sif]-[jobs:0]-[~/docks/dev/learn/wandb/tutorial]
$ python tutorial.py
Using TensorFlow backend.
2020-04-14 16:33:47.382557: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-14 16:33:47.383710: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
wandb: Tracking run with wandb version 0.8.31
wandb: Run data is saved locally in wandb/run-20200414_233348-2kd35ww6
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
wandb: ERROR Launch exception: Permission denied to access wandb/set-run-name-to-id/2kd35ww6
wandb: ERROR To disable wandb syncing set WANDB_MODE=dryrun
wandb: ERROR W&B process (PID 16419) did not respond
wandb: ERROR W&B process failed to launch, see: wandb/debug.log
Traceback (most recent call last):
  File "tutorial.py", line 33, in <module>
    wandb.init(config=hyperparameter_defaults)#, entity="rrs")
  File "/home/rrs/.local/lib/python3.6/site-packages/wandb/__init__.py", line 1090, in init
    _init_headless(run)
  File "/home/rrs/.local/lib/python3.6/site-packages/wandb/__init__.py", line 306, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.log

[rrs@/home/rrs/tf.sif]-[jobs:0]-[~/docks/dev/learn/wandb/tutorial]
```

Notes: 
- Installed ~10 mins ago
- My TF environment is in a singularity container (so `pip install --user` was used)
- C-c C-v the instructions from the `sample-project` page under my Projects on wandb

**Comment by vanpelt** [comment]
Hey @radoye that's a permission error.  You're trying to save results to `entity="wandb", project="set-run-name-to-id"` which you don't have permission to.  In your call to init, add `entity="YOUR_USERNAME"` and try again.

**Comment by andrewjong** [comment]
I also encountered this error in the sample-project. The sample-project shows up the first time the user views https://app.wandb.ai/home. The instructions do not specify you need to add entity="YOUR_USERNAME" to `tutorial.py`. I agree with radoye that this instruction should be added.

**Comment by vanpelt** [comment]
Yep, we'll update the tutorial.

**Comment by cvphelps** [comment]
Here's the updated tutorial, settings file removed so runs aren't going to the wandb entity: https://github.com/wandb/tutorial

**Comment by karenc3** [comment]
Hi,

I'm still getting the error. I've included my username in the `wandb.init()` call. Please find the error displayed on the command line below(I've replaced my username).

```
wandb: Tracking run with wandb version 0.9.4
wandb: Run data is saved locally in wandb\run-20200805_212707-2py2az48
wandb: ERROR Error while calling W&B API: permission denied (<Response [401]>)
wandb: ERROR Launch exception: Invalid or missing api_key.  Run wandb login
wandb: ERROR To disable wandb syncing set WANDB_MODE=dryrun
wandb: ERROR W&B process (PID 368) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
Traceback (most recent call last):
  File "src\test.py", line 15, in <module>
    wandb.init(project='sklearn_experiments', entity=<wandb-username>, name='first_exp')
  File "C:\Users\nachiket.kare\Envs\wandbenv\lib\site-packages\wandb\__init__.py", line 1280, in init
    _init_headless(run)
  File "C:\Users\nachiket.kare\Envs\wandbenv\lib\site-packages\wandb\__init__.py", line 332, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log
```


In the code I'm just trying to build a classification model and a regression model and log the metrics and plot the classifier/regressor.

**Comment by karenc3** [comment]
Hi,

I'm still getting the error. I've included the username and also successfully executed the  `wandb login` command from the command line. I'm running the code on windows.

```
(wandbenv) >wandb login <api-key>
wandb: Appending key for api.wandb.ai to your netrc file: .netrc
Successfully logged in to Weights & Biases!

(wandbenv) >python src\test.py
wandb: Tracking run with wandb version 0.9.4
wandb: Run data is saved locally in wandb\run-20200805_213857-3s8rm7rb
wandb: ERROR Error while calling W&B API: permission denied (<Response [401]>)
wandb: ERROR Launch exception: Invalid or missing api_key.  Run wandb login
wandb: ERROR To disable wandb syncing set WANDB_MODE=dryrun
wandb: ERROR W&B process (PID 16216) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
Traceback (most recent call last):
  File "src\test.py", line 15, in <module>
    wandb.init(project='sklearn_experiments', entity=<wandb-username>, name='first_exp')
  File "Envs\wandbenv\lib\site-packages\wandb\__init__.py", line 1280, in init
    _init_headless(run)
  File "Envs\wandbenv\lib\site-packages\wandb\__init__.py", line 332, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log
```

In the code I'm trying to run a regression model and a classification model and log the model and metric for both of them.

**Comment by ariG23498** [comment]
Hey @karenc3 
Do you still notice this error?

**Comment by copperwiring** [comment]
@vanpelt `viewmaker` is the code repo from which I am running it so I am assuming it takes it as the team. Username is sulphur so  entity=sulphur? If yes, how to edit it?

**Comment by vanpelt** [comment]
@copperwiring correct, entity should be set to "sulphur" or you can just remove the entity argument altogether and it should default to "sulphur".  The stacktrace shows that `scripts/run_image.py` is calling `wandb.init(project='image', entity='viewmaker', ...)` on line 67.

**Comment by stelais** [comment]
> 

Hi @vanpelt, I have more than one teamwork, and I don't know exactly why, but wandb keeps me logging in to the team I didn't want to. Even though I set the entity as the right one, it keeps finding the other one. I also have logged in with the right code. any thoughts?

**Comment by stelais** [comment]
> @copperwiring what's your wandb username? The code is specifying `wandb.init(project="image", entity="viewmaker")` which means you must be on the `viewmaker` team.

Hi @vanpelt , I am having a similar issue. However, in my case, I am part of more than one teamwork. My wandb keeps logging in to only one of them. I have tried deleting the old entry from my `.netrc` file and deleting the `wandb/settings` file as well. And then redoing the `wandb login` with the correct `API_KEY`, but it still shows `wandb: Currently logged in as: old-team` . Any advices? I tried setting the `entity` as my user and as the team name, but the two solutions find the old team.

**Comment by brando90** [comment]
@vanpelt I have a similar issue. details here:
- https://community.wandb.ai/t/wandb-automatically-logeed-into-the-wrong-user-why/2916/7
- https://stackoverflow.com/questions/73335735/wandb-automatically-logeed-into-the-wrong-user-why/73335943#73335943

**Comment by djaym7** [comment]
why is this closed ?

**Comment by balloch** [comment]
to anyone who has stumbled upon this topic, ensure that your program isn't setting your "entity" somewhere in your code. It will default to your account when you are logged in, but if it is set somewhere else it will still show you as logged in successfully but will deny you (because your account doesn't have access to this other entity)

**Comment by sorenwacker** [comment]
I also have this issue.
