### ISSUE TITLE
 Error 3143: Invalid JSON path expression. The error is around character position 62.

### ISSUE THREAD

**Issue by tomginsberg** [wandb/client#677]
wandb, version 0.8.15
Python 3.7.4
Mac OS Darwin

### Description

I logged several runs in a project that appear to have some errors in them (I'm really not sure what specifically). But now when I view project runs I get the error message 
![image](https://user-images.githubusercontent.com/10860163/68805661-8d93ee80-0664-11ea-8888-21a7b7237adb.png)

### What I Did

There's nothing that I can really do besides log more runs and only open them from the home page. I cannot delete the faulty runs, so it has practically corrupted my whole project.

**Comment by tsholmes** [comment]
hey @tomginsberg thanks for the report. this should be fixed now.
