### ISSUE TITLE
Logging results to Weights & Biases. Couldn't load entity due to error: Can't connect to network to query entity from API key

### ISSUE THREAD

**Issue by ajay340** [wandb/client#678]
* Weights and Biases version: 0.8.15
* Python version: 3.7.4
* Operating System: Windows 10

### Description

I updated the library and logged into wandb successfully through cli.
I tried importing this snippet of code: 
```import wandb
from wandb.keras import WandbCallback
wandb.init(project="my_project_name")
```

into my jupyter notebook and when I run all of my cells sequentially, I get this error:

```
AttributeError                            Traceback (most recent call last)
C:\Python37\lib\site-packages\wandb\meta.py in setup(self)
     46             import __main__
---> 47             self.data["program"] = __main__.__file__
     48         except (ImportError, AttributeError):

AttributeError: module '__main__' has no attribute '__file__'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
 in 
      1 import wandb
      2 from wandb.keras import WandbCallback
----> 3 wandb.init(project="my_project_name")

C:\Python37\lib\site-packages\wandb\__init__.py in init(job_type, dir, config, project, entity, reinit, tags, group, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, name, notes, id, magic, anonymous)
   1068         allow_val_change = True
   1069     if config or telemetry_updated:
-> 1070         run.config._update(config, allow_val_change=allow_val_change, as_defaults=not allow_val_change)
   1071 
   1072     # Access history to ensure resumed is set when resuming

C:\Python37\lib\site-packages\wandb\wandb_config.py in _update(self, params, allow_val_change, as_defaults)
    276                 continue
    277             self._items[key] = val
--> 278         self.persist()
    279 
    280     def update(self, params, allow_val_change=False):

C:\Python37\lib\site-packages\wandb\wandb_config.py in persist(self)
    194             conf_file.write(str(self))
    195         if wandb.run and wandb.run._jupyter_agent:
--> 196             wandb.run._jupyter_agent.start()
    197 
    198     def get(self, *args):

C:\Python37\lib\site-packages\wandb\jupyter.py in start(self)
    120     def start(self):
    121         if self.paused:
--> 122             self.rm = RunManager(wandb.run, output=False, cloud=wandb.run.mode != "dryrun")
    123             wandb.run.api._file_stream_api = None
    124             self.rm.mirror_stdout_stderr()

C:\Python37\lib\site-packages\wandb\run_manager.py in __init__(self, run, project, tags, cloud, output, port)
    504         # Calling .start() on _meta and _system_stats will spin a thread that reports system stats every 30 seconds
    505         self._system_stats = stats.SystemStats(run, self._api)
--> 506         self._meta = meta.Meta(self._api, self._run.dir)
    507         self._meta.data["jobType"] = self._run.job_type
    508         self._meta.data["mode"] = self._run.mode

C:\Python37\lib\site-packages\wandb\meta.py in __init__(self, api, out_dir)
     34             self.data = {}
     35         self.lock = threading.Lock()
---> 36         self.setup()
     37         self._thread = threading.Thread(target=self._thread_body)
     38         self._thread.daemon = True

C:\Python37\lib\site-packages\wandb\meta.py in setup(self)
     52                     self.data["program"] = os.getenv(env.NOTEBOOK_NAME)
     53                 else:
---> 54                     meta = wandb.jupyter.notebook_metadata()
     55                     if meta.get("path"):
     56                         if "fileId=" in meta["path"]:

C:\Python37\lib\site-packages\wandb\jupyter.py in notebook_metadata()
    108             if isinstance(nn, dict) and nn.get("kernel"):
    109                 if nn['kernel']['id'] == kernel_id:
--> 110                     return {"root": s['notebook_dir'], "path": nn['notebook']['path'], "name": nn['notebook']['name']}
    111     return {}
    112 

KeyError: 'notebook'
```

### What I Did

```
pip install --upgrade wandb
wandb login <insert token>


import wandb
from wandb.keras import WandbCallback
wandb.init(project="my_project_name")


```

**Comment by T3hlo** [comment]
Have the same problem have you found out what is causing it?

**Comment by ajay340** [comment]
> 
> 
> Have the same problem have you found out what is causing it?

A workaround I did was run the weights and biases in a normal python script and then run it again in the notebook and then it started working.

**Comment by ajay340** [comment]
> 
> 
> > Have the same problem have you found out what is causing it?
> 
>  ̶A̶ ̶w̶o̶r̶k̶a̶r̶o̶u̶n̶d̶ ̶I̶ ̶d̶i̶d̶ ̶w̶a̶s̶ ̶r̶u̶n̶ ̶t̶h̶e̶ ̶w̶e̶i̶g̶h̶t̶s̶ ̶a̶n̶d̶ ̶b̶i̶a̶s̶e̶s̶ ̶i̶n̶ ̶a̶ ̶n̶o̶r̶m̶a̶l̶ ̶p̶y̶t̶h̶o̶n̶ ̶s̶c̶r̶i̶p̶t̶ ̶a̶n̶d̶ ̶t̶h̶e̶n̶ ̶r̶u̶n̶ ̶i̶t̶ ̶a̶g̶a̶i̶n̶ ̶i̶n̶ ̶t̶h̶e̶ ̶n̶o̶t̶e̶b̶o̶o̶k̶ ̶a̶n̶d̶ ̶t̶h̶e̶n̶ ̶i̶t̶ ̶s̶t̶a̶r̶t̶e̶d̶ ̶w̶o̶r̶k̶i̶n̶g̶.̶

Nevermind this workaround is no longer working.

**Comment by vanpelt** [comment]
@ajay340 set enitity to your username when you call wandb.init

**Comment by ajay340** [comment]
> 
> 
> @ajay340 set enitity to your username when you call wandb.init

Thanks it started working when I set the entity in my wandb.init

**Comment by vanpelt** [comment]
Cool, we’ll have a fix for the root cause in the next release!

**Comment by jwanga** [comment]
Hi. Im still experiencing this issue with version 0.8.19. 
I'm not sure what is meant by:
> set enitity to your username when you call wandb.init
Can you post an example?
Thank you.

**Comment by jwanga** [comment]
Nevermind my comment above. I sorted out that I need to do: 
`wandb.init(project="project-name", entity="username")`
However, I'm still receiving:
`KeyError: 'notebook'`

**Comment by vanpelt** [comment]
Hey @jwanga can you share the full stacktrace for the KeyError you're seeing?

**Comment by jwanga** [comment]
@vanpelt
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/wandb/meta.py in setup(self)
     46             import __main__
---> 47             self.data["program"] = __main__.__file__
     48         except (ImportError, AttributeError):

AttributeError: module '__main__' has no attribute '__file__'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
 in 
      3 get_ipython().system(' wandb login 12121212121212121212121212121212121')
----> 4 wandb.init(project="project-name", entity="username")

/usr/local/lib/python3.7/site-packages/wandb/__init__.py in init(job_type, dir, config, project, entity, reinit, tags, group, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, name, notes, id, magic, anonymous)
   1084         allow_val_change = True
   1085     if config or telemetry_updated:
-> 1086         run.config._update(config, allow_val_change=allow_val_change, as_defaults=not allow_val_change)
   1087 
   1088     # Access history to ensure resumed is set when resuming

/usr/local/lib/python3.7/site-packages/wandb/wandb_config.py in _update(self, params, allow_val_change, as_defaults)
    277                 continue
    278             self._items[key] = val
--> 279         self.persist()
    280 
    281     def update(self, params, allow_val_change=False):

/usr/local/lib/python3.7/site-packages/wandb/wandb_config.py in persist(self)
    195             conf_file.write(str(self))
    196         if wandb.run and wandb.run._jupyter_agent:
--> 197             wandb.run._jupyter_agent.start()
    198 
    199     def get(self, *args):

/usr/local/lib/python3.7/site-packages/wandb/jupyter.py in start(self)
    120     def start(self):
    121         if self.paused:
--> 122             self.rm = RunManager(wandb.run, output=False, cloud=wandb.run.mode != "dryrun")
    123             wandb.run.api._file_stream_api = None
    124             self.rm.mirror_stdout_stderr()

/usr/local/lib/python3.7/site-packages/wandb/run_manager.py in __init__(self, run, project, tags, cloud, output, port)
    504         # Calling .start() on _meta and _system_stats will spin a thread that reports system stats every 30 seconds
    505         self._system_stats = stats.SystemStats(run, self._api)
--> 506         self._meta = meta.Meta(self._api, self._run.dir)
    507         self._meta.data["jobType"] = self._run.job_type
    508         self._meta.data["mode"] = self._run.mode

/usr/local/lib/python3.7/site-packages/wandb/meta.py in __init__(self, api, out_dir)
     34             self.data = {}
     35         self.lock = threading.Lock()
---> 36         self.setup()
     37         self._thread = threading.Thread(target=self._thread_body)
     38         self._thread.daemon = True

/usr/local/lib/python3.7/site-packages/wandb/meta.py in setup(self)
     52                     self.data["program"] = os.getenv(env.NOTEBOOK_NAME)
     53                 else:
---> 54                     meta = wandb.jupyter.notebook_metadata()
     55                     if meta.get("path"):
     56                         if "fileId=" in meta["path"]:

/usr/local/lib/python3.7/site-packages/wandb/jupyter.py in notebook_metadata()
    108             if isinstance(nn, dict) and nn.get("kernel"):
    109                 if nn['kernel']['id'] == kernel_id:
--> 110                     return {"root": s['notebook_dir'], "path": nn['notebook']['path'], "name": nn['notebook']['name']}
    111     return {}
    112 

KeyError: 'notebook'
`

**Comment by jwanga** [comment]
@vanpelt created a PR to address the issue I was seeing. Its partially a bug in the Jupiter instance that ships with VSCode. So I added some code to handle it gracefully.

https://github.com/wandb/client/pull/782

**Comment by ajay340** [comment]
Just wanted to update that my issue still persists despite that I have added the entity parameter in the wandb.init function.

**Comment by jwanga** [comment]
@ajay340 try upgrading to v0.8.22. It includes my PR that fixed the issue for me.

**Comment by ajay340** [comment]
@jwanga I have upgraded to 0.8.22 and the issue still persists.

**Comment by jwanga** [comment]
@ajay340 can you post your newest stack trace again?

**Comment by ajay340** [comment]
@jwanga Sorry about that. I had updated my wandb package but not jupyter. So I updated and restarted jupyter and now it is working.
