### ISSUE TITLE
Feature request: upload file once

### ISSUE THREAD

**Issue by vwxyzjn** [wandb/client#679]
`wandb --version && python --version && uname`

wandb, version 0.8.13
Python 3.7.4
Linux

### Description

The file save function only supports "live" and "end" policies, but I was wondering if "once" policy could be added. Where the when `wandb.save("test.txt", policy="once")` is called, "test.txt" is uploaded once and it happens immediately with no future tracking or updates on this file.

**Use case**: sometimes I modify the files in a way that is not easily characterizable by hyper-parameters. It is desirable if the particular version of this file is uploaded. However, I lately realized that, because of the default "live" policy, the file is uploaded and overwritten again as I modify the file, which is not desirable in my use case.

In a way, it almost sounds like `sync` is a more proper name to this function than `save` because of the update policy. `save` should perhaps be more low-level that it saves the file as what it sees at that moment when it was called. 

I also suspect that the policy "end" is perhaps not necessary. If the user desire to save the files in the end, why couldn't they just call `wandb.save("test.txt")` just before the script finishes?

In any case, I think it would perhaps be desirable to have two separate functions

```python
# upload the file as it changes, overwriting the previous version
wandb.sync("test.txt") 
# upload the file once and immediately
wandb.save("test.txt")
```

**Comment by vanpelt** [comment]
Sorry for the delay, this is a great feature request.  I think the easiest implementation is to add a "once" policy.  I like the sync api idea, we'll target that for 1.0.  As an immediate fix for your usecase you can copy the file to `wandb.run.dir` then call `wandb.save("filename")` to apply the "live" policy to it.  Then just don't copy the file when you modify the original.

**Comment by ariG23498** [comment]
Hey @vwxyzjn 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
