### ISSUE TITLE
wandb.log information does not appear in wandb app when I initiate the engine with `wandb.init(reinit=True)`

### ISSUE THREAD

**Issue by seilna** [wandb/client#683]
### Environment
* Weights and Biases version: 0.8.15
* Python version: 3.7.4
* Operating System: Linux

### Description
I used `wandb.init(project='my project', reinit=True)`, because I want to launch multiple runs in single process. Then, I wrote the code so that each run logs its test performance as follows:
```python
for run in range(n_multiple_runs_with_different_setting):
    wandb.init(project='my project', reinit=True)
    # ... some training script ...
    test_performance = measure_acc(my_model, test_data)
    wandb.log({'performance': test_performance})
```
But I can't see any performance logged in my wandb app. It just shows some hyperparameters I set.
If I fix the init code as `wandb.init(project='my project', reinit=False)`, it successfully log its performance, but as you know, it only works at first run.
Is this behavior intended? How I can do logging for multiple runs in single process?

**Comment by vanpelt** [comment]
Hey @seilna if you run `wandb.join()` at the end of the loop it should work.  We're working on improvements to this scenario.

**Comment by yonathansantosa** [comment]
Somehow I still get the following error after the first loop using `wandb.join()`

```
OSError: [WinError 6] The handle is invalid
wandb: ERROR W&B process (PID 19696) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
```
