### ISSUE TITLE
%%wandb doen't work in PyCharm

### ISSUE THREAD

**Issue by YahngSungho** [wandb/client#687]
`wandb --version && python --version && uname`

* Weights and Biases version: latest
* Python version: 3.7
* Operating System: Windows7

![2019-11-21 11 34 39 dlProject  C__Users_Administrator_PycharmProjects_dlProject  -  _trySomething_wandb ipynb - PyCharm (Administrator)](https://user-images.githubusercontent.com/29212791/69299171-3d63f000-0c53-11ea-9fbc-7c3bb37eac7e.png)

The error 'Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable' occurs

When I tried on web browser with jupyter, it seems to work but the error still occurs

![2019-11-21 11 36 50 wandb - Jupyter Notebook - Chrome](https://user-images.githubusercontent.com/29212791/69299235-68e6da80-0c53-11ea-812c-a178e958c68a.png)

Should I set WANDB_NOTEBOOK_NAME correctly? But I couldn't find what name should I set on this field...

**Comment by vanpelt** [comment]
Setting the WANDB_NOTEBOOK_NAME is optional.  You should set it to whatever your notebook is named, i.e. "My Notebook.ipynb".  The error you're seeing isn't related though.  If you rerun the cell in pycharm does it show up?

**Comment by YahngSungho** [comment]
@vanpelt 
The error message disappeared so there's difference, but still doesn't work

![2019-11-21 14 24 50 dlProject  C__Users_Administrator_PycharmProjects_dlProject  -  _trySomething_wandb ipynb - PyCharm (Administrator)](https://user-images.githubusercontent.com/29212791/69306491-fc77d580-0c6a-11ea-947f-df8d30346f20.png)

**Comment by ariG23498** [comment]
Hey @YahngSungho 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
