### ISSUE TITLE
%%wandb not loaded before calling wandb.init() at least once

### ISSUE THREAD

**Issue by gfepfl** [wandb/client#690]
`wandb version 0.8.16`

The jupyter wandb magic does not work until `wandb.init()` was at least called once.
I have the following setup:

```
%%wandb
train_model()   # <-- calls wandb.init()
```

This gives the error:
```
UsageError: Cell magic `%%wandb` not found.
```

Loading the extension explicitly with `%load_ext wandb` did not help either.
Is there a way to load the magic without creating a new run?

**Comment by vanpelt** [comment]
Hey @gfepfl you can do it manually as so: 

```python
ipython = get_ipython()
ipython.register_magics(wandb.jupyter.WandBMagics)
```

I'll keep this open as we could do this on import of wandb.

**Comment by gfepfl** [comment]
Thanks, this loads indeed the magic, but now I get an error when I actually want to use it:

``` 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

wandb/jupyter.py in _repr_html_(self)
    145     def _repr_html_(self):
    146         state = "running"
--> 147         if self.run._jupyter_agent == None:
    148             state = "no_agent"
    149         elif self.run._jupyter_agent.paused:

AttributeError: 'NoneType' object has no attribute '_jupyter_agent'
```

**Comment by vanpelt** [comment]
Ahh that makes sense.  You can do the following to display inside of your train_model function after calling `wandb.init` and just don't use the magic.

```python
display(wandb.jupyter.Run())
```

**Comment by gfepfl** [comment]
Thanks! Works like a charm.

**Comment by JacobARose** [comment]
@vanpelt Your suggested solution actually demonstrates the issue I have with the docs for the jupyter extension. Neither your answer nor the docs ever mention what display() actually is, nor how to import it. Is it a wandb function? Or a jupyter function?

I'd like to try it that way since Im currently just getting a blank white rectangle instead of any wandb widgets when using 

`wandb.init()`
then
`%%wandb`

**Comment by vanpelt** [comment]
Hey @JacobARose, display is a jupyter function.  You can run `from IPython.display import display`.  You shouldn't need to use this method if you're calling `wandb.init` in a cell previous to a cell decorated with the `%%wandb` magic.  If you want to call `wandb.init` later in your notebook and just display live updating stats in an earlier cell, you can do the following:

```
from wandb.lib.ipython import display_html
def display_run(run):
    display_html('''<iframe src="{}" style="border:none;height:420px;width:100%"/>'''.format(run.url))
run = wandb.Api().create_run(project="test_project")
display_run(run)
```

Then later in your notebook you can have a cell that calls init and log passing in the id of the run we created:

```
wandb.init(id=run.id, project="test_project")
wandb.log({"metric": 1})
```

**Comment by JacobARose** [comment]
@vanpelt Thanks, that would explain it. My intuition said it was probably an ipython-specific function, but Ive rarely worked directly with that code so I didnt feel comfortable testing it out myself.

I believe I am doing everything you instructed but still getting this white rectangle error, is it possible I havent installed the right jupyter library? This is in jupyterlab on ubuntu.
![image](https://user-images.githubusercontent.com/31635761/96950513-7be3d980-14b8-11eb-94bb-a62437c5c5ec.png)
