### ISSUE TITLE
Sweep stop

### ISSUE THREAD

**Issue by sirtris** [wandb/client#698]
* Weights and Biases version: 0.8.17
* Python version: 3.7.1
* Operating System: Linux-5.2.9-arch1-1-ARCH-x86_64-with-debian-buster-sid

### Description

Sweep stops without interuption: 
```
2019-12-04 12:48:10,473 - wandb.wandb_agent - INFO - Running runs: ['oe72ewxg']
2019-12-04 12:48:10,657 - wandb.wandb_agent - INFO - Agent received command: stop
2019-12-04 12:48:10,657 - wandb.wandb_agent - INFO - Stop: oe72ewxg
```

### What I Did

When I run a sweep it runs for one to three sweeps and the stops with the message above.  
I did not stop the runs in the webapp.   
Sweeps are started with: 

```
sweep_id = wandb.sweep(sweep_config, entity="MY_ENTITY_NAME", project="MY_PROJECT_NAME")
wandb.agent(sweep_id, function=train)
```

In the train function I have a `sweep_config` dict.

**Comment by raubitsj** [comment]
Can you post your sweep or run url? if you want to keep that private, you can direct message me at: http://bit.ly/wandb-forum

**Comment by raubitsj** [comment]
It looks like the python sweep api is not working with early_terminate/hyperband,  for now the workarounds are one of the following:
- use the sweep command line (wandb sweep sweep.yaml, wandb agent SWEEP_ID)
- disable early_terminate from the sweep yaml for now

**Comment by raubitsj** [comment]
Early terminate was fixed with the python agent api.  Marking this closed.

**Comment by qshzh** [comment]
I encountered the same issue. However, I am using sweep command line. wandb version is 0.10.12
Any suggestions?

**Comment by amariucaitheodor** [comment]
Same issue with wandb 0.15.2
