### ISSUE TITLE
GitCommandError

### ISSUE THREAD

**Issue by sirtris** [wandb/client#699]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.17
* Python version: 3.7.1
* Operating System: Linux-5.2.9-arch

### Description

I was running a normal run with code I have run before

### What I Did
In `wandb.init(project="MY_PROJECT")` I get this error:  
```
GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git status --porcelain --untracked-files
  stderr: 'fatal: unable to read tree dd01dff437ea440dd0db6412f7223af30b7eb371
'
```

**Comment by vanpelt** [comment]
It looks like you have a corrupt git repository.  Try running `git gc` from the terminal in your git repo.  If you still have the error, you can disable our git tracking by setting the **WANDB_DISABLE_CODE** environment variable to "true" before calling `wandb.init`

**Comment by sirtris** [comment]
Thanks `git gc` seems to have solved the problem
