### ISSUE TITLE
Feature Request: Deleting runs via API

### ISSUE THREAD

**Issue by BenedictWilkinsAI** [wandb/client#702]
I am not sure where to post feature requests, I will move this request to the proper place if required. 

It would be useful for me to be able to delete a (non-local) run from within python. So far I have not found a way to do this (please let me know if there is one!). The typical use case is if my program encounters a run-time error, it may invalidate the run. In this case I want to remove the run completely and conveniently i.e. not have to go to the web interface and do it manually.

Thanks!

**Comment by cvphelps** [comment]
Hi Benedict! Thanks for the feature request, this is a great idea. I'll add it to our internal tracker.

**Comment by sash-a** [comment]
Any update on this? It would be quite a useful feature.

**Comment by dan-r95** [comment]
If anyone stumbles over this issue when searching for a way to bulk delete runs in the UI, this is  [possible](https://docs.wandb.com/app/features/sidebar#bulk-select-runs) :fire: 😄

**Comment by ariG23498** [comment]
With version of `0.10.18+`
we could do something like this
```python
import wandb
api = wandb.Api()
run = api.run("username/project/run_id")
run.delete()
```
to delete runs from the API.

**Comment by samiede** [comment]
I often get a "Bad Request" from this, and the runs are also not deleteable in the web interface, does anyone know what I could be doing wrong?

**Comment by armanhar** [comment]
@samiede can you tell me which wandb version are you using? Also are you getting an error when deleting a run in the UI?

**Comment by samiede** [comment]
I'm using version 0.12.1. 
Yeah, it also times out on those runs and I'm not able to delete them there!

**Comment by armanhar** [comment]
Hey @samiede, the issue should be resolved now. Can you check?

**Comment by samiede** [comment]
Hey @armanhar, I'm afraid I can't because I've resolved the issue by deleting the whole project the faulty runs where in 🙈
I did, however, notice the new deletion dialog and I was also able to delete some very old runs, but I'm not sure if those were the ones I was not able to delete. Sorry!

**Comment by brando90** [comment]
what about multiple runs, or by group?
