### ISSUE TITLE
Failed to launch process without WANDB_DISABLE_CODE=true

### ISSUE THREAD

**Issue by HansPinckaers** [wandb/client#708]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.18
* Python version: 3.7.1
* Operating System: Ubuntu docker

### Description

wandb.init() crashes with the following error: process did not respond.

Adding WANDB_DISABLE_CODE=True works, found during NeurIPS debugging session with @vanpelt. It seems to timeout on the git code and not recover.

So, something weird is going on with my GitHub repo. 

Is wandb trying to send diffs of new files? Because there are quite some, including some saved network checkpoints which are large.

**Comment by raubitsj** [comment]
Yes, by default it grabs a diff which is helpful to see what changed in your repository between training runs.

I think for this bug we should do one or more of the following:
- try and make code collection asynchronous -- maybe snapshot the git last commit synchronously and the rest can be done later (not at startup)
- put limits on the size of the diff? or amount of time?
- extend the timer and or show progress of the action that is happening

**Comment by ariG23498** [comment]
Hey @HansPinckaers 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
