### ISSUE TITLE
Initialising error

### ISSUE THREAD

**Issue by bluesky314** [wandb/client#734]
`wandb --version && python --version && uname`

* Weights and Biases version: Latest
* Python version: 3
* Operating System:Linux

### Description

Not initialising 

### What I Did

```
`wandb.init(project="matting-disEntangleRes34DIM") `gives me error :
```

Traceback (most recent call last):
  File "disentangleNetDIMBlock.py", line 51, in <module>
    wandb.init(project="matting-disEntangleRes34DIM")
  File "/opt/anaconda3/lib/python3.7/site-packages/wandb/__init__.py", line 1067, in init
    _init_headless(run)
  File "/opt/anaconda3/lib/python3.7/site-packages/wandb/__init__.py", line 306, in _init_headless
    stdout_redirector = io_wrap.FileRedirector(sys.stdout, stdout_slave)
  File "/opt/anaconda3/lib/python3.7/site-packages/wandb/io_wrap.py", line 331, in __init__
    self._from_fd = redir_file.fileno()
AttributeError: 'IOBuffer' object has no attribute 'fileno'
```
```
It is working on my other machine but not this one, I am thinking maybe some requirment is off?

**Comment by vanpelt** [comment]
Hey @bluesky314 thanks for reporting.  I created a branch that fixes this.  You can try it by running `pip install --upgrade git+git://github.com/wandb/client.git@master#egg=wandb`, we should get it out in the next release next week.

**Comment by bluesky314** [comment]
@vanpelt  Am still getting exact same error. Could there be some other cause of this?

**Comment by vanpelt** [comment]
@bluesky314 my appologies, I gave you the wrong git branch.  This branch fixes it:  `pip install --upgrade git+git://github.com/wandb/client.git@bug/bad_io#egg=wandb`

**Comment by bluesky314** [comment]
@vanpelt Ok that error has disappeared but now nothing is getting logged. When I go to the project link provided I see the page :"Not Found: We couldnt find what you were looking for".
The project does not appear on my project dashboard as well.

**Comment by vanpelt** [comment]
Can you share the links that are being logged?

**Comment by bluesky314** [comment]
Sure here is the one it gave me on the python terminal:
https://app.wandb.ai/bluesky314/XResNetDisentagleNet/runs/n3frcyzw

**Comment by bluesky314** [comment]
The page generated by the run: https://app.wandb.ai/bluesky314/XResNetDisentagleNet also has the same error

**Comment by bluesky314** [comment]
@vanpelt My bad it is working, I was logged out on my browser. Maybe there should be a page saying please log in or no acess to make the situation a bit more clear.

**Comment by vanpelt** [comment]
I see, yeah we display a 404 to avoid leaking the existence of private usernames / projects.  We should make the 404 page say if you own this project please login.
