### ISSUE TITLE
Is there a way to turn off Weights and Biases without code changes?

### ISSUE THREAD

**Issue by mathemakitten** [wandb/client#764]
* Weights and Biases version: 0.8.19
* Python version: 3.7
* Operating System: Linux

Is there a way to totally turn off W&B without having to build if-logic? I know I can do WANDB_MODE="dryrun" but I want to turn it completely off (i.e. ignore Wandb.init(), ignore wand.save, don't even write files).

**Comment by mathemakitten** [comment]
Also, is there a way to turn off W&B warnings?

**Comment by vanpelt** [comment]
Hey @mathemakitten currently you can't completely turn off wandb.init but it's a feature we should add.  You can turn off all messages from wandb by setting `WANDB_SILENT=true`

**Comment by jarednielsen** [comment]
Is there a timeline for adding this feature? I have a use case where wandb is cluttering up my filesystem even if WANDB_SILENT=true; I would like an environment variable that makes wandb act as a no-op.

**Comment by raubitsj** [comment]
@jarednielsen : This is a feature of a new experimental client library:
https://github.com/wandb/client-ng

We are working out the timeline for getting these changes into the released library.  But starting next week we will have a noop mode.

The trick to the noop mode is that all the wandb methods and objects have to behave sanely so that your code execution still works like:
run = wandb.init()
run.config.value = 3
print(run.config["value"])

When the experimental client has validated and documented how to use this feature we will comment here and mark this issue with the label "c:cling-flixed". when it is released in the main library this issue will be marked closed

**Comment by JDE65** [comment]
> Hey @mathemakitten currently you can't completely turn off wandb.init but it's a feature we should add. You can turn off all messages from wandb by setting `WANDB_SILENT=true`

I tried both directly and with os.environ... it doesn't work :-(
Is there no other way ?
THX

**Comment by vanpelt** [comment]
We just released wandb 0.10.7 which has support for the `WANDB_SILENT` environment variable.  You can set it in code before calling wandb.init with `os.environ['WANDB_SILENT']="true"`.

**Comment by JDE65** [comment]
Great, I'll immediately update it :-)

**Comment by JDE65** [comment]
I tried and I stll get all warnings and unuseful messages :-(

And I run the same code several times in a row, I also get trouble with the conflict between init and login

**Comment by vanpelt** [comment]
Can you share a few examples of message you're seeing?  `WANDB_SILENT` should disable any lines beginning with **wandb: **.  You need to set this env variable before any calls to wandb api's in your script.

**Comment by glenn-jocher** [comment]
I'm going to +1 this thread. **I think `wandb off` should do what it says**, and shut it off completely. My current workaround is `pip uninstall wandb` when I want to be sure it's not logging, since I'm confused by the variety of other options, none of which seem to simply turn it off easily.

I think this applicable to a variety of situations, i.e. debugging small issues that may cause you to run short trainings dozens of times in a day that you don't want logged anywhere.

**Comment by vanpelt** [comment]
Hey @glenn-jocher we're going to address this in the next release hopefully tomorrow.  We're deprecating `wandb on` and `wandb off`, there will now be 4 commands:

* `wandb online`, `WANDB_MODE=online` or `wandb.init(mode="online")` - runs in online mode, the default
* `wandb offline`, `WANDB_MODE=offline` or `wandb.init(mode="offline")` - runs in offline mode, writes all data to disk for later syncing to a server
* `wandb disabled`, `WANDB_MODE=disabled` or `wandb.init(mode="disabled")` - makes all calls to wandb api's noop's, while maintaining core functionality such as `wandb.config` and `wandb.summary` in case you have logic that reads from these dicts.
* `wandb enabled` - sets the mode to back online

**Comment by glenn-jocher** [comment]
@vanpelt ah that sounds like a good improvement, I think this will help a lot!

**Comment by drozzy** [comment]
Yes, this was rally a pita for me, i wrote my own if-else statements.
The `mode="disabled"` would be awesome!

**Comment by glenn-jocher** [comment]
Can confirm this is working better now. 

`wandb enabled` and `wandb disabled` seem to behave well and as expected with YOLOv5 :)

**Comment by vanpelt** [comment]
Awesome!  We just deployed this feature with `wandb==0.10.11`, anyone finding this can upgrade with `pip install wandb --upgrade`.  This version now supports the `wandb enabled` and `wandb disabled` CLI commands as well as passing `mode="disabled"` or `mode="enabled"` to `wandb.init`.  _(You can also just set the `WANDB_MODE` environment variable)_

**Comment by tom-andersson** [comment]
@vanpelt If running a sweep, does `mode` in `wandb.init()` do anything? In my case I have `mode='disabled'` by default (controlled by a command line input to my train script), and I'm wondering if that will affect my sweeps.

**Comment by raubitsj** [comment]
`disabled` mode is not compatible with sweeps as we need to know what configurations have run.   The wandb.init() call is what signals our hyperparameter algorithm that a parameter set was received by an agent.

**Comment by tom-andersson** [comment]
Thank you @raubitsj, I've since edited my `sweep.yaml` to pass in the `--wandb` command to my train script which triggers `mode='online'` in `wandb.init()`:

```
command:      
  - ${env}    
  - python3   
  - ${program}
  - "--wandb" 
  - ${args}   
```

I'm was previously getting no information sent to the web app when running sweeps, but now everything's running nicely!

**Comment by WilliamAshbee** [comment]
WANDB_MODE=offline
seems to make output go to stderr

**Comment by glenn-jocher** [comment]
`pip uninstall wandb` or `wandb disabled`
