### ISSUE TITLE
Recursive creation of link to run folder in itself

### ISSUE THREAD

**Issue by ogvalt** [wandb/client#768]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.20
* Python version: 3.7
* Operating System: Ubuntu Linux 19.10

### Description

I'm using catalyst integration of wandb. When program stores info on disk it creates inside itself link to itself like :
```
| run123/
|----run123/
|----other files
```

In the result it fails to exit application normally and sent 
```ERROR Error uploading...``` 

### What I Did

```
The only way to fix this is to remove link to folder, but why it is created at first place
```

**Comment by cvphelps** [comment]
@raubitsj could you take a look at this?

**Comment by ogvalt** [comment]
it seems, that with 0.8.21 wandb this issue fixed
