### ISSUE TITLE
LaunchError: W&B process failed to launch

### ISSUE THREAD

**Issue by stathius** [wandb/client#785]
I get the following error. It seems random. I sent a couple of jobs to a cluster and 3 of the 24 failed like this so it's not an isolated issue. Some others timed out (see: https://github.com/wandb/client/issues/660). Python 3.7,  CentOS Linux release 7.7.1908 
```
wandb: Tracking run with wandb version 0.8.21
wandb: Run data is saved locally in ../../experiments/wandb/wave_propagation/wandb/run-20200121_205449-icfw2hdx
wandb: Syncing run unet_batch_16_samples_5_in_10_out_1_horizon_20_normalizer_normal_lr_0.0001_dataset_original_patience_7_wd_0_time_24
wandb: ⭐️ View project at https://app.wandb.ai/stathius/wave_prop
wandb: 🚀 View run at https://app.wandb.ai/stathius/wave_prop/runs/icfw2hdx
wandb: Run `wandb off` to turn off syncing.
wandb: ERROR W&B process (PID 17606) did not respond
wandb: ERROR W&B process failed to launch, see: /rds/general/user/ef1015/home/experiments/wandb/wave_propagation/wandb/debug.log
Traceback (most recent call last):
  File "train_network.py", line 18, in <module>
    wandb.init(project=args.project, name=args.experiment_name, config=vars(args))
  File "/rds/general/user/ef1015/home/anaconda3/envs/cuda10/lib/python3.7/site-packages/wandb/__init__.py", line 1075, in init
    _init_headless(run)
  File "/rds/general/user/ef1015/home/anaconda3/envs/cuda10/lib/python3.7/site-packages/wandb/__init__.py", line 296, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: /rds/general/user/ef1015/home/experiments/wandb/wave_propagation/wandb/debug.log
```

[debug.log](https://github.com/wandb/client/files/4097085/debug.log)

**Comment by vanpelt** [comment]
Hey @stathius we would love to get to the bottom of this.  In the past we've seen this happen with large git repos, but your debug.log doesn't seem to indicate that's happening.  One thing to try would be to set the "WANDB_DISABLE_CODE" environment variable to "true".

Are you running multiple process on the same machine?  Is this running directly on the linux host or within Docker?  If we can get a simple script that hangs intermittently it will be easier to debug.  Can you try running the following script and see if it also fails to launch intermittently?

```python
import wandb
wandb.init(project="hang_test", config={"hang": True})
wandb.config.hang = False
wandb.log({"finished": 1})
```

**Comment by stathius** [comment]
Hi @vanpelt. More than glad to try this but it is hard even to know how to replicate the problem. I run the code on a cluster node directly (no docker). Not sure if multiple processes run on the same machine. It also depends on what you mean by machine, the cluster itself manages the virtual nodes so I don't have much visibility on that. 

Will give it a try to do what you told me and come back to you.

**Comment by vanpelt** [comment]
Thanks @stathius what I meant by machine was multiple processes in the same OS.  It could also have something to do with a shared drive if multiple machines are writing to the same underlying filesystem.  Thanks for being open to reproduce, I don't want to waste your time so we're trying to reproduce on our end too.  If it would help to do a screenshare I would be happy to pair.

**Comment by stathius** [comment]
Tried to run the code you sent me locally first and gives this error:
```wandb: ERROR Attempted to change value of key "hang" from True to False
wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "wandb_debug.py", line 4, in <module>
    wandb.config.hang = False
  File "/rds/general/user/ef1015/home/anaconda3/envs/cuda10/lib/python3.7/site-packages/wandb/wandb_config.py", line 206, in __setitem__
    key, val = self._sanitize(key, val)
  File "/rds/general/user/ef1015/home/anaconda3/envs/cuda10/lib/python3.7/site-packages/wandb/wandb_config.py", line 222, in _sanitize
    key, self._items[key], val))
wandb.wandb_config.ConfigError: Attempted to change value of key "hang" from True to False
If you really want to do this, pass allow_val_change=True to config.update()
```
Is this expected? should I try and send the script to the nodes?

**Comment by vanpelt** [comment]
Whoops, sorry about that.  You can change the config line to: `wandb.config.update({"hang": False}, allow_val_change=True)`

**Comment by stathius** [comment]
The script runs fine. I've sent 6 jobs with WANDB_DISABLE_CODE=True and another 6 with False and they all finished ok.

**Comment by vanpelt** [comment]
It's likely something specific to your integration.  Is the code that's failing something you could share with us so we could try to reproduce?

**Comment by stathius** [comment]
Hey, yes I could do you have an email? 
I was thinking that it might be due to the cluster but truth is that my code without wandb runs fine everytime on it.

**Comment by vanpelt** [comment]
Sure, my email is vanpelt@wandb.com.  If you're running from a git repo, if you could give me a tarball of the whole git repo as it would exist in your cluster that would help as well.

**Comment by stathius** [comment]
@vanpelt email sent

**Comment by ariG23498** [comment]
Hey @stathius 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
