### ISSUE TITLE
Logged video not showing on browser

### ISSUE THREAD

**Issue by seungjaeryanlee** [wandb/client#798]
* Weights and Biases version: 0.8.21
* Python version: 3.7.4
* Operating System: Linux

### Description

I was trying to log videos. I am not using `monitor_gym` because it did not work when I used two environments (train and eval envs). Instead, I am using `wandb.Video(filepath)` on videos generated by OpenAI Gym Monitor.

I only see the evaluation video and not the training video. Instead of the video, I get this text:

```
This run didn't log videos for key "train/video", step 8737, index 0. Docs →
```

It works when I call the `wandb.log` for the training video less times, so I'm wondering if that's the problem?

### What I Did

[Here is my code](https://github.com/seungjaeryanlee/r13y/blob/7cddd41/examples/cartpole/train.py). It was run with `python train.py -c cartpole.conf`

**Comment by kennazilis** [comment]
Hello! I just asked one of our engineers @nbardy to see if he can help!

**Comment by nbardy** [comment]
Hey, can you provide a link to the run where this failing
