### ISSUE TITLE
[tune/WandbLogger] Trial failure causes subsequent logs to not get synced

### ISSUE THREAD

**Issue by hartikainen** [wandb/client#803]
- Weights and Biases version: 0.8.22
- Python version: 3.7.5
- Operating System: Darwin

### Description
When a trial fails in a tune run, the `WandbLogger` stops syncing any of the subsequent data in that run. I would expect the logger to be able to correctly handle the non-failured trials. Note that tune correctly reports the rest of the results despite the failing trial.

Here's what I see from the wandb web ui:
![image](https://user-images.githubusercontent.com/2308543/73137556-663ca300-4051-11ea-8b33-a0ceb5d171b5.png)

Here's what I see from the data logged by the `UnifiedLogger` visualized with viskit:
![image](https://user-images.githubusercontent.com/2308543/73137568-88362580-4051-11ea-999f-0c54e53c3c5f.png)
Note that only the failed trial is missing from the plot.

The ability to recover from a failure like this is important since, for example, when running experiments on preemptible/spot instances, we can't avoid occasional failures (tune handles these failure cases without any issue).

### What I Did
```python
import random
import time

import tensorflow as tf
from ray import tune
from wandb.ray import WandbLogger


class ExperimentRunner(tune.Trainable):
    def _setup(self, variant):
        self.timestep = 0

    def _train(self):
        self.timestep += 1
        v = tf.tanh(float(self.timestep) / self.config.get("width", 1)).numpy()
        v *= self.config.get("height", 1)

        time.sleep(tf.random.uniform((), minval=0.1, maxval=2.0))

        if self.config['width'] == 10:
            raise ValueError("Intentional exception to see if wandb fails.")

        return {"episode_reward_mean": v}


def main():
    tune.run(
        ExperimentRunner,
        resources_per_trial={'cpu': 2},
        loggers=[tune.logger.UnifiedLogger, WandbLogger],
        num_samples=1,
        stop={"training_iteration": 10},
        config={
            "width": tune.grid_search([10, 20, 30]),
            "height": tune.sample_from(lambda spec: int(100 * random.random())),
            'monitor': True,
            'env_config': {"wandb": {"project": "my-project-name"}},
        },
        local_dir='/tmp/wandb-test',
        queue_trials=True,
        reuse_actors=True)


if __name__ == '__main__':
    main()
```

**Comment by sydholl** [comment]
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
