### ISSUE TITLE
plaintext git password saved in run summary

### ISSUE THREAD

**Issue by BenedictWilkinsAI** [wandb/client#817]
`wandb --version  0.8.22

### Description

In the run summary there is a field called "Git repository", when cloning a private repository with https the command has the following structure:

`git clone https://USERNAME:PASSWORD@github.com/REPO.git`

wandb will save this command including the PASSWORD in plain text, if the run is public... you see the issue.

**Comment by raubitsj** [comment]
Thanks for pointing this out, this is certainly not good.
I think it makes sense for us to to regex this situation and mask user and password.

Right now if you want to avoid this behavior you can set an environment variable to disable saving information about your git repo:
WANDB_DISABLE_CODE=True python train.py

**Comment by ariG23498** [comment]
Hey @BenedictWilkinsAI 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
