### ISSUE TITLE
Plot histograms instead of heatmaps for wandb.Histogram

### ISSUE THREAD

**Issue by prash-p** [wandb/client#821]
Would it be possible to implement histogram plots instead of bin heatmaps for histogram objects? It's much more intuitive to read these. It also seems a histogram is already plotted when you hover over the heatmap: 
![image](https://user-images.githubusercontent.com/5707552/73600824-c4163280-450a-11ea-840e-2d8f251322fa.png)

**Comment by kennazilis** [comment]
Hello! Thanks for writing in. That's a great feature request! I've added to our internal tracker.

**Comment by heitorrapela** [comment]
Any news about that feature? :)

**Comment by szeitlin** [comment]
+1 this would be more useful for me too.

**Comment by itssimon** [comment]
I'd love to see this too. And the ability to compare histograms across runs would be amazing.

**Comment by rebekah-west** [comment]
This would be very helpful!

**Comment by cvphelps** [comment]
Hi folks, we have a new beta feature for custom visualizations that will support these histograms, would you please message me at carey@wandb.com so I can help you try it out and get your feedback

**Comment by ariG23498** [comment]
Hey folks,
Would love to hear your feedback on the custom viz feature.
It would be helpful if one could also send in feedback related to this ticket. :smile:

**Comment by prash-p** [comment]
@ariG23498 I'm not sure how to do a histogram plot still.

In my code I am doing:
`wandb.log({"Dice": wandb.Histogram(np.asarray(dice))})`

But when adding a custom viz. on the website, I don't see a full histogram - just options for 10%, 25%, etc.

**Comment by vanpelt** [comment]
Hey @prash-p if you want to use our custom charts feature you can log custom histograms with:

```
data = [[s] for s in scores]
table = wandb.Table(data=np.asarray(dice), columns=["scores"])
wandb.log({'my_histogram': wandb.plot.histogram(table, "scores", title=None)})
```

**Comment by ariG23498** [comment]
Hey guys
I am closing this ticket due to the inactivity of the ticket and that we have a perfectly working scenario with custom charts for this.

**Comment by GeoffNN** [comment]
Hi!
Is there a tutorial / script anywhere to compare histograms across runs, rather than across steps? I have a few runs for which I used `wandb.log({'values': wandb.Histogram(values)}`, and I'd like to plot overlapping histograms across runs.

**Comment by ariG23498** [comment]
Hey @GeoffNN 
You can use our [custom chart](https://docs.wandb.ai/ref/app/features/custom-charts) tool and use a [Vega preset](https://vega.github.io/vega-lite/examples/area_density_stacked.html) to get an overlapping histogram.
