### ISSUE TITLE
Include 50% percentile in summary metrics

### ISSUE THREAD

**Issue by prash-p** [wandb/client#822]
For array/tensor summary metrics, 10, 25, 75, 90% percentiles and mean/variances are calculated, but the median should also be presented as this is an important descriptive measure of the data.

**Comment by cvphelps** [comment]
@prash-p calculated metrics are a great idea. When you say these percentiles are calculated, where are you seeing this?

**Comment by prash-p** [comment]
@cvphelps On a run page, I click overview, then go to 'Summary' on the right side of the screen, then I click 'Raw' which shows the descriptive metrics:
![image](https://user-images.githubusercontent.com/5707552/73682357-18d5bc80-4675-11ea-9fda-1dd98b7fe579.png)

**Comment by ariG23498** [comment]
Hey @prash-p 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by prash-p** [comment]
@ariG23498 This would still be a nice feature to have
