### ISSUE TITLE
Raise an error if wandb.init called twice.

### ISSUE THREAD

**Issue by shawnlewis** [wandb/client#84]

**Comment by free-soellingeraj** [comment]
I have a situation where wandb is being called twice.
<img width="732" alt="Screen Shot 2020-05-17 at 3 19 13 PM" src="https://user-images.githubusercontent.com/44525375/82148023-1416cc00-9852-11ea-8771-a437d656f2cd.png">
Wondering if this issue has been resolved.

**Comment by vanpelt** [comment]
@free-soellingeraj can you share you're whole notebook with us?  You can add `reinit=False` to your call to wandb.init to ensure it won't reinitialize if called multiple times in the same jupyter context.

**Comment by free-soellingeraj** [comment]
it's here
https://github.com/free-soellingeraj/course-v3/blob/soellingeraj/emotions/nbs/dl1/emotions-RAF_Face_Database_basic.ipynb

**Comment by vanpelt** [comment]
Ahh, I believe if you remove the `callback_fns=WandbCallback` to the cnn_learner it will only use the the callback passed to fit_one_cycle.  The original author @borisdayma may have more input here.

**Comment by borisdayma** [comment]
That is correct.

You either use the callback in the learner or in the training loop.

The main difference is whether you want separate runs per training loop (for example after you unfreeze your model) or if you want to keep the entire logging in one run.

**Comment by free-soellingeraj** [comment]
It’s funny you say that.  I just started separating my training runs this way.  Thanks!
