### ISSUE TITLE
No way to display torch.Tensor images without normalization.

### ISSUE THREAD

**Issue by timothybrooks** [wandb/client#843]
* Weights and Biases version: 0.8.25
* Python version: 3.7.6
* Operating System: Linux

### Description

I am trying to compare images 

### What I Did

```
wandb.log({name: wandb.Image(image), 'Epoch': epoch}, step=step)
```

When passing a torch.Tensor, this calls wandb/data_types.py, line 762, in `__init__`
```
data = vis_util.make_grid(data, normalize=True)
```

While normalization can be useful, it is preventing us from comparing images and features on an absolute scale, which is often important as well. Here are a few options for resolving this:
 - Have normalize be an argument to wandb.Image. This is probably ideal, since it would be nice to be able to sometimes normalize and sometimes not, regardless of the underlying image data type. Normalization can occur at the start of the method, and the call to `make_grid(...)` can set `normalize=False`.
 - If the dtype is uint8, assume it does not need normalization. Otherwise, assume it needs normalization. This is a pretty reasonable assumption, since if the data is already uint8, it is already in the format of an image. I've seen this used before (at least in internal libraries).
 - Don't normalize, and leave that up to the user to do beforehand. While this isn't ideal, I think it is still preferred over always forcing the tensors to be normalized.

Thanks!

**Comment by timothybrooks** [comment]
Sounds good!

**Comment by ariG23498** [comment]
Hey @timothybrooks 
I think you have the solution to the ticket.
We are closing this issue due to the inactivity of the thread. Please feel free to reopen it if need be.
