### ISSUE TITLE
[Feature request] Filter runs based on steps

### ISSUE THREAD

**Issue by ankitkv** [wandb/client#845]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.21
* Python version: 3.7.2
* Operating System: Linux

### Description

I am trying to filter my runs based on the number of steps (similar to the duration filter, but on steps instead of time), but this feature does not exist. It would be nice to be able to filter runs based on steps to see which runs have run long enough for certain metrics to be reliable or which runs haven't run long enough and need to be resumed.

**Comment by kennazilis** [comment]
Hi Ankit, 
Thank you for the feature request! We really appreciate the feedback. I have added it to our internal tracker.

**Comment by cvphelps** [comment]
Hi Ankit, you can filter runs based on steps in the table like so:
![image](https://user-images.githubusercontent.com/6355078/74091761-ffb37e00-4a6f-11ea-942a-7aa71d606ae0.png)

Is this what you were looking for?

**Comment by ankitkv** [comment]
Yes @cvphelps , that is what I was looking for. Thanks!
