### ISSUE TITLE
Point Clouds not Rendering

### ISSUE THREAD

**Issue by fwilliams** [wandb/client#863]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.27  
* Python version: 3.7.5
* Operating System: Linux 

### Description

I am calling `wandb.log({"key": wandb.Object3D(pts)})` where `pts` is a numpy array with shape `(8192, 3)` of 3D points. The call succeeds, however in the browser, I see a blank square:

![Screenshot_2020-02-12_19-51-16](https://user-images.githubusercontent.com/1343232/74391060-0c6a0600-4dd1-11ea-9284-91f4d3febe50.png)

I dumped the points that were supposed to be rendered to a file and rendered them on my laptop. They look like below (so it's not an issue with the data).
![Screenshot_2020-02-12_21-08-48](https://user-images.githubusercontent.com/1343232/74394992-1e9d7180-4ddc-11ea-95c0-1dcc18748ab8.png)

### What you did
Tried this out on both Chrome and Firefox on Ubuntu

**Comment by lukas** [comment]
Do you know if the points were saved locally?  Is it possible to post a public link to your run in here?

**Comment by fwilliams** [comment]
Unfortunately, I can't share the run publicly at the moment. It appears to be working now (I didn't change anything on my end!). I'm closing the issue.

**Comment by hillaric** [comment]
Do you solve this problem
