### ISSUE TITLE
Error: "There was a problem rendering this workspace"

### ISSUE THREAD

**Issue by intermx-rwalden** [wandb/client#864]
* Weights and Biases version: 0.8.27
* Python version: Python 3.5.3
* Operating System: Linux

### Description

I logged a plotly of a correlation matrix size 36x36 and it seems to have been logged fine. The issue is when I use the browser to pin the chart. Even if the dash is empty, I receive the title error.

### What I Did

```
cols = df.columns
layout = go.Layout(yaxis = {"tickmode": "linear"}, title='Kendall Tau Feature Correlation Matrix')
fig = go.Figure(data=
                go.Heatmap(z=correlations, # a numpy matrix size 36x36
                           x=cols, # list of column names 36x1
                           y=cols,
                           ), 
                layout=layout)

wandb.log({'Kendall Tau Feature Correlation Matrix': fig})
```

**Comment by shawnlewis** [comment]
Can you send us a link to the broken page?

**Comment by intermx-rwalden** [comment]
https://app.wandb.ai/intermx/visit-anomaly-detection/groups/28915-vfa-mae

**Comment by intermx-rwalden** [comment]
Sorry didn't mean to close the issue 
https://app.wandb.ai/intermx/visit-anomaly-detection/groups/28915-vfa-mae

**Comment by intermx-rwalden** [comment]
Sorry didn't mean to close the issue
https://app.wandb.ai/intermx/visit-anomaly-detection/groups/28915-vfa-mae

**Comment by ariG23498** [comment]
Hey @intermx-rwalden 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
