### ISSUE TITLE
Frontend bug when plotting 3D meshes with `step=`

### ISSUE THREAD

**Issue by fwilliams** [wandb/client#867]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.27
* Python version: 3.7.5
* Operating System: Linux

### Description

I am trying to plot 3D models using the code:
```
wandb.log({prefix + " Mesh %d" % i: wandb.Object3D(open(obj_path))}, step=step)
```

This worked fine until I added the `step=` argument (so I could see the evolution of the meshes over time). I've checked that the steps are monotonically increasing between calls with the same key and that the keys are what I expect them to be.

Whenever a new mesh is plotted for a given key, the web UI shows two meshes beside each other and the controls stop working (see screenshot). The problem goes away when refreshing the page. 

The screenshot below shows the problem after several new steps have been plotted:
![Screenshot_2020-02-18_13-49-36](https://user-images.githubusercontent.com/1343232/74768474-a52bd600-5256-11ea-86aa-555db22be788.png)

This screenshot shows the same view after refreshing the page (this is what I always expect to see):
![Screenshot_2020-02-18_13-59-34](https://user-images.githubusercontent.com/1343232/74768637-ec19cb80-5256-11ea-9612-3d9a852eb154.png)

**Comment by fwilliams** [comment]
Here's a public run: If you open it now and wait a bit for the plots to update you'll see the bug.

https://app.wandb.ai/fwilliams/voronoinet?workspace=user-fwilliams

**Comment by fwilliams** [comment]
Any updates on this issue? It makes it quite difficult to use 3D plotting with W&B.

**Comment by vanpelt** [comment]
Hey @fwilliams, my colleague @nbardy will take a look at this.

**Comment by fwilliams** [comment]
Thanks a lot @nbardy for looking into this! I really like W&B as a product and I hope to keep using it in the future :smile: 

Some comments if you're working on a new 3D renderer: 
1. It would be really nice to have some control on the shading both from the Python side (in `wandb.log`) and in the plot on the webpage
2. Right now the only way to upload a 3D model is to save a mesh file (.obj, .stl, etc...) and log it. I cannot delete the mesh file until it's been uploaded which leads to a lot of spammy obj files on my file system. I would really like to be able to do `wandb.log({'mymesh': Object3d(vertices, faces)})` where `vertices` is an Nx3 tensor/array of vertices (N vertices, one vertex per row) and `faces` is an Mx3 array of indices into the rows of `vertices` (M triangles, one triangle per row).
3. Overlays: It would be really nice to be able to overlay point clouds, meshes and lines (and possibly text) inside one 3D figure.

**Comment by fwilliams** [comment]
Also I'm still seeing the issue with multiple 3D plots. Has your fix been pushed to production yet?

**Comment by nbardy** [comment]
> Also I'm still seeing the issue with multiple 3D plots. Has your fix been pushed to production yet?

The fix will be deployed today. I'll let you know when it's live.

> would be really nice to have some control on the shading both from the Python side (in wandb.log) and in the plot on the webpage

Are you interested in writing your own custom shader code? e.g. GLSL. Or something more along the lines of options for controlling lighting position, intensity, type ettc?

> 3. Overlays: It would be really nice to be able to overlay point clouds, meshes and lines (and possibly text) inside one 3D figure.

Great request, I'll add this to the roadmap.

> 2. Right now the only way to upload a 3D model is to save a mesh file (.obj, .stl, etc...) and log it. I cannot delete the mesh file until it's been uploaded which leads to a lot of spammy obj files on my file system.

We also support passing `StringIO` objects to media files so you can build your obj file in memory.

I created a new example of that for you here showing how it works:
https://github.com/wandb/client/pull/902/files#diff-503fb3aee8655ce2af95bead1a038319R55

> I would really like to be able to do wandb.log({'mymesh': Object3d(vertices, faces)}) where vertices is an Nx3 tensor/array of vertices (N vertices, one vertex per row) and faces is an Mx3 array of indices into the rows of vertices (M triangles, one triangle per row).

Being able to go straight from tensors as vertices and faces to `obj` would great. If you build a helper function to convert tensors to obj. We'd be exciting to merge it into our open source client repo.

**Comment by nbardy** [comment]
@fwilliams The frontend fix is deployed

**Comment by fwilliams** [comment]
Hey @nbardy thanks for the fix and for answering my questions!

> > would be really nice to have some control on the shading both from the Python side (in wandb.log) and in the plot on the webpage
> 
> Are you interested in writing your own custom shader code? e.g. GLSL. Or something more along the lines of options for controlling lighting position, intensity, type ettc?
> 
I'm not particularly interested in writing my own shader code. I'd like to control lighting parameters, and maybe have some prebuild shading styles (using per-face vs. per-vertex normals when rendering a mesh). 

> > 1. Overlays: It would be really nice to be able to overlay point clouds, meshes and lines (and possibly text) inside one 3D figure.
> 
> Great request, I'll add this to the roadmap.
> 
One gripe I have right now with the current point cloud renderer is that I can't figure out if there's a way to control the point size or Glyph. 

By far my favorite 3D plotting library is [Mayavi](https://docs.enthought.com/mayavi/mayavi/auto/mlab_reference.html) which supports a wide variety of 3D visualizations (and it's blazing fast because it's built on top of VTK). In particular they have a bunch of prebuilt glyphs for rendering points and lines. They also support static as well as dynamic sizing (per point). This kind of functionality would be really useful for 3D deep learning applications and I'd love to be able to render plots like this directly in W&B.

> > 1. Right now the only way to upload a 3D model is to save a mesh file (.obj, .stl, etc...) and log it. I cannot delete the mesh file until it's been uploaded which leads to a lot of spammy obj files on my file system.
> 
> We also support passing `StringIO` objects to media files so you can build your obj file in memory.
> 
> I created a new example of that for you here showing how it works:
> https://github.com/wandb/client/pull/902/files#diff-503fb3aee8655ce2af95bead1a038319R55
> 
Thanks for that!

> > I would really like to be able to do wandb.log({'mymesh': Object3d(vertices, faces)}) where vertices is an Nx3 tensor/array of vertices (N vertices, one vertex per row) and faces is an Mx3 array of indices into the rows of vertices (M triangles, one triangle per row).
> 
> Being able to go straight from tensors as vertices and faces to `obj` would great. If you build a helper function to convert tensors to obj. We'd be exciting to merge it into our open source client repo.

It would be nice to not have to go from V, F arrays to OBJ (which is string based) but instead just upload the arrays directly in a binary format. 

A nice option would be to have the client save a binary PLY file directly from the V, F into a file (similarly to how point clouds are written out as JSON files). There are a bunch of Python libraries (e.g. [https://github.com/fwilliams/point-cloud-utils](Point Cloud Utils)) which can write a binary PLY file from a V, F array I can you to if you're interested.

**Comment by fwilliams** [comment]
Also camera options in the 3D viewer (e.g. Near/Far planes, FOV, Orthographic) would be nice!

**Comment by fwilliams** [comment]
Here's a [gist](https://gist.github.com/fwilliams/b448583fdeb7ba6b61e79bf2b16ce774) with a function to generate an OBJ string from V, F, N arrays or lists. Feel free to integrate it into the wandb client.

**Comment by ariG23498** [comment]
Hey @fwilliams 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
