### ISSUE TITLE
Support for logging Altair plots

### ISSUE THREAD

**Issue by itssimon** [wandb/client#881]
Is there any chance that Altair plots will be supported for logging with wandb?

**Comment by vanpelt** [comment]
Hey @itssimon we do support rendering Vega, but haven't added formal support Altair.  Can you tell us a little more about what you're wanting to log specifically and give us an example usecase?

**Comment by itssimon** [comment]
I would like to add some charts to wandb showing things like model calibration. I have an existing library that produces these sorts of charts for a fitted model in Altair. Being able to simply write them to the wandb summary would be fantastic.

If rendering Vega is already supported it sounds like adding Altair support should be fairly straightforward. Given Altair's rise in popularity this would probably be of interest to many users.

**Comment by cvphelps** [comment]
@shawnlewis could you comment? It looks like Altair is built on top of Vega: https://altair-viz.github.io/

**Comment by shawnlewis** [comment]
Hi, we are refining our Vega feature now. You're right, supporting Altair plots should be straightforward. I'll post an update later this week about the Vega feature.

**Comment by itssimon** [comment]
@shawnlewis any update on this?

**Comment by itssimon** [comment]
While the official Altair support is still in development, are you guys able to guide me on how to use the existing Vega feature? I can't find anything in the docs.

**Comment by cvphelps** [comment]
Just got flagged on this one! Here's the documentation on Custom Charts: https://docs.wandb.ai/app/features/custom-charts

Here's a live example in a [hosted notebook →](https://colab.research.google.com/drive/1uXLKDmsYg7QMRVFyjUAlg-eZH2MW8yWH?usp=sharing)

**Comment by drozzy** [comment]
Altair is definitely more readable than vega json spec :-)

```python
import altair as alt

# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
```
