### ISSUE TITLE
Issue with running TF 2.1.0 with `validation_data` tuple present

### ISSUE THREAD

**Issue by bshikin** [wandb/client#887]
* Weights and Biases version: wandb, version 0.8.28
* Python version: Python 3.7.2
* Operating System: Darwin

### Description

I am not able to train TF models when passing `validation_data` on TF 2.1.0.

### What I Did

```
import tensorflow_core as tf
from wandb.keras import WandbCallback
import wandb

wandb.init(
    project="test",
)

model = tf.keras.models.Sequential()
...
 model.fit(
                x=train_features,
                y=train_values,
                validation_data=(test_features, test_values),
                epochs=5,
                callbacks=[WandbCallback()],
                verbose=2
)
```

Results in:
```
  File "[redacted project file]", line 57, in run_training
    self.sequential = self._train_network(train_features, test_features, train_values, test_values)
  File "[redacted project file]", line 128, in _train_network
    verbose=2
  File "[redacted project loc]/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "[redacted project loc]/venv/lib/python3.7/site-packages/wandb/keras/__init__.py", line 111, in new_v2
    set_wandb_attrs(cbk, val_data)
  File "[redacted project loc]/venv/lib/python3.7/site-packages/wandb/keras/__init__.py", line 79, in set_wandb_attrs
    elif isinstance(val_data, tuple) and isinstance(val_data[0], tf.Tensor):
AttributeError: module 'tensorflow' has no attribute 'Tensor'
```

**Note 1:** I am using `tensorflow==2.1.0`. 

**Note 2:** The issue does not occur if I remove `validation_data`

**Comment by cvphelps** [comment]
Thanks for reporting this! @raubitsj could you please take a look.

**Comment by arunraja-hub** [comment]
I used model.fit as well. I am not getting the attribute error mentioned above. However, when I run the training with model.fit, the training metrics are logged at all. The training process is taken care by Tf+Keras without any issues but no live-logging/logging is available under the Chart tab in the WandB page. Please advise

**Comment by vanpelt** [comment]
If you use the `WandbCallback` in your `fit` function you can pass `validation_data` directly to the `WandbCallback` as a keyword argument.  In older version of keras we picked this up for you automatically.  We'll look into the root cause and do this automatically for you, but until then just pass the same validation_data to the WandbCallback.

**Comment by ariG23498** [comment]
Closing this as @vanpelt has already mentioned a workaround for the ticket.
