### ISSUE TITLE
Expanding groups in the table breaks after deleting runs

### ISSUE THREAD

**Issue by rahulvigneswaran** [wandb/client#896]
**How to replicate :**
- Have multiple runs under various filters.
- Open Table view.
- Expand a specific run's branch of the tree fully.
- Delete that run.

**Issue :** If you try to expand some other branch now, it does expand and also doesn't show any other runs.

**Temporary fix:** Refresh the Webpage.

**Comment by cvphelps** [comment]
Hi Rahul, thanks for letting me know about this table issue. @tsholmes could you please take a look.

**Comment by tsholmes** [comment]
@rahulvigneswaran this should be fixed now

**Comment by rahulvigneswaran** [comment]
@tsholmes Thank you :)
