### ISSUE TITLE
Captions are not showing up for videos in UI?

### ISSUE THREAD

**Issue by alsuhr-c** [wandb/client#899]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb, version 0.8.28
* Python version: Python 3.7.6
* Operating System: Linux

### Description

I'm trying to put captions on videos in the Weights and Biases UI. When creating a video, I create it like: `wandb.Video(data, caption="caption here")`. But the captions aren't showing up in the UI under the videos.

### What I Did

Called `wandb.Video(data, caption="caption here")`

But getting videos like this (still image; the video itself is working):
![Screen Shot 2020-03-05 at 3 55 42 PM](https://user-images.githubusercontent.com/20176003/76024838-ca2c7400-5ef9-11ea-8fbe-3d30bc61795f.png)

These four videos are assigned different captions.

The captions work when I create an image instead of a video.

Thanks!

**Comment by vanpelt** [comment]
Hey @alsuhr-c can you send me a link to a run where this is happening for you.  We can dig into the root cause.

**Comment by alsuhr-c** [comment]
Sure, this is a link to a run where it is happening: https://app.wandb.ai/lil/cereal_bar/runs/w6nx08ya?workspace=user-alsuhr 

Under custom visualizations, the tab "predictions/plans" should have captions under the five videos. 

Thanks!

**Comment by vanpelt** [comment]
Great!  We're working on a fix now.  We'll keep you posted.

**Comment by nbardy** [comment]
Hey @alsuhr-c. Sorry for the late follow up.

I pushed a patch out for this a few days, ago. Enjoy!

**Comment by alsuhr-c** [comment]
Looks great!! Thank you!
