### ISSUE TITLE
wandb config with nested dictionaries

### ISSUE THREAD

**Issue by andrijazz** [wandb/client#901]
* Weights and Biases version: 0.8.28
* Python version: 3.6.9
* Operating System: Linux

### Description

I'm not sure if this is a bug ... 

I would expect that when passing config with nested dictionaries all nested dictionaries should be flattened recursively.

### What I Did
```
x = {'a': {'b': 'c'}}
wandb.init(project="xyz", config=x)

print(wandb.config.a.b)

Outputs:
AttributeError: 'dict' object has no attribute 'b'
```

**Comment by vanpelt** [comment]
Yeah, this is currently as designed and is a bit unfortunate.  Any nested dictionaries must be accessed with the `["key"]` syntax instead of the attribute syntax.  We'll keep this open as we should be able to allow the attribute syntax for nested keys.

**Comment by ariG23498** [comment]
Hey @andrijazz 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
