### ISSUE TITLE
Sweeps with slurm: config-default.yaml will be overwritten if task is inside waiting list

### ISSUE THREAD

**Issue by Yumin-Sun-00** [wandb/client#906]
### Description

I work with `slurm` that will recieve my training task and execute it. But, since my collegues are using the slurm at the same time, each person will have a maximal submits. This means, some tasks are submitted, but go into waiting list, until resources are released.

I am using the config-default.yaml to register all my hyperparams, but once the task goes to waiting list, if I overwrite the .yaml file as the same time, then when the task is finally executed, the yaml loaded will be the latest version of that file. I know this is not a bug inside wandb, but is that possible, that your team can find a solution for this?

**Comment by cvphelps** [comment]
Hi Yumin, thanks for reporting this. @raubitsj could you please take a look.

**Comment by ariG23498** [comment]
Hey @Yumin-Sun-00 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
