### ISSUE TITLE
log files miss part of content

### ISSUE THREAD

**Issue by Yumin-Sun-00** [wandb/client#908]
`wandb --0.8.29 && python --3.6.9 `

* Operating System: Ubuntu

### Description
The log on wandb missed some part of print.

### What I Did
I run task on slurm and found that the log on wandb does not always as same as my local log files or error files. There are some part missing on wandb.

## local log files start with this messages:
```
valid_loader batch size: 4
Using UpsampleConvLayer (slow, but no checkerboard artefacts)
data_loader length 330, validation data loader length1388
[preview indices]: [16, 49, 82, 115, 148, 181, 214, 247, 280, 313]
[val preview indices]: [69, 207, 346, 485, 624, 763, 901, 1040, 1179, 1318]
[getitem] idx  0
first element...
seg filename /.../segmentation_00000002.png
img filename img_00000002.png
next element  1
seg filename /...segmentation_00000003.png
img filename img_00000003.png
next element  2
img filename img_00000004.png
next element  3
seg filename /.../segmentation_00000005.png
img filename img_00000005.png
next element  4
img filename img_00000006.png
[getitem] idx  1
first element...
```

## wandb log messages start with:
```
first element...
seg filename /.../segmentation_00000012.png
img filename img_00000012.png
next element  1
seg filename /.../segmentation_00000013.png
img filename img_00000013.png
next element  2
img filename img_00000014.png
next element  3
seg filename /.../segmentation_00000015.png
img filename img_00000015.png
next element  4
img filename img_00000016.png
[getitem] idx  7
```

**Comment by cvphelps** [comment]
Hi Yumin, are you printing out a lot of lines at once? We have a rate limit on the number of lines we send.  @vanpelt could you remind me what the rate limit for log lines is?

**Comment by Yumin-Sun-00** [comment]
> Hi Yumin, are you printing out a lot of lines at once? We have a rate limit on the number of lines we send. @vanpelt could you remind me what the rate limit for log lines is?

Thank you, I see.

**Comment by vanpelt** [comment]
We should push all logs eventually (30-60seconds).  If the logs are truly missing, that indicates the program crashed in a way we couldn't recover from.  Are you able to reproduce this behaviour?

**Comment by Yumin-Sun-00** [comment]
> We should push all logs eventually (30-60seconds). If the logs are truly missing, that indicates the program crashed in a way we couldn't recover from. Are you able to reproduce this behaviour?

No, the program didn't crash, it just misses some lines. I was shocked first as the print is not what I desired, so I thought I probably have a bug, but then I open the local slurm log files, I see the print content is different to online. It is okay for me, not a big deal. I just want to share some noise to you :)

**Comment by ariG23498** [comment]
Hey @Yumin-Sun-00 
We're closing issues older than 6 months. Please comment to reopen.
