### ISSUE TITLE
Expanding groups in Table resets the scroll bar

### ISSUE THREAD

**Issue by rahulvigneswaran** [wandb/client#911]
Whenever I expand something in the Table the scroll bar goes to the top. It gets quite annoying when there are too many groups and runs. Kindly take a look at it.

**Comment by cvphelps** [comment]
Hi Rahul thanks for letting me know about this!

**Comment by cvphelps** [comment]
@rahulvigneswaran could you share a few more details— is this on a report page or a project page? What browser and operating system are you using?

**Comment by rahulvigneswaran** [comment]
@cvphelps I am using Windows 10 with Google Chrome. This happens in the project page -> Table -> Tree View of the Runs.

**Comment by ariG23498** [comment]
Hey @rahulvigneswaran 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
