### ISSUE TITLE
wandb clock has 1 hour difference

### ISSUE THREAD

**Issue by Yumin-Sun-00** [wandb/client#920]
### Description

As I understood, each run will be save inside wandb/ folder with name run-DATE-CLOCK-identifier/.

But I found that the clock is always 1 hours beyond my clock. Since my models are saved with the similar naming manner, it makes hard for me to identify my model folder-wandb folder pairs.

I think you forget the clock in europe is a bit different, here we change the clock in summer and winter.

**Comment by cvphelps** [comment]
Hi @Yumin-Sun-00, thanks for your message!

Local wandb folders are meant to be temporary. The goal is to have everything sync'd to our web interface so you can use the web app or the API to get any files. The folders that are saved locally are just there in case we lose internet connection so your run data will still be saved, but you can delete the temporary folders after the run finishes syncing to the cloud.

@vanpelt I think I remember that you have a helpful command to let people clean up local folders. Could you remind me what you'd suggest users do in this scenario?

**Comment by vanpelt** [comment]
@Yumin-Sun-00 the local paths are named with UTC time and only there to provide a reasonable sort order when listing them.  There is a command `wandb gc` to remove old run caches.

**Comment by ariG23498** [comment]
Hey @Yumin-Sun-00 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
