### ISSUE TITLE
Logging Unicode

### ISSUE THREAD

**Issue by msalvaris** [wandb/client#940]
* Weights and Biases version: 0.8.30
* Python version: 3.6.8
* Operating System: Linux

### Description
My training scripts logs unicode characters to my log, different emojis.
When using weights and biases I get the following error:
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/files/irobot/project/16sno1k6/file_stream

After removing the unicode characters from my logging everything worked fine.

Just wanted to check whether unicode characters are supported in wandb

**Comment by lukas** [comment]
No we want to support this, we will look into it.

**Comment by lukas** [comment]
This is fixed now - thanks for raising it.  Please reopen if the issue is still there for you.
