### ISSUE TITLE
TPU utilization with support for torch-xla

### ISSUE THREAD

**Issue by harpone** [wandb/client#942]
Would be nice to be able to see TPU utilization on W&B.

I'm now using Google's `capture_tpu_profile` by ssh:ing to the main VM and running it there.

The output seems to be just byte strings to stdout, so it should be fairly simple to catch that.

**Comment by raubitsj** [comment]
This is a great feature to add, I have flagged it to be included with an experimental wandb client, I will update when it is included

**Comment by vanpelt** [comment]
This is coming in the next release 0.10.13 early next week.
