### ISSUE TITLE
Filtering results using `summary.*` returns a HTTP.Error

### ISSUE THREAD

**Issue by sff1019** [wandb/client#945]
* Weights and Biases version: 0.8.29
* Python version: 3.7.3
* Operating System: Linux

### Description

I have been enjoying using Weight and Biases, and started using it daily!

However, I have bumped into some problems. After training a series of deep learning models, I am now trying to get one of the best results via python. Through this API (https://docs.wandb.com/library/reference/wandb_api#api%60.), I figured I could use MongoDB to get one of the top results like this: 
```
api = wandb.Api()
for batch_size in batch_size_list:
  runs = api.runs(
    path="my_entity/my_project",
    {'summary.train_loss': {'$lt': 0.01}, '$sort': {'summary.train_loss': 1}}
  )
...
```

However, I get this error message. 
```
Traceback (most recent call last):
...
File "~/lib/python3.7/site-packages/wandb/apis/public.py", line 404, in __getitem__
  loaded = self._load_page()
File "~/lib/python3.7/site-packages/wandb/apis/public.py", line 397, in _load_page
  self.QUERY, variable_values=self.variables)
File "~/lib/python3.7/site-packages/wandb/retry.py", line 130, in wrapped_fn
  return retrier(*args, **kargs)
File "~/lib/python3.7/site-packages/wandb/retry.py", line 95, in __call__
  result = self._call_fn(*args, **kwargs)
File "~/lib/python3.7/site-packages/wandb/apis/public.py", line 91, in execute
  return self._client.execute(*args, **kwargs)
File "~/lib/python3.7/site-packages/gql/client.py", line 52, in execute
  result = self._get_result(document, *args, **kwargs)
File "~/lib/python3.7/site-packages/gql/client.py", line 60, in _get_result
  return self.transport.execute(document, *args, **kwargs)
File "~/lib/python3.7/site-packages/gql/transport/requests.py", line 39, in execute
  request.raise_for_status()
File "~/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
  raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphq
```

I was expecting a list of runs with a train_loss that is less than 0.01 and is sorted in ascending order by train_loss. I was able to get a list of runs if I filtered it using `config.*`. 

Is this an expected output? If so, it would be generous to change the error message to something more informational than `requests.exception.HTTPError`.

Thank you in advance, and hope if somebody can help me out!

**Comment by sff1019** [comment]
I might have figured this out. 
Instead of specifying the summary elements as `summary.*`, we might have to use `summary_metrics.*`. This to worked out for me.
However, this is different from the API document, so it would make sense to fix it.

**Comment by cvphelps** [comment]
Hi @sff1019, thanks for reporting this! @vanpelt could you take a look.

**Comment by ariG23498** [comment]
Hey @sff1019 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
