### ISSUE TITLE
Weights and Bias is super slow with Chrome and sometimes crushes the browser

### ISSUE THREAD

**Issue by kojimano** [wandb/client#946]
* Weights and Biases version: 0.8.28
* Python version: 3.7 (Anaconda Distribution)
* Operating System: Linux
* Running Browser: Chrome (version: 80.0.3987.149), Safari (version: 12.0.2 (14606.3.4)) 

### Description
Hi it comes to my attention that Weights and Bias crushes or is extremely slow when I try to open a experiments table UI with Chrome (the version specified above) but open in a reasonable time with Safari.    

Are there any known incompatibility to Chrome or its plug-ins?

Let me know if you need more information from me to reproduce this issue.

Thank you very much in advance.

**Comment by alsuhr-c** [comment]
I'm in the same boat as @kojimano , the UI seems to be responding slowly in the last few days, with varying speeds in Chrome, Safari, and Firefox. My chrome version is the same, the Firefox is 72.0.2 (64-bit) (Firefox was not too slow last night, but this morning very slow). I mostly use the "graph view" summarizing  multiple experiments, and the UI is responding slowly to, e.g., hovering over areas of the graphs. I haven't seen Chrome crashing yet.

**Comment by shawnlewis** [comment]
For people experiencing this, can you please try the "disable hardware acceleration" in the Chrome settings?

**Comment by kojimano** [comment]
Works great to me! Thanks!

**Comment by alsuhr-c** [comment]
It was working well for me after disabling hardware acceleration, but I came back to my computer after 1 hour and now my workspace is not loading at all in any browsers. After a few minutes of the dashboard loading (spinning circle) I get a "context deadline exceeded -- an application error occurred" box.

**Comment by ashok-arjun** [comment]
This issue still persists for me - open >1 W&B workspace tabs in chrome crashes the entire window.

I have a fairly strong multi-core CPU processor.

**Comment by omgwenxx** [comment]
I came across this issue, the website also gets stuck for me once I try to display the next page in my table.
![image](https://github.com/wandb/wandb/assets/26310939/42a6d7f2-fa7b-4b3e-b8b6-9d99ed657376)

I'm using Google Chrome Version 126.0.6478.127 (64-bit)

Problem: I click on the next page icon and it doesn't load the next page (page 3 in this case).
