### ISSUE TITLE
After nan in BO objective all agents fail with: "TypeError: '>' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#947]
wandb, version 0.8.31
Python 3.8.2
Linux

### Description

When using `method: bayes` after some time all my agents stop with a repeated error message of `wandb: ERROR  (<Response [500]>)
wandb: ERROR Error while calling W&B API: anaconda 400 error: {"code":400,"message":"TypeError: '>' not supported between instances of 'float' and 'str'"
}`.

After further investigation I am fairly confident that this has to do with one of the runs having a `nan` as the `metric: name: valid_loss` value. Why do I believe this?

* I was watching a run, and as soon as the reported metric for valid_loss which is my metric has a `nan` as a final result in one of my runs, then all consecutive agents fail.
* A random sweep with the exact same code and wand config (except random instead of bayes) does not have these issues, despite some runs having `nan` as the result.
* When I change my code to log as a final value a large number instead of `nan` I don't observe this issue.

**Comment by adrnswanberg** [comment]
This should be fixed as of 2 days ago. Please re-open if you see this error agian.
