### ISSUE TITLE
wandb init ignoring project parameter

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#949]
wandb, version 0.8.31
Python 3.8.2
Linux

### Description

When I initialize a project with `wandb.init(project=wandb_project)` I expect the project to be `wandb_project`. 
Instead it is `path-to-script`. 
This changed in one of the recent versions. Now the only way for me to have the correct project is to run wandb init in all directories in which I have scripts, which is unfeasible. 
The project parameter in init should have priority over all other configuration options.

**Comment by cvphelps** [comment]
Hi there, thanks for your message. I'm trying to reproduce your issue, and wandb.init(project="project-name") is working for me.

Here's the project page: https://app.wandb.ai/carey/dream-flasher-test?workspace=user-carey
Here's the google colab: https://colab.research.google.com/drive/1LceLkfVjZDPUNbxcBJuSRe1ANIodUAdZ

Do you think you could help me reproduce your issue?

**Comment by raubitsj** [comment]
There are a few reasons why this might be happening:
1) you are running a sweep (we ignore wandb.init() specified project because it needs to be in the same project as the sweep, use the sweep command line or yaml to specify your project)
2) you set an environment variable WANDB_PROJECT
3) you configured your work directory with a project using `wandb init` command line (if you didnt want this, you can remove that configuration by removing wandb/settings file)

**Comment by dreamflasher** [comment]
@raubitsj Thank you!

This behaviour seems to be new. I am indeed running a sweep (1), and this used to work. I tried to look up in your documentation on how to configure the project in the yaml, but there is no info on that: https://docs.wandb.com/sweeps/configuration

Would you be so kind as to update the documentation/explain here how to do this?

**Comment by raubitsj** [comment]
I added documentation for setting entity and project at:
https://docs.wandb.com/sweeps/configuration
and 
https://docs.wandb.com/sweeps/python-api

Reopen if this is still not working for you.

**Comment by dreamflasher** [comment]
@raubitsj Thank you for adding the documentation. Unfortunately, I can't reopen the ticket.

It would be great if it were possible to specify the project just via python code and not needing to have it fixed in the sweep config – this used to work before.

In your comment it's the first time I hear about `entity` – what is this? The documentation is lacking an explanation, `entity` is such a general term that it can be really anything.

**Comment by vijetadeshpande** [comment]
I am facing this issue and it happened pretty suddenly. Just an hour ago I was able to log everything at `project="desired_name"` but now everything is getting logged at `project="file_name"`.

I am using wandb in following order,

import wandb
wandb.init(
    project="desired_name",
    tags=["t1", "t2", ..],
)
wandb.log(...)
wandb.finish()

And I am not doing a sweep.

**Comment by vijetadeshpande** [comment]
My issue is resolved, it was a mistake on my end. I had two initializations (`wandb.init(..)`) in my script and the first one was logging the results to `project="file_name"`. I removed the first initialization and the issue was resolved.

**Comment by aounleonardo** [comment]
Same issue for me and my teammate:
`{"run.id='w0ffezvg', run.name='dummy-w0ffezvg', run.group='', run.project='dummy'"}`

And it's not consistent, sometimes we run it and it works 🤷 
I can share more details if this is the right thread, but I thought I'd share this quickly in case it's a known issue
