### ISSUE TITLE
[Help] I can't finish any runs if my program is stiil running (even for none-wandb-related things).

### ISSUE THREAD

**Issue by richardyy1188** [wandb/client#951]
* Weights and Biases version: 0.8.31
* Python version:  3.6.9
* Operating System: Linux

### Description

When I run many runs sequentially, I can see on the website that state of past runs keeps showing `running`, runtime keeps increasing too, and only when my program is stopped runs will show `finished`.

- Is that mean I am running many many runs simultaneously during the running of my program ?
  
- I want to shut down the run when I finish it.
- I want to see the true runtime of runs. 

### What I Did

```
import time
for _ in range(100):
  wandb.init(entity=<my username>, project='test', config={'param':233})
  wandb.log({'metric':332})
  wandb.join()
  time.sleep(10)
```

**Comment by raubitsj** [comment]
This should work if you add `reinit=True` to your wandb.init() call

**Comment by raubitsj** [comment]
Or alternatively you can do:
```
import time
for _ in range(100):
  run = wandb.init(entity=<my username>, project='test', config={'param':233}, reinit=True)
  with run:
     run.log({'metric':332})
  time.sleep(10)
```
