### ISSUE TITLE
Make views sharable by passing GET url parameters

### ISSUE THREAD

**Issue by dreamflasher** [wandb/client#954]
### Description

I'd like to be able to share views (eg. a table of runs) with colleagues. These tables are configured by filters, group and sorting. It would be great if you pass filters, gouping and sorting as url get parameters, so that one can easily share such a URL and others will have that same view.

**Comment by cvphelps** [comment]
Hi Marcel, this is a great idea for a feature request. For the moment, you can click "Export to report" in the lower right corner of the page and then save the state of your tables, grouping, sorting, filters, etc. in that report so collaborators can see the snapshot of your workspace.

**Comment by ariG23498** [comment]
Hey @dreamflasher 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by dreamflasher** [comment]
Please reopen

**Comment by vanpelt** [comment]
@dreamflasher you can do this today by clicking "Create Report" in a workspace and choosing the section or tables you want to share.  Then the report itself can be shared with a private sharing link.  Can you describe what makes this not work for your usecase?

**Comment by dreamflasher** [comment]
https://blog.benwinding.com/github-stale-bots/ and https://www.reddit.com/r/programming/comments/kzvryq/github_stale_bots_a_false_economy/

@vanpelt "create report" is a lot of effort if I only want to share simply the view that I am currently seeing. 
Overall the UX of creating a decent view or a report is lacking a lot behind – it always starts with a huge number of columns because by default a lot of stuff is reported, and picking the interesting columns is very slow (the drag and drop is pain in the ass, as well as clicken the column and hiding it is super slow).

**Comment by ariG23498** [comment]
Hey @dreamflasher
We have updated the "reports" editor. You can indeed share the panels as shown here 👇 
![image](https://user-images.githubusercontent.com/36856589/108723583-6f48be00-754a-11eb-8271-435fcc2bb854.png)

Here you will be sharing the panels in the form of a report that is time-stamped for you. Would this suffice the feature that you are looking for?

**Comment by fellhorn** [comment]
We face a similar issue when trying to have links from our workflow orchestration tool to wandb. We would like to group/tag all runs of a single workflow and have a direct link to this group/tag. As far as we see there is currently no way to achieve this with wandb, right?

**Comment by oshapio** [comment]
Can this please be reopened? Making a new report is tedious and doesn't allow (as far as I know) to maintain the same layout and view as the default view of UI provides. It's not as flexible.

We run experiments that consist of many different models and we have an interest in their performance relative to each other and to each group itself. Often new experiments take place and this makes old reports obsolete. Sometimes bugs are found and old experiments need to be removed and replaced. We have do filtering by procedure names and keep a list of names within each experiment, and these change.  

If the filters were (say optionally) reflected in the URL, this would allow sharing specific configurations of experiments without the need to spawn redundant/temporary reports. Reports would still have their place for a more permanent results showcase, but for temporary work being able to quickly filter out runs would be ideal. 

@vanpelt
