### ISSUE TITLE
Allow `wandb pull` with the experiment name instead of only with run_id

### ISSUE THREAD

**Issue by bkkaggle** [wandb/client#959]
### Description

Hi,

Right now, if you want to download saved files with the cli you have to do something like 
```
wandb pull -e username -p projectname run_id
```
It would be nice to be able to use the shortcut name (e.g. vibrant-eon-807) so you don't have to look up the run_id which is only visible in the URL (https://app.wandb.ai/[username]/[project_name]/runs/[run_id]/overview). 

Something like this would be a lot more user-friendly:
```
wandb pull -e username -p projectname vibrant-eon-807
```

Thanks

**Comment by tyomhak** [comment]
Thank you for your feedback and feature request. I have added it to our tickets for discussion for the future updates.

**Comment by vanpelt** [comment]
Currently you can use `wandb pull -e username projectname/vibrant-eon-807` or `WANDB_ENTITY=username wandb pull projectname/vibrant-eon-807`.  We'll keep this open to provide full path support

**Comment by ariG23498** [comment]
Hey @bkkaggle 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
