### ISSUE TITLE
Why login is required in offline mode?

### ISSUE THREAD

**Issue by rohitgr7** [wandb/client#960]
* Weights and Biases version: 0.8.31
* Python version: 3.6.6
* Operating System: Linux

### Description

I need to run wandb in offline mode on Kaggle kernels with no internet access. But whenever I run `wandb.init()` it asks for login key. Why would I need to login in offline mode? I just want the log files. Even if I put a key, it requires the internet to authenticate which is not possible with no internet access.

### What I Did

![image](https://user-images.githubusercontent.com/30778939/79007728-6260ed00-7b79-11ea-9a42-dbe73e80a221.png)

**Comment by vanpelt** [comment]
You can call `wandb.login(key=“X”*40)` or set the WANDB_API_KEY env variable to a 40 character string.  We'll implement a fix to not assert auth when in jupyter / dryrun mode.  You should also specify your username with the `entity` keyword in `wandb.init`, i.e. `wandb.init(entity="my_username", project="my_project")`

**Comment by rohitgr7** [comment]
Thanks!! Working now.
