### ISSUE TITLE
Fastai learner export error while using callback 

### ISSUE THREAD

**Issue by usama13o** [wandb/client#961]
`wandb --version && python --version && uname`

* Weights and Biases version:0.8.31

* Python version:3.6.8

* Operating System: Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-centos-7.7.1908-Core

### Description

I was using the Wandb callback in Fastai library, everything executed well and all logs uploaded fine, but when I tried to export the learner I got a pickle error.

### What I Did
```
AttributeError                            Traceback (most recent call last)
<ipython-input-30-de301e3d8ad1> in <module>
----> 1 learn.export('Unet_baseline____12_0.pkl')

~/.virtualenv/lib64/python3.6/site-packages/fastai/basic_train.py in export(self, file, destroy)
    241             state['data'] = self.data.valid_ds.get_state(**xtra)
    242             state['cls'] = self.__class__
--> 243             try_save(state, self.path, file)
    244         if destroy: self.destroy()
    245 

~/.virtualenv/lib64/python3.6/site-packages/fastai/torch_core.py in try_save(state, path, file)
    414             #To avoid the warning that come from PyTorch about model not being checked
    415             warnings.simplefilter("ignore")
--> 416             torch.save(state, target)
    417     except OSError as e:
    418         raise Exception(f"{e}\n Can't write {path/file}. Pass an absolute writable pathlib obj `fname`.")

~/.virtualenv/lib64/python3.6/site-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    326 
    327     with _open_file_like(f, 'wb') as opened_file:
--> 328         _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
    329 
    330 

~/.virtualenv/lib64/python3.6/site-packages/torch/serialization.py in _legacy_save(obj, f, pickle_module, pickle_protocol)
    399     pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
    400     pickler.persistent_id = persistent_id
--> 401     pickler.dump(obj)
    402 
    403     serialized_storage_keys = sorted(serialized_storages.keys())

AttributeError: Can't pickle local object 'TorchHistory.add_log_hooks_to_pytorch_module.<locals>.<lambda>'
...

**Comment by vanpelt** [comment]
@borisdayma have you seen this error before?

**Comment by borisdayma** [comment]
Hi, which version of fastai and pytorch are you using?

Also do you need to export or just save your model: see [here](https://docs.fast.ai/basic_train.html#Saving-and-loading-models)
When saving, you just have to recreate your learner and load back the model instead of saving full learner state.

If you really want to export your model, try to use `wandb.unwatch(learn.model)` prior to exporting your learner.

**Comment by usama13o** [comment]
Hi 

> When saving, you just have to recreate your learner and load back the model instead of saving full learner state.

that works fine.

but when I try `wandb.unwatchh(learn.model)` I get this 

### 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-bb7ba215153a> in <module>
----> 1 wandb.unwatch(learn.model)
      2 learn.export('Unet_baseline____12.pkl')

~/.virtualenv/lib64/python3.6/site-packages/wandb/__init__.py in unwatch(models)
    180             else:
    181                 for name in model._wandb_hook_names:
--> 182                     run.history.torch.unhook(name)
    183     else:
    184         run.history.torch.unhook_all()

~/.virtualenv/lib64/python3.6/site-packages/wandb/wandb_torch.py in unhook(self, name)
    264 
    265     def unhook(self, name):
--> 266         handle = self._hook_handles.pop(name)
    267         handle.remove()
    268 

TypeError: 'str' object cannot be interpreted as an integer

```

I even tried passing the modules, since I am using a dynamic Unet


```
wandb: WARNING )> model has not been watched

**Comment by usama13o** [comment]
Am using fastai version: 1.0.61.dev0

PyTorch version :1.4.0

**Comment by borisdayma** [comment]
I was not able to recreate the issue.
See [my notebook](https://gist.github.com/borisdayma/0ffa2550dbf45010623f29eb15c3b1e7)

**Comment by vukovicnikola** [comment]
I have the same problem. 
The TorchHistory class inside the WandB callback causes an error when trying to save a PyTorch model via pickle. 
The lambdas should be converted to regular functions for pickle export to work.

**Comment by borisdayma** [comment]
Do you have a reproducible example?
From my notebook [above](https://github.com/wandb/client/issues/961#issuecomment-613109478), I could not reproduce the issue.

**Comment by vukovicnikola** [comment]
Hi Boris. I don't have a notebook, unfortunately, but it's well documented that Python (and torch.save by consequence) won't pickle lambda functions (such as the ones in TorchHistory), which is what causes the errors. Converting the two lines in the wandb TorchHistory class to use a simple function instead of lambda should solve the issue.

From https://docs.python.org/3/library/pickle.html:

```
What can be pickled and unpickled?
The following types can be pickled:

None, True, and False
integers, floating point numbers, complex numbers
strings, bytes, bytearrays
tuples, lists, sets, and dictionaries containing only picklable objects
**functions defined at the top level of a module (using def, not lambda)**
built-in functions defined at the top level of a module
classes that are defined at the top level of a module
instances of such classes whose __dict__ or the result of calling __getstate__() is picklable (see section Pickling Class Instances for details).

```

**Comment by bnapora** [comment]
Having a similar issue using fastai v1:
learn = Learner(data, model, loss_func=crit, callback_fns=[BBMetrics, ShowGraph, WandbCallback], metrics=[voc])
-train model
learn.export() 
AttributeError: Can't pickle local object 'TorchGraph.hook_torch_modules.<locals>.backward_hook'

Only solution is to disable wandb callback when creating learner.  Then can export model without error.

**Comment by vanpelt** [comment]
Hey @bnapora you can set the `WANDB_WATCH=false` environment variable to just diable the gradient logging which is causing the pickle error.  We'll look into making `wandb.watch` properly support pickling.

**Comment by bnapora** [comment]
@vanpelt That worked.  Was able to export model without having to disable the wandb callback

**Comment by ariG23498** [comment]
Hey folks we are closing this issue as the thread has a probable solution listed and is also going stale due to the inactivity.

**Comment by dipta007** [comment]
> Hey @bnapora you can set the `WANDB_WATCH=false` environment variable to just diable the gradient logging which is causing the pickle error. We'll look into making `wandb.watch` properly support pickling.

Has it been done? As I am still getting the same error on wandb with pytorch
