### ISSUE TITLE
Feature request: Renaming project name, runs, and deleting them using code.

### ISSUE THREAD

**Issue by braindotai** [wandb/client#969]
Is it possible to rename project name, runs and also deleting them within our code itself instead of doing that using the UI?

I don't know if its possible right now but haven't found any documentation regarding that.

Thanks.

**Comment by vanpelt** [comment]
You can rename runs using the public api.  Project renaming and deletion is not currently supported via the Python API.  You can do bulk deletion via our UI by expanding the run table and selecting the check boxes.

**Comment by braindotai** [comment]
> You can rename runs using the public api.

An example would be really helpful, cuz I couldn't find it in the documentation.

Thanks

**Comment by vanpelt** [comment]
```python
import wandb
api = wandb.Api()
run = wandb.run("username/project/run_id")
run.name = "My new name"
run.update()
```

**Comment by braindotai** [comment]
Oh thanks, that was helpful.
