### ISSUE TITLE
Opaque restoring of local copy over cloud copies.

### ISSUE THREAD

**Issue by jeroenbe** [wandb/client#970]
* Weights and Biases version: 0.8.31
* Python version: 3.7.6
* Operating System: Darwin --> macOS Catalina (10.15.3)
* Framework: Pytorch (1.4.0)

### Description

I want to load a model from a previous run, but loaded local copy from a different run instead. This caught my attention as I changed model architecture between these runs, causing a Pytorch error. After this I realised I had wrongly loaded runs with the same architecture. 

I should note that adding `replace=True` fixed it (as is noted in [the documentation](https://docs.wandb.com/library/restore#overview)), but this does not seem like appropriate default behaviour. 

### What I Did

I trained/saved 2 models:
```python
model_1.train()
torch.save(model_1.state_dict(), os.path.join(wand.run.dir, 'model.h5')) 
# --> run 2rnc4loc
# local dir: run-20200404_151459-2rnc4loc

model_2.train()
torch.save(model_2.state_dict(), os.path.join(wand.run.dir, 'model.h5')) 
# --> run o49gv8qw
# local dir: run-20200404_151559-o49gv8qw
```

I have loaded my model from the first run, and then proceed to load my model from the second run:
```python
model = Model(**kwargs) # some pytorch model
loc = wandb.restore('model.h5', run_path='jeroenbe/$PROJECT/o49gv8qw')
model.load_state_dict(torch.load(loc.name)) # --> loads from run 2rnc4loc
```

**Comment by vanpelt** [comment]
Calling `wandb.restore` will download the data from cloud storage at the `run_path` specified.  replace=True will just overwrite a local file if it exists.  Any time you call `wandb.init` we create a new local directory.  Does that make sense?

**Comment by jeroenbe** [comment]
So for every run there should be a different local file, right?

If this is the case, I am not sure why above behaviour is happening. I will go through some more code; when I find something I will report here.

**Comment by vanpelt** [comment]
Yeah, each new run should have a fresh local directory.  Let us know what you find, happy to hop on a quick screenshare if that would help.

**Comment by jeroenbe** [comment]
Great, I will close for now. When/should I find something I will reopen. Thanks!
