### ISSUE TITLE
[Question] How to backfit missing config info into past runs

### ISSUE THREAD

**Issue by neomatrix369** [wandb/client#972]
### Description

Often when beginning to track params and metrics for experiments, we end up with more variables/params to track than when we started.

How can I backfit config info (something we usually do via `wandb.config`) into my past runs?

I don't want to delete those runs and re-run the experiments but simply apply the static values they need to be set with so all my runs are consistent.

### What I Did

Nothing so far, apart from the start of this discussion.

**Comment by vanpelt** [comment]
Hey @neomatrix369 you can use the public api to update existing runs: 

https://docs.wandb.com/library/api/examples#update-config-in-a-run

**Comment by neomatrix369** [comment]
> Hey @neomatrix369 you can use the public api to update existing runs:
> 
> https://docs.wandb.com/library/api/examples#update-config-in-a-run

Thanks I'll give it a go.
