### ISSUE TITLE
Web App, report: Scatter Plot selection affects only first run set on other plots

### ISSUE THREAD

**Issue by b0hd4n** [wandb/client#973]
`wandb --version && python --version && uname`

setup 1:
wandb, version 0.8.31
Python 3.6.9
Linux

setup 2:
wandb, version 0.8.30
Python 3.6.8
Linux
### Description

As I noticed, selecting points on Scatter Plot or range on coordinate on Parallel Coordinates leads to disappearing all unselected runs from other Line Plots or Bar Charts on the page or at the report. Which is quite a cool feature, even though I have not find any description of that. Unfortunately, it only works for the first "run set" of all run sets.

It would be great if this kind of hiding other runs on all other visualizations happened to be a feature not a bug: it really helps

### What I Did

- Done:
I select points on a Scatter Plot or a range on Parallel Coordinates

- Observed:
Unselected runs from the first (leftmost) run set are hidden from all other Line Plots and Bar Charts in the current report section. Runs from other run sets are not affected.

- Expected:
All unselected runs are hidden from the Line Plots and Bar Charts in the current report section.

- Steps to observe:
1.  At the [report](https://app.wandb.ai/b0hd4n/multitarget-mt/reports/Report-1-for-github-issue--Vmlldzo4MTYwNg) select couple of points at the scatter plot. This will affect the bar chart to the right. [Image](https://i.ibb.co/CvJzmBJ/report-1.png). All runs from the leftmost run set are/were run with setup 2 from above.
2.  Here is the [copy of the report with run sets order changed](https://app.wandb.ai/b0hd4n/multitarget-mt/reports/Report-2-for-github-issue--Vmlldzo4MTU3Mw). Now the hidden and shown runs are different. [Image](https://i.ibb.co/rcWQ61F/report-2.png). All runs from the leftmost run set are/were run with setup 1 from above

So, it is not an issue with setup 1 or setup 2, but with the order of run sets.

I have a script which runs in parallel with the training process, parses logs and logs them with wandb.log(). 
Jobs are run on two clusters with setups 1 and 2 from above.

**Comment by shawnlewis** [comment]
Yes, this is definitely a feature! When you select on a scatter plot or parallel coordinates plot, your actually adding range selections that say something like "select all points where learning rate is less than 0.9 and greater than 0.8". It's not super clear what to do with multiple run sets. I suppose we could just add the range selection to all of them.

**Comment by b0hd4n** [comment]
> I suppose we could just add the range selection to all of them.

That would be really awesome:) This seems to be the most intuitive way how to deal with run selections and multiple run sets.

Revisiting the documentation I've noticed there is something related to the issue in [cross-project reports:](https://docs.wandb.com/app/pages/reports#cross-project-reports)
> The visualizations in the section pull columns from the first active runset. If you're not seeing the metric you're looking for in the line plot, make sure that the first run set checked in the section has that column available.

However, in the current case it does not matter if the first run set is checked or not. But it may be related to the issue

**Comment by ariG23498** [comment]
Hey @b0hd4n 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
