### ISSUE TITLE
Suggestions for logging experiments with different runs and versions.

### ISSUE THREAD

**Issue by braindotai** [wandb/client#974]
First of all absolutely loving wandb, thanks to the community and all the contributors to make it happen.

Now here's my doubt. Wandb for each project (or experiment in my case) provides logging different runs of a model, so that let's say if we wanna compare some metric for different learning rate, then it's indeed possible. 
And here the map of the project looks like-

**Project ->**
- Run 1,
- Run 2,
- Run 3...

My doubt is if there's a way of logging different models of different versions with their different runs?
What I mean is let's say I'd want to start a project (experiment), where I'd compare different models (possibly with completely different model architecture) final results, and to get final results of each unique model I would run many runs tweaking hyperparameters etc... So that in this case the map of the project might look like-

**Project ->**
- Version 1
    - Run1,
    - Run2,
    - Run3...
- Version 3
    - Run1,
    - Run2,
    - Run3...
- Version 3
    - Run1,
    - Run2,
    - Run3...
- ......

Thanks.

**Comment by neomatrix369** [comment]
> First of all absolutely loving wandb, thanks to the community and all the contributors to make it happen.
> 
....
> **Project ->**
> 
> * Version 1
>   
>   * Run1,
>   * Run2,
>   * Run3...
> * Version 3
>   
>   * Run1,
>   * Run2,
>   * Run3...
> * Version 3
>   
>   * Run1,
>   * Run2,
>   * Run3...
> * ......
> 
> Thanks.

Have you tried using `wandb.save(model_filename)`, it saves your model for upload, versioned with your experiments. You can do this at the end of each experiment. The elaborate steps are:

```
[at the end of each model creation step for each experiment]
[save your model as a pickle file]
wandb.save(model_filename)
```

I hope this helps and what you have been looking for.

**Comment by neomatrix369** [comment]
I add an additional versioning to the model but embedding the model filename with meta-data that makes it easy for me to link the code, the data and experiments but this is optional and may not be required in your case.

**Comment by braindotai** [comment]
@neomatrix369 Thanks for your response, I tried saving model using dill as `dill.dump(model, open('Classifier.model', 'wb'))`,
and then saving using wandb as `wandb.save('Classifier.model')` but got error - `OSError: symbolic link privilege not held`.

**Comment by braindotai** [comment]
I also tried saving only model's state_dict as I'm using pytorch, still got same error.

**Comment by neomatrix369** [comment]
> @neomatrix369 Thanks for your response, I tried saving model using dill as `dill.dump(model, open('Classifier.model', 'wb'))`,
> and then saving using wandb as `wandb.save('Classifier.model')` but got error - `OSError: symbolic link privilege not held`.

Wow, not sure about that, not sure if it is something to do with wandb - did you google the error, its a OS level error. See this https://github.com/explosion/spaCy/issues/895#issuecomment-287781342 

Are you running your commands in administrator mode on Windows?

**Comment by neomatrix369** [comment]
> I also tried saving only model's state_dict as I'm using pytorch, still got same error.

Which explains its not `wandb` client error.

**Comment by braindotai** [comment]
Thanks again, yes running my vscode as administration made wandb able to save without that `OSError`. But still I wonder cuz I can't see anything on the wandb's project ui related to that saved model. So how can I actually use that saved file anyway.

Sorry I'm very noob to wandb.

**Comment by shawnlewis** [comment]
Hi braindotai, you can click on an individual run's name to get to it's "run page". From there you can click on the files tab to see and download the files you saved.

Going back to your original question, I would suggest storing more information about each model in the wandb config: https://docs.wandb.com/library/config

It would make sense to have a config key called "model_type", that you can filter on in the UI.

**Comment by braindotai** [comment]
Thanks to @neomatrix369 and @shawnlewis for solving my issue.
So now I know how to save model's states or better whole model as a pickle file and also filtering the runs based on model name stored in the config file, that was a great obvious idea btw, should have thought in the first place already :)

This does solve my issue 99%.

Thanks again.

**Comment by neomatrix369** [comment]
@shawnlewis did a lot more professional job than me, I learnt from his suggestion. Currently, I store model type differently, will revisit docs to improve my implementation.
