### ISSUE TITLE
Pre-binned histograms corrupted

### ISSUE THREAD

**Issue by chrka** [wandb/client#975]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.32
* Python version: Python 3.6.9 :: Anaconda, Inc.
* Operating System: Linux (Ubuntu 18.04) and macOS (10.15.4)

### Description

Converted data to a histogram using `np.histogram` and logged a a `wandb.Histogram` object from the pre-binned data with `np_histogram`.

The histogram did not show up correctly in the workspace, and when I open the info for the run in the browser, I only get an error.

### What I Did

```python
histogram = np.histogram(rmsse.values, bins=64, range=(0, 5),
                                     density=False)
wandb.log({
                'WRMSSE': wrmsse,
                # 'level_WRMSSE': level_wrmsses,
                'series_RMSSE': wandb.Histogram(np_histogram=histogram)
            })
```

(I'll attach a pull request for a simple fix.)

**Comment by cvphelps** [comment]
Hi Christoffer, thanks for reporting this. @raubitsj is going to take a look.
