### ISSUE TITLE
Possible overlay bug with binary segmentation masks

### ISSUE THREAD

**Issue by surajpaib** [wandb/client#977]
* Weights and Biases version: wandb, version 0.8.32

* Python version: Python 3.6.8

* Operating System: Linux

### Description

Semantic Segmentation usecase for binary image masks feature for 3D volumes in grayscale 

### What I Did
Here's the code to reproduce:

Malfunctioning code:
The dashboard shows overlays only for class with label 0. 

```
import numpy as np
import wandb


wandb.init(project='prototyping', entity='maastro-clinic')


target = np.random.randint(2, size=(32, 256, 256)).astype(np.uint8)
output = np.random.randint(2, size=(32, 256, 256)).astype(np.uint8)
data = np.random.randint(256, size=(32, 256, 256)).astype(np.uint8)


images = []

idx = 0
class_labels = {
    0: 'background',
    1: "nodule"
}

for im, t, o in zip(data, target, output):
    idx += 1        
    images.append(wandb.Image(im, masks={"predictions": {"mask_data": o, "class_labels": class_labels}, \
        "ground_truth": {"mask_data": t, "class_labels": class_labels}}, caption='CT'))


wandb.log({"Predictions": images})

```
Changing the masks to have values from 0 to 2 and adding a class label makes all the 3 overlays work fine.

```
import numpy as np
import wandb


wandb.init(project='prototyping', entity='maastro-clinic')


target = np.random.randint(3, size=(32, 256, 256)).astype(np.uint8)
output = np.random.randint(3, size=(32, 256, 256)).astype(np.uint8)
data = np.random.randint(256, size=(32, 256, 256)).astype(np.uint8)


images = []

idx = 0
class_labels = {
    0: 'background',
    1: "nodule",
    2: "nodule2"

}

for im, t, o in zip(data, target, output):
    idx += 1        
    images.append(wandb.Image(im, masks={"predictions": {"mask_data": o, "class_labels": class_labels}, \
        "ground_truth": {"mask_data": t, "class_labels": class_labels}}, caption='CT'))


wandb.log({"Predictions": images})
```

Am I missing something here?

![image](https://user-images.githubusercontent.com/10467804/79525521-54bcd300-8063-11ea-8d5c-0efd753ea197.png)

**Comment by cvphelps** [comment]
Hi there, it looks like a couple of your overlays are turned off— could you please try clicking background and nodule2?

**Comment by cvphelps** [comment]
Hi Suraj, thanks for your message! @nbardy could you please take a look at this

**Comment by surajpaib** [comment]
Hi @cvphelps, Thanks!

I seem to be having a lot of trouble with using the image masks, there seem to be render issues when I try to upload multiple ( 16 images each step and over 17 steps). 

The first few steps look alright, but when I reach the 12th step the masks are shifted in the wandb dashboard although they are fine when downloaded.  I've reverted to using multiple images for masks for now.

Attached the images for reference.

Let me know if you need any more info

![media_images_Images_19](https://user-images.githubusercontent.com/10467804/79808674-cc924280-836e-11ea-8b37-415c63cad536.png)

![image](https://user-images.githubusercontent.com/10467804/79808698-dfa51280-836e-11ea-9002-da55e5d94543.png)

**Comment by nbardy** [comment]
Hey @surajpaib thanks for reporting these bugs. I want to get both of these fixed for you.

I've got a PR up to fix the binary image masks issue #985. I'm looking the other issue and I'll get a fix out this week.

**Comment by nbardy** [comment]
Could you provide me with a link to the run with the shifted mask issue?

**Comment by surajpaib** [comment]
> i

It's not public atm, would like me to make it public before I share?

**Comment by nbardy** [comment]
If you forward the link to my email we won't need to make it public for me to debug.
nick@wandb.com

**Comment by surajpaib** [comment]
@nbardy Tested the binary masks and works perfectly, haven't been able to check on the other issue yet since it happens when I run consecutive inferences. I'll keep you updated on that! Thanks

**Comment by nbardy** [comment]
@surajpaib I'm going to close this issue. Feel free to open a new ticket if you find the other issue causing problems.
