### ISSUE TITLE
Question - Plotting 3D graphs (scatter plot/lines)

### ISSUE THREAD

**Issue by bsridatta** [wandb/client#980]
I am trying to log 3D plots using scatter plot and line, to get something like in the image below. I have looked at the 3D object type which already exists that take snl, obj and other format data which requires vertices faces and lot more than what 3D lines have. 
I was able to plot just the points by passing [x y z]'s but I mainly want to plot the lines. 

It would be great if I can get some pointers on how to get this to work in Wandb. 
Thanks in advance!

![image](https://user-images.githubusercontent.com/17333185/79618117-7bcde000-8109-11ea-938b-b23ad9b1b0f2.png)

**Comment by bsridatta** [comment]
I have also tried to plot using mayavi to export to obj but it works only if there is 1 element in the .obj. In the sense, multiple groups are not being detected. And also mtl code. Any clue on how to overcome this?

**Comment by ariG23498** [comment]
Hey @bsridatta 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
