### ISSUE TITLE
[Question] How to enable a Feature importance table/graph in W&B Dashboard for custom models/algorithms

### ISSUE THREAD

**Issue by neomatrix369** [wandb/client#981]
### Description

When using scikit-learn models with W&B, we can get access to the Feature Importance list as mentioned here https://docs.wandb.com/library/frameworks/scikit#feature-importances, how can I do that for native/custom runs i.e. CatBoost (on the back of the previous issue raised #965). 

Is it possible to send such a list via the `wandb.log()` command in a way that it receives the whole list each time and then when we compare or combine runs we can see which features have been more influential than the others?

Atm, I could send individual element of the FI list (variable and coefficient) but then the values are all scattered across the param list, it would be great to group these variables under one parameter and be able to track (and graph) the values in this list across different runs.

### What I Did

Checked the docs about FI for Scikitlearn https://docs.wandb.com/library/frameworks/scikit#feature-importances.

**Comment by neomatrix369** [comment]
With regards to #965 I would like to also add, that `catboost` generates a Feature Importance list at the end of each run and it would be great to pass this along to W&B and display the FI list in the dashboard like the natively available `plot_feature_importance()` (for scikitlearn models) would do.

**Comment by neomatrix369** [comment]
Also wanted to add this idea I mentioned on the other issue #971: https://github.com/wandb/client/issues/971#issuecomment-618656302

**Comment by neomatrix369** [comment]
Just for argument sake would this be a good way to track feature importance lists:

```
<end of training>
wandb.log( { {feature1: 0.9},  {feature2: 0.7}, {feature3: 0.8}....{feature50: 0.10} } )
```
How would/could we tell w&b that now using the main dictionary to plot a bar graph, which could lool like this (I'm showing in text form):

```
feature1:  |========= |
feature2:  |=======   |
feature3:  |========  |
.
.
.
feature50: |=         |

**Comment by ariG23498** [comment]
Hey @neomatrix369 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
