### ISSUE TITLE
wandb crashes randomly after running some iterations

### ISSUE THREAD

**Issue by shailesh-agarwal** [wandb/client#986]
`wandb --0.8.32 && python --3.7 && Shailesh`

* Weights and Biases version:0.8.32
* Python version:3.7
* Operating System:macOS

### Description
I am training an ALBERT model of simple transformers. After running a few iterations, wand crashes randomly and shows RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### What I Did
I ran the following commands:
model_albert = ClassificationModel('albert', 'albert-base-v2', num_labels=2, use_cuda=False, args=train_args)

model_albert.train_model(train_df_clean, eval_df=eval_df_clean)

I got the following error after running a few iterations:
~/opt/anaconda3/lib/python3.7/site-packages/wandb/wandb_torch.py in <lambda>(grad)
    254             self.log_tensor_stats(grad.data, name)
    255 
--> 256         handle = var.register_hook(lambda grad: _callback(grad, log_track))
    257         self._hook_handles[name] = handle
    258         return handle

~/opt/anaconda3/lib/python3.7/site-packages/wandb/wandb_torch.py in _callback(grad, log_track)
    252             if not log_track_update(log_track):
    253                 return
--> 254             self.log_tensor_stats(grad.data, name)
    255 
    256         handle = var.register_hook(lambda grad: _callback(grad, log_track))

~/opt/anaconda3/lib/python3.7/site-packages/wandb/wandb_torch.py in log_tensor_stats(self, tensor, name)
    163             tensor = backing_values
    164 
--> 165         flat = tensor.view(-1)
    166 
    167         # For pytorch 0.3 we use unoptimized numpy histograms (detach is new in 0.4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by lukas** [comment]
This is fixed in the upcoming release - thanks for reporting.
