### ISSUE TITLE
re-instantiate wandb logger

### ISSUE THREAD

**Issue by AljoSt** [wandb/client#987]
* Weights and Biases version: 0.8.21
* Python version: 3.7
* Operating System: Ubuntu 18.04

I would like to do two different training runs in a script. When I do that currently, it get the error  `wandb.wandb_config.ConfigError: Attempted to change value of key "experiment_name" from test_01 to test_02`. I've looked into the code and online API, but I could not find anything about terminating/re-instantiating the logger. Is that possible?

**Comment by cvphelps** [comment]
Thanks for your message. Here's a link to the docs for how to launch multiple runs from the same script: https://docs.wandb.com/library/init#how-do-i-launch-multiple-runs-from-one-script

**Comment by ariG23498** [comment]
Hey @AljoSt 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.
